CREATE TABLE [ETL].[ActualVBudgetByWell] (
    [Amount Type]                 NVARCHAR (255) NULL,
    [Date]                        DATETIME       NULL,
    [Cost Center]                 NVARCHAR (255) NULL,
    [Cost Center Number]          FLOAT (53)     NULL,
    [County]                      NVARCHAR (255) NULL,
    [District]                    NVARCHAR (255) NULL,
    [Area]                        NVARCHAR (255) NULL,
    [Field]                       NVARCHAR (255) NULL,
    [Operator]                    NVARCHAR (255) NULL,
    [Gross Oil Production Mbbl]   FLOAT (53)     NULL,
    [Gross NGL Production Mbbl]   FLOAT (53)     NULL,
    [Gross Gas Production MMcf]   FLOAT (53)     NULL,
    [Net Oil Production Mbbl]     FLOAT (53)     NULL,
    [Net NGL Production Mbbl]     FLOAT (53)     NULL,
    [Net Gas Production MMcf]     FLOAT (53)     NULL,
    [Gross Oil Price $/B]         FLOAT (53)     NULL,
    [Gross NGL Price $/B]         FLOAT (53)     NULL,
    [Gross Gas Price $/M]         FLOAT (53)     NULL,
    [Net Oil Sales M$]            FLOAT (53)     NULL,
    [Net NGL Sales M$]            FLOAT (53)     NULL,
    [Net Gas Sales M$]            FLOAT (53)     NULL,
    [Total Net Sales M$]          FLOAT (53)     NULL,
    [Production Taxes M$]         FLOAT (53)     NULL,
    [Ad Valorem Taxes M$]         FLOAT (53)     NULL,
    [Capital Costs M$]            FLOAT (53)     NULL,
    [Abandonment Cost M$]         FLOAT (53)     NULL,
    [Total OPEX]                  FLOAT (53)     NULL,
    [Fixed Opex]                  FLOAT (53)     NULL,
    [Variable Opex]               FLOAT (53)     NULL,
    [Methane Emission Monitoring] FLOAT (53)     NULL,
    [Insurance]                   FLOAT (53)     NULL,
    [Workovers]                   FLOAT (53)     NULL,
    [WI Gas Production MMcf]      FLOAT (53)     NULL,
    [2018 Carry Over Capital ]    FLOAT (53)     NULL
);

