CREATE TABLE [StagePeloton].[wvjobafefinalinvoicecost] (
    [idwell]            VARCHAR (32)  NOT NULL,
    [idrecparent]       VARCHAR (32)  NULL,
    [idrec]             VARCHAR (32)  NOT NULL,
    [amount]            FLOAT (53)    NULL,
    [amountlocal]       FLOAT (53)    NULL,
    [code1]             VARCHAR (100) NULL,
    [code2]             VARCHAR (100) NULL,
    [code3]             VARCHAR (100) NULL,
    [code4]             VARCHAR (100) NULL,
    [code5]             VARCHAR (100) NULL,
    [code6]             VARCHAR (100) NULL,
    [currencycodelocal] VARCHAR (10)  NULL,
    [des]               VARCHAR (100) NULL,
    [finalinvoicedttm]  DATETIME      NULL,
    [invoicerefno]      VARCHAR (50)  NULL,
    [note]              VARCHAR (255) NULL,
    [vendor]            VARCHAR (100) NULL,
    [vendorcode]        VARCHAR (100) NULL,
    [vendorsubcode]     VARCHAR (100) NULL,
    [sysseq]            INT           NULL,
    [syslockmeui]       SMALLINT      NULL,
    [syslockchildrenui] SMALLINT      NULL,
    [syslockme]         SMALLINT      NULL,
    [syslockchildren]   SMALLINT      NULL,
    [syslockdate]       DATETIME      NULL,
    [sysmoddate]        DATETIME      NULL,
    [sysmoduser]        VARCHAR (50)  NULL,
    [syscreatedate]     DATETIME      NULL,
    [syscreateuser]     VARCHAR (50)  NULL,
    [systag]            VARCHAR (255) NULL
);

