CREATE TABLE [StagePeloton].[wvjobreporttimelog] (
    [IDWELL]            VARCHAR (32)   NULL,
    [IDRECPARENT]       VARCHAR (32)   NULL,
    [IDREC]             VARCHAR (32)   NULL,
    [CODE1]             VARCHAR (100)  NULL,
    [CODE2]             VARCHAR (100)  NULL,
    [CODE3]             VARCHAR (100)  NULL,
    [CODE4]             VARCHAR (100)  NULL,
    [COM]               VARCHAR (2000) NULL,
    [DEPTHEND]          FLOAT (53)     NULL,
    [DEPTHSTART]        FLOAT (53)     NULL,
    [DURATION]          FLOAT (53)     NULL,
    [IDRECWELLBORE]     VARCHAR (32)   NULL,
    [IDRECWELLBORETK]   VARCHAR (26)   NULL,
    [IDRECWSSTRING]     VARCHAR (32)   NULL,
    [IDRECWSSTRINGTK]   VARCHAR (26)   NULL,
    [INACTIVE]          SMALLINT       NULL,
    [OPSCATEGORY]       VARCHAR (50)   NULL,
    [REFDERRICK]        VARCHAR (50)   NULL,
    [UNSCHEDTYP]        VARCHAR (100)  NULL,
    [USERTXT1]          VARCHAR (50)   NULL,
    [USERTXT2]          VARCHAR (50)   NULL,
    [SYSSEQ]            INT            NULL,
    [SYSLOCKMEUI]       SMALLINT       NULL,
    [SYSLOCKCHILDRENUI] SMALLINT       NULL,
    [SYSLOCKME]         SMALLINT       NULL,
    [SYSLOCKCHILDREN]   SMALLINT       NULL,
    [SYSLOCKDATE]       DATETIME       NULL,
    [SYSMODDATE]        DATETIME       NULL,
    [SYSMODUSER]        VARCHAR (50)   NULL,
    [SYSCREATEDATE]     DATETIME       NULL,
    [SYSCREATEUSER]     VARCHAR (50)   NULL,
    [SYSTAG]            VARCHAR (255)  NULL,
    [depthbtmactual]    FLOAT (53)     NULL,
    [depthbtmprop]      FLOAT (53)     NULL,
    [depthtopactual]    FLOAT (53)     NULL,
    [depthtopprop]      FLOAT (53)     NULL,
    [des]               VARCHAR (100)  NULL,
    [dttmend]           DATETIME       NULL,
    [dttmpropend]       DATETIME       NULL,
    [dttmstart]         DATETIME       NULL,
    [dttmpropstart]     DATETIME       NULL,
    [sz]                FLOAT (53)     NULL
);

