CREATE TABLE [StagePeloton].[wvjobafecost] (
    [idwell]             VARCHAR (32)   NOT NULL,
    [idrecparent]        VARCHAR (32)   NULL,
    [syscarryfwdp]       SMALLINT       NULL,
    [idrec]              VARCHAR (32)   NOT NULL,
    [afenumbersupprev]   VARCHAR (50)   NULL,
    [amount]             FLOAT (53)     NULL,
    [amountsupp]         FLOAT (53)     NULL,
    [amountsuppdttm]     DATETIME       NULL,
    [code1]              VARCHAR (100)  NULL,
    [code2]              VARCHAR (100)  NULL,
    [code3]              VARCHAR (100)  NULL,
    [code4]              VARCHAR (100)  NULL,
    [code5]              VARCHAR (100)  NULL,
    [code6]              VARCHAR (100)  NULL,
    [des]                VARCHAR (100)  NULL,
    [dttmforecast]       DATETIME       NULL,
    [dttmforecastspend]  DATETIME       NULL,
    [forecast]           FLOAT (53)     NULL,
    [idrecphasecustom]   VARCHAR (32)   NULL,
    [idrecphasecustomtk] VARCHAR (26)   NULL,
    [justification]      VARCHAR (2000) NULL,
    [note]               VARCHAR (255)  NULL,
    [sysseq]             INT            NULL,
    [syslockmeui]        SMALLINT       NULL,
    [syslockchildrenui]  SMALLINT       NULL,
    [syslockme]          SMALLINT       NULL,
    [syslockchildren]    SMALLINT       NULL,
    [syslockdate]        DATETIME       NULL,
    [sysmoddate]         DATETIME       NULL,
    [sysmoduser]         VARCHAR (50)   NULL,
    [syscreatedate]      DATETIME       NULL,
    [syscreateuser]      VARCHAR (50)   NULL,
    [systag]             VARCHAR (255)  NULL
);

