CREATE TABLE [StagePeloton].[wvloccongressional] (
    [idwell]            VARCHAR (32)  NULL,
    [idrecparent]       VARCHAR (32)  NULL,
    [idrec]             VARCHAR (32)  NULL,
    [tblkeyparent]      VARCHAR (52)  NULL,
    [irregularsection]  SMALLINT      NULL,
    [lot]               VARCHAR (50)  NULL,
    [meridian]          VARCHAR (50)  NULL,
    [note]              VARCHAR (255) NULL,
    [range]             FLOAT (53)    NULL,
    [rangedir]          VARCHAR (20)  NULL,
    [section]           FLOAT (53)    NULL,
    [sectionsuffix]     VARCHAR (10)  NULL,
    [township]          FLOAT (53)    NULL,
    [townshipdir]       VARCHAR (20)  NULL,
    [townshipname]      VARCHAR (100) NULL,
    [quarter1]          VARCHAR (50)  NULL,
    [quarter2]          VARCHAR (50)  NULL,
    [quarter3]          VARCHAR (50)  NULL,
    [quarter4]          VARCHAR (50)  NULL,
    [sectiontyp]        VARCHAR (100) NULL,
    [source]            VARCHAR (50)  NULL,
    [syslockmeui]       SMALLINT      NULL,
    [syslockchildrenui] SMALLINT      NULL,
    [syslockme]         SMALLINT      NULL,
    [syslockchildren]   SMALLINT      NULL,
    [syslockdate]       DATETIME      NULL,
    [sysmoddate]        DATETIME      NULL,
    [sysmoduser]        VARCHAR (50)  NULL,
    [syscreatedate]     DATETIME      NULL,
    [syscreateuser]     VARCHAR (50)  NULL,
    [systag]            VARCHAR (255) NULL
);

