CREATE TABLE [StagePeloton].[wvperforation] (
    [idwell]                 VARCHAR (32)   NOT NULL,
    [idrec]                  VARCHAR (32)   NOT NULL,
    [balance]                VARCHAR (20)   NULL,
    [balancepres]            FLOAT (53)     NULL,
    [carrierdes]             VARCHAR (100)  NULL,
    [carriermake]            VARCHAR (100)  NULL,
    [chargemake]             VARCHAR (100)  NULL,
    [chargesz]               FLOAT (53)     NULL,
    [chargetyp]              VARCHAR (100)  NULL,
    [cluserrefno]            FLOAT (53)     NULL,
    [com]                    VARCHAR (2000) NULL,
    [contractor]             VARCHAR (50)   NULL,
    [conveymeth]             VARCHAR (20)   NULL,
    [depthbtm]               FLOAT (53)     NULL,
    [depthcsngcollarref]     FLOAT (53)     NULL,
    [depthfluidafter]        FLOAT (53)     NULL,
    [depthfluidbefore]       FLOAT (53)     NULL,
    [depthgauge]             FLOAT (53)     NULL,
    [depthtop]               FLOAT (53)     NULL,
    [dttm]                   DATETIME       NULL,
    [explosivetyp]           VARCHAR (100)  NULL,
    [fluiddensity]           FLOAT (53)     NULL,
    [fluidtyp]               VARCHAR (100)  NULL,
    [guncentralize]          VARCHAR (50)   NULL,
    [gundes]                 VARCHAR (100)  NULL,
    [gunleftinhole]          SMALLINT       NULL,
    [gunmetallurgy]          VARCHAR (100)  NULL,
    [icondrawshort]          SMALLINT       NULL,
    [idrecjob]               VARCHAR (32)   NULL,
    [idrecjobtk]             VARCHAR (26)   NULL,
    [idreclog]               VARCHAR (32)   NULL,
    [idreclogtk]             VARCHAR (26)   NULL,
    [idrecstring]            VARCHAR (32)   NULL,
    [idrecstringtk]          VARCHAR (26)   NULL,
    [idrecwellbore]          VARCHAR (32)   NULL,
    [idrecwellboretk]        VARCHAR (26)   NULL,
    [idreczoneor]            VARCHAR (32)   NULL,
    [idreczoneortk]          VARCHAR (26)   NULL,
    [intno]                  FLOAT (53)     NULL,
    [orientation]            VARCHAR (20)   NULL,
    [orientmethod]           VARCHAR (20)   NULL,
    [penetrationnom]         FLOAT (53)     NULL,
    [phasing]                FLOAT (53)     NULL,
    [presbh]                 FLOAT (53)     NULL,
    [presbhtyp]              VARCHAR (100)  NULL,
    [presdatum]              FLOAT (53)     NULL,
    [presdesignbh]           FLOAT (53)     NULL,
    [presduringperf]         FLOAT (53)     NULL,
    [preshhsurftompp]        FLOAT (53)     NULL,
    [presfinalsurf]          FLOAT (53)     NULL,
    [presgradientgaugetompp] FLOAT (53)     NULL,
    [presinitsurf]           FLOAT (53)     NULL,
    [presmpp]                FLOAT (53)     NULL,
    [proposed]               SMALLINT       NULL,
    [ratefluidafter]         FLOAT (53)     NULL,
    [ratefluidbefore]        FLOAT (53)     NULL,
    [resulttechnical]        VARCHAR (50)   NULL,
    [resulttechnicaldetail]  VARCHAR (50)   NULL,
    [resulttechnicalnote]    VARCHAR (255)  NULL,
    [shotdensity]            FLOAT (53)     NULL,
    [shotplan]               INT            NULL,
    [shottotal]              INT            NULL,
    [szgun]                  FLOAT (53)     NULL,
    [szholeact]              FLOAT (53)     NULL,
    [szholenom]              FLOAT (53)     NULL,
    [typ]                    VARCHAR (100)  NULL,
    [syslockmeui]            SMALLINT       NULL,
    [syslockchildrenui]      SMALLINT       NULL,
    [syslockme]              SMALLINT       NULL,
    [syslockchildren]        SMALLINT       NULL,
    [syslockdate]            DATETIME       NULL,
    [sysmoddate]             DATETIME       NULL,
    [sysmoduser]             VARCHAR (50)   NULL,
    [syscreatedate]          DATETIME       NULL,
    [syscreateuser]          VARCHAR (50)   NULL,
    [systag]                 VARCHAR (255)  NULL
);

