CREATE TABLE [StagePeloton].[wvwellboredirsurvey] (
    [idwell]             VARCHAR (32)   NOT NULL,
    [idrecparent]        VARCHAR (32)   NULL,
    [idrec]              VARCHAR (32)   NOT NULL,
    [azimuthcorrection]  VARCHAR (100)  NULL,
    [azimuthnorthtyp]    VARCHAR (100)  NULL,
    [azimuthtiein]       FLOAT (53)     NULL,
    [com]                VARCHAR (2000) NULL,
    [convergence]        FLOAT (53)     NULL,
    [declination]        FLOAT (53)     NULL,
    [definitive]         SMALLINT       NULL,
    [depthcorrection]    VARCHAR (100)  NULL,
    [des]                VARCHAR (100)  NULL,
    [dttm]               DATETIME       NULL,
    [ewtiein]            FLOAT (53)     NULL,
    [idrecjob]           VARCHAR (32)   NULL,
    [idrecjobtk]         VARCHAR (26)   NULL,
    [inclinationtiein]   FLOAT (53)     NULL,
    [mdtiein]            FLOAT (53)     NULL,
    [notecorrection]     VARCHAR (255)  NULL,
    [nstiein]            FLOAT (53)     NULL,
    [proposed]           SMALLINT       NULL,
    [tvdtiein]           FLOAT (53)     NULL,
    [validatedbycompany] VARCHAR (100)  NULL,
    [validatedbyname]    VARCHAR (100)  NULL,
    [validateddttm]      DATETIME       NULL,
    [syslockmeui]        SMALLINT       NULL,
    [syslockchildrenui]  SMALLINT       NULL,
    [syslockme]          SMALLINT       NULL,
    [syslockchildren]    SMALLINT       NULL,
    [syslockdate]        DATETIME       NULL,
    [sysmoddate]         DATETIME       NULL,
    [sysmoduser]         VARCHAR (50)   NULL,
    [syscreatedate]      DATETIME       NULL,
    [syscreateuser]      VARCHAR (50)   NULL,
    [systag]             VARCHAR (255)  NULL
);

