CREATE TABLE [StagePeloton].[wvwellbore] (
    [idwell]               VARCHAR (32)   NOT NULL,
    [idrec]                VARCHAR (32)   NOT NULL,
    [com]                  VARCHAR (2000) NULL,
    [county]               VARCHAR (50)   NULL,
    [depthdraw]            FLOAT (53)     NULL,
    [depthstart]           FLOAT (53)     NULL,
    [des]                  VARCHAR (100)  NULL,
    [ewdist]               FLOAT (53)     NULL,
    [ewflag]               VARCHAR (5)    NULL,
    [exclude]              SMALLINT       NULL,
    [fieldcode]            VARCHAR (50)   NULL,
    [fieldname]            VARCHAR (50)   NULL,
    [idrecdirsrvyactual]   VARCHAR (32)   NULL,
    [idrecdirsrvyactualtk] VARCHAR (26)   NULL,
    [idrecdirsrvyprop]     VARCHAR (32)   NULL,
    [idrecdirsrvyproptk]   VARCHAR (26)   NULL,
    [idrecjob]             VARCHAR (32)   NULL,
    [idrecjobtk]           VARCHAR (26)   NULL,
    [idrecparent]          VARCHAR (32)   NULL,
    [idrecparenttk]        VARCHAR (26)   NULL,
    [latitude]             FLOAT (53)     NULL,
    [latlongdatum]         VARCHAR (50)   NULL,
    [latlongsource]        VARCHAR (50)   NULL,
    [legalsurveyloc]       VARCHAR (50)   NULL,
    [legalsurveysubtyp]    VARCHAR (100)  NULL,
    [legalsurveytyp]       VARCHAR (100)  NULL,
    [locationnote]         VARCHAR (255)  NULL,
    [locationref]          VARCHAR (50)   NULL,
    [longitude]            FLOAT (53)     NULL,
    [nsdist]               FLOAT (53)     NULL,
    [nsflag]               VARCHAR (5)    NULL,
    [profiletyp]           VARCHAR (100)  NULL,
    [purpose]              VARCHAR (50)   NULL,
    [stateprov]            VARCHAR (50)   NULL,
    [towndist]             FLOAT (53)     NULL,
    [townflag]             VARCHAR (5)    NULL,
    [townname]             VARCHAR (50)   NULL,
    [townstateprov]        VARCHAR (50)   NULL,
    [usernum1]             FLOAT (53)     NULL,
    [usernum2]             FLOAT (53)     NULL,
    [usernum3]             FLOAT (53)     NULL,
    [usertxt1]             VARCHAR (50)   NULL,
    [usertxt2]             VARCHAR (50)   NULL,
    [usertxt3]             VARCHAR (50)   NULL,
    [utmgridzone]          INT            NULL,
    [utmsource]            VARCHAR (50)   NULL,
    [utmx]                 FLOAT (53)     NULL,
    [utmy]                 FLOAT (53)     NULL,
    [vsdir]                FLOAT (53)     NULL,
    [vsoriginew]           FLOAT (53)     NULL,
    [vsoriginns]           FLOAT (53)     NULL,
    [wellboreida]          VARCHAR (50)   NULL,
    [wellboreidb]          VARCHAR (50)   NULL,
    [wellboreidc]          VARCHAR (50)   NULL,
    [wellboreidd]          VARCHAR (50)   NULL,
    [wellboreide]          VARCHAR (50)   NULL,
    [sysseq]               INT            NULL,
    [syslockmeui]          SMALLINT       NULL,
    [syslockchildrenui]    SMALLINT       NULL,
    [syslockme]            SMALLINT       NULL,
    [syslockchildren]      SMALLINT       NULL,
    [syslockdate]          DATETIME       NULL,
    [sysmoddate]           DATETIME       NULL,
    [sysmoduser]           VARCHAR (50)   NULL,
    [syscreatedate]        DATETIME       NULL,
    [syscreateuser]        VARCHAR (50)   NULL,
    [systag]               VARCHAR (255)  NULL
);

