CREATE TABLE [StagePeloton].[wvzone] (
    [idwell]            VARCHAR (32)   NOT NULL,
    [idrec]             VARCHAR (32)   NOT NULL,
    [com]               VARCHAR (2000) NULL,
    [datasource]        VARCHAR (50)   NULL,
    [depthbtm]          FLOAT (53)     NULL,
    [depthref]          FLOAT (53)     NULL,
    [depthtop]          FLOAT (53)     NULL,
    [dttmzoneabandon]   DATETIME       NULL,
    [dttmzonelic]       DATETIME       NULL,
    [dttmzoneonprod]    DATETIME       NULL,
    [fieldcode]         VARCHAR (50)   NULL,
    [fieldname]         VARCHAR (50)   NULL,
    [iconname]          VARCHAR (255)  NULL,
    [idrecwellbore]     VARCHAR (32)   NULL,
    [idrecwellboretk]   VARCHAR (26)   NULL,
    [objective]         VARCHAR (100)  NULL,
    [unitcode]          VARCHAR (50)   NULL,
    [unitname]          VARCHAR (50)   NULL,
    [usertxt1]          VARCHAR (50)   NULL,
    [usertxt2]          VARCHAR (50)   NULL,
    [usertxt3]          VARCHAR (50)   NULL,
    [usertxt4]          VARCHAR (50)   NULL,
    [usertxt5]          VARCHAR (50)   NULL,
    [usertxt6]          VARCHAR (50)   NULL,
    [zonecode]          VARCHAR (50)   NULL,
    [zoneida]           VARCHAR (50)   NULL,
    [zoneidb]           VARCHAR (50)   NULL,
    [zoneidc]           VARCHAR (50)   NULL,
    [zoneidd]           VARCHAR (50)   NULL,
    [zoneide]           VARCHAR (50)   NULL,
    [zonelicensee]      VARCHAR (50)   NULL,
    [zonelicenseno]     VARCHAR (50)   NULL,
    [zonename]          VARCHAR (50)   NULL,
    [syslockmeui]       SMALLINT       NULL,
    [syslockchildrenui] SMALLINT       NULL,
    [syslockme]         SMALLINT       NULL,
    [syslockchildren]   SMALLINT       NULL,
    [syslockdate]       DATETIME       NULL,
    [sysmoddate]        DATETIME       NULL,
    [sysmoduser]        VARCHAR (50)   NULL,
    [syscreatedate]     DATETIME       NULL,
    [syscreateuser]     VARCHAR (50)   NULL,
    [systag]            VARCHAR (255)  NULL
);

