CREATE TABLE [TEMP].[ARSYSCOL] (
    [TABLESET]       VARCHAR (12)  NOT NULL,
    [TBL_ALIAS]      VARCHAR (20)  NOT NULL,
    [COL_NAME]       VARCHAR (30)  NOT NULL,
    [EDITABLE]       VARCHAR (1)   NULL,
    [PRIMARYKEY]     VARCHAR (1)   NULL,
    [MAKEKEY]        VARCHAR (30)  NULL,
    [DESCRIPTN]      VARCHAR (254) NULL,
    [UNITTYPE]       SMALLINT      NULL,
    [COMBRULE]       VARCHAR (60)  NULL,
    [USER_REQUESTED] VARCHAR (1)   NULL
);

