CREATE TABLE [StageDI].[Completions] (
    [UID]                INT            NULL,
    [UIDParent]          INT            NULL,
    [CompletionID]       INT            NULL,
    [WellboreID]         INT            NULL,
    [Governmentid]       BIGINT         NULL,
    [StateProvince]      VARCHAR (209)  NULL,
    [County]             VARCHAR (191)  NULL,
    [CompletionDate]     DATETIME       NULL,
    [CreatedDate]        DATETIME       NULL,
    [UpdatedDate]        DATETIME       NULL,
    [DeletedDate]        DATETIME       NULL,
    [CompletionEventID]  INT            NULL,
    [PermitDate]         DATETIME       NULL,
    [CompletionEvent]    INT            NULL,
    [CompletionSequence] SMALLINT       NULL,
    [CompletionNumber]   SMALLINT       NULL,
    [TopDepth]           REAL           NULL,
    [BaseDepth]          REAL           NULL,
    [PermitNumber]       VARCHAR (24)   NULL,
    [Source]             VARCHAR (67)   NULL,
    [Formation]          VARCHAR (82)   NULL,
    [Type]               VARCHAR (22)   NULL,
    [Method]             VARCHAR (20)   NULL,
    [Remark]             VARCHAR (2117) NULL,
    [DepthUOM]           VARCHAR (60)   NULL,
    [Region]             VARCHAR (6)    NULL,
    [Country]            VARCHAR (70)   NULL,
    [Field]              VARCHAR (64)   NULL,
    [BasinName]          VARCHAR (68)   NULL,
    [District]           VARCHAR (68)   NULL,
    [Section]            VARCHAR (28)   NULL,
    [Township]           SMALLINT       NULL,
    [TownshipDirection]  VARCHAR (17)   NULL,
    [Range]              SMALLINT       NULL,
    [RangeDirection]     VARCHAR (68)   NULL,
    [Abstract]           VARCHAR (79)   NULL
);

