CREATE TABLE [StageDI].[Perforations] (
    [PerforationID]       INT            NULL,
    [CompletionID]        INT            NULL,
    [GovernmentID]        BIGINT         NULL,
    [WellboreID]          INT            NULL,
    [UpdatedDate]         DATETIME       NULL,
    [DeletedDate]         DATETIME       NULL,
    [StateProvince]       VARCHAR (13)   NULL,
    [County]              VARCHAR (34)   NULL,
    [CreatedDate]         DATETIME       NULL,
    [Source]              VARCHAR (6)    NULL,
    [TopDepth]            REAL           NULL,
    [BaseDepth]           REAL           NULL,
    [Formation]           VARCHAR (82)   NULL,
    [PerforationDate]     DATETIME       NULL,
    [PerforationDensity]  VARCHAR (18)   NULL,
    [PerforationDiameter] VARCHAR (19)   NULL,
    [PerforationPhase]    VARCHAR (8000) NULL,
    [PerforationSequence] SMALLINT       NULL,
    [OpenHole]            BIT            NULL,
    [PerforationRemark]   VARCHAR (147)  NULL,
    [CementSacks]         SMALLINT       NULL,
    [IsolationDate]       DATETIME       NULL,
    [IsolationMethod]     VARCHAR (8000) NULL,
    [IsolationRemark]     VARCHAR (8000) NULL,
    [Region]              VARCHAR (6)    NULL,
    [Country]             VARCHAR (6)    NULL,
    [Field]               VARCHAR (64)   NULL,
    [BasinName]           VARCHAR (68)   NULL,
    [District]            VARCHAR (68)   NULL
);

