CREATE TABLE [StageDI].[Permits] (
    [PermitID]                 INT           NULL,
    [SubmittedDate]            DATETIME      NULL,
    [OrigApprovedDate]         DATETIME      NULL,
    [AmendmentFiledDate]       DATETIME      NULL,
    [ApprovedDate]             DATETIME      NULL,
    [ExpiredDate]              DATETIME      NULL,
    [API10]                    VARCHAR (30)  NULL,
    [StateProvince]            VARCHAR (7)   NULL,
    [CountyParish]             VARCHAR (39)  NULL,
    [LeaseName]                VARCHAR (114) NULL,
    [OperatorAlias]            VARCHAR (129) NULL,
    [PermitType]               VARCHAR (144) NULL,
    [WellType]                 VARCHAR (93)  NULL,
    [DrillType]                VARCHAR (81)  NULL,
    [Section]                  VARCHAR (57)  NULL,
    [Township]                 VARCHAR (57)  NULL,
    [Range]                    VARCHAR (21)  NULL,
    [Block]                    VARCHAR (30)  NULL,
    [Survey]                   VARCHAR (126) NULL,
    [Abstract]                 VARCHAR (123) NULL,
    [CreatedDate]              DATETIME      NULL,
    [UpdatedDate]              DATETIME      NULL,
    [DeletedDate]              DATETIME      NULL,
    [API12]                    VARCHAR (114) NULL,
    [WGID]                     VARCHAR (114) NULL,
    [PermitNumber]             VARCHAR (114) NULL,
    [OFSRegion]                VARCHAR (114) NULL,
    [District]                 VARCHAR (42)  NULL,
    [ReportedOperator]         VARCHAR (114) NULL,
    [WellNumber]               VARCHAR (114) NULL,
    [LeaseNumber]              VARCHAR (114) NULL,
    [Field]                    VARCHAR (114) NULL,
    [Formation]                VARCHAR (255) NULL,
    [PermitDepth]              VARCHAR (123) NULL,
    [PermitDepthUOM]           VARCHAR (96)  NULL,
    [TrueVerticalDepth]        VARCHAR (129) NULL,
    [TrueVerticalDepthUOM]     VARCHAR (99)  NULL,
    [PermitStatus]             VARCHAR (129) NULL,
    [WellStatus]               VARCHAR (54)  NULL,
    [ContactName]              VARCHAR (81)  NULL,
    [ContactPhone]             VARCHAR (66)  NULL,
    [OperatorAddress]          VARCHAR (174) NULL,
    [OperatorCity]             VARCHAR (180) NULL,
    [OperatorState]            VARCHAR (180) NULL,
    [OperatorZip]              VARCHAR (180) NULL,
    [OperatorCity30mi]         VARCHAR (156) NULL,
    [OperatorCity50mi]         VARCHAR (144) NULL,
    [H2SArea]                  VARCHAR (123) NULL,
    [SurfaceLatitudeWGS84]     VARCHAR (114) NULL,
    [SurfaceLongitudeWGS84]    VARCHAR (93)  NULL,
    [BottomHoleLatitudeWGS84]  VARCHAR (87)  NULL,
    [BottomHoleLongitudeWGS84] VARCHAR (63)  NULL,
    [TellurianUpdatedDate]     DATETIME      NULL
);

