CREATE TABLE [StageDI].[ProducingEntities] (
    [EntityId]             INT           NOT NULL,
    [WellId]               INT           NULL,
    [ProdType]             VARCHAR (22)  NULL,
    [State]                VARCHAR (10)  NULL,
    [ApiNo]                VARCHAR (30)  NULL,
    [Reservoir]            VARCHAR (64)  NULL,
    [County]               VARCHAR (42)  NULL,
    [CurrOperName]         VARCHAR (76)  NULL,
    [Basin]                VARCHAR (68)  NULL,
    [DrillType]            VARCHAR (68)  NULL,
    [CommingleDate]        DATETIME      NULL,
    [CompDate]             DATETIME      NULL,
    [SpudDate]             DATETIME      NULL,
    [CreatedDate]          DATETIME      NULL,
    [UpdatedDate]          DATETIME      NULL,
    [DeletedDate]          DATETIME      NULL,
    [District]             VARCHAR (76)  NULL,
    [PdenType]             VARCHAR (76)  NULL,
    [Country]              VARCHAR (76)  NULL,
    [PdenName]             VARCHAR (66)  NULL,
    [Offshore]             VARCHAR (68)  NULL,
    [Field]                VARCHAR (70)  NULL,
    [LeaseNo]              VARCHAR (70)  NULL,
    [CommingleNo]          VARCHAR (54)  NULL,
    [CountyId]             VARCHAR (64)  NULL,
    [WellNo]               VARCHAR (26)  NULL,
    [CurrOperNo]           VARCHAR (18)  NULL,
    [Status]               VARCHAR (76)  NULL,
    [ElevationType]        VARCHAR (76)  NULL,
    [LocRemark]            VARCHAR (78)  NULL,
    [Location]             VARCHAR (80)  NULL,
    [Section]              VARCHAR (78)  NULL,
    [QtrQtr]               VARCHAR (72)  NULL,
    [Merid]                VARCHAR (80)  NULL,
    [OcsArea]              VARCHAR (72)  NULL,
    [CommonOperName]       VARCHAR (76)  NULL,
    [LesseeAvail]          VARCHAR (78)  NULL,
    [PgcArea]              VARCHAR (78)  NULL,
    [QuadName]             VARCHAR (66)  NULL,
    [Abstract]             VARCHAR (58)  NULL,
    [Survey]               VARCHAR (90)  NULL,
    [TxBlock]              VARCHAR (62)  NULL,
    [TxSec]                VARCHAR (86)  NULL,
    [SubSurvey]            VARCHAR (66)  NULL,
    [TxScrap]              VARCHAR (80)  NULL,
    [FieldNo]              VARCHAR (52)  NULL,
    [ReportedOperName]     VARCHAR (80)  NULL,
    [Formation]            VARCHAR (64)  NULL,
    [Twp]                  VARCHAR (64)  NULL,
    [Rng]                  VARCHAR (64)  NULL,
    [AllocPlus]            VARCHAR (64)  NULL,
    [Geom]                 VARCHAR (100) NULL,
    [Elevation]            VARCHAR (100) NULL,
    [CurrOperId]           VARCHAR (100) NULL,
    [TotalDepth]           VARCHAR (100) NULL,
    [UpperPerf]            VARCHAR (100) NULL,
    [LowerPerf]            VARCHAR (100) NULL,
    [LiqGrav]              VARCHAR (100) NULL,
    [GasGrav]              VARCHAR (100) NULL,
    [Latitude]             VARCHAR (100) NULL,
    [Longitude]            VARCHAR (100) NULL,
    [RkbElev]              VARCHAR (100) NULL,
    [WaterDepth]           VARCHAR (100) NULL,
    [ResVertDepth]         REAL          NULL,
    [MaxVertDepth]         REAL          NULL,
    [LatitudeBotm]         REAL          NULL,
    [LongitudeBotm]        REAL          NULL,
    [LatitudeEx1]          REAL          NULL,
    [LongitudeEx1]         REAL          NULL,
    [LeaseId]              BIGINT        NULL,
    [PerfIntervalLength]   REAL          NULL,
    [IsDeleted]            REAL          NULL,
    [TellurianUpdatedDate] DATETIME      NULL,
    CONSTRAINT [PK_ProducingEntites_EntityID] PRIMARY KEY CLUSTERED ([EntityId] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);


GO
CREATE NONCLUSTERED INDEX [idx_producingentities_apino]
    ON [StageDI].[ProducingEntities]([ApiNo] ASC) WITH (STATISTICS_NORECOMPUTE = ON);

