CREATE TABLE [StageDI].[WellBores] (
    [UID]                   INT            NULL,
    [UIDParent]             INT            NULL,
    [WellID]                INT            NULL,
    [WellboreID]            INT            NULL,
    [GovernmentID]          VARCHAR (315)  NULL,
    [WellboreName]          VARCHAR (199)  NULL,
    [StateProvince]         VARCHAR (191)  NULL,
    [County]                VARCHAR (80)   NULL,
    [CurrentStatusDate]     DATETIME       NULL,
    [AbandonmentDate]       DATETIME       NULL,
    [CompletionDate]        DATETIME       NULL,
    [FinalDrillDate]        DATETIME       NULL,
    [OnProductionDate]      DATETIME       NULL,
    [RigOnsiteDate]         DATETIME       NULL,
    [RigReleaseDate]        DATETIME       NULL,
    [SpudDate]              DATETIME       NULL,
    [CreatedDate]           DATETIME       NULL,
    [UpdatedDate]           DATETIME       NULL,
    [DeletedDate]           DATETIME       NULL,
    [WGS84Latitude]         REAL           NULL,
    [WGS84Longitude]        REAL           NULL,
    [DepthDatumElev]        REAL           NULL,
    [CasingFlangeElev]      REAL           NULL,
    [DerrickFloorElevation] REAL           NULL,
    [KellyBushingElevation] REAL           NULL,
    [RotaryTableElev]       REAL           NULL,
    [KickoffPointDepth]     REAL           NULL,
    [TotalDepth]            REAL           NULL,
    [TrueVerticalDepth]     REAL           NULL,
    [LoggersTotalDepth]     REAL           NULL,
    [WhipstockDepth]        VARCHAR (90)   NULL,
    [DrillerTotalDepth]     VARCHAR (16)   NULL,
    [PlugbackDepth]         INT            NULL,
    [WellboreNumber]        SMALLINT       NULL,
    [WellboreType]          VARCHAR (62)   NULL,
    [CurrentStatus]         VARCHAR (27)   NULL,
    [CurrentClassification] VARCHAR (36)   NULL,
    [DepthUOM]              VARCHAR (6)    NULL,
    [ElevUOM]               VARCHAR (56)   NULL,
    [DepthDatum]            VARCHAR (7)    NULL,
    [Source]                VARCHAR (6)    NULL,
    [FluidType]             VARCHAR (69)   NULL,
    [ProfileType]           VARCHAR (3)    NULL,
    [FormationAtTD]         VARCHAR (123)  NULL,
    [Remarks]               VARCHAR (2117) NULL,
    [Region]                VARCHAR (30)   NULL,
    [Country]               VARCHAR (9)    NULL,
    [Field]                 VARCHAR (96)   NULL,
    [BasinName]             VARCHAR (102)  NULL,
    [District]              VARCHAR (102)  NULL,
    [Section]               VARCHAR (42)   NULL,
    [Township]              REAL           NULL,
    [TownshipDirection]     VARCHAR (20)   NULL,
    [Range]                 REAL           NULL,
    [RangeDirection]        VARCHAR (50)   NULL,
    [Abstract]              VARCHAR (20)   NULL,
    [Formation]             VARCHAR (123)  NULL,
    [TellurianUpdatedDate]  DATETIME       NULL
);

