CREATE TABLE [StageDI].[WellOrigins] (
    [UID]                   INT           NULL,
    [GovernmentID]          BIGINT        NULL,
    [County]                VARCHAR (90)  NULL,
    [FluidType]             VARCHAR (69)  NULL,
    [LeaseName]             VARCHAR (111) NULL,
    [OriginalOperator]      VARCHAR (96)  NULL,
    [ProvinceState]         VARCHAR (75)  NULL,
    [WellName]              VARCHAR (162) NULL,
    [WellNumber]            VARCHAR (126) NULL,
    [CurrentStatusDate]     DATETIME      NULL,
    [LicenseDate]           DATETIME      NULL,
    [OnProductionDate]      DATETIME      NULL,
    [SpudDate]              DATETIME      NULL,
    [ConfidentialDate]      DATETIME      NULL,
    [CreatedDate]           DATETIME      NULL,
    [UpdatedDate]           DATETIME      NULL,
    [DeletedDate]           DATETIME      NULL,
    [Source]                VARCHAR (105) NULL,
    [LeaseNumber]           VARCHAR (102) NULL,
    [PermitNumber]          VARCHAR (102) NULL,
    [Wgs84Latitude]         REAL          NULL,
    [Wgs84Longitude]        REAL          NULL,
    [Section]               VARCHAR (10)  NULL,
    [Township]              REAL          NULL,
    [TownshipDirection]     VARCHAR (5)   NULL,
    [Range]                 REAL          NULL,
    [RangeDirection]        VARCHAR (5)   NULL,
    [Abstract]              VARCHAR (20)  NULL,
    [CurrentOperator]       VARCHAR (147) NULL,
    [Country]               VARCHAR (87)  NULL,
    [Region]                VARCHAR (84)  NULL,
    [Field]                 VARCHAR (96)  NULL,
    [Basin]                 VARCHAR (114) NULL,
    [District]              VARCHAR (102) NULL,
    [Environment]           VARCHAR (102) NULL,
    [InitialClassification] VARCHAR (102) NULL,
    [CurrentStatus]         VARCHAR (102) NULL,
    [ElevRefDatum]          VARCHAR (39)  NULL,
    [ElevRefDatumepsgCode]  VARCHAR (27)  NULL,
    [GroundElev]            VARCHAR (27)  NULL,
    [WaterDepthDatum]       VARCHAR (27)  NULL,
    [WaterDepth]            VARCHAR (27)  NULL,
    [Confidential]          VARCHAR (5)   NULL,
    [Remark]                SMALLINT      NULL,
    [DepthUom]              VARCHAR (9)   NULL,
    [ElevUom]               VARCHAR (9)   NULL,
    [Formation]             VARCHAR (105) NULL,
    [TellurianUpdatedDate]  DATETIME      NULL
);

