CREATE TABLE [StageDI].[WellRollups] (
    [AAPGGeologicProvince]                            VARCHAR (38)  NULL,
    [API10]                                           VARCHAR (10)  NULL,
    [API12]                                           VARCHAR (12)  NULL,
    [API14]                                           VARCHAR (14)  NOT NULL,
    [Abstract]                                        VARCHAR (20)  NULL,
    [AvgDistanceFromBaseOfZone]                       REAL          NULL,
    [AvgDistanceFromTopOfZone]                        REAL          NULL,
    [Block]                                           VARCHAR (20)  NULL,
    [BottomHoleLatitudeWGS84]                         REAL          NULL,
    [BottomHoleLongitudeWGS84]                        REAL          NULL,
    [CompletionCountAPI10]                            INT           NULL,
    [CompletionDate]                                  VARCHAR (20)  NULL,
    [CompletionDateSource]                            VARCHAR (16)  NULL,
    [Country]                                         VARCHAR (2)   NULL,
    [CountyParish]                                    VARCHAR (42)  NULL,
    [CreatedDate]                                     VARCHAR (24)  NULL,
    [CumBCFGE]                                        REAL          NULL,
    [CumBOE]                                          REAL          NULL,
    [CumGOR]                                          REAL          NULL,
    [CumGas]                                          REAL          NULL,
    [CumMMCFGE]                                       REAL          NULL,
    [CumOil]                                          REAL          NULL,
    [CumWater]                                        REAL          NULL,
    [DIBasin]                                         VARCHAR (24)  NULL,
    [DILandingZone]                                   VARCHAR (28)  NULL,
    [DILandingZoneSource]                             VARCHAR (11)  NULL,
    [DILateralLength]                                 REAL          NULL,
    [DILateralLengthSource]                           VARCHAR (20)  NULL,
    [DIPlay]                                          VARCHAR (29)  NULL,
    [DISubplay]                                       VARCHAR (30)  NULL,
    [DailyGas]                                        REAL          NULL,
    [DailyOil]                                        REAL          NULL,
    [DeepestPerforation]                              REAL          NULL,
    [DeletedDate]                                     DATETIME2 (7) NULL,
    [District]                                        VARCHAR (11)  NULL,
    [DrillType]                                       VARCHAR (1)   NULL,
    [EURBEGasPer1000BBLFluid]                         REAL          NULL,
    [EURBEGasPer1MMLbsProppant]                       REAL          NULL,
    [EURBEGasPerPerforatedFt]                         REAL          NULL,
    [EURBEOilPer1000BBLFluid]                         REAL          NULL,
    [EURBEOilPer1MMLbsProppant]                       REAL          NULL,
    [EURBEOilPerPerforatedFt]                         REAL          NULL,
    [EURBFactorBE]                                    REAL          NULL,
    [EURBFactorFull]                                  REAL          NULL,
    [EURCalcDate]                                     VARCHAR (20)  NULL,
    [EUREndDateBE]                                    VARCHAR (20)  NULL,
    [EUREndDateFull]                                  VARCHAR (20)  NULL,
    [EURFinalRateBE]                                  REAL          NULL,
    [EURFinalRateFull]                                REAL          NULL,
    [EURGasBE]                                        REAL          NULL,
    [EURGasDeltaBE]                                   REAL          NULL,
    [EURGasDeltaPercentBE]                            REAL          NULL,
    [EURGasFull]                                      REAL          NULL,
    [EURInitialDeclineBE]                             REAL          NULL,
    [EURInitialDeclineFull]                           REAL          NULL,
    [EURInitialRateBE]                                REAL          NULL,
    [EUROilBE]                                        REAL          NULL,
    [EUROilDeltaBE]                                   REAL          NULL,
    [EUROilDeltaPercentBE]                            REAL          NULL,
    [EUROilFull]                                      REAL          NULL,
    [EURPrimaryProduct]                               VARCHAR (3)   NULL,
    [Elevation]                                       REAL          NULL,
    [ElevationType]                                   VARCHAR (112) NULL,
    [EndDateFirstTreatmentJob]                        DATETIME2 (7) NULL,
    [ExtFormationThicknessMean]                       REAL          NULL,
    [Field]                                           VARCHAR (63)  NULL,
    [First12BOE]                                      REAL          NULL,
    [First12BOEPer1000BBLFluid]                       REAL          NULL,
    [First12BOEPer1MMLbsProppant]                     REAL          NULL,
    [First12BOEPerPerforatedFt]                       REAL          NULL,
    [First12Gas]                                      REAL          NULL,
    [First12GasPer1000BBLFluid]                       REAL          NULL,
    [First12GasPer1MMLbsProppant]                     REAL          NULL,
    [First12GasPerPerforatedFt]                       REAL          NULL,
    [First12MMCFGE]                                   REAL          NULL,
    [First12Oil]                                      REAL          NULL,
    [First12OilPer1000BBLFluid]                       REAL          NULL,
    [First12OilPer1MMLbsProppant]                     REAL          NULL,
    [First12OilPerPerforatedFt]                       REAL          NULL,
    [First12Water]                                    REAL          NULL,
    [First24BOE]                                      REAL          NULL,
    [First24Gas]                                      REAL          NULL,
    [First24MMCFGE]                                   REAL          NULL,
    [First24Oil]                                      REAL          NULL,
    [First24Water]                                    REAL          NULL,
    [First60BOE]                                      REAL          NULL,
    [First60Gas]                                      REAL          NULL,
    [First60MMCFGE]                                   REAL          NULL,
    [First60Oil]                                      REAL          NULL,
    [First60Water]                                    REAL          NULL,
    [First6BOE]                                       REAL          NULL,
    [First6BOEPer1000BBLFluid]                        REAL          NULL,
    [First6BOEPer1MMLbsProppant]                      REAL          NULL,
    [First6BOEPerPerforatedFt]                        REAL          NULL,
    [First6Gas]                                       REAL          NULL,
    [First6GasPer1000BBLFluid]                        REAL          NULL,
    [First6GasPer1MMLbsProppant]                      REAL          NULL,
    [First6GasPerPerforatedFt]                        REAL          NULL,
    [First6Oil]                                       REAL          NULL,
    [First6OilPer1000BBLFluid]                        REAL          NULL,
    [First6OilPer1MMLbsProppant]                      REAL          NULL,
    [First6OilPerPerforatedFt]                        REAL          NULL,
    [First6Water]                                     REAL          NULL,
    [FirstMonthGas]                                   REAL          NULL,
    [FirstMonthOil]                                   REAL          NULL,
    [FirstMonthWater]                                 REAL          NULL,
    [FirstProdDate]                                   VARCHAR (20)  NULL,
    [FirstReportedTestType]                           VARCHAR (20)  NULL,
    [FirstTestCasingPressure]                         REAL          NULL,
    [FirstTestChokeSize]                              VARCHAR (27)  NULL,
    [FirstTestFlowingTubingPressure]                  REAL          NULL,
    [FirstTestGOR]                                    REAL          NULL,
    [FirstTestGasGravity]                             REAL          NULL,
    [FirstTestGasVolume]                              REAL          NULL,
    [FirstTestHoursTested]                            REAL          NULL,
    [FirstTestOilGravity]                             REAL          NULL,
    [FirstTestOilVolume]                              REAL          NULL,
    [FirstTestProductionMethod]                       VARCHAR (26)  NULL,
    [FirstTestWaterVolume]                            REAL          NULL,
    [FirstWellTestDate]                               VARCHAR (20)  NULL,
    [FluidPerPerforatedFootFirstTreatmentJob]         REAL          NULL,
    [FootageInLandingZone]                            REAL          NULL,
    [FracVendor]                                      VARCHAR (51)  NULL,
    [GasGatherer]                                     VARCHAR (45)  NULL,
    [GasGravity]                                      REAL          NULL,
    [GasRRRBE]                                        REAL          NULL,
    [GasRRRFull]                                      REAL          NULL,
    [GrossPerforatedInterval]                         REAL          NULL,
    [GrossPerforatedIntervalMultipleProdEntities]     REAL          NULL,
    [GrossPerforationIntervalSource]                  VARCHAR (20)  NULL,
    [GroundElevation]                                 REAL          NULL,
    [HasDigitizedTrajectory]                          VARCHAR (5)   NULL,
    [HasFilingDocument]                               VARCHAR (5)   NULL,
    [HasWellLogLAS]                                   VARCHAR (5)   NULL,
    [HasWellLogRaster]                                VARCHAR (5)   NULL,
    [HorizontalLength]                                REAL          NULL,
    [HorizontalWellboreLength]                        REAL          NULL,
    [LASMnemonics]                                    VARCHAR (500) NULL,
    [Last12Gas]                                       REAL          NULL,
    [Last12Oil]                                       REAL          NULL,
    [Last12Water]                                     REAL          NULL,
    [Last12Yield]                                     REAL          NULL,
    [LastProdDate]                                    VARCHAR (141) NULL,
    [LastTestType]                                    VARCHAR (20)  NULL,
    [LastWellTestDate]                                VARCHAR (20)  NULL,
    [LateralLength]                                   REAL          NULL,
    [LatestGOR]                                       REAL          NULL,
    [LatestGas]                                       REAL          NULL,
    [LatestOil]                                       REAL          NULL,
    [LatestWater]                                     REAL          NULL,
    [LatestWhsip]                                     REAL          NULL,
    [LatestYield]                                     REAL          NULL,
    [LeaseName]                                       VARCHAR (64)  NULL,
    [LowerPerforation]                                REAL          NULL,
    [MaxInjectionPressureFirstTreatmentJob]           VARCHAR (7)   NULL,
    [MaxInjectionRateFirstTreatmentJob]               REAL          NULL,
    [MeasuredDepth]                                   REAL          NULL,
    [MonthsProduced]                                  REAL          NULL,
    [OCSArea]                                         VARCHAR (23)  NULL,
    [OilGatherer]                                     VARCHAR (46)  NULL,
    [OilGravity]                                      REAL          NULL,
    [OilRRRBE]                                        REAL          NULL,
    [OilRRRFull]                                      REAL          NULL,
    [OperatorAlias]                                   VARCHAR (75)  NULL,
    [OperatorCompanyName]                             VARCHAR (75)  NULL,
    [OperatorTicker]                                  VARCHAR (8)   NULL,
    [PGCArea]                                         VARCHAR (9)   NULL,
    [PeakBOE]                                         REAL          NULL,
    [PeakBOEMonthNo]                                  REAL          NULL,
    [PeakBOEPer1000BBLFluid]                          REAL          NULL,
    [PeakBOEPer1MMLbsProppant]                        REAL          NULL,
    [PeakBOEPerPerforatedFt]                          REAL          NULL,
    [PeakGas]                                         REAL          NULL,
    [PeakGasMonthNo]                                  REAL          NULL,
    [PeakGasPer1000BBLFluid]                          REAL          NULL,
    [PeakGasPer1MMLbsProppant]                        REAL          NULL,
    [PeakGasPerPerforatedFt]                          REAL          NULL,
    [PeakMMCFGE]                                      REAL          NULL,
    [PeakMMCFGEMonthNo]                               REAL          NULL,
    [PeakOil]                                         REAL          NULL,
    [PeakOilMonthNo]                                  REAL          NULL,
    [PeakOilPer1000BBLFluid]                          REAL          NULL,
    [PeakOilPer1MMLbsProppant]                        REAL          NULL,
    [PeakOilPerPerforatedFt]                          REAL          NULL,
    [PercentInLandingZone]                            REAL          NULL,
    [PlayAssessmentBasin]                             VARCHAR (22)  NULL,
    [PracIPBOE]                                       REAL          NULL,
    [PracIPCFGED]                                     REAL          NULL,
    [PracIPGasDaily]                                  REAL          NULL,
    [PracIPOilDaily]                                  REAL          NULL,
    [Prior12Gas]                                      REAL          NULL,
    [Prior12Oil]                                      REAL          NULL,
    [Prior12Water]                                    REAL          NULL,
    [ProducingEntityCount]                            INT           NULL,
    [ProducingEntityID]                               VARCHAR (255) NULL,
    [ProducingEntityLeaseNumber]                      VARCHAR (17)  NULL,
    [ProducingEntityType]                             VARCHAR (8)   NULL,
    [ProducingReservoir]                              VARCHAR (50)  NULL,
    [ProductionType]                                  VARCHAR (23)  NULL,
    [ProppantConcentrationLbsPerGalFirstTreatmentJob] REAL          NULL,
    [ProppantPerHorizontalFootFirstTreatmentJob]      REAL          NULL,
    [ProppantPerPerforatedFootFirstTreatmentJob]      REAL          NULL,
    [QualifierFirstTreatmentJob]                      VARCHAR (15)  NULL,
    [QuarterQuarter]                                  VARCHAR (10)  NULL,
    [Range]                                           VARCHAR (10)  NULL,
    [ReportedOperator]                                VARCHAR (75)  NULL,
    [SecondMonthGOR]                                  REAL          NULL,
    [SecondMonthYield]                                REAL          NULL,
    [Section]                                         VARCHAR (20)  NULL,
    [ShallowestPerforation]                           REAL          NULL,
    [SpudDate]                                        DATETIME2 (7) NULL,
    [SpudDateSource]                                  VARCHAR (8)   NULL,
    [StageCountFirstTreatmentJob]                     VARCHAR (20)  NULL,
    [StartDateFirstTreatmentJob]                      VARCHAR (20)  NULL,
    [State]                                           VARCHAR (10)  NULL,
    [SurfaceHoleLatitudeWGS84]                        REAL          NULL,
    [SurfaceHoleLongitudeWGS84]                       REAL          NULL,
    [Survey]                                          VARCHAR (56)  NULL,
    [TVDSSMean]                                       REAL          NULL,
    [TargetFormation]                                 VARCHAR (63)  NULL,
    [ToeInLandingZone]                                VARCHAR (1)   NULL,
    [TotalAdditiveFirstTreatmentJob]                  REAL          NULL,
    [TotalFluidFirstTreatmentJob]                     REAL          NULL,
    [TotalProppantFirstTreatmentJob]                  REAL          NULL,
    [Township]                                        VARCHAR (20)  NULL,
    [TreatmentJobCountAPI10]                          VARCHAR (10)  NULL,
    [TreatmentType]                                   VARCHAR (34)  NULL,
    [TrueVerticalDepth]                               REAL          NULL,
    [TrueVerticalDepthSource]                         VARCHAR (10)  NULL,
    [UWI]                                             VARCHAR (18)  NULL,
    [UpdatedDate]                                     DATETIME2 (7) NULL,
    [UpperPerforation]                                REAL          NULL,
    [WellName]                                        VARCHAR (98)  NULL,
    [WellNumber]                                      VARCHAR (48)  NULL,
    [WellStatus]                                      VARCHAR (14)  NULL,
    [WellboreCountAPI10]                              VARCHAR (20)  NULL
);


GO
CREATE NONCLUSTERED INDEX [nci_wi_WellRollups_CD34C856889A701B36E89626F10E52F1]
    ON [StageDI].[WellRollups]([API10] ASC);


GO
CREATE NONCLUSTERED INDEX [nci_wi_WellRollups_74B1301B87241BE111B33E82A5F79158]
    ON [StageDI].[WellRollups]([API14] ASC)
    INCLUDE([AAPGGeologicProvince], [Abstract], [Block], [BottomHoleLatitudeWGS84], [BottomHoleLongitudeWGS84], [CompletionDate], [CountyParish], [CreatedDate], [DILateralLength], [DIPlay], [DISubplay], [DrillType], [Field], [FirstProdDate], [GrossPerforatedInterval], [GroundElevation], [HorizontalLength], [HorizontalWellboreLength], [LateralLength], [LeaseName], [LowerPerforation], [MeasuredDepth], [OperatorAlias], [OperatorCompanyName], [ProducingReservoir], [ProductionType], [QuarterQuarter], [Range], [Section], [SpudDate], [State], [SurfaceHoleLatitudeWGS84], [SurfaceHoleLongitudeWGS84], [Survey], [TargetFormation], [Township], [TrueVerticalDepth], [UpdatedDate], [UpperPerforation], [WellNumber]);


GO
CREATE NONCLUSTERED INDEX [idx_wellrollups_api14]
    ON [StageDI].[WellRollups]([API14] ASC) WITH (STATISTICS_NORECOMPUTE = ON);


GO
ALTER INDEX [idx_wellrollups_api14]
    ON [StageDI].[WellRollups] DISABLE;

