/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[ZediDataQTR]
(
[location_id] [int] NULL,
[location] [nvarchar] (100) NULL,
[starttime] [datetime] NOT NULL,
[endtime] [datetime] NULL,
[sensor] [nvarchar] (100) NULL,
[sensor_id] [int] NOT NULL,
[unit] [nvarchar] (25) NULL,
[amount] [float] NULL,
[qtrtype] [nvarchar] (15) NULL
)
GO
ALTER TABLE [dbo].[ZediDataQTR] ADD CONSTRAINT [PK__ZediData__345A12023E25804F] PRIMARY KEY CLUSTERED ([starttime], [sensor_id])
GO
CREATE NONCLUSTERED INDEX [ndx_location_sensor_incl_all_QTR] ON [dbo].[ZediDataQTR] ([location_id], [sensor]) INCLUDE ([location], [starttime], [endtime], [sensor_id], [unit], [amount], [qtrtype])
GO
