


/************************************************************
** Name: ProcessDocumentMetadataXML
** Desc: 
** Auth: Aaron Vogt
** Date: 02/05/2020
**************************
** Change History
**************************
** PR Date         Author         Description 
** -- ----         ------         -------------------------------------------
** 1  02/05/2020   Aaron          Object creation
************************************************************/
CREATE PROCEDURE [dbo].[ProcessDocumentMetadataXML]
	@DocumentMetadataXML VARCHAR(MAX),
	@ProjectId INT = NULL
AS
BEGIN

DECLARE @DocumentMetadataXMLDocumentHandle INT
EXEC sp_xml_preparedocument @DocumentMetadataXMLDocumentHandle OUTPUT, @DocumentMetadataXML

MERGE RegisterDocument AS Destination 
USING
(
SELECT
	[DocumentId], 
	[AsBuiltRequired], 
	[Attribute1], 
	[Attribute2], 
	[Attribute3], 
	[Attribute4], 
	[Author], 
	[AuthorisedBy], 
	[Category], 
	[Check1], 
	[Check2], 
	[Comments], 
	[Comments2], 
	[Confidential], 
	[ConfidentialUserAccessList], 
	[UserId], 
	[ContractDeliverable], 
	[ContractNumber], 
	[ContractorDocumentNumber], 
	[ContractorRevision], 
	[Date1], 
	[Date2], 
	[DateCreated], 
	[DateForReview], 
	[DateModified], 
	[DateReviewed], 
	[Discipline], 
	[DocumentNumber], 
	[DocumentStatus], 
	[DocumentType], 
	[FileSize], 
	[Filename], 
	[PackageNumber], 
	[PercentComplete], 
	[PrintSize], 
	[ProjectField1], 
	[ProjectField2], 
	[ProjectField3], 
	[Received], 
	[Reference], 
	[Registered], 
	[Reviewed], 
	[ReviewSource], 
	[ReviewStatus], 
	[Revision], 
	[RevisionDate], 
	[Scale], 
	[SelectList1], 
	[SelectList2], 
	[SelectList3], 
	[SelectList4], 
	[SelectList5], 
	[SelectList6], 
	[SelectList7], 
	[SelectList8], 
	[SelectList9], 
	[SelectList10], 
	[TagNumber], 
	[Title], 
	[ToClientDate], 
	[Vdrcode], 
	[VendorDocumentNumber], 
	[VendorRevision],
	(SELECT ProjectShortName FROM Projects WHERE ProjectId = @ProjectId) AS ProjectShortName
FROM OPENXML (@DocumentMetadataXMLDocumentHandle, '/RegisterDocument')
WITH (
	DocumentId varchar(200) './@DocumentId',
	AsBuiltRequired char(5) './AsBuiltRequired',
	Attribute1 varchar(200) './Attribute1',
	Attribute2 varchar(200) './Attribute2',
	Attribute3 varchar(200) './Attribute3',
	Attribute4 varchar(200) './Attribute4',
	Author varchar(50) './Author',
	AuthorisedBy varchar(50) './AuthorisedBy',
	Category varchar(50) './Category',
	Check1 char(5) './Check1',
	Check2 char(5) './Check2',
	Comments varchar(50) './Comments',
	Comments2 varchar(50) './Comments2',
	Confidential char(5) './Confidential',
	ConfidentialUserAccessList varchar(200) './ConfidentialUserAccessList',
	UserId varchar(200) './UserId',
	ContractDeliverable char(5) './ContractDeliverable',
	ContractNumber varchar(50) './ContractNumber',
	ContractorDocumentNumber varchar(50) './ContractorDocumentNumber',
	ContractorRevision varchar(50) './ContractorRevision',
	Date1 datetime './Date1',
	Date2 datetime './Date2',
	DateCreated datetime './DateCreated',
	DateForReview datetime './DateForReview',
	DateModified datetime './DateModified',
	DateReviewed datetime './DateReviewed',
	Discipline varchar(50) './Discipline',
	DocumentNumber varchar(210) './DocumentNumber',
	DocumentStatus varchar(50) './DocumentStatus',
	DocumentType varchar(50) './DocumentType',
	FileSize int './FileSize',
	Filename varchar(50) './Filename',
	PackageNumber varchar(50) './PackageNumber',
	PercentComplete int './PercentComplete',
	PrintSize varchar(50) './PrintSize',
	ProjectField1 varchar(50) './ProjectField1',
	ProjectField2 varchar(50) './ProjectField2',
	ProjectField3 varchar(50) './ProjectField3',
	Received datetime './Received',
	Reference varchar(50) './Reference',
	Registered datetime './Registered',
	Reviewed datetime './Reviewed',
	ReviewSource varchar(50) './ReviewSource',
	ReviewStatus varchar(50) './ReviewStatus',
	Revision varchar(50) './Revision',
	RevisionDate datetime './RevisionDate',
	Scale varchar(50) './Scale',
	SelectList1 varchar(60) './SelectList1',
	SelectList2 varchar(60) './SelectList2',
	SelectList3 varchar(60) './SelectList3',
	SelectList4 varchar(60) './SelectList4',
	SelectList5 varchar(60) './SelectList5',
	SelectList6 varchar(60) './SelectList6',
	SelectList7 varchar(60) './SelectList7',
	SelectList8 varchar(60) './SelectList8',
	SelectList9 varchar(60) './SelectList9',
	SelectList10 varchar(60) './SelectList10',
	TagNumber varchar(50) './TagNumber',
	Title varchar(50) './Title',
	ToClientDate datetime './ToClientDate',
	Vdrcode varchar(50) './Vdrcode',
	VendorDocumentNumber varchar(50) './VendorDocumentNumber',
	VendorRevision varchar(50) './VendorRevision'
)) AS Source
ON
	Source.DocumentId = Destination.DocumentId
WHEN NOT MATCHED THEN
INSERT
(
	DocumentId,
	AsBuiltRequired,
	Attribute1,
	Attribute2,
	Attribute3,
	Attribute4,
	Author,
	AuthorisedBy,
	Category,
	Check1,
	Check2,
	Comments,
	Comments2,
	Confidential,
	ConfidentialUserAccessList,
	UserId,
	ContractDeliverable,
	ContractNumber,
	ContractorDocumentNumber,
	ContractorRevision,
	Date1,
	Date2,
	DateCreated,
	DateForReview,
	DateModified,
	DateReviewed,
	Discipline,
	DocumentNumber,
	DocumentStatus,
	DocumentType,
	FileSize,
	[Filename],
	PackageNumber,
	PercentComplete,
	PrintSize,
	ProjectField1,
	ProjectField2,
	ProjectField3,
	Received,
	Reference,
	Registered,
	Reviewed,
	ReviewSource,
	ReviewStatus,
	Revision,
	RevisionDate,
	Scale,
	SelectList1,
	SelectList2,
	SelectList3,
	SelectList4,
	SelectList5,
	SelectList6,
	SelectList7,
	SelectList8,
	SelectList9,
	SelectList10,
	TagNumber,
	Title,
	ToClientDate,
	Vdrcode,
	VendorDocumentNumber,
	VendorRevision,
	ProjectShortName,
	ProjectId
)
VALUES
(
	Source.DocumentId,
	Source.AsBuiltRequired,
	Source.Attribute1,
	Source.Attribute2,
	Source.Attribute3,
	Source.Attribute4,
	Source.Author,
	Source.AuthorisedBy,
	Source.Category,
	Source.Check1,
	Source.Check2,
	Source.Comments,
	Source.Comments2,
	Source.Confidential,
	Source.ConfidentialUserAccessList,
	Source.UserId,
	Source.ContractDeliverable,
	Source.ContractNumber,
	Source.ContractorDocumentNumber,
	Source.ContractorRevision,
	Source.Date1,
	Source.Date2,
	Source.DateCreated,
	Source.DateForReview,
	Source.DateModified,
	Source.DateReviewed,
	Source.Discipline,
	Source.DocumentNumber,
	Source.DocumentStatus,
	Source.DocumentType,
	Source.FileSize,
	Source.[Filename],
	Source.PackageNumber,
	Source.PercentComplete,
	Source.PrintSize,
	Source.ProjectField1,
	Source.ProjectField2,
	Source.ProjectField3,
	Source.Received,
	Source.Reference,
	Source.Registered,
	Source.Reviewed,
	Source.ReviewSource,
	Source.ReviewStatus,
	Source.Revision,
	Source.RevisionDate,
	Source.Scale,
	Source.SelectList1,
	Source.SelectList2,
	Source.SelectList3,
	Source.SelectList4,
	Source.SelectList5,
	Source.SelectList6,
	Source.SelectList7,
	Source.SelectList8,
	Source.SelectList9,
	Source.SelectList10,
	Source.TagNumber,
	Source.Title,
	Source.ToClientDate,
	Source.Vdrcode,
	Source.VendorDocumentNumber,
	Source.VendorRevision,
	Source.ProjectShortName,
	@ProjectID
)
WHEN MATCHED THEN
UPDATE SET
	Destination.AsBuiltRequired = Source.AsBuiltRequired,
	Destination.Attribute1 = Source.Attribute1,
	Destination.Attribute2 = Source.Attribute2,
	Destination.Attribute3 = Source.Attribute3,
	Destination.Attribute4 = Source.Attribute4,
	Destination.Author = Source.Author,
	Destination.AuthorisedBy = Source.AuthorisedBy,
	Destination.Category = Source.Category,
	Destination.Check1 = Source.Check1,
	Destination.Check2 = Source.Check2,
	Destination.Comments = Source.Comments,
	Destination.Comments2 = Source.Comments2,
	Destination.Confidential = Source.Confidential,
	Destination.ConfidentialUserAccessList = Source.ConfidentialUserAccessList,
	Destination.UserId = Source.UserId,
	Destination.ContractDeliverable = Source.ContractDeliverable,
	Destination.ContractNumber = Source.ContractNumber,
	Destination.ContractorDocumentNumber = Source.ContractorDocumentNumber,
	Destination.ContractorRevision = Source.ContractorRevision,
	Destination.Date1 = Source.Date1,
	Destination.Date2 = Source.Date2,
	Destination.DateCreated = Source.DateCreated,
	Destination.DateForReview = Source.DateForReview,
	Destination.DateModified = Source.DateModified,
	Destination.DateReviewed = Source.DateReviewed,
	Destination.Discipline = Source.Discipline,
	Destination.DocumentNumber = Source.DocumentNumber,
	Destination.DocumentStatus = Source.DocumentStatus,
	Destination.DocumentType = Source.DocumentType,
	Destination.FileSize = Source.FileSize,
	Destination.[Filename] = Source.[Filename],
	Destination.PackageNumber = Source.PackageNumber,
	Destination.PercentComplete = Source.PercentComplete,
	Destination.PrintSize = Source.PrintSize,
	Destination.ProjectField1 = Source.ProjectField1,
	Destination.ProjectField2 = Source.ProjectField2,
	Destination.ProjectField3 = Source.ProjectField3,
	Destination.Received = Source.Received,
	Destination.Reference = Source.Reference,
	Destination.Registered = Source.Registered,
	Destination.Reviewed = Source.Reviewed,
	Destination.ReviewSource = Source.ReviewSource,
	Destination.ReviewStatus = Source.ReviewStatus,
	Destination.Revision = Source.Revision,
	Destination.RevisionDate = Source.RevisionDate,
	Destination.Scale = Source.Scale,
	Destination.SelectList1 = Source.SelectList1,
	Destination.SelectList2 = Source.SelectList2,
	Destination.SelectList3 = Source.SelectList3,
	Destination.SelectList4 = Source.SelectList4,
	Destination.SelectList5 = Source.SelectList5,
	Destination.SelectList6 = Source.SelectList6,
	Destination.SelectList7 = Source.SelectList7,
	Destination.SelectList8 = Source.SelectList8,
	Destination.SelectList9 = Source.SelectList9,
	Destination.SelectList10 = Source.SelectList10,
	Destination.TagNumber = Source.TagNumber,
	Destination.Title = Source.Title,
	Destination.ToClientDate = Source.ToClientDate,
	Destination.Vdrcode = Source.Vdrcode,
	Destination.VendorDocumentNumber = Source.VendorDocumentNumber,
	Destination.VendorRevision = Source.VendorRevision,
	Destination.DateRecordCreated = GETDATE(),
	Destination.DateRecordUpdated = GETDATE(),
	Destination.ProjectShortName = Source.ProjectShortName,
	Destination.ProjectID = @ProjectID;

EXEC sp_xml_removedocument @DocumentMetadataXMLDocumentHandle

END