/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

ALTER ROLE [db_datareader] ADD MEMBER [TLN\jlogbotche]
GO
ALTER ROLE [db_datareader] ADD MEMBER [TLN\svc-powerbi]
GO
ALTER ROLE [db_datareader] ADD MEMBER [TLN\ttaylor]
GO
ALTER ROLE [db_datareader] ADD MEMBER [TLN\upstream]
GO
