CREATE TABLE [TEMP].[ECOSTRM] (
    [KEYWORD]   VARCHAR (20) NOT NULL,
    [CNTRY]     VARCHAR (4)  NOT NULL,
    [ARRAY]     VARCHAR (1)  NOT NULL,
    [ITEM_NUM]  SMALLINT     NOT NULL,
    [DEPENDENT] SMALLINT     NULL,
    [DATA_SECT] SMALLINT     NULL,
    [DET_SUM]   VARCHAR (1)  NULL,
    [HELP_TEXT] VARCHAR (48) NULL
);

