/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[StatusLookup]
(
[StatusKey] [int] NOT NULL,
[StatusFirstName] [varchar] (255) NULL,
[StatusLastName] [varchar] (255) NULL
)
GO
ALTER TABLE [dbo].[StatusLookup] ADD CONSTRAINT [StatusLookUpPK] PRIMARY KEY CLUSTERED ([StatusKey])
GO
