CREATE TABLE [dbo].[OperatedWellSpreadsheet] (
    [Op/_Non-Op]       NVARCHAR (255) NULL,
    [Cost_Center]      NVARCHAR (255) NULL,
    [State_Serial #]   NVARCHAR (255) NULL,
    [API_Code]         NVARCHAR (255) NULL,
    [State_Field #]    NVARCHAR (255) NULL,
    [State Field]      NVARCHAR (255) NULL,
    [AFE #]            NVARCHAR (255) NULL,
    [Well_Name]        NVARCHAR (255) NULL,
    [Land Name]        NVARCHAR (255) NULL,
    [P2 Name]          NVARCHAR (255) NULL,
    [ProdView Name]    NVARCHAR (255) NULL,
    [Propnum]          NVARCHAR (255) NULL,
    [First_Sales Date] DATETIME       NULL,
    [NRI]              FLOAT (53)     NULL,
    [Operator_Name]    NVARCHAR (255) NULL,
    [Former Operator]  NVARCHAR (255) NULL,
    [S-T-R]            NVARCHAR (255) NULL,
    [T-R]              NVARCHAR (255) NULL,
    [County_Name]      NVARCHAR (255) NULL,
    [State_Name]       NVARCHAR (255) NULL,
    [Lease_Type]       NVARCHAR (255) NULL,
    [Formation_Name]   NVARCHAR (255) NULL,
    [Area]             NVARCHAR (255) NULL,
    [Gathering]        NVARCHAR (255) NULL,
    [Latitude]         FLOAT (53)     NULL,
    [Longitude]        FLOAT (53)     NULL,
    [Status]           NVARCHAR (255) NULL,
    [TVD]              FLOAT (53)     NULL,
    [MD]               FLOAT (53)     NULL
);

