CREATE TABLE [dbo].[TELL_PDP_LATLONGS] (
    [OBJECTID *]   NVARCHAR (255) NULL,
    [Shape *]      NVARCHAR (255) NULL,
    [Latitude]     NVARCHAR (255) NULL,
    [Longitude]    NVARCHAR (255) NULL,
    [Survey_Typ]   NVARCHAR (255) NULL,
    [Hole_Direc]   NVARCHAR (255) NULL,
    [Name]         NVARCHAR (255) NULL,
    [UWI]          NVARCHAR (255) NULL,
    [ZIndexOrde]   NVARCHAR (255) NULL,
    [SurfLocY]     NVARCHAR (255) NULL,
    [KB_Elevati]   NVARCHAR (255) NULL,
    [Borehole_I]   NVARCHAR (255) NULL,
    [Primary_Ty]   NVARCHAR (255) NULL,
    [Well_Numbe]   NVARCHAR (255) NULL,
    [Active_Ele]   NVARCHAR (255) NULL,
    [Computatio]   NVARCHAR (255) NULL,
    [Well_Name]    NVARCHAR (255) NULL,
    [North_Refe]   NVARCHAR (255) NULL,
    [Current_Op]   NVARCHAR (255) NULL,
    [Well_Nam_1]   NVARCHAR (255) NULL,
    [Lease_Name]   NVARCHAR (255) NULL,
    [Borehole_N]   NVARCHAR (255) NULL,
    [SurfLocX]     NVARCHAR (255) NULL,
    [Total_Dept]   NVARCHAR (255) NULL,
    [Formation]    NVARCHAR (255) NULL,
    [Shape_Length] NVARCHAR (255) NULL,
    [Map_Label]    NVARCHAR (255) NULL
);

