CREATE TABLE [Upstream].[UV_AC_PROP_AT] (
    [UWI]                                                              VARCHAR (20)     NOT NULL,
    [RecordSource]                                                     VARCHAR (20)     NULL,
    [LoadDate]                                                         DATETIME2 (7)    CONSTRAINT [DF__UV_AC_PRO__LoadD__0777106D] DEFAULT (getdate()) NULL,
    [SOURCE]                                                           VARCHAR (50)     NULL,
    [API_NUMBER]                                                       VARCHAR (20)     NOT NULL,
    [OPERATOR_NAME]                                                    VARCHAR (100)    NULL,
    [REGULATORY_API]                                                   VARCHAR (20)     NOT NULL,
    [CURRENT_OPERATOR_NAME]                                            VARCHAR (100)    NULL,
    [LEASE_NAME]                                                       VARCHAR (100)    NULL,
    [WELL_NUMBER]                                                      VARCHAR (50)     NULL,
    [FIELD_NAME]                                                       VARCHAR (100)    NULL,
    [COUNTRY_NAME]                                                     VARCHAR (3)      NOT NULL,
    [STATE_NAME]                                                       VARCHAR (60)     NULL,
    [COUNTY_NAME]                                                      VARCHAR (60)     NULL,
    [HOLE_DIRECTION]                                                   VARCHAR (12)     NULL,
    [WELL_STATUS]                                                      VARCHAR (60)     NULL,
    [CURRENT_STATUS]                                                   VARCHAR (60)     NULL,
    [BASIN]                                                            VARCHAR (60)     NULL,
    [PLAY_NAME]                                                        VARCHAR (60)     NULL,
    [TPC_PLAY_NAME]                                                    VARCHAR (60)     NULL,
    [PLAY_TYPE]                                                        VARCHAR (30)     NULL,
    [PERMIT_DATE]                                                      DATE             NULL,
    [DEPTH_TOTAL_DRILLER]                                              DECIMAL (32, 5)  NULL,
    [DEPTH_TOTAL_LOGGER]                                               DECIMAL (32, 5)  NULL,
    [DEPTH_TRUE_VERTICAL]                                              DECIMAL (32, 5)  NULL,
    [DEPTH_WHIPSTOCK]                                                  DECIMAL (32, 5)  NULL,
    [STATUS_FINAL_CODE]                                                VARCHAR (12)     NULL,
    [FORMATION_PROJECTED_NAME]                                         VARCHAR (200)    NULL,
    [DEPTH_TOTAL_PROJECTED]                                            DECIMAL (32, 5)  NULL,
    [FORMATION_AT_TD_NAME]                                             VARCHAR (200)    NULL,
    [PRODFIT_FORMATION_AT_TD_NAME]                                     VARCHAR (200)    NULL,
    [FORMATION_PRODUCING_NAME]                                         VARCHAR (200)    NULL,
    [PRODFIT_TOP_PRODUCING_FORMATION]                                  VARCHAR (200)    NULL,
    [PRODFIT_BASE_PRODUCING_FORMATION]                                 VARCHAR (200)    NULL,
    [PRODFIT_80_DEGREE_HEEL_PT_FORM]                                   VARCHAR (200)    NULL,
    [GROUND_ELEVATION]                                                 DECIMAL (32, 5)  NULL,
    [DATE_SPUD]                                                        DATE             NULL,
    [DATE_COMPLETION]                                                  DATE             NULL,
    [DATE_RIG_RELEASE]                                                 DATE             NULL,
    [DATE_ABANDONMENT]                                                 DATE             NULL,
    [DATE_LAST_ACTIVITY]                                               DATE             NULL,
    [SURFACE_LATITUDE]                                                 DECIMAL (32, 9)  NULL,
    [SURFACE_LONGITUDE]                                                DECIMAL (32, 9)  NULL,
    [BH_LATITUDE]                                                      DECIMAL (32, 9)  NULL,
    [BH_LONGITUDE]                                                     DECIMAL (32, 9)  NULL,
    [RECORD_CREATION_DATE]                                             DATETIME2 (7)    NULL,
    [RECORD_UPDATE_DATE]                                               DATETIME2 (7)    NULL,
    [DEPTH_TOP]                                                        DECIMAL (38, 16) NULL,
    [DEPTH_BASE]                                                       DECIMAL (38, 16) NULL,
    [LAT_LEN_HORIZ_DISPLACEMENT_FT]                                    INT              NULL,
    [LAT_LEN_GROSS_PERF_INTVL]                                         DECIMAL (38, 5)  NULL,
    [NUM_FRAC_STAGES]                                                  DECIMAL (38)     NULL,
    [NUM_TREATMENT_RECORDS]                                            DECIMAL (38)     NULL,
    [PROPPANT_SAND_LBS]                                                DECIMAL (12, 1)  NULL,
    [PROPPANT_RESIN_COATED_SAND_LBS]                                   DECIMAL (12, 1)  NULL,
    [PROPPANT_CERAMIC_LBS]                                             DECIMAL (12, 1)  NULL,
    [PROPPANT_RESIN_COATED_CERAMIC_LBS]                                DECIMAL (12, 1)  NULL,
    [PROPPAND_SAND_CERAMIC_LBS]                                        DECIMAL (12, 1)  NULL,
    [PROPPANT_SAND_RESIN_COATED_CERAMIC_LBS]                           DECIMAL (12, 1)  NULL,
    [PROPPANT_SAND_CERAMIC_RESIN_COATED_SAND_LBS]                      DECIMAL (12, 1)  NULL,
    [PROPPANT_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS]                   DECIMAL (12, 1)  NULL,
    [PROPPANT_SAND_RESIN_COATED_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS] DECIMAL (12, 1)  NULL,
    [PROPPANT_BAUXITE_LBS]                                             DECIMAL (12, 1)  NULL,
    [PROPPANT_WALNUT_LBS]                                              DECIMAL (12, 1)  NULL,
    [PROPPANT_MARBLE_LBS]                                              DECIMAL (12, 1)  NULL,
    [PROPPANT_GRAVEL_LBS]                                              DECIMAL (12, 1)  NULL,
    [PROPPANT_SAND_BAUXITE_CERAMIC_LBS]                                DECIMAL (12, 1)  NULL,
    [PROPPANT_OTHER_LBS]                                               DECIMAL (12, 1)  NULL,
    [TOTAL_PROPPANT_LBS]                                               DECIMAL (38, 1)  NULL,
    [FLUID_WATER_GALS]                                                 DECIMAL (12, 1)  NULL,
    [FLUID_SLICK_WATER_GALS]                                           DECIMAL (12, 1)  NULL,
    [FLUID_SALT_WATER_GALS]                                            DECIMAL (12, 1)  NULL,
    [FLUID_FOAM_GALS]                                                  DECIMAL (12, 1)  NULL,
    [FLUID_OIL_GALS]                                                   DECIMAL (12, 1)  NULL,
    [FLUID_POTASSIUM_CHLORIDE_GALS]                                    DECIMAL (12, 1)  NULL,
    [FLUID_SURFACTANT_GALS]                                            DECIMAL (12, 1)  NULL,
    [FLUID_EMULSION_GALS]                                              DECIMAL (12, 1)  NULL,
    [N2_CO2_GAS_GALS]                                                  DECIMAL (12, 1)  NULL,
    [ACID_GALS]                                                        DECIMAL (12, 1)  NULL,
    [GEL_X_LINK_GALS]                                                  DECIMAL (12, 1)  NULL,
    [FLUID_EXPLOSIVE_GALS]                                             DECIMAL (12, 1)  NULL,
    [FLUID_OTHER_GALS]                                                 DECIMAL (12, 1)  NULL,
    [TOTAL_FLUID_GALS]                                                 DECIMAL (38, 1)  NULL,
    [TOTAL_PROPPANT_LBS_OR_TOTAL_FLUID_GAL]                            DECIMAL (38, 16) NULL,
    [SURFACE_TOWNSHIP_DIRECTION]                                       VARCHAR (12)     NULL,
    [SURFACE_TOWNSHIP_NUMBER]                                          DECIMAL (6, 1)   NULL,
    [SURFACE_RANGE_DIRECTION]                                          VARCHAR (12)     NULL,
    [SURFACE_RANGE_NUMBER]                                             DECIMAL (5, 1)   NULL,
    [SURFACE_SECTION_NUMBER]                                           VARCHAR (20)     NULL,
    [SURFACE_SECTION_TYPE]                                             VARCHAR (12)     NULL,
    [SURFACE_SPOT]                                                     VARCHAR (12)     NULL,
    [SURFACE_MERIDIAN_NAME]                                            VARCHAR (20)     NULL,
    [SURFACE_REMARK]                                                   VARCHAR (240)    NULL,
    [SURFACE_FOOTAGE_NORTH_SOUTH]                                      DECIMAL (7, 2)   NULL,
    [SURFACE_FOOTAGE_NORTH_SOUTH_START_LINE]                           VARCHAR (12)     NULL,
    [SURFACE_FOOTAGE_EAST_WEST]                                        DECIMAL (7, 2)   NULL,
    [SURFACE_FOOTAGE_EAST_WEST_START_LINE]                             VARCHAR (12)     NULL,
    [SURFACE_FOOTAGE_REFERENCE_NAME]                                   VARCHAR (60)     NULL,
    [BH_TOWNSHIP_DIRECTION]                                            VARCHAR (12)     NULL,
    [BH_TOWNSHIP_NUMBER]                                               DECIMAL (6, 1)   NULL,
    [BH_RANGE_DIRECTION]                                               VARCHAR (12)     NULL,
    [BH_RANGE_NUMBER]                                                  DECIMAL (5, 1)   NULL,
    [BH_SECTION_NUMBER]                                                DECIMAL (5, 1)   NULL,
    [BH_SECTION_TYPE]                                                  VARCHAR (12)     NULL,
    [BH_SPOT]                                                          VARCHAR (12)     NULL,
    [BH_MERIDIAN_NAME]                                                 VARCHAR (20)     NULL,
    [BH_REMARK]                                                        VARCHAR (240)    NULL,
    [BH_FOOTAGE_NORTH_SOUTH]                                           DECIMAL (7, 2)   NULL,
    [BH_FOOTAGE_NORTH_SOUTH_START_LINE]                                VARCHAR (12)     NULL,
    [BH_FOOTAGE_EAST_WEST]                                             DECIMAL (7, 2)   NULL,
    [BH_FOOTAGE_EAST_WEST_START_LINE]                                  VARCHAR (12)     NULL,
    [BH_FOOTAGE_REFERENCE_NAME]                                        VARCHAR (60)     NULL,
    CONSTRAINT [PK_UV_AC_PROP_AT] PRIMARY KEY CLUSTERED ([UWI] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

