CREATE TABLE [Upstream].[WellHeader_WellTreatment] (
    [API14]                                                                VARCHAR (20)     NOT NULL,
    [IHS_LoadDate]                                                         DATETIME2 (7)    CONSTRAINT [DF__WellHeade__IHS_L__764C846B] DEFAULT (getdate()) NOT NULL,
    [DI_LoadDate]                                                          DATETIME2 (7)    CONSTRAINT [DF__WellHeade__DI_Lo__7740A8A4] DEFAULT (getdate()) NOT NULL,
    [IHS_NUM_FRAC_STAGES]                                                  DECIMAL (38)     NULL,
    [IHS_NUM_TREATMENT_RECORDS]                                            DECIMAL (38)     NULL,
    [IHS_PROPPANT_SAND_LBS]                                                DECIMAL (12, 1)  NULL,
    [IHS_PROPPANT_RESIN_COATED_SAND_LBS]                                   DECIMAL (12, 1)  NULL,
    [IHS_PROPPANT_CERAMIC_LBS]                                             DECIMAL (12, 1)  NULL,
    [IHS_PROPPANT_RESIN_COATED_CERAMIC_LBS]                                DECIMAL (12, 1)  NULL,
    [IHS_PROPPAND_SAND_CERAMIC_LBS]                                        DECIMAL (12, 1)  NULL,
    [IHS_PROPPANT_SAND_RESIN_COATED_CERAMIC_LBS]                           DECIMAL (12, 1)  NULL,
    [IHS_PROPPANT_SAND_CERAMIC_RESIN_COATED_SAND_LBS]                      DECIMAL (12, 1)  NULL,
    [IHS_PROPPANT_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS]                   DECIMAL (12, 1)  NULL,
    [IHS_PROPPANT_SAND_RESIN_COATED_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS] DECIMAL (12, 1)  NULL,
    [IHS_PROPPANT_BAUXITE_LBS]                                             DECIMAL (12, 1)  NULL,
    [IHS_PROPPANT_WALNUT_LBS]                                              DECIMAL (12, 1)  NULL,
    [IHS_PROPPANT_MARBLE_LBS]                                              DECIMAL (12, 1)  NULL,
    [IHS_PROPPANT_GRAVEL_LBS]                                              DECIMAL (12, 1)  NULL,
    [IHS_PROPPANT_SAND_BAUXITE_CERAMIC_LBS]                                DECIMAL (12, 1)  NULL,
    [IHS_PROPPANT_OTHER_LBS]                                               DECIMAL (12, 1)  NULL,
    [IHS_TOTAL_PROPPANT_LBS]                                               DECIMAL (38, 1)  NULL,
    [IHS_FLUID_WATER_GALS]                                                 DECIMAL (12, 1)  NULL,
    [IHS_FLUID_SLICK_WATER_GALS]                                           DECIMAL (12, 1)  NULL,
    [IHS_FLUID_SALT_WATER_GALS]                                            DECIMAL (12, 1)  NULL,
    [IHS_FLUID_FOAM_GALS]                                                  DECIMAL (12, 1)  NULL,
    [IHS_FLUID_OIL_GALS]                                                   DECIMAL (12, 1)  NULL,
    [IHS_FLUID_POTASSIUM_CHLORIDE_GALS]                                    DECIMAL (12, 1)  NULL,
    [IHS_FLUID_SURFACTANT_GALS]                                            DECIMAL (12, 1)  NULL,
    [IHS_FLUID_EMULSION_GALS]                                              DECIMAL (12, 1)  NULL,
    [IHS_N2_CO2_GAS_GALS]                                                  DECIMAL (12, 1)  NULL,
    [IHS_ACID_GALS]                                                        DECIMAL (12, 1)  NULL,
    [IHS_GEL_X_LINK_GALS]                                                  DECIMAL (12, 1)  NULL,
    [IHS_FLUID_EXPLOSIVE_GALS]                                             DECIMAL (12, 1)  NULL,
    [IHS_FLUID_OTHER_GALS]                                                 DECIMAL (12, 1)  NULL,
    [IHS_TOTAL_FLUID_GALS]                                                 DECIMAL (38, 1)  NULL,
    [IHS_TOTAL_PROPPANT_LBS_OR_TOTAL_FLUID_GAL]                            DECIMAL (38, 18) NULL,
    [IHS_TotalLateralLengths]                                              DECIMAL (38, 5)  NULL,
    [IHS_TotalOffsetsMinTopDepthMaxBaseDepth]                              DECIMAL (38, 5)  NULL,
    [IHS_AverageLateralLengthHorizontalDisplacement]                       INT              NULL,
    [IHS_TotalLateralLengthHorizontalDisplacement]                         INT              NULL,
    [IHS_TotalGrossPerforationInterval]                                    DECIMAL (38, 5)  NULL,
    [IHS_MinTopDepth]                                                      DECIMAL (38, 16) NULL,
    [IHS_MaxBaseDepth]                                                     DECIMAL (38, 16) NULL,
    [IHS_OffsetSurfaceCoordBHCoordFeet]                                    NUMERIC (38, 16) NULL,
    [DI_NUM_FRAC_STAGES]                                                   DECIMAL (38)     NULL,
    [DI_NUM_TREATMENT_RECORDS]                                             DECIMAL (38)     NULL,
    [DI_PROPPANT_SAND_LBS]                                                 DECIMAL (12, 1)  NULL,
    [DI_PROPPANT_RESIN_COATED_SAND_LBS]                                    DECIMAL (12, 1)  NULL,
    [DI_PROPPANT_CERAMIC_LBS]                                              DECIMAL (12, 1)  NULL,
    [DI_PROPPANT_RESIN_COATED_CERAMIC_LBS]                                 DECIMAL (12, 1)  NULL,
    [DI_PROPPAND_SAND_CERAMIC_LBS]                                         DECIMAL (12, 1)  NULL,
    [DI_PROPPANT_SAND_RESIN_COATED_CERAMIC_LBS]                            DECIMAL (12, 1)  NULL,
    [DI_PROPPANT_SAND_CERAMIC_RESIN_COATED_SAND_LBS]                       DECIMAL (12, 1)  NULL,
    [DI_PROPPANT_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS]                    DECIMAL (12, 1)  NULL,
    [DI_PROPPANT_SAND_RESIN_COATED_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS]  DECIMAL (12, 1)  NULL,
    [DI_PROPPANT_BAUXITE_LBS]                                              DECIMAL (12, 1)  NULL,
    [DI_PROPPANT_WALNUT_LBS]                                               DECIMAL (12, 1)  NULL,
    [DI_PROPPANT_MARBLE_LBS]                                               DECIMAL (12, 1)  NULL,
    [DI_PROPPANT_GRAVEL_LBS]                                               DECIMAL (12, 1)  NULL,
    [DI_PROPPANT_SAND_BAUXITE_CERAMIC_LBS]                                 DECIMAL (12, 1)  NULL,
    [DI_PROPPANT_OTHER_LBS]                                                DECIMAL (12, 1)  NULL,
    [DI_TOTAL_PROPPANT_LBS]                                                DECIMAL (38, 1)  NULL,
    [DI_FLUID_WATER_GALS]                                                  DECIMAL (12, 1)  NULL,
    [DI_FLUID_SLICK_WATER_GALS]                                            DECIMAL (12, 1)  NULL,
    [DI_FLUID_SALT_WATER_GALS]                                             DECIMAL (12, 1)  NULL,
    [DI_FLUID_FOAM_GALS]                                                   DECIMAL (12, 1)  NULL,
    [DI_FLUID_OIL_GALS]                                                    DECIMAL (12, 1)  NULL,
    [DI_FLUID_POTASSIUM_CHLORIDE_GALS]                                     DECIMAL (12, 1)  NULL,
    [DI_FLUID_SURFACTANT_GALS]                                             DECIMAL (12, 1)  NULL,
    [DI_FLUID_EMULSION_GALS]                                               DECIMAL (12, 1)  NULL,
    [DI_N2_CO2_GAS_GALS]                                                   DECIMAL (12, 1)  NULL,
    [DI_ACID_GALS]                                                         DECIMAL (12, 1)  NULL,
    [DI_GEL_X_LINK_GALS]                                                   DECIMAL (12, 1)  NULL,
    [DI_FLUID_EXPLOSIVE_GALS]                                              DECIMAL (12, 1)  NULL,
    [DI_FLUID_OTHER_GALS]                                                  DECIMAL (12, 1)  NULL,
    [DI_TOTAL_FLUID_GALS]                                                  DECIMAL (38, 1)  NULL,
    [DI_TOTAL_PROPPANT_LBS_OR_TOTAL_FLUID_GAL]                             DECIMAL (38, 16) NULL,
    [DI_TotalLateralLengths]                                               DECIMAL (38, 5)  NULL,
    [DI_TotalOffsetsMinTopDepthMaxBaseDepth]                               DECIMAL (38, 5)  NULL,
    [DI_AverageLateralLengthHorizontalDisplacement]                        INT              NULL,
    [DI_TotalLateralLengthHorizontalDisplacement]                          INT              NULL,
    [DI_TotalGrossPerforationInterval]                                     DECIMAL (38, 5)  NULL,
    [DI_MinTopDepth]                                                       DECIMAL (38, 16) NULL,
    [DI_MaxBaseDepth]                                                      DECIMAL (38, 16) NULL,
    [DI_OffsetSurfaceCoordBHCoordFeet]                                     NUMERIC (38, 16) NULL,
    CONSTRAINT [PK_WellHeader_Treatment] PRIMARY KEY CLUSTERED ([API14] ASC, [IHS_LoadDate] ASC, [DI_LoadDate] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

