CREATE TABLE [dbo].[CompletionDailyTb] (
    [MerrickID]                  INT              NOT NULL,
    [RecordDate]                 DATETIME         NOT NULL,
    [ProducingStatus]            INT              NULL,
    [ProducingMethod]            INT              NULL,
    [ProductionDate]             DATETIME         NULL,
    [ProductCode]                INT              NULL,
    [ProductType]                INT              NULL,
    [DispositionCode]            INT              NULL,
    [DataSourceCode]             INT              NULL,
    [DataPopulationFlag]         INT              NULL,
    [ProrationMeter]             INT              NULL,
    [AllocationResultType]       INT              NULL,
    [LoadFluidRecoveryFlag]      INT              NULL,
    [LoadFluidCalcStatus]        INT              NULL,
    [OutsideOperatedFlag]        INT              NULL,
    [HoursFlowed]                FLOAT (53)       NULL,
    [HoursInjected]              FLOAT (53)       NULL,
    [HoursRecovery]              FLOAT (53)       NULL,
    [HoursIdle]                  FLOAT (53)       NULL,
    [DailyDownTime]              FLOAT (53)       NULL,
    [ReadingTime]                CHAR (8)         NULL,
    [CasingPressure]             FLOAT (53)       NULL,
    [InjectionPressure]          FLOAT (53)       NULL,
    [InterCasingPressure]        FLOAT (53)       NULL,
    [SurfaceCasingPressure]      FLOAT (53)       NULL,
    [LinerCasingPressure]        FLOAT (53)       NULL,
    [OtherCasingPressure]        FLOAT (53)       NULL,
    [TubingPressure]             FLOAT (53)       NULL,
    [TubingTemperature]          FLOAT (53)       NULL,
    [SecondTubingPressure]       FLOAT (53)       NULL,
    [ChokeSize]                  FLOAT (53)       NULL,
    [PressureClassification]     INT              NULL,
    [GasOilRatio]                FLOAT (53)       NULL,
    [EnvComplianceFlag]          INT              NULL,
    [BHPShutIn]                  FLOAT (53)       NULL,
    [BHPFlowing]                 FLOAT (53)       NULL,
    [BHTemperature]              FLOAT (53)       NULL,
    [BHPGaugeDepth]              FLOAT (53)       NULL,
    [ShutInTubingPressure]       FLOAT (53)       NULL,
    [EnteredGasVolmcfLeaseUse]   FLOAT (53)       NULL,
    [PumpDepth]                  FLOAT (53)       NULL,
    [AverageJointLength]         FLOAT (53)       NULL,
    [JointsToFluid]              FLOAT (53)       NULL,
    [FluidLevel]                 FLOAT (53)       NULL,
    [SetupChangeFlag]            CHAR (8)         NULL,
    [TheoreticalProdGas]         FLOAT (53)       NULL,
    [TheoreticalProdGasLiquids]  FLOAT (53)       NULL,
    [TheoreticalProdGasLift]     FLOAT (53)       NULL,
    [TheoreticalProdGasHighPres] FLOAT (53)       NULL,
    [TheoreticalProdGasLowPres]  FLOAT (53)       NULL,
    [TheoreticalProdOil]         FLOAT (53)       NULL,
    [TheoreticalProdWater]       FLOAT (53)       NULL,
    [TheoreticalProdCO2]         FLOAT (53)       NULL,
    [TheoreticalInjGasMCF]       FLOAT (53)       NULL,
    [TheoreticalInjOil]          FLOAT (53)       NULL,
    [TheoreticalInjWater]        FLOAT (53)       NULL,
    [TheoreticalInjCO2]          FLOAT (53)       NULL,
    [TheoreticalGasLiquidsGPM]   FLOAT (53)       NULL,
    [TheoreticalShrinkage]       FLOAT (53)       NULL,
    [TheoreticalOilWaterRatio]   FLOAT (53)       NULL,
    [TheoreticalOilGPM]          FLOAT (53)       NULL,
    [SustainedDeliverabilityGas] FLOAT (53)       NULL,
    [SustainedDeliverabilityOil] FLOAT (53)       NULL,
    [ProratedProdGas]            FLOAT (53)       NULL,
    [ProratedProdOil]            FLOAT (53)       NULL,
    [ProratedProdWater]          FLOAT (53)       NULL,
    [ProratedProdNGL]            FLOAT (53)       NULL,
    [AllocEstBTUFactor]          FLOAT (53)       NULL,
    [AllocEstTemperature]        FLOAT (53)       NULL,
    [AllocEstPressureBase]       FLOAT (53)       NULL,
    [AllocEstGravity]            FLOAT (53)       NULL,
    [AllocEstWetDryFlag]         INT              NULL,
    [AllocEstOilVol]             FLOAT (53)       NULL,
    [AllocEstWaterVol]           FLOAT (53)       NULL,
    [AllocEstGasVolMCF]          FLOAT (53)       NULL,
    [AllocEstGasVolMMBTU]        FLOAT (53)       NULL,
    [AllocEstCO2Vol]             FLOAT (53)       NULL,
    [AllocEstOtherVol]           FLOAT (53)       NULL,
    [AllocEstPlantGasMCF]        FLOAT (53)       NULL,
    [AllocEstPlantGasMMBTU]      FLOAT (53)       NULL,
    [AllocEstInjOilVol]          FLOAT (53)       NULL,
    [AllocEstInjWaterVol]        FLOAT (53)       NULL,
    [AllocEstInjGasVolMCF]       FLOAT (53)       NULL,
    [AllocEstInjGasVolMMBTU]     FLOAT (53)       NULL,
    [AllocEstInjCO2Vol]          FLOAT (53)       NULL,
    [AllocEstInjOtherVol]        FLOAT (53)       NULL,
    [AllocEstNGLVol]             FLOAT (53)       NULL,
    [AllocEstSulfurMass]         FLOAT (53)       NULL,
    [BeginningOil]               FLOAT (53)       NULL,
    [EndingOil]                  FLOAT (53)       NULL,
    [OilProduction]              FLOAT (53)       NULL,
    [BeginningWater]             FLOAT (53)       NULL,
    [EndingWater]                FLOAT (53)       NULL,
    [WaterProduction]            FLOAT (53)       NULL,
    [AllocEstRecoveryOilVol]     FLOAT (53)       NULL,
    [AllocEstRecoveryWaterVol]   FLOAT (53)       NULL,
    [AllocEstRecoveryGasVol]     FLOAT (53)       NULL,
    [AllocEstNetOilVol]          FLOAT (53)       NULL,
    [AllocEstNetWaterVol]        FLOAT (53)       NULL,
    [AllocEstNetGasVol]          FLOAT (53)       NULL,
    [GasBeginningInjInv]         FLOAT (53)       NULL,
    [GasEndingInjInv]            FLOAT (53)       NULL,
    [OilBeginningInjInv]         FLOAT (53)       NULL,
    [OilEndingInjInv]            FLOAT (53)       NULL,
    [WaterBeginningInjInv]       FLOAT (53)       NULL,
    [WaterEndingInjInv]          FLOAT (53)       NULL,
    [OtherBeginningInjInv]       FLOAT (53)       NULL,
    [OtherEndingInjInv]          FLOAT (53)       NULL,
    [EnteredBTUFactor]           FLOAT (53)       NULL,
    [EnteredTemperature]         FLOAT (53)       NULL,
    [EnteredPressureBase]        FLOAT (53)       NULL,
    [EnteredGravity]             FLOAT (53)       NULL,
    [EnteredWetDryFlag]          INT              NULL,
    [EnteredOilVol]              FLOAT (53)       NULL,
    [EnteredWaterVol]            FLOAT (53)       NULL,
    [EnteredGasVolMCF]           FLOAT (53)       NULL,
    [EnteredGasVolMMBTU]         FLOAT (53)       NULL,
    [EnteredGasSalesVolMCF]      FLOAT (53)       NULL,
    [EnteredGasSalesVolMMBTU]    FLOAT (53)       NULL,
    [EnteredCO2Vol]              FLOAT (53)       NULL,
    [EnteredCO2Mass]             FLOAT (53)       NULL,
    [EnteredOtherVol]            FLOAT (53)       NULL,
    [EnteredOilProduction]       FLOAT (53)       NULL,
    [EnteredWaterProduction]     FLOAT (53)       NULL,
    [EnteredBeginningOil]        FLOAT (53)       NULL,
    [EnteredEndingOil]           FLOAT (53)       NULL,
    [EnteredBeginningWater]      FLOAT (53)       NULL,
    [EnteredEndingWater]         FLOAT (53)       NULL,
    [EnteredPlantGasMCF]         FLOAT (53)       NULL,
    [EnteredPlantGasMMBTU]       FLOAT (53)       NULL,
    [EnteredInjOilVol]           FLOAT (53)       NULL,
    [EnteredInjWaterVol]         FLOAT (53)       NULL,
    [EnteredInjGasVolMCF]        FLOAT (53)       NULL,
    [EnteredInjGasVolMMBTU]      FLOAT (53)       NULL,
    [EnteredInjCO2Vol]           FLOAT (53)       NULL,
    [EnteredInjCO2Mass]          FLOAT (53)       NULL,
    [EnteredInjOtherVol]         FLOAT (53)       NULL,
    [EnteredNGLVol]              FLOAT (53)       NULL,
    [EnteredGasFlareMcf]         FLOAT (53)       NULL,
    [EnteredGasFlashMcf]         FLOAT (53)       NULL,
    [EnteredGasVentedMcf]        FLOAT (53)       NULL,
    [EnteredRetrogradeVol]       FLOAT (53)       NULL,
    [LastEnteredDate]            DATETIME         NULL,
    [LastEnteredDateDays]        INT              NULL,
    [RateOil]                    FLOAT (53)       NULL,
    [RateWater]                  FLOAT (53)       NULL,
    [RateGas]                    FLOAT (53)       NULL,
    [RateOilInj]                 FLOAT (53)       NULL,
    [RateWaterInj]               FLOAT (53)       NULL,
    [RateGasInj]                 FLOAT (53)       NULL,
    [FactorComputationFlag]      INT              NULL,
    [EnteredAsAllocatedFlag]     INT              NULL,
    [AllocationActiveFlag]       INT              NULL,
    [FixedVolumeFlagOil]         INT              NULL,
    [FixedVolumeFlagGas]         INT              NULL,
    [FixedVolumeFlagWater]       INT              NULL,
    [AllocationFactor]           FLOAT (53)       NULL,
    [AllocationFactorType]       INT              NULL,
    [AllocationFactor2]          FLOAT (53)       NULL,
    [AllocationFactorType2]      INT              NULL,
    [AllocationFactor3]          FLOAT (53)       NULL,
    [AllocationFactorType3]      INT              NULL,
    [AllocationFactor4]          FLOAT (53)       NULL,
    [AllocationFactorType4]      INT              NULL,
    [AllocationFactor5]          FLOAT (53)       NULL,
    [AllocationFactorType5]      INT              NULL,
    [AllocationFactor6]          FLOAT (53)       NULL,
    [AllocationFactorType6]      INT              NULL,
    [AllocationFactor7]          FLOAT (53)       NULL,
    [AllocationFactorType7]      INT              NULL,
    [AllocationFactor8]          FLOAT (53)       NULL,
    [AllocationFactorType8]      INT              NULL,
    [EquipAllocFactor]           FLOAT (53)       NULL,
    [EquipAllocFactorType]       INT              NULL,
    [EquipAllocFactor2]          FLOAT (53)       NULL,
    [EquipAllocFactorType2]      INT              NULL,
    [EquipAllocFactor3]          FLOAT (53)       NULL,
    [EquipAllocFactorType3]      INT              NULL,
    [EquipAllocFactor4]          FLOAT (53)       NULL,
    [EquipAllocFactorType4]      INT              NULL,
    [UserNumber1]                FLOAT (53)       NULL,
    [UserNumber2]                FLOAT (53)       NULL,
    [UserNumber3]                FLOAT (53)       NULL,
    [UserNumber4]                FLOAT (53)       NULL,
    [UserNumber5]                FLOAT (53)       NULL,
    [UserNumber6]                FLOAT (53)       NULL,
    [UserStringA]                VARCHAR (50)     NULL,
    [UserStringB]                VARCHAR (50)     NULL,
    [ErrorNumber]                INT              NULL,
    [SustainedDeliverability]    FLOAT (53)       NULL,
    [CompletionFlag]             INT              NULL,
    [GasInjection]               FLOAT (53)       NULL,
    [OilInjection]               FLOAT (53)       NULL,
    [WaterInjection]             FLOAT (53)       NULL,
    [ConfigurationMethod]        CHAR (8)         NULL,
    [ProductionTarget]           FLOAT (53)       NULL,
    [Choke]                      CHAR (8)         NULL,
    [AllocEstGasLiftVol]         FLOAT (53)       NULL,
    [TheoreticalWaterGPM]        FLOAT (53)       NULL,
    [BackgroundTaskFlag]         INT              NULL,
    [LastTransmission]           INT              NULL,
    [LastLoadDate]               DATETIME         NULL,
    [LastLoadTime]               CHAR (8)         NULL,
    [TransmitFlag]               INT              NULL,
    [DateTimeStamp]              DATETIME         NULL,
    [BLogicDateStamp]            DATETIME         NULL,
    [BLogicTimeStamp]            CHAR (8)         NULL,
    [AllocationDateStamp]        DATETIME         NULL,
    [AllocationTimeStamp]        CHAR (8)         NULL,
    [UserDateStamp]              DATETIME         NULL,
    [UserTimeStamp]              CHAR (8)         NULL,
    [UserID]                     INT              NULL,
    [CalculationStatusFlag]      INT              NOT NULL,
    [EnteredBeginningNGL]        FLOAT (53)       NULL,
    [EnteredEndingNGL]           FLOAT (53)       NULL,
    [EnteredNGLProduction]       FLOAT (53)       NULL,
    [StillDownFlag]              INT              NULL,
    [RowUID]                     UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_CompletionDailyTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC, [RecordDate] ASC)
);

