CREATE TABLE [dbo].[CompletionAllocationTypeTb] (
    [AllocationType]           INT              NOT NULL,
    [AllocationName]           VARCHAR (50)     NULL,
    [Description]              VARCHAR (500)    NULL,
    [ActiveFlag]               INT              NULL,
    [s_TestsEnabledFlag]       INT              NULL,
    [s_OutsideOperatedFlag]    INT              NULL,
    [s_UnitsTypeFlag]          INT              NULL,
    [s_CarryForwardFlag]       INT              NULL,
    [d_DataPopulationFlag]     INT              NULL,
    [d_FactorComputationFlag]  INT              NULL,
    [d_EnteredAsAllocatedFlag] INT              NULL,
    [d_AllocationActiveFlag]   INT              NULL,
    [d_AllocationFactor]       FLOAT (53)       NULL,
    [d_AllocationFactorType]   INT              NULL,
    [d_AllocationFactor2]      FLOAT (53)       NULL,
    [d_AllocationFactorType2]  INT              NULL,
    [d_AllocationFactor3]      FLOAT (53)       NULL,
    [d_AllocationFactorType3]  INT              NULL,
    [d_AllocationFactor4]      FLOAT (53)       NULL,
    [d_AllocationFactorType4]  INT              NULL,
    [d_AllocationFactor5]      FLOAT (53)       NULL,
    [d_AllocationFactorType5]  INT              NULL,
    [d_AllocationFactor6]      FLOAT (53)       NULL,
    [d_AllocationFactorType6]  INT              NULL,
    [d_AllocationFactor7]      FLOAT (53)       NULL,
    [d_AllocationFactorType7]  INT              NULL,
    [d_AllocationFactor8]      FLOAT (53)       NULL,
    [d_AllocationFactorType8]  INT              NULL,
    [d_EquipAllocFactor]       FLOAT (53)       NULL,
    [d_EquipAllocFactorType]   INT              NULL,
    [d_EquipAllocFactor2]      FLOAT (53)       NULL,
    [d_EquipAllocFactorType2]  INT              NULL,
    [d_EquipAllocFactor3]      FLOAT (53)       NULL,
    [d_EquipAllocFactorType3]  INT              NULL,
    [d_EquipAllocFactor4]      FLOAT (53)       NULL,
    [d_EquipAllocFactorType4]  INT              NULL,
    [m_DataPopulationFlag]     INT              NULL,
    [m_FactorComputationFlag]  INT              NULL,
    [m_EnteredAsAllocatedFlag] INT              NULL,
    [m_AllocationActiveFlag]   INT              NULL,
    [m_AllocationFactor]       FLOAT (53)       NULL,
    [m_AllocationFactorType]   INT              NULL,
    [m_AllocationFactor2]      FLOAT (53)       NULL,
    [m_AllocationFactorType2]  INT              NULL,
    [m_AllocationFactor3]      FLOAT (53)       NULL,
    [m_AllocationFactorType3]  INT              NULL,
    [m_AllocationFactor4]      FLOAT (53)       NULL,
    [m_AllocationFactorType4]  INT              NULL,
    [m_AllocationFactor5]      FLOAT (53)       NULL,
    [m_AllocationFactorType5]  INT              NULL,
    [m_AllocationFactor6]      FLOAT (53)       NULL,
    [m_AllocationFactorType6]  INT              NULL,
    [m_AllocationFactor7]      FLOAT (53)       NULL,
    [m_AllocationFactorType7]  INT              NULL,
    [m_AllocationFactor8]      FLOAT (53)       NULL,
    [m_AllocationFactorType8]  INT              NULL,
    [m_EquipAllocFactor]       FLOAT (53)       NULL,
    [m_EquipAllocFactorType]   INT              NULL,
    [m_EquipAllocFactor2]      FLOAT (53)       NULL,
    [m_EquipAllocFactorType2]  INT              NULL,
    [m_EquipAllocFactor3]      FLOAT (53)       NULL,
    [m_EquipAllocFactorType3]  INT              NULL,
    [m_EquipAllocFactor4]      FLOAT (53)       NULL,
    [m_EquipAllocFactorType4]  INT              NULL,
    [UserDateStamp]            DATETIME         NULL,
    [UserTimeStamp]            CHAR (8)         NULL,
    [UserID]                   INT              NULL,
    [RowUID]                   UNIQUEIDENTIFIER NOT NULL,
    [TargetType]               INT              NOT NULL,
    CONSTRAINT [PK_CompletionAllocationTypeTb] PRIMARY KEY CLUSTERED ([AllocationType] ASC)
);

