CREATE TABLE [dbo].[CrossReferenceTb] (
    [MerrickID]            INT          NOT NULL,
    [MerrickType]          INT          NOT NULL,
    [UniqueID]             INT          NULL,
    [ObjectName]           VARCHAR (80) NULL,
    [ObjectNumber]         VARCHAR (40) NULL,
    [ObjectType]           VARCHAR (15) NULL,
    [PrintFlag]            INT          NULL,
    [AccountingTeamID]     INT          NULL,
    [DrillingTeamID]       INT          NULL,
    [ProductionTeamID]     INT          NULL,
    [GroupID]              INT          NULL,
    [DivisionID]           INT          NULL,
    [FieldGroupID]         INT          NULL,
    [AreaID]               INT          NULL,
    [PlatformID]           INT          NULL,
    [BatteryID]            INT          NULL,
    [LeaseID]              INT          NULL,
    [PlantID]              INT          NULL,
    [DDAID]                INT          NULL,
    [StateID]              INT          NULL,
    [CountyID]             INT          NULL,
    [AccountingID]         VARCHAR (30) NULL,
    [ProductionID]         VARCHAR (30) NULL,
    [EngineeringID]        VARCHAR (30) NULL,
    [ActiveFlag]           INT          NULL,
    [RecordCompletionFlag] VARCHAR (20) NULL,
    CONSTRAINT [PK_CrossReferenceTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC, [MerrickType] ASC)
);

