CREATE TABLE [dbo].[DowntimeCodeTb] (
    [DowntimeCode]              INT          NOT NULL,
    [DowntimeDescription]       VARCHAR (80) NULL,
    [ObjectMerrickType]         INT          NULL,
    [ActiveFlag]                INT          NULL,
    [UpDownFlag]                INT          NULL,
    [ParentCode]                INT          NULL,
    [DowntimeDescriptionLevel1] VARCHAR (80) NULL,
    [DowntimeDescriptionLevel2] VARCHAR (80) NULL,
    [DowntimeDescriptionLevel3] VARCHAR (80) NULL,
    [DowntimeDescriptionLevel4] VARCHAR (80) NULL,
    [CommentRequiredFlag]       INT          NULL,
    [AlternateCode]             INT          NULL,
    [DefaultProducingStatus]    INT          NULL,
    [AccountingID]              VARCHAR (10) NULL,
    [EngineeringID]             VARCHAR (10) NULL,
    [ProductionID]              VARCHAR (10) NULL,
    [RioDowntimeCode]           VARCHAR (10) NULL,
    [MMSReasonCode]             VARCHAR (10) NULL,
    [CaliforniaReasonCode]      VARCHAR (10) NULL,
    [ProducingStatus]           INT          NULL,
    [ProducingMethod]           INT          NULL,
    [TempInteger]               INT          NULL,
    [DateTimeStamp]             DATETIME     NULL,
    [UserDateStamp]             DATETIME     NULL,
    [UserTimeStamp]             CHAR (8)     NULL,
    [UserID]                    INT          NULL,
    CONSTRAINT [PK_DowntimeCodeTb] PRIMARY KEY CLUSTERED ([DowntimeCode] ASC)
);

