CREATE TABLE [dbo].[EquipmentAllocationTypeTb] (
    [AllocationType]            INT              NOT NULL,
    [AllocationName]            VARCHAR (50)     NULL,
    [Description]               VARCHAR (500)    NULL,
    [ActiveFlag]                INT              NULL,
    [s_EquipmentType]           INT              NULL,
    [s_MeasurementPointRole]    INT              NULL,
    [s_ProductCode]             INT              NULL,
    [s_ProductType]             INT              NULL,
    [s_DispositionCode]         INT              NULL,
    [s_UnitsTypeFlag]           INT              NULL,
    [s_HoursOnTotal24Flag]      INT              NULL,
    [s_CarryForwardFlag]        INT              NULL,
    [d_AllocationMethod]        INT              NULL,
    [d_LeaseUseCoefficient]     FLOAT (53)       NULL,
    [d_LeaseUseCoefficientType] INT              NULL,
    [d_VolumeAutoPopulateFlag]  INT              NULL,
    [d_HoursOnAutopopulateFlag] INT              NULL,
    [m_AllocationMethod]        INT              NULL,
    [m_LeaseUseCoefficient]     FLOAT (53)       NULL,
    [m_LeaseUseCoefficientType] INT              NULL,
    [m_HoursOnOverwriteFlag]    INT              NULL,
    [m_MonthlyAutopopulateFlag] INT              NULL,
    [UserDateStamp]             DATETIME         NULL,
    [UserTimeStamp]             CHAR (8)         NULL,
    [UserID]                    INT              NULL,
    [RowUID]                    UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_EquipmentAllocationTypeTb] PRIMARY KEY CLUSTERED ([AllocationType] ASC)
);

