CREATE TABLE [dbo].[EquipmentTb] (
    [MerrickID]                 INT              NOT NULL,
    [EquipmentType]             INT              NULL,
    [EquipmentNumber]           VARCHAR (20)     NULL,
    [EquipmentName]             VARCHAR (30)     NULL,
    [EquipmentDescription]      VARCHAR (50)     NULL,
    [EquipmentOwnerID]          INT              NULL,
    [EquipmentOwnerLoc]         INT              NULL,
    [MeasurementPointRole]      INT              NULL,
    [AllocationTypeFlag]        INT              NULL,
    [AllocationTypeStartDate]   DATETIME         NULL,
    [AllocationOrder]           INT              NULL,
    [AllocationByComponent]     INT              NULL,
    [AllocAutoFlag]             INT              NULL,
    [AllocAutoStartDate]        DATETIME         NULL,
    [OutsideOperatedFlag]       INT              NULL,
    [UnitsTypeFlag]             INT              NULL,
    [UnitsConfigurableFlag]     INT              NULL,
    [DataEditStartDate]         DATETIME         NULL,
    [CarryForwardFlag]          INT              NULL,
    [ValidationDaysBack]        INT              NULL,
    [ParameterTemplateID]       INT              NULL,
    [ProductCode]               INT              NULL,
    [ProductType]               INT              NULL,
    [DispositionCode]           INT              NULL,
    [ProductionID]              VARCHAR (20)     NULL,
    [EngineeringID]             VARCHAR (20)     NULL,
    [AccountingID]              VARCHAR (30)     NULL,
    [ScadaID]                   VARCHAR (30)     NULL,
    [GatheringSystemID]         INT              NULL,
    [RouteID]                   INT              NULL,
    [AccountingTeamID]          INT              NULL,
    [DrillingTeamID]            INT              NULL,
    [ProductionTeamID]          INT              NULL,
    [GroupID]                   INT              NULL,
    [DivisionID]                INT              NULL,
    [FieldGroupID]              INT              NULL,
    [AreaID]                    INT              NULL,
    [PlatformID]                INT              NULL,
    [BatteryID]                 INT              NULL,
    [LeaseID]                   INT              NULL,
    [PlantID]                   INT              NULL,
    [StateID]                   INT              NULL,
    [CountyID]                  INT              NULL,
    [AllocationGroupID]         INT              NULL,
    [SuperPersonID]             INT              NULL,
    [ForemanPersonID]           INT              NULL,
    [PumperPersonID]            INT              NULL,
    [EngineerPersonID]          INT              NULL,
    [AccountantPersonID]        INT              NULL,
    [PurchaseOption]            INT              NULL,
    [DateInstalled]             DATETIME         NULL,
    [LeaseDescription]          VARCHAR (40)     NULL,
    [RentalCompanyUnitNumber]   VARCHAR (20)     NULL,
    [InternalUnitNumber]        VARCHAR (20)     NULL,
    [RentDate]                  DATETIME         NULL,
    [RentalTermsMonths]         INT              NULL,
    [AgreementNumber]           VARCHAR (20)     NULL,
    [ManufacturerBEID]          INT              NULL,
    [SerialNumber]              VARCHAR (20)     NULL,
    [SKUNumber]                 VARCHAR (20)     NULL,
    [ModelNumber]               VARCHAR (20)     NULL,
    [Make]                      VARCHAR (20)     NULL,
    [BaseRentalCharges]         FLOAT (53)       NULL,
    [InsuranceCharges]          FLOAT (53)       NULL,
    [MaintenanceCharges]        FLOAT (53)       NULL,
    [PumperCharges]             FLOAT (53)       NULL,
    [Horsepower]                FLOAT (53)       NULL,
    [NumberOfStages]            INT              NULL,
    [HoursOnTotal24Flag]        INT              NULL,
    [HoursOnDefaultFlag]        INT              NULL,
    [LeaseUseCoefficient]       FLOAT (53)       NULL,
    [LeaseUseCoefficientType]   INT              NULL,
    [VolumeAutoPopulateFlag]    INT              NULL,
    [AccountingUploadFlag]      INT              NULL,
    [EngineeringUploadFlag]     INT              NULL,
    [SealRequiredFlag]          INT              NULL,
    [ActiveFlag]                INT              NULL,
    [StartActiveDate]           DATETIME         NULL,
    [EndActiveDate]             DATETIME         NULL,
    [DeleteFlag]                INT              NULL,
    [AllocationDailyComment]    VARCHAR (500)    NULL,
    [AllocationMonthlyComment]  VARCHAR (500)    NULL,
    [SetupComments]             VARCHAR (500)    NULL,
    [PumperInstructions]        VARCHAR (500)    NULL,
    [TemplateRecordFlag]        INT              NULL,
    [TemplateRecordUsed]        INT              NULL,
    [MeterChildCount]           INT              NULL,
    [CompletionChildCount]      INT              NULL,
    [AllocationRunTwiceDaily]   INT              NULL,
    [AllocationRunTwiceMonthly] INT              NULL,
    [UserNumber1]               FLOAT (53)       NULL,
    [UserNumber1Label]          VARCHAR (30)     NULL,
    [UserNumber2]               FLOAT (53)       NULL,
    [UserNumber2Label]          VARCHAR (30)     NULL,
    [UserNumber3]               FLOAT (53)       NULL,
    [UserNumber3Label]          VARCHAR (30)     NULL,
    [UserNumber4]               FLOAT (53)       NULL,
    [UserNumber4Label]          VARCHAR (30)     NULL,
    [UserNumber5]               FLOAT (53)       NULL,
    [UserNumber5Label]          VARCHAR (30)     NULL,
    [UserNumber6]               FLOAT (53)       NULL,
    [UserNumber6Label]          VARCHAR (30)     NULL,
    [UserStringA]               VARCHAR (100)    NULL,
    [UserStringALabel]          VARCHAR (30)     NULL,
    [UserStringB]               VARCHAR (100)    NULL,
    [UserStringBLabel]          VARCHAR (30)     NULL,
    [UserStringC]               VARCHAR (100)    NULL,
    [UserStringCLabel]          VARCHAR (30)     NULL,
    [UserStringD]               VARCHAR (100)    NULL,
    [UserStringDLabel]          VARCHAR (30)     NULL,
    [UserStringE]               VARCHAR (100)    NULL,
    [UserStringELabel]          VARCHAR (30)     NULL,
    [UserStringF]               VARCHAR (100)    NULL,
    [UserStringFLabel]          VARCHAR (30)     NULL,
    [UserDailyNumber1Label]     VARCHAR (30)     NULL,
    [UserDailyNumber2Label]     VARCHAR (30)     NULL,
    [UserDailyNumber3Label]     VARCHAR (30)     NULL,
    [UserDailyNumber4Label]     VARCHAR (30)     NULL,
    [UserDailyNumber5Label]     VARCHAR (30)     NULL,
    [UserDailyNumber6Label]     VARCHAR (30)     NULL,
    [UserDailyStringALabel]     VARCHAR (30)     NULL,
    [UserDailyStringBLabel]     VARCHAR (30)     NULL,
    [PrintFlag]                 INT              NULL,
    [CompletionMethod]          INT              NULL,
    [DateTimeStamp]             DATETIME         NULL,
    [SystemMessage]             VARCHAR (80)     NULL,
    [CleanupDateStamp]          DATETIME         NULL,
    [CleanupTimeStamp]          CHAR (8)         NULL,
    [LastTransmission]          INT              NULL,
    [LastLoadDate]              DATETIME         NULL,
    [LastLoadTime]              CHAR (8)         NULL,
    [TransmitFlag]              INT              NULL,
    [RecordCreationDate]        DATETIME         NULL,
    [BLogicDateStamp]           DATETIME         NULL,
    [BLogicTimeStamp]           CHAR (8)         NULL,
    [UserDateStamp]             DATETIME         NULL,
    [UserTimeStamp]             CHAR (8)         NULL,
    [UserID]                    INT              NULL,
    [GasAnalysisSourceID]       INT              NULL,
    [GasanalysisSourceType]     INT              NULL,
    [CalculationStatusFlag]     INT              NOT NULL,
    [StatePointOfDisposition]   VARCHAR (20)     NULL,
    [LocationMerrickID]         INT              NULL,
    [LocationOrder]             INT              NULL,
    [FacilityID]                INT              NULL,
    [RowUID]                    UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_EquipmentTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC)
);

