CREATE TABLE [dbo].[GatheringSystemTb] (
    [GatheringSystemMerrickID]   INT              NOT NULL,
    [GatheringSystemID]          VARCHAR (20)     NULL,
    [GatheringSystemName]        VARCHAR (40)     NULL,
    [GatheringSystemNameShort]   VARCHAR (16)     NULL,
    [GatheringSystemDescription] VARCHAR (50)     NULL,
    [ProductType]                INT              NULL,
    [ActiveFlag]                 INT              NULL,
    [StartActiveDate]            DATETIME         NULL,
    [EndActiveDate]              DATETIME         NULL,
    [AllocationProcess]          INT              NULL,
    [AllocAutoFlag]              INT              NULL,
    [DataEditStartDate]          DATETIME         NULL,
    [LockEditingWithGSLock]      INT              NULL,
    [OwnerID]                    INT              NULL,
    [OwnerLoc]                   INT              NULL,
    [AccountingUploadFlag]       INT              NULL,
    [EngineeringUploadFlag]      INT              NULL,
    [AccountingID]               VARCHAR (30)     NULL,
    [ProductionID]               VARCHAR (30)     NULL,
    [EngineeringID]              VARCHAR (30)     NULL,
    [SuperPersonID]              INT              NULL,
    [ForemanPersonID]            INT              NULL,
    [PumperPersonID]             INT              NULL,
    [EngineerPersonID]           INT              NULL,
    [AccountantPersonID]         INT              NULL,
    [AccountingTeamID]           INT              NULL,
    [DrillingTeamID]             INT              NULL,
    [ProductionTeamID]           INT              NULL,
    [GroupID]                    INT              NULL,
    [DivisionID]                 INT              NULL,
    [FieldGroupID]               INT              NULL,
    [AreaID]                     INT              NULL,
    [PlatformID]                 INT              NULL,
    [BatteryID]                  INT              NULL,
    [LastAllocationDate]         DATETIME         NULL,
    [PrintFlag]                  INT              NULL,
    [DateTimeStamp]              DATETIME         NULL,
    [UserDateStamp]              DATETIME         NULL,
    [UserTimeStamp]              CHAR (8)         NULL,
    [UserID]                     INT              NULL,
    [RowUID]                     UNIQUEIDENTIFIER NOT NULL,
    [WalkUpFlag]                 INT              NULL,
    CONSTRAINT [PK_GatheringSystemTb] PRIMARY KEY CLUSTERED ([GatheringSystemMerrickID] ASC)
);

