CREATE TABLE [dbo].[MeterMonthlyDispTb] (
    [MerrickID]              INT          NOT NULL,
    [RecordDate]             DATETIME     NOT NULL,
    [SourceID]               INT          NOT NULL,
    [SourceType]             INT          NOT NULL,
    [RunTicketNumber]        VARCHAR (22) NOT NULL,
    [RunTicketDate]          DATETIME     NULL,
    [RunTicketFlag]          INT          NULL,
    [ProductCode]            INT          NULL,
    [ProductType]            INT          NULL,
    [DispositionCode]        INT          NULL,
    [OverwriteFlag]          INT          NULL,
    [GatheringSystemID]      INT          NULL,
    [SourceAllocationMethod] INT          NULL,
    [AllocBTUFactor]         FLOAT (53)   NULL,
    [AllocTemperature]       FLOAT (53)   NULL,
    [AllocPressureBase]      FLOAT (53)   NULL,
    [AllocGravity]           FLOAT (53)   NULL,
    [AllocWetDryFlag]        INT          NULL,
    [AllocOilVol]            FLOAT (53)   NULL,
    [AllocWaterVol]          FLOAT (53)   NULL,
    [AllocGasVolMCF]         FLOAT (53)   NULL,
    [AllocGasVolMMBTU]       FLOAT (53)   NULL,
    [AllocPlantGasMCF]       FLOAT (53)   NULL,
    [AllocPlantGasMMBTU]     FLOAT (53)   NULL,
    [AllocCO2Vol]            FLOAT (53)   NULL,
    [AllocOtherVol]          FLOAT (53)   NULL,
    [AllocOilProd]           FLOAT (53)   NULL,
    [AllocWaterProd]         FLOAT (53)   NULL,
    [AllocBeginningOil]      FLOAT (53)   NULL,
    [AllocBeginningWater]    FLOAT (53)   NULL,
    [AllocEndOil]            FLOAT (53)   NULL,
    [AllocEndWater]          FLOAT (53)   NULL,
    [AllocBasisGasVolMCF]    FLOAT (53)   NULL,
    [AllocBasisGasVolMMBTU]  FLOAT (53)   NULL,
    [AllocBasisOilVol]       FLOAT (53)   NULL,
    [AllocBasisWaterVol]     FLOAT (53)   NULL,
    [AllocBasisOilProd]      FLOAT (53)   NULL,
    [AllocBasisWaterProd]    FLOAT (53)   NULL,
    [DateTimeStamp]          DATETIME     NULL,
    [AllocationDateStamp]    DATETIME     NULL,
    [AllocationTimeStamp]    CHAR (8)     NULL,
    [UserDateStamp]          DATETIME     NULL,
    [UserTimeStamp]          CHAR (8)     NULL,
    [UserID]                 INT          NULL,
    [AllocMass]              FLOAT (53)   NOT NULL,
    CONSTRAINT [PK_MeterMonthlyDispTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC, [RecordDate] ASC, [SourceID] ASC, [SourceType] ASC, [RunTicketNumber] ASC)
);

