CREATE TABLE [dbo].[ProducingStatusTb] (
    [ProducingStatusMerrickID]  INT          NOT NULL,
    [ProducingDescription]      VARCHAR (50) NULL,
    [ProducingDescriptionShort] VARCHAR (6)  NULL,
    [ActiveFlag]                INT          NULL,
    [WellActiveIndicator]       INT          NULL,
    [HoursOnTotal24Flag]        INT          NULL,
    [AccountingID]              VARCHAR (30) NULL,
    [EngineeringID]             VARCHAR (30) NULL,
    [ProductionID]              VARCHAR (30) NULL,
    [RioStatusCode]             INT          NULL,
    [MmsMroCode]                VARCHAR (10) NULL,
    [MmsOgorCode]               VARCHAR (10) NULL,
    [NewMexicoStateCode]        VARCHAR (10) NULL,
    [UtahStateCode]             VARCHAR (10) NULL,
    [WyomingStateCode]          VARCHAR (10) NULL,
    [CaliforniaStateCode]       VARCHAR (10) NULL,
    [LouisianaStateCode]        VARCHAR (10) NULL,
    [ColoradoStateCode]         VARCHAR (10) NULL,
    [MississippiStateCode]      VARCHAR (10) NULL,
    [ArkansasStateCode]         VARCHAR (10) NULL,
    [MontanaStateCode]          VARCHAR (10) NULL,
    [NorthDakotaStateCode]      VARCHAR (10) NULL,
    [SouthDakotaStateCode]      VARCHAR (10) NULL,
    [AlabamaStateCode]          VARCHAR (10) NULL,
    [MichiganStateCode]         VARCHAR (10) NULL,
    [AlaskaStateCode]           VARCHAR (10) NULL,
    [TexasStateCode]            VARCHAR (10) NULL,
    [DateTimeStamp]             DATETIME     NULL,
    [UserDateStamp]             DATETIME     NULL,
    [UserTimeStamp]             CHAR (8)     NULL,
    [UserID]                    INT          NULL,
    CONSTRAINT [PK_ProducingStatusTb] PRIMARY KEY CLUSTERED ([ProducingStatusMerrickID] ASC)
);

