CREATE TABLE [dbo].[TankMonthlyTb] (
    [MerrickID]                  INT              NOT NULL,
    [RecordDate]                 DATETIME         NOT NULL,
    [ProductCode]                INT              NULL,
    [ProductType]                INT              NULL,
    [DataSourceCode]             INT              NULL,
    [AllocationByComponent]      INT              NULL,
    [GasEquivalentFactor]        FLOAT (53)       NULL,
    [BeginningNGL]               FLOAT (53)       NULL,
    [EndingNGL]                  FLOAT (53)       NULL,
    [TotalRunsNGL]               FLOAT (53)       NULL,
    [ProductionNGL]              FLOAT (53)       NULL,
    [NGLProduction]              FLOAT (53)       NULL,
    [AllocationComment]          VARCHAR (200)    NULL,
    [AllocationMethod]           INT              NULL,
    [AllocationOrder]            INT              NULL,
    [TankDataEntryFlag]          INT              NULL,
    [TankDataSummaryCode]        INT              NULL,
    [FirstDayFlag]               INT              NULL,
    [StartDate]                  DATETIME         NULL,
    [EndDate]                    DATETIME         NULL,
    [ProductionAllocDefault]     INT              NULL,
    [DispositionAllocDefault]    INT              NULL,
    [FactorComputationFlag]      INT              NULL,
    [TotalRunsPumperEntered]     INT              NULL,
    [TotalRunsHaulerEntered]     INT              NULL,
    [BeginningOil]               FLOAT (53)       NULL,
    [BeginningWater]             FLOAT (53)       NULL,
    [EndOil]                     FLOAT (53)       NULL,
    [EndWater]                   FLOAT (53)       NULL,
    [BSAndW]                     FLOAT (53)       NULL,
    [TopOpenFeet]                INT              NULL,
    [TopOpenInch]                INT              NULL,
    [TopOpenQuarter]             FLOAT (53)       NULL,
    [TopCloseFeet]               INT              NULL,
    [TopCloseInch]               INT              NULL,
    [TopCloseQuarter]            FLOAT (53)       NULL,
    [TopOpenTotalInches]         FLOAT (53)       NULL,
    [TopCloseTotalInches]        FLOAT (53)       NULL,
    [BottomOpenTotalInches]      FLOAT (53)       NULL,
    [BottomCloseTotalInches]     FLOAT (53)       NULL,
    [BottomOpenFeet]             INT              NULL,
    [BottomOpenInch]             INT              NULL,
    [BottomOpenQuarter]          FLOAT (53)       NULL,
    [BottomCloseFeet]            INT              NULL,
    [BottomCloseInch]            INT              NULL,
    [BottomCloseQuarter]         FLOAT (53)       NULL,
    [OilProduction]              FLOAT (53)       NULL,
    [WaterProduction]            FLOAT (53)       NULL,
    [TotalRunsOil]               FLOAT (53)       NULL,
    [TotalRunsWater]             FLOAT (53)       NULL,
    [TotalDispositionOil]        FLOAT (53)       NULL,
    [TotalDispositionWater]      FLOAT (53)       NULL,
    [TotalHaulerOil]             FLOAT (53)       NULL,
    [TotalHaulerWater]           FLOAT (53)       NULL,
    [TankVaporFactor]            FLOAT (53)       NULL,
    [TankVaporVolume]            FLOAT (53)       NULL,
    [MeasurementPointRole]       INT              NULL,
    [TankBatteryRole]            INT              NULL,
    [SuperPersonID]              INT              NULL,
    [ForemanPersonID]            INT              NULL,
    [PumperPersonID]             INT              NULL,
    [EngineerPersonID]           INT              NULL,
    [AccountantPersonID]         INT              NULL,
    [OperatorEntityID]           INT              NULL,
    [OperatorEntityLoc]          INT              NULL,
    [MasterTankBatteryID]        INT              NOT NULL,
    [PurchaserBEID]              INT              NULL,
    [PurchaserBELoc]             INT              NULL,
    [PurchaserTankID]            VARCHAR (20)     NULL,
    [WaterPurchaser]             INT              NULL,
    [HaulerBEID]                 INT              NULL,
    [HaulerBELoc]                INT              NULL,
    [HaulerTankNumber]           VARCHAR (20)     NULL,
    [WaterHauler]                INT              NULL,
    [ProductionID]               VARCHAR (30)     NULL,
    [EngineeringID]              VARCHAR (30)     NULL,
    [AccountingID]               VARCHAR (30)     NULL,
    [GatheringSystemID]          INT              NULL,
    [AccountingTeamID]           INT              NULL,
    [DrillingTeamID]             INT              NULL,
    [ProductionTeamID]           INT              NULL,
    [GroupID]                    INT              NULL,
    [DivisionID]                 INT              NULL,
    [FieldGroupID]               INT              NULL,
    [AreaID]                     INT              NULL,
    [TankBatteryID]              INT              NULL,
    [PlatformID]                 INT              NULL,
    [BatteryID]                  INT              NULL,
    [AllowNegativeInventoryFlag] INT              NULL,
    [StrappingDate]              DATETIME         NULL,
    [DispositionCode]            INT              NULL,
    [ActiveFlag]                 INT              NULL,
    [BackgroundTaskFlag]         INT              NULL,
    [DateTimeStamp]              DATETIME         NULL,
    [BLogicDateStamp]            DATETIME         NULL,
    [BLogicTimeStamp]            CHAR (8)         NULL,
    [AllocationDateStamp]        DATETIME         NULL,
    [AllocationTimeStamp]        CHAR (8)         NULL,
    [UserDateStamp]              DATETIME         NULL,
    [UserTimeStamp]              CHAR (8)         NULL,
    [UserID]                     INT              NULL,
    [LoadTransferFlag]           INT              NOT NULL,
    [CalculationStatusFlag]      INT              NOT NULL,
    [TankMonthlyInvSource]       INT              NOT NULL,
    [TankCompBegInvSource]       INT              NOT NULL,
    [RowUID]                     UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_TankMonthlyTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC, [RecordDate] ASC)
);

