CREATE TABLE [dbo].[TankTb] (
    [MerrickID]                    INT              NOT NULL,
    [TankType]                     INT              NULL,
    [TankConstruction]             INT              NULL,
    [TankGaugeType]                INT              NULL,
    [TankName]                     VARCHAR (40)     NULL,
    [TankDescription]              VARCHAR (30)     NULL,
    [UnitsTypeFlag]                INT              NULL,
    [UnitsConfigurableFlag]        INT              NULL,
    [DataEditStartDate]            DATETIME         NULL,
    [GasAnalysisSourceID]          INT              NULL,
    [GasAnalysisSourceType]        INT              NULL,
    [ProductCode]                  INT              NULL,
    [ProductType]                  INT              NULL,
    [MeasurementPointRole]         INT              NULL,
    [AllocationTypeFlag]           INT              NULL,
    [AllocationTypeStartDate]      DATETIME         NULL,
    [AllocAutoFlag]                INT              NULL,
    [AllocAutoStartDate]           DATETIME         NULL,
    [ParameterTemplateID]          INT              NULL,
    [FIFOAllocationFlag]           INT              NULL,
    [AllocationOrder]              INT              NULL,
    [IgnoreBSWVolumeFlag]          INT              NULL,
    [StandardGaugeTime]            CHAR (8)         NULL,
    [UseVaporAdjustmentFlag]       INT              NULL,
    [WaterCutAverageDays]          INT              NULL,
    [CarryForwardFlag]             INT              NULL,
    [ValidationDaysBack]           INT              NULL,
    [TankBatteryID]                INT              NULL,
    [TankBatteryRole]              INT              NULL,
    [MasterTankBatteryID]          INT              NULL,
    [SuperPersonID]                INT              NULL,
    [ForemanPersonID]              INT              NULL,
    [PumperPersonID]               INT              NULL,
    [EngineerPersonID]             INT              NULL,
    [AccountantPersonID]           INT              NULL,
    [OperatorEntityID]             INT              NULL,
    [OperatorEntityLoc]            INT              NULL,
    [OperatorTankNumber]           VARCHAR (20)     NULL,
    [OutsideOperatedFlag]          INT              NULL,
    [PurchaserBEID]                INT              NULL,
    [PurchaserBELoc]               INT              NULL,
    [PurchaserTankID]              VARCHAR (20)     NULL,
    [PurchaserLocationNumber]      VARCHAR (20)     NULL,
    [WaterPurchaser]               INT              NULL,
    [HaulerBEID]                   INT              NULL,
    [HaulerBELoc]                  INT              NULL,
    [HaulerTankNumber]             VARCHAR (20)     NULL,
    [WaterHauler]                  INT              NULL,
    [ProductionID]                 VARCHAR (30)     NULL,
    [EngineeringID]                VARCHAR (30)     NULL,
    [AccountingID]                 VARCHAR (30)     NULL,
    [ScadaID]                      VARCHAR (30)     NULL,
    [GatheringSystemID]            INT              NULL,
    [RouteID]                      INT              NULL,
    [AccountingTeamID]             INT              NULL,
    [DrillingTeamID]               INT              NULL,
    [ProductionTeamID]             INT              NULL,
    [GroupID]                      INT              NULL,
    [DivisionID]                   INT              NULL,
    [FieldGroupID]                 INT              NULL,
    [AreaID]                       INT              NULL,
    [PlatformID]                   INT              NULL,
    [BatteryID]                    INT              NULL,
    [LeaseID]                      INT              NULL,
    [PlantID]                      INT              NULL,
    [StateID]                      INT              NULL,
    [CountyID]                     INT              NULL,
    [AllocationGroupID]            INT              NULL,
    [AccountingUploadFlag]         INT              NULL,
    [EngineeringUploadFlag]        INT              NULL,
    [SealRequiredFlag]             INT              NULL,
    [ActiveFlag]                   INT              NULL,
    [StartActiveDate]              DATETIME         NULL,
    [EndActiveDate]                DATETIME         NULL,
    [DeleteFlag]                   INT              NULL,
    [ManufacturerBEID]             INT              NULL,
    [SerialNumber]                 VARCHAR (20)     NULL,
    [ModelNumber]                  VARCHAR (20)     NULL,
    [Make]                         VARCHAR (20)     NULL,
    [CompletionChildCount]         INT              NULL,
    [AllocationDailyComment]       VARCHAR (500)    NULL,
    [AllocationMonthlyComment]     VARCHAR (500)    NULL,
    [SetupComments]                VARCHAR (500)    NULL,
    [PumperInstructions]           VARCHAR (500)    NULL,
    [AllocationRunTwiceDaily]      INT              NULL,
    [AllocationRunTwiceMonthly]    INT              NULL,
    [TankSize]                     FLOAT (53)       NULL,
    [TopFeet]                      INT              NULL,
    [TopInches]                    INT              NULL,
    [TopQuarter]                   FLOAT (53)       NULL,
    [TopTotalInches]               FLOAT (53)       NULL,
    [BarrelsPerInch]               FLOAT (53)       NULL,
    [LastStrappingDate]            DATETIME         NULL,
    [UserNumber1]                  FLOAT (53)       NULL,
    [UserNumber1Label]             VARCHAR (30)     NULL,
    [UserNumber2]                  FLOAT (53)       NULL,
    [UserNumber2Label]             VARCHAR (30)     NULL,
    [UserNumber3]                  FLOAT (53)       NULL,
    [UserNumber3Label]             VARCHAR (30)     NULL,
    [UserNumber4]                  FLOAT (53)       NULL,
    [UserNumber4Label]             VARCHAR (30)     NULL,
    [UserNumber5]                  FLOAT (53)       NULL,
    [UserNumber5Label]             VARCHAR (30)     NULL,
    [UserNumber6]                  FLOAT (53)       NULL,
    [UserNumber6Label]             VARCHAR (30)     NULL,
    [UserStringA]                  VARCHAR (100)    NULL,
    [UserStringALabel]             VARCHAR (30)     NULL,
    [UserStringB]                  VARCHAR (100)    NULL,
    [UserStringBLabel]             VARCHAR (30)     NULL,
    [UserStringC]                  VARCHAR (100)    NULL,
    [UserStringCLabel]             VARCHAR (30)     NULL,
    [UserStringD]                  VARCHAR (100)    NULL,
    [UserStringDLabel]             VARCHAR (30)     NULL,
    [UserStringE]                  VARCHAR (100)    NULL,
    [UserStringELabel]             VARCHAR (30)     NULL,
    [UserStringF]                  VARCHAR (100)    NULL,
    [UserStringFLabel]             VARCHAR (30)     NULL,
    [IncludeInventoryInRegsFlag]   INT              NULL,
    [MmsFmpNumber]                 VARCHAR (20)     NULL,
    [MmsMeteringPoint]             VARCHAR (20)     NULL,
    [StatePointOfDisposition]      VARCHAR (20)     NULL,
    [StatePointOfDispositionWater] VARCHAR (20)     NULL,
    [StatePointOfDispositionOil]   VARCHAR (20)     NULL,
    [BarrelsPerQuarterInch]        FLOAT (53)       NULL,
    [StartDate]                    DATETIME         NULL,
    [EndDate]                      DATETIME         NULL,
    [DateTimeStamp]                DATETIME         NULL,
    [PrintFlag]                    INT              NULL,
    [SystemMessage]                VARCHAR (80)     NULL,
    [CleanupDateStamp]             DATETIME         NULL,
    [CleanupTimeStamp]             CHAR (8)         NULL,
    [LastTransmission]             INT              NULL,
    [LastLoadDate]                 DATETIME         NULL,
    [LastLoadTime]                 CHAR (8)         NULL,
    [TransmitFlag]                 INT              NULL,
    [RecordCreationDate]           DATETIME         NULL,
    [BLogicDateStamp]              DATETIME         NULL,
    [BLogicTimeStamp]              CHAR (8)         NULL,
    [UserDateStamp]                DATETIME         NULL,
    [UserTimeStamp]                CHAR (8)         NULL,
    [UserID]                       INT              NULL,
    [CalculationStatusFlag]        INT              NOT NULL,
    [LocationMerrickID]            INT              NULL,
    [LocationOrder]                INT              NULL,
    [FacilityID]                   INT              NULL,
    [Latitude]                     VARCHAR (12)     NULL,
    [Longitude]                    VARCHAR (12)     NULL,
    [TerminalID]                   INT              NULL,
    [PipelineID]                   INT              NULL,
    [SkipMidstreamCalc]            INT              NULL,
    [RowUID]                       UNIQUEIDENTIFIER NOT NULL,
    [InsulatedFlag]                INT              NULL,
    [ShellReferenceTemperature]    FLOAT (53)       NULL,
    [ShellExpansionCoefficient]    FLOAT (53)       NULL,
    CONSTRAINT [PK_TankTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC)
);

