CREATE TABLE [dbo].[WellTypeTb] (
    [WellTypeMerrickID]        INT          NOT NULL,
    [WellTypeName]             VARCHAR (20) NULL,
    [WellTypeDescription]      VARCHAR (50) NULL,
    [WellTypeDescriptionShort] VARCHAR (6)  NULL,
    [ActiveFlag]               INT          NULL,
    [AccountingID]             VARCHAR (10) NULL,
    [EngineeringID]            VARCHAR (10) NULL,
    [ProductionID]             VARCHAR (10) NULL,
    [RioWellType]              INT          NULL,
    [EntryScreenType]          INT          NOT NULL,
    [WyomingStateCode]         VARCHAR (10) NULL,
    [CaliforniaStateCode]      VARCHAR (10) NULL,
    [CaliforniaInjectionCode]  VARCHAR (10) NULL,
    [LouisianaStateCode]       VARCHAR (10) NULL,
    [ColoradoStateCode]        VARCHAR (10) NULL,
    [SouthDakotaStateCode]     VARCHAR (10) NULL,
    [SouthDakotaStateInjCode]  VARCHAR (10) NULL,
    [MississippiStateCode]     VARCHAR (10) NULL,
    [ArkansasStateCode]        VARCHAR (10) NULL,
    [MontanaStateCode]         VARCHAR (10) NULL,
    [NorthDakotaStateCode]     VARCHAR (10) NULL,
    [MMSCode]                  VARCHAR (10) NULL,
    [AlabamaStateCode]         VARCHAR (10) NULL,
    [UtahStateCode]            VARCHAR (10) NULL,
    [MichiganStateCode]        VARCHAR (10) NULL,
    [AlaskaStateCode]          VARCHAR (10) NULL,
    [TexasStateCode]           VARCHAR (10) NULL,
    [DateTimeStamp]            DATETIME     NULL,
    [UserDateStamp]            DATETIME     NULL,
    [UserTimeStamp]            CHAR (8)     NULL,
    [UserID]                   INT          NULL,
    CONSTRAINT [PK_WellTypeTb] PRIMARY KEY CLUSTERED ([WellTypeMerrickID] ASC)
);

