create view BOLO.V_ActualVBudget_ByWell AS
SELECT [Amount Type]
      ,[Date]
      ,[Cost Center]
      ,[Cost Center Number]
      ,[County]
      ,[District]
      ,[Area]
      ,[Field]
      ,[Operator]
      ,[Gross Oil Production Mbbl]
      ,[Gross NGL Production Mbbl]
      ,[Gross Gas Production MMcf]
      ,[Net Oil Production Mbbl]
      ,[Net NGL Production Mbbl]
      ,[Net Gas Production MMcf]
      ,[Gross Oil Price $/B]
      ,[Gross NGL Price $/B]
      ,[Gross Gas Price $/M]
      ,[Net Oil Sales M$]
      ,[Net NGL Sales M$]
      ,[Net Gas Sales M$]
      ,[Total Net Sales M$]
      ,[Production Taxes M$]
      ,[Ad Valorem Taxes M$]
      ,[Capital Costs M$]
      ,[Abandonment Cost M$]
      ,[Total OPEX]
      ,[Fixed Opex]
      ,[Variable Opex]
      ,[Methane Emission Monitoring]
      ,[Insurance]
      ,[Workovers]
      ,[WI Gas Production MMcf]
      ,[2018 Carry Over Capital]
  FROM [ETL].[ActualVBudgetByWell]