create view BOLO.V_AFEvActual as
SELECT [Cost Center]
      ,[Cost Center Number]
      ,[AFE Number]
      ,[Description]
      ,[8/8 AFE Budget]
      ,[8/8 Actual AFE Costs]
      ,[8/8 Actual (Over)/Under]
      ,[8/8 Actual % (Over)/Under]
      ,[Approval]
      ,[Net WI %]
      ,[Net AFE Budget]
      ,[Net Actual AFE Costs]
      ,[Net Actual (Over)/Under]
      ,[Net Actual % (Over)/Under]
      ,[Operator]
  FROM [ETL].[AFEvActual]