CREATE TABLE [dbo].[Combined_STG] (
    [Index]                               INT             NULL,
    [Source]                              VARCHAR (4000)  NULL,
    [TabName]                             VARCHAR (4000)  NULL,
    [Job Title]                           VARCHAR (4000)  NULL,
    [Job Code]                            VARCHAR (4000)  NULL,
    [Inc]                                 NUMERIC (18, 2) NULL,
    [Cos]                                 NUMERIC (18, 2) NULL,
    [Effective Date]                      VARCHAR (4000)  NULL,
    [Base 25th Percentile]                NUMERIC (18, 2) NULL,
    [Base 50th Percentile]                NUMERIC (18, 2) NULL,
    [Base 75th Percentile]                NUMERIC (18, 2) NULL,
    [Base 90th Percentile]                NUMERIC (18, 2) NULL,
    [Actual TC 25th Percentile]           NUMERIC (18, 2) NULL,
    [Actual TC 50th Percentile]           NUMERIC (18, 2) NULL,
    [Actual TC 75th Percentile]           NUMERIC (18, 2) NULL,
    [Actual TC 90th Percentile]           NUMERIC (18, 2) NULL,
    [Target TC 25th Percentile]           NUMERIC (18, 2) NULL,
    [Target TC 50th Percentile]           NUMERIC (18, 2) NULL,
    [Target TC 75th Percentile]           NUMERIC (18, 2) NULL,
    [Target TC 90th Percentile]           NUMERIC (18, 2) NULL,
    [LTI 25th Percentile]                 NUMERIC (18, 2) NULL,
    [LTI 50th Percentile]                 NUMERIC (18, 2) NULL,
    [LTI 75th Percentile]                 NUMERIC (18, 2) NULL,
    [LTI 90th Percentile]                 NUMERIC (18, 2) NULL,
    [Total Direct Actual 25th Percentile] NUMERIC (18, 2) NULL,
    [Total Direct Actual 50th Percentile] NUMERIC (18, 2) NULL,
    [Total Direct Actual 75th Percentile] NUMERIC (18, 2) NULL,
    [Total Direct Actual 90th Percentile] NUMERIC (18, 2) NULL,
    [Target TDC 25th Percentile]          NUMERIC (18, 2) NULL,
    [Target TDC 50th Percentile]          NUMERIC (18, 2) NULL,
    [Target TDC 75th Percentile]          NUMERIC (18, 2) NULL,
    [Target TDC 90th Percentile]          NUMERIC (18, 2) NULL,
    [Industry]                            VARCHAR (4000)  NULL,
    [Corporate-Noncorporate]              VARCHAR (4000)  NULL,
    [Rev Responsibility-Location-Other]   VARCHAR (4000)  NULL,
    [Family]                              VARCHAR (4000)  NULL,
    [Sub-Family]                          VARCHAR (4000)  NULL,
    [Specialization]                      VARCHAR (4000)  NULL,
    [Job Description]                     VARCHAR (4000)  NULL,
    [Mercer Job Type]                     VARCHAR (4000)  NULL,
    [AonHewitt Scope From]                VARCHAR (4000)  NULL,
    [AonHewitt Scope To]                  VARCHAR (4000)  NULL,
    [AonHewitt Scope Desc]                VARCHAR (4000)  NULL,
    [AI Percentage 25th Percentile]       NUMERIC (18, 2) NULL,
    [AI Percentage 50th Percentile]       NUMERIC (18, 2) NULL,
    [AI Percentage 75th Percentile]       NUMERIC (18, 2) NULL,
    [AI Percentage 90th Percentile]       NUMERIC (18, 2) NULL,
    [LTI Percent of Base 25th Percentile] NUMERIC (18, 2) NULL,
    [LTI Percent of Base 50th Percentile] NUMERIC (18, 2) NULL,
    [LTI Percent of Base 75th Percentile] NUMERIC (18, 2) NULL,
    [LTI Percent of Base 90th Percentile] NUMERIC (18, 2) NULL,
    [Calc AI % 25th Percentile]           NUMERIC (18, 2) NULL,
    [Calc AI % 50th Percentile]           NUMERIC (18, 2) NULL,
    [Calc AI % 75th Percentile]           NUMERIC (18, 2) NULL,
    [Calc AI % 90th Percentile]           NUMERIC (18, 2) NULL,
    [Calc LTI % 25th Percentile]          NUMERIC (18, 2) NULL,
    [Calc LTI % 50th Percentile]          NUMERIC (18, 2) NULL,
    [Calc LTI % 75th Percentile]          NUMERIC (18, 2) NULL,
    [Calc LTI % 90th Percentile]          NUMERIC (18, 2) NULL,
    [CreatedDate]                         VARCHAR (4000)  NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [RowNumberIndex]
    ON [dbo].[Combined_STG]([Index] ASC);

