CREATE TABLE [StageAries].[CHK_AC_PROPERTY] (
    [DBSKEY]          VARCHAR (12)  NULL,
    [PROPNUM]         VARCHAR (12)  NULL,
    [SEQNUM]          FLOAT (53)    NULL,
    [MAJOR]           VARCHAR (4)   NULL,
    [RSV_CAT]         VARCHAR (6)   NULL,
    [RSV_CLASS]       VARCHAR (10)  NULL,
    [PROP_NUM]        VARCHAR (10)  NULL,
    [ARIES_CODE]      VARCHAR (10)  NULL,
    [PARENT_CODE]     VARCHAR (10)  NULL,
    [LEASE]           VARCHAR (50)  NULL,
    [WELL_ID]         VARCHAR (10)  NULL,
    [REGION]          VARCHAR (30)  NULL,
    [STATE]           VARCHAR (2)   NULL,
    [COUNTY]          VARCHAR (20)  NULL,
    [FIELD]           VARCHAR (35)  NULL,
    [RESERVOIR]       VARCHAR (100) NULL,
    [OPERATOR]        VARCHAR (35)  NULL,
    [OPER_RSV]        VARCHAR (10)  NULL,
    [FIELD_OFC]       VARCHAR (25)  NULL,
    [HORIZONTAL]      BIT           NULL,
    [LATERAL_LEN]     FLOAT (53)    NULL,
    [LATERAL_DIR]     VARCHAR (10)  NULL,
    [SPUD_DATE]       DATETIME      NULL,
    [TD_DATE]         DATETIME      NULL,
    [DATE_COMP]       DATETIME      NULL,
    [FIRST_PROD]      DATETIME      NULL,
    [START_DATE]      DATETIME      NULL,
    [D_MIN_GAS]       FLOAT (53)    NULL,
    [D_MIN_OIL]       FLOAT (53)    NULL,
    [QUALIFIER]       VARCHAR (10)  NULL,
    [LAT_SURFACE]     FLOAT (53)    NULL,
    [LONG_SURFACE]    FLOAT (53)    NULL,
    [LAT_BH]          FLOAT (53)    NULL,
    [LONG_BH]         FLOAT (53)    NULL,
    [LOCATION]        VARCHAR (75)  NULL,
    [M_SECTION]       FLOAT (53)    NULL,
    [TOWNSHIP]        VARCHAR (6)   NULL,
    [RANGE]           VARCHAR (6)   NULL,
    [SPOT]            VARCHAR (20)  NULL,
    [TWN]             FLOAT (53)    NULL,
    [TWND]            VARCHAR (10)  NULL,
    [RAN]             FLOAT (53)    NULL,
    [RAND]            VARCHAR (10)  NULL,
    [MERIDIAN]        FLOAT (53)    NULL,
    [TEXAS_BLOCK]     VARCHAR (20)  NULL,
    [TEXAS_SURVEY]    VARCHAR (50)  NULL,
    [TEXAS_ABSTRACT]  VARCHAR (20)  NULL,
    [API]             VARCHAR (18)  NULL,
    [DWI_CODE]        VARCHAR (34)  NULL,
    [PROD_ID]         VARCHAR (34)  NULL,
    [DEPTH]           FLOAT (53)    NULL,
    [PB_DEPTH]        FLOAT (53)    NULL,
    [UPR_PERF]        FLOAT (53)    NULL,
    [LWR_PERF]        FLOAT (53)    NULL,
    [PIPELINE]        VARCHAR (100) NULL,
    [OIL_DIFF]        FLOAT (53)    NULL,
    [NGL_DIFF]        FLOAT (53)    NULL,
    [GAS_DIFF_ADD]    FLOAT (53)    NULL,
    [BTU]             FLOAT (53)    NULL,
    [SHRINK]          FLOAT (53)    NULL,
    [TYPE_INT]        VARCHAR (10)  NULL,
    [WI_BPO]          FLOAT (53)    NULL,
    [NRI_BPO]         FLOAT (53)    NULL,
    [WI_APO]          FLOAT (53)    NULL,
    [NRI_APO]         FLOAT (53)    NULL,
    [PAYOUT]          FLOAT (53)    NULL,
    [WI_APO2]         FLOAT (53)    NULL,
    [NRI_APO2]        FLOAT (53)    NULL,
    [PAYOUT2]         FLOAT (53)    NULL,
    [WI_CORP_BPO]     FLOAT (53)    NULL,
    [NRI_CORP_BPO]    FLOAT (53)    NULL,
    [WI_CORP_APO]     FLOAT (53)    NULL,
    [NRI_CORP_APO]    FLOAT (53)    NULL,
    [WI_CORP_APO2]    FLOAT (53)    NULL,
    [NRI_CORP_APO2]   FLOAT (53)    NULL,
    [ROI]             FLOAT (53)    NULL,
    [ORRI]            FLOAT (53)    NULL,
    [OPC_TYPE]        VARCHAR (10)  NULL,
    [OP_COST]         FLOAT (53)    NULL,
    [OP_OVRHD]        FLOAT (53)    NULL,
    [OPC_GAS]         FLOAT (53)    NULL,
    [OPC_OIL]         FLOAT (53)    NULL,
    [OPC_WTR]         FLOAT (53)    NULL,
    [WELLCT]          FLOAT (53)    NULL,
    [CAPITAL]         FLOAT (53)    NULL,
    [SALVAGE]         FLOAT (53)    NULL,
    [PLUGGING]        FLOAT (53)    NULL,
    [PRIOR_OIL]       FLOAT (53)    NULL,
    [PRIOR_GAS]       FLOAT (53)    NULL,
    [PRIOR_WTR]       FLOAT (53)    NULL,
    [PRIOR_OIL_DAILY] FLOAT (53)    NULL,
    [PRIOR_GAS_DAILY] FLOAT (53)    NULL,
    [NOTES1]          VARCHAR (255) NULL,
    [NOTES2]          VARCHAR (255) NULL,
    [PV10]            FLOAT (53)    NULL,
    [TC_AREA]         VARCHAR (255) NULL,
    [GGS]             VARCHAR (255) NULL,
    [PIPELINEAREA]    VARCHAR (50)  NULL,
    [TELL_CAP]        NVARCHAR (10) NULL,
    [GISNUM]          VARCHAR (10)  NULL,
    [EXCL_RUN]        NVARCHAR (10) NULL,
    [CHK_LATLEN]      FLOAT (53)    NULL,
    [CHK_RSV_CAT]     VARCHAR (50)  NULL,
    [CHK_RESERVOIR]   VARCHAR (50)  NULL,
    [PRE_DRILL_CAP]   FLOAT (53)    NULL,
    [DRILL_CAP]       FLOAT (53)    NULL,
    [COMP_CAP]        FLOAT (53)    NULL,
    [TIL_CAP]         FLOAT (53)    NULL,
    [POST_TIL_CAP]    FLOAT (53)    NULL,
    [PRE_DRILL_DATE]  DATETIME      NULL,
    [POST_TIL_DATE]   DATETIME      NULL,
    [START_DATE_NORM] DATETIME      NULL,
    [WELL_5]          VARCHAR (50)  NULL,
    [FIXED_START]     VARCHAR (50)  NULL,
    [START1]          DATETIME      NULL,
    [START2]          DATETIME      NULL,
    [START3]          DATETIME      NULL,
    [START4]          DATETIME      NULL,
    [TPC_OGIP]        FLOAT (53)    NULL,
    [TPC_T_EUR]       FLOAT (53)    NULL,
    [TC_AREA_GEO]     VARCHAR (255) NULL,
    [RISKED_LOC]      NVARCHAR (10) NULL,
    [RPT_GRPS]        VARCHAR (50)  NULL,
    [START5]          DATETIME      NULL
);

