CREATE TABLE [StageAries].[DVN_AC_PROPERTY] (
    [DBSKEY]             VARCHAR (12)  NULL,
    [PROPNUM]            VARCHAR (12)  NULL,
    [EVALUATE]           VARCHAR (1)   NULL,
    [SEQNUM]             INT           NULL,
    [RSV_CAT]            VARCHAR (10)  NULL,
    [STATUS]             VARCHAR (40)  NULL,
    [LEASE]              VARCHAR (200) NULL,
    [WELL_NUMBER]        VARCHAR (10)  NULL,
    [RESERVOIR]          VARCHAR (200) NULL,
    [FIELD]              VARCHAR (38)  NULL,
    [FIELD_GRP]          VARCHAR (30)  NULL,
    [TC_AREA]            VARCHAR (255) NULL,
    [COST_CENTER]        VARCHAR (255) NULL,
    [PRA_WELL_COMPL_NO]  VARCHAR (255) NULL,
    [WL_NO]              VARCHAR (5)   NULL,
    [WC_NO]              VARCHAR (3)   NULL,
    [API]                VARCHAR (17)  NULL,
    [LAND_API]           VARCHAR (255) NULL,
    [MAJOR]              VARCHAR (4)   NULL,
    [SPUD_DATE]          DATETIME      NULL,
    [IP_DATE]            DATETIME      NULL,
    [DRILL_DIRECTION]    VARCHAR (3)   NULL,
    [PRODUCING_METHOD]   VARCHAR (15)  NULL,
    [PROD_METH_LOOKUP]   VARCHAR (255) NULL,
    [PROD_METH_COMMENTS] VARCHAR (255) NULL,
    [POST16_SPUD]        VARCHAR (3)   NULL,
    [OPERATOR]           VARCHAR (75)  NULL,
    [OPERATED]           VARCHAR (1)   NULL,
    [LOCATION]           VARCHAR (25)  NULL,
    [COUNTY]             VARCHAR (20)  NULL,
    [STATE]              VARCHAR (2)   NULL,
    [DIVISION]           VARCHAR (20)  NULL,
    [PROJ_AREA]          VARCHAR (30)  NULL,
    [DISTRICT]           VARCHAR (30)  NULL,
    [REGION]             VARCHAR (50)  NULL,
    [IHS_PROD_NO]        VARCHAR (255) NULL,
    [LAT]                VARCHAR (10)  NULL,
    [LAT_DIR]            VARCHAR (1)   NULL,
    [LONGITUDE]          VARCHAR (10)  NULL,
    [LONG_DIR]           VARCHAR (1)   NULL,
    [GATH_SYSTEM]        VARCHAR (11)  NULL,
    [ACACIA_HEADER]      VARCHAR (3)   NULL,
    [WI]                 FLOAT (53)    NULL,
    [NRI]                FLOAT (53)    NULL,
    [WATER_DIST]         VARCHAR (50)  NULL,
    [DOW_WELL]           VARCHAR (3)   NULL,
    [BEHIND_PIPE]        VARCHAR (13)  NULL,
    [REFRAC]             VARCHAR (18)  NULL,
    [REFRAC_DATE]        DATETIME      NULL,
    [REFRAC_IP]          FLOAT (53)    NULL,
    [REFRAC_CAPEX]       FLOAT (53)    NULL,
    [SHRINK]             FLOAT (53)    NULL,
    [BTU_WH]             FLOAT (53)    NULL,
    [BTU_RES]            FLOAT (53)    NULL,
    [NGL_YIELD]          FLOAT (53)    NULL,
    [END_DT]             VARCHAR (12)  NULL,
    [START_DT]           VARCHAR (12)  NULL,
    [COMMENTS]           VARCHAR (255) NULL,
    [TELL_RSVCAT]        VARCHAR (255) NULL,
    [TELL_START1]        DATETIME      NULL,
    [TELL_START2]        DATETIME      NULL,
    [TELL_START3]        DATETIME      NULL,
    [TELL_START4]        DATETIME      NULL,
    [TELL_BHLAT]         FLOAT (53)    NULL,
    [TELL_BHLONG]        FLOAT (53)    NULL,
    [TELL_SHLAT]         FLOAT (53)    NULL,
    [TELL_SHLONG]        FLOAT (53)    NULL,
    [TELL_GISNUM]        VARCHAR (255) NULL,
    [TELL_LATLEN]        FLOAT (53)    NULL,
    [TELL_SHRINK]        FLOAT (53)    NULL,
    [TELL_BTU]           FLOAT (53)    NULL,
    [TELL_NOTES]         VARCHAR (255) NULL,
    [TELL_ZONE]          VARCHAR (255) NULL,
    [TELL_FPD]           DATETIME      NULL,
    [TELL_CAP]           VARCHAR (255) NULL,
    [TELL_TC_AREA]       VARCHAR (50)  NULL,
    [TELL_EUR_GAS]       FLOAT (53)    NULL,
    [TELL_EUR_OIL]       FLOAT (53)    NULL,
    [TELL_BCF_FT]        FLOAT (53)    NULL,
    [TELL_PV10]          FLOAT (53)    NULL,
    [TELL_PROP]          FLOAT (53)    NULL,
    [TELL_FLUID]         FLOAT (53)    NULL,
    [DRLG_CAPEX]         FLOAT (53)    NULL,
    [COMP_CAPEX]         FLOAT (53)    NULL,
    [COMP_DATE]          DATETIME      NULL,
    [FAC_CAPEX]          FLOAT (53)    NULL,
    [FAC_DATE]           DATETIME      NULL,
    [PLNGR_DATE]         DATETIME      NULL,
    [LAT_LENGTH]         FLOAT (53)    NULL,
    [TYPE_CURVE]         VARCHAR (50)  NULL,
    [TELL_WI]            FLOAT (53)    NULL,
    [TELL_NRI]           FLOAT (53)    NULL,
    [TELL_WELLTYPE]      VARCHAR (50)  NULL,
    [TELL_WELLNO]        FLOAT (53)    NULL,
    [TELL_SPACING]       FLOAT (53)    NULL,
    [TELL_REFRAC]        VARCHAR (50)  NULL,
    [TELL_REFRAC_DT]     DATETIME      NULL,
    [TELL_OPEX_REF]      VARCHAR (50)  NULL,
    [TELL_GP_REF]        VARCHAR (50)  NULL,
    [TELL_GPADJ_REF]     VARCHAR (50)  NULL,
    [TELL_SP_1000]       VARCHAR (50)  NULL,
    [TELL_SP_500]        VARCHAR (50)  NULL,
    [TELL_SP_750]        VARCHAR (50)  NULL,
    [TELL_OPEX_START]    VARCHAR (50)  NULL
);

