CREATE TABLE [StageAries].[ROCK_AC_PRODUCT] (
    [PROPNUM]      VARCHAR (12) NULL,
    [P_DATE]       DATETIME     NULL,
    [OIL]          FLOAT (53)   NULL,
    [GAS]          FLOAT (53)   NULL,
    [WATER]        FLOAT (53)   NULL,
    [DAYS_ON]      FLOAT (53)   NULL,
    [WELLS]        FLOAT (53)   NULL,
    [WTR_INJ]      FLOAT (53)   NULL,
    [WTR_INJ_DAYS] FLOAT (53)   NULL,
    [GAS_INJ]      FLOAT (53)   NULL,
    [GAS_INJ_DAYS] FLOAT (53)   NULL,
    [INJ_COUNT]    FLOAT (53)   NULL,
    [NGL]          FLOAT (53)   NULL,
    [CON]          FLOAT (53)   NULL,
    [ETHANE]       FLOAT (53)   NULL,
    [PROPANE]      FLOAT (53)   NULL,
    [BUTANE]       FLOAT (53)   NULL,
    [SULFUR]       FLOAT (53)   NULL,
    [USR1]         FLOAT (53)   NULL,
    [USR2]         FLOAT (53)   NULL,
    [USR3]         FLOAT (53)   NULL,
    [USR4]         FLOAT (53)   NULL
);

