CREATE TABLE [PEL].[V_Daily_Alloc_Prod_snapshot20190725] (
    [FlowNetworkName]    VARCHAR (50)  NULL,
    [UnitName]           VARCHAR (100) NULL,
    [Date]               DATETIME      NULL,
    [VolProdAllocGas]    FLOAT (53)    NULL,
    [VolProdAllocWater]  FLOAT (53)    NULL,
    [VolProdGathGas]     FLOAT (53)    NULL,
    [VolProdGathWater]   FLOAT (53)    NULL,
    [VolLostGas]         FLOAT (53)    NULL,
    [VolDispSaleGas]     FLOAT (53)    NULL,
    [VolDispFuelGas]     FLOAT (53)    NULL,
    [WorkingInterest]    FLOAT (53)    NULL,
    [Gas_NRI]            FLOAT (53)    NULL,
    [Tubing_Pressure]    FLOAT (53)    NULL,
    [Casing_Pressure]    FLOAT (53)    NULL,
    [Chokesize]          FLOAT (53)    NULL,
    [Producing_Method]   VARCHAR (50)  NULL,
    [Downtime_Type]      VARCHAR (20)  NULL,
    [Downtime_StartDate] DATETIME      NULL,
    [Downtime_Code]      VARCHAR (50)  NULL,
    [RegulatoryID]       VARCHAR (50)  NULL,
    [API]                VARCHAR (50)  NULL,
    [ARIES_Propnum]      VARCHAR (50)  NULL,
    [Operator]           VARCHAR (50)  NULL,
    [District]           VARCHAR (100) NULL,
    [Area]               VARCHAR (50)  NULL,
    [Field]              VARCHAR (50)  NULL,
    [State]              VARCHAR (50)  NULL,
    [County]             VARCHAR (50)  NULL,
    [PadName]            VARCHAR (50)  NULL,
    [GatheringSystem]    VARCHAR (50)  NULL,
    [Cost_Center_Number] FLOAT (53)    NULL,
    [FacilityName]       VARCHAR (255) NULL
);

