CREATE TABLE [PEL].[wvt_wvwelltesttransflowper_bkp20190730] (
    [idwell]             VARCHAR (32)   NOT NULL,
    [idrecparent]        VARCHAR (32)   NULL,
    [idrec]              VARCHAR (32)   NOT NULL,
    [bswend]             FLOAT (53)     NULL,
    [com]                VARCHAR (2000) NULL,
    [densitygasend]      FLOAT (53)     NULL,
    [densityoilend]      FLOAT (53)     NULL,
    [depthfluidlevelend] FLOAT (53)     NULL,
    [dttmend]            DATETIME       NULL,
    [dttmstart]          DATETIME       NULL,
    [efficiency]         FLOAT (53)     NULL,
    [h2send]             FLOAT (53)     NULL,
    [idrecgaugeused]     VARCHAR (32)   NULL,
    [idrecgaugeusedtk]   VARCHAR (26)   NULL,
    [phwaterend]         FLOAT (53)     NULL,
    [presbhend]          FLOAT (53)     NULL,
    [presbhinit]         FLOAT (53)     NULL,
    [prescasend]         FLOAT (53)     NULL,
    [prescasinit]        FLOAT (53)     NULL,
    [pressepend]         FLOAT (53)     NULL,
    [pressepinit]        FLOAT (53)     NULL,
    [prestubend]         FLOAT (53)     NULL,
    [prestubinit]        FLOAT (53)     NULL,
    [ratecondend]        FLOAT (53)     NULL,
    [rategasend]         FLOAT (53)     NULL,
    [rategasliftgas]     FLOAT (53)     NULL,
    [rateoilend]         FLOAT (53)     NULL,
    [ratewaterend]       FLOAT (53)     NULL,
    [salinitywaterend]   FLOAT (53)     NULL,
    [sandcutend]         FLOAT (53)     NULL,
    [szdiachoke]         FLOAT (53)     NULL,
    [tempbhend]          FLOAT (53)     NULL,
    [tempbhinit]         FLOAT (53)     NULL,
    [tempcasend]         FLOAT (53)     NULL,
    [tempcasinit]        FLOAT (53)     NULL,
    [tempsepend]         FLOAT (53)     NULL,
    [tempsepinit]        FLOAT (53)     NULL,
    [temptubend]         FLOAT (53)     NULL,
    [temptubinit]        FLOAT (53)     NULL,
    [typ]                VARCHAR (100)  NULL,
    [volumecondtotal]    FLOAT (53)     NULL,
    [volumegastotal]     FLOAT (53)     NULL,
    [volumeoiltotal]     FLOAT (53)     NULL,
    [volumewatertotal]   FLOAT (53)     NULL,
    [syslockmeui]        SMALLINT       NULL,
    [syslockchildrenui]  SMALLINT       NULL,
    [syslockme]          SMALLINT       NULL,
    [syslockchildren]    SMALLINT       NULL,
    [syslockdate]        DATETIME       NULL,
    [sysmoddate]         DATETIME       NULL,
    [sysmoduser]         VARCHAR (50)   NULL,
    [syscreatedate]      DATETIME       NULL,
    [syscreateuser]      VARCHAR (50)   NULL,
    [systag]             VARCHAR (255)  NULL
);

