CREATE TABLE [GIS].[RXT_NG_METER_POINTS] (
    [OBJECTID]          INT              NOT NULL,
    [PNTRID]            NVARCHAR (40)    NULL,
    [PNTDRN]            NVARCHAR (100)   NULL,
    [PNTPROPLOC]        NVARCHAR (100)   NULL,
    [PNTFERC]           NVARCHAR (5)     NULL,
    [PNTPLNAME]         NVARCHAR (80)    NULL,
    [PNTLOCNAME]        NVARCHAR (200)   NULL,
    [PNTSTDTYPE]        NVARCHAR (2)     NULL,
    [DESIGNCAP]         NUMERIC (38, 8)  NULL,
    [AVG2008OLD]        NUMERIC (38, 8)  NULL,
    [AVG2008NET]        NUMERIC (38, 8)  NULL,
    [AVG2008ABS]        NUMERIC (38, 8)  NULL,
    [AVG2009NET]        NUMERIC (38, 8)  NULL,
    [AVG2009ABS]        NUMERIC (38, 8)  NULL,
    [AVG2010NET]        NUMERIC (38, 8)  NULL,
    [AVG2010ABS]        NUMERIC (38, 8)  NULL,
    [AVG2011NET]        NUMERIC (38, 8)  NULL,
    [AVG2011ABS]        NUMERIC (38, 8)  NULL,
    [AVG2012NET]        NUMERIC (38, 8)  NULL,
    [AVG2012ABS]        NUMERIC (38, 8)  NULL,
    [AVG2013NET]        NUMERIC (38, 8)  NULL,
    [AVG2013ABS]        NUMERIC (38, 8)  NULL,
    [AVG2014NET]        NUMERIC (38, 8)  NULL,
    [AVG2014ABS]        NUMERIC (38, 8)  NULL,
    [AVG2015NET]        NUMERIC (38, 8)  NULL,
    [AVG2015ABS]        NUMERIC (38, 8)  NULL,
    [AVG2016NET]        NUMERIC (38, 8)  NULL,
    [AVG2016ABS]        NUMERIC (38, 8)  NULL,
    [AVG2017NET]        NUMERIC (38, 8)  NULL,
    [AVG2017ABS]        NUMERIC (38, 8)  NULL,
    [STATE]             NVARCHAR (35)    NULL,
    [COUNTRY]           NVARCHAR (254)   NULL,
    [UPDATE_NO]         NVARCHAR (254)   NULL,
    [RQCHECK]           NUMERIC (38, 8)  NULL,
    [Shape]             [sys].[geometry] NULL,
    [GDB_GEOMATTR_DATA] VARBINARY (MAX)  NULL,
    CONSTRAINT [ObjectID_pk] PRIMARY KEY CLUSTERED ([OBJECTID] ASC) WITH (FILLFACTOR = 75)
);

