CREATE TABLE [dbo].[OperationalData] (
    [id]                     VARCHAR (121)  NOT NULL,
    [dataSet]                SMALLINT       NULL,
    [indicator]              VARCHAR (46)   NULL,
    [periodType]             VARCHAR (3)    NULL,
    [periodFrom]             DATETIME       NULL,
    [periodTo]               DATETIME       NULL,
    [operatorKey]            VARCHAR (11)   NULL,
    [tsoEicCode]             VARCHAR (16)   NULL,
    [operatorLabel]          VARCHAR (43)   NULL,
    [pointKey]               VARCHAR (9)    NULL,
    [pointLabel]             VARCHAR (71)   NULL,
    [tsoItemIdentifier]      VARCHAR (22)   NULL,
    [directionKey]           VARCHAR (5)    NULL,
    [unit]                   VARCHAR (7)    NULL,
    [itemRemarks]            VARCHAR (2000) NULL,
    [generalRemarks]         VARCHAR (2000) NULL,
    [value]                  REAL           NULL,
    [lastUpdateDateTime]     DATETIME       NULL,
    [isUnlimited]            SMALLINT       NULL,
    [flowStatus]             VARCHAR (11)   NULL,
    [interruptionType]       VARCHAR (9)    NULL,
    [restorationInformation] VARCHAR (MAX)  NULL,
    [capacityType]           VARCHAR (13)   NULL,
    [capacityBookingStatus]  VARCHAR (9)    NULL,
    [isCamRelevant]          SMALLINT       NULL,
    [isNA]                   SMALLINT       NULL,
    [originalPeriodFrom]     VARCHAR (100)  NULL,
    [isCmpRelevant]          SMALLINT       NULL,
    [bookingPlatformKey]     VARCHAR (MAX)  NULL,
    [bookingPlatformLabel]   VARCHAR (MAX)  NULL,
    [bookingPlatformURL]     VARCHAR (MAX)  NULL,
    CONSTRAINT [pk_OperationalDataId] PRIMARY KEY CLUSTERED ([id] ASC)
);

