CREATE TABLE [dbo].[output] (
    [id]                     VARCHAR (108) NULL,
    [dataSet]                SMALLINT      NULL,
    [indicator]              VARCHAR (46)  NULL,
    [periodType]             VARCHAR (3)   NULL,
    [periodFrom]             DATETIME      NULL,
    [periodTo]               DATETIME      NULL,
    [operatorKey]            VARCHAR (11)  NULL,
    [tsoEicCode]             VARCHAR (16)  NULL,
    [operatorLabel]          VARCHAR (20)  NULL,
    [pointKey]               VARCHAR (9)   NULL,
    [pointLabel]             VARCHAR (70)  NULL,
    [tsoItemIdentifier]      VARCHAR (16)  NULL,
    [directionKey]           VARCHAR (5)   NULL,
    [unit]                   VARCHAR (7)   NULL,
    [itemRemarks]            VARCHAR (257) NULL,
    [generalRemarks]         VARCHAR (149) NULL,
    [value]                  REAL          NULL,
    [lastUpdateDateTime]     DATETIME      NULL,
    [isUnlimited]            SMALLINT      NULL,
    [flowStatus]             VARCHAR (11)  NULL,
    [interruptionType]       VARCHAR (9)   NULL,
    [restorationInformation] VARCHAR (MAX) NULL,
    [capacityType]           VARCHAR (13)  NULL,
    [capacityBookingStatus]  VARCHAR (5)   NULL,
    [isCamRelevant]          SMALLINT      NULL,
    [isNA]                   SMALLINT      NULL,
    [originalPeriodFrom]     VARCHAR (100) NULL,
    [isCmpRelevant]          SMALLINT      NULL,
    [bookingPlatformKey]     VARCHAR (MAX) NULL,
    [bookingPlatformLabel]   VARCHAR (MAX) NULL,
    [bookingPlatformURL]     VARCHAR (MAX) NULL
);

