CREATE TABLE [dbo].[OG_SALE_CTL_RV_AR_TRANS_IDX] (
    [subValueId]           VARCHAR (255) NOT NULL,
    [OG_SALE_CTL_RV_AR_ID] VARCHAR (255) NULL,
    [RV_AR_TRANS_INDEX]    VARCHAR (11)  NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OG_SALE_C_OG_SALE_C_16334]
    ON [dbo].[OG_SALE_CTL_RV_AR_TRANS_IDX]([OG_SALE_CTL_RV_AR_ID] ASC);

