CREATE TABLE [dbo].[OG_SALE_OWNER_SALE_INDEX] (
    [OG_SALE_OWNER_SALE_INDEX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                       VARCHAR (255) NULL,
    [OWNER_SALE_INDEX]            VARCHAR (10)  NULL,
    [OWNER_SALE_STATUS]           VARCHAR (5)   NULL,
    [REALLOC_OWNER_SALE_FLAG]     VARCHAR (7)   NULL,
    [time_stamp]                  DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OG_SALE_OWNER_SALE_INDEX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OG_SALE_O_u2_id_7293]
    ON [dbo].[OG_SALE_OWNER_SALE_INDEX]([u2_id] ASC);

