CREATE TABLE [dbo].[OGCC_OGP_IDX] (
    [OGCC_OGP_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]           VARCHAR (255) NULL,
    [OGP_PROP_INDEX]  VARCHAR (14)  NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OGCC_OGP_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OGCC_OGP_IDX_u2_id_in]
    ON [dbo].[OGCC_OGP_IDX]([u2_id] ASC);

