CREATE TABLE [dbo].[OGP_PROP_OPER] (
    [OGP_PROP_OPER_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [OPERATORS]        VARCHAR (9)   NULL,
    [OP_EFF_DATES]     DATETIME      NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OGP_PROP_OPER_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OGP_PROP_OPER_u2_id_in]
    ON [dbo].[OGP_PROP_OPER]([u2_id] ASC);

