CREATE TABLE [dbo].[OGP_PROP_INJ] (
    [OGP_PROP_INJ_ID] VARCHAR (255) NOT NULL,
    [u2_id]           VARCHAR (255) NULL,
    [INJ_PTS]         VARCHAR (8)   NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OGP_PROP_INJ_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OGP_PROP_INJ_u2_id_in]
    ON [dbo].[OGP_PROP_INJ]([u2_id] ASC);

