CREATE TABLE [dbo].[OGP_PROP_CTRC_SPLIT_DET] (
    [subValueId]             VARCHAR (255)   NOT NULL,
    [OGP_PROP_CTRC_SPLIT_ID] VARCHAR (255)   NULL,
    [SPLIT_DECIMALS_320C]    NUMERIC (19, 8) NULL,
    [SPLIT_GAS_PRDS_320C]    VARCHAR (5)     NULL,
    [SPLIT_NGL_PRDS_320C]    VARCHAR (5)     NULL,
    [SPLIT_OIL_PRDS_320C]    VARCHAR (5)     NULL,
    [SPLIT_PUNS_320C]        VARCHAR (17)    NULL,
    [time_stamp]             DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OGP_PROP__OGP_PROP__90028]
    ON [dbo].[OGP_PROP_CTRC_SPLIT_DET]([OGP_PROP_CTRC_SPLIT_ID] ASC);

