CREATE TABLE [dbo].[OGP_PROP_CNV_INFO] (
    [OGP_PROP_CNV_INFO_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [CNV_NAME]             VARCHAR (4)   NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OGP_PROP_CNV_INFO_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OGP_PROP_CNV_INFO_u2_id_in]
    ON [dbo].[OGP_PROP_CNV_INFO]([u2_id] ASC);

