CREATE TABLE [dbo].[OGP_PROP_TRANSPORTER] (
    [OGP_PROP_TRANSPORTER_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [TRANSPORTERS]            VARCHAR (11)  NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OGP_PROP_TRANSPORTER_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OGP_PROP_TRANSPORTER_u2_id_in]
    ON [dbo].[OGP_PROP_TRANSPORTER]([u2_id] ASC);

