CREATE TABLE [dbo].[OGP_PROP_CPARTY] (
    [OGP_PROP_CPARTY_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [CPARTIES]           VARCHAR (8)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OGP_PROP_CPARTY_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OGP_PROP_CPARTY_u2_id_in]
    ON [dbo].[OGP_PROP_CPARTY]([u2_id] ASC);

