CREATE TABLE [dbo].[OGP_PROP_UDF] (
    [OGP_PROP_UDF_ID]  VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [USER_DATA_FIELDS] VARCHAR (11)  NULL,
    [USER_DATA_VALUES] VARCHAR (11)  NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OGP_PROP_UDF_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OGP_PROP_UDF_u2_id_in]
    ON [dbo].[OGP_PROP_UDF]([u2_id] ASC);

