CREATE TABLE [dbo].[OGP_PROP_CTRC_SPLIT] (
    [OGP_PROP_CTRC_SPLIT_ID] VARCHAR (255)   NOT NULL,
    [u2_id]                  VARCHAR (255)   NULL,
    [SPLIT_EFF_DATES_320C]   DATETIME        NULL,
    [SPLIT_EXP_DATES_320C]   DATETIME        NULL,
    [SPLIT_TOTALS_320C]      NUMERIC (19, 8) NULL,
    [time_stamp]             DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([OGP_PROP_CTRC_SPLIT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OGP_PROP_CTRC_SPLIT_u2_id_in]
    ON [dbo].[OGP_PROP_CTRC_SPLIT]([u2_id] ASC);

