CREATE TABLE [dbo].[OGP_PROP_KS] (
    [OGP_PROP_KS_ID]      VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [KS_EXEMPT_CERTS]     VARCHAR (10)  NULL,
    [KS_EXEMPT_EFF_DATES] DATETIME      NULL,
    [KS_EXEMPT_EXP_DATES] DATETIME      NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OGP_PROP_KS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OGP_PROP_KS_u2_id_in]
    ON [dbo].[OGP_PROP_KS]([u2_id] ASC);

