CREATE TABLE [dbo].[OGP_PROP_TAX] (
    [OGP_PROP_TAX_ID]   VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [TAX_CLASSES]       VARCHAR (5)   NULL,
    [TAX_CLASS_PRODUCT] VARCHAR (7)   NULL,
    [TXCLASS_EFF_DATES] DATETIME      NULL,
    [TXCLASS_EXP_DATES] DATETIME      NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OGP_PROP_TAX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OGP_PROP_TAX_u2_id_in]
    ON [dbo].[OGP_PROP_TAX]([u2_id] ASC);

