CREATE TABLE [dbo].[OWN_CHANGE_OWN] (
    [OWN_CHANGE_OWN_ID]  VARCHAR (255)   NOT NULL,
    [u2_id]              VARCHAR (255)   NULL,
    [OVERRIDE_PAY_CODES] VARCHAR (5)     NULL,
    [SHARES]             NUMERIC (19, 8) NULL,
    [TARGET_OWNERS]      VARCHAR (9)     NULL,
    [TOTAL_ENTERED]      NUMERIC (19, 8) NULL,
    [time_stamp]         DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([OWN_CHANGE_OWN_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OWN_CHANGE_OWN_u2_id_in]
    ON [dbo].[OWN_CHANGE_OWN]([u2_id] ASC);

