CREATE TABLE [dbo].[OWN_CHANGE_INT_TP] (
    [OWN_CHANGE_INT_TP_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [LD_INTEREST_TYPES]    VARCHAR (3)   NULL,
    [RV_INTEREST_TYPES]    VARCHAR (3)   NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OWN_CHANGE_INT_TP_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OWN_CHANGE_INT_TP_u2_id_in]
    ON [dbo].[OWN_CHANGE_INT_TP]([u2_id] ASC);

