CREATE TABLE [dbo].[OWN_CHANGE_OS_IDX] (
    [OWN_CHANGE_OS_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [OWNER_SALE_INDEX]     VARCHAR (8)   NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OWN_CHANGE_OS_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OWN_CHANGE_OS_IDX_u2_id_in]
    ON [dbo].[OWN_CHANGE_OS_IDX]([u2_id] ASC);

