CREATE TABLE [dbo].[OWN_CHANGE_CC_MDECK_INDEX] (
    [subValueId]       VARCHAR (255) NOT NULL,
    [OWN_CHANGE_CC_ID] VARCHAR (255) NULL,
    [CC_MDECK_INDEX]   VARCHAR (8)   NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OWN_CHANG_OWN_CHANG_5439]
    ON [dbo].[OWN_CHANGE_CC_MDECK_INDEX]([OWN_CHANGE_CC_ID] ASC);

