CREATE TABLE [dbo].[OWNER_SALE_CUTBACK_VOUCHERS] (
    [subValueId]        VARCHAR (255) NOT NULL,
    [OWNER_SALE_ADJ_ID] VARCHAR (255) NULL,
    [CUTBACK_VOUCHERS]  VARCHAR (15)  NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OWNER_SAL_OWNER_SAL_23700]
    ON [dbo].[OWNER_SALE_CUTBACK_VOUCHERS]([OWNER_SALE_ADJ_ID] ASC);

