CREATE TABLE [dbo].[OWNER_BAL_INV_SALE_DT] (
    [subValueId]                 VARCHAR (255) NOT NULL,
    [OWNER_BAL_INV_ACCTG_PER_ID] VARCHAR (255) NULL,
    [INVERTED_SALE_DATES]        DATETIME      NULL,
    [time_stamp]                 DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OWNER_BAL_OWNER_BAL_11297]
    ON [dbo].[OWNER_BAL_INV_SALE_DT]([OWNER_BAL_INV_ACCTG_PER_ID] ASC);

