CREATE TABLE [dbo].[OWNER_VOL] (
    [u2_id]                        VARCHAR (255)   NOT NULL,
    [ACCTG_PERIOD]                 DATETIME        NULL,
    [ADJ_TAKE_VOL1]                NUMERIC (19, 2) NULL,
    [ADJ_TAKE_VOL2]                NUMERIC (19, 2) NULL,
    [ADJ_TYPE_CODE]                VARCHAR (4)     NULL,
    [COMPANY]                      VARCHAR (7)     NULL,
    [CTRC_VOL_ID]                  VARCHAR (11)    NULL,
    [DIV_ID]                       VARCHAR (10)    NULL,
    [DIV_SESSION]                  VARCHAR (4)     NULL,
    [ENTITLED_VOL1]                NUMERIC (19, 2) NULL,
    [ENTITLED_VOL2]                NUMERIC (19, 2) NULL,
    [ENTITLEMENT_DELIVERED_MCFS]   NUMERIC (19, 2) NULL,
    [ENTITLEMENT_DELIVERED_MMBTUS] NUMERIC (19, 2) NULL,
    [ENTITLEMENT_INTEREST]         NUMERIC (19, 8) NULL,
    [ENTITLEMENT_PRODUCED_MCFS]    NUMERIC (19, 2) NULL,
    [ENTITLEMENT_PRODUCED_MMBTUS]  NUMERIC (19, 2) NULL,
    [GAS_BAL_ONLY_FLAG]            VARCHAR (7)     NULL,
    [GROSS_VALUE]                  NUMERIC (19, 2) NULL,
    [INTEREST_TYPE]                VARCHAR (8)     NULL,
    [OWNER]                        VARCHAR (10)    NULL,
    [OWNER_BAL_DATE]               DATETIME        NULL,
    [POSTED_DATE]                  DATETIME        NULL,
    [PPL_STMT_ID]                  VARCHAR (17)    NULL,
    [PRD_BAL_ADJ_ID]               VARCHAR (14)    NULL,
    [PRD_BAL_MAN_ID]               VARCHAR (11)    NULL,
    [PRODUCT]                      VARCHAR (7)     NULL,
    [REVERSAL_OWNER_VOL_ID]        VARCHAR (9)     NULL,
    [SALE_DATE]                    DATETIME        NULL,
    [SOURCE_OWNER_VOL_ID]          VARCHAR (9)     NULL,
    [TAKEN_DELIVERED_MCFS]         NUMERIC (19, 2) NULL,
    [TAKEN_DELIVERED_MMBTUS]       NUMERIC (19, 2) NULL,
    [TAKEN_PRODUCED_MCFS]          NUMERIC (19, 2) NULL,
    [TAKEN_PRODUCED_MMBTUS]        NUMERIC (19, 2) NULL,
    [TAKE_VOL1]                    NUMERIC (19, 2) NULL,
    [TAKE_VOL2]                    NUMERIC (19, 2) NULL,
    [UPDATE_PGM]                   VARCHAR (14)    NULL,
    [WELL]                         VARCHAR (10)    NULL,
    [time_stamp]                   DATETIME        NULL,
    [u2_checksum]                  VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

