CREATE TABLE [dbo].[OWNER_SALE_REPLACEMENT_CPTS] (
    [subValueId]                   VARCHAR (255) NOT NULL,
    [OWNER_SALE_REPLACEMENT_ID]    VARCHAR (255) NULL,
    [REPLACEMENT_CPTS]             VARCHAR (7)   NULL,
    [REPLACEMENT_OWN_CHANGE_INDEX] VARCHAR (10)  NULL,
    [time_stamp]                   DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OWNER_SAL_OWNER_SAL_92377]
    ON [dbo].[OWNER_SALE_REPLACEMENT_CPTS]([OWNER_SALE_REPLACEMENT_ID] ASC);

