CREATE TABLE [dbo].[OWNER_SALE_ACCTG_PER] (
    [OWNER_SALE_ACCTG_PER_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [ACCTG_PERIODS]           DATETIME      NULL,
    [ACCTS]                   VARCHAR (9)   NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OWNER_SALE_ACCTG_PER_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OWNER_SALE_ACCTG_PER_u2_id_in]
    ON [dbo].[OWNER_SALE_ACCTG_PER]([u2_id] ASC);

