CREATE TABLE [dbo].[OWNER_VOL_VOL_IDX] (
    [OWNER_VOL_VOL_IDX_ID]  VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [ALLOC_OWNER_VOL_INDEX] VARCHAR (9)   NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OWNER_VOL_VOL_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OWNER_VOL_VOL_IDX_u2_id_in]
    ON [dbo].[OWNER_VOL_VOL_IDX]([u2_id] ASC);

