CREATE TABLE [dbo].[OWNER_SALE_CYCLE_PER] (
    [OWNER_SALE_CYCLE_PER_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [CYCLE_PERIODS]           DATETIME      NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OWNER_SALE_CYCLE_PER_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OWNER_SALE_CYCLE_PER_u2_id_in]
    ON [dbo].[OWNER_SALE_CYCLE_PER]([u2_id] ASC);

