CREATE TABLE [dbo].[OWNER_JIB_ADJ] (
    [OWNER_JIB_ADJ_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [ADJ_PERIODS]      DATETIME      NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OWNER_JIB_ADJ_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OWNER_JIB_ADJ_u2_id_in]
    ON [dbo].[OWNER_JIB_ADJ]([u2_id] ASC);

