CREATE TABLE [dbo].[OWNER_PRICE_INT_TPS] (
    [subValueId]            VARCHAR (255) NOT NULL,
    [OWNER_PRICE_EFF_DT_ID] VARCHAR (255) NULL,
    [INT_TYPES]             VARCHAR (4)   NULL,
    [PRICE_METHODS]         VARCHAR (10)  NULL,
    [VOLUME_METHODS]        VARCHAR (10)  NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OWNER_PRI_OWNER_PRI_56336]
    ON [dbo].[OWNER_PRICE_INT_TPS]([OWNER_PRICE_EFF_DT_ID] ASC);

