CREATE TABLE [dbo].[OWNER_JIB_ADJ_TRANS] (
    [subValueId]       VARCHAR (255) NOT NULL,
    [OWNER_JIB_ADJ_ID] VARCHAR (255) NULL,
    [ADJ_TYPES]        VARCHAR (4)   NULL,
    [TRANS_DATES]      DATETIME      NULL,
    [TRANS_INDEX]      VARCHAR (9)   NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OWNER_JIB_OWNER_JIB_57636]
    ON [dbo].[OWNER_JIB_ADJ_TRANS]([OWNER_JIB_ADJ_ID] ASC);

