CREATE TABLE [dbo].[PAY_CODE_CHANGE_BDECK] (
    [PAY_CODE_CHANGE_BDECK_ID] VARCHAR (255) NOT NULL,
    [u2_id]                    VARCHAR (255) NULL,
    [BDECK_INDEX]              VARCHAR (8)   NULL,
    [BDECK_SESSIONS]           VARCHAR (7)   NULL,
    [time_stamp]               DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PAY_CODE_CHANGE_BDECK_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PAY_CODE_CHANGE_BDECK_u2_id_in]
    ON [dbo].[PAY_CODE_CHANGE_BDECK]([u2_id] ASC);

