CREATE TABLE [dbo].[PAY_CODE_CHANGE_OS_IDX] (
    [PAY_CODE_CHANGE_OS_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                     VARCHAR (255) NULL,
    [OWNER_SALE_INDEX]          VARCHAR (7)   NULL,
    [time_stamp]                DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PAY_CODE_CHANGE_OS_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PAY_CODE__u2_id_3609]
    ON [dbo].[PAY_CODE_CHANGE_OS_IDX]([u2_id] ASC);

