CREATE TABLE [dbo].[PAY_CODE_CHANGE_LDECK] (
    [PAY_CODE_CHANGE_LDECK_ID] VARCHAR (255) NOT NULL,
    [u2_id]                    VARCHAR (255) NULL,
    [LDECK_INDEX]              VARCHAR (8)   NULL,
    [LDECK_SESSIONS]           VARCHAR (7)   NULL,
    [time_stamp]               DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PAY_CODE_CHANGE_LDECK_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PAY_CODE_CHANGE_LDECK_u2_id_in]
    ON [dbo].[PAY_CODE_CHANGE_LDECK]([u2_id] ASC);

