CREATE TABLE [dbo].[PAYOUT_CTRC_IDX] (
    [PAYOUT_CTRC_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [CONTRACT_INDEX]     VARCHAR (8)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PAYOUT_CTRC_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PAYOUT_CTRC_IDX_u2_id_in]
    ON [dbo].[PAYOUT_CTRC_IDX]([u2_id] ASC);

