CREATE TABLE [dbo].[PDECK_SESS] (
    [PDECK_SESS_ID]        VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [ASSIGN_SRC_INTERESTS] VARCHAR (11)  NULL,
    [ASSIGN_SRC_INVESTORS] VARCHAR (7)   NULL,
    [CHANGE_DATES]         DATETIME      NULL,
    [CHG_AUTHORIZATION_NO] VARCHAR (10)  NULL,
    [CONTROL_FLAG]         VARCHAR (4)   NULL,
    [EFF_DATES]            DATETIME      NULL,
    [EXPLANATIONS]         VARCHAR (30)  NULL,
    [SESSIONS]             VARCHAR (4)   NULL,
    [SESSION_APPRS]        VARCHAR (3)   NULL,
    [SESSION_APPR_DATES]   DATETIME      NULL,
    [SESSION_STATUS]       VARCHAR (4)   NULL,
    [SESSION_USER_ID]      VARCHAR (9)   NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PDECK_SESS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PDECK_SESS_u2_id_in]
    ON [dbo].[PDECK_SESS]([u2_id] ASC);

