CREATE TABLE [dbo].[POR_WELL_AUDIT] (
    [POR_WELL_AUDIT_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [SYSTEM_DATE]       DATETIME      NULL,
    [SYSTEM_TIME]       VARCHAR (8)   NULL,
    [SYSTEM_USER_ID]    VARCHAR (5)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([POR_WELL_AUDIT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [POR_WELL_AUDIT_u2_id_in]
    ON [dbo].[POR_WELL_AUDIT]([u2_id] ASC);

