CREATE TABLE [dbo].[POR_WELL_DET] (
    [subValueId]            VARCHAR (255) NOT NULL,
    [POR_WELL_FLAT_RATE_ID] VARCHAR (255) NULL,
    [FLAT_RATE_GAS_INCOMES] NUMERIC (9)   NULL,
    [FLAT_RATE_OIL_INCOMES] NUMERIC (9)   NULL,
    [FLAT_RATE_OWNERS]      VARCHAR (9)   NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [POR_WELL__POR_WELL__83016]
    ON [dbo].[POR_WELL_DET]([POR_WELL_FLAT_RATE_ID] ASC);

