CREATE TABLE [dbo].[PPL_SALE_NGL_OG_IDX] (
    [PPL_SALE_NGL_OG_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [OG_SALE_DET_INDEX]      VARCHAR (17)  NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PPL_SALE_NGL_OG_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PPL_SALE_NGL_OG_IDX_u2_id_in]
    ON [dbo].[PPL_SALE_NGL_OG_IDX]([u2_id] ASC);

