CREATE TABLE [dbo].[PPL_STMT_CTRC_IDX] (
    [PPL_STMT_CTRC_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [CTRC_VOL_INDEX]       VARCHAR (14)  NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PPL_STMT_CTRC_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PPL_STMT_CTRC_IDX_u2_id_in]
    ON [dbo].[PPL_STMT_CTRC_IDX]([u2_id] ASC);

