CREATE TABLE [dbo].[PPL_STMT_PROP_CTRC] (
    [subValueId]              VARCHAR (255) NOT NULL,
    [PPL_STMT_PROP_ID]        VARCHAR (255) NULL,
    [WELL_CONTRACTS]          VARCHAR (14)  NULL,
    [WELL_CONTRACT_PROD_VOLS] VARCHAR (15)  NULL,
    [WELL_CONTRACT_STMT_VOLS] VARCHAR (15)  NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PPL_STMT__PPL_STMT__97625]
    ON [dbo].[PPL_STMT_PROP_CTRC]([PPL_STMT_PROP_ID] ASC);

