CREATE TABLE [dbo].[PPL_STMT] (
    [u2_id]              VARCHAR (255)   NOT NULL,
    [ACCTG_PERIOD]       DATETIME        NULL,
    [ALLOC_DATE]         DATETIME        NULL,
    [ALLOC_METHOD]       VARCHAR (6)     NULL,
    [BTU_BASIS]          VARCHAR (10)    NULL,
    [BTU_FACTOR]         VARCHAR (10)    NULL,
    [COMPANY]            VARCHAR (3)     NULL,
    [COMPLETE_FLAG]      VARCHAR (8)     NULL,
    [CONTRA_PPL_STMT_ID] VARCHAR (8)     NULL,
    [GAS_BAL_ONLY_FLAG]  VARCHAR (7)     NULL,
    [GC_MEAS_PT]         VARCHAR (10)    NULL,
    [GRAVITY]            VARCHAR (7)     NULL,
    [MEAS_PT]            VARCHAR (10)    NULL,
    [PLANT_NGL_TOTAL]    NUMERIC (19, 2) NULL,
    [POSTED_DATE]        DATETIME        NULL,
    [PRESSURE_BASE]      VARCHAR (13)    NULL,
    [PRODUCT]            VARCHAR (7)     NULL,
    [PROD_VOL_TOTAL]     NUMERIC (19, 2) NULL,
    [RECEIPT_PT]         VARCHAR (11)    NULL,
    [REVERSAL_FLAG]      VARCHAR (4)     NULL,
    [SALE_DATE]          DATETIME        NULL,
    [SALE_TYPE]          VARCHAR (4)     NULL,
    [STMT_BTU_BASIS]     VARCHAR (5)     NULL,
    [STMT_BTU_FACTOR]    NUMERIC (19, 6) NULL,
    [STMT_PRESSURE_BASE] NUMERIC (19, 4) NULL,
    [STMT_REF]           VARCHAR (9)     NULL,
    [STMT_UOM]           VARCHAR (9)     NULL,
    [STMT_VOL_TOTAL]     NUMERIC (19, 2) NULL,
    [UOM]                VARCHAR (7)     NULL,
    [VALUE_DATE]         DATETIME        NULL,
    [time_stamp]         DATETIME        NULL,
    [u2_checksum]        VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

