CREATE TABLE [dbo].[PPL_STMT_DAILY_OVRD] (
    [PPL_STMT_DAILY_OVRD_ID]   VARCHAR (255) NOT NULL,
    [u2_id]                    VARCHAR (255) NULL,
    [DAILY_OVERRIDE_VOL_FLAGS] VARCHAR (8)   NULL,
    [time_stamp]               DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PPL_STMT_DAILY_OVRD_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PPL_STMT_DAILY_OVRD_u2_id_in]
    ON [dbo].[PPL_STMT_DAILY_OVRD]([u2_id] ASC);

