CREATE TABLE [dbo].[PPL_STMT_PROP_MKT] (
    [subValueId]                   VARCHAR (255)   NOT NULL,
    [PPL_STMT_PROP_ID]             VARCHAR (255)   NULL,
    [WELL_MARKETS]                 VARCHAR (12)    NULL,
    [WELL_MARKET_DELIVERED_MCFS]   NUMERIC (19, 2) NULL,
    [WELL_MARKET_DELIVERED_MMBTUS] NUMERIC (19, 2) NULL,
    [WELL_MARKET_PRODUCED_MCFS]    NUMERIC (19, 2) NULL,
    [WELL_MARKET_PRODUCED_MMBTUS]  NUMERIC (19, 2) NULL,
    [time_stamp]                   DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PPL_STMT__PPL_STMT__66759]
    ON [dbo].[PPL_STMT_PROP_MKT]([PPL_STMT_PROP_ID] ASC);

