CREATE TABLE [dbo].[PPL_STMT_PROP] (
    [PPL_STMT_PROP_ID] VARCHAR (255)   NOT NULL,
    [u2_id]            VARCHAR (255)   NULL,
    [PRODUCED_MCFS]    NUMERIC (19, 2) NULL,
    [PRODUCED_MMBTUS]  NUMERIC (19, 2) NULL,
    [WELLS]            VARCHAR (10)    NULL,
    [time_stamp]       DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([PPL_STMT_PROP_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PPL_STMT_PROP_u2_id_in]
    ON [dbo].[PPL_STMT_PROP]([u2_id] ASC);

