CREATE TABLE [dbo].[PRD_TRANS_ALLOC_IDX] (
    [PRD_TRANS_ALLOC_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [ALLOC_TRANS_INDEX]      VARCHAR (9)   NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PRD_TRANS_ALLOC_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PRD_TRANS_ALLOC_IDX_u2_id_in]
    ON [dbo].[PRD_TRANS_ALLOC_IDX]([u2_id] ASC);

