CREATE TABLE [dbo].[PRD_TRANS_CF_INS] (
    [subValueId]        VARCHAR (255)   NOT NULL,
    [PRD_TRANS_CASH_ID] VARCHAR (255)   NULL,
    [CF_INS_AMTS]       NUMERIC (19, 2) NULL,
    [CF_INS_COMPANIES]  VARCHAR (3)     NULL,
    [CF_POST_DATE]      DATETIME        NULL,
    [time_stamp]        DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PRD_TRANS_PRD_TRANS_70364]
    ON [dbo].[PRD_TRANS_CF_INS]([PRD_TRANS_CASH_ID] ASC);

