CREATE TABLE [dbo].[PRD_BAL_ADJ_ENT] (
    [PRD_BAL_ADJ_ENT_ID] VARCHAR (255)   NOT NULL,
    [u2_id]              VARCHAR (255)   NULL,
    [ADJ_VOL1S]          NUMERIC (19, 2) NULL,
    [ADJ_VOL2S]          NUMERIC (19, 2) NULL,
    [ENTITLEMENT_OWNERS] VARCHAR (9)     NULL,
    [ENTITLEMENT_VOL1S]  NUMERIC (19, 2) NULL,
    [ENTITLEMENT_VOL2S]  NUMERIC (19, 2) NULL,
    [TAKE_VOL1S]         NUMERIC (19, 2) NULL,
    [TAKE_VOL2S]         NUMERIC (19, 2) NULL,
    [time_stamp]         DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([PRD_BAL_ADJ_ENT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PRD_BAL_ADJ_ENT_u2_id_in]
    ON [dbo].[PRD_BAL_ADJ_ENT]([u2_id] ASC);

