CREATE TABLE [dbo].[PRD_TRANS_PRD_DISP] (
    [PRD_TRANS_PRD_DISP_ID] VARCHAR (255)   NOT NULL,
    [u2_id]                 VARCHAR (255)   NULL,
    [PRD_DISPS]             VARCHAR (6)     NULL,
    [PRD_DISP_AMTS]         NUMERIC (19, 2) NULL,
    [PRD_DISP_STAT2_AMTS]   NUMERIC (19, 2) NULL,
    [time_stamp]            DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([PRD_TRANS_PRD_DISP_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PRD_TRANS_PRD_DISP_u2_id_in]
    ON [dbo].[PRD_TRANS_PRD_DISP]([u2_id] ASC);

