CREATE TABLE [dbo].[PRICE_CTRC] (
    [u2_id]                          VARCHAR (255)  NOT NULL,
    [COMPANY]                        VARCHAR (3)    NULL,
    [COMPANY_CONTRACT]               VARCHAR (20)   NULL,
    [CONTRACT]                       VARCHAR (20)   NULL,
    [CONTRACTING_PARTY]              VARCHAR (8)    NULL,
    [CONTRACTING_PARTY_CONTRACT_REF] VARCHAR (10)   NULL,
    [CONTRACT_DATE]                  DATETIME       NULL,
    [CONTRACT_TYPE]                  VARCHAR (4)    NULL,
    [DEEMED_GRAVITY]                 NUMERIC (9, 1) NULL,
    [DEEMED_GRAVITY_EFF_DATE]        DATETIME       NULL,
    [DEEMED_GRAVITY_EXP_DATE]        DATETIME       NULL,
    [DESCRIPTION]                    VARCHAR (30)   NULL,
    [EFF_DATE]                       DATETIME       NULL,
    [EVERGREEN_DATE]                 DATETIME       NULL,
    [EXP_DATE]                       DATETIME       NULL,
    [OBA_FLAG]                       VARCHAR (3)    NULL,
    [OFP_PROP_GRP_KEY]               VARCHAR (10)   NULL,
    [PARENT_PTR_CONTRACT]            VARCHAR (8)    NULL,
    [PRICE_TIER]                     VARCHAR (5)    NULL,
    [PROPERTY]                       VARCHAR (10)   NULL,
    [PROPERTY_GROUP]                 VARCHAR (10)   NULL,
    [PURCHASE_CONTRACT_FLAG]         VARCHAR (4)    NULL,
    [P_OR_PG]                        VARCHAR (10)   NULL,
    [RESELL_CONTRACT_FLAG]           VARCHAR (4)    NULL,
    [RES_PTR_ASSOC_CTRC]             VARCHAR (8)    NULL,
    [RES_PTR_FLAG]                   VARCHAR (3)    NULL,
    [SOURCE_CTRC]                    VARCHAR (10)   NULL,
    [UPI_FLAG]                       VARCHAR (3)    NULL,
    [VOL_BAL_FLAG]                   VARCHAR (3)    NULL,
    [time_stamp]                     DATETIME       NULL,
    [u2_checksum]                    VARCHAR (25)   NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

