CREATE TABLE [dbo].[PRICE_CTRC_PROP_IDX] (
    [PRICE_CTRC_PROP_IDX_ID]         VARCHAR (255) NOT NULL,
    [u2_id]                          VARCHAR (255) NULL,
    [CONTRACTING_PARTY_PROPERTY_REF] VARCHAR (10)  NULL,
    [PROPERTY_INDEX]                 VARCHAR (15)  NULL,
    [time_stamp]                     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PRICE_CTRC_PROP_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PRICE_CTRC_PROP_IDX_u2_id_in]
    ON [dbo].[PRICE_CTRC_PROP_IDX]([u2_id] ASC);

