CREATE TABLE [dbo].[PRICE_CTRC_PRD] (
    [PRICE_CTRC_PRD_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [PRODUCT]           VARCHAR (3)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PRICE_CTRC_PRD_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PRICE_CTRC_PRD_u2_id_in]
    ON [dbo].[PRICE_CTRC_PRD]([u2_id] ASC);

