CREATE TABLE [dbo].[PRICE_CTRC_PROP_GRP] (
    [PRICE_CTRC_PROP_GRP_ID]          VARCHAR (255)   NOT NULL,
    [u2_id]                           VARCHAR (255)   NULL,
    [PROPERTY_GROUP_PROPERTY_ANALYST] VARCHAR (10)    NULL,
    [PROPERTY_GROUP_PROPERTY_COUNTY]  VARCHAR (10)    NULL,
    [PROPERTY_GROUP_PROPERTY_NAME]    VARCHAR (25)    NULL,
    [PROPERTY_GROUP_PROPERTY_STATE]   VARCHAR (2)     NULL,
    [PROPERTY_GROUP_PROPERTY_SULPHUR] NUMERIC (19, 4) NULL,
    [PROPERTY_GRP_PROP_COUNTY_NAME]   VARCHAR (15)    NULL,
    [time_stamp]                      DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([PRICE_CTRC_PROP_GRP_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PRICE_CTRC_PROP_GRP_u2_id_in]
    ON [dbo].[PRICE_CTRC_PROP_GRP]([u2_id] ASC);

