CREATE TABLE [dbo].[PROD_FAC_PRD_FACILITIES] (
    [subValueId]                              VARCHAR (255) NOT NULL,
    [PROD_FAC_PRD_UPSTREAM_ID]                VARCHAR (255) NULL,
    [UPSTREAM_ALLOC_METHODS]                  VARCHAR (11)  NULL,
    [UPSTREAM_CONNECTION_PRODUCES_GAS_LIFTS]  VARCHAR (10)  NULL,
    [UPSTREAM_CONNECTION_PRODUCES_INJECTIONS] VARCHAR (10)  NULL,
    [UPSTREAM_CONNECTION_TYPES]               VARCHAR (10)  NULL,
    [UPSTREAM_FACILITIES]                     VARCHAR (14)  NULL,
    [UPSTREAM_SUB_SYSTEMS]                    VARCHAR (8)   NULL,
    [UPSTREAM_VOL_METHODS]                    VARCHAR (11)  NULL,
    [time_stamp]                              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROD_FAC__PROD_FAC__23981]
    ON [dbo].[PROD_FAC_PRD_FACILITIES]([PROD_FAC_PRD_UPSTREAM_ID] ASC);

