CREATE TABLE [dbo].[PROD_FAC_PRD_UPSTREAM] (
    [PROD_FAC_PRD_UPSTREAM_ID] VARCHAR (255) NOT NULL,
    [u2_id]                    VARCHAR (255) NULL,
    [UPSTREAM_EFF_DATES]       DATETIME      NULL,
    [time_stamp]               DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PROD_FAC_PRD_UPSTREAM_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROD_FAC_PRD_UPSTREAM_u2_id_in]
    ON [dbo].[PROD_FAC_PRD_UPSTREAM]([u2_id] ASC);

