CREATE TABLE [dbo].[PROD_DAILY_CONN_TYPE] (
    [PROD_DAILY_CONN_TYPE_ID]    VARCHAR (255) NOT NULL,
    [u2_id]                      VARCHAR (255) NULL,
    [ALLOCATED_CONNECTION_TYPES] VARCHAR (9)   NULL,
    [time_stamp]                 DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PROD_DAILY_CONN_TYPE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROD_DAILY_CONN_TYPE_u2_id_in]
    ON [dbo].[PROD_DAILY_CONN_TYPE]([u2_id] ASC);

