CREATE TABLE [dbo].[PROD_DAILY_GATHERING_SYSTEMS] (
    [PROD_DAILY_GATHERING_SYSTEMS_ID] VARCHAR (255) NOT NULL,
    [u2_id]                           VARCHAR (255) NULL,
    [GATHERING_SYSTEMS]               VARCHAR (12)  NULL,
    [time_stamp]                      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PROD_DAILY_GATHERING_SYSTEMS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROD_DAIL_u2_id_84983]
    ON [dbo].[PROD_DAILY_GATHERING_SYSTEMS]([u2_id] ASC);

