CREATE TABLE [dbo].[PROD_MO_THEO_TRN] (
    [PROD_MO_THEO_TRN_ID] VARCHAR (255)   NOT NULL,
    [u2_id]               VARCHAR (255)   NULL,
    [TRANSFERS]           NUMERIC (19, 2) NULL,
    [time_stamp]          DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([PROD_MO_THEO_TRN_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROD_MO_THEO_TRN_u2_id_in]
    ON [dbo].[PROD_MO_THEO_TRN]([u2_id] ASC);

