CREATE TABLE [dbo].[PROD_FAC_PRD_ALLOC_PT] (
    [PROD_FAC_PRD_ALLOC_PT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                    VARCHAR (255) NULL,
    [ALLOC_PT_EFF_DATES]       DATETIME      NULL,
    [ALLOC_PT_EXP_DATES]       DATETIME      NULL,
    [ALLOC_PT_ORDER_NUM]       VARCHAR (5)   NULL,
    [ALLOC_PT_RELEVANCE]       VARCHAR (9)   NULL,
    [time_stamp]               DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PROD_FAC_PRD_ALLOC_PT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROD_FAC_PRD_ALLOC_PT_u2_id_in]
    ON [dbo].[PROD_FAC_PRD_ALLOC_PT]([u2_id] ASC);

