CREATE TABLE [dbo].[PROD_DAILY] (
    [u2_id]                        VARCHAR (255)   NOT NULL,
    [ALLOC_BEGIN_INVENTORY]        NUMERIC (19, 2) NULL,
    [ALLOC_BEGIN_WATER_INVENTORY]  NUMERIC (19, 2) NULL,
    [ALLOC_ENDING_INVENTORY]       NUMERIC (19, 2) NULL,
    [ALLOC_ENDING_WATER_INVENTORY] NUMERIC (19, 2) NULL,
    [ALLOC_GROSS_SALES]            NUMERIC (19, 2) NULL,
    [ALLOC_PROD_GROSS_VOL]         NUMERIC (19, 2) NULL,
    [ALLOC_PROD_STD_VOL]           NUMERIC (19, 2) NULL,
    [ALLOC_PROD_VOL]               NUMERIC (19, 2) NULL,
    [ALLOC_PROD_WATER_VOL]         NUMERIC (19, 2) NULL,
    [ALLOC_SALES]                  NUMERIC (19, 2) NULL,
    [ALLOC_SALES_MMBTU]            NUMERIC (19, 2) NULL,
    [ALLOC_STD_SALES]              NUMERIC (19, 2) NULL,
    [AV_DATE]                      VARCHAR (8)     NULL,
    [BEGIN_INVENTORY]              NUMERIC (19, 2) NULL,
    [BEGIN_WATER_INVENTORY]        NUMERIC (19, 2) NULL,
    [CALCULATED]                   VARCHAR (6)     NULL,
    [CASING_PRESSURE]              NUMERIC (9)     NULL,
    [CHANGE_DATE_TIME]             VARCHAR (8)     NULL,
    [CHANGE_FLAG]                  VARCHAR (3)     NULL,
    [CHANGE_USER_ID]               VARCHAR (6)     NULL,
    [CHOKE]                        VARCHAR (5)     NULL,
    [DAILY_REMARKS]                VARCHAR (210)   NULL,
    [DAYS_ON]                      VARCHAR (7)     NULL,
    [DOWN_END_OF_DAY]              VARCHAR (6)     NULL,
    [DOWN_HOURS]                   NUMERIC (19, 2) NULL,
    [DOWN_MINUTES]                 NUMERIC (9)     NULL,
    [DOWN_REASON]                  VARCHAR (6)     NULL,
    [ENDING_INVENTORY]             NUMERIC (19, 2) NULL,
    [ENDING_WATER_INVENTORY]       NUMERIC (19, 2) NULL,
    [ENTERED_BTU_FACTOR]           NUMERIC (19, 4) NULL,
    [ERR_STATUS]                   VARCHAR (6)     NULL,
    [GAS_PROD]                     NUMERIC (19, 2) NULL,
    [GATHERING_SUB_SYSTEM]         VARCHAR (6)     NULL,
    [GATHERING_SYSTEM]             VARCHAR (12)    NULL,
    [GATH_SUB_SYS_ID]              VARCHAR (12)    NULL,
    [GENERAL_PROD_ID]              VARCHAR (16)    NULL,
    [GL_DATE]                      VARCHAR (8)     NULL,
    [GRAVITY]                      NUMERIC (9, 1)  NULL,
    [GROSS_SALES]                  NUMERIC (19, 2) NULL,
    [INJECTED_VOL]                 NUMERIC (19, 2) NULL,
    [INJECTION_PRESSURE]           NUMERIC (19, 2) NULL,
    [MMBTU_SALES]                  NUMERIC (19, 2) NULL,
    [MODE_]                        VARCHAR (5)     NULL,
    [OIL_PROD]                     NUMERIC (19, 2) NULL,
    [ORPHAN_SOURCE_NODE]           VARCHAR (8)     NULL,
    [OUTPUT_MMBTU]                 NUMERIC (19, 2) NULL,
    [OUTPUT_VOL]                   NUMERIC (19, 2) NULL,
    [OUTPUT_WATER_VOL]             NUMERIC (19, 2) NULL,
    [PRODUCT]                      VARCHAR (5)     NULL,
    [PROD_DATE]                    DATETIME        NULL,
    [PROD_FAC_PRD_ID]              VARCHAR (16)    NULL,
    [PROD_GROSS_VOL]               NUMERIC (19, 2) NULL,
    [PROD_STD_VOL]                 NUMERIC (19, 2) NULL,
    [PROD_VOL]                     NUMERIC (19, 2) NULL,
    [PROD_WATER_VOL]               NUMERIC (19, 2) NULL,
    [REMARKS]                      VARCHAR (20)    NULL,
    [RIO_FLAG]                     VARCHAR (4)     NULL,
    [RIO_RESERVE]                  VARCHAR (7)     NULL,
    [SALES]                        NUMERIC (19, 2) NULL,
    [SALES_MMBTU]                  NUMERIC (19, 2) NULL,
    [SOURCE_ID]                    VARCHAR (22)    NULL,
    [SOURCE_PROD_FAC_PRD_ID]       VARCHAR (15)    NULL,
    [STATUS]                       VARCHAR (6)     NULL,
    [STD_SALES]                    NUMERIC (19, 2) NULL,
    [TERMINAL_NODE]                VARCHAR (15)    NULL,
    [TOTAL_GAS_SALES]              NUMERIC (19, 2) NULL,
    [TOTAL_OIL_SALES]              NUMERIC (19, 2) NULL,
    [TUBING_PRESSURE]              NUMERIC (9)     NULL,
    [WATER_PROD]                   NUMERIC (19, 2) NULL,
    [time_stamp]                   DATETIME        NULL,
    [u2_checksum]                  VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

