CREATE TABLE [dbo].[PROD_FAC_GAS_ANALYSIS] (
    [PROD_FAC_GAS_ANALYSIS_ID] VARCHAR (255) NOT NULL,
    [u2_id]                    VARCHAR (255) NULL,
    [GAS_ANALYSIS_EFF_DATES]   DATETIME      NULL,
    [GAS_ANALYSIS_INDEX]       VARCHAR (8)   NULL,
    [time_stamp]               DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PROD_FAC_GAS_ANALYSIS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROD_FAC_GAS_ANALYSIS_u2_id_in]
    ON [dbo].[PROD_FAC_GAS_ANALYSIS]([u2_id] ASC);

