CREATE TABLE [dbo].[PROD_DAILY_UDF] (
    [PROD_DAILY_UDF_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [PROD_METHOD]       VARCHAR (6)   NULL,
    [USER_DATA_FIELDS]  VARCHAR (17)  NULL,
    [USER_DATA_VALUES]  VARCHAR (6)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PROD_DAILY_UDF_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROD_DAILY_UDF_u2_id_in]
    ON [dbo].[PROD_DAILY_UDF]([u2_id] ASC);

