CREATE TABLE [dbo].[PROD_MO_RPT] (
    [PROD_MO_RPT_ID] VARCHAR (255) NOT NULL,
    [u2_id]          VARCHAR (255) NULL,
    [REPORTS]        VARCHAR (10)  NULL,
    [REPORT_DATES]   DATETIME      NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PROD_MO_RPT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROD_MO_RPT_u2_id_in]
    ON [dbo].[PROD_MO_RPT]([u2_id] ASC);

