CREATE TABLE [dbo].[PROD_DAILY_TANK_INVENTORY_CHANGE] (
    [PROD_DAILY_TANK_INVENTORY_CHANGE_ID] VARCHAR (255)   NOT NULL,
    [u2_id]                               VARCHAR (255)   NULL,
    [TANK_INVENTORY_CHANGE]               NUMERIC (19, 2) NULL,
    [time_stamp]                          DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([PROD_DAILY_TANK_INVENTORY_CHANGE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROD_DAIL_u2_id_34299]
    ON [dbo].[PROD_DAILY_TANK_INVENTORY_CHANGE]([u2_id] ASC);

