CREATE TABLE [dbo].[PROD_FAC_PRD_BTU_EFF_DATE] (
    [PROD_FAC_PRD_BTU_EFF_DATE_ID] VARCHAR (255)   NOT NULL,
    [u2_id]                        VARCHAR (255)   NULL,
    [BTU_FACTORS]                  NUMERIC (19, 4) NULL,
    [BTU_FACTOR_EXP_DATES]         DATETIME        NULL,
    [DOWNSTREAM_CONNECTION_TYPES]  DATETIME        NULL,
    [time_stamp]                   DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([PROD_FAC_PRD_BTU_EFF_DATE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROD_FAC__u2_id_92103]
    ON [dbo].[PROD_FAC_PRD_BTU_EFF_DATE]([u2_id] ASC);

