CREATE TABLE [dbo].[PROD_DAILY_THEO] (
    [u2_id]                           VARCHAR (255)   NOT NULL,
    [AGGREGATE_BEGIN_INVENTORY]       NUMERIC (19, 2) NULL,
    [AGGREGATE_BEGIN_WATER_INVENTORY] NUMERIC (19, 2) NULL,
    [AGGREGATE_GAS_LIFT_MMBTU]        VARCHAR (9)     NULL,
    [AGGREGATE_GAS_LIFT_VOL]          NUMERIC (19, 2) NULL,
    [AGGREGATE_OUPUT_WATER_VOL]       NUMERIC (19, 2) NULL,
    [AGGREGATE_OUTPUT_VOL]            NUMERIC (19, 2) NULL,
    [AGGREGATE_OUTPUT_WATER_VOL]      NUMERIC (19, 2) NULL,
    [ALLOC_BEGIN_INVENTORY]           NUMERIC (19, 2) NULL,
    [ALLOC_BEGIN_WATER_INVENTORY]     NUMERIC (19, 2) NULL,
    [BEGIN_INVENTORY]                 NUMERIC (19, 2) NULL,
    [BEGIN_WATER_INVENTORY]           NUMERIC (19, 2) NULL,
    [BTU_FACTOR]                      NUMERIC (19, 4) NULL,
    [GAS_LIFT_MMBTU]                  NUMERIC (19, 2) NULL,
    [GAS_LIFT_VOL]                    NUMERIC (19, 2) NULL,
    [GATHERING_SUB_SYSTEM]            VARCHAR (5)     NULL,
    [GATHERING_SYSTEM]                VARCHAR (12)    NULL,
    [GATH_SUB_SYS_ID]                 VARCHAR (12)    NULL,
    [INJECTED]                        NUMERIC (19, 2) NULL,
    [INJECTED_MMBTU]                  NUMERIC (19, 2) NULL,
    [OUTPUT_WATER_VOL]                NUMERIC (19, 2) NULL,
    [PRODUCT]                         VARCHAR (5)     NULL,
    [PROD_DATE]                       DATETIME        NULL,
    [PROD_FAC_ID]                     VARCHAR (11)    NULL,
    [PROD_FAC_PRD_ID]                 VARCHAR (15)    NULL,
    [SUB_SYSTEM]                      VARCHAR (6)     NULL,
    [TERMINAL_NODE]                   VARCHAR (15)    NULL,
    [USED]                            NUMERIC (19, 2) NULL,
    [USED_MMBTU]                      NUMERIC (19, 2) NULL,
    [VOLUME_METHOD]                   VARCHAR (6)     NULL,
    [VOLUME_TYPE]                     VARCHAR (6)     NULL,
    [time_stamp]                      DATETIME        NULL,
    [u2_checksum]                     VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

