CREATE TABLE [dbo].[PROD_WF_PUMP] (
    [PROD_WF_PUMP_ID] VARCHAR (255) NOT NULL,
    [u2_id]           VARCHAR (255) NULL,
    [PUMPER_ROUTES]   VARCHAR (9)   NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PROD_WF_PUMP_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROD_WF_PUMP_u2_id_in]
    ON [dbo].[PROD_WF_PUMP]([u2_id] ASC);

