CREATE TABLE [dbo].[PROD_ROUTE_STOP_ID] (
    [PROD_ROUTE_STOP_ID_ID] VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [ROUTE_STOPS]           VARCHAR (14)  NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PROD_ROUTE_STOP_ID_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROD_ROUTE_STOP_ID_u2_id_in]
    ON [dbo].[PROD_ROUTE_STOP_ID]([u2_id] ASC);

