CREATE TABLE [dbo].[PROD_DAILY_RPT] (
    [PROD_DAILY_RPT_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [REPORTS]           VARCHAR (10)  NULL,
    [REPORT_DATES]      DATETIME      NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PROD_DAILY_RPT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROD_DAILY_RPT_u2_id_in]
    ON [dbo].[PROD_DAILY_RPT]([u2_id] ASC);

