CREATE TABLE [dbo].[PROD_WF_FAC_EFF_DT] (
    [subValueId]      VARCHAR (255) NOT NULL,
    [PROD_WF_GATH_ID] VARCHAR (255) NULL,
    [FAC_EFF_DATES]   DATETIME      NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROD_WF_F_PROD_WF_G_34240]
    ON [dbo].[PROD_WF_FAC_EFF_DT]([PROD_WF_GATH_ID] ASC);

