CREATE TABLE [dbo].[PROD_ROUTE_PUMPER] (
    [PROD_ROUTE_PUMPER_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [PUMPERS]              VARCHAR (8)   NULL,
    [PUMPER_EFF_DATES]     DATETIME      NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PROD_ROUTE_PUMPER_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROD_ROUTE_PUMPER_u2_id_in]
    ON [dbo].[PROD_ROUTE_PUMPER]([u2_id] ASC);

