CREATE TABLE [dbo].[PROD_MO_EQ] (
    [u2_id]                         VARCHAR (255)   NOT NULL,
    [AVG_TEMP]                      NUMERIC (9, 1)  NULL,
    [BEGIN_METER_VOL]               NUMERIC (19, 2) NULL,
    [BSW_FACTOR]                    NUMERIC (19, 3) NULL,
    [CASING_PRESSURE]               NUMERIC (9)     NULL,
    [CHANGE_DATE_TIME]              VARCHAR (8)     NULL,
    [CHANGE_FLAG]                   VARCHAR (3)     NULL,
    [CHANGE_USER_ID]                VARCHAR (8)     NULL,
    [CHOKE]                         VARCHAR (5)     NULL,
    [CLOSING_METER_VOL]             NUMERIC (19, 2) NULL,
    [COEFFICIENT]                   NUMERIC (19, 4) NULL,
    [COMPRESSOR_BTU_FACTOR]         NUMERIC (19, 4) NULL,
    [COMPRESSOR_MMBTU]              NUMERIC (19, 2) NULL,
    [COMPRESSOR_VOL]                NUMERIC (19, 2) NULL,
    [CORRECTED_GRAVITY]             NUMERIC (9, 1)  NULL,
    [DAILY_REMARKS]                 VARCHAR (20)    NULL,
    [DIFFERENTIAL]                  NUMERIC (19, 3) NULL,
    [DISCHARGE_PRESSURE]            NUMERIC (9)     NULL,
    [DISP_BTU_FACTOR]               NUMERIC (19, 4) NULL,
    [DISP_COMMENTS]                 VARCHAR (30)    NULL,
    [DISP_MMBTU]                    NUMERIC (19, 2) NULL,
    [DOWN_END_OF_DAY]               VARCHAR (6)     NULL,
    [DOWN_HOURS]                    NUMERIC (19, 2) NULL,
    [DOWN_MINUTES]                  NUMERIC (9)     NULL,
    [DOWN_REASON]                   VARCHAR (6)     NULL,
    [ENTERED_BTU_FACTOR]            NUMERIC (19, 4) NULL,
    [EQUIP_DOWN_END_OF_DAY]         VARCHAR (5)     NULL,
    [EQUIP_DOWN_HOURS]              NUMERIC (19, 2) NULL,
    [EQUIP_DOWN_MINUTES]            NUMERIC (9)     NULL,
    [EQUIP_DOWN_REASON]             VARCHAR (6)     NULL,
    [EQUIP_REMARKS]                 VARCHAR (30)    NULL,
    [FEET]                          VARCHAR (4)     NULL,
    [FLOWING_HOURS]                 NUMERIC (9)     NULL,
    [FLOWING_MINUTES]               NUMERIC (9)     NULL,
    [FLOWING_TEMP]                  NUMERIC (9, 1)  NULL,
    [FRACTIONAL_INCHES]             VARCHAR (10)    NULL,
    [GAS_BTU_FACTOR]                NUMERIC (19, 4) NULL,
    [GAS_MMBTU]                     NUMERIC (19, 2) NULL,
    [GAS_VOL]                       NUMERIC (19, 2) NULL,
    [GRAVITY]                       NUMERIC (9, 1)  NULL,
    [GROSS_METER_VOL]               NUMERIC (19, 2) NULL,
    [INCHES]                        VARCHAR (6)     NULL,
    [METER_FACTOR]                  NUMERIC (19, 8) NULL,
    [METER_RESET_FLAG]              VARCHAR (5)     NULL,
    [METER_TICKET]                  VARCHAR (6)     NULL,
    [OBSERVED_GRAVITY]              NUMERIC (9, 1)  NULL,
    [OBSERVED_TEMP]                 NUMERIC (9, 1)  NULL,
    [OIL_METER_NET_OIL_VOL]         NUMERIC (19, 2) NULL,
    [OIL_METER_WATER_VOL]           VARCHAR (9)     NULL,
    [PROD_PERIOD]                   DATETIME        NULL,
    [REMARKS]                       VARCHAR (20)    NULL,
    [RPM]                           NUMERIC (9)     NULL,
    [STATIC_PRESSURE]               NUMERIC (19, 3) NULL,
    [SUCTION_PRESSURE]              NUMERIC (9)     NULL,
    [TANK_BEGIN_INVENTORY]          NUMERIC (19, 2) NULL,
    [TANK_BEGIN_WATER_INVENTORY]    NUMERIC (19, 2) NULL,
    [TANK_ENDING_INVENTORY]         NUMERIC (19, 2) NULL,
    [TANK_ENDING_WATER_INVENTORY]   NUMERIC (19, 2) NULL,
    [TANK_NET_OIL_VOL]              NUMERIC (19, 2) NULL,
    [TANK_OIL_SALES]                NUMERIC (19, 2) NULL,
    [TANK_WATER_VOL]                NUMERIC (19, 2) NULL,
    [TEMP_CORRECTION_FACTOR]        NUMERIC (19, 4) NULL,
    [TUBING_PRESSURE]               NUMERIC (9)     NULL,
    [WATER_FEET]                    NUMERIC (9)     NULL,
    [WATER_FRACTIONAL_INCHES]       NUMERIC (9)     NULL,
    [WATER_INCHES]                  NUMERIC (9)     NULL,
    [WATER_METER_BEGIN_METER_VOL]   NUMERIC (19, 2) NULL,
    [WATER_METER_CLOSING_METER_VOL] NUMERIC (19, 2) NULL,
    [WATER_METER_GROSS_METER_VOL]   NUMERIC (19, 2) NULL,
    [WATER_METER_METER_FACTOR]      NUMERIC (19, 2) NULL,
    [WATER_METER_METER_RESET_FLAG]  VARCHAR (5)     NULL,
    [WATER_PRESSURE]                NUMERIC (9)     NULL,
    [WATER_VOL]                     NUMERIC (19, 2) NULL,
    [time_stamp]                    DATETIME        NULL,
    [u2_checksum]                   VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

