CREATE TABLE [dbo].[PROJ_RMK] (
    [PROJ_RMK_ID]  VARCHAR (255) NOT NULL,
    [u2_id]        VARCHAR (255) NULL,
    [REMARKS]      VARCHAR (30)  NULL,
    [REMARKS_DATE] DATETIME      NULL,
    [REMARKS_TYPE] VARCHAR (4)   NULL,
    [time_stamp]   DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PROJ_RMK_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROJ_RMK_u2_id_in]
    ON [dbo].[PROJ_RMK]([u2_id] ASC);

