CREATE TABLE [dbo].[PROJ_SYSTEM] (
    [PROJ_SYSTEM_ID] VARCHAR (255) NOT NULL,
    [u2_id]          VARCHAR (255) NULL,
    [SYSTEM_DATE]    DATETIME      NULL,
    [SYSTEM_TIME]    VARCHAR (8)   NULL,
    [SYSTEM_USER_ID] VARCHAR (6)   NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PROJ_SYSTEM_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROJ_SYSTEM_u2_id_in]
    ON [dbo].[PROJ_SYSTEM]([u2_id] ASC);

