CREATE TABLE [dbo].[PROJ_ACC] (
    [PROJ_ACC_ID]     VARCHAR (255)   NOT NULL,
    [u2_id]           VARCHAR (255)   NULL,
    [ACCRUAL_ACCTS]   VARCHAR (9)     NULL,
    [TOT_BUDGET_AMTS] NUMERIC (19, 2) NULL,
    [time_stamp]      DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([PROJ_ACC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROJ_ACC_u2_id_in]
    ON [dbo].[PROJ_ACC]([u2_id] ASC);

