CREATE TABLE [dbo].[PROJ_ACC_ACCTG_PER] (
    [subValueId]             VARCHAR (255)   NOT NULL,
    [PROJ_ACC_ID]            VARCHAR (255)   NULL,
    [ACCRUAL_ACCTG_PERIODS]  DATETIME        NULL,
    [ACCRUAL_AMTS]           NUMERIC (19, 2) NULL,
    [ACCRUAL_INVOICED_AMTS]  NUMERIC (19, 2) NULL,
    [ESTIMATED_REMAINING]    NUMERIC (19, 2) NULL,
    [INCURRED_TO_DATE]       NUMERIC (19, 2) NULL,
    [INCUR_TRANS_INDEX]      VARCHAR (8)     NULL,
    [OVERRIDE_INCURRED_AMTS] NUMERIC (19, 2) NULL,
    [PERCENT_COMPLETE]       NUMERIC (19, 2) NULL,
    [time_stamp]             DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROJ_ACC__PROJ_ACC__14974]
    ON [dbo].[PROJ_ACC_ACCTG_PER]([PROJ_ACC_ID] ASC);

