CREATE TABLE [dbo].[PROP_CHANGE_OS_IDX] (
    [PROP_CHANGE_OS_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [OWNER_SALE_INDEX]      VARCHAR (10)  NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PROP_CHANGE_OS_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROP_CHANGE_OS_IDX_u2_id_in]
    ON [dbo].[PROP_CHANGE_OS_IDX]([u2_id] ASC);

