CREATE TABLE [dbo].[PROSPECT_LINK] (
    [PROSPECT_LINK_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [LINKS]            VARCHAR (25)  NULL,
    [LINK_TYPES]       VARCHAR (6)   NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PROSPECT_LINK_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROSPECT_LINK_u2_id_in]
    ON [dbo].[PROSPECT_LINK]([u2_id] ASC);

