CREATE TABLE [dbo].[PROSPECT_SURVEY] (
    [PROSPECT_SURVEY_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [SURVEYS]            VARCHAR (10)  NULL,
    [SURVEY_BLOCKS]      VARCHAR (3)   NULL,
    [SURVEY_SECTIONS]    VARCHAR (50)  NULL,
    [SURVEY_SEC_DESCS]   VARCHAR (50)  NULL,
    [SURVEY_TOWNSHIPS]   VARCHAR (3)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PROSPECT_SURVEY_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PROSPECT_SURVEY_u2_id_in]
    ON [dbo].[PROSPECT_SURVEY]([u2_id] ASC);

