CREATE TABLE [dbo].[PRR_DATA_CODE_UDF] (
    [PRR_DATA_CODE_UDF_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [EDIT_CODES]           VARCHAR (6)   NULL,
    [EDIT_VALUES]          VARCHAR (9)   NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PRR_DATA_CODE_UDF_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PRR_DATA_CODE_UDF_u2_id_in]
    ON [dbo].[PRR_DATA_CODE_UDF]([u2_id] ASC);

