CREATE TABLE [dbo].[PRR_TX_EFF_DT] (
    [PRR_TX_EFF_DT_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [EFF_DATES]        DATETIME      NULL,
    [EXP_DATES]        DATETIME      NULL,
    [RRC_GAS_ID]       VARCHAR (9)   NULL,
    [STATE_LEASE_NOS]  VARCHAR (10)  NULL,
    [STATE_PERMIT_NOS] VARCHAR (6)   NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PRR_TX_EFF_DT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PRR_TX_EFF_DT_u2_id_in]
    ON [dbo].[PRR_TX_EFF_DT]([u2_id] ASC);

