CREATE TABLE [dbo].[PRR_STATUS_WELL_ST] (
    [PRR_STATUS_WELL_ST_ID] VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [VALID_WELL_STATUS]     VARCHAR (6)   NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PRR_STATUS_WELL_ST_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PRR_STATUS_WELL_ST_u2_id_in]
    ON [dbo].[PRR_STATUS_WELL_ST]([u2_id] ASC);

