CREATE TABLE [dbo].[PRR_LA_LUW_PARISH_DATA] (
    [subValueId]             VARCHAR (255) NOT NULL,
    [PRR_LA_LUW_EFF_DATE_ID] VARCHAR (255) NULL,
    [PARISH_NAME]            VARCHAR (20)  NULL,
    [PARISH_NONAPI_CODES]    VARCHAR (6)   NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PRR_LA_LU_PRR_LA_LU_65659]
    ON [dbo].[PRR_LA_LUW_PARISH_DATA]([PRR_LA_LUW_EFF_DATE_ID] ASC);

