CREATE TABLE [dbo].[PTD_CALC_FCTR] (
    [PTD_CALC_FCTR_ID]     VARCHAR (255)   NOT NULL,
    [u2_id]                VARCHAR (255)   NULL,
    [CALC_FACTORS]         NUMERIC (19, 5) NULL,
    [FACTOR_BEGIN_PERIODS] DATETIME        NULL,
    [FACTOR_END_PERIODS]   DATETIME        NULL,
    [time_stamp]           DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([PTD_CALC_FCTR_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PTD_CALC_FCTR_u2_id_in]
    ON [dbo].[PTD_CALC_FCTR]([u2_id] ASC);

