CREATE TABLE [dbo].[PTR_DIST_DET] (
    [u2_id]           VARCHAR (255)   NOT NULL,
    [ACCOUNT_NO]      VARCHAR (25)    NULL,
    [AMT]             NUMERIC (19, 2) NULL,
    [APP]             VARCHAR (8)     NULL,
    [COA_GRP]         VARCHAR (10)    NULL,
    [COST_CENTER]     VARCHAR (8)     NULL,
    [DIST_CO]         VARCHAR (4)     NULL,
    [DIST_DATE]       DATETIME        NULL,
    [DSPLY_AMT]       NUMERIC (19, 2) NULL,
    [DSPLY_QTY1]      NUMERIC (19, 2) NULL,
    [INV_CHANGE_ID]   VARCHAR (10)    NULL,
    [LAST_ADJ_DOC]    VARCHAR (16)    NULL,
    [LAST_ADJ_PERIOD] DATETIME        NULL,
    [LAST_ADJ_TYPE]   VARCHAR (4)     NULL,
    [MAIL_TO_ADDRESS] VARCHAR (7)     NULL,
    [MAIL_TO_BROKER]  VARCHAR (7)     NULL,
    [OCCUR_DATE]      DATETIME        NULL,
    [OWNER_PCT]       NUMERIC (19, 8) NULL,
    [PARTNER_NO]      VARCHAR (7)     NULL,
    [PAY_CODE]        VARCHAR (4)     NULL,
    [PAY_STATUS]      VARCHAR (6)     NULL,
    [PROD_TYPE]       VARCHAR (4)     NULL,
    [PROJECT]         VARCHAR (10)    NULL,
    [PTRSHP_AMT]      NUMERIC (19, 2) NULL,
    [PTRSHP_NO]       VARCHAR (6)     NULL,
    [PTRSHP_QTY1]     NUMERIC (19, 2) NULL,
    [PTRSHP_QTY2]     NUMERIC (19, 2) NULL,
    [PTR_ADJ_CTL_ID]  VARCHAR (7)     NULL,
    [QTY1]            NUMERIC (19, 2) NULL,
    [QTY2]            NUMERIC (19, 2) NULL,
    [SOURCE_PDD_ID]   VARCHAR (8)     NULL,
    [STATUS]          VARCHAR (6)     NULL,
    [VOUCHER]         VARCHAR (16)    NULL,
    [time_stamp]      DATETIME        NULL,
    [u2_checksum]     VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

