CREATE TABLE [dbo].[PTR_COMMENT] (
    [PTR_COMMENT_ID] VARCHAR (255) NOT NULL,
    [u2_id]          VARCHAR (255) NULL,
    [COMMENTS]       VARCHAR (40)  NULL,
    [COMMENT_DATES]  DATETIME      NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PTR_COMMENT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PTR_COMMENT_u2_id_in]
    ON [dbo].[PTR_COMMENT]([u2_id] ASC);

