CREATE TABLE [dbo].[PTR_DIST_DET_ADJ_PER] (
    [PTR_DIST_DET_ADJ_PER_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [ADJ_PERIODS]             DATETIME      NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PTR_DIST_DET_ADJ_PER_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PTR_DIST_DET_ADJ_PER_u2_id_in]
    ON [dbo].[PTR_DIST_DET_ADJ_PER]([u2_id] ASC);

