CREATE TABLE [dbo].[PTR_DIST_DET_PTRSHP_DET] (
    [PTR_DIST_DET_PTRSHP_DET_ID] VARCHAR (255) NOT NULL,
    [u2_id]                      VARCHAR (255) NULL,
    [PTRSHP_DIST_DET_ID]         VARCHAR (9)   NULL,
    [time_stamp]                 DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PTR_DIST_DET_PTRSHP_DET_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PTR_DIST__u2_id_14050]
    ON [dbo].[PTR_DIST_DET_PTRSHP_DET]([u2_id] ASC);

