CREATE TABLE [dbo].[PTR_SALESREP_RMK] (
    [PTR_SALESREP_RMK_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [REMARKS]             VARCHAR (30)  NULL,
    [REMARK_DATES]        VARCHAR (8)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PTR_SALESREP_RMK_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PTR_SALESREP_RMK_u2_id_in]
    ON [dbo].[PTR_SALESREP_RMK]([u2_id] ASC);

