CREATE TABLE [dbo].[PTRSHP_SYS_AUDIT] (
    [PTRSHP_SYS_AUDIT_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [SYSTEM_DATE]         VARCHAR (8)   NULL,
    [SYSTEM_TIME]         VARCHAR (84)  NULL,
    [SYSTEM_USER_ID]      VARCHAR (5)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PTRSHP_SYS_AUDIT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PTRSHP_SYS_AUDIT_u2_id_in]
    ON [dbo].[PTRSHP_SYS_AUDIT]([u2_id] ASC);

