CREATE TABLE [dbo].[PTRSHP_DIST_DET_TRANS_IDX] (
    [PTRSHP_DIST_DET_TRANS_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                        VARCHAR (255) NULL,
    [TRANS_DATES]                  DATETIME      NULL,
    [TRANS_INDEX]                  VARCHAR (9)   NULL,
    [time_stamp]                   DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PTRSHP_DIST_DET_TRANS_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PTRSHP_DI_u2_id_74350]
    ON [dbo].[PTRSHP_DIST_DET_TRANS_IDX]([u2_id] ASC);

