CREATE TABLE [dbo].[PTRSHP_INVESTOR_TMP_SUB] (
    [PTRSHP_INVESTOR_TMP_SUB_ID] VARCHAR (255) NOT NULL,
    [u2_id]                      VARCHAR (255) NULL,
    [TEMP_SUB_LIST]              VARCHAR (13)  NULL,
    [time_stamp]                 DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PTRSHP_INVESTOR_TMP_SUB_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PTRSHP_IN_u2_id_68812]
    ON [dbo].[PTRSHP_INVESTOR_TMP_SUB]([u2_id] ASC);

