CREATE TABLE [dbo].[PTRSHP_COA_GRP_VLD_ACCT] (
    [PTRSHP_COA_GRP_VLD_ACCT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                      VARCHAR (255) NULL,
    [VALID_ACCTS]                VARCHAR (15)  NULL,
    [time_stamp]                 DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PTRSHP_COA_GRP_VLD_ACCT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PTRSHP_CO_u2_id_22489]
    ON [dbo].[PTRSHP_COA_GRP_VLD_ACCT]([u2_id] ASC);

