CREATE TABLE [dbo].[PTRSHP_INVESTOR_SALES_REP] (
    [PTRSHP_INVESTOR_SALES_REP_ID] VARCHAR (255) NOT NULL,
    [u2_id]                        VARCHAR (255) NULL,
    [DFLT_SALES_REP]               VARCHAR (8)   NULL,
    [SALES_REP_EFF_DATES]          DATETIME      NULL,
    [time_stamp]                   DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PTRSHP_INVESTOR_SALES_REP_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [PTRSHP_IN_u2_id_38103]
    ON [dbo].[PTRSHP_INVESTOR_SALES_REP]([u2_id] ASC);

