CREATE TABLE [dbo].[RE_CHECK_OS_IDX] (
    [RE_CHECK_OS_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [OWNER_SALE_INDEX]   VARCHAR (9)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RE_CHECK_OS_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RE_CHECK_OS_IDX_u2_id_in]
    ON [dbo].[RE_CHECK_OS_IDX]([u2_id] ASC);

