CREATE TABLE [dbo].[RE_EXCEPTION_OWNER_CC] (
    [RE_EXCEPTION_OWNER_CC_ID] VARCHAR (255) NOT NULL,
    [u2_id]                    VARCHAR (255) NULL,
    [OWNER_CC_EXCEPTIONS]      VARCHAR (6)   NULL,
    [OWNER_CC_REASONS]         VARCHAR (30)  NULL,
    [OWNER_CC_STATUSES]        VARCHAR (4)   NULL,
    [OWNER_CC_STATUS_DATES]    DATETIME      NULL,
    [time_stamp]               DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RE_EXCEPTION_OWNER_CC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RE_EXCEPTION_OWNER_CC_u2_id_in]
    ON [dbo].[RE_EXCEPTION_OWNER_CC]([u2_id] ASC);

