CREATE TABLE [dbo].[RE_EXCEPTION_CC_OWNER] (
    [RE_EXCEPTION_CC_OWNER_ID] VARCHAR (255) NOT NULL,
    [u2_id]                    VARCHAR (255) NULL,
    [CC_OWNER_EXCEPTIONS]      VARCHAR (6)   NULL,
    [CC_OWNER_REASONS]         VARCHAR (30)  NULL,
    [CC_OWNER_STATUSES]        VARCHAR (4)   NULL,
    [CC_OWNER_STATUS_DATES]    DATETIME      NULL,
    [time_stamp]               DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RE_EXCEPTION_CC_OWNER_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RE_EXCEPTION_CC_OWNER_u2_id_in]
    ON [dbo].[RE_EXCEPTION_CC_OWNER]([u2_id] ASC);

