CREATE TABLE [dbo].[RECEIPT_ADJ_IDX] (
    [RECEIPT_ADJ_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [RECEIPT_ADJ_INDEX]  VARCHAR (6)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RECEIPT_ADJ_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RECEIPT_ADJ_IDX_u2_id_in]
    ON [dbo].[RECEIPT_ADJ_IDX]([u2_id] ASC);

