CREATE TABLE [dbo].[RECEIPT_ADJ_AR_INV_DET_IDX] (
    [subValueId]            VARCHAR (255) NOT NULL,
    [RECEIPT_ADJ_AR_INV_ID] VARCHAR (255) NULL,
    [AR_INV_DET_IDX]        VARCHAR (10)  NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RECEIPT_A_RECEIPT_A_39450]
    ON [dbo].[RECEIPT_ADJ_AR_INV_DET_IDX]([RECEIPT_ADJ_AR_INV_ID] ASC);

