CREATE TABLE [dbo].[RECEIPT_TYPE_SEL] (
    [RECEIPT_TYPE_SEL_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [SELECTION_ACCTS]     VARCHAR (10)  NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RECEIPT_TYPE_SEL_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RECEIPT_TYPE_SEL_u2_id_in]
    ON [dbo].[RECEIPT_TYPE_SEL]([u2_id] ASC);

