CREATE TABLE [dbo].[RECEIPT_SEL] (
    [RECEIPT_SEL_ID] VARCHAR (255) NOT NULL,
    [u2_id]          VARCHAR (255) NULL,
    [TMP_SELECT1]    VARCHAR (7)   NULL,
    [TMP_SELECT2]    VARCHAR (7)   NULL,
    [TMP_SELECT3]    VARCHAR (7)   NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RECEIPT_SEL_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RECEIPT_SEL_u2_id_in]
    ON [dbo].[RECEIPT_SEL]([u2_id] ASC);

