CREATE TABLE [dbo].[RECEIPT_APPLD_AR_INV_IDX] (
    [subValueId]           VARCHAR (255) NOT NULL,
    [RECEIPT_APPLD_ID]     VARCHAR (255) NULL,
    [APPLIED_AR_INV_INDEX] VARCHAR (23)  NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RECEIPT_A_RECEIPT_A_87787]
    ON [dbo].[RECEIPT_APPLD_AR_INV_IDX]([RECEIPT_APPLD_ID] ASC);

