CREATE TABLE [dbo].[RECEIPT_OS_IDX] (
    [RECEIPT_OS_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [OS_REFUND_FLAGS]   VARCHAR (6)   NULL,
    [OWNER_SALE_INDEX]  VARCHAR (10)  NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RECEIPT_OS_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RECEIPT_OS_IDX_u2_id_in]
    ON [dbo].[RECEIPT_OS_IDX]([u2_id] ASC);

