CREATE TABLE [dbo].[RECEIPT] (
    [u2_id]            VARCHAR (255)   NOT NULL,
    [ACCTG_PERIOD]     DATETIME        NULL,
    [ANALYST]          VARCHAR (9)     NULL,
    [APPR_DATE]        DATETIME        NULL,
    [AR_VOUCHER]       VARCHAR (16)    NULL,
    [CHECK_AMT]        NUMERIC (19, 2) NULL,
    [CHECK_DATE]       DATETIME        NULL,
    [CHECK_NO]         VARCHAR (21)    NULL,
    [COMPANY]          VARCHAR (3)     NULL,
    [CUSTOMER]         VARCHAR (6)     NULL,
    [DEPOSIT]          VARCHAR (24)    NULL,
    [MISC_VOUCHER]     VARCHAR (29)    NULL,
    [NEW_CHECK_NO]     VARCHAR (12)    NULL,
    [PP_VOUCHER]       VARCHAR (16)    NULL,
    [REFUND_VOUCHER]   VARCHAR (16)    NULL,
    [REMITTER]         VARCHAR (8)     NULL,
    [REVISED_REMITTER] VARCHAR (6)     NULL,
    [STATUS]           VARCHAR (6)     NULL,
    [SYSTEM_DATE]      DATETIME        NULL,
    [SYSTEM_TIME]      VARCHAR (8)     NULL,
    [SYSTEM_USER_ID]   VARCHAR (7)     NULL,
    [TMP_ACCTG_PERIOD] DATETIME        NULL,
    [TMP_VOUCHER]      VARCHAR (15)    NULL,
    [TOTAL_APPLIED]    NUMERIC (19, 2) NULL,
    [TYPE]             VARCHAR (4)     NULL,
    [UNDIST_AMOUNT]    NUMERIC (19, 2) NULL,
    [UNDIST_AMT]       NUMERIC (19, 2) NULL,
    [a1099_YEAR]       NUMERIC (9)     NULL,
    [time_stamp]       DATETIME        NULL,
    [u2_checksum]      VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

