CREATE TABLE [dbo].[RECEIPT_ADJ_AR_INV] (
    [RECEIPT_ADJ_AR_INV_ID] VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [AR_INV_INDEX]          VARCHAR (16)  NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RECEIPT_ADJ_AR_INV_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RECEIPT_ADJ_AR_INV_u2_id_in]
    ON [dbo].[RECEIPT_ADJ_AR_INV]([u2_id] ASC);

