CREATE TABLE [dbo].[RESERVE_TRANS_OWN_JIB_IDX] (
    [RESERVE_TRANS_OWN_JIB_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                        VARCHAR (255) NULL,
    [OWNER_JIB_INDEX]              VARCHAR (8)   NULL,
    [time_stamp]                   DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RESERVE_TRANS_OWN_JIB_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RESERVE_T_u2_id_40412]
    ON [dbo].[RESERVE_TRANS_OWN_JIB_IDX]([u2_id] ASC);

