CREATE TABLE [dbo].[RESERVE_TRANS_INS_ACCTG_PER] (
    [RESERVE_TRANS_INS_ACCTG_PER_ID] VARCHAR (255) NOT NULL,
    [u2_id]                          VARCHAR (255) NULL,
    [INS_ACCTG_PERIODS]              DATETIME      NULL,
    [time_stamp]                     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RESERVE_TRANS_INS_ACCTG_PER_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RESERVE_T_u2_id_57155]
    ON [dbo].[RESERVE_TRANS_INS_ACCTG_PER]([u2_id] ASC);

