CREATE TABLE [dbo].[RINV_TRANS_INDEX] (
    [subValueId]        VARCHAR (255) NOT NULL,
    [RINV_ACCTG_PER_ID] VARCHAR (255) NULL,
    [TRANS_INDEX]       VARCHAR (8)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RINV_TRAN_RINV_ACCT_1057]
    ON [dbo].[RINV_TRANS_INDEX]([RINV_ACCTG_PER_ID] ASC);

