CREATE TABLE [dbo].[RIO_WELL_TEST] (
    [u2_id]             VARCHAR (255) NOT NULL,
    [ALLOCATABLE]       VARCHAR (11)  NULL,
    [API_GRAVITY]       VARCHAR (11)  NULL,
    [BH_PRESS]          VARCHAR (20)  NULL,
    [BH_TEMP]           VARCHAR (16)  NULL,
    [BOLO_WELL]         VARCHAR (9)   NULL,
    [BOLO_WELL_NAME]    VARCHAR (30)  NULL,
    [BOLO_WELL_NO]      VARCHAR (15)  NULL,
    [CASING_PRESS]      VARCHAR (15)  NULL,
    [CASING_PRESS2]     VARCHAR (13)  NULL,
    [CHOKE]             VARCHAR (10)  NULL,
    [COMMENTS]          VARCHAR (30)  NULL,
    [DATA_SOURCE]       VARCHAR (8)   NULL,
    [DELETED]           VARCHAR (3)   NULL,
    [GAS_LIFT]          VARCHAR (15)  NULL,
    [GAS_PROD]          VARCHAR (15)  NULL,
    [GAUGE_DEPTH]       VARCHAR (11)  NULL,
    [INITIALS]          VARCHAR (4)   NULL,
    [MOD_DATE]          VARCHAR (8)   NULL,
    [MOD_USER]          VARCHAR (8)   NULL,
    [OIL_PROD]          VARCHAR (15)  NULL,
    [RIO_WELL]          VARCHAR (8)   NULL,
    [SAND]              VARCHAR (4)   NULL,
    [SI_BH_PRESS]       VARCHAR (21)  NULL,
    [SI_TUBING_PRESS]   VARCHAR (15)  NULL,
    [SURF_CASING_PRESS] VARCHAR (17)  NULL,
    [TEST_DATE]         VARCHAR (9)   NULL,
    [TEST_HOURS]        VARCHAR (10)  NULL,
    [TUBING_PRESS]      VARCHAR (15)  NULL,
    [TUBING_PRESS2]     VARCHAR (13)  NULL,
    [WATER_PROD]        VARCHAR (15)  NULL,
    [time_stamp]        DATETIME      NULL,
    [u2_checksum]       VARCHAR (25)  NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

