CREATE TABLE [dbo].[RIO_MONTHLY] (
    [u2_id]          VARCHAR (255)   NOT NULL,
    [ALLOC_DATE]     DATETIME        NULL,
    [BOLO_WELLZONE]  VARCHAR (11)    NULL,
    [BOLO_WELL_NAME] VARCHAR (30)    NULL,
    [BOLO_WELL_NO]   VARCHAR (15)    NULL,
    [CO2_INJ]        VARCHAR (15)    NULL,
    [DATA_SOURCE]    VARCHAR (11)    NULL,
    [DAYS_ON]        VARCHAR (7)     NULL,
    [GAS_INJ]        NUMERIC (19, 2) NULL,
    [GAS_LIFT]       NUMERIC (19, 2) NULL,
    [GAS_PROD]       NUMERIC (19, 2) NULL,
    [LAST_MOD_DT]    DATETIME        NULL,
    [LAST_MOD_USER]  VARCHAR (20)    NULL,
    [LUMP_SUM]       VARCHAR (8)     NULL,
    [METHOD]         VARCHAR (6)     NULL,
    [NGL_PROD]       NUMERIC (19, 2) NULL,
    [OIL_PROD]       NUMERIC (19, 2) NULL,
    [RIO_WELLZONE]   VARCHAR (11)    NULL,
    [STATUS]         VARCHAR (6)     NULL,
    [STEAM]          NUMERIC (19, 2) NULL,
    [WATER_INJ]      NUMERIC (19, 2) NULL,
    [WATER_PROD]     NUMERIC (19, 2) NULL,
    [WELL_TYPE]      VARCHAR (15)    NULL,
    [time_stamp]     DATETIME        NULL,
    [u2_checksum]    VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

