CREATE TABLE [dbo].[ROY_NM_SYS_SLO_OWN] (
    [ROY_NM_SYS_SLO_OWN_ID] VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [SLO_OWNER_NOS]         VARCHAR (10)  NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([ROY_NM_SYS_SLO_OWN_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ROY_NM_SYS_SLO_OWN_u2_id_in]
    ON [dbo].[ROY_NM_SYS_SLO_OWN]([u2_id] ASC);

