CREATE TABLE [dbo].[RR_SYS] (
    [u2_id]                 VARCHAR (255)   NOT NULL,
    [ACKNOWLEDGE_FLAG]      VARCHAR (4)     NULL,
    [AMC_62_UNUSED]         VARCHAR (3)     NULL,
    [AMC_66_UNUSED]         VARCHAR (15)    NULL,
    [AP_OPTION]             VARCHAR (3)     NULL,
    [BANK_ACCT]             VARCHAR (8)     NULL,
    [BILL_EXPENSE_ACCT]     VARCHAR (10)    NULL,
    [CLRG_ACCT]             VARCHAR (10)    NULL,
    [CLRG_CC]               VARCHAR (10)    NULL,
    [COMPANY]               VARCHAR (3)     NULL,
    [COMPANY_PBASE]         NUMERIC (19, 4) NULL,
    [CONTACT_ADDR1]         VARCHAR (32)    NULL,
    [CONTACT_ADDR2]         VARCHAR (30)    NULL,
    [CONTACT_EMAIL]         VARCHAR (25)    NULL,
    [CONTACT_NAME]          VARCHAR (30)    NULL,
    [CONTACT_NO]            VARCHAR (10)    NULL,
    [CONTACT_PHONE]         VARCHAR (13)    NULL,
    [CONTROL_NO]            VARCHAR (10)    NULL,
    [CPT_CALC_TOL]          NUMERIC (19, 2) NULL,
    [DFLT_LAG_MONTHS]       NUMERIC (9)     NULL,
    [EDI_APP_RECEIVER_CODE] VARCHAR (15)    NULL,
    [EDI_FILE_NAME]         VARCHAR (20)    NULL,
    [EDI_SENDER_IDENTIFIER] VARCHAR (15)    NULL,
    [EDI_SENDER_QUALIFIER]  VARCHAR (2)     NULL,
    [FED_EXCL_PAY_CODE]     VARCHAR (4)     NULL,
    [GRAVITY]               NUMERIC (9, 1)  NULL,
    [JE_TYPE]               VARCHAR (3)     NULL,
    [LA_SEV_ACCT]           VARCHAR (5)     NULL,
    [OK300_DEEP48_TAX_CODE] VARCHAR (5)     NULL,
    [OK300_DEEP60_TAX_CODE] VARCHAR (5)     NULL,
    [OK300_HORIZ_TAX_CODE]  VARCHAR (5)     NULL,
    [PMT_METH]              VARCHAR (4)     NULL,
    [PMT_VENDOR]            VARCHAR (8)     NULL,
    [RECON_FILE_NAME]       VARCHAR (20)    NULL,
    [RES_PRD_CDE]           VARCHAR (3)     NULL,
    [RPT_COMPANY_NAME]      VARCHAR (30)    NULL,
    [RPT_PBASE]             NUMERIC (19, 4) NULL,
    [RPT_PBASE_TYPE]        VARCHAR (3)     NULL,
    [SPECIAL_CPT]           VARCHAR (7)     NULL,
    [STATE]                 VARCHAR (2)     NULL,
    [TRANS_ALLOW]           NUMERIC (19, 2) NULL,
    [VOU_SRC]               VARCHAR (3)     NULL,
    [time_stamp]            DATETIME        NULL,
    [u2_checksum]           VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

