CREATE TABLE [dbo].[RR_SYS_EXCLUSION] (
    [RR_SYS_EXCLUSION_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [EXCL_CODE]           VARCHAR (4)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RR_SYS_EXCLUSION_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RR_SYS_EXCLUSION_u2_id_in]
    ON [dbo].[RR_SYS_EXCLUSION]([u2_id] ASC);

