CREATE TABLE [dbo].[RR_SYS_XMP_OWN] (
    [RR_SYS_XMP_OWN_ID]  VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [EXEMPT_OWNER_TYPES] VARCHAR (4)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RR_SYS_XMP_OWN_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RR_SYS_XMP_OWN_u2_id_in]
    ON [dbo].[RR_SYS_XMP_OWN]([u2_id] ASC);

