CREATE TABLE [dbo].[RR_SYS_SPL_ST] (
    [RR_SYS_SPL_ST_ID]  VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [SUPPL_STATE_CODES] VARCHAR (5)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RR_SYS_SPL_ST_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RR_SYS_SPL_ST_u2_id_in]
    ON [dbo].[RR_SYS_SPL_ST]([u2_id] ASC);

