CREATE TABLE [dbo].[RR_WELL_LUG_AUDIT] (
    [RR_WELL_LUG_AUDIT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [ORR_AUDIT_IDS]        VARCHAR (10)  NULL,
    [SYSTEM_DATE]          DATETIME      NULL,
    [SYSTEM_TIME]          VARCHAR (8)   NULL,
    [SYSTEM_USER_ID]       VARCHAR (8)   NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RR_WELL_LUG_AUDIT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RR_WELL_LUG_AUDIT_u2_id_in]
    ON [dbo].[RR_WELL_LUG_AUDIT]([u2_id] ASC);

