CREATE TABLE [dbo].[RR_WELL_LUG_OGSALE] (
    [RR_WELL_LUG_OGSALE_ID] VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [ORR_COMPANY_VOLUMES]   VARCHAR (12)  NULL,
    [ORR_OG_IDS]            VARCHAR (10)  NULL,
    [ORR_STATE_PRD]         VARCHAR (6)   NULL,
    [ORR_TAXABLE_VALUES]    VARCHAR (12)  NULL,
    [ORR_TAXABLE_VOLUMES]   VARCHAR (12)  NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RR_WELL_LUG_OGSALE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RR_WELL_LUG_OGSALE_u2_id_in]
    ON [dbo].[RR_WELL_LUG_OGSALE]([u2_id] ASC);

