CREATE TABLE [dbo].[RUN_TICKET] (
    [u2_id]                       VARCHAR (255)   NOT NULL,
    [ACCTG_PERIOD]                DATETIME        NULL,
    [AFTER_STOCK_FLAG]            VARCHAR (5)     NULL,
    [APP]                         VARCHAR (8)     NULL,
    [AVG_TEMP]                    NUMERIC (9, 1)  NULL,
    [BBL_MIN_FLAG]                VARCHAR (3)     NULL,
    [BEGIN_METER]                 NUMERIC (19, 3) NULL,
    [BSW_FACTOR]                  NUMERIC (19, 4) NULL,
    [CALC_BSW]                    NUMERIC (19, 2) NULL,
    [CALC_METER_ADJ]              NUMERIC (19, 2) NULL,
    [CALC_NET_BBLS]               NUMERIC (19, 2) NULL,
    [CALC_SHRINKAGE]              NUMERIC (19, 2) NULL,
    [CODE_CO_ID]                  VARCHAR (5)     NULL,
    [CODE_DATE]                   DATETIME        NULL,
    [CODE_SEND_CONT_DATE]         DATETIME        NULL,
    [CODE_SEND_PUR_DATE]          DATETIME        NULL,
    [COMPANY]                     VARCHAR (4)     NULL,
    [CORRECTED_GRAVITY]           NUMERIC (9, 1)  NULL,
    [CORRECTION_TICKET_ID]        VARCHAR (10)    NULL,
    [CORR_BBLS]                   NUMERIC (19, 2) NULL,
    [COST_CENTER]                 VARCHAR (8)     NULL,
    [DISP]                        VARCHAR (4)     NULL,
    [DRIVER]                      VARCHAR (6)     NULL,
    [DRIVER_COMP_DATE]            DATETIME        NULL,
    [END_METER]                   NUMERIC (19, 3) NULL,
    [ENTERED_BSW]                 NUMERIC (19, 2) NULL,
    [ENTERED_GROSS_BBLS]          NUMERIC (19, 2) NULL,
    [ENTERED_NET_BBLS]            NUMERIC (19, 2) NULL,
    [ERROR]                       VARCHAR (5)     NULL,
    [FACILITY]                    VARCHAR (8)     NULL,
    [FEET_READING_1]              VARCHAR (7)     NULL,
    [FEET_READING_2]              VARCHAR (7)     NULL,
    [FRACTIONAL_INCHES_READING_1] VARCHAR (10)    NULL,
    [FRACTIONAL_INCHES_READING_2] VARCHAR (10)    NULL,
    [GATHERER]                    VARCHAR (9)     NULL,
    [GATHERING_SYSTEM]            VARCHAR (11)    NULL,
    [GROSS_BBLS]                  NUMERIC (19, 2) NULL,
    [GROSS_BBLS_1]                NUMERIC (19, 2) NULL,
    [GROSS_BBLS_2]                NUMERIC (19, 2) NULL,
    [INCHES_READING_1]            VARCHAR (7)     NULL,
    [INCHES_READING_2]            VARCHAR (7)     NULL,
    [INJ_PT]                      VARCHAR (9)     NULL,
    [MEAS_PT]                     VARCHAR (12)    NULL,
    [METER]                       VARCHAR (8)     NULL,
    [METER_FACTOR]                NUMERIC (19, 8) NULL,
    [OBSERVED_GRAVITY]            NUMERIC (9, 1)  NULL,
    [OBSERVED_TEMP]               NUMERIC (9, 1)  NULL,
    [OFP_TARIFF_ID]               VARCHAR (9)     NULL,
    [OIL_PURCHASER]               VARCHAR (9)     NULL,
    [OIL_STMT_ID]                 VARCHAR (5)     NULL,
    [OVERRIDE_NET_BBLS]           VARCHAR (8)     NULL,
    [PRODUCT]                     VARCHAR (7)     NULL,
    [PROD_DAILY_ID]               VARCHAR (10)    NULL,
    [PROD_MO_ID]                  VARCHAR (7)     NULL,
    [PROPERTY]                    VARCHAR (16)    NULL,
    [PURCHASER]                   VARCHAR (9)     NULL,
    [PURCHASER_CORRECTED_GRAVITY] NUMERIC (9, 1)  NULL,
    [PURCHASER_GROSS_VALUE]       NUMERIC (19, 2) NULL,
    [PURCHASER_NET_BBLS]          NUMERIC (19, 2) NULL,
    [PURCHASER_PRICE]             NUMERIC (19, 5) NULL,
    [PURCHASER_TAXES]             NUMERIC (19, 2) NULL,
    [QTR_READING_1]               VARCHAR (5)     NULL,
    [QTR_READING_2]               VARCHAR (7)     NULL,
    [REJECT]                      VARCHAR (6)     NULL,
    [RELATED_DRIVER_COMP_FLAGS]   VARCHAR (6)     NULL,
    [REVERSAL_ACCTG_PERIOD]       DATETIME        NULL,
    [REVERSAL_TICKET_ID]          VARCHAR (8)     NULL,
    [RUN_TIME]                    VARCHAR (4)     NULL,
    [SALES_PT]                    VARCHAR (12)    NULL,
    [SEAL_OFF]                    VARCHAR (8)     NULL,
    [SEAL_ON]                     VARCHAR (7)     NULL,
    [SHRINKAGE_FACTOR]            NUMERIC (19, 4) NULL,
    [SOURCE_TICKET_ID]            VARCHAR (8)     NULL,
    [SPLIT_LOAD]                  VARCHAR (5)     NULL,
    [SPLIT_TICKET_FROM]           VARCHAR (6)     NULL,
    [SPLIT_TICKET_TO]             VARCHAR (6)     NULL,
    [STATUS]                      VARCHAR (6)     NULL,
    [STMT_DATE]                   DATETIME        NULL,
    [SUB_SYSTEM]                  VARCHAR (5)     NULL,
    [TANK]                        VARCHAR (8)     NULL,
    [TEMP_CORRECTION]             NUMERIC (19, 2) NULL,
    [TEMP_READING_1]              NUMERIC (9, 1)  NULL,
    [TEMP_READING_2]              NUMERIC (9, 1)  NULL,
    [TICKET]                      VARCHAR (9)     NULL,
    [TICKET_DATE]                 DATETIME        NULL,
    [TICKET_DATE_1]               DATETIME        NULL,
    [TICKET_DATE_2]               DATETIME        NULL,
    [TICKET_TIME_1]               VARCHAR (7)     NULL,
    [TICKET_TIME_2]               VARCHAR (5)     NULL,
    [TICKET_TYPE]                 VARCHAR (4)     NULL,
    [TRANSFER]                    VARCHAR (8)     NULL,
    [TRANSPORT_COST]              NUMERIC (19, 2) NULL,
    [UNUSED_OPERATOR]             VARCHAR (8)     NULL,
    [time_stamp]                  DATETIME        NULL,
    [u2_checksum]                 VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

