CREATE TABLE [dbo].[RUN_TICKET_PRICE_CTRC_IDX] (
    [RUN_TICKET_PRICE_CTRC_IDX_ID]      VARCHAR (255) NOT NULL,
    [u2_id]                             VARCHAR (255) NULL,
    [OG_SALE_DET_SALE_PRICE_CTRC_INDEX] VARCHAR (9)   NULL,
    [time_stamp]                        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RUN_TICKET_PRICE_CTRC_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RUN_TICKE_u2_id_85821]
    ON [dbo].[RUN_TICKET_PRICE_CTRC_IDX]([u2_id] ASC);

