CREATE TABLE [dbo].[RV_OWNER_CONTACTS] (
    [RV_OWNER_CONTACTS_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [CONTACTS]             VARCHAR (30)  NULL,
    [CONTACT_COMMENTS]     VARCHAR (30)  NULL,
    [CONTACT_PHONES]       VARCHAR (12)  NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RV_OWNER_CONTACTS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RV_OWNER_CONTACTS_u2_id_in]
    ON [dbo].[RV_OWNER_CONTACTS]([u2_id] ASC);

