CREATE TABLE [dbo].[RV_OWNER_WIRE_TO] (
    [RV_OWNER_WIRE_TO_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [WIRE_TO]             VARCHAR (40)  NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RV_OWNER_WIRE_TO_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RV_OWNER_WIRE_TO_u2_id_in]
    ON [dbo].[RV_OWNER_WIRE_TO]([u2_id] ASC);

