CREATE TABLE [dbo].[RV_OWNER_PAY_BAL_CO] (
    [RV_OWNER_PAY_BAL_CO_ID] VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [PAY_BAL_COMPANIES]      VARCHAR (5)   NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RV_OWNER_PAY_BAL_CO_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RV_OWNER_PAY_BAL_CO_u2_id_in]
    ON [dbo].[RV_OWNER_PAY_BAL_CO]([u2_id] ASC);

