CREATE TABLE [dbo].[RV_OWNER] (
    [u2_id]                 VARCHAR (255) NOT NULL,
    [BACKUP_WH_FLAG]        VARCHAR (2)   NULL,
    [BANK]                  VARCHAR (10)  NULL,
    [BANK_ACCT]             VARCHAR (17)  NULL,
    [BANK_ACCT_TYPE]        VARCHAR (3)   NULL,
    [BASE_ID]               VARCHAR (6)   NULL,
    [CORR_ADDRESS]          VARCHAR (9)   NULL,
    [DFLT_INTEREST_TYPE]    VARCHAR (4)   NULL,
    [EFFECT_DATE]           DATETIME      NULL,
    [ELECTRONIC_REV_FLAG]   VARCHAR (4)   NULL,
    [EXPIRE_DATE]           DATETIME      NULL,
    [INSIDE_COMPANY]        VARCHAR (4)   NULL,
    [MIN_SUSPENSE]          VARCHAR (4)   NULL,
    [NET_CUSTOMER]          VARCHAR (8)   NULL,
    [PMT_ADDRESS]           VARCHAR (9)   NULL,
    [PRENOTE_DATE]          DATETIME      NULL,
    [SITE]                  VARCHAR (3)   NULL,
    [SORT_ORDER]            VARCHAR (5)   NULL,
    [SPECIAL_INSTRUCTIONS]  VARCHAR (98)  NULL,
    [SUMMARY_CHECK]         VARCHAR (7)   NULL,
    [SUPPRESS_ACH_DETAIL]   VARCHAR (4)   NULL,
    [SUPPRESS_CHECK_DETAIL] VARCHAR (4)   NULL,
    [TAX_CTRY]              VARCHAR (4)   NULL,
    [TEN42_EXEMPT_CODE]     VARCHAR (6)   NULL,
    [TEN42_REQ]             VARCHAR (4)   NULL,
    [TEN99_REQ]             VARCHAR (5)   NULL,
    [time_stamp]            DATETIME      NULL,
    [u2_checksum]           VARCHAR (25)  NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

