CREATE TABLE [dbo].[RV_SYS] (
    [u2_id]                         VARCHAR (255)   NOT NULL,
    [ACCRUAL_BAL_INCOME_ACCT]       VARCHAR (10)    NULL,
    [ACCRUAL_BAL_PAYABLE_ACCT]      VARCHAR (10)    NULL,
    [ACCRUAL_CLRG_ACCT]             VARCHAR (10)    NULL,
    [ACCRUAL_RECV_ACCT]             VARCHAR (10)    NULL,
    [ACCRUAL_REV_VOU_APP]           VARCHAR (10)    NULL,
    [ACCRUAL_REV_VOU_SRC]           VARCHAR (7)     NULL,
    [ACCRUAL_SALES_VOU_APP]         VARCHAR (10)    NULL,
    [ACCRUAL_SALES_VOU_SRC]         VARCHAR (7)     NULL,
    [ACCRUED_OWNER_PAYABLE_ACCT]    VARCHAR (12)    NULL,
    [ACCRUED_TAXES_PAYABLE_ACCT]    VARCHAR (10)    NULL,
    [ACC_CUTBACK_VOU_APP]           VARCHAR (10)    NULL,
    [ACC_CUTBACK_VOU_SRC]           VARCHAR (7)     NULL,
    [ARCHIVE_DIV_FLAG]              VARCHAR (7)     NULL,
    [AR_WRITE_OFF_AMT]              NUMERIC (19, 2) NULL,
    [AR_WRITE_OFF_VOU_APP]          VARCHAR (12)    NULL,
    [AR_WRITE_OFF_VOU_SRC]          VARCHAR (12)    NULL,
    [BAL_INCOME_ACCT]               VARCHAR (10)    NULL,
    [BAL_OWNER]                     VARCHAR (9)     NULL,
    [BAL_PAYABLE_ACCT]              VARCHAR (10)    NULL,
    [CASH_ERR_DOLLARS]              NUMERIC (19, 2) NULL,
    [CASH_ERR_RATE]                 NUMERIC (19, 4) NULL,
    [CLRG_ACCT]                     VARCHAR (10)    NULL,
    [CLRG_WRITE_OFF_AMT]            NUMERIC (19, 2) NULL,
    [CONTRACT_REQ]                  VARCHAR (8)     NULL,
    [CUTBACK_VOU_APP]               VARCHAR (10)    NULL,
    [CUTBACK_VOU_SRC]               VARCHAR (7)     NULL,
    [CYCLE_REQ_FLAG]                VARCHAR (5)     NULL,
    [DFLT_RECEIVABLE_FLAG]          VARCHAR (4)     NULL,
    [DFLT_SALE_TYPE]                VARCHAR (4)     NULL,
    [DYNAMIC_REMIT_OWNER]           VARCHAR (10)    NULL,
    [ELEC_CHECK_DET_MSG]            VARCHAR (30)    NULL,
    [EST_REV_VOU_APP]               VARCHAR (10)    NULL,
    [EST_REV_VOU_SRC]               VARCHAR (4)     NULL,
    [EST_SALES_SALE_TYPE]           VARCHAR (5)     NULL,
    [FUTURE_CASH_OVERRIDE]          VARCHAR (8)     NULL,
    [INSIDER_PAY]                   VARCHAR (1)     NULL,
    [MIN_SUSPENSE]                  VARCHAR (4)     NULL,
    [NET_ERR_DOLLARS]               NUMERIC (19, 2) NULL,
    [NET_ERR_RATE]                  NUMERIC (19, 4) NULL,
    [NONSTD_CPT_DIST_FLAG]          VARCHAR (9)     NULL,
    [NON_CASH_SALES_VOU_APP]        VARCHAR (10)    NULL,
    [NON_CASH_SALES_VOU_SRC]        VARCHAR (7)     NULL,
    [OGP_PURCHASE_ACCT]             VARCHAR (10)    NULL,
    [OG_SALE_RVS_ACCT]              VARCHAR (10)    NULL,
    [OG_SALE_RVS_VOU_APP]           VARCHAR (10)    NULL,
    [OG_SALE_RVS_VOU_SRC]           VARCHAR (4)     NULL,
    [OWNER_ADJ_VOU_APP]             VARCHAR (10)    NULL,
    [OWNER_ADJ_VOU_SRC]             VARCHAR (7)     NULL,
    [OWNER_SALE_SRC_CPT]            VARCHAR (5)     NULL,
    [OWNER_SALE_SRC_PRINT_FLAG]     VARCHAR (5)     NULL,
    [OWNER_SALE_SRC_VOL_CPT]        VARCHAR (5)     NULL,
    [OWNER_SALE_SRC_VOL_PRINT_FLAG] VARCHAR (5)     NULL,
    [OWNER_SALE_WI_CPT]             VARCHAR (5)     NULL,
    [OWNER_SALE_WI_PRINT_FLAG]      VARCHAR (5)     NULL,
    [OWNER_SALE_WI_VOL_CPT]         VARCHAR (5)     NULL,
    [OWNER_SALE_WI_VOL_PRINT_FLAG]  VARCHAR (5)     NULL,
    [PAYABLE_ACCT]                  VARCHAR (10)    NULL,
    [PAY_CODE_ADJ_VOU_APP]          VARCHAR (10)    NULL,
    [PAY_CODE_ADJ_VOU_SRC]          VARCHAR (4)     NULL,
    [PAY_CODE_AUTHORIZATION]        VARCHAR (4)     NULL,
    [PREPAID_SALES_ACCT]            VARCHAR (10)    NULL,
    [PURCH_AR_ACCT]                 VARCHAR (10)    NULL,
    [PURCH_AR_UBA_VOLUMETRIC_ACCT]  VARCHAR (10)    NULL,
    [PURCH_AR_VOLUMETRIC_ACCT]      VARCHAR (10)    NULL,
    [REFUND_VOU_APP]                VARCHAR (9)     NULL,
    [REFUND_VOU_SRC]                VARCHAR (7)     NULL,
    [SALES_VOU_APP]                 VARCHAR (10)    NULL,
    [SALES_VOU_SRC]                 VARCHAR (5)     NULL,
    [SIG_CK_AMT]                    NUMERIC (19, 2) NULL,
    [SUSPENSE_ACCT]                 VARCHAR (10)    NULL,
    [TOLERANCE_ERROR_OVERRIDE]      VARCHAR (9)     NULL,
    [TRANS_OPTION]                  VARCHAR (11)    NULL,
    [WRITE_OFF_ACCT]                VARCHAR (10)    NULL,
    [time_stamp]                    DATETIME        NULL,
    [u2_checksum]                   VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

