CREATE TABLE [dbo].[RV_SYS_SEN168] (
    [RV_SYS_SEN168_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [SEN168_INT_TYPES] VARCHAR (6)   NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RV_SYS_SEN168_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RV_SYS_SEN168_u2_id_in]
    ON [dbo].[RV_SYS_SEN168]([u2_id] ASC);

