CREATE TABLE [dbo].[RVCC_INFO_REMIT] (
    [RVCC_INFO_REMIT_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [REMITTERS]          VARCHAR (9)   NULL,
    [REMITTER_COMPANIES] VARCHAR (8)   NULL,
    [REMITTER_EXP_DATES] DATETIME      NULL,
    [REMITTER_PRODUCTS]  VARCHAR (8)   NULL,
    [REMITTER_PROPS]     VARCHAR (8)   NULL,
    [REMIT_FMTS]         VARCHAR (11)  NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RVCC_INFO_REMIT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RVCC_INFO_REMIT_u2_id_in]
    ON [dbo].[RVCC_INFO_REMIT]([u2_id] ASC);

