CREATE TABLE [dbo].[RVCC_INFO_REMIT_TP] (
    [subValueId]         VARCHAR (255) NOT NULL,
    [RVCC_INFO_REMIT_ID] VARCHAR (255) NULL,
    [REMIT_TYPES]        VARCHAR (5)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RVCC_INFO_RVCC_INFO_15812]
    ON [dbo].[RVCC_INFO_REMIT_TP]([RVCC_INFO_REMIT_ID] ASC);

