CREATE TABLE [dbo].[RVCC_INFO_ACCR] (
    [RVCC_INFO_ACCR_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [ACCRUAL_DIV_IDS]   VARCHAR (7)   NULL,
    [ACCRUAL_METHODS]   VARCHAR (7)   NULL,
    [VALID_PRODUCTS]    VARCHAR (8)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([RVCC_INFO_ACCR_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RVCC_INFO_ACCR_u2_id_in]
    ON [dbo].[RVCC_INFO_ACCR]([u2_id] ASC);

