CREATE TABLE [dbo].[RVCLOSE_CTL_EXC_USER] (
    [subValueId]         VARCHAR (255) NOT NULL,
    [RVCLOSE_CTL_EXC_ID] VARCHAR (255) NULL,
    [EXC_USERS]          VARCHAR (9)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RVCLOSE_C_RVCLOSE_C_64313]
    ON [dbo].[RVCLOSE_CTL_EXC_USER]([RVCLOSE_CTL_EXC_ID] ASC);

