CREATE TABLE [dbo].[RVCTL_INT_CAT] (
    [subValueId]    VARCHAR (255) NOT NULL,
    [RVCTL_CPT_ID]  VARCHAR (255) NULL,
    [INTEREST_CATS] VARCHAR (5)   NULL,
    [OFFSET_ACCTS]  VARCHAR (10)  NULL,
    [TARGET_ACCTS]  VARCHAR (10)  NULL,
    [time_stamp]    DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [RVCTL_INT_CAT_RVCTL_CPT_ID_in]
    ON [dbo].[RVCTL_INT_CAT]([RVCTL_CPT_ID] ASC);

