CREATE TABLE [dbo].[SALE_CONTRACT_OG_SALE_DET_ALLOC_IDX] (
    [SALE_CONTRACT_OG_SALE_DET_ALLOC_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                                  VARCHAR (255) NULL,
    [ALLOC_OG_SALE_DET_INDEX]                VARCHAR (10)  NULL,
    [time_stamp]                             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([SALE_CONTRACT_OG_SALE_DET_ALLOC_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SALE_CONT_u2_id_69518]
    ON [dbo].[SALE_CONTRACT_OG_SALE_DET_ALLOC_IDX]([u2_id] ASC);

