CREATE TABLE [dbo].[STATE_WTYPE_STATE_WTYPEX] (
    [STATE_WTYPE_STATE_WTYPEX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                       VARCHAR (255) NULL,
    [STATE_WTYPEX]                VARCHAR (20)  NULL,
    [time_stamp]                  DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STATE_WTYPE_STATE_WTYPEX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STATE_WTY_u2_id_71370]
    ON [dbo].[STATE_WTYPE_STATE_WTYPEX]([u2_id] ASC);

