CREATE TABLE [dbo].[STATE_SVY] (
    [STATE_SVY_ID]   VARCHAR (255) NOT NULL,
    [u2_id]          VARCHAR (255) NULL,
    [SURVEY_METHODS] VARCHAR (6)   NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STATE_SVY_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STATE_SVY_u2_id_in]
    ON [dbo].[STATE_SVY]([u2_id] ASC);

