CREATE TABLE [dbo].[STATE_MER] (
    [STATE_MER_ID] VARCHAR (255) NOT NULL,
    [u2_id]        VARCHAR (255) NULL,
    [MERIDIANS]    VARCHAR (8)   NULL,
    [time_stamp]   DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STATE_MER_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STATE_MER_u2_id_in]
    ON [dbo].[STATE_MER]([u2_id] ASC);

