CREATE TABLE [dbo].[STATE_LEASE_TAX] (
    [STATE_LEASE_TAX_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [TAXPAYER]           VARCHAR (8)   NULL,
    [TAXPAYER_EFF_DATE]  DATETIME      NULL,
    [TAXPAYER_TERM_DATE] DATETIME      NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STATE_LEASE_TAX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STATE_LEASE_TAX_u2_id_in]
    ON [dbo].[STATE_LEASE_TAX]([u2_id] ASC);

