CREATE TABLE [dbo].[STATE_EDI_AUDIT] (
    [STATE_EDI_AUDIT_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [SYSTEM_DATE]        DATETIME      NULL,
    [SYSTEM_TIME]        VARCHAR (8)   NULL,
    [SYSTEM_USER_ID]     VARCHAR (4)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STATE_EDI_AUDIT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STATE_EDI_AUDIT_u2_id_in]
    ON [dbo].[STATE_EDI_AUDIT]([u2_id] ASC);

