CREATE TABLE [dbo].[STATE_EDI_DATA_STR] (
    [subValueId]       VARCHAR (255) NOT NULL,
    [STATE_EDI_GRP_ID] VARCHAR (255) NULL,
    [DATA_STR]         VARCHAR (20)  NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STATE_EDI_STATE_EDI_81793]
    ON [dbo].[STATE_EDI_DATA_STR]([STATE_EDI_GRP_ID] ASC);

