CREATE TABLE [dbo].[STATE_PRD_XMPT] (
    [STATE_PRD_XMPT_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [XMPT_CPTS]         VARCHAR (4)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STATE_PRD_XMPT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STATE_PRD_XMPT_u2_id_in]
    ON [dbo].[STATE_PRD_XMPT]([u2_id] ASC);

