CREATE TABLE [dbo].[STATE_FORM_PRD] (
    [STATE_FORM_PRD_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [STATE_PRDS]        VARCHAR (4)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STATE_FORM_PRD_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STATE_FORM_PRD_u2_id_in]
    ON [dbo].[STATE_FORM_PRD]([u2_id] ASC);

