CREATE TABLE [dbo].[STATE_STATEX] (
    [STATE_STATEX_ID] VARCHAR (255) NOT NULL,
    [u2_id]           VARCHAR (255) NULL,
    [STATEX]          VARCHAR (20)  NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STATE_STATEX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STATE_STATEX_u2_id_in]
    ON [dbo].[STATE_STATEX]([u2_id] ASC);

