CREATE TABLE [dbo].[STATE_LEASE_PROD] (
    [STATE_LEASE_PROD_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [PRODUCER]            VARCHAR (8)   NULL,
    [PRODUCER_EFF_DATE]   DATETIME      NULL,
    [PRODUCER_TERM_DATE]  DATETIME      NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STATE_LEASE_PROD_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STATE_LEASE_PROD_u2_id_in]
    ON [dbo].[STATE_LEASE_PROD]([u2_id] ASC);

