CREATE TABLE [dbo].[STATE_FORM_EDI] (
    [STATE_FORM_EDI_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [EDI_ADJ_TYPE_HIER] VARCHAR (4)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STATE_FORM_EDI_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STATE_FORM_EDI_u2_id_in]
    ON [dbo].[STATE_FORM_EDI]([u2_id] ASC);

