CREATE TABLE [dbo].[STATE_PBASE_PBASE] (
    [STATE_PBASE_PBASE_ID] VARCHAR (255)   NOT NULL,
    [u2_id]                VARCHAR (255)   NULL,
    [FROM_PBASE]           NUMERIC (19, 4) NULL,
    [time_stamp]           DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([STATE_PBASE_PBASE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STATE_PBASE_PBASE_u2_id_in]
    ON [dbo].[STATE_PBASE_PBASE]([u2_id] ASC);

