CREATE TABLE [dbo].[STD_TRANS_OWN_JIB_IDX] (
    [STD_TRANS_OWN_JIB_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                    VARCHAR (255) NULL,
    [OWNER_JIB_INDEX]          VARCHAR (8)   NULL,
    [time_stamp]               DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STD_TRANS_OWN_JIB_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STD_TRANS_OWN_JIB_IDX_u2_id_in]
    ON [dbo].[STD_TRANS_OWN_JIB_IDX]([u2_id] ASC);

