CREATE TABLE [dbo].[STD_RPT_FMT_LOS] (
    [STD_RPT_FMT_LOS_ID]         VARCHAR (255) NOT NULL,
    [u2_id]                      VARCHAR (255) NULL,
    [LEASE_OPERATING_STATEMENTS] VARCHAR (9)   NULL,
    [time_stamp]                 DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STD_RPT_FMT_LOS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STD_RPT_FMT_LOS_u2_id_in]
    ON [dbo].[STD_RPT_FMT_LOS]([u2_id] ASC);

