CREATE TABLE [dbo].[STD_TRANS_CN_TRANS_IDX] (
    [STD_TRANS_CN_TRANS_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                     VARCHAR (255) NULL,
    [CN_TRANS_INDEX]            VARCHAR (9)   NULL,
    [time_stamp]                DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STD_TRANS_CN_TRANS_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STD_TRANS_u2_id_13364]
    ON [dbo].[STD_TRANS_CN_TRANS_IDX]([u2_id] ASC);

