CREATE TABLE [dbo].[STD_TRANS_CF_INS] (
    [subValueId]        VARCHAR (255)   NOT NULL,
    [STD_TRANS_CASH_ID] VARCHAR (255)   NULL,
    [CF_INS_AMTS]       NUMERIC (19, 2) NULL,
    [CF_INS_COMPANIES]  VARCHAR (3)     NULL,
    [CF_POST_DATE]      DATETIME        NULL,
    [time_stamp]        DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STD_TRANS_STD_TRANS_89987]
    ON [dbo].[STD_TRANS_CF_INS]([STD_TRANS_CASH_ID] ASC);

