CREATE TABLE [dbo].[STD_RPT_FMT_INC_ST] (
    [STD_RPT_FMT_INC_ST_ID] VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [INCOME_STATEMENTS]     VARCHAR (8)   NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STD_RPT_FMT_INC_ST_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STD_RPT_FMT_INC_ST_u2_id_in]
    ON [dbo].[STD_RPT_FMT_INC_ST]([u2_id] ASC);

