CREATE TABLE [dbo].[STD_RPT_FMT_AFE_COMP] (
    [STD_RPT_FMT_AFE_COMP_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [AFE_COMPARISONS]         VARCHAR (10)  NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STD_RPT_FMT_AFE_COMP_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STD_RPT_FMT_AFE_COMP_u2_id_in]
    ON [dbo].[STD_RPT_FMT_AFE_COMP]([u2_id] ASC);

