CREATE TABLE [dbo].[STD_TRANS] (
    [u2_id]                 VARCHAR (255)   NOT NULL,
    [ACCT]                  VARCHAR (10)    NULL,
    [ACCTG_PERIOD]          DATETIME        NULL,
    [ACTIVITY_DATE]         DATETIME        NULL,
    [ALLOC_PCT]             NUMERIC (19, 4) NULL,
    [AMT]                   NUMERIC (19, 2) NULL,
    [APP]                   VARCHAR (8)     NULL,
    [APPLY_WHT]             VARCHAR (5)     NULL,
    [BALANCING_AMT]         NUMERIC (19, 2) NULL,
    [BAL_SOURCE_TRANS_ID]   VARCHAR (8)     NULL,
    [CC_ALLOC_DATE]         DATETIME        NULL,
    [CC_ALLOC_ID]           VARCHAR (15)    NULL,
    [CN_GRP_ID]             VARCHAR (25)    NULL,
    [CN_PCT]                NUMERIC (19, 8) NULL,
    [COST_CENTER]           VARCHAR (6)     NULL,
    [CPT]                   VARCHAR (4)     NULL,
    [DESCRIPTION]           VARCHAR (55)    NULL,
    [DIRECT_BILL]           VARCHAR (9)     NULL,
    [DIST_COMPANY]          VARCHAR (4)     NULL,
    [DOI]                   VARCHAR (5)     NULL,
    [DOI_SESSION]           VARCHAR (4)     NULL,
    [GL_DATE]               DATETIME        NULL,
    [INTERCO_FROM_TRANS_ID] VARCHAR (8)     NULL,
    [INTERCO_TO_TRANS_ID]   VARCHAR (8)     NULL,
    [JIB_ALLOC_DATE]        DATETIME        NULL,
    [JIB_DECK]              VARCHAR (5)     NULL,
    [JIB_DECK_SESSION]      VARCHAR (4)     NULL,
    [NAME]                  VARCHAR (6)     NULL,
    [PMT_AMT]               NUMERIC (19, 2) NULL,
    [PO_NO]                 VARCHAR (8)     NULL,
    [PRODUCT]               VARCHAR (3)     NULL,
    [PROJECT]               VARCHAR (9)     NULL,
    [QTY1]                  NUMERIC (19, 2) NULL,
    [QTY2]                  NUMERIC (19, 2) NULL,
    [RECEIPT_ID]            VARCHAR (10)    NULL,
    [SOURCE_CURRENCY]       VARCHAR (3)     NULL,
    [SOURCE_DOCUMENT]       VARCHAR (26)    NULL,
    [SOURCE_PORT]           VARCHAR (8)     NULL,
    [SOURCE_TABLE]          VARCHAR (12)    NULL,
    [SRC_ALLOC_TRANS_ID]    VARCHAR (9)     NULL,
    [SRC_CN_TRANS_ID]       VARCHAR (9)     NULL,
    [STAT1_AMT]             NUMERIC (19, 2) NULL,
    [STAT1_QTY1]            NUMERIC (19, 2) NULL,
    [STAT1_QTY2]            NUMERIC (19, 2) NULL,
    [STAT2_AMT]             NUMERIC (19, 2) NULL,
    [STAT2_QTY1]            NUMERIC (19, 2) NULL,
    [STAT2_QTY2]            NUMERIC (19, 2) NULL,
    [STD_JE_ID]             VARCHAR (26)    NULL,
    [SYSTEM_DATE]           DATETIME        NULL,
    [SYSTEM_TIME]           VARCHAR (8)     NULL,
    [SYSTEM_USER_ID]        VARCHAR (5)     NULL,
    [TEN99_CODE]            VARCHAR (4)     NULL,
    [TYPE]                  VARCHAR (6)     NULL,
    [time_stamp]            DATETIME        NULL,
    [u2_checksum]           VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

