CREATE TABLE [dbo].[STD_TRANS_TARG_CURR] (
    [STD_TRANS_TARG_CURR_ID] VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [TARGET_CURRENCIES]      VARCHAR (4)   NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STD_TRANS_TARG_CURR_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STD_TRANS_TARG_CURR_u2_id_in]
    ON [dbo].[STD_TRANS_TARG_CURR]([u2_id] ASC);

