CREATE TABLE [dbo].[STD_TRANS_INS_ACCTG_PER] (
    [STD_TRANS_INS_ACCTG_PER_ID] VARCHAR (255) NOT NULL,
    [u2_id]                      VARCHAR (255) NULL,
    [INS_ACCTG_PERIODS]          DATETIME      NULL,
    [time_stamp]                 DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STD_TRANS_INS_ACCTG_PER_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STD_TRANS_u2_id_33026]
    ON [dbo].[STD_TRANS_INS_ACCTG_PER]([u2_id] ASC);

