CREATE TABLE [dbo].[STD_RPT_FMT_BAL_SH] (
    [STD_RPT_FMT_BAL_SH_ID] VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [BALANCE_SHEETS]        VARCHAR (7)   NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([STD_RPT_FMT_BAL_SH_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [STD_RPT_FMT_BAL_SH_u2_id_in]
    ON [dbo].[STD_RPT_FMT_BAL_SH]([u2_id] ASC);

