CREATE TABLE [dbo].[SUBSCRIPTION_COMMENT] (
    [SUBSCRIPTION_COMMENT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [COMMENTS]                VARCHAR (40)  NULL,
    [COMMENT_DATES]           VARCHAR (10)  NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([SUBSCRIPTION_COMMENT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SUBSCRIPTION_COMMENT_u2_id_in]
    ON [dbo].[SUBSCRIPTION_COMMENT]([u2_id] ASC);

