CREATE TABLE [dbo].[TANK_PROD_ROUTES] (
    [TANK_PROD_ROUTES_ID]  VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [PROD_ROUTES]          VARCHAR (9)   NULL,
    [PROD_ROUTE_EFF_DATES] DATETIME      NULL,
    [PROD_ROUTE_EXP_DATES] DATETIME      NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TANK_PROD_ROUTES_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TANK_PROD_ROUTES_u2_id_in]
    ON [dbo].[TANK_PROD_ROUTES]([u2_id] ASC);

