CREATE TABLE [dbo].[TANK_PROD_FAC_PRD_EFF_DT] (
    [TANK_PROD_FAC_PRD_EFF_DT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                       VARCHAR (255) NULL,
    [PROD_FAC_PRD_EFF_DATES]      DATETIME      NULL,
    [PROD_FAC_PRD_EXP_DATES]      DATETIME      NULL,
    [time_stamp]                  DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TANK_PROD_FAC_PRD_EFF_DT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TANK_PROD_u2_id_64679]
    ON [dbo].[TANK_PROD_FAC_PRD_EFF_DT]([u2_id] ASC);

