CREATE TABLE [dbo].[TANK_EFF_DATES] (
    [TANK_EFF_DATES_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [EFF_DATES]         DATETIME      NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TANK_EFF_DATES_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TANK_EFF_DATES_u2_id_in]
    ON [dbo].[TANK_EFF_DATES]([u2_id] ASC);

