CREATE TABLE [dbo].[TANK_LEVEL] (
    [TANK_LEVEL_ID] VARCHAR (255) NOT NULL,
    [u2_id]         VARCHAR (255) NULL,
    [INVENTORIES]   VARCHAR (11)  NULL,
    [LEVELS]        VARCHAR (10)  NULL,
    [READING_DATES] DATETIME      NULL,
    [time_stamp]    DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TANK_LEVEL_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TANK_LEVEL_u2_id_in]
    ON [dbo].[TANK_LEVEL]([u2_id] ASC);

