CREATE TABLE [dbo].[TEN99_CTL] (
    [u2_id]                VARCHAR (255) NOT NULL,
    [COMPANY_ADDR]         VARCHAR (30)  NULL,
    [COMPANY_CITY]         VARCHAR (13)  NULL,
    [COMPANY_NAME]         VARCHAR (37)  NULL,
    [COMPANY_STATE]        VARCHAR (7)   NULL,
    [COMPANY_ZIP]          VARCHAR (9)   NULL,
    [CONTACT_EMAIL]        VARCHAR (35)  NULL,
    [CONTACT_NAME]         VARCHAR (61)  NULL,
    [CONTACT_PHONE]        VARCHAR (21)  NULL,
    [CORRECTION_FILE_NAME] VARCHAR (15)  NULL,
    [CORR_FILE_IND]        VARCHAR (4)   NULL,
    [FIRST_PAYER_NAME]     VARCHAR (37)  NULL,
    [FOREIGN_CORP]         VARCHAR (1)   NULL,
    [LAST_FILING]          VARCHAR (1)   NULL,
    [MAG_TAPE_IND]         VARCHAR (1)   NULL,
    [NAME_CONTROL]         VARCHAR (10)  NULL,
    [ORIG_FILE_IND]        VARCHAR (4)   NULL,
    [PAYERS_TIN]           VARCHAR (11)  NULL,
    [PAYER_PHONE]          VARCHAR (12)  NULL,
    [REPLACE_CHARS]        VARCHAR (11)  NULL,
    [REPL_FILE_IND]        VARCHAR (4)   NULL,
    [REPORT_COMPANY]       VARCHAR (3)   NULL,
    [STATE_FILER]          VARCHAR (1)   NULL,
    [STATE_OF_INCORP]      VARCHAR (6)   NULL,
    [SVC_BUREAU]           VARCHAR (1)   NULL,
    [TCC]                  VARCHAR (5)   NULL,
    [TEN42_TCC]            VARCHAR (8)   NULL,
    [TEST_IND]             VARCHAR (1)   NULL,
    [TRANSMITTER_ADDR]     VARCHAR (40)  NULL,
    [TRANSMITTER_CSZ]      VARCHAR (40)  NULL,
    [TRANSMITTER_NAME]     VARCHAR (40)  NULL,
    [TRANSMITTER_TIN]      VARCHAR (11)  NULL,
    [XFER_AGENT_ADDR]      VARCHAR (40)  NULL,
    [XFER_AGENT_CITY]      VARCHAR (40)  NULL,
    [XFER_AGENT_IND]       VARCHAR (1)   NULL,
    [XFER_AGENT_NAME]      VARCHAR (40)  NULL,
    [XFER_AGENT_STATE]     VARCHAR (5)   NULL,
    [XFER_AGENT_ZIP]       VARCHAR (10)  NULL,
    [time_stamp]           DATETIME      NULL,
    [u2_checksum]          VARCHAR (25)  NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

