CREATE TABLE [dbo].[TRACT_REC] (
    [TRACT_REC_ID]   VARCHAR (255) NOT NULL,
    [u2_id]          VARCHAR (255) NULL,
    [REC_BOOKS]      VARCHAR (16)  NULL,
    [REC_BOOK_TYPES] VARCHAR (18)  NULL,
    [REC_DATES]      VARCHAR (8)   NULL,
    [REC_PAGES]      VARCHAR (14)  NULL,
    [REC_REFS]       VARCHAR (63)  NULL,
    [REC_STATUS]     VARCHAR (6)   NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TRACT_REC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRACT_REC_u2_id_in]
    ON [dbo].[TRACT_REC]([u2_id] ASC);

