CREATE TABLE [dbo].[TRACT_NORM_PMT] (
    [TRACT_NORM_PMT_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [NORMAL_PMT_MOS]    VARCHAR (3)   NULL,
    [NORMAL_PMT_TYPES]  VARCHAR (8)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TRACT_NORM_PMT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRACT_NORM_PMT_u2_id_in]
    ON [dbo].[TRACT_NORM_PMT]([u2_id] ASC);

