CREATE TABLE [dbo].[TRACT_ADDL_PROSPECTS] (
    [TRACT_ADDL_PROSPECTS_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [ADDL_PROSPECTS]          VARCHAR (9)   NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TRACT_ADDL_PROSPECTS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRACT_ADDL_PROSPECTS_u2_id_in]
    ON [dbo].[TRACT_ADDL_PROSPECTS]([u2_id] ASC);

