CREATE TABLE [dbo].[TRACT_SPC_OBL] (
    [TRACT_SPC_OBL_ID]  VARCHAR (255)  NOT NULL,
    [u2_id]             VARCHAR (255)  NULL,
    [SPC_OBL_DATES]     DATETIME       NULL,
    [SPC_OBL_DESCS]     VARCHAR (2595) NULL,
    [SPC_OBL_END_DATES] DATETIME       NULL,
    [SPC_OBL_PERIODS]   VARCHAR (8)    NULL,
    [SPC_OBL_TYPES]     VARCHAR (13)   NULL,
    [time_stamp]        DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([TRACT_SPC_OBL_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRACT_SPC_OBL_u2_id_in]
    ON [dbo].[TRACT_SPC_OBL]([u2_id] ASC);

