CREATE TABLE [dbo].[TRACT_BILLING_TRANS] (
    [TRACT_BILLING_TRANS_ID] VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [BILLING_TRANS_INDEX]    VARCHAR (42)  NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TRACT_BILLING_TRANS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRACT_BILLING_TRANS_u2_id_in]
    ON [dbo].[TRACT_BILLING_TRANS]([u2_id] ASC);

