CREATE TABLE [dbo].[TRACT_ADDL_CTYS] (
    [TRACT_ADDL_CTYS_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [ADDL_CTYS]          VARCHAR (7)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TRACT_ADDL_CTYS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRACT_ADDL_CTYS_u2_id_in]
    ON [dbo].[TRACT_ADDL_CTYS]([u2_id] ASC);

