CREATE TABLE [dbo].[TRANS_CODE_AT_EFF_DT] (
    [subValueId]       VARCHAR (255) NOT NULL,
    [TRANS_CODE_AT_ID] VARCHAR (255) NULL,
    [AT_EFF_DATES]     DATETIME      NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRANS_COD_TRANS_COD_72583]
    ON [dbo].[TRANS_CODE_AT_EFF_DT]([TRANS_CODE_AT_ID] ASC);

