CREATE TABLE [dbo].[TRANS_SRC_DOCS] (
    [TRANS_SRC_DOCS_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [SOURCE_DOCUMENT]   VARCHAR (35)  NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TRANS_SRC_DOCS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRANS_SRC_DOCS_u2_id_in]
    ON [dbo].[TRANS_SRC_DOCS]([u2_id] ASC);

