CREATE TABLE [dbo].[TRANS_CODE_UDF] (
    [TRANS_CODE_UDF_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [USER_DATA_FIELDS]  VARCHAR (6)   NULL,
    [USER_DATA_VALUES]  VARCHAR (5)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TRANS_CODE_UDF_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRANS_CODE_UDF_u2_id_in]
    ON [dbo].[TRANS_CODE_UDF]([u2_id] ASC);

