CREATE TABLE [dbo].[TRANS_CAT_UDF] (
    [TRANS_CAT_UDF_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [USER_DATA_FIELDS] VARCHAR (19)  NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TRANS_CAT_UDF_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRANS_CAT_UDF_u2_id_in]
    ON [dbo].[TRANS_CAT_UDF]([u2_id] ASC);

