CREATE TABLE [dbo].[TRANS_OWNER_JIB_IDX] (
    [TRANS_OWNER_JIB_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [OWNER_JIB_INDEX]        VARCHAR (8)   NULL,
    [REALLOC_OWNER_JIB_FLAG] VARCHAR (7)   NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TRANS_OWNER_JIB_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRANS_OWNER_JIB_IDX_u2_id_in]
    ON [dbo].[TRANS_OWNER_JIB_IDX]([u2_id] ASC);

