CREATE TABLE [dbo].[TRANS_FROM_ALLOC_TRANS_IDX] (
    [TRANS_FROM_ALLOC_TRANS_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                         VARCHAR (255) NULL,
    [FROM_ALLOC_TRANS_INDEX]        VARCHAR (8)   NULL,
    [time_stamp]                    DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TRANS_FROM_ALLOC_TRANS_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRANS_FRO_u2_id_94769]
    ON [dbo].[TRANS_FROM_ALLOC_TRANS_IDX]([u2_id] ASC);

