CREATE TABLE [dbo].[TRANS_TRANS_CODE] (
    [TRANS_TRANS_CODE_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [TRANS_CATS]          VARCHAR (17)  NULL,
    [TRANS_CODES]         VARCHAR (48)  NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TRANS_TRANS_CODE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRANS_TRANS_CODE_u2_id_in]
    ON [dbo].[TRANS_TRANS_CODE]([u2_id] ASC);

