CREATE TABLE [dbo].[TRANS_CAT_EDIT] (
    [subValueId]            VARCHAR (255) NOT NULL,
    [TRANS_CAT_UDF_ID]      VARCHAR (255) NULL,
    [USER_DATA_EDIT_CODES]  VARCHAR (4)   NULL,
    [USER_DATA_EDIT_VALUES] VARCHAR (5)   NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRANS_CAT_TRANS_CAT_29058]
    ON [dbo].[TRANS_CAT_EDIT]([TRANS_CAT_UDF_ID] ASC);

