CREATE TABLE [dbo].[TRANS_CODE_EFF_DT] (
    [TRANS_CODE_EFF_DT_ID]   VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [PROD_FAC_PRD_EFF_DATES] DATETIME      NULL,
    [PROD_FAC_PRD_EXP_DATES] DATETIME      NULL,
    [PROD_FAC_PRD_INDEX]     VARCHAR (12)  NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TRANS_CODE_EFF_DT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRANS_CODE_EFF_DT_u2_id_in]
    ON [dbo].[TRANS_CODE_EFF_DT]([u2_id] ASC);

