CREATE TABLE [dbo].[TRANS_AT_TRANS_IDX] (
    [TRANS_AT_TRANS_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [AT_ASSET_DET_INDEX]    VARCHAR (12)  NULL,
    [AT_PERSPECTIVE]        VARCHAR (12)  NULL,
    [AT_TRANS_INDEX]        VARCHAR (11)  NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TRANS_AT_TRANS_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRANS_AT_TRANS_IDX_u2_id_in]
    ON [dbo].[TRANS_AT_TRANS_IDX]([u2_id] ASC);

