CREATE TABLE [dbo].[TRANS_ERR] (
    [TRANS_ERR_ID] VARCHAR (255) NOT NULL,
    [u2_id]        VARCHAR (255) NULL,
    [ERR_FIELDS]   VARCHAR (12)  NULL,
    [ERR_MSG]      VARCHAR (176) NULL,
    [time_stamp]   DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([TRANS_ERR_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRANS_ERR_u2_id_in]
    ON [dbo].[TRANS_ERR]([u2_id] ASC);

