CREATE TABLE [dbo].[TRANS_CODE_AT_DEPR_METH] (
    [subValueId]       VARCHAR (255) NOT NULL,
    [TRANS_CODE_AT_ID] VARCHAR (255) NULL,
    [AT_DEPR_METHODS]  VARCHAR (14)  NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TRANS_COD_TRANS_COD_35503]
    ON [dbo].[TRANS_CODE_AT_DEPR_METH]([TRANS_CODE_AT_ID] ASC);

