CREATE TABLE [dbo].[UPR_OWNER_ATTACH] (
    [UPR_OWNER_ATTACH_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [ATTACHMENTS]         VARCHAR (30)  NULL,
    [ATTACHMENT_TYPES]    VARCHAR (6)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([UPR_OWNER_ATTACH_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UPR_OWNER_ATTACH_u2_id_in]
    ON [dbo].[UPR_OWNER_ATTACH]([u2_id] ASC);

