CREATE TABLE [dbo].[UPR_OWNER_XREF] (
    [UPR_OWNER_XREF_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [XREF_STRING]       VARCHAR (20)  NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([UPR_OWNER_XREF_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UPR_OWNER_XREF_u2_id_in]
    ON [dbo].[UPR_OWNER_XREF]([u2_id] ASC);

