CREATE TABLE [dbo].[UPR_RPT_OSIDX] (
    [UPR_RPT_OSIDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [OWNER_SALE_INDEX] VARCHAR (8)   NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([UPR_RPT_OSIDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UPR_RPT_OSIDX_u2_id_in]
    ON [dbo].[UPR_RPT_OSIDX]([u2_id] ASC);

