CREATE TABLE [dbo].[UPR_OWNER_SOURCE] (
    [UPR_OWNER_SOURCE_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [SOURCE_COMPANIES]    VARCHAR (9)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([UPR_OWNER_SOURCE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UPR_OWNER_SOURCE_u2_id_in]
    ON [dbo].[UPR_OWNER_SOURCE]([u2_id] ASC);

