CREATE TABLE [dbo].[UPR_SYS_AIP] (
    [UPR_SYS_AIP_ID]    VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [UPR2301_AIP]       VARCHAR (8)   NULL,
    [UPR2301_AIP_RERUN] VARCHAR (3)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([UPR_SYS_AIP_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UPR_SYS_AIP_u2_id_in]
    ON [dbo].[UPR_SYS_AIP]([u2_id] ASC);

