CREATE TABLE [dbo].[USER_RPT_FMT_OVRRIDE] (
    [USER_RPT_FMT_OVRRIDE_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [OVERRIDE_COLS]           VARCHAR (8)   NULL,
    [OVERRIDE_CONVS]          VARCHAR (8)   NULL,
    [OVERRIDE_DATE_FORMULAS]  DATETIME      NULL,
    [OVERRIDE_FORMULAS]       VARCHAR (36)  NULL,
    [OVERRIDE_ROWS]           VARCHAR (8)   NULL,
    [OVERRIDE_SUM_BUCKETS]    VARCHAR (8)   NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([USER_RPT_FMT_OVRRIDE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [USER_RPT_FMT_OVRRIDE_u2_id_in]
    ON [dbo].[USER_RPT_FMT_OVRRIDE]([u2_id] ASC);

