CREATE TABLE [dbo].[USER_RPT_FMT_COL] (
    [USER_RPT_FMT_COL_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [COL_ACT_BUD_FLAGS]   VARCHAR (6)   NULL,
    [COL_CONTROL_VALUES]  VARCHAR (6)   NULL,
    [COL_CONVS]           VARCHAR (10)  NULL,
    [COL_DATA_TYPES]      VARCHAR (4)   NULL,
    [COL_DATE_FORMULAS]   DATETIME      NULL,
    [COL_FMTS]            VARCHAR (7)   NULL,
    [COL_FORMULAS]        VARCHAR (62)  NULL,
    [COL_HEADINGS]        VARCHAR (80)  NULL,
    [COL_SUM_BUCKETS]     VARCHAR (6)   NULL,
    [COL_SUM_FLAGS]       VARCHAR (26)  NULL,
    [COL_SUPPRESS_ULS]    VARCHAR (9)   NULL,
    [NUMERIC_COL_FLAGS]   VARCHAR (7)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([USER_RPT_FMT_COL_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [USER_RPT_FMT_COL_u2_id_in]
    ON [dbo].[USER_RPT_FMT_COL]([u2_id] ASC);

