CREATE TABLE [dbo].[USER_RPT_FMT_CNTR] (
    [USER_RPT_FMT_CNTR_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [CENTER_HEADING]       VARCHAR (46)  NULL,
    [CENTER_HEADING_FMT]   VARCHAR (6)   NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([USER_RPT_FMT_CNTR_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [USER_RPT_FMT_CNTR_u2_id_in]
    ON [dbo].[USER_RPT_FMT_CNTR]([u2_id] ASC);

