CREATE TABLE [dbo].[USER_RPT_FMT_SEL] (
    [USER_RPT_FMT_SEL_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [SELECTION_CRITERIA]  VARCHAR (227) NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([USER_RPT_FMT_SEL_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [USER_RPT_FMT_SEL_u2_id_in]
    ON [dbo].[USER_RPT_FMT_SEL]([u2_id] ASC);

