CREATE TABLE [dbo].[USER_RPT_FMT_USER] (
    [USER_RPT_FMT_USER_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [USER_BUCKETS]         VARCHAR (7)   NULL,
    [USER_PARAMETERS_TEXT] VARCHAR (36)  NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([USER_RPT_FMT_USER_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [USER_RPT_FMT_USER_u2_id_in]
    ON [dbo].[USER_RPT_FMT_USER]([u2_id] ASC);

