CREATE TABLE [dbo].[USER_RPT_FMT_CNTR_CAPT] (
    [USER_RPT_FMT_CNTR_CAPT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                     VARCHAR (255) NULL,
    [CENTER_CAPTION]            VARCHAR (35)  NULL,
    [CENTER_CAPTION_FMT]        VARCHAR (7)   NULL,
    [time_stamp]                DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([USER_RPT_FMT_CNTR_CAPT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [USER_RPT__u2_id_19296]
    ON [dbo].[USER_RPT_FMT_CNTR_CAPT]([u2_id] ASC);

