CREATE TABLE [dbo].[USER_RPT_FMT_HDG] (
    [subValueId]          VARCHAR (255) NOT NULL,
    [USER_RPT_FMT_COL_ID] VARCHAR (255) NULL,
    [HEADING_LEVELS]      VARCHAR (11)  NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [USER_RPT__USER_RPT__12376]
    ON [dbo].[USER_RPT_FMT_HDG]([USER_RPT_FMT_COL_ID] ASC);

