CREATE TABLE [dbo].[USERS_COMPANIES] (
    [USERS_COMPANIES_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [VALID_COMPANIES]    VARCHAR (4)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([USERS_COMPANIES_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [USERS_COMPANIES_u2_id_in]
    ON [dbo].[USERS_COMPANIES]([u2_id] ASC);

