CREATE TABLE [dbo].[USERS_APPS] (
    [USERS_APPS_ID] VARCHAR (255) NOT NULL,
    [u2_id]         VARCHAR (255) NULL,
    [VALID_APPS]    VARCHAR (8)   NULL,
    [time_stamp]    DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([USERS_APPS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [USERS_APPS_u2_id_in]
    ON [dbo].[USERS_APPS]([u2_id] ASC);

