CREATE TABLE [dbo].[USER_RPT_FMT_RT] (
    [USER_RPT_FMT_RT_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [RIGHT_HEADING]      VARCHAR (24)  NULL,
    [RIGHT_HEADING_FMT]  VARCHAR (5)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([USER_RPT_FMT_RT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [USER_RPT_FMT_RT_u2_id_in]
    ON [dbo].[USER_RPT_FMT_RT]([u2_id] ASC);

