CREATE TABLE [dbo].[VENDOR_JUR] (
    [VENDOR_JUR_ID] VARCHAR (255) NOT NULL,
    [u2_id]         VARCHAR (255) NULL,
    [JURISDICTION]  VARCHAR (12)  NULL,
    [VAT_EXEMPT]    VARCHAR (6)   NULL,
    [time_stamp]    DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([VENDOR_JUR_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [VENDOR_JUR_u2_id_in]
    ON [dbo].[VENDOR_JUR]([u2_id] ASC);

