CREATE TABLE [dbo].[VENDOR_CO] (
    [VENDOR_CO_ID]    VARCHAR (255) NOT NULL,
    [u2_id]           VARCHAR (255) NULL,
    [DFLT_TERMS]      VARCHAR (4)   NULL,
    [PAY_DISPOSITION] VARCHAR (4)   NULL,
    [SEP_CHK]         VARCHAR (6)   NULL,
    [SH_CODES]        VARCHAR (5)   NULL,
    [VALID_COMPANIES] VARCHAR (3)   NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([VENDOR_CO_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [VENDOR_CO_u2_id_in]
    ON [dbo].[VENDOR_CO]([u2_id] ASC);

