CREATE TABLE [dbo].[VENDOR_RMK] (
    [VENDOR_RMK_ID] VARCHAR (255) NOT NULL,
    [u2_id]         VARCHAR (255) NULL,
    [REMARKS]       VARCHAR (91)  NULL,
    [REMARK_DATES]  DATETIME      NULL,
    [time_stamp]    DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([VENDOR_RMK_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [VENDOR_RMK_u2_id_in]
    ON [dbo].[VENDOR_RMK]([u2_id] ASC);

