CREATE TABLE [dbo].[VOU_SRC_PROF_RSVE] (
    [VOU_SRC_PROF_RSVE_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [JE_TYPES]             VARCHAR (7)   NULL,
    [RESERVED_VOUCHER_NOS] VARCHAR (8)   NULL,
    [REVERSE_FLAGS]        VARCHAR (7)   NULL,
    [VOUCHER_DESCS]        VARCHAR (25)  NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([VOU_SRC_PROF_RSVE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [VOU_SRC_PROF_RSVE_u2_id_in]
    ON [dbo].[VOU_SRC_PROF_RSVE]([u2_id] ASC);

