CREATE TABLE [dbo].[VOUCHER_RELATED_VOUCHERS] (
    [VOUCHER_RELATED_VOUCHERS_ID] VARCHAR (255) NOT NULL,
    [u2_id]                       VARCHAR (255) NULL,
    [RELATED_VOUCHERS]            VARCHAR (15)  NULL,
    [time_stamp]                  DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([VOUCHER_RELATED_VOUCHERS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [VOUCHER_R_u2_id_67092]
    ON [dbo].[VOUCHER_RELATED_VOUCHERS]([u2_id] ASC);

