CREATE TABLE [dbo].[VOUCHER_TRANS_INDEX] (
    [subValueId]             VARCHAR (255) NOT NULL,
    [VOUCHER_DOC_ID]         VARCHAR (255) NULL,
    [INCOMPLETE_TRANS_FLAGS] VARCHAR (10)  NULL,
    [TRANS_INDEX]            VARCHAR (10)  NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [VOUCHER_T_VOUCHER_D_44207]
    ON [dbo].[VOUCHER_TRANS_INDEX]([VOUCHER_DOC_ID] ASC);

