CREATE TABLE [dbo].[VOUCHER_LAST_SUBMIT] (
    [VOUCHER_LAST_SUBMIT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [LAST_SUBMIT_BY]         VARCHAR (9)   NULL,
    [LAST_SUBMIT_DATE]       DATETIME      NULL,
    [LAST_SUBMIT_TIME]       VARCHAR (10)  NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([VOUCHER_LAST_SUBMIT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [VOUCHER_LAST_SUBMIT_u2_id_in]
    ON [dbo].[VOUCHER_LAST_SUBMIT]([u2_id] ASC);

