CREATE TABLE [dbo].[WELL_INFO_GAS_ANALYSIS] (
    [WELL_INFO_GAS_ANALYSIS_ID] VARCHAR (255) NOT NULL,
    [u2_id]                     VARCHAR (255) NULL,
    [GAS_ANALYSIS_EFF_DATES]    DATETIME      NULL,
    [GAS_ANALYSIS_INDEX]        VARCHAR (8)   NULL,
    [time_stamp]                DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([WELL_INFO_GAS_ANALYSIS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [WELL_INFO_u2_id_44910]
    ON [dbo].[WELL_INFO_GAS_ANALYSIS]([u2_id] ASC);

