CREATE TABLE [dbo].[WELL_INFO_TRACT_INDEX] (
    [WELL_INFO_TRACT_INDEX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                    VARCHAR (255) NULL,
    [TRACT_IDX]                VARCHAR (15)  NULL,
    [time_stamp]               DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([WELL_INFO_TRACT_INDEX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [WELL_INFO_TRACT_INDEX_u2_id_in]
    ON [dbo].[WELL_INFO_TRACT_INDEX]([u2_id] ASC);

