CREATE TABLE [dbo].[WELL_INFO_WELL_CNT_EFF] (
    [WELL_INFO_WELL_CNT_EFF_ID] VARCHAR (255) NOT NULL,
    [u2_id]                     VARCHAR (255) NULL,
    [WELL_COUNT_EFF_DATES]      DATETIME      NULL,
    [time_stamp]                DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([WELL_INFO_WELL_CNT_EFF_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [WELL_INFO_u2_id_27302]
    ON [dbo].[WELL_INFO_WELL_CNT_EFF]([u2_id] ASC);

