CREATE TABLE [dbo].[WELL_INFO_UDF] (
    [WELL_INFO_UDF_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [USER_DATA_FIELDS] VARCHAR (9)   NULL,
    [USER_DATA_VALUES] VARCHAR (9)   NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([WELL_INFO_UDF_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [WELL_INFO_UDF_u2_id_in]
    ON [dbo].[WELL_INFO_UDF]([u2_id] ASC);

