CREATE TABLE [dbo].[WELL_INFO_WELL_TEST] (
    [WELL_INFO_WELL_TEST_ID] VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [WELL_TEST_EFF_DATES]    DATETIME      NULL,
    [WELL_TEST_INDEX]        VARCHAR (15)  NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([WELL_INFO_WELL_TEST_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [WELL_INFO_WELL_TEST_u2_id_in]
    ON [dbo].[WELL_INFO_WELL_TEST]([u2_id] ASC);

