CREATE TABLE [dbo].[WELL_INFO_ADDL_CTYS] (
    [WELL_INFO_ADDL_CTYS_ID] VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [ADDL_CTY]               VARCHAR (7)   NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([WELL_INFO_ADDL_CTYS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [WELL_INFO_ADDL_CTYS_u2_id_in]
    ON [dbo].[WELL_INFO_ADDL_CTYS]([u2_id] ASC);

