CREATE TABLE [dbo].[WELL_TEST] (
    [u2_id]                        VARCHAR (255)   NOT NULL,
    [ALLOCATABLE]                  VARCHAR (6)     NULL,
    [CC_NO]                        VARCHAR (15)    NULL,
    [CHOKE_SIZE]                   VARCHAR (5)     NULL,
    [COST_CENTER]                  VARCHAR (11)    NULL,
    [DURATION]                     NUMERIC (19, 2) NULL,
    [FLOWING_BOTTOM_HOLE_PRESSURE] VARCHAR (8)     NULL,
    [FLOWING_BOTTOM_HOLE_TEMP]     VARCHAR (7)     NULL,
    [FLOWING_CASING_PRESSURE]      VARCHAR (8)     NULL,
    [FLOWING_TUBING_PRESSURE]      VARCHAR (8)     NULL,
    [GAS_LIFT]                     NUMERIC (19, 2) NULL,
    [GAS_LIFT_24]                  NUMERIC (19, 2) NULL,
    [GAS_SALES]                    NUMERIC (19, 2) NULL,
    [GAS_VOL]                      NUMERIC (19, 2) NULL,
    [GAS_VOL_24]                   NUMERIC (19, 2) NULL,
    [GRAVITY]                      NUMERIC (9, 1)  NULL,
    [GROSS_GAS_PRODUCED]           NUMERIC (19, 2) NULL,
    [GRS_GAS_24]                   NUMERIC (19, 2) NULL,
    [GRS_NET_GAS]                  VARCHAR (11)    NULL,
    [INJECTED_GAS]                 NUMERIC (19, 2) NULL,
    [INJECTED_GAS_24]              NUMERIC (19, 2) NULL,
    [INJECTED_WATER]               NUMERIC (19, 2) NULL,
    [INJECTED_WATER_24]            NUMERIC (19, 2) NULL,
    [INJECTION_PRESSURE]           VARCHAR (9)     NULL,
    [INJ_GAS_24]                   NUMERIC (19, 2) NULL,
    [OIL_VOL]                      NUMERIC (19, 2) NULL,
    [OIL_VOL_24]                   NUMERIC (19, 2) NULL,
    [REMARKS]                      VARCHAR (39)    NULL,
    [RIO_FLAG]                     VARCHAR (4)     NULL,
    [RIO_RESERVE]                  VARCHAR (7)     NULL,
    [SALES_LINE_PRESSURE]          VARCHAR (8)     NULL,
    [SALES_LINE_TEMP]              VARCHAR (5)     NULL,
    [SEPARATOR_PRESSURE]           VARCHAR (9)     NULL,
    [SHUT_IN_BOTTOM_HOLE_PRESSURE] VARCHAR (8)     NULL,
    [SHUT_IN_BOTTOM_HOLE_TEMP]     VARCHAR (7)     NULL,
    [SHUT_IN_CASING_PRESSURE]      VARCHAR (8)     NULL,
    [SHUT_IN_TUBING_PRESSURE]      VARCHAR (8)     NULL,
    [SURFACE_TEMP]                 VARCHAR (7)     NULL,
    [TEST_DATE]                    DATETIME        NULL,
    [WATER_VOL]                    NUMERIC (19, 2) NULL,
    [WATER_VOL_24]                 NUMERIC (19, 2) NULL,
    [WELL_NAME]                    VARCHAR (25)    NULL,
    [time_stamp]                   DATETIME        NULL,
    [u2_checksum]                  VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

