CREATE TABLE [dbo].[WELL_INFO_DEPTH] (
    [WELL_INFO_DEPTH_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [FROM_DEPTHS]        NUMERIC (9)   NULL,
    [FROM_FORMATIONS]    VARCHAR (9)   NULL,
    [FROM_REFERENCES]    VARCHAR (7)   NULL,
    [TO_DEPTHS]          NUMERIC (9)   NULL,
    [TO_FORMATIONS]      VARCHAR (9)   NULL,
    [TO_REFERENCES]      VARCHAR (6)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([WELL_INFO_DEPTH_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [WELL_INFO_DEPTH_u2_id_in]
    ON [dbo].[WELL_INFO_DEPTH]([u2_id] ASC);

