CREATE TABLE [dbo].[WELL_COUNT_DOC] (
    [WELL_COUNT_DOC_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [COUNTS]            VARCHAR (6)   NULL,
    [WELL_STATUS]       VARCHAR (10)  NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([WELL_COUNT_DOC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [WELL_COUNT_DOC_u2_id_in]
    ON [dbo].[WELL_COUNT_DOC]([u2_id] ASC);

