CREATE TABLE [dbo].[WELL_PROD] (
    [u2_id]             VARCHAR (255)   NOT NULL,
    [APP]               VARCHAR (8)     NULL,
    [BTU_BASIS]         VARCHAR (5)     NULL,
    [BTU_FACTOR]        NUMERIC (19, 6) NULL,
    [CC_SALE_DATE]      VARCHAR (12)    NULL,
    [CORRECTED_GRAVITY] NUMERIC (9, 1)  NULL,
    [COST_CENTER]       VARCHAR (8)     NULL,
    [DISP]              VARCHAR (4)     NULL,
    [GATHERING_SYSTEM]  VARCHAR (15)    NULL,
    [GL_DATE]           VARCHAR (8)     NULL,
    [GL_POST_KEY]       VARCHAR (7)     NULL,
    [MEAS_PT]           VARCHAR (12)    NULL,
    [PRESSURE_BASE]     NUMERIC (19, 3) NULL,
    [PRODUCT]           VARCHAR (7)     NULL,
    [PURCHASER]         VARCHAR (12)    NULL,
    [SALE_DATE]         DATETIME        NULL,
    [TEMP_WELL]         VARCHAR (4)     NULL,
    [TOW_DISP]          VARCHAR (12)    NULL,
    [TRANSPORTER]       VARCHAR (11)    NULL,
    [UNIT_OF_MEASURE]   VARCHAR (7)     NULL,
    [VOLUME]            NUMERIC (19, 3) NULL,
    [WELLHEAD_VOLUME]   NUMERIC (19, 3) NULL,
    [WI_COMPANY]        VARCHAR (8)     NULL,
    [WI_STATE]          VARCHAR (2)     NULL,
    [time_stamp]        DATETIME        NULL,
    [u2_checksum]       VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

