CREATE TABLE [dbo].[XCG_EXPORT_TEMPLATE_QUERY] (
    [XCG_EXPORT_TEMPLATE_QUERY_ID] VARCHAR (255) NOT NULL,
    [u2_id]                        VARCHAR (255) NULL,
    [QUERY_STATEMENTS]             VARCHAR (342) NULL,
    [time_stamp]                   DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([XCG_EXPORT_TEMPLATE_QUERY_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [XCG_EXPOR_u2_id_36041]
    ON [dbo].[XCG_EXPORT_TEMPLATE_QUERY]([u2_id] ASC);

