CREATE TABLE [dbo].[XCG_EXPORT_TEMPLATE_PARAMS] (
    [XCG_EXPORT_TEMPLATE_PARAMS_ID] VARCHAR (255) NOT NULL,
    [u2_id]                         VARCHAR (255) NULL,
    [PARAMETERS_TEXT]               VARCHAR (23)  NULL,
    [PARAMETER_BUCKETS]             VARCHAR (6)   NULL,
    [time_stamp]                    DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([XCG_EXPORT_TEMPLATE_PARAMS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [XCG_EXPOR_u2_id_68725]
    ON [dbo].[XCG_EXPORT_TEMPLATE_PARAMS]([u2_id] ASC);

