CREATE TABLE [dbo].[RegisterDocument] (
    [DocumentId]                 VARCHAR (200) NULL,
    [AsBuiltRequired]            CHAR (5)      NULL,
    [Attribute1]                 VARCHAR (200) NULL,
    [Attribute2]                 VARCHAR (200) NULL,
    [Attribute3]                 VARCHAR (200) NULL,
    [Attribute4]                 VARCHAR (200) NULL,
    [Author]                     VARCHAR (50)  NULL,
    [AuthorisedBy]               VARCHAR (50)  NULL,
    [Category]                   VARCHAR (50)  NULL,
    [Check1]                     CHAR (5)      NULL,
    [Check2]                     CHAR (5)      NULL,
    [Comments]                   VARCHAR (50)  NULL,
    [Comments2]                  VARCHAR (50)  NULL,
    [Confidential]               CHAR (5)      NULL,
    [ConfidentialUserAccessList] VARCHAR (200) NULL,
    [UserId]                     VARCHAR (200) NULL,
    [ContractDeliverable]        CHAR (5)      NULL,
    [ContractNumber]             VARCHAR (50)  NULL,
    [ContractorDocumentNumber]   VARCHAR (50)  NULL,
    [ContractorRevision]         VARCHAR (50)  NULL,
    [Date1]                      DATETIME      NULL,
    [Date2]                      DATETIME      NULL,
    [DateCreated]                DATETIME      NULL,
    [DateForReview]              DATETIME      NULL,
    [DateModified]               DATETIME      NULL,
    [DateReviewed]               DATETIME      NULL,
    [Discipline]                 VARCHAR (50)  NULL,
    [DocumentNumber]             VARCHAR (210) NULL,
    [DocumentStatus]             VARCHAR (50)  NULL,
    [DocumentType]               VARCHAR (50)  NULL,
    [FileSize]                   INT           NULL,
    [Filename]                   VARCHAR (50)  NULL,
    [PackageNumber]              VARCHAR (50)  NULL,
    [PercentComplete]            INT           NULL,
    [PrintSize]                  VARCHAR (50)  NULL,
    [ProjectField1]              VARCHAR (50)  NULL,
    [ProjectField2]              VARCHAR (50)  NULL,
    [ProjectField3]              VARCHAR (50)  NULL,
    [Received]                   DATETIME      NULL,
    [Reference]                  VARCHAR (50)  NULL,
    [Registered]                 DATETIME      NULL,
    [Reviewed]                   DATETIME      NULL,
    [ReviewSource]               VARCHAR (50)  NULL,
    [ReviewStatus]               VARCHAR (50)  NULL,
    [Revision]                   VARCHAR (50)  NULL,
    [RevisionDate]               DATETIME      NULL,
    [Scale]                      VARCHAR (50)  NULL,
    [SelectList1]                VARCHAR (60)  NULL,
    [SelectList2]                VARCHAR (60)  NULL,
    [SelectList3]                VARCHAR (60)  NULL,
    [SelectList4]                VARCHAR (60)  NULL,
    [SelectList5]                VARCHAR (60)  NULL,
    [SelectList6]                VARCHAR (60)  NULL,
    [SelectList7]                VARCHAR (60)  NULL,
    [SelectList8]                VARCHAR (60)  NULL,
    [SelectList9]                VARCHAR (60)  NULL,
    [SelectList10]               VARCHAR (60)  NULL,
    [TagNumber]                  VARCHAR (50)  NULL,
    [Title]                      VARCHAR (50)  NULL,
    [ToClientDate]               DATETIME      NULL,
    [Vdrcode]                    VARCHAR (50)  NULL,
    [VendorDocumentNumber]       VARCHAR (50)  NULL,
    [VendorRevision]             VARCHAR (50)  NULL,
    [DateRecordCreated]          DATETIME      DEFAULT (getdate()) NULL,
    [DateRecordUpdated]          DATETIME      DEFAULT (getdate()) NULL,
    [ProjectShortName]           VARCHAR (200) NULL,
    [ProjectID]                  INT           NULL
);

