CREATE TABLE [dbo].[WellHeader_test] (
    [Id]                                    VARCHAR (4000) NULL,
    [API Number]                            VARCHAR (4000) NULL,
    [Well Name]                             VARCHAR (4000) NULL,
    [Texas District]                        VARCHAR (4000) NULL,
    [Lease Name]                            VARCHAR (4000) NULL,
    [Lease Number]                          VARCHAR (4000) NULL,
    [Number of Wells in Lease]              VARCHAR (4000) NULL,
    [Formation]                             VARCHAR (4000) NULL,
    [Field]                                 VARCHAR (4000) NULL,
    [Well Direction]                        VARCHAR (4000) NULL,
    [Well Type]                             VARCHAR (4000) NULL,
    [Spud Date]                             VARCHAR (4000) NULL,
    [Completion Date]                       VARCHAR (4000) NULL,
    [Initial Test Date]                     VARCHAR (4000) NULL,
    [Production Start Date]                 VARCHAR (4000) NULL,
    [Peak Production Date]                  VARCHAR (4000) NULL,
    [Permit Issue Date]                     VARCHAR (4000) NULL,
    [Last Production Date]                  VARCHAR (4000) NULL,
    [Refracturing Date]                     VARCHAR (4000) NULL,
    [Well Status]                           VARCHAR (4000) NULL,
    [Last Update Date]                      VARCHAR (4000) NULL,
    [Frac Focus Version]                    VARCHAR (4000) NULL,
    [Pad ID]                                VARCHAR (4000) NULL,
    [Reported Production Months]            VARCHAR (4000) NULL,
    [Reported Well Type]                    VARCHAR (4000) NULL,
    [First Record Date]                     VARCHAR (4000) NULL,
    [Number of Casing Strings Group]        VARCHAR (4000) NULL,
    [Number of Casing Strings Category]     VARCHAR (4000) NULL,
    [Pad State]                             VARCHAR (4000) NULL,
    [Parent Child Classification]           VARCHAR (4000) NULL,
    [Pad Sequence Completion]               VARCHAR (4000) NULL,
    [Pad Segment Completion]                VARCHAR (4000) NULL,
    [Pad Sequence Spud]                     VARCHAR (4000) NULL,
    [Pad Segment Spud]                      VARCHAR (4000) NULL,
    [Land Type]                             VARCHAR (4000) NULL,
    [Choke Size]                            VARCHAR (4000) NULL,
    [Well Spacing]                          VARCHAR (4000) NULL,
    [Longitude]                             VARCHAR (4000) NULL,
    [Latitude]                              VARCHAR (4000) NULL,
    [Reported 24-h Test Water Production]   VARCHAR (4000) NULL,
    [Reported 24-h Test Production]         VARCHAR (4000) NULL,
    [Maximum Treatment Pressure]            VARCHAR (4000) NULL,
    [Maximum Treatment Rate]                VARCHAR (4000) NULL,
    [Proppant (Thousand pounds)]            VARCHAR (4000) NULL,
    [Ground Level]                          VARCHAR (4000) NULL,
    [Total Measured Depth]                  VARCHAR (4000) NULL,
    [True Vertical Depth]                   VARCHAR (4000) NULL,
    [Lateral Length]                        VARCHAR (4000) NULL,
    [Drilling Days]                         VARCHAR (4000) NULL,
    [Frac Stages (Count)]                   VARCHAR (4000) NULL,
    [BottomHole Longitude]                  VARCHAR (4000) NULL,
    [BottomHole Latitude]                   VARCHAR (4000) NULL,
    [Surface Lateral Projection]            VARCHAR (4000) NULL,
    [Upper Perforation]                     VARCHAR (4000) NULL,
    [Lower Perforation]                     VARCHAR (4000) NULL,
    [Perforated Length]                     VARCHAR (4000) NULL,
    [Distance Closest Well 2D (Feet)]       VARCHAR (4000) NULL,
    [Distance Closest Well 3D (Feet)]       VARCHAR (4000) NULL,
    [FK_NASGeography]                       VARCHAR (4000) NULL,
    [FK_NASOperator]                        VARCHAR (4000) NULL,
    [RE ID]                                 VARCHAR (4000) NULL,
    [Asset]                                 VARCHAR (4000) NULL,
    [FK_NASDataQuality]                     VARCHAR (4000) NULL,
    [Light Oil Content Group]               VARCHAR (4000) NULL,
    [Light Oil Content Category]            VARCHAR (4000) NULL,
    [Light Oil Content Detail]              VARCHAR (4000) NULL,
    [Initial Production Group]              VARCHAR (4000) NULL,
    [Initial Production Category]           VARCHAR (4000) NULL,
    [Initial Production Detail]             VARCHAR (4000) NULL,
    [FK_NASREAnalysis]                      VARCHAR (4000) NULL,
    [Spud Date Reporting Group]             VARCHAR (4000) NULL,
    [Completion Date Reporting Group]       VARCHAR (4000) NULL,
    [Production Start Date Reporting Group] VARCHAR (4000) NULL,
    [TVD Group]                             VARCHAR (4000) NULL,
    [TVD Category]                          VARCHAR (4000) NULL,
    [TVD Detail]                            VARCHAR (4000) NULL,
    [Well Origin]                           VARCHAR (4000) NULL,
    [TMD Group]                             VARCHAR (4000) NULL,
    [TMD Category]                          VARCHAR (4000) NULL,
    [TMD Detail]                            VARCHAR (4000) NULL,
    [Lateral Length Group]                  VARCHAR (4000) NULL,
    [Lateral Length Category]               VARCHAR (4000) NULL,
    [Lateral Length Detail]                 VARCHAR (4000) NULL,
    [Service Provider]                      VARCHAR (4000) NULL,
    [Service Provider Confidence]           VARCHAR (4000) NULL,
    [Initial Light Oil Content Group]       VARCHAR (4000) NULL,
    [Initial Light Oil Content Category]    VARCHAR (4000) NULL,
    [Initial Light Oil Content Detail]      VARCHAR (4000) NULL,
    [FK_NASBreakevenOilPrice]               VARCHAR (4000) NULL,
    [FK_NASBreakevenGasPrice]               VARCHAR (4000) NULL,
    [API Group]                             VARCHAR (4000) NULL,
    [API Category]                          VARCHAR (4000) NULL,
    [API Detail]                            VARCHAR (4000) NULL,
    [Gas Gatherer]                          VARCHAR (4000) NULL,
    [Liquids Gatherer]                      VARCHAR (4000) NULL,
    [Proppant Type Group]                   VARCHAR (4000) NULL,
    [Proppant Type Category]                VARCHAR (4000) NULL,
    [Proppant Type Detail]                  VARCHAR (4000) NULL,
    [Life Cycle Group]                      VARCHAR (4000) NULL,
    [Life Cycle Category]                   VARCHAR (4000) NULL,
    [Life Cycle Detail]                     VARCHAR (4000) NULL,
    [Acreage Grade Group]                   VARCHAR (4000) NULL,
    [Acreage Grade Category]                VARCHAR (4000) NULL,
    [Acreage Grade Detail]                  VARCHAR (4000) NULL,
    [Frac Job Type Group]                   VARCHAR (4000) NULL,
    [Frac Job Type Category]                VARCHAR (4000) NULL,
    [Frac Job Type Detail]                  VARCHAR (4000) NULL,
    [Proppant Intensity Group]              VARCHAR (4000) NULL,
    [Proppant Intensity Category]           VARCHAR (4000) NULL,
    [Proppant Intensity Detail]             VARCHAR (4000) NULL,
    [Fluid Intensity Group]                 VARCHAR (4000) NULL,
    [Fluid Intensity Category]              VARCHAR (4000) NULL,
    [Fluid Intensity Detail]                VARCHAR (4000) NULL,
    [FK_NASLocation]                        VARCHAR (4000) NULL,
    [Distance 3D Group]                     VARCHAR (4000) NULL,
    [Distance 3D Category]                  VARCHAR (4000) NULL,
    [Distance 3D Detail]                    VARCHAR (4000) NULL
);

