CREATE TABLE [dbo].[rawDominionOperationalCapacity_old] (
    [Posting Date]                       VARCHAR (50) NULL,
    [Posting Time]                       VARCHAR (50) NULL,
    [TSP]                                VARCHAR (50) NULL,
    [TSP Name]                           VARCHAR (50) NULL,
    [CycleDesc]                          VARCHAR (50) NULL,
    [Eff Gas Day]                        VARCHAR (50) NULL,
    [Eff Time]                           VARCHAR (50) NULL,
    [Meas Basis Desc]                    VARCHAR (50) NULL,
    [Loc Purp Desc]                      VARCHAR (50) NULL,
    [Loc QTI Desc]                       VARCHAR (50) NULL,
    [Interconnect Party Name]            VARCHAR (50) NULL,
    [OIA]                                VARCHAR (50) NULL,
    [Loc]                                VARCHAR (50) NULL,
    [Loc Name]                           VARCHAR (50) NULL,
    [Operating Capacity]                 VARCHAR (50) NULL,
    [Total Scheduled Qty]                VARCHAR (50) NULL,
    [Operationally Available Capacity]   VARCHAR (50) NULL,
    [Design Capacity]                    VARCHAR (50) NULL,
    [All Quantities Available Indicator] VARCHAR (50) NULL,
    [Quantity Not Available Reason]      VARCHAR (50) NULL,
    [Flow Ind]                           VARCHAR (50) NULL,
    [IT]                                 VARCHAR (50) NULL,
    [Column 22]                          VARCHAR (50) NULL
);

