/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'TLN\svc-powerbi')
CREATE LOGIN [TLN\svc-powerbi] FROM WINDOWS
GO
CREATE USER [TLN\svc-powerbi] FOR LOGIN [TLN\svc-powerbi]
GO
