CREATE TABLE [StageBOLO].[LEASE_PMT] (
    [u2_id]                 VARCHAR (255)   NULL,
    [ACCT]                  VARCHAR (12)    NULL,
    [ACCTG_PERIOD]          DATETIME        NULL,
    [AMT]                   NUMERIC (19, 2) NULL,
    [BAL]                   NUMERIC (19, 2) NULL,
    [BANK_ACCT]             VARCHAR (4)     NULL,
    [BANK_FEE]              NUMERIC (19, 2) NULL,
    [COMPANY]               VARCHAR (4)     NULL,
    [COST_CENTER]           VARCHAR (12)    NULL,
    [DUE_DATE]              DATETIME        NULL,
    [LEASE_ID]              VARCHAR (12)    NULL,
    [OCCUR_DATE]            DATETIME        NULL,
    [PAID_IN_FULL_PERIOD]   DATETIME        NULL,
    [PAYEE]                 VARCHAR (9)     NULL,
    [PAYEE_AMT]             NUMERIC (19, 2) NULL,
    [PAY_FLAG]              VARCHAR (4)     NULL,
    [PMT_DUE_DATE]          DATETIME        NULL,
    [PMT_PERIOD]            DATETIME        NULL,
    [PMT_TYPE]              VARCHAR (9)     NULL,
    [REVERSAL_ACCTG_PERIOD] DATETIME        NULL,
    [REVERSAL_VOUCHER]      VARCHAR (15)    NULL,
    [SOURCE_CURRENCY]       VARCHAR (4)     NULL,
    [SYSTEM_DATE]           DATETIME        NULL,
    [SYSTEM_TIME]           VARCHAR (8)     NULL,
    [SYSTEM_USER_ID]        VARCHAR (8)     NULL,
    [VOUCHER]               VARCHAR (14)    NULL,
    [time_stamp]            DATETIME        NULL,
    [u2_checksum]           VARCHAR (25)    NULL
);

