CREATE TABLE [StageBOLO].[OG_SALE] (
    [u2_id]              VARCHAR (255)   NULL,
    [AGENCY_NET]         NUMERIC (19, 2) NULL,
    [AGENCY_SALE]        NUMERIC (19, 2) NULL,
    [AGENCY_SALE_VOL1]   NUMERIC (19, 2) NULL,
    [AGENCY_SALE_VOL2]   NUMERIC (19, 2) NULL,
    [ALLOC_STATUS]       VARCHAR (6)     NULL,
    [APP]                VARCHAR (8)     NULL,
    [AR_INV_DET_ID]      VARCHAR (13)    NULL,
    [BONUS_PRICE_ADJ]    NUMERIC (19, 5) NULL,
    [BTU_FACTOR]         NUMERIC (9)     NULL,
    [CALC_AGENCY_NET]    NUMERIC (19, 2) NULL,
    [CALC_CASH_AMT_RECD] NUMERIC (19, 2) NULL,
    [CALC_GROSS_NET]     NUMERIC (19, 2) NULL,
    [CASH_ACCTG_PERIOD]  DATETIME        NULL,
    [CASH_AMT_RECD]      NUMERIC (19, 2) NULL,
    [CLRG_AMT]           NUMERIC (19, 2) NULL,
    [CNV_ID]             VARCHAR (6)     NULL,
    [COMPANY]            VARCHAR (4)     NULL,
    [CONTRACT]           VARCHAR (8)     NULL,
    [CONTRA_SALE_ID]     VARCHAR (7)     NULL,
    [COST_CENTER]        VARCHAR (9)     NULL,
    [DIV_ID]             VARCHAR (14)    NULL,
    [DIV_SESSION]        VARCHAR (15)    NULL,
    [DOC_TYPE]           VARCHAR (7)     NULL,
    [ERR_STATUS]         VARCHAR (5)     NULL,
    [GRAVITY]            NUMERIC (19, 2) NULL,
    [GROSS_NET]          NUMERIC (19, 2) NULL,
    [GROSS_SALE]         NUMERIC (19, 2) NULL,
    [GROSS_SALE_VOL1]    NUMERIC (19, 2) NULL,
    [GROSS_SALE_VOL2]    NUMERIC (19, 2) NULL,
    [MEAS_PT]            VARCHAR (12)    NULL,
    [MKT_VOL_ID]         VARCHAR (20)    NULL,
    [OG_BAL_ID]          VARCHAR (6)     NULL,
    [ORIG_DIV_SESS]      VARCHAR (8)     NULL,
    [PRESSURE_BASE]      NUMERIC (19, 3) NULL,
    [PRICE_REF]          VARCHAR (6)     NULL,
    [PRODUCT]            VARCHAR (3)     NULL,
    [PROPERTY]           VARCHAR (16)    NULL,
    [PURCHASER]          VARCHAR (9)     NULL,
    [REMITTER]           VARCHAR (9)     NULL,
    [REVERSAL_FLAG]      VARCHAR (3)     NULL,
    [SALE_ACCTG_PERIOD]  DATETIME        NULL,
    [SALE_DATE]          DATETIME        NULL,
    [SALE_TYPE]          VARCHAR (4)     NULL,
    [SOURCE_DOCUMENT]    VARCHAR (74)    NULL,
    [SRC_OG_SALE_ID]     VARCHAR (7)     NULL,
    [STATUS]             VARCHAR (4)     NULL,
    [SYSTEM_DATE]        DATETIME        NULL,
    [SYSTEM_TIME]        VARCHAR (8)     NULL,
    [SYSTEM_USER_ID]     VARCHAR (6)     NULL,
    [TKTGRAVITY]         NUMERIC (19, 2) NULL,
    [VOUCHER]            VARCHAR (16)    NULL,
    [time_stamp]         DATETIME        NULL,
    [u2_checksum]        VARCHAR (25)    NULL
);

