CREATE TABLE [StageBOLO].[WELL_INFO] (
    [u2_id]                 VARCHAR (255)   NOT NULL,
    [API_WELL_NO]           VARCHAR (18)    NULL,
    [AREA]                  VARCHAR (6)     NULL,
    [BASIN]                 VARCHAR (9)     NULL,
    [CC_TYPE]               VARCHAR (5)     NULL,
    [COMPANY]               VARCHAR (3)     NULL,
    [COMPLETION_DATE]       DATETIME        NULL,
    [COUNTY]                VARCHAR (6)     NULL,
    [DATE_OF_FIRST_SALE]    DATETIME        NULL,
    [DESCRIPTION]           VARCHAR (3904)  NULL,
    [DISTRICT]              VARCHAR (7)     NULL,
    [FIELD_ID]              VARCHAR (6)     NULL,
    [FIRST_GAS_PROD_DATE]   DATETIME        NULL,
    [FIRST_OIL_PROD_DATE]   DATETIME        NULL,
    [FIRST_WATER_PROD_DATE] DATETIME        NULL,
    [GAS_PROFILE]           VARCHAR (6)     NULL,
    [INPUT_DATE]            DATETIME        NULL,
    [INPUT_USER]            VARCHAR (5)     NULL,
    [IN_SERVICE_PERIOD]     DATETIME        NULL,
    [JIB_PROPERTY]          VARCHAR (8)     NULL,
    [JOA]                   VARCHAR (185)   NULL,
    [LAST_STATUS]           VARCHAR (5)     NULL,
    [LEGAL_DESC_ID]         VARCHAR (7)     NULL,
    [MASTER_RPTG_DECK]      VARCHAR (6)     NULL,
    [MERIDIAN]              VARCHAR (9)     NULL,
    [MMS_SALE_MONTH_LAGX]   VARCHAR (3)     NULL,
    [NAME]                  VARCHAR (89)    NULL,
    [NRI_RPTG_DOI]          VARCHAR (4)     NULL,
    [OCS_NO]                VARCHAR (6)     NULL,
    [OFFICE]                VARCHAR (6)     NULL,
    [OPERATOR]              VARCHAR (9)     NULL,
    [OTHER_LEGAL_DESC]      VARCHAR (3904)  NULL,
    [POOL]                  VARCHAR (5)     NULL,
    [PRICE_METHOD]          VARCHAR (8)     NULL,
    [PROD_FAC_ID]           VARCHAR (8)     NULL,
    [PROSPECT]              VARCHAR (6)     NULL,
    [PUMPER]                VARCHAR (9)     NULL,
    [ROLLUP_PROP]           VARCHAR (8)     NULL,
    [RRC_DISTRICT]          VARCHAR (4)     NULL,
    [SHADOW_KEY]            VARCHAR (14)    NULL,
    [SPACING_ACRES]         NUMERIC (19, 4) NULL,
    [SPUD_DATE]             DATETIME        NULL,
    [STATE]                 VARCHAR (2)     NULL,
    [STATE_LEASE_NO]        VARCHAR (10)    NULL,
    [SUPERVISOR]            VARCHAR (9)     NULL,
    [SURVEY_METHOD]         VARCHAR (6)     NULL,
    [TERMINATION_DATE]      DATETIME        NULL,
    [TERMINATION_REMARKS]   VARCHAR (221)   NULL,
    [TERMINATION_TYPE]      VARCHAR (4)     NULL,
    [TOTAL_DEPTH]           NUMERIC (9)     NULL,
    [UNIT_RPTG_DECK]        VARCHAR (9)     NULL,
    [USER_CODE1]            VARCHAR (30)    NULL,
    [WI_RPTG_DECK]          VARCHAR (5)     NULL,
    [time_stamp]            DATETIME        NULL,
    [u2_checksum]           VARCHAR (25)    NULL
);

