/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[ZediData]
(
[location_id] [int] NULL,
[location] [nvarchar] (100) NULL,
[readingtime] [datetime] NOT NULL,
[sensor] [nvarchar] (100) NULL,
[sensor_id] [int] NOT NULL,
[unit] [nvarchar] (25) NULL,
[amount] [float] NULL,
[amountstring] [nvarchar] (max) NULL,
[amountdatetimeutc] [datetime] NULL
)
GO
ALTER TABLE [dbo].[ZediData] ADD CONSTRAINT [PK__ZediData__7898FF2825A0D962] PRIMARY KEY CLUSTERED ([readingtime], [sensor_id])
GO
CREATE NONCLUSTERED INDEX [ndx_location_sensor_incl_all] ON [dbo].[ZediData] ([location_id], [sensor]) INCLUDE ([location], [readingtime], [sensor_id], [unit], [amount], [amountstring], [amountdatetimeutc])
GO
