


CREATE PROCEDURE [dbo].[ProcessKinderMorganData_manual] AS
INSERT INTO [Pipeline_Data].[dbo].[rawKinderMorganOperationalCapacity]
(	[TSP]
      ,[TSP Name]
      ,[Eff Gas Day Eff Time]
      ,[CycleDesc]
      ,[Loc Purp Desc]
      ,[Meas Basis Desc]
      ,[Post Date Post Time]
      ,[Loc QTI Desc]
      ,[Loc]
      ,[Loc Name]
      ,[Loc Zn]
      ,[Loc (Segment)]
      ,[Design Capacity]
      ,[Operating Capacity]
      ,[Total Scheduled Quantity]
      ,[Operationally Available Capacity]
      ,[IT]
      ,[Flow Ind]
      ,[All Qty Avail]
      ,[Qty Reason])
SELECT
		[TSP]
      ,[TSP Name]
      ,[Eff Gas Day Eff Time]
      ,[CycleDesc]
      ,[Loc Purp Desc]
      ,[Meas Basis Desc]
      ,[Post Date Post Time]
      ,[Loc QTI Desc]
      ,[Loc]
      ,[Loc Name]
      ,[Loc Zn]
      ,[Loc (Segment)]
      ,[Design Capacity]
      ,[Operating Capacity]
      ,[Total Scheduled Quantity]
      ,[Operationally Available Capacity]
      ,[IT]
      ,[Flow Ind]
      ,[All Qty Avail]
      ,[Qty Reason]
  FROM
[Pipeline_Data].[dbo].[vw_TransformRawKinderMorganData_old]