/******************************
** Name:  [vw_Upstream_UV_AC_PROP_AT]
** Desc:  View used to populate the upstream table UV_AC_PROP_AT
** Auth:  Aaron Vogt
** Date:  10/28/2019
**************************
** Change History
**************************
** PR   Date         Author    Description 
** --   ----------   -------   ------------------------------------
** 1    10/28/2019   Aaron     Object creation
*******************************/
CREATE VIEW 
	[DW].[vw_Upstream_UV_AC_PROP_AT]
AS 
SELECT 
	hub.API14 AS UWI, 
	'DI/IHS Well Headers' AS RecordSource,
	COALESCE(ihswh.RecordSource, diwh.RecordSource) AS SOURCE, 
	GETDATE() AS LoadDate,
	hub.API14 AS API_NUMBER, 
	COALESCE(ihswh.Operator, diwh.Operator) AS OPERATOR_NAME, 
	hub.API14 AS REGULATORY_API, 
	COALESCE(ihswh.Operator, diwh.Operator) AS CURRENT_OPERATOR_NAME, 
	COALESCE(ihswh.Lease_Name, diwh.Lease_Name) AS LEASE_NAME, 
	COALESCE(ihswh.Well_Number, diwh.Well_Number) AS WELL_NUMBER, 
	COALESCE(ihswh.Field, diwh.Field) AS FIELD_NAME, 
	'USA' AS COUNTRY_NAME, 
	COALESCE(ihswh.State, diwh.State) AS STATE_NAME, 
	COALESCE(ihswh.County, diwh.County) AS COUNTY_NAME, 
	COALESCE(ihswh.Hole_Direction, diwh.Hole_Direction) AS HOLE_DIRECTION, 
	COALESCE(ihsws.[Status], diws.[Status]) AS WELL_STATUS, 
	COALESCE(ihsws.[Status], diws.[Status]) AS CURRENT_STATUS, 
	COALESCE(ihswh.Basin, diwh.Basin) AS BASIN, 
	COALESCE(ihswh.Play, diwh.Play) AS PLAY_NAME, 
	COALESCE(ihsplay.New_Play, diplay.New_Play) AS TPC_PLAY_NAME, 
	COALESCE(ihswh.Play_Type, diwh.Play_Type) AS PLAY_TYPE, 
	COALESCE(ihswh.Date_Permit, diwh.Date_Permit) AS PERMIT_DATE, 
	COALESCE(ihswh.Depth_Total_Driller, diwh.Depth_Total_Driller) AS DEPTH_TOTAL_DRILLER, 
	COALESCE(ihswh.Depth_Total_Logger, diwh.Depth_Total_Logger) AS DEPTH_TOTAL_LOGGER, 
	COALESCE(ihswh.Depth_True_Vertical, diwh.Depth_True_Vertical) AS DEPTH_TRUE_VERTICAL, 
	COALESCE(ihswh.Depth_Whipstock, diwh.Depth_Whipstock) AS DEPTH_WHIPSTOCK, 
	COALESCE(ihswh.Status_Final_Code, diwh.Status_Final_Code) AS STATUS_FINAL_CODE, 
	COALESCE(ihswh.Formation_Projected, diwh.Formation_Projected) AS FORMATION_PROJECTED_NAME, 
	COALESCE(ihswh.Depth_Total_Projected, diwh.Depth_Total_Projected) AS DEPTH_TOTAL_PROJECTED, 
	COALESCE(ihswh.Formation_TD, diwh.Formation_TD) AS FORMATION_AT_TD_NAME, 
	COALESCE(ihswh.Formation_TD, diwh.Formation_TD) AS PRODFIT_FORMATION_AT_TD_NAME,
	COALESCE(ihswh.Formation_Producing_Name, diwh.Formation_Producing_Name) AS FORMATION_PRODUCING_NAME,
	COALESCE(ihswh.Formation_Producing_Top, diwh.Formation_Producing_Top) AS PRODFIT_TOP_PRODUCING_FORMATION,
	COALESCE(ihswh.Formation_Producing_Base, diwh.Formation_Producing_Base) AS PRODFIT_BASE_PRODUCING_FORMATION,
	COALESCE(ihswh.Formation_80_Degree_Heel_Pt, diwh.Formation_80_Degree_Heel_Pt) AS PRODFIT_80_DEGREE_HEEL_PT_FORM,
	COALESCE(ihswh.Elevation_Ground, diwh.Elevation_Ground) AS GROUND_ELEVATION, 
	COALESCE(ihswh.Date_Spud, diwh.Date_Spud) AS DATE_SPUD, 
	COALESCE(ihswh.Date_Completion, diwh.Date_Completion) AS DATE_COMPLETION, 
	COALESCE(ihswh.Date_Rig_Release, diwh.Date_Rig_Release) AS DATE_RIG_RELEASE, 
	COALESCE(ihswh.Date_Abandonment, diwh.Date_Abandonment) AS DATE_ABANDONMENT, 
	COALESCE(ihswh.Date_Last_Activity, diwh.Date_Last_Activity) AS DATE_LAST_ACTIVITY, 
	COALESCE(ihswh.Surface_Hole_Latitude, diwh.Surface_Hole_Latitude) AS SURFACE_LATITUDE, 
	COALESCE(ihswh.Surface_Hole_Longitude, diwh.Surface_Hole_Longitude) AS SURFACE_LONGITUDE, 
	COALESCE(ihswh.Bottom_Hole_Latitude, diwh.Bottom_Hole_Latitude) AS BH_LATITUDE, 
	COALESCE(ihswh.Bottom_Hole_Longitude, diwh.Bottom_Hole_Longitude) AS BH_LONGITUDE, 
	COALESCE(ihswh.LoadDate, diwh.LoadDate) AS RECORD_CREATION_DATE, 
	COALESCE(ihswh.LoadDate, diwh.LoadDate) AS RECORD_UPDATE_DATE,
	COALESCE(ihswt.MinTopDepth, diwt.MinTopDepth) AS DEPTH_TOP, 
	COALESCE(ihswt.MaxBaseDepth, diwt.MaxBaseDepth) AS DEPTH_BASE, 
	COALESCE(ihswt.AverageLateralLengthHorizontalDisplacement, diwt.AverageLateralLengthHorizontalDisplacement) AS LAT_LEN_HORIZ_DISPLACEMENT_FT, 
	COALESCE(ihswt.TotalGrossPerforationInterval, diwt.TotalGrossPerforationInterval) AS LAT_LEN_GROSS_PERF_INTVL,
	COALESCE(ihswt.NUM_FRAC_STAGES, diwt.NUM_FRAC_STAGES) AS NUM_FRAC_STAGES, 
	COALESCE(ihswt.NUM_TREATMENT_RECORDS, diwt.NUM_TREATMENT_RECORDS) AS NUM_TREATMENT_RECORDS, 
	COALESCE(ihswt.PROPPANT_SAND_LBS, diwt.PROPPANT_SAND_LBS) AS PROPPANT_SAND_LBS, 
	COALESCE(ihswt.PROPPANT_RESIN_COATED_SAND_LBS, diwt.PROPPANT_RESIN_COATED_SAND_LBS) AS PROPPANT_RESIN_COATED_SAND_LBS, 
	COALESCE(ihswt.PROPPANT_CERAMIC_LBS, diwt.PROPPANT_CERAMIC_LBS) AS PROPPANT_CERAMIC_LBS, 
	COALESCE(ihswt.PROPPANT_RESIN_COATED_CERAMIC_LBS, diwt.PROPPANT_RESIN_COATED_CERAMIC_LBS) AS PROPPANT_RESIN_COATED_CERAMIC_LBS, 
	COALESCE(ihswt.PROPPAND_SAND_CERAMIC_LBS, diwt.PROPPAND_SAND_CERAMIC_LBS) AS PROPPAND_SAND_CERAMIC_LBS, 
	COALESCE(ihswt.PROPPANT_SAND_RESIN_COATED_CERAMIC_LBS, diwt.PROPPANT_SAND_RESIN_COATED_CERAMIC_LBS) AS PROPPANT_SAND_RESIN_COATED_CERAMIC_LBS, 
	COALESCE(ihswt.PROPPANT_SAND_CERAMIC_RESIN_COATED_SAND_LBS, diwt.PROPPANT_SAND_CERAMIC_RESIN_COATED_SAND_LBS) AS PROPPANT_SAND_CERAMIC_RESIN_COATED_SAND_LBS, 
	COALESCE(ihswt.PROPPANT_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS, diwt.PROPPANT_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS) AS PROPPANT_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS, 
	COALESCE(ihswt.PROPPANT_SAND_RESIN_COATED_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS, diwt.PROPPANT_SAND_RESIN_COATED_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS) AS PROPPANT_SAND_RESIN_COATED_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS, 
	COALESCE(ihswt.PROPPANT_BAUXITE_LBS, diwt.PROPPANT_BAUXITE_LBS) AS PROPPANT_BAUXITE_LBS, 
	COALESCE(ihswt.PROPPANT_WALNUT_LBS, diwt.PROPPANT_WALNUT_LBS) AS PROPPANT_WALNUT_LBS, 
	COALESCE(ihswt.PROPPANT_MARBLE_LBS, diwt.PROPPANT_MARBLE_LBS) AS PROPPANT_MARBLE_LBS, 
	COALESCE(ihswt.PROPPANT_GRAVEL_LBS, diwt.PROPPANT_GRAVEL_LBS) AS PROPPANT_GRAVEL_LBS, 
	COALESCE(ihswt.PROPPANT_SAND_BAUXITE_CERAMIC_LBS, diwt.PROPPANT_SAND_BAUXITE_CERAMIC_LBS) AS PROPPANT_SAND_BAUXITE_CERAMIC_LBS, 
	COALESCE(ihswt.PROPPANT_OTHER_LBS, diwt.PROPPANT_OTHER_LBS) AS PROPPANT_OTHER_LBS, 
	COALESCE(ihswt.TOTAL_PROPPANT_LBS, diwt.TOTAL_PROPPANT_LBS) AS TOTAL_PROPPANT_LBS, 
	COALESCE(ihswt.FLUID_WATER_GALS, diwt.FLUID_WATER_GALS) AS FLUID_WATER_GALS, 
	COALESCE(ihswt.FLUID_SLICK_WATER_GALS, diwt.FLUID_SLICK_WATER_GALS) AS FLUID_SLICK_WATER_GALS, 
	COALESCE(ihswt.FLUID_SALT_WATER_GALS, diwt.FLUID_SALT_WATER_GALS) AS FLUID_SALT_WATER_GALS, 
	COALESCE(ihswt.FLUID_FOAM_GALS, diwt.FLUID_FOAM_GALS) AS FLUID_FOAM_GALS, 
	COALESCE(ihswt.FLUID_OIL_GALS, diwt.FLUID_OIL_GALS) AS FLUID_OIL_GALS, 
	COALESCE(ihswt.FLUID_POTASSIUM_CHLORIDE_GALS, diwt.FLUID_POTASSIUM_CHLORIDE_GALS) AS FLUID_POTASSIUM_CHLORIDE_GALS, 
	COALESCE(ihswt.FLUID_SURFACTANT_GALS, diwt.FLUID_SURFACTANT_GALS) AS FLUID_SURFACTANT_GALS, 
	COALESCE(ihswt.FLUID_EMULSION_GALS, diwt.FLUID_EMULSION_GALS) AS FLUID_EMULSION_GALS, 
	COALESCE(ihswt.N2_CO2_GAS_GALS, diwt.N2_CO2_GAS_GALS) AS N2_CO2_GAS_GALS, 
	COALESCE(ihswt.ACID_GALS, diwt.ACID_GALS) AS ACID_GALS, 
	COALESCE(ihswt.GEL_X_LINK_GALS, diwt.GEL_X_LINK_GALS) AS GEL_X_LINK_GALS, 
	COALESCE(ihswt.FLUID_EXPLOSIVE_GALS, diwt.FLUID_EXPLOSIVE_GALS) AS FLUID_EXPLOSIVE_GALS, 
	COALESCE(ihswt.FLUID_OTHER_GALS, diwt.FLUID_OTHER_GALS) AS FLUID_OTHER_GALS, 
	COALESCE(ihswt.TOTAL_FLUID_GALS, diwt.TOTAL_FLUID_GALS) AS TOTAL_FLUID_GALS, 
	COALESCE(ihswt.TOTAL_PROPPANT_LBS_OR_TOTAL_FLUID_GAL, diwt.TOTAL_PROPPANT_LBS_OR_TOTAL_FLUID_GAL) AS TOTAL_PROPPANT_LBS_OR_TOTAL_FLUID_GAL,
	COALESCE(ihswl.Surface_TOWNSHIP_DIRECTION, diwl.Surface_TOWNSHIP_DIRECTION) AS SURFACE_TOWNSHIP_DIRECTION, 
	COALESCE(ihswl.Surface_TOWNSHIP_NUMBER, diwl.Surface_TOWNSHIP_NUMBER) AS SURFACE_TOWNSHIP_NUMBER, 
	COALESCE(ihswl.Surface_RANGE_DIRECTION, diwl.Surface_RANGE_DIRECTION) AS SURFACE_RANGE_DIRECTION, 
	COALESCE(ihswl.Surface_RANGE_NUMBER, diwl.Surface_RANGE_NUMBER) AS SURFACE_RANGE_NUMBER, 
	COALESCE(ihswl.Surface_SECTION_NUMBER, diwl.Surface_SECTION_NUMBER) AS SURFACE_SECTION_NUMBER, 
	COALESCE(ihswl.Surface_SECTION_TYPE, diwl.Surface_SECTION_TYPE) AS SURFACE_SECTION_TYPE, 
	COALESCE(ihswl.Surface_SPOT, diwl.Surface_SPOT) AS SURFACE_SPOT, 
	COALESCE(ihswl.Surface_MERIDIAN_NAME, diwl.Surface_MERIDIAN_NAME) AS SURFACE_MERIDIAN_NAME, 
	COALESCE(ihswl.Surface_REMARK, diwl.Surface_REMARK) AS SURFACE_REMARK, 
	COALESCE(ihswl.Surface_FOOTAGE_NORTH_SOUTH, diwl.Surface_FOOTAGE_NORTH_SOUTH) AS SURFACE_FOOTAGE_NORTH_SOUTH, 
	COALESCE(ihswl.Surface_FOOTAGE_NORTH_SOUTH_START_LINE, diwl.Surface_FOOTAGE_NORTH_SOUTH_START_LINE) AS SURFACE_FOOTAGE_NORTH_SOUTH_START_LINE, 
	COALESCE(ihswl.Surface_FOOTAGE_EAST_WEST, diwl.Surface_FOOTAGE_EAST_WEST) AS SURFACE_FOOTAGE_EAST_WEST, 
	COALESCE(ihswl.Surface_FOOTAGE_EAST_WEST_START_LINE, diwl.Surface_FOOTAGE_EAST_WEST_START_LINE) AS SURFACE_FOOTAGE_EAST_WEST_START_LINE, 
	COALESCE(ihswl.Surface_FOOTAGE_REFERENCE_NAME, diwl.Surface_FOOTAGE_REFERENCE_NAME) AS SURFACE_FOOTAGE_REFERENCE_NAME,
	COALESCE(ihswl.BH_TOWNSHIP_DIRECTION, diwl.BH_TOWNSHIP_DIRECTION) AS BH_TOWNSHIP_DIRECTION, 
	COALESCE(ihswl.BH_TOWNSHIP_NUMBER, diwl.BH_TOWNSHIP_NUMBER) AS BH_TOWNSHIP_NUMBER, 
	COALESCE(ihswl.BH_RANGE_DIRECTION, diwl.BH_RANGE_DIRECTION) AS BH_RANGE_DIRECTION, 
	COALESCE(ihswl.BH_RANGE_NUMBER, diwl.BH_RANGE_NUMBER) AS BH_RANGE_NUMBER, 
	COALESCE(ihswl.BH_SECTION_NUMBER, diwl.BH_SECTION_NUMBER) AS BH_SECTION_NUMBER, 
	COALESCE(ihswl.BH_SECTION_TYPE, diwl.BH_SECTION_TYPE) AS BH_SECTION_TYPE, 
	COALESCE(ihswl.BH_SPOT, diwl.BH_SPOT) AS BH_SPOT, 
	COALESCE(ihswl.BH_MERIDIAN_NAME, diwl.BH_MERIDIAN_NAME) AS BH_MERIDIAN_NAME, 
	COALESCE(ihswl.BH_REMARK, diwl.BH_REMARK) AS BH_REMARK, 
	COALESCE(ihswl.BH_FOOTAGE_NORTH_SOUTH, diwl.BH_FOOTAGE_NORTH_SOUTH) AS BH_FOOTAGE_NORTH_SOUTH, 
	COALESCE(ihswl.BH_FOOTAGE_NORTH_SOUTH_START_LINE, diwl.BH_FOOTAGE_NORTH_SOUTH_START_LINE) AS BH_FOOTAGE_NORTH_SOUTH_START_LINE, 
	COALESCE(ihswl.BH_FOOTAGE_EAST_WEST, diwl.BH_FOOTAGE_EAST_WEST) AS BH_FOOTAGE_EAST_WEST, 
	COALESCE(ihswl.BH_FOOTAGE_EAST_WEST_START_LINE, diwl.BH_FOOTAGE_EAST_WEST_START_LINE) AS BH_FOOTAGE_EAST_WEST_START_LINE, 
	COALESCE(ihswl.BH_FOOTAGE_REFERENCE_NAME, diwl.BH_FOOTAGE_REFERENCE_NAME) AS BH_FOOTAGE_REFERENCE_NAME
FROM 
[DW].HubWell hub WITH (NOLOCK)
LEFT JOIN
	[DW].[SatWellHeader] diwh WITH (NOLOCK)
ON
	diwh.WellHashKey = hub.WellHashKey AND
	diwh.RecordSource = 'DI Well Rollups' AND
	diwh.LoadEndDate IS NULL
LEFT JOIN
	[DW].[SatWellHeader] ihswh WITH (NOLOCK)
ON
	ihswh.WellHashKey = hub.WellHashKey AND
	ihswh.RecordSource = 'IHS Well Header' AND
	ihswh.LoadEndDate IS NULL
LEFT JOIN
	[DW].[SatWellStatus] diws WITH (NOLOCK)
ON
	hub.WellHashKey = diws.WellHashKey AND
	diws.RecordSource = 'DI Well Rollups' AND
	diws.LoadEndDate IS NULL
LEFT JOIN
	[DW].[SatWellStatus] ihsws WITH (NOLOCK)
ON
	hub.WellHashKey = ihsws.WellHashKey AND
	ihsws.RecordSource = 'IHS Well Header' AND
	ihsws.LoadEndDate IS NULL
LEFT JOIN
	[DW].[SatWellLocation] diwl WITH (NOLOCK)
ON
	hub.WellHashKey = diwl.WellHashKey AND
	diwl.RecordSource = 'DI Well Rollups' AND
	diwl.LoadEndDate IS NULL
LEFT JOIN
	[DW].[SatWellLocation] ihswl WITH (NOLOCK)
ON
	hub.WellHashKey = ihswl.WellHashKey AND
	ihswl.RecordSource = 'IHS Well Location' AND
	ihswl.LoadEndDate IS NULL
LEFT JOIN
	[DW].[SatWellTreatment] diwt WITH (NOLOCK)
ON
	hub.WellHashKey = diwt.WellHashKey AND
	diwt.RecordSource = 'DI Treatment Jobs' AND
	diwt.LoadEndDate IS NULL
LEFT JOIN
	[DW].[SatWellTreatment] ihswt WITH (NOLOCK)
ON
	hub.WellHashKey = ihswt.WellHashKey AND
	ihswt.RecordSource = 'IHS Well Treatment Summary' AND
	ihswt.LoadEndDate IS NULL
LEFT JOIN
	[Upstream].[RefWell_PlayByStateCounty] ihsplay
ON
	ihswh.State = ihsplay.State AND
	ihswh.County = ihsplay.County AND
	ihswh.LoadEndDate IS NULL
LEFT JOIN
	[Upstream].[RefWell_PlayByStateCounty] diplay
ON
	diwh.State = diplay.State AND
	diwh.County = diplay.County
WHERE
	--Make sure we have header information, at the very least
	(diwh.LoadDate IS NOT NULL OR ihswh.LoadDate IS NOT NULL)