CREATE TABLE [StageIHS].[T_WELL_HEADER] (
    [UWI]                              VARCHAR (175)   NOT NULL,
    [SOURCE]                           VARCHAR (175)   NOT NULL,
    [API_NUMBER]                       VARCHAR (175)   NULL,
    [IC_NUMBER]                        VARCHAR (175)   NULL,
    [OPERATOR_NAME]                    VARCHAR (175)   NULL,
    [OPERATOR_CITY]                    VARCHAR (175)   NULL,
    [REGULATORY_API]                   VARCHAR (175)   NULL,
    [CURRENT_OPERATOR_NAME]            VARCHAR (175)   NULL,
    [CURRENT_OPERATOR_CITY]            VARCHAR (175)   NULL,
    [LEASE_NAME]                       VARCHAR (175)   NULL,
    [WELL_NUMBER]                      VARCHAR (175)   NULL,
    [FIELD_NAME]                       VARCHAR (175)   NULL,
    [COUNTRY_NAME]                     VARCHAR (175)   NULL,
    [STATE_NAME]                       VARCHAR (175)   NULL,
    [COUNTY_NAME]                      VARCHAR (175)   NULL,
    [OS_INDICATOR]                     VARCHAR (175)   NULL,
    [HOLE_DIRECTION]                   VARCHAR (175)   NULL,
    [WELL_STATUS]                      VARCHAR (175)   NULL,
    [CURRENT_STATUS]                   VARCHAR (175)   NULL,
    [BASIN]                            VARCHAR (175)   NULL,
    [PLAY_NAME]                        VARCHAR (175)   NULL,
    [PLAY_TYPE]                        VARCHAR (175)   NULL,
    [PERMIT_NUMBER]                    VARCHAR (175)   NULL,
    [PERMIT_DATE]                      DATE            NULL,
    [DEPTH_TOTAL_DRILLER]              DECIMAL (10, 5) NULL,
    [DEPTH_TOTAL_LOGGER]               DECIMAL (10, 5) NULL,
    [DEPTH_TRUE_VERTICAL]              DECIMAL (10, 5) NULL,
    [DEPTH_WHIPSTOCK]                  DECIMAL (10, 5) NULL,
    [CLASS_INITIAL_NAME]               VARCHAR (175)   NULL,
    [CLASS_INITIAL_CODE]               VARCHAR (175)   NULL,
    [CLASS_FINAL_NAME]                 VARCHAR (175)   NULL,
    [CLASS_FINAL_CODE]                 VARCHAR (175)   NULL,
    [STATUS_FINAL_CODE]                VARCHAR (175)   NULL,
    [FORMATION_PROJECTED_NAME]         VARCHAR (175)   NULL,
    [DEPTH_TOTAL_PROJECTED]            DECIMAL (10, 5) NULL,
    [FORMATION_AT_TD_NAME]             VARCHAR (175)   NULL,
    [PRODFIT_FORMATION_AT_TD_NAME]     VARCHAR (175)   NULL,
    [FORMATION_PRODUCING_NAME]         VARCHAR (175)   NULL,
    [PRODFIT_TOP_PRODUCING_FORMATION]  VARCHAR (175)   NULL,
    [PRODFIT_BASE_PRODUCING_FORMATION] VARCHAR (175)   NULL,
    [PRODFIT_80_DEGREE_HEEL_PT_FORM]   VARCHAR (175)   NULL,
    [ELEVATION_REFERENCE_VALUE]        DECIMAL (10, 5) NULL,
    [ELEVATION_REFERENCE_DATUM]        VARCHAR (175)   NULL,
    [GROUND_ELEVATION]                 DECIMAL (10, 5) NULL,
    [DATE_FIRST_SPUD]                  DATE            NULL,
    [DATE_SPUD]                        DATE            NULL,
    [DATE_COMPLETION]                  DATE            NULL,
    [DATE_RIG_RELEASE]                 DATE            NULL,
    [DATE_ABANDONMENT]                 DATE            NULL,
    [DATE_FIRST_REPORT]                DATE            NULL,
    [DATE_LAST_ACTIVITY]               DATE            NULL,
    [DEPTH_WATER_VALUE]                DECIMAL (10, 5) NULL,
    [DEPTH_WATER_DATUM]                VARCHAR (175)   NULL,
    [SURFACE_LATITUDE]                 DECIMAL (13, 9) NULL,
    [SURFACE_LONGITUDE]                DECIMAL (13, 9) NULL,
    [SURFACE_LL_SOURCE]                VARCHAR (175)   NULL,
    [PROPOSED_BH_LATITUDE]             DECIMAL (13, 9) NULL,
    [PROPOSED_BH_LONGITUDE]            DECIMAL (13, 9) NULL,
    [PROPOSED_BH_LL_SOURCE]            VARCHAR (175)   NULL,
    [BH_LATITUDE]                      DECIMAL (13, 9) NULL,
    [BH_LONGITUDE]                     DECIMAL (13, 9) NULL,
    [BH_LL_SOURCE]                     VARCHAR (175)   NULL,
    [ACTIVITY_CODE]                    VARCHAR (175)   NULL,
    [PERMIT_FILER_LONG]                VARCHAR (240)   NULL,
    [PERMIT_PHONE]                     VARCHAR (175)   NULL,
    [REGULATORY_STATUS]                VARCHAR (175)   NULL,
    [REGULATORY_STATUS_DATE]           DATE            NULL,
    [PERMIT_REISSUE_DATE]              DATE            NULL,
    [MAP_SYMBOL]                       VARCHAR (175)   NULL,
    [CADIS_SYSTEM_INSERTED]            DATETIME        NULL,
    [CADIS_SYSTEM_UPDATED]             DATETIME        NULL,
    [CADIS_SYSTEM_CHANGEDBY]           NVARCHAR (175)  NULL,
    [CADIS_SYSTEM_TIMESTAMP]           VARBINARY (50)  NULL,
    [CADIS_SYSTEM_RUNID]               INT             NULL,
    [CADIS_SYSTEM_TOPRUNID]            INT             NULL,
    CONSTRAINT [PK_T_WELL_HEADER] PRIMARY KEY CLUSTERED ([UWI] ASC, [SOURCE] ASC)
);

