CREATE TABLE [StageIHS].[T_WELL_TREATMENT_SUMMARY] (
    [UWI]                                                              VARCHAR (450)   NOT NULL,
    [SOURCE]                                                           VARCHAR (450)   NOT NULL,
    [NUM_FRAC_STAGES]                                                  DECIMAL (3)     NULL,
    [NUM_TREATMENT_RECORDS]                                            DECIMAL (3)     NULL,
    [PROPPANT_SAND_LBS]                                                DECIMAL (12, 1) NULL,
    [PROPPANT_RESIN_COATED_SAND_LBS]                                   DECIMAL (12, 1) NULL,
    [PROPPANT_CERAMIC_LBS]                                             DECIMAL (12, 1) NULL,
    [PROPPANT_RESIN_COATED_CERAMIC_LBS]                                DECIMAL (12, 1) NULL,
    [PROPPAND_SAND_CERAMIC_LBS]                                        DECIMAL (12, 1) NULL,
    [PROPPANT_SAND_RESIN_COATED_CERAMIC_LBS]                           DECIMAL (12, 1) NULL,
    [PROPPANT_SAND_CERAMIC_RESIN_COATED_SAND_LBS]                      DECIMAL (12, 1) NULL,
    [PROPPANT_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS]                   DECIMAL (12, 1) NULL,
    [PROPPANT_SAND_RESIN_COATED_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS] DECIMAL (12, 1) NULL,
    [PROPPANT_BAUXITE_LBS]                                             DECIMAL (12, 1) NULL,
    [PROPPANT_WALNUT_LBS]                                              DECIMAL (12, 1) NULL,
    [PROPPANT_MARBLE_LBS]                                              DECIMAL (12, 1) NULL,
    [PROPPANT_GRAVEL_LBS]                                              DECIMAL (12, 1) NULL,
    [PROPPANT_SAND_BAUXITE_CERAMIC_LBS]                                DECIMAL (12, 1) NULL,
    [PROPPANT_OTHER_LBS]                                               DECIMAL (12, 1) NULL,
    [TOTAL_PROPPANT_LBS]                                               DECIMAL (12, 1) NULL,
    [FLUID_WATER_GALS]                                                 DECIMAL (12, 1) NULL,
    [FLUID_SLICK_WATER_GALS]                                           DECIMAL (12, 1) NULL,
    [FLUID_SALT_WATER_GALS]                                            DECIMAL (12, 1) NULL,
    [FLUID_FOAM_GALS]                                                  DECIMAL (12, 1) NULL,
    [FLUID_OIL_GALS]                                                   DECIMAL (12, 1) NULL,
    [FLUID_POTASSIUM_CHLORIDE_GALS]                                    DECIMAL (12, 1) NULL,
    [FLUID_SURFACTANT_GALS]                                            DECIMAL (12, 1) NULL,
    [FLUID_EMULSION_GALS]                                              DECIMAL (12, 1) NULL,
    [N2_CO2_GAS_GALS]                                                  DECIMAL (12, 1) NULL,
    [ACID_GALS]                                                        DECIMAL (12, 1) NULL,
    [GEL_X_LINK_GALS]                                                  DECIMAL (12, 1) NULL,
    [FLUID_EXPLOSIVE_GALS]                                             DECIMAL (12, 1) NULL,
    [FLUID_OTHER_GALS]                                                 DECIMAL (12, 1) NULL,
    [TOTAL_FLUID_GALS]                                                 DECIMAL (12, 1) NULL,
    [CADIS_SYSTEM_INSERTED]                                            DATETIME        NULL,
    [CADIS_SYSTEM_UPDATED]                                             DATETIME        NULL,
    [CADIS_SYSTEM_CHANGEDBY]                                           NVARCHAR (450)  NULL,
    [CADIS_SYSTEM_TIMESTAMP]                                           VARBINARY (50)  NOT NULL,
    [CADIS_SYSTEM_RUNID]                                               INT             NOT NULL,
    [CADIS_SYSTEM_TOPRUNID]                                            INT             NOT NULL,
    [TOTAL_PROPPANT_LBS_OR_TOTAL_FLUID_GAL]                            DECIMAL (12, 1) NULL,
    CONSTRAINT [PK_T_WELL_TREATMENT_SUMMARY] PRIMARY KEY CLUSTERED ([UWI] ASC, [SOURCE] ASC)
);

