CREATE TABLE [StageIHS].[T_WELL_LOCATION] (
    [UWI]                                     VARCHAR (80)    NOT NULL,
    [SOURCE]                                  VARCHAR (80)    NOT NULL,
    [POSITION]                                VARCHAR (80)    NOT NULL,
    [TYPE]                                    VARCHAR (80)    NOT NULL,
    [TOWNSHIP_DIRECTION]                      VARCHAR (80)    NULL,
    [TOWNSHIP_NUMBER]                         DECIMAL (6, 1)  NULL,
    [RANGE_DIRECTION]                         VARCHAR (80)    NULL,
    [RANGE_NUMBER]                            DECIMAL (5, 1)  NULL,
    [SECTION_NUMBER]                          DECIMAL (5, 1)  NULL,
    [SECTION_TYPE]                            VARCHAR (80)    NULL,
    [SPOT]                                    VARCHAR (80)    NULL,
    [MERIDIAN_NAME]                           VARCHAR (80)    NULL,
    [REMARK]                                  VARCHAR (240)   NULL,
    [FOOTAGE_NORTH_SOUTH]                     DECIMAL (7, 2)  NULL,
    [FOOTAGE_NORTH_SOUTH_START_LINE]          VARCHAR (80)    NULL,
    [FOOTAGE_EAST_WEST]                       DECIMAL (7, 2)  NULL,
    [FOOTAGE_EAST_WEST_START_LINE]            VARCHAR (80)    NULL,
    [FOOTAGE_REFERENCE_NAME]                  VARCHAR (80)    NULL,
    [OFFSHORE_BLOCK_ADDITION]                 VARCHAR (80)    NULL,
    [OFFSHORE_BLOCK_NUMBER]                   VARCHAR (80)    NULL,
    [OFFSHORE_BLOCK_MODIFIER]                 VARCHAR (80)    NULL,
    [OFFSHORE_OCS_NUMBER]                     VARCHAR (80)    NULL,
    [OFFSHORE_AREA_CODE]                      VARCHAR (80)    NULL,
    [OFFSHORE_UTM_QUADRANT]                   VARCHAR (80)    NULL,
    [OFFSHORE_GOVERNING_AGENCY]               VARCHAR (80)    NULL,
    [OFFSHORE_WATER_BOTTOM_ZONE_NAME]         VARCHAR (80)    NULL,
    [OFFSHORE_REMARK]                         VARCHAR (240)   NULL,
    [OFFSHORE_FOOTAGE_NORTH_SOUTH]            DECIMAL (7, 2)  NULL,
    [OFFSHORE_FOOTAGE_NORTH_SOUTH_START_LINE] VARCHAR (80)    NULL,
    [OFFSHORE_FOOTAGE_EAST_WEST]              DECIMAL (7, 2)  NULL,
    [OFFSHORE_FOOTAGE_EAST_WEST_START_LINE]   VARCHAR (80)    NULL,
    [OFFSHORE_FOOTAGE_REFERENCE_NAME]         VARCHAR (80)    NULL,
    [TEXAS_DISTRICT_NAME]                     VARCHAR (80)    NULL,
    [TEXAS_BLOCK_NUMBER]                      VARCHAR (80)    NULL,
    [TEXAS_BLOCK_FRACTION]                    VARCHAR (80)    NULL,
    [TEXAS_LEAGUE]                            VARCHAR (80)    NULL,
    [TEXAS_LOT]                               VARCHAR (80)    NULL,
    [TEXAS_TOWNSHIP_DIRECTION]                VARCHAR (80)    NULL,
    [TEXAS_TOWNSHIP_NUMBER]                   DECIMAL (4, 1)  NULL,
    [TEXAS_SECTION_NUMBER]                    VARCHAR (80)    NULL,
    [TEXAS_SECTION_FRACTION]                  VARCHAR (80)    NULL,
    [TEXAS_LABOR]                             VARCHAR (80)    NULL,
    [TEXAS_SURVEY]                            VARCHAR (80)    NULL,
    [TEXAS_ABSTRACT]                          VARCHAR (80)    NULL,
    [TEXAS_SPOT]                              VARCHAR (80)    NULL,
    [TEXAS_REMARK]                            VARCHAR (240)   NULL,
    [TEXAS_FOOTAGE_NORTH_SOUTH]               DECIMAL (7, 2)  NULL,
    [TEXAS_FOOTAGE_NORTH_SOUTH_START_LINE]    VARCHAR (80)    NULL,
    [TEXAS_FOOTAGE_EAST_WEST]                 DECIMAL (7, 2)  NULL,
    [TEXAS_FOOTAGE_EAST_WEST_START_LINE]      VARCHAR (80)    NULL,
    [TEXAS_FOOTAGE_REFERENCE_NAME]            VARCHAR (80)    NULL,
    [CARTER_TOWNSHIP_DIRECTION]               VARCHAR (80)    NULL,
    [CARTER_TOWNSHIP_NAME]                    VARCHAR (80)    NULL,
    [CARTER_RANGE_DIRECTION]                  VARCHAR (80)    NULL,
    [CARTER_RANGE_NUMBER]                     DECIMAL (5, 1)  NULL,
    [CARTER_SECTION]                          DECIMAL (5, 1)  NULL,
    [CARTER_SPOT]                             VARCHAR (80)    NULL,
    [CARTER_QUADRANGLE_MINUTES]               DECIMAL (3, 1)  NULL,
    [CARTER_QUADRANGLE_NAME]                  VARCHAR (80)    NULL,
    [CARTER_REMARK]                           VARCHAR (240)   NULL,
    [CARTER_FOOTAGE_NORTH_SOUTH]              DECIMAL (7, 2)  NULL,
    [CARTER_FOOTAGE_NORTH_SOUTH_START_LINE]   VARCHAR (80)    NULL,
    [CARTER_FOOTAGE_EAST_WEST]                DECIMAL (7, 2)  NULL,
    [CARTER_FOOTAGE_EAST_WEST_START_LINE]     VARCHAR (80)    NULL,
    [CARTER_FOOTAGE_REFERENCE_NAME]           VARCHAR (80)    NULL,
    [OHIO_LOT_CODE]                           VARCHAR (80)    NULL,
    [OHIO_SECTION_CODE]                       VARCHAR (80)    NULL,
    [OHIO_TOWNSHIP_NAME]                      VARCHAR (80)    NULL,
    [OHIO_MERIDIAN_NAME]                      VARCHAR (80)    NULL,
    [OHIO_SPOT]                               VARCHAR (80)    NULL,
    [OHIO_QUADRANGLE_NAME]                    VARCHAR (80)    NULL,
    [OHIO_QUADRANGLE_MINUTES]                 DECIMAL (3, 1)  NULL,
    [OHIO_REMARK]                             VARCHAR (240)   NULL,
    [OHIO_FOOTAGE_NORTH_SOUTH]                DECIMAL (7, 2)  NULL,
    [OHIO_FOOTAGE_NORTH_SOUTH_START_LINE]     VARCHAR (80)    NULL,
    [OHIO_FOOTAGE_EAST_WEST]                  DECIMAL (7, 2)  NULL,
    [OHIO_FOOTAGE_EAST_WEST_START_LINE]       VARCHAR (80)    NULL,
    [OHIO_FOOTAGE_REFERENCE_NAME]             VARCHAR (80)    NULL,
    [NE_REFERENCE_LATITUDE]                   DECIMAL (12, 7) NULL,
    [NE_REFERENCE_LONGITUDE]                  DECIMAL (12, 7) NULL,
    [NE_TOWNSHIP_NAME]                        VARCHAR (80)    NULL,
    [NE_LOT_CODE]                             VARCHAR (80)    NULL,
    [NE_DISTRICT]                             VARCHAR (80)    NULL,
    [NE_QUADRANGLE_MINUTES]                   DECIMAL (3, 1)  NULL,
    [NE_QUADRANGLE_NAME]                      VARCHAR (80)    NULL,
    [NE_QUADRANGLE_SECTION]                   VARCHAR (80)    NULL,
    [NE_REMARK]                               VARCHAR (240)   NULL,
    [NE_FOOTAGE_NORTH_SOUTH]                  DECIMAL (7, 2)  NULL,
    [NE_FOOTAGE_NORTH_SOUTH_START_LINE]       VARCHAR (80)    NULL,
    [NE_FOOTAGE_EAST_WEST]                    DECIMAL (7, 2)  NULL,
    [NE_FOOTAGE_EAST_WEST_START_LINE]         VARCHAR (80)    NULL,
    [NE_FOOTAGE_REFERENCE_NAME]               VARCHAR (80)    NULL,
    [DLS_LOCATION_TYPE]                       VARCHAR (80)    NULL,
    [DLS_EVENT_SEQUENCE]                      VARCHAR (80)    NULL,
    [DLS_LEGAL_SUBDIVISION]                   VARCHAR (80)    NULL,
    [DLS_LOC_EXCEPTION]                       VARCHAR (80)    NULL,
    [DLS_MERIDIAN]                            VARCHAR (80)    NULL,
    [DLS_MERIDIAN_DIRECTION]                  VARCHAR (80)    NULL,
    [DLS_RANGE]                               VARCHAR (80)    NULL,
    [DLS_RANGE_MODIFIER]                      VARCHAR (80)    NULL,
    [DLS_SECTION]                             VARCHAR (80)    NULL,
    [DLS_TOWNSHIP]                            TINYINT         NULL,
    [DLS_TOWNSHIP_MODIFIER]                   VARCHAR (80)    NULL,
    [DLS_REMARK]                              VARCHAR (240)   NULL,
    [DLS_SOURCE]                              VARCHAR (80)    NULL,
    [FPS_LOCATION_TYPE]                       VARCHAR (80)    NULL,
    [FPS_EXCEPTION]                           VARCHAR (80)    NULL,
    [FPS_GRID]                                VARCHAR (80)    NULL,
    [FPS_REMARK]                              VARCHAR (240)   NULL,
    [FPS_SECTION]                             VARCHAR (80)    NULL,
    [FPS_SOURCE]                              VARCHAR (80)    NULL,
    [FPS_UNIT]                                VARCHAR (80)    NULL,
    [NTS_LOCATION_TYPE]                       VARCHAR (80)    NULL,
    [NTS_BLOCK]                               VARCHAR (80)    NULL,
    [NTS_EVENT_SEQUENCE]                      VARCHAR (80)    NULL,
    [NTS_LETTER_QUADRANGLE]                   VARCHAR (80)    NULL,
    [NTS_LOC_EXCEPTION]                       VARCHAR (80)    NULL,
    [NTS_PRIMARY_QUADRANGLE]                  TINYINT         NULL,
    [NTS_QUARTER_UNIT]                        VARCHAR (80)    NULL,
    [NTS_REMARK]                              VARCHAR (240)   NULL,
    [NTS_SIXTEENTH]                           TINYINT         NULL,
    [NTS_SOURCE]                              VARCHAR (80)    NULL,
    [NTS_UNIT]                                TINYINT         NULL,
    [CADIS_SYSTEM_INSERTED]                   DATETIME        NULL,
    [CADIS_SYSTEM_UPDATED]                    DATETIME        NULL,
    [CADIS_SYSTEM_CHANGEDBY]                  NVARCHAR (80)   NULL,
    [CADIS_SYSTEM_TIMESTAMP]                  VARBINARY (50)  NULL,
    [CADIS_SYSTEM_RUNID]                      INT             NULL,
    [CADIS_SYSTEM_TOPRUNID]                   INT             NULL,
    CONSTRAINT [PK_T_WELL_LOCATION] PRIMARY KEY CLUSTERED ([UWI] ASC, [SOURCE] ASC, [POSITION] ASC, [TYPE] ASC)
);

