create view BOLO.V_AFEvReturnCertificate as
SELECT [AFE]
      ,[Cost Center]
      ,[Cost Center Number]
      ,[AFE Budget]
      ,[Gross Field Estimate]
      ,[Interest]
      ,[Net AFE Budget]
      ,[Net Actuals]
      ,[Net Field Est]
      ,[105% Return Certificate]
      ,[Variance Field Estimate to 105% of Ret Cert]
      ,[Variance Net Actuals to 105% of Ret Cert]
  FROM [ETL].[AFEvReturnCertificate]