CREATE TABLE [DW].[HubAFE] (
    [AFEHashKey]   CHAR (32)     NOT NULL,
    [RecordSource] VARCHAR (50)  NOT NULL,
    [LoadDate]     DATETIME2 (7) CONSTRAINT [DF_HubAFE_LoadDate_] DEFAULT (getdate()) NOT NULL,
    [AFENumber]    VARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_HubAFE] PRIMARY KEY NONCLUSTERED ([AFEHashKey] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [UK_HubAFEAFENumber] UNIQUE NONCLUSTERED ([AFENumber] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

