CREATE TABLE [DW].[HubParty] (
    [RecordSource] VARCHAR (50)  NOT NULL,
    [LoadDate]     DATETIME2 (7) CONSTRAINT [DF_HubParty_LoadDate] DEFAULT (getdate()) NOT NULL,
    [NAME_Base_ID] VARCHAR (50)  NOT NULL,
    [PartyHashKey] BINARY (32)   NOT NULL,
    CONSTRAINT [PK_HubParty] PRIMARY KEY NONCLUSTERED ([PartyHashKey] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [UK_HubParty_Name_Base_ID] UNIQUE NONCLUSTERED ([NAME_Base_ID] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

