CREATE TABLE [DW].[HubWell] (
    [RecordSource] VARCHAR (50)  NOT NULL,
    [LoadDate]     DATETIME2 (7) CONSTRAINT [DF__HubWell__LoadDat__79C80F94] DEFAULT (getdate()) NOT NULL,
    [API14]        VARCHAR (20)  NOT NULL,
    [WellHashKey]  BINARY (32)   NOT NULL,
    CONSTRAINT [PK_HubWell] PRIMARY KEY CLUSTERED ([WellHashKey] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [UK_HubWellAPI14] UNIQUE NONCLUSTERED ([API14] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);


GO
CREATE NONCLUSTERED INDEX [idx_HubWell_WellHashKey_API14]
    ON [DW].[HubWell]([WellHashKey] ASC, [API14] ASC);

