CREATE TABLE [DW].[SatWellTreatment] (
    [RecordSource]                                                     VARCHAR (50)     NOT NULL,
    [LoadDate]                                                         DATETIME2 (7)    CONSTRAINT [DF__SatWellTr__LoadD__670A40DB] DEFAULT (getdate()) NOT NULL,
    [LoadEndDate]                                                      DATETIME2 (7)    NULL,
    [NUM_FRAC_STAGES]                                                  DECIMAL (38)     NULL,
    [NUM_TREATMENT_RECORDS]                                            DECIMAL (38)     NULL,
    [PROPPANT_SAND_LBS]                                                DECIMAL (12, 1)  NULL,
    [PROPPANT_RESIN_COATED_SAND_LBS]                                   DECIMAL (12, 1)  NULL,
    [PROPPANT_CERAMIC_LBS]                                             DECIMAL (12, 1)  NULL,
    [PROPPANT_RESIN_COATED_CERAMIC_LBS]                                DECIMAL (12, 1)  NULL,
    [PROPPAND_SAND_CERAMIC_LBS]                                        DECIMAL (12, 1)  NULL,
    [PROPPANT_SAND_RESIN_COATED_CERAMIC_LBS]                           DECIMAL (12, 1)  NULL,
    [PROPPANT_SAND_CERAMIC_RESIN_COATED_SAND_LBS]                      DECIMAL (12, 1)  NULL,
    [PROPPANT_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS]                   DECIMAL (12, 1)  NULL,
    [PROPPANT_SAND_RESIN_COATED_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS] DECIMAL (12, 1)  NULL,
    [PROPPANT_BAUXITE_LBS]                                             DECIMAL (12, 1)  NULL,
    [PROPPANT_WALNUT_LBS]                                              DECIMAL (12, 1)  NULL,
    [PROPPANT_MARBLE_LBS]                                              DECIMAL (12, 1)  NULL,
    [PROPPANT_GRAVEL_LBS]                                              DECIMAL (12, 1)  NULL,
    [PROPPANT_SAND_BAUXITE_CERAMIC_LBS]                                DECIMAL (12, 1)  NULL,
    [PROPPANT_OTHER_LBS]                                               DECIMAL (12, 1)  NULL,
    [TOTAL_PROPPANT_LBS]                                               DECIMAL (38, 1)  NULL,
    [FLUID_WATER_GALS]                                                 DECIMAL (12, 1)  NULL,
    [FLUID_SLICK_WATER_GALS]                                           DECIMAL (12, 1)  NULL,
    [FLUID_SALT_WATER_GALS]                                            DECIMAL (12, 1)  NULL,
    [FLUID_FOAM_GALS]                                                  DECIMAL (12, 1)  NULL,
    [FLUID_OIL_GALS]                                                   DECIMAL (12, 1)  NULL,
    [FLUID_POTASSIUM_CHLORIDE_GALS]                                    DECIMAL (12, 1)  NULL,
    [FLUID_SURFACTANT_GALS]                                            DECIMAL (12, 1)  NULL,
    [FLUID_EMULSION_GALS]                                              DECIMAL (12, 1)  NULL,
    [N2_CO2_GAS_GALS]                                                  DECIMAL (12, 1)  NULL,
    [ACID_GALS]                                                        DECIMAL (12, 1)  NULL,
    [GEL_X_LINK_GALS]                                                  DECIMAL (12, 1)  NULL,
    [FLUID_EXPLOSIVE_GALS]                                             DECIMAL (12, 1)  NULL,
    [FLUID_OTHER_GALS]                                                 DECIMAL (12, 1)  NULL,
    [TOTAL_FLUID_GALS]                                                 DECIMAL (38, 1)  NULL,
    [TOTAL_PROPPANT_LBS_OR_TOTAL_FLUID_GAL]                            DECIMAL (38, 18) NULL,
    [TotalLateralLengths]                                              DECIMAL (38, 5)  NULL,
    [TotalOffsetsMinTopDepthMaxBaseDepth]                              DECIMAL (38, 5)  NULL,
    [AverageLateralLengthHorizontalDisplacement]                       INT              NULL,
    [TotalLateralLengthHorizontalDisplacement]                         INT              NULL,
    [TotalGrossPerforationInterval]                                    DECIMAL (38, 5)  NULL,
    [MinTopDepth]                                                      DECIMAL (38, 16) NULL,
    [MaxBaseDepth]                                                     DECIMAL (38, 16) NULL,
    [OffsetSurfaceCoordBHCoordFeet]                                    NUMERIC (38, 16) NULL,
    [WellHashKey]                                                      BINARY (32)      NOT NULL,
    CONSTRAINT [PK_SatWellTreatment] PRIMARY KEY CLUSTERED ([WellHashKey] ASC, [RecordSource] ASC, [LoadDate] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

