CREATE TABLE [ProCount].[CompletionTb] (
    [MerrickID]                  INT              NOT NULL,
    [PropertyWellID]             INT              NULL,
    [PropertyNumber]             VARCHAR (20)     NULL,
    [WellNumber]                 VARCHAR (20)     NULL,
    [CompletionNumber]           VARCHAR (20)     NULL,
    [WellName]                   VARCHAR (60)     NULL,
    [CompletionName]             VARCHAR (60)     NULL,
    [WellPlusCompletionName]     VARCHAR (120)    NULL,
    [CompletionType]             INT              NULL,
    [UnitsTypeFlag]              INT              NULL,
    [UnitsConfigurableFlag]      INT              NULL,
    [DataEditStartDate]          DATETIME         NULL,
    [ProducingStatus]            INT              NULL,
    [LastStatusChangedDate]      DATETIME         NULL,
    [ProducingMethod]            INT              NULL,
    [OutsideOperatedFlag]        INT              NULL,
    [DirectionalSurveyReference] VARCHAR (200)    NULL,
    [WellBoreDiagramReference]   VARCHAR (200)    NULL,
    [LastProducingStatus]        INT              NULL,
    [LastProducingMethod]        INT              NULL,
    [AllocationTypeFlag]         INT              NULL,
    [AllocationTypeStartDate]    DATETIME         NULL,
    [AllocMonthlyDailyFlag]      INT              NULL,
    [AllocProductDependence]     INT              NULL,
    [AllocAutoFlag]              INT              NULL,
    [AllocAutoStartDate]         DATETIME         NULL,
    [ParameterTemplateID]        INT              NULL,
    [ComputeFactorFlag]          INT              NULL,
    [GasProductionFactorFlag]    INT              NULL,
    [CommingledType]             INT              NULL,
    [CompletionStatus]           INT              NULL,
    [CompletionFluidType]        INT              NULL,
    [CompletionFlowDirection]    INT              NULL,
    [RegsReservoirId]            INT              NULL,
    [MPSCNumber]                 VARCHAR (20)     NULL,
    [PRUNumber]                  VARCHAR (20)     NULL,
    [PetroRegsId]                VARCHAR (15)     NULL,
    [RioID]                      VARCHAR (10)     NULL,
    [RioProdID]                  VARCHAR (40)     NULL,
    [RioInterfaceFlag]           INT              NULL,
    [RioProdInterfaceFlag]       INT              NULL,
    [IHSID]                      VARCHAR (50)     NULL,
    [SplitStreamFlag]            INT              NULL,
    [CarryForwardFlag]           INT              NULL,
    [ValidationDaysBack]         INT              NULL,
    [ApiWellNumber]              VARCHAR (15)     NULL,
    [ApiCompletionNumber]        VARCHAR (3)      NULL,
    [DateCompleted]              DATETIME         NULL,
    [DateOfInitialProductionOil] DATETIME         NULL,
    [DateOfInitialProductionGas] DATETIME         NULL,
    [FirstOilSales]              DATETIME         NULL,
    [FirstGasSales]              DATETIME         NULL,
    [DateShutIn]                 DATETIME         NULL,
    [DateWellSold]               DATETIME         NULL,
    [SalesCode]                  INT              NULL,
    [DateWellAcquired]           DATETIME         NULL,
    [AcquisitionCode]            INT              NULL,
    [DateAbandoned]              DATETIME         NULL,
    [ReserveCatagory]            INT              NULL,
    [Partnership]                INT              NULL,
    [ProrationMeter]             INT              NULL,
    [GasAnalysisSourceID]        INT              NULL,
    [GasAnalysisSourceType]      INT              NULL,
    [OffshoreFlag]               INT              NULL,
    [FromDepth]                  FLOAT (53)       NULL,
    [ToDepth]                    FLOAT (53)       NULL,
    [SecondFromDepth]            FLOAT (53)       NULL,
    [SecondToDepth]              FLOAT (53)       NULL,
    [ThirdFromDepth]             FLOAT (53)       NULL,
    [ThirdToDepth]               FLOAT (53)       NULL,
    [PackerDepth]                FLOAT (53)       NULL,
    [WaterDepth]                 FLOAT (53)       NULL,
    [KellyBushingLevel]          FLOAT (53)       NULL,
    [Acreage]                    FLOAT (53)       NULL,
    [RigReleaseDate]             DATETIME         NULL,
    [ProjectNumber]              VARCHAR (20)     NULL,
    [OperatorWellID]             VARCHAR (20)     NULL,
    [GatheringSystemID]          INT              NULL,
    [InjectionGatheringSystemID] INT              NULL,
    [RouteID]                    INT              NULL,
    [CommingledDescription]      VARCHAR (40)     NULL,
    [LandPropertyName]           VARCHAR (40)     NULL,
    [RevenuePropertyName]        VARCHAR (40)     NULL,
    [AccountingPropertyName]     VARCHAR (40)     NULL,
    [JIBPropertyName]            VARCHAR (40)     NULL,
    [CostCenter]                 VARCHAR (20)     NULL,
    [DirectionalWellFlag]        INT              NULL,
    [TIKOilSalesFlag]            INT              NULL,
    [TIKGasSalesFlag]            INT              NULL,
    [GasBalancingFlag]           INT              NULL,
    [NormalHandlingOnTaxFlag]    INT              NULL,
    [InsuranceCountFlag]         INT              NULL,
    [ReservesCountFlag]          INT              NULL,
    [StripperQualifiedWellFlag]  INT              NULL,
    [StateProdTaxReliefQualFlag] INT              NULL,
    [TaxCreditQualifiedFlag]     INT              NULL,
    [MarginalWellFlag]           INT              NULL,
    [AverageJointLength]         FLOAT (53)       NULL,
    [StrokeLine]                 FLOAT (53)       NULL,
    [Latitude]                   VARCHAR (12)     NULL,
    [Longitude]                  VARCHAR (12)     NULL,
    [MapCoordinateX]             FLOAT (53)       NULL,
    [MapCoordinateY]             FLOAT (53)       NULL,
    [UWI]                        VARCHAR (30)     NULL,
    [UWIDisplay]                 VARCHAR (30)     NULL,
    [UWISurface]                 VARCHAR (30)     NULL,
    [UWISurfaceDisplay]          VARCHAR (30)     NULL,
    [UWIType]                    INT              NULL,
    [UltimateReservesOil]        FLOAT (53)       NULL,
    [UltimateReservesGas]        FLOAT (53)       NULL,
    [UltimateReservesWater]      FLOAT (53)       NULL,
    [CumulativeStartMonth]       DATETIME         NULL,
    [LastProductionDate]         DATETIME         NULL,
    [ProductionActiveFlag]       INT              NULL,
    [LastTestDate]               DATETIME         NULL,
    [LastTestOil]                FLOAT (53)       NULL,
    [LastTestGas]                FLOAT (53)       NULL,
    [LastTestWater]              FLOAT (53)       NULL,
    [AccountingTeamID]           INT              NULL,
    [DrillingTeamID]             INT              NULL,
    [ProductionTeamID]           INT              NULL,
    [GroupID]                    INT              NULL,
    [DivisionID]                 INT              NULL,
    [FieldGroupID]               INT              NULL,
    [AreaID]                     INT              NULL,
    [PlatformID]                 INT              NULL,
    [BatteryID]                  INT              NULL,
    [LeaseID]                    INT              NULL,
    [PlantID]                    INT              NULL,
    [DDAID]                      INT              NULL,
    [StateID]                    INT              NULL,
    [CountyID]                   INT              NULL,
    [CountryID]                  INT              NULL,
    [AllocationGroupID]          INT              NULL,
    [FormationID]                INT              NULL,
    [ReservoirID]                INT              NULL,
    [UnitID]                     INT              NULL,
    [SuperPersonID]              INT              NULL,
    [ForemanPersonID]            INT              NULL,
    [PumperPersonID]             INT              NULL,
    [EngineerPersonID]           INT              NULL,
    [AccountantPersonID]         INT              NULL,
    [ReserveAuditorID]           INT              NULL,
    [OperatorEntityID]           INT              NULL,
    [OperatorEntityLoc]          INT              NULL,
    [AccountingID]               VARCHAR (30)     NULL,
    [ProductionID]               VARCHAR (30)     NULL,
    [EngineeringID]              VARCHAR (30)     NULL,
    [ScadaID]                    VARCHAR (30)     NULL,
    [AccountingUploadFlag]       INT              NULL,
    [EngineeringUploadFlag]      INT              NULL,
    [WellViewID]                 VARCHAR (40)     NULL,
    [ReportProductionFlag]       INT              NULL,
    [ReportAccountingFlag]       INT              NULL,
    [ReportManagementFlag]       INT              NULL,
    [ReportDrillingFlag]         INT              NULL,
    [ReportDeliverabilityFlag]   INT              NULL,
    [AllocationDailyComment]     VARCHAR (500)    NULL,
    [AllocationMonthlyComment]   VARCHAR (500)    NULL,
    [SetupComments]              VARCHAR (500)    NULL,
    [PumperInstructions]         VARCHAR (2500)   NULL,
    [SealRequiredFlag]           INT              NULL,
    [ActiveFlag]                 INT              NULL,
    [StartActiveDate]            DATETIME         NULL,
    [EndActiveDate]              DATETIME         NULL,
    [HoursOnTotal24Flag]         INT              NULL,
    [HoursOnDefaultFlag]         INT              NULL,
    [TemplateRecordFlag]         INT              NULL,
    [TemplateRecordUsed]         INT              NULL,
    [SIGasVolConversion]         FLOAT (53)       NULL,
    [AllocationRunTwiceDaily]    INT              NULL,
    [AllocationRunTwiceMonthly]  INT              NULL,
    [UserNumber1]                FLOAT (53)       NULL,
    [UserNumber1Label]           VARCHAR (30)     NULL,
    [UserNumber2]                FLOAT (53)       NULL,
    [UserNumber2Label]           VARCHAR (30)     NULL,
    [UserNumber3]                FLOAT (53)       NULL,
    [UserNumber3Label]           VARCHAR (30)     NULL,
    [UserNumber4]                FLOAT (53)       NULL,
    [UserNumber4Label]           VARCHAR (30)     NULL,
    [UserNumber5]                FLOAT (53)       NULL,
    [UserNumber5Label]           VARCHAR (30)     NULL,
    [UserNumber6]                FLOAT (53)       NULL,
    [UserNumber6Label]           VARCHAR (30)     NULL,
    [UserStringA]                VARCHAR (100)    NULL,
    [UserStringALabel]           VARCHAR (30)     NULL,
    [UserStringB]                VARCHAR (100)    NULL,
    [UserStringBLabel]           VARCHAR (30)     NULL,
    [UserStringC]                VARCHAR (100)    NULL,
    [UserStringCLabel]           VARCHAR (30)     NULL,
    [UserStringD]                VARCHAR (100)    NULL,
    [UserStringDLabel]           VARCHAR (30)     NULL,
    [UserStringE]                VARCHAR (100)    NULL,
    [UserStringELabel]           VARCHAR (30)     NULL,
    [UserStringF]                VARCHAR (100)    NULL,
    [UserStringFLabel]           VARCHAR (30)     NULL,
    [UserDailyNumber1Label]      VARCHAR (30)     NULL,
    [UserDailyNumber2Label]      VARCHAR (30)     NULL,
    [UserDailyNumber3Label]      VARCHAR (30)     NULL,
    [UserDailyNumber4Label]      VARCHAR (30)     NULL,
    [UserDailyNumber5Label]      VARCHAR (30)     NULL,
    [UserDailyNumber6Label]      VARCHAR (30)     NULL,
    [UserDailyStringALabel]      VARCHAR (30)     NULL,
    [UserDailyStringBLabel]      VARCHAR (30)     NULL,
    [StateFilingFlag]            INT              NULL,
    [StateFilingID]              VARCHAR (20)     NULL,
    [StateWellNumber]            VARCHAR (20)     NULL,
    [StateProducingZone]         VARCHAR (20)     NULL,
    [StateDistrictNumber]        VARCHAR (20)     NULL,
    [StatePropertyCode]          VARCHAR (20)     NULL,
    [StateAPIWellNumber]         VARCHAR (14)     NULL,
    [StateLeaseName]             VARCHAR (40)     NULL,
    [RegulatoryFieldID]          INT              NULL,
    [RegulatoryProductType]      INT              NULL,
    [MMSFilingFlag]              INT              NULL,
    [MMSProducingInterval]       VARCHAR (5)      NULL,
    [MMSAPIWellNumber]           VARCHAR (14)     NULL,
    [MMSLeaseNumber]             VARCHAR (26)     NULL,
    [MMSWellName]                VARCHAR (30)     NULL,
    [RegulatoryCompletion]       VARCHAR (10)     NULL,
    [UICNumber]                  VARCHAR (30)     NULL,
    [ComminglingNumber]          VARCHAR (30)     NULL,
    [LUWCode]                    VARCHAR (30)     NULL,
    [TempStringForReports1]      VARCHAR (50)     NULL,
    [PrintFlag]                  INT              NULL,
    [DateTimeStamp]              DATETIME         NULL,
    [DeleteFlag]                 INT              NULL,
    [SystemMessage]              VARCHAR (80)     NULL,
    [CleanupDateStamp]           DATETIME         NULL,
    [CleanupTimeStamp]           CHAR (8)         NULL,
    [LastTransmission]           INT              NULL,
    [LastLoadDate]               DATETIME         NULL,
    [LastLoadTime]               CHAR (8)         NULL,
    [TransmitFlag]               INT              NULL,
    [RecordCreationDate]         DATETIME         NULL,
    [BLogicDateStamp]            DATETIME         NULL,
    [BLogicTimeStamp]            CHAR (8)         NULL,
    [UserDateStamp]              DATETIME         NULL,
    [UserTimeStamp]              CHAR (8)         NULL,
    [UserID]                     INT              NULL,
    [ComputeLoadFluid]           INT              NOT NULL,
    [CalculationStatusFlag]      INT              NOT NULL,
    [LocationMerrickID]          INT              NULL,
    [LocationOrder]              INT              NULL,
    [FacilityID]                 INT              NULL,
    [AccountingShortName]        VARCHAR (30)     NULL,
    [DataSourceCode]             INT              NULL,
    [LoadFluidSourceType]        INT              NULL,
    [LoadFluidSourceID]          INT              NULL,
    [RowUID]                     UNIQUEIDENTIFIER NOT NULL,
    [ComputeNetGasFlag]          INT              NOT NULL
);

