CREATE TABLE [Aries].[AC_PROPERTY] (
    [DBSKEY]             VARCHAR (12)  NOT NULL,
    [PROPNUM]            VARCHAR (12)  NOT NULL,
    [SEQNUM]             SMALLINT      NULL,
    [LEASE]              VARCHAR (50)  NULL,
    [PRIOR_YR_LEASE]     VARCHAR (255) NULL,
    [WELL_NO]            VARCHAR (30)  NULL,
    [CLASS]              VARCHAR (8)   NULL,
    [RSV_CAT]            VARCHAR (8)   NULL,
    [REVISION]           VARCHAR (255) NULL,
    [REV_REMARK]         VARCHAR (255) NULL,
    [TYPE]               VARCHAR (50)  NULL,
    [ASSET]              VARCHAR (50)  NULL,
    [FIELD]              VARCHAR (76)  NULL,
    [RESERVOIR]          VARCHAR (40)  NULL,
    [OPERATOR]           VARCHAR (48)  NULL,
    [OPERATED]           VARCHAR (255) NULL,
    [COUNTY]             VARCHAR (40)  NULL,
    [STATE]              VARCHAR (4)   NULL,
    [MAJOR]              VARCHAR (8)   NULL,
    [API]                VARCHAR (34)  NULL,
    [LOCATION]           VARCHAR (30)  NULL,
    [SECTION]            VARCHAR (255) NULL,
    [TWN]                VARCHAR (255) NULL,
    [RNG]                VARCHAR (255) NULL,
    [FIRST_PROD]         DATETIME      NULL,
    [LAST_PROD]          DATETIME      NULL,
    [PRIOR_OIL]          FLOAT (53)    NULL,
    [PRIOR_GAS]          FLOAT (53)    NULL,
    [PRIOR_WTR]          FLOAT (53)    NULL,
    [TD]                 VARCHAR (5)   NULL,
    [STATUS]             VARCHAR (12)  NULL,
    [LATITUDE]           FLOAT (53)    NULL,
    [LONGITUDE]          FLOAT (53)    NULL,
    [UNIQUEID]           VARCHAR (40)  NULL,
    [GASGATH]            VARCHAR (25)  NULL,
    [GASPURCHASER]       VARCHAR (255) NULL,
    [LATERAL_LENGTH]     INT           NULL,
    [NS_TCGROUP]         VARCHAR (255) NULL,
    [GIS_NUM]            VARCHAR (50)  NULL,
    [DDA_POOL]           VARCHAR (255) NULL,
    [START_DATE]         DATETIME      NULL,
    [BOLO_ID]            FLOAT (53)    NULL,
    [BOOK_DATE]          VARCHAR (255) NULL,
    [WI]                 FLOAT (53)    NULL,
    [NRI]                FLOAT (53)    NULL,
    [REVERSION]          VARCHAR (255) NULL,
    [WI_REV]             FLOAT (53)    NULL,
    [NRI_REV]            FLOAT (53)    NULL,
    [ENTITY_ID]          VARCHAR (34)  NULL,
    [ACQ_YR]             VARCHAR (255) NULL,
    [SOLD_YR]            VARCHAR (255) NULL,
    [PA_YR]              VARCHAR (255) NULL,
    [AFE_NUM]            INT           NULL,
    [PRIOR_YR_RSV_CAT]   VARCHAR (255) NULL,
    [NSAI_LEASE]         VARCHAR (50)  NULL,
    [TPC_TC_AREA]        VARCHAR (255) NULL,
    [FCST_DATE]          DATETIME      NULL,
    [LL_NEW]             INT           NULL,
    [LL_MUL]             FLOAT (53)    NULL,
    [PAD_NAME]           VARCHAR (255) NULL,
    [SPUD_DATE]          DATETIME      NULL,
    [COMPL_DATE]         DATETIME      NULL,
    [REPORT_GRP]         VARCHAR (255) NULL,
    [CATEGORY]           VARCHAR (255) NULL,
    [SOUR_GAS]           VARCHAR (50)  NULL,
    [AREA]               VARCHAR (50)  NULL,
    [NSAI_RSV_CAT]       VARCHAR (50)  NULL,
    [ENERSIGHT_NAME]     VARCHAR (50)  NULL,
    [FINANCE_GRP_NAME]   VARCHAR (50)  NULL,
    [ENERSIGHT_FACILITY] VARCHAR (50)  NULL,
    CONSTRAINT [AC_PROPERTY_PRIMARY_KEY] PRIMARY KEY CLUSTERED ([DBSKEY] ASC, [PROPNUM] ASC)
);

