CREATE TABLE [CSV].[WellHeader] (
    [Id]                                    INT           NULL,
    [API Number]                            VARCHAR (40)  NULL,
    [Well Name]                             VARCHAR (120) NULL,
    [Texas District]                        VARCHAR (MAX) NULL,
    [Lease Name]                            VARCHAR (94)  NULL,
    [Lease Number]                          INT           NULL,
    [Number of Wells in Lease]              SMALLINT      NULL,
    [Formation]                             VARCHAR (132) NULL,
    [Field]                                 VARCHAR (112) NULL,
    [Well Direction]                        VARCHAR (22)  NULL,
    [Well Type]                             VARCHAR (38)  NULL,
    [Spud Date]                             DATETIME2 (7) NULL,
    [Completion Date]                       DATETIME      NULL,
    [Initial Test Date]                     DATETIME      NULL,
    [Production Start Date]                 DATETIME      NULL,
    [Peak Production Date]                  DATETIME      NULL,
    [Permit Issue Date]                     DATETIME      NULL,
    [Last Production Date]                  DATETIME      NULL,
    [Refracturing Date]                     DATETIME      NULL,
    [Well Status]                           VARCHAR (32)  NULL,
    [Last Update Date]                      DATETIME      NULL,
    [Frac Focus Version]                    VARCHAR (32)  NULL,
    [Pad ID]                                VARCHAR (18)  NULL,
    [Reported Production Months]            SMALLINT      NULL,
    [Reported Well Type]                    VARCHAR (44)  NULL,
    [First Record Date]                     DATETIME      NULL,
    [Number of Casing Strings Group]        VARCHAR (20)  NULL,
    [Number of Casing Strings Category]     VARCHAR (40)  NULL,
    [Pad State]                             VARCHAR (30)  NULL,
    [Parent Child Classification]           VARCHAR (32)  NULL,
    [Pad Sequence Completion]               SMALLINT      NULL,
    [Pad Segment Completion]                SMALLINT      NULL,
    [Pad Sequence Spud]                     SMALLINT      NULL,
    [Pad Segment Spud]                      SMALLINT      NULL,
    [Land Type]                             VARCHAR (14)  NULL,
    [Choke Size]                            VARCHAR (MAX) NULL,
    [Well Spacing]                          REAL          NULL,
    [Longitude]                             REAL          NULL,
    [Latitude]                              REAL          NULL,
    [Reported 24-h Test Water Production]   REAL          NULL,
    [Reported 24-h Test Production]         REAL          NULL,
    [Maximum Treatment Pressure]            REAL          NULL,
    [Maximum Treatment Rate]                REAL          NULL,
    [Proppant (Thousand pounds)]            REAL          NULL,
    [Ground Level]                          REAL          NULL,
    [Total Measured Depth]                  REAL          NULL,
    [True Vertical Depth]                   REAL          NULL,
    [Lateral Length]                        REAL          NULL,
    [Drilling Days]                         REAL          NULL,
    [Frac Stages (Count)]                   SMALLINT      NULL,
    [BottomHole Longitude]                  REAL          NULL,
    [BottomHole Latitude]                   REAL          NULL,
    [Surface Lateral Projection]            REAL          NULL,
    [Upper Perforation]                     REAL          NULL,
    [Lower Perforation]                     REAL          NULL,
    [Perforated Length]                     REAL          NULL,
    [Distance Closest Well 2D (Feet)]       REAL          NULL,
    [Distance Closest Well 3D (Feet)]       REAL          NULL,
    [FK_NASGeography]                       SMALLINT      NULL,
    [FK_NASOperator]                        INT           NULL,
    [RE ID]                                 VARCHAR (16)  NULL,
    [Asset]                                 VARCHAR (256) NULL,
    [FK_NASDataQuality]                     SMALLINT      NULL,
    [Light Oil Content Group]               VARCHAR (54)  NULL,
    [Light Oil Content Category]            VARCHAR (50)  NULL,
    [Light Oil Content Detail]              VARCHAR (50)  NULL,
    [Initial Production Group]              VARCHAR (48)  NULL,
    [Initial Production Category]           VARCHAR (48)  NULL,
    [Initial Production Detail]             VARCHAR (48)  NULL,
    [FK_NASREAnalysis]                      SMALLINT      NULL,
    [Spud Date Reporting Group]             VARCHAR (38)  NULL,
    [Completion Date Reporting Group]       VARCHAR (50)  NULL,
    [Production Start Date Reporting Group] VARCHAR (62)  NULL,
    [TVD Group]                             VARCHAR (54)  NULL,
    [TVD Category]                          VARCHAR (50)  NULL,
    [TVD Detail]                            VARCHAR (50)  NULL,
    [Well Origin]                           VARCHAR (36)  NULL,
    [TMD Group]                             VARCHAR (72)  NULL,
    [TMD Category]                          VARCHAR (50)  NULL,
    [TMD Detail]                            VARCHAR (50)  NULL,
    [Lateral Length Group]                  VARCHAR (70)  NULL,
    [Lateral Length Category]               VARCHAR (58)  NULL,
    [Lateral Length Detail]                 VARCHAR (58)  NULL,
    [Service Provider]                      VARCHAR (60)  NULL,
    [Service Provider Confidence]           VARCHAR (34)  NULL,
    [Initial Light Oil Content Group]       VARCHAR (54)  NULL,
    [Initial Light Oil Content Category]    VARCHAR (50)  NULL,
    [Initial Light Oil Content Detail]      VARCHAR (50)  NULL,
    [FK_NASBreakevenOilPrice]               SMALLINT      NULL,
    [FK_NASBreakevenGasPrice]               SMALLINT      NULL,
    [API Group]                             VARCHAR (42)  NULL,
    [API Category]                          VARCHAR (38)  NULL,
    [API Detail]                            VARCHAR (38)  NULL,
    [Gas Gatherer]                          VARCHAR (90)  NULL,
    [Liquids Gatherer]                      VARCHAR (90)  NULL,
    [Proppant Type Group]                   VARCHAR (50)  NULL,
    [Proppant Type Category]                VARCHAR (64)  NULL,
    [Proppant Type Detail]                  VARCHAR (422) NULL,
    [Life Cycle Group]                      VARCHAR (26)  NULL,
    [Life Cycle Category]                   VARCHAR (52)  NULL,
    [Life Cycle Detail]                     VARCHAR (56)  NULL,
    [Acreage Grade Group]                   VARCHAR (24)  NULL,
    [Acreage Grade Category]                VARCHAR (24)  NULL,
    [Acreage Grade Detail]                  VARCHAR (24)  NULL,
    [Frac Job Type Group]                   VARCHAR (20)  NULL,
    [Frac Job Type Category]                VARCHAR (104) NULL,
    [Frac Job Type Detail]                  VARCHAR (182) NULL,
    [Proppant Intensity Group]              VARCHAR (32)  NULL,
    [Proppant Intensity Category]           VARCHAR (32)  NULL,
    [Proppant Intensity Detail]             VARCHAR (32)  NULL,
    [Fluid Intensity Group]                 VARCHAR (24)  NULL,
    [Fluid Intensity Category]              VARCHAR (24)  NULL,
    [Fluid Intensity Detail]                VARCHAR (26)  NULL,
    [FK_NASLocation]                        INT           NULL,
    [Distance 3D Group]                     VARCHAR (24)  NULL,
    [Distance 3D Category]                  VARCHAR (24)  NULL,
    [Distance 3D Detail]                    VARCHAR (28)  NULL,
    [TellurianUpdatedDate]                  DATETIME      DEFAULT (getdate()) NULL,
    [TellurianCreatedDate]                  DATETIME      DEFAULT (getdate()) NULL
);

