CREATE TABLE [StagePEAK_DW].[LOS_GRP_INCL_ACCTS] (
    [u2_id]       VARCHAR (255) NULL,
    [CAT]         VARCHAR (8)   NULL,
    [DESCRIPTION] VARCHAR (93)  NULL,
    [SUB_CAT]     VARCHAR (8)   NULL,
    [COMPANIES]   VARCHAR (3)   NULL,
    [ACCTS]       VARCHAR (12)  NULL
);

