CREATE TABLE [welland].[DATABASECHANGELOG] (
    [ID]            VARCHAR (255) NOT NULL,
    [AUTHOR]        VARCHAR (255) NOT NULL,
    [FILENAME]      VARCHAR (255) NOT NULL,
    [DATEEXECUTED]  DATETIME      NOT NULL,
    [ORDEREXECUTED] INT           NOT NULL,
    [EXECTYPE]      VARCHAR (10)  NOT NULL,
    [MD5SUM]        VARCHAR (35)  NULL,
    [DESCRIPTION]   VARCHAR (255) NULL,
    [COMMENTS]      VARCHAR (255) NULL,
    [TAG]           VARCHAR (255) NULL,
    [LIQUIBASE]     VARCHAR (20)  NULL,
    [CONTEXTS]      VARCHAR (255) NULL,
    [LABELS]        VARCHAR (255) NULL,
    [DEPLOYMENT_ID] VARCHAR (10)  NULL
);

