CREATE TABLE [dbo].[ACC_OG_SALE] (
    [u2_id]              VARCHAR (255)   NOT NULL,
    [AGENCY_NET]         NUMERIC (19, 2) NULL,
    [AGENCY_SALE]        NUMERIC (19, 2) NULL,
    [AGENCY_SALE_VOL1]   NUMERIC (19, 2) NULL,
    [AGENCY_SALE_VOL2]   NUMERIC (19, 2) NULL,
    [APP]                VARCHAR (8)     NULL,
    [BTU_FACTOR]         NUMERIC (19, 4) NULL,
    [CALC_AGENCY_NET]    NUMERIC (19, 2) NULL,
    [CALC_CASH_AMT_RECD] NUMERIC (19, 2) NULL,
    [CALC_GROSS_NET]     NUMERIC (19, 2) NULL,
    [CASH_ACCTG_PERIOD]  DATETIME        NULL,
    [CASH_AMT_RECD]      NUMERIC (19, 2) NULL,
    [CLRG_AMT]           NUMERIC (19, 2) NULL,
    [COMPANY]            VARCHAR (4)     NULL,
    [CONTRACT]           VARCHAR (8)     NULL,
    [CONTRA_SALE_ID]     VARCHAR (7)     NULL,
    [COST_CENTER]        VARCHAR (8)     NULL,
    [DIV_ID]             VARCHAR (6)     NULL,
    [DIV_SESSION]        VARCHAR (4)     NULL,
    [ERR_STATUS]         VARCHAR (5)     NULL,
    [GRAVITY]            NUMERIC (19, 2) NULL,
    [GROSS_NET]          NUMERIC (19, 2) NULL,
    [GROSS_SALE]         NUMERIC (19, 2) NULL,
    [GROSS_SALE_VOL1]    NUMERIC (19, 2) NULL,
    [GROSS_SALE_VOL2]    NUMERIC (19, 2) NULL,
    [MEAS_PT]            VARCHAR (14)    NULL,
    [MKT_VOL_ID]         VARCHAR (16)    NULL,
    [PRESSURE_BASE]      NUMERIC (19, 2) NULL,
    [PRICE1]             NUMERIC (19, 5) NULL,
    [PRICE2]             NUMERIC (19, 5) NULL,
    [PRICE_REF]          VARCHAR (6)     NULL,
    [PRODUCT]            VARCHAR (3)     NULL,
    [PURCHASER]          VARCHAR (8)     NULL,
    [REACCRUAL_FLAG]     VARCHAR (9)     NULL,
    [REMITTER]           VARCHAR (8)     NULL,
    [REVERSAL_FLAG]      VARCHAR (3)     NULL,
    [SALE_ACCTG_PERIOD]  DATETIME        NULL,
    [SALE_DATE]          DATETIME        NULL,
    [SALE_TYPE]          VARCHAR (4)     NULL,
    [STATUS]             VARCHAR (2)     NULL,
    [SYSTEM_DATE]        DATETIME        NULL,
    [SYSTEM_TIME]        VARCHAR (8)     NULL,
    [SYSTEM_USER_ID]     VARCHAR (6)     NULL,
    [VOL1_88S]           NUMERIC (19, 2) NULL,
    [VOUCHER]            VARCHAR (12)    NULL,
    [time_stamp]         DATETIME        NULL,
    [u2_checksum]        VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

