CREATE TABLE [dbo].[ACC_OWNER_SALE_TRANS] (
    [subValueId]            VARCHAR (255) NOT NULL,
    [ACC_OWNER_SALE_CPT_ID] VARCHAR (255) NULL,
    [CUTBACK_VOUCHERS]      VARCHAR (15)  NULL,
    [TRANS_DATES]           DATETIME      NULL,
    [TRANS_INDEX]           VARCHAR (9)   NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ACC_OWNER_ACC_OWNER_3769]
    ON [dbo].[ACC_OWNER_SALE_TRANS]([ACC_OWNER_SALE_CPT_ID] ASC);

