CREATE TABLE [dbo].[ACC_OG_SALE_CPT] (
    [ACC_OG_SALE_CPT_ID] VARCHAR (255)   NOT NULL,
    [u2_id]              VARCHAR (255)   NULL,
    [AGENCY_CPT_AMTS]    NUMERIC (19, 2) NULL,
    [CPTS]               VARCHAR (6)     NULL,
    [CPT_DISPS]          VARCHAR (4)     NULL,
    [CPT_ENTERED_FLAGS]  VARCHAR (7)     NULL,
    [CPT_MMBTU_RATES]    NUMERIC (19, 5) NULL,
    [CPT_RATES]          NUMERIC (19, 6) NULL,
    [EXEMPT_INTEREST]    NUMERIC (19, 8) NULL,
    [GROSS_CPT_AMTS]     NUMERIC (19, 2) NULL,
    [TAXABLE_VALUE]      NUMERIC (19, 2) NULL,
    [time_stamp]         DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([ACC_OG_SALE_CPT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ACC_OG_SALE_CPT_u2_id_in]
    ON [dbo].[ACC_OG_SALE_CPT]([u2_id] ASC);

