CREATE TABLE [dbo].[ACC_OG_SALE_ACC_OS_IDX] (
    [ACC_OG_SALE_ACC_OS_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                     VARCHAR (255) NULL,
    [ACC_OWNER_SALE_INDEX]      VARCHAR (10)  NULL,
    [time_stamp]                DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([ACC_OG_SALE_ACC_OS_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ACC_OG_SA_u2_id_4515]
    ON [dbo].[ACC_OG_SALE_ACC_OS_IDX]([u2_id] ASC);

