CREATE TABLE [dbo].[ACC_OG_SALE_CTL_TRANS_IDX] (
    [ACC_OG_SALE_CTL_TRANS_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                        VARCHAR (255) NULL,
    [TRANS_INDEX]                  VARCHAR (9)   NULL,
    [time_stamp]                   DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([ACC_OG_SALE_CTL_TRANS_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ACC_OG_SA_u2_id_64022]
    ON [dbo].[ACC_OG_SALE_CTL_TRANS_IDX]([u2_id] ASC);

