CREATE TABLE [dbo].[ACCTG_PERIOD_PROC_CYC] (
    [ACCTG_PERIOD_PROC_CYC_ID] VARCHAR (255) NOT NULL,
    [u2_id]                    VARCHAR (255) NULL,
    [PROCESS_CYCLES]           VARCHAR (5)   NULL,
    [time_stamp]               DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([ACCTG_PERIOD_PROC_CYC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ACCTG_PERIOD_PROC_CYC_u2_id_in]
    ON [dbo].[ACCTG_PERIOD_PROC_CYC]([u2_id] ASC);

