CREATE TABLE [dbo].[AFE_TYPE_CC_TYPE] (
    [AFE_TYPE_CC_TYPE_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [COST_CENTER_TYPES]   VARCHAR (6)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AFE_TYPE_CC_TYPE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AFE_TYPE_CC_TYPE_u2_id_in]
    ON [dbo].[AFE_TYPE_CC_TYPE]([u2_id] ASC);

