CREATE TABLE [dbo].[AFE_PROF_RECLASS_CD] (
    [AFE_PROF_RECLASS_CD_ID] VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [VALID_RECLASS_CODES]    VARCHAR (7)   NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AFE_PROF_RECLASS_CD_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AFE_PROF_RECLASS_CD_u2_id_in]
    ON [dbo].[AFE_PROF_RECLASS_CD]([u2_id] ASC);

