CREATE TABLE [dbo].[AGENCY_DISP_TEMPLATE_DYN_DATA] (
    [AGENCY_DISP_TEMPLATE_DYN_DATA_ID] VARCHAR (255) NOT NULL,
    [u2_id]                            VARCHAR (255) NULL,
    [DYNAMIC_DATA_FIELDS]              VARCHAR (12)  NULL,
    [time_stamp]                       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AGENCY_DISP_TEMPLATE_DYN_DATA_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AGENCY_DI_u2_id_10079]
    ON [dbo].[AGENCY_DISP_TEMPLATE_DYN_DATA]([u2_id] ASC);

