CREATE TABLE [dbo].[ANALYST_SELECT_PRODUCT] (
    [ANALYST_SELECT_PRODUCT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                     VARCHAR (255) NULL,
    [PRODUCT]                   VARCHAR (3)   NULL,
    [time_stamp]                DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([ANALYST_SELECT_PRODUCT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ANALYST_S_u2_id_20871]
    ON [dbo].[ANALYST_SELECT_PRODUCT]([u2_id] ASC);

