CREATE TABLE [dbo].[ANALYST_SELECT_BASIN] (
    [ANALYST_SELECT_BASIN_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [BASIN]                   VARCHAR (10)  NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([ANALYST_SELECT_BASIN_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ANALYST_SELECT_BASIN_u2_id_in]
    ON [dbo].[ANALYST_SELECT_BASIN]([u2_id] ASC);

