CREATE TABLE [dbo].[ANALYST_SELECT_WELL] (
    [ANALYST_SELECT_WELL_ID] VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [WELL]                   VARCHAR (10)  NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([ANALYST_SELECT_WELL_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ANALYST_SELECT_WELL_u2_id_in]
    ON [dbo].[ANALYST_SELECT_WELL]([u2_id] ASC);

