CREATE TABLE [dbo].[ANALYST_SELECT_GATHERING_SYSTEM] (
    [ANALYST_SELECT_GATHERING_SYSTEM_ID] VARCHAR (255) NOT NULL,
    [u2_id]                              VARCHAR (255) NULL,
    [GATHERING_SYSTEM]                   VARCHAR (16)  NULL,
    [time_stamp]                         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([ANALYST_SELECT_GATHERING_SYSTEM_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ANALYST_S_u2_id_81891]
    ON [dbo].[ANALYST_SELECT_GATHERING_SYSTEM]([u2_id] ASC);

