CREATE TABLE [dbo].[AP_ADJ_TRANS_INDEX] (
    [AP_ADJ_TRANS_INDEX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AP_ADJ_TRANS_INDEX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AP_ADJ_TRANS_INDEX_u2_id_in]
    ON [dbo].[AP_ADJ_TRANS_INDEX]([u2_id] ASC);

