CREATE TABLE [dbo].[AP_INV_ROUTING] (
    [AP_INV_ROUTING_ID]    VARCHAR (255)  NOT NULL,
    [u2_id]                VARCHAR (255)  NULL,
    [ROUTING_PERSONS]      VARCHAR (17)   NULL,
    [ROUTING_REMARKS]      VARCHAR (1956) NULL,
    [ROUTING_REMARK_DATES] DATETIME       NULL,
    [time_stamp]           DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([AP_INV_ROUTING_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AP_INV_ROUTING_u2_id_in]
    ON [dbo].[AP_INV_ROUTING]([u2_id] ASC);

