CREATE TABLE [dbo].[AR_ADJ_OA_IDX] (
    [AR_ADJ_OA_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [OPEN_AR_INDEX]    VARCHAR (23)  NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AR_ADJ_OA_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AR_ADJ_OA_IDX_u2_id_in]
    ON [dbo].[AR_ADJ_OA_IDX]([u2_id] ASC);

