CREATE TABLE [dbo].[AR_ADJ_TRANS] (
    [AR_ADJ_TRANS_ID] VARCHAR (255) NOT NULL,
    [u2_id]           VARCHAR (255) NULL,
    [TRANS_INDEX]     VARCHAR (9)   NULL,
    [TRANS_TYPES]     VARCHAR (4)   NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AR_ADJ_TRANS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AR_ADJ_TRANS_u2_id_in]
    ON [dbo].[AR_ADJ_TRANS]([u2_id] ASC);

