CREATE TABLE [dbo].[AR_INV_CC] (
    [AR_INV_CC_ID]     VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [AR_INV_DET_INDEX] VARCHAR (5)   NULL,
    [PRICE_CTRC_INDEX] VARCHAR (8)   NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AR_INV_CC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AR_INV_CC_u2_id_in]
    ON [dbo].[AR_INV_CC]([u2_id] ASC);

