CREATE TABLE [dbo].[AR_INV_DET] (
    [u2_id]                   VARCHAR (255)   NOT NULL,
    [ACCT]                    VARCHAR (10)    NULL,
    [ACCTG_PERIOD]            DATETIME        NULL,
    [AMT]                     NUMERIC (19, 2) NULL,
    [APPLIED_AMT]             NUMERIC (19, 2) NULL,
    [APPLY_JIB]               VARCHAR (5)     NULL,
    [AR_INV_ID]               VARCHAR (23)    NULL,
    [AV_REVERSAL_FLAG]        VARCHAR (8)     NULL,
    [BAL]                     NUMERIC (19, 2) NULL,
    [BTU_FACTOR]              NUMERIC (19, 6) NULL,
    [CALC_BAL]                NUMERIC (19, 2) NULL,
    [CC_NO]                   VARCHAR (13)    NULL,
    [COMPANY]                 VARCHAR (4)     NULL,
    [CREDIT_TERMS]            VARCHAR (5)     NULL,
    [CTRC_PRICE]              NUMERIC (19, 5) NULL,
    [CUSTOMER]                VARCHAR (9)     NULL,
    [DAYS_PAST_DUE]           VARCHAR (10)    NULL,
    [DESCRIPTION]             VARCHAR (125)   NULL,
    [DISC_AMT]                NUMERIC (19, 2) NULL,
    [DUE_DATE]                DATETIME        NULL,
    [EFF_DATE]                DATETIME        NULL,
    [FOREIGN_SYSTEM_DATE]     DATETIME        NULL,
    [GRAVITY]                 NUMERIC (9, 1)  NULL,
    [GROSS_SALE]              NUMERIC (19, 2) NULL,
    [INVOICE_DATE]            DATETIME        NULL,
    [INVOICE_ID]              VARCHAR (23)    NULL,
    [INVOICE_NO]              VARCHAR (19)    NULL,
    [NON_NETTABLE_PREPAYMENT] NUMERIC (19, 2) NULL,
    [OCCUR_DATE]              DATETIME        NULL,
    [PAID_IN_FULL_PERIOD]     DATETIME        NULL,
    [PAST_DUE_1_30]           NUMERIC (9)     NULL,
    [PAST_DUE_31_60]          NUMERIC (9)     NULL,
    [PAST_DUE_61_90]          NUMERIC (9)     NULL,
    [PAST_DUE_91]             NUMERIC (9)     NULL,
    [PORT]                    VARCHAR (10)    NULL,
    [PRICE_CTRC_ID]           VARCHAR (5)     NULL,
    [PRINT_STATUS]            VARCHAR (5)     NULL,
    [PROD_VOL1]               NUMERIC (19, 2) NULL,
    [PROD_VOL2]               NUMERIC (19, 2) NULL,
    [PROD_VOL3]               NUMERIC (19, 2) NULL,
    [REVALUE_FLAG]            VARCHAR (7)     NULL,
    [SOURCE_CURRENCY]         VARCHAR (4)     NULL,
    [SYSTEM_DATE]             DATETIME        NULL,
    [SYSTEM_TIME]             VARCHAR (8)     NULL,
    [SYSTEM_USER_ID]          VARCHAR (4)     NULL,
    [TYPE]                    VARCHAR (4)     NULL,
    [UNDIST_AMT]              NUMERIC (19, 2) NULL,
    [VOUCHER]                 VARCHAR (16)    NULL,
    [time_stamp]              DATETIME        NULL,
    [u2_checksum]             VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

