CREATE TABLE [dbo].[AR_INV_DESCS] (
    [AR_INV_DESCS_ID] VARCHAR (255) NOT NULL,
    [u2_id]           VARCHAR (255) NULL,
    [DESCRIPTION]     VARCHAR (122) NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AR_INV_DESCS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AR_INV_DESCS_u2_id_in]
    ON [dbo].[AR_INV_DESCS]([u2_id] ASC);

