CREATE TABLE [dbo].[AT_DEPR_METHOD_PERSP] (
    [AT_DEPR_METHOD_PERSP_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [VALID_PERSPECTIVES]      VARCHAR (11)  NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AT_DEPR_METHOD_PERSP_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AT_DEPR_METHOD_PERSP_u2_id_in]
    ON [dbo].[AT_DEPR_METHOD_PERSP]([u2_id] ASC);

