CREATE TABLE [dbo].[AT_DDA_DET_LYR_PER] (
    [AT_DDA_DET_LYR_PER_ID]     VARCHAR (255)   NOT NULL,
    [u2_id]                     VARCHAR (255)   NULL,
    [LAYER_ACCUM_DDA_ADJ_AMTS]  NUMERIC (19, 2) NULL,
    [LAYER_BALFWD_ACCUM_DDA]    NUMERIC (19, 2) NULL,
    [LAYER_COSTS]               NUMERIC (19, 2) NULL,
    [LAYER_DEPR_CALC_CONVS]     VARCHAR (5)     NULL,
    [LAYER_FIRST_ACCTG_PERIODS] DATETIME        NULL,
    [LAYER_FIRST_DEPR_PERIODS]  DATETIME        NULL,
    [LAYER_FYES]                DATETIME        NULL,
    [LAYER_IN_SERVICE_PERIODS]  DATETIME        NULL,
    [LAYER_ITD_ACCUM_DDA]       NUMERIC (19, 2) NULL,
    [LAYER_PERIODS]             DATETIME        NULL,
    [LAYER_REMAINDER_MONTHS]    VARCHAR (9)     NULL,
    [LAYER_RETIREMENTS]         NUMERIC (19, 2) NULL,
    [time_stamp]                DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([AT_DDA_DET_LYR_PER_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AT_DDA_DET_LYR_PER_u2_id_in]
    ON [dbo].[AT_DDA_DET_LYR_PER]([u2_id] ASC);

