CREATE TABLE [dbo].[AT_MT] (
    [u2_id]                     VARCHAR (255)   NOT NULL,
    [ACCTG_PERIOD]              DATETIME        NULL,
    [ACCUM_DEPR_AMT]            NUMERIC (19, 2) NULL,
    [ACCUM_DEPR_PER_UNIT]       NUMERIC (19, 2) NULL,
    [AMOUNT_CHANGE_EXPLANATION] VARCHAR (30)    NULL,
    [AMOUNT_OVERRIDE_FLAG]      VARCHAR (8)     NULL,
    [AMT]                       NUMERIC (19, 2) NULL,
    [COMPANY]                   VARCHAR (3)     NULL,
    [COMPLETE_FLAG]             VARCHAR (8)     NULL,
    [COST]                      NUMERIC (19, 2) NULL,
    [COST_CHANGE_EXPLANATION]   VARCHAR (30)    NULL,
    [COST_PER_UNIT]             NUMERIC (19, 6) NULL,
    [DESCRIPTION]               VARCHAR (30)    NULL,
    [FMV_AMT_PER_UNIT]          NUMERIC (19, 6) NULL,
    [FROM_ACCT]                 VARCHAR (10)    NULL,
    [FROM_COST_CENTER]          VARCHAR (11)    NULL,
    [FROM_DIRECT_BILL]          VARCHAR (6)     NULL,
    [FROM_DIST_COMPANY]         VARCHAR (7)     NULL,
    [FROM_IN_SERVICE_PERIOD]    DATETIME        NULL,
    [FROM_JIB_DECK]             VARCHAR (6)     NULL,
    [FROM_JIB_DECK_SESSION]     VARCHAR (6)     NULL,
    [FROM_NET_ACCT]             VARCHAR (8)     NULL,
    [FROM_PROJECT]              VARCHAR (8)     NULL,
    [MAX_COST]                  NUMERIC (19, 2) NULL,
    [MAX_QTY1]                  NUMERIC (19, 2) NULL,
    [MAX_QTY2]                  NUMERIC (19, 2) NULL,
    [OCCUR_DATE]                DATETIME        NULL,
    [PERSPECTIVE]               VARCHAR (11)    NULL,
    [PROCEEDS]                  NUMERIC (19, 2) NULL,
    [PROCEED_CLRG_TRANS_ID]     VARCHAR (8)     NULL,
    [QTY1]                      NUMERIC (19, 2) NULL,
    [QTY2]                      NUMERIC (19, 2) NULL,
    [REVERSAL_AT_MT_ID]         VARCHAR (8)     NULL,
    [RINV_ID]                   NUMERIC (19, 6) NULL,
    [SALES_TAX_AMT]             NUMERIC (19, 2) NULL,
    [SALES_TAX_RATE]            NUMERIC (19, 4) NULL,
    [SOURCE_AT_MT_ID]           VARCHAR (8)     NULL,
    [SRC_CURR]                  VARCHAR (8)     NULL,
    [SYSTEM_DATE]               DATETIME        NULL,
    [SYSTEM_TIME]               VARCHAR (8)     NULL,
    [SYSTEM_USER_ID]            VARCHAR (6)     NULL,
    [TICKET]                    VARCHAR (15)    NULL,
    [TO_ACCT]                   VARCHAR (10)    NULL,
    [TO_COST_CENTER]            VARCHAR (11)    NULL,
    [TO_DIRECT_BILL]            VARCHAR (6)     NULL,
    [TO_DIST_COMPANY]           VARCHAR (4)     NULL,
    [TO_IN_SERVICE_PERIOD]      DATETIME        NULL,
    [TO_JIB_DECK]               VARCHAR (4)     NULL,
    [TO_JIB_DECK_SESSION]       VARCHAR (4)     NULL,
    [TO_NET_ACCT]               VARCHAR (10)    NULL,
    [TO_PROJECT]                VARCHAR (8)     NULL,
    [TYPE]                      VARCHAR (4)     NULL,
    [VOUCHER]                   VARCHAR (15)    NULL,
    [time_stamp]                DATETIME        NULL,
    [u2_checksum]               VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

