CREATE TABLE [dbo].[AT_MT_GAIN_LOSS] (
    [AT_MT_GAIN_LOSS_ID]    VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [GAIN_LOSS_TRANS_INDEX] VARCHAR (11)  NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AT_MT_GAIN_LOSS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AT_MT_GAIN_LOSS_u2_id_in]
    ON [dbo].[AT_MT_GAIN_LOSS]([u2_id] ASC);

