CREATE TABLE [dbo].[AT_RETIREMENT] (
    [u2_id]                     VARCHAR (255)   NOT NULL,
    [ACCTG_PERIOD]              DATETIME        NULL,
    [ACCUM_DEPR_AMT]            NUMERIC (19, 2) NULL,
    [ACCUM_DEPR_PER_UNIT]       NUMERIC (19, 2) NULL,
    [ACCUM_DEPR_TRANS_ID]       VARCHAR (8)     NULL,
    [ASSET]                     VARCHAR (11)    NULL,
    [ASSET_TRANS_ID]            VARCHAR (8)     NULL,
    [AT_ASSET_DET_ID]           VARCHAR (15)    NULL,
    [AT_DDA_DET_ID]             VARCHAR (13)    NULL,
    [COMPANY]                   VARCHAR (3)     NULL,
    [COMPLETE_FLAG]             VARCHAR (8)     NULL,
    [COST]                      NUMERIC (19, 2) NULL,
    [COST_PER_UNIT]             NUMERIC (19, 6) NULL,
    [DESCRIPTION]               VARCHAR (30)    NULL,
    [FROM_ACCT]                 VARCHAR (10)    NULL,
    [FROM_COST_CENTER]          VARCHAR (11)    NULL,
    [FROM_DIST_COMPANY]         VARCHAR (7)     NULL,
    [FROM_IN_SERVICE_PERIOD]    DATETIME        NULL,
    [FROM_PROJECT]              VARCHAR (8)     NULL,
    [GAIN_LOSS_TRANS_ID]        VARCHAR (11)    NULL,
    [MAX_QTY1]                  NUMERIC (19, 2) NULL,
    [NET_COST_PER_UNIT]         NUMERIC (19, 6) NULL,
    [OCCUR_DATE]                DATETIME        NULL,
    [PERSPECTIVE]               VARCHAR (5)     NULL,
    [PROCEEDS_AMT]              NUMERIC (19, 2) NULL,
    [PROCEEDS_CLRG_TRANS_ID]    VARCHAR (8)     NULL,
    [QTY1]                      NUMERIC (19, 2) NULL,
    [QTY2]                      NUMERIC (19, 2) NULL,
    [REVERSAL_AT_RETIREMENT_ID] VARCHAR (8)     NULL,
    [SOURCE_AT_ASSET_DET]       VARCHAR (12)    NULL,
    [SOURCE_AT_RETIREMENT_ID]   VARCHAR (8)     NULL,
    [SRC_CURR]                  NUMERIC (19, 2) NULL,
    [SYSTEM_DATE]               DATETIME        NULL,
    [SYSTEM_TIME]               VARCHAR (8)     NULL,
    [SYSTEM_USER_ID]            VARCHAR (6)     NULL,
    [TO_ACCT]                   VARCHAR (10)    NULL,
    [TO_COST_CENTER]            VARCHAR (11)    NULL,
    [TO_DIST_COMPANY]           VARCHAR (4)     NULL,
    [TO_IN_SERVICE_PERIOD]      DATETIME        NULL,
    [TO_PROJECT]                VARCHAR (8)     NULL,
    [TYPE]                      VARCHAR (4)     NULL,
    [VOUCHER]                   VARCHAR (15)    NULL,
    [time_stamp]                DATETIME        NULL,
    [u2_checksum]               VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

