CREATE TABLE [dbo].[AT_SYS_UOP_PROD] (
    [AT_SYS_UOP_PROD_ID]     VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [UOP_PRODUCT_CATEGORIES] VARCHAR (4)   NULL,
    [UOP_PROD_ACCT_GROUPS]   VARCHAR (12)  NULL,
    [UOP_PROD_VOL_FLAGS]     VARCHAR (4)   NULL,
    [UOP_RESERVES_ACCTS]     VARCHAR (9)   NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AT_SYS_UOP_PROD_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AT_SYS_UOP_PROD_u2_id_in]
    ON [dbo].[AT_SYS_UOP_PROD]([u2_id] ASC);

