CREATE TABLE [dbo].[AT_TRANS_ERR] (
    [AT_TRANS_ERR_ID] VARCHAR (255) NOT NULL,
    [u2_id]           VARCHAR (255) NULL,
    [ERR_FIELDS]      VARCHAR (10)  NULL,
    [ERR_MSG]         VARCHAR (30)  NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AT_TRANS_ERR_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AT_TRANS_ERR_u2_id_in]
    ON [dbo].[AT_TRANS_ERR]([u2_id] ASC);

