CREATE TABLE [dbo].[AT_TRANS_FROM_TRANS_IDX] (
    [AT_TRANS_FROM_TRANS_IDX_ID] VARCHAR (255)   NOT NULL,
    [u2_id]                      VARCHAR (255)   NULL,
    [FROM_TRANS_INDEX]           VARCHAR (9)     NULL,
    [FROM_TRANS_PCTS]            NUMERIC (19, 6) NULL,
    [time_stamp]                 DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([AT_TRANS_FROM_TRANS_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AT_TRANS__u2_id_24602]
    ON [dbo].[AT_TRANS_FROM_TRANS_IDX]([u2_id] ASC);

