CREATE TABLE [dbo].[AT_TAX_ADJ_TRANS] (
    [AT_TAX_ADJ_TRANS_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [TRANS_INDEX]         VARCHAR (9)   NULL,
    [TRANS_TYPES]         VARCHAR (5)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AT_TAX_ADJ_TRANS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AT_TAX_ADJ_TRANS_u2_id_in]
    ON [dbo].[AT_TAX_ADJ_TRANS]([u2_id] ASC);

