CREATE TABLE [dbo].[AT_TRANS_REALLOC] (
    [AT_TRANS_REALLOC_ID]    VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [REALLOC_OWNER_JIB_FLAG] VARCHAR (7)   NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AT_TRANS_REALLOC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AT_TRANS_REALLOC_u2_id_in]
    ON [dbo].[AT_TRANS_REALLOC]([u2_id] ASC);

