CREATE TABLE [dbo].[AT_TRANS_INS] (
    [AT_TRANS_INS_ID] VARCHAR (255) NOT NULL,
    [u2_id]           VARCHAR (255) NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AT_TRANS_INS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AT_TRANS_INS_u2_id_in]
    ON [dbo].[AT_TRANS_INS]([u2_id] ASC);

