CREATE TABLE [dbo].[AT_TRANS_RETIRE] (
    [AT_TRANS_RETIRE_ID]            VARCHAR (255)   NOT NULL,
    [u2_id]                         VARCHAR (255)   NULL,
    [RETIREMENT_ACCUM_DEPR_AMTS]    NUMERIC (19, 2) NULL,
    [RETIREMENT_ACCUM_DEPR_PERIODS] DATETIME        NULL,
    [time_stamp]                    DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([AT_TRANS_RETIRE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AT_TRANS_RETIRE_u2_id_in]
    ON [dbo].[AT_TRANS_RETIRE]([u2_id] ASC);

