CREATE TABLE [dbo].[AT_TRANS_RPT] (
    [AT_TRANS_RPT_ID] VARCHAR (255)   NOT NULL,
    [u2_id]           VARCHAR (255)   NULL,
    [RPT_AMT]         NUMERIC (19, 2) NULL,
    [RPT_GROSS_AMT]   NUMERIC (19, 2) NULL,
    [RPT_GROSS_QTY1]  NUMERIC (19, 2) NULL,
    [RPT_GROSS_QTY2]  NUMERIC (19, 2) NULL,
    [RPT_QTY1]        NUMERIC (19, 2) NULL,
    [RPT_QTY2]        NUMERIC (19, 2) NULL,
    [RPT_STAT1_AMT]   NUMERIC (19, 2) NULL,
    [RPT_STAT1_QTY1]  NUMERIC (19, 2) NULL,
    [RPT_STAT1_QTY2]  NUMERIC (19, 2) NULL,
    [RPT_STAT2_AMT]   NUMERIC (19, 2) NULL,
    [RPT_STAT2_QTY1]  NUMERIC (19, 2) NULL,
    [RPT_STAT2_QTY2]  NUMERIC (19, 2) NULL,
    [time_stamp]      DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([AT_TRANS_RPT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AT_TRANS_RPT_u2_id_in]
    ON [dbo].[AT_TRANS_RPT]([u2_id] ASC);

