CREATE TABLE [dbo].[AT_TRANS_TRANS_CD] (
    [AT_TRANS_TRANS_CD_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [TRANS_CODES]          VARCHAR (48)  NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AT_TRANS_TRANS_CD_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AT_TRANS_TRANS_CD_u2_id_in]
    ON [dbo].[AT_TRANS_TRANS_CD]([u2_id] ASC);

