CREATE TABLE [dbo].[AT_VOUCHER_TRANS_IDX] (
    [subValueId]             VARCHAR (255) NOT NULL,
    [AT_VOUCHER_DOC_ID]      VARCHAR (255) NULL,
    [INCOMPLETE_TRANS_FLAGS] VARCHAR (10)  NULL,
    [TRANS_INDEX]            VARCHAR (10)  NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AT_VOUCHE_AT_VOUCHE_4711]
    ON [dbo].[AT_VOUCHER_TRANS_IDX]([AT_VOUCHER_DOC_ID] ASC);

