CREATE TABLE [dbo].[AT_VOUCHER_REL_VOU] (
    [AT_VOUCHER_REL_VOU_ID] VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [RELATED_VOUCHERS]      VARCHAR (15)  NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([AT_VOUCHER_REL_VOU_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AT_VOUCHER_REL_VOU_u2_id_in]
    ON [dbo].[AT_VOUCHER_REL_VOU]([u2_id] ASC);

