CREATE TABLE [dbo].[AV_INV_CTRC] (
    [AV_INV_CTRC_ID]   VARCHAR (255)   NOT NULL,
    [u2_id]            VARCHAR (255)   NULL,
    [BTU_FACTOR]       NUMERIC (19, 6) NULL,
    [CORR_VOLUME_VOL1] NUMERIC (19, 2) NULL,
    [CORR_VOLUME_VOL2] NUMERIC (19, 2) NULL,
    [CORR_VOLUME_VOL3] NUMERIC (19, 2) NULL,
    [FINAL_CTRC_PRICE] NUMERIC (19, 5) NULL,
    [GRAVITY]          NUMERIC (9, 1)  NULL,
    [GROSS_SALE]       NUMERIC (19, 2) NULL,
    [PRICE_CTRC]       VARCHAR (10)    NULL,
    [PROD_VOLUME_VOL1] NUMERIC (19, 2) NULL,
    [PROD_VOLUME_VOL2] NUMERIC (19, 2) NULL,
    [PROD_VOLUME_VOL3] NUMERIC (19, 2) NULL,
    [REVERSAL_FLAG]    VARCHAR (3)     NULL,
    [time_stamp]       DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([AV_INV_CTRC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [AV_INV_CTRC_u2_id_in]
    ON [dbo].[AV_INV_CTRC]([u2_id] ASC);

