CREATE TABLE [dbo].[BANK_INFO_CNTCT] (
    [BANK_INFO_CNTCT_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [CONTACTS]           VARCHAR (30)  NULL,
    [CONTACT_COMMENTS]   VARCHAR (30)  NULL,
    [CONTACT_PHONES]     VARCHAR (12)  NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([BANK_INFO_CNTCT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [BANK_INFO_CNTCT_u2_id_in]
    ON [dbo].[BANK_INFO_CNTCT]([u2_id] ASC);

