CREATE TABLE [dbo].[BANK_DATA_CTL_ACCT] (
    [BANK_DATA_CTL_ACCT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [ACCOUNTS]              VARCHAR (12)  NULL,
    [LOAD_STATUS]           VARCHAR (2)   NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([BANK_DATA_CTL_ACCT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [BANK_DATA_CTL_ACCT_u2_id_in]
    ON [dbo].[BANK_DATA_CTL_ACCT]([u2_id] ASC);

