CREATE TABLE [dbo].[BANK_ACCT_POSPAY] (
    [BANK_ACCT_POSPAY_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [ACH_HEADING]         VARCHAR (40)  NULL,
    [POSPAY_FOOTING]      VARCHAR (30)  NULL,
    [POSPAY_HEADING]      VARCHAR (30)  NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([BANK_ACCT_POSPAY_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [BANK_ACCT_POSPAY_u2_id_in]
    ON [dbo].[BANK_ACCT_POSPAY]([u2_id] ASC);

