CREATE TABLE [dbo].[BDECK_ASSN_IDX] (
    [subValueId]      VARCHAR (255)   NOT NULL,
    [BDECK_ASSN_ID]   VARCHAR (255)   NULL,
    [ASSIGN_ATTRS]    VARCHAR (19)    NULL,
    [ASSIGN_INTEREST] NUMERIC (19, 8) NULL,
    [ASSIGN_OWNERS]   VARCHAR (8)     NULL,
    [time_stamp]      DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [BDECK_ASS_BDECK_ASS_44210]
    ON [dbo].[BDECK_ASSN_IDX]([BDECK_ASSN_ID] ASC);

