CREATE TABLE [dbo].[CC_ALLOC_HDR_STS] (
    [CC_ALLOC_HDR_STS_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [WELL_STATUSES]       VARCHAR (6)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CC_ALLOC_HDR_STS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CC_ALLOC_HDR_STS_u2_id_in]
    ON [dbo].[CC_ALLOC_HDR_STS]([u2_id] ASC);

