CREATE TABLE [dbo].[CC_ALLOC_HDR_EFF] (
    [CC_ALLOC_HDR_EFF_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [EFF_DATES]           DATETIME      NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CC_ALLOC_HDR_EFF_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CC_ALLOC_HDR_EFF_u2_id_in]
    ON [dbo].[CC_ALLOC_HDR_EFF]([u2_id] ASC);

