CREATE TABLE [dbo].[CC_GRP_CCS] (
    [CC_GRP_CCS_ID] VARCHAR (255) NOT NULL,
    [u2_id]         VARCHAR (255) NULL,
    [COST_CENTERS]  VARCHAR (10)  NULL,
    [time_stamp]    DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CC_GRP_CCS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CC_GRP_CCS_u2_id_in]
    ON [dbo].[CC_GRP_CCS]([u2_id] ASC);

