CREATE TABLE [dbo].[CC_HIERARCHY_DET] (
    [subValueId]            VARCHAR (255) NOT NULL,
    [CC_HIERARCHY_ID]       VARCHAR (255) NULL,
    [ROLLUP_DEFINITION_CCS] VARCHAR (11)  NULL,
    [SUBORDINATE_CCS]       VARCHAR (17)  NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CC_HIERAR_CC_HIERAR_84517]
    ON [dbo].[CC_HIERARCHY_DET]([CC_HIERARCHY_ID] ASC);

