CREATE TABLE [dbo].[CC_HIER_LVL] (
    [CC_HIER_LVL_ID] VARCHAR (255) NOT NULL,
    [u2_id]          VARCHAR (255) NULL,
    [LEVEL_INDEX]    VARCHAR (15)  NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CC_HIER_LVL_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CC_HIER_LVL_u2_id_in]
    ON [dbo].[CC_HIER_LVL]([u2_id] ASC);

