CREATE TABLE [dbo].[CC_PROD_UI_NODE] (
    [CC_PROD_UI_NODE_ID]          VARCHAR (255) NOT NULL,
    [u2_id]                       VARCHAR (255) NULL,
    [PROD_FAC_PRD_NODE_EFF_DATES] DATETIME      NULL,
    [PROD_FAC_PRD_NODE_EXP_DATES] DATETIME      NULL,
    [time_stamp]                  DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CC_PROD_UI_NODE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CC_PROD_UI_NODE_u2_id_in]
    ON [dbo].[CC_PROD_UI_NODE]([u2_id] ASC);

