CREATE TABLE [dbo].[CC_TYPE_UDF] (
    [CC_TYPE_UDF_ID]   VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [USER_DATA_FIELDS] VARCHAR (8)   NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CC_TYPE_UDF_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CC_TYPE_UDF_u2_id_in]
    ON [dbo].[CC_TYPE_UDF]([u2_id] ASC);

