CREATE TABLE [dbo].[CC_UDF] (
    [CC_UDF_ID]        VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [USER_DATA_FIELDS] VARCHAR (11)  NULL,
    [USER_DATA_VALUES] VARCHAR (22)  NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CC_UDF_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CC_UDF_u2_id_in]
    ON [dbo].[CC_UDF]([u2_id] ASC);

