CREATE TABLE [dbo].[CD_SYS] (
    [u2_id]                       VARCHAR (255) NOT NULL,
    [ADDR_OFFSET_AP]              VARCHAR (6)   NULL,
    [ADDR_OFFSET_LAND]            VARCHAR (6)   NULL,
    [ADDR_OFFSET_RV]              VARCHAR (6)   NULL,
    [ADD_FINAL_CK_FF]             VARCHAR (5)   NULL,
    [AP_CHECK_APP]                VARCHAR (11)  NULL,
    [AP_CHECK_FORM]               VARCHAR (10)  NULL,
    [AP_CHK_APP]                  VARCHAR (10)  NULL,
    [AP_CHK_VOU_SRC]              VARCHAR (7)   NULL,
    [AP_VOID_CHK_APP]             VARCHAR (10)  NULL,
    [CHECK_STUB_MESSAGE]          VARCHAR (40)  NULL,
    [JIB_NET_APP]                 VARCHAR (10)  NULL,
    [JIB_NET_VOU_SRC]             VARCHAR (7)   NULL,
    [LAND_CHK_APP]                VARCHAR (10)  NULL,
    [LAND_CHK_VOU_SRC]            VARCHAR (4)   NULL,
    [LD_VOID_CHK_APP]             VARCHAR (10)  NULL,
    [MAN_AP_CHK_APP]              VARCHAR (10)  NULL,
    [MAN_AP_CHK_VOU_SRC]          VARCHAR (7)   NULL,
    [MAN_LAND_CHK_APP]            VARCHAR (10)  NULL,
    [MAN_LAND_CHK_VOU_SRC]        VARCHAR (4)   NULL,
    [MAN_PTR_CHK_APP]             VARCHAR (11)  NULL,
    [MAN_PTR_CHK_VOU_SRC]         VARCHAR (7)   NULL,
    [MAN_REV_CHK_APP]             VARCHAR (10)  NULL,
    [MAN_REV_CHK_VOU_SRC]         VARCHAR (7)   NULL,
    [OG_CTRC_OPTION]              VARCHAR (4)   NULL,
    [OWNER_SORT_OPT]              VARCHAR (7)   NULL,
    [PTR_CHK_APP]                 VARCHAR (11)  NULL,
    [PTR_CHK_VOU_SRC]             VARCHAR (7)   NULL,
    [RENT_CHECK_FORM]             VARCHAR (10)  NULL,
    [REV_CHECK_APP]               VARCHAR (11)  NULL,
    [REV_CHK_APP]                 VARCHAR (10)  NULL,
    [REV_CHK_VOU_SRC]             VARCHAR (7)   NULL,
    [RPT_ZERO_BAL_INVS]           VARCHAR (4)   NULL,
    [RV_VOID_CHK_APP]             VARCHAR (10)  NULL,
    [SIG_AP]                      VARCHAR (3)   NULL,
    [SIG_LAND]                    VARCHAR (3)   NULL,
    [SIG_RV]                      VARCHAR (3)   NULL,
    [SUPPRESS_SHRINK_EXTRA_INFO]  VARCHAR (8)   NULL,
    [SUPPRESS_WT_FORM]            VARCHAR (4)   NULL,
    [THIRD_PARTY_AP_PRINT_FLAG]   VARCHAR (5)   NULL,
    [THIRD_PARTY_LAND_PRINT_FLAG] VARCHAR (5)   NULL,
    [THIRD_PARTY_PTR_PRINT_FLAG]  VARCHAR (5)   NULL,
    [THIRD_PARTY_REV_PRINT_FLAG]  VARCHAR (5)   NULL,
    [VOID_AP_CHK_VOU_SRC]         VARCHAR (7)   NULL,
    [VOID_LD_CHK_VOU_SRC]         VARCHAR (4)   NULL,
    [VOID_PTR_CHK_APP]            VARCHAR (11)  NULL,
    [VOID_PTR_CHK_VOU_SRC]        VARCHAR (7)   NULL,
    [VOID_RV_CHK_VOU_SRC]         VARCHAR (4)   NULL,
    [time_stamp]                  DATETIME      NULL,
    [u2_checksum]                 VARCHAR (25)  NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

