CREATE TABLE [dbo].[CDX_DETAIL_INT_TP] (
    [CDX_DETAIL_INT_TP_ID] VARCHAR (255)   NOT NULL,
    [u2_id]                VARCHAR (255)   NULL,
    [DECIMAL_FLAGS]        VARCHAR (3)     NULL,
    [INTERESTS]            NUMERIC (19, 8) NULL,
    [INTEREST_TYPES]       VARCHAR (3)     NULL,
    [time_stamp]           DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([CDX_DETAIL_INT_TP_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CDX_DETAIL_INT_TP_u2_id_in]
    ON [dbo].[CDX_DETAIL_INT_TP]([u2_id] ASC);

