CREATE TABLE [dbo].[CDX_CO_NAME] (
    [CDX_CO_NAME_ID] VARCHAR (255) NOT NULL,
    [u2_id]          VARCHAR (255) NULL,
    [NAME_IDS]       VARCHAR (9)   NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CDX_CO_NAME_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CDX_CO_NAME_u2_id_in]
    ON [dbo].[CDX_CO_NAME]([u2_id] ASC);

