CREATE TABLE [dbo].[CDX_CO_PRD_IDX] (
    [subValueId]     VARCHAR (255) NOT NULL,
    [CDX_CO_PROP_ID] VARCHAR (255) NULL,
    [PROP_CDX_PRD]   VARCHAR (4)   NULL,
    [PROP_DAVE_PRD]  VARCHAR (4)   NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CDX_CO_PR_CDX_CO_PR_68883]
    ON [dbo].[CDX_CO_PRD_IDX]([CDX_CO_PROP_ID] ASC);

