CREATE TABLE [dbo].[CDX_CO_RMK] (
    [CDX_CO_RMK_ID] VARCHAR (255) NOT NULL,
    [u2_id]         VARCHAR (255) NULL,
    [REMARKS]       VARCHAR (30)  NULL,
    [REMARK_DATES]  VARCHAR (8)   NULL,
    [time_stamp]    DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CDX_CO_RMK_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CDX_CO_RMK_u2_id_in]
    ON [dbo].[CDX_CO_RMK]([u2_id] ASC);

