CREATE TABLE [dbo].[CHECK_PTRSHP_NO] (
    [CHECK_PTRSHP_NO_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [PTRSHP_NO]          VARCHAR (6)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CHECK_PTRSHP_NO_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CHECK_PTRSHP_NO_u2_id_in]
    ON [dbo].[CHECK_PTRSHP_NO]([u2_id] ASC);

