CREATE TABLE [dbo].[CHECK_VOID_TRANS_IDX] (
    [CHECK_VOID_TRANS_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [VOID_TRANS_INDEX]        VARCHAR (9)   NULL,
    [VOID_TRANS_TYPES]        VARCHAR (3)   NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CHECK_VOID_TRANS_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CHECK_VOID_TRANS_IDX_u2_id_in]
    ON [dbo].[CHECK_VOID_TRANS_IDX]([u2_id] ASC);

