CREATE TABLE [dbo].[CHECK_PARTNER_NO] (
    [CHECK_PARTNER_NO_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [PARTNER_NO]          VARCHAR (9)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CHECK_PARTNER_NO_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CHECK_PARTNER_NO_u2_id_in]
    ON [dbo].[CHECK_PARTNER_NO]([u2_id] ASC);

