CREATE TABLE [dbo].[CHECK_PAY_DET_IDX] (
    [subValueId]           VARCHAR (255)   NOT NULL,
    [CHECK_MAN_CHECK_ID]   VARCHAR (255)   NULL,
    [MAN_DETAIL_AMTS]      NUMERIC (19, 2) NULL,
    [MAN_PAY_DETAIL_INDEX] VARCHAR (8)     NULL,
    [time_stamp]           DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CHECK_PAY_CHECK_MAN_93388]
    ON [dbo].[CHECK_PAY_DET_IDX]([CHECK_MAN_CHECK_ID] ASC);

