CREATE TABLE [dbo].[CN_COA_CLASS_ACCT] (
    [CN_COA_CLASS_ACCT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [ACCTS]                VARCHAR (15)  NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CN_COA_CLASS_ACCT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CN_COA_CLASS_ACCT_u2_id_in]
    ON [dbo].[CN_COA_CLASS_ACCT]([u2_id] ASC);

