CREATE TABLE [dbo].[CN_SYS_INC_ACCT] (
    [CN_SYS_INC_ACCT_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [INCOME_ACCT_CAT]    VARCHAR (6)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CN_SYS_INC_ACCT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CN_SYS_INC_ACCT_u2_id_in]
    ON [dbo].[CN_SYS_INC_ACCT]([u2_id] ASC);

