CREATE TABLE [dbo].[CN_SYS_INV_GRP] (
    [CN_SYS_INV_GRP_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [FULLY_CONTRIBUTE]  VARCHAR (1)   NULL,
    [VALID_INVEST_GRPS] VARCHAR (5)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CN_SYS_INV_GRP_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CN_SYS_INV_GRP_u2_id_in]
    ON [dbo].[CN_SYS_INV_GRP]([u2_id] ASC);

