CREATE TABLE [dbo].[CN_SYS_PTRS] (
    [CN_SYS_PTRS_ID] VARCHAR (255) NOT NULL,
    [u2_id]          VARCHAR (255) NULL,
    [EFF_DATES]      DATETIME      NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CN_SYS_PTRS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CN_SYS_PTRS_u2_id_in]
    ON [dbo].[CN_SYS_PTRS]([u2_id] ASC);

