CREATE TABLE [dbo].[CO_CONTACT_RMK] (
    [CO_CONTACT_RMK_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [DESC_LABELS]       VARCHAR (11)  NULL,
    [DESC_REMARKS]      VARCHAR (30)  NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CO_CONTACT_RMK_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CO_CONTACT_RMK_u2_id_in]
    ON [dbo].[CO_CONTACT_RMK]([u2_id] ASC);

