CREATE TABLE [dbo].[CO_CONTACT_X_STR] (
    [CO_CONTACT_X_STR_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [XREF_STRING]         VARCHAR (20)  NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CO_CONTACT_X_STR_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CO_CONTACT_X_STR_u2_id_in]
    ON [dbo].[CO_CONTACT_X_STR]([u2_id] ASC);

