CREATE TABLE [dbo].[CO_NOT_USED2] (
    [CO_NOT_USED2_ID] VARCHAR (255) NOT NULL,
    [u2_id]           VARCHAR (255) NULL,
    [NOT_USED2]       VARCHAR (10)  NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CO_NOT_USED2_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CO_NOT_USED2_u2_id_in]
    ON [dbo].[CO_NOT_USED2]([u2_id] ASC);

