CREATE TABLE [dbo].[CO_TB_FYE] (
    [CO_TB_FYE_ID] VARCHAR (255) NOT NULL,
    [u2_id]        VARCHAR (255) NULL,
    [TAX_BASE_FYE] DATETIME      NULL,
    [time_stamp]   DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CO_TB_FYE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CO_TB_FYE_u2_id_in]
    ON [dbo].[CO_TB_FYE]([u2_id] ASC);

