CREATE TABLE [dbo].[CO_VOU_SRC] (
    [CO_VOU_SRC_ID] VARCHAR (255) NOT NULL,
    [u2_id]         VARCHAR (255) NULL,
    [JE_VOU_SRC]    VARCHAR (3)   NULL,
    [time_stamp]    DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CO_VOU_SRC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CO_VOU_SRC_u2_id_in]
    ON [dbo].[CO_VOU_SRC]([u2_id] ASC);

