CREATE TABLE [dbo].[COA_GRP_CO_EXC_ACCTS] (
    [subValueId]    VARCHAR (255) NOT NULL,
    [COA_GRP_CO_ID] VARCHAR (255) NULL,
    [EXC_ACCTS]     VARCHAR (10)  NULL,
    [time_stamp]    DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [COA_GRP_C_COA_GRP_C_2657]
    ON [dbo].[COA_GRP_CO_EXC_ACCTS]([COA_GRP_CO_ID] ASC);

