CREATE TABLE [dbo].[COA_GRP_CO] (
    [COA_GRP_CO_ID] VARCHAR (255) NOT NULL,
    [u2_id]         VARCHAR (255) NULL,
    [COMPANIES]     VARCHAR (3)   NULL,
    [time_stamp]    DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([COA_GRP_CO_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [COA_GRP_CO_u2_id_in]
    ON [dbo].[COA_GRP_CO]([u2_id] ASC);

