CREATE TABLE [dbo].[COA_XREF_STRING] (
    [COA_XREF_STRING_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [XREF_STRING]        VARCHAR (26)  NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([COA_XREF_STRING_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [COA_XREF_STRING_u2_id_in]
    ON [dbo].[COA_XREF_STRING]([u2_id] ASC);

