CREATE TABLE [dbo].[COA_INVALID_COMPANIES] (
    [COA_INVALID_COMPANIES_ID] VARCHAR (255) NOT NULL,
    [u2_id]                    VARCHAR (255) NULL,
    [INVALID_COMPANIES]        VARCHAR (5)   NULL,
    [time_stamp]               DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([COA_INVALID_COMPANIES_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [COA_INVALID_COMPANIES_u2_id_in]
    ON [dbo].[COA_INVALID_COMPANIES]([u2_id] ASC);

