CREATE TABLE [dbo].[COA_USER_DATA_FIELDS] (
    [COA_USER_DATA_FIELDS_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [USER_DATA_FIELDS]        VARCHAR (10)  NULL,
    [USER_DATA_VALUES]        VARCHAR (63)  NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([COA_USER_DATA_FIELDS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [COA_USER_DATA_FIELDS_u2_id_in]
    ON [dbo].[COA_USER_DATA_FIELDS]([u2_id] ASC);

