CREATE TABLE [dbo].[COA_BUS_RELATIONS] (
    [COA_BUS_RELATIONS_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [BUS_RELATIONS]        VARCHAR (8)   NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([COA_BUS_RELATIONS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [COA_BUS_RELATIONS_u2_id_in]
    ON [dbo].[COA_BUS_RELATIONS]([u2_id] ASC);

