CREATE TABLE [dbo].[COD_CO_CODE_PROP] (
    [subValueId]      VARCHAR (255) NOT NULL,
    [COD_CO_CO_ID]    VARCHAR (255) NULL,
    [CODE_METERS]     VARCHAR (7)   NULL,
    [CODE_PROPERTIES] VARCHAR (14)  NULL,
    [CODE_TANKS]      VARCHAR (7)   NULL,
    [DAVE_METERS]     VARCHAR (7)   NULL,
    [DAVE_PROPERTIES] VARCHAR (14)  NULL,
    [DAVE_TANKS]      VARCHAR (7)   NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [COD_CO_CO_COD_CO_CO_19398]
    ON [dbo].[COD_CO_CODE_PROP]([COD_CO_CO_ID] ASC);

