CREATE TABLE [dbo].[CPT_CDX] (
    [CPT_CDX_ID]   VARCHAR (255) NOT NULL,
    [u2_id]        VARCHAR (255) NULL,
    [CDX_CODE]     VARCHAR (4)   NULL,
    [CDX_PRODUCTS] VARCHAR (3)   NULL,
    [time_stamp]   DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CPT_CDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CPT_CDX_u2_id_in]
    ON [dbo].[CPT_CDX]([u2_id] ASC);

