CREATE TABLE [dbo].[CPT_REG] (
    [CPT_REG_ID] VARCHAR (255) NOT NULL,
    [u2_id]      VARCHAR (255) NULL,
    [REG_CD]     VARCHAR (11)  NULL,
    [time_stamp] DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CPT_REG_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CPT_REG_u2_id_in]
    ON [dbo].[CPT_REG]([u2_id] ASC);

