CREATE TABLE [dbo].[CPTCALC_EFF_DT] (
    [subValueId]     VARCHAR (255) NOT NULL,
    [CPTCALC_CPT_ID] VARCHAR (255) NULL,
    [EFF_DATES]      DATETIME      NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CPTCALC_E_CPTCALC_C_81959]
    ON [dbo].[CPTCALC_EFF_DT]([CPTCALC_CPT_ID] ASC);

