CREATE TABLE [dbo].[CTRC_VOL_NGL_CTRC] (
    [subValueId]             VARCHAR (255)   NOT NULL,
    [CTRC_VOL_NGL_WI_ID]     VARCHAR (255)   NULL,
    [ACTUAL_INTERESTS]       NUMERIC (19, 8) NULL,
    [CONTRACTS]              VARCHAR (8)     NULL,
    [CONTRACT_TAKE_PROD_VOL] NUMERIC (19, 2) NULL,
    [CONTRACT_TAKE_STMT_VOL] NUMERIC (19, 2) NULL,
    [CONTRACT_TAKE_VALUES]   NUMERIC (19, 2) NULL,
    [ORR_ACTUAL_INTERESTS]   NUMERIC (19, 8) NULL,
    [ORR_CONTRACT_TAKES]     NUMERIC (19, 2) NULL,
    [time_stamp]             DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CTRC_VOL__CTRC_VOL__12118]
    ON [dbo].[CTRC_VOL_NGL_CTRC]([CTRC_VOL_NGL_WI_ID] ASC);

