CREATE TABLE [dbo].[CTRC_VOL_NGL_OWN_IDX] (
    [CTRC_VOL_NGL_OWN_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [OWNER_VOL_INDEX]         VARCHAR (9)   NULL,
    [REALLOC_OWNER_VOL_FLAG]  VARCHAR (9)   NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CTRC_VOL_NGL_OWN_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CTRC_VOL_NGL_OWN_IDX_u2_id_in]
    ON [dbo].[CTRC_VOL_NGL_OWN_IDX]([u2_id] ASC);

