CREATE TABLE [dbo].[CUST_RMK] (
    [CUST_RMK_ID]  VARCHAR (255) NOT NULL,
    [u2_id]        VARCHAR (255) NULL,
    [REMARKS]      VARCHAR (100) NULL,
    [REMARK_DATES] DATETIME      NULL,
    [time_stamp]   DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CUST_RMK_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CUST_RMK_u2_id_in]
    ON [dbo].[CUST_RMK]([u2_id] ASC);

