CREATE TABLE [dbo].[CUST_NET_INT_CAT] (
    [subValueId]     VARCHAR (255) NOT NULL,
    [CUST_NET_CC_ID] VARCHAR (255) NULL,
    [NET_INT_CATS]   VARCHAR (3)   NULL,
    [NET_JBCCS]      VARCHAR (4)   NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CUST_NET__CUST_NET__46015]
    ON [dbo].[CUST_NET_INT_CAT]([CUST_NET_CC_ID] ASC);

