CREATE TABLE [dbo].[DAILY_PPL_STMT_CTRC] (
    [DAILY_PPL_STMT_CTRC_ID] VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [CONTRACTS]              VARCHAR (8)   NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([DAILY_PPL_STMT_CTRC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DAILY_PPL_STMT_CTRC_u2_id_in]
    ON [dbo].[DAILY_PPL_STMT_CTRC]([u2_id] ASC);

