CREATE TABLE [dbo].[DAILY_PPL_STMT_CTRCTS] (
    [subValueId]           VARCHAR (255) NOT NULL,
    [DAILY_PPL_STMT_DD_ID] VARCHAR (255) NULL,
    [CONTRACTS_BY_DAY]     VARCHAR (8)   NULL,
    [CONTRACT_MMBTUS]      NUMERIC (9)   NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DAILY_PPL_DAILY_PPL_91312]
    ON [dbo].[DAILY_PPL_STMT_CTRCTS]([DAILY_PPL_STMT_DD_ID] ASC);

