CREATE TABLE [dbo].[DB_TRIG_PROF_DELETE] (
    [DB_TRIG_PROF_DELETE_ID]      VARCHAR (255) NOT NULL,
    [u2_id]                       VARCHAR (255) NULL,
    [DELETE_TRIGGERS]             VARCHAR (29)  NULL,
    [DELETE_TRIGGERS_ENABLED]     VARCHAR (7)   NULL,
    [DELETE_TRIGGER_MODIFY_FLAGS] VARCHAR (7)   NULL,
    [time_stamp]                  DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([DB_TRIG_PROF_DELETE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DB_TRIG_PROF_DELETE_u2_id_in]
    ON [dbo].[DB_TRIG_PROF_DELETE]([u2_id] ASC);

