CREATE TABLE [dbo].[DEPOSIT_TRANS] (
    [DEPOSIT_TRANS_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [DOC_INDEX]        VARCHAR (26)  NULL,
    [TRANS_INDEX]      VARCHAR (9)   NULL,
    [TRANS_TYPES]      VARCHAR (5)   NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([DEPOSIT_TRANS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DEPOSIT_TRANS_u2_id_in]
    ON [dbo].[DEPOSIT_TRANS]([u2_id] ASC);

