CREATE TABLE [dbo].[DIV_STATUS] (
    [subValueId]        VARCHAR (255) NOT NULL,
    [DIV_SESS_ID]       VARCHAR (255) NULL,
    [CTRC_VOL_INDEX]    VARCHAR (8)   NULL,
    [PRD_BAL_ADJ_INDEX] VARCHAR (9)   NULL,
    [PRD_BAL_MAN_INDEX] VARCHAR (9)   NULL,
    [SESSION_STATUS]    VARCHAR (10)  NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DIV_STATUS_DIV_SESS_ID_in]
    ON [dbo].[DIV_STATUS]([DIV_SESS_ID] ASC);

