CREATE TABLE [dbo].[DIV_NRI_WELL_IDX] (
    [DIV_NRI_WELL_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [NRI_WELL_INDEX]      VARCHAR (6)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([DIV_NRI_WELL_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DIV_NRI_WELL_IDX_u2_id_in]
    ON [dbo].[DIV_NRI_WELL_IDX]([u2_id] ASC);

