CREATE TABLE [dbo].[DIV_ASSEM_LDECK_IDX] (
    [subValueId]            VARCHAR (255) NOT NULL,
    [DIV_ASSEM_LGL_IDX_ID]  VARCHAR (255) NULL,
    [INTEREST_TYPES]        VARCHAR (4)   NULL,
    [LDECK_INDEX]           VARCHAR (8)   NULL,
    [LDECK_SESSIONS]        VARCHAR (7)   NULL,
    [NET_REVENUE_INTERESTS] VARCHAR (21)  NULL,
    [NRI_FORMULAS]          VARCHAR (40)  NULL,
    [NRI_OWNERS]            VARCHAR (10)  NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DIV_ASSEM_DIV_ASSEM_27698]
    ON [dbo].[DIV_ASSEM_LDECK_IDX]([DIV_ASSEM_LGL_IDX_ID] ASC);

