CREATE TABLE [dbo].[DIV_ASSEM_LGL_IDX] (
    [DIV_ASSEM_LGL_IDX_ID]  VARCHAR (255)   NOT NULL,
    [u2_id]                 VARCHAR (255)   NULL,
    [LEGAL_DESC_INDEX]      VARCHAR (5)     NULL,
    [LEGAL_DESC_NRI_TOTALS] NUMERIC (19, 8) NULL,
    [TRACT_ALLOC_UNITS]     NUMERIC (19, 4) NULL,
    [TRACT_FACTORS]         NUMERIC (19, 8) NULL,
    [TRACT_FACTOR_FORMULAS] VARCHAR (7)     NULL,
    [TRACT_INDEX]           VARCHAR (5)     NULL,
    [time_stamp]            DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([DIV_ASSEM_LGL_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DIV_ASSEM_LGL_IDX_u2_id_in]
    ON [dbo].[DIV_ASSEM_LGL_IDX]([u2_id] ASC);

