CREATE TABLE [dbo].[DOCUMENT_DET] (
    [subValueId]       VARCHAR (255) NOT NULL,
    [DOCUMENT_ATTR_ID] VARCHAR (255) NULL,
    [ATTRIBUTE_VALUES] VARCHAR (30)  NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DOCUMENT__DOCUMENT__2893]
    ON [dbo].[DOCUMENT_DET]([DOCUMENT_ATTR_ID] ASC);

