CREATE TABLE [dbo].[DR21W_CTL_ADV_CPT] (
    [DR21W_CTL_ADV_CPT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [ADVALOREM_CPT]        VARCHAR (10)  NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([DR21W_CTL_ADV_CPT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DR21W_CTL_ADV_CPT_u2_id_in]
    ON [dbo].[DR21W_CTL_ADV_CPT]([u2_id] ASC);

