CREATE TABLE [dbo].[DR21W_CTL_OIL_CD] (
    [DR21W_CTL_OIL_CD_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [OIL_PRD_CODE]        VARCHAR (8)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([DR21W_CTL_OIL_CD_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DR21W_CTL_OIL_CD_u2_id_in]
    ON [dbo].[DR21W_CTL_OIL_CD]([u2_id] ASC);

