CREATE TABLE [dbo].[DRAFT] (
    [u2_id]              VARCHAR (255)   NOT NULL,
    [ACRES]              NUMERIC (19, 4) NULL,
    [AFE]                VARCHAR (10)    NULL,
    [AGENT]              VARCHAR (20)    NULL,
    [BANK]               VARCHAR (8)     NULL,
    [BANK_COMPANY]       VARCHAR (7)     NULL,
    [COMPANY]            VARCHAR (4)     NULL,
    [CONSIDERATION_DESC] VARCHAR (30)    NULL,
    [CONSIDERATION_FOR]  VARCHAR (30)    NULL,
    [COUNTY]             VARCHAR (7)     NULL,
    [DRAFT_AMT]          NUMERIC (19, 2) NULL,
    [DRAFT_DATE]         DATETIME        NULL,
    [DRAFT_NO]           VARCHAR (12)    NULL,
    [FT]                 NUMERIC (19, 2) NULL,
    [INTEREST]           NUMERIC (19, 8) NULL,
    [LEGAL_DESC]         VARCHAR (30)    NULL,
    [MISC_REMARKS]       VARCHAR (30)    NULL,
    [PAID_DATE]          DATETIME        NULL,
    [PAYEE]              VARCHAR (8)     NULL,
    [PAYEE_ADDR1]        VARCHAR (30)    NULL,
    [PAYEE_ADDR2]        VARCHAR (30)    NULL,
    [PAYEE_ADDR3]        VARCHAR (30)    NULL,
    [PAYEE_CITY]         VARCHAR (30)    NULL,
    [PAYEE_COUNTRY]      VARCHAR (3)     NULL,
    [PAYEE_NAME1]        VARCHAR (30)    NULL,
    [PAYEE_NAME2]        VARCHAR (30)    NULL,
    [PAYEE_NAME3]        VARCHAR (30)    NULL,
    [PAYEE_STATE]        VARCHAR (5)     NULL,
    [PAYEE_TAX_ID]       VARCHAR (12)    NULL,
    [PAYEE_ZIP]          VARCHAR (12)    NULL,
    [PRINTED_DATE]       DATETIME        NULL,
    [PROSPECT]           VARCHAR (8)     NULL,
    [REPLACEMENT_DRAFT]  VARCHAR (10)    NULL,
    [SIGHT_DAYS]         VARCHAR (5)     NULL,
    [STATE]              VARCHAR (5)     NULL,
    [TRACT]              VARCHAR (10)    NULL,
    [WELL]               VARCHAR (10)    NULL,
    [time_stamp]         DATETIME        NULL,
    [u2_checksum]        VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

