CREATE TABLE [dbo].[ENT_BALFWD_ACTIVE] (
    [ENT_BALFWD_ACTIVE_ID]    VARCHAR (255)   NOT NULL,
    [u2_id]                   VARCHAR (255)   NULL,
    [ACTIVE_ACCTG_PERIODS]    DATETIME        NULL,
    [ACTIVE_GROSS_WI]         NUMERIC (19, 8) NULL,
    [ACTIVE_GROSS_WI_VOLUMES] NUMERIC (19, 2) NULL,
    [ACTIVE_NRI]              NUMERIC (19, 8) NULL,
    [ACTIVE_RATIO_INTEREST]   NUMERIC (19, 8) NULL,
    [time_stamp]              DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([ENT_BALFWD_ACTIVE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ENT_BALFWD_ACTIVE_u2_id_in]
    ON [dbo].[ENT_BALFWD_ACTIVE]([u2_id] ASC);

