CREATE TABLE [dbo].[ENT_MANUAL_AUDIT] (
    [ENT_MANUAL_AUDIT_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [SYSTEM_DATE]         DATETIME      NULL,
    [SYSTEM_TIME]         VARCHAR (12)  NULL,
    [SYSTEM_USER_ID]      VARCHAR (12)  NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([ENT_MANUAL_AUDIT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ENT_MANUAL_AUDIT_u2_id_in]
    ON [dbo].[ENT_MANUAL_AUDIT]([u2_id] ASC);

