CREATE TABLE [dbo].[ENT_BALFWD_OVR] (
    [ENT_BALFWD_OVR_ID] VARCHAR (255)   NOT NULL,
    [u2_id]             VARCHAR (255)   NULL,
    [OVERRIDE_PERIODS]  DATETIME        NULL,
    [OVERRIDE_PRICES]   NUMERIC (19, 3) NULL,
    [time_stamp]        DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([ENT_BALFWD_OVR_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ENT_BALFWD_OVR_u2_id_in]
    ON [dbo].[ENT_BALFWD_OVR]([u2_id] ASC);

