CREATE TABLE [dbo].[ENT_BALFWD_PROCESS_DATES_sub1] (
    [subValueId]              VARCHAR (255) NOT NULL,
    [ENT_BALFWD_ACCTG_PER_ID] VARCHAR (255) NULL,
    [PROCESS_DATES]           DATETIME      NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ENT_BALFW_ENT_BALFW_69319]
    ON [dbo].[ENT_BALFWD_PROCESS_DATES_sub1]([ENT_BALFWD_ACCTG_PER_ID] ASC);

