CREATE TABLE [dbo].[ENT_BALFWD_AUDIT] (
    [ENT_BALFWD_AUDIT_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [AUDIT_DATE]          DATETIME      NULL,
    [AUDIT_USER]          VARCHAR (9)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([ENT_BALFWD_AUDIT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ENT_BALFWD_AUDIT_u2_id_in]
    ON [dbo].[ENT_BALFWD_AUDIT]([u2_id] ASC);

