CREATE TABLE [dbo].[FDEFS_ITYPE_DATA_DICT] (
    [FDEFS_ITYPE_DATA_DICT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                    VARCHAR (255) NULL,
    [ITYPE_LINE1_COMMENT]      VARCHAR (504) NULL,
    [time_stamp]               DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([FDEFS_ITYPE_DATA_DICT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FDEFS_ITYPE_DATA_DICT_u2_id_in]
    ON [dbo].[FDEFS_ITYPE_DATA_DICT]([u2_id] ASC);

