CREATE TABLE [dbo].[FDEFS_UPDT_SRC] (
    [subValueId]         VARCHAR (255) NOT NULL,
    [FDEFS_DATA_DICT_ID] VARCHAR (255) NULL,
    [UPDATE_SOURCE]      VARCHAR (28)  NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FDEFS_UPD_FDEFS_DAT_13666]
    ON [dbo].[FDEFS_UPDT_SRC]([FDEFS_DATA_DICT_ID] ASC);

