CREATE TABLE [dbo].[FDEFS_IDX_DET] (
    [subValueId]         VARCHAR (255) NOT NULL,
    [FDEFS_INDEX_DEF_ID] VARCHAR (255) NULL,
    [INDEX_AMC]          VARCHAR (29)  NULL,
    [INDEX_KEY_AMC]      VARCHAR (10)  NULL,
    [INDEX_SUBR]         VARCHAR (15)  NULL,
    [INDEX_TABLE_AMC]    VARCHAR (10)  NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FDEFS_IDX_FDEFS_IND_15154]
    ON [dbo].[FDEFS_IDX_DET]([FDEFS_INDEX_DEF_ID] ASC);

