CREATE TABLE [dbo].[FIN_RPT_FMT_CTR_CAP] (
    [FIN_RPT_FMT_CTR_CAP_ID] VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [CENTER_CAPTION]         VARCHAR (20)  NULL,
    [CENTER_CAPTION_FMT]     VARCHAR (7)   NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([FIN_RPT_FMT_CTR_CAP_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FIN_RPT_FMT_CTR_CAP_u2_id_in]
    ON [dbo].[FIN_RPT_FMT_CTR_CAP]([u2_id] ASC);

