CREATE TABLE [dbo].[FIN_RPT_FMT_UDF] (
    [FIN_RPT_FMT_UDF_ID]   VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [USER_BUCKETS]         VARCHAR (7)   NULL,
    [USER_PARAMETERS_TEXT] VARCHAR (47)  NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([FIN_RPT_FMT_UDF_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FIN_RPT_FMT_UDF_u2_id_in]
    ON [dbo].[FIN_RPT_FMT_UDF]([u2_id] ASC);

