CREATE TABLE [dbo].[FIN_RPT_FMT_COL] (
    [FIN_RPT_FMT_COL_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [COL_ACT_BUD_FLAGS]  VARCHAR (6)   NULL,
    [COL_CONTROL_VALUES] VARCHAR (18)  NULL,
    [COL_CONVS]          VARCHAR (10)  NULL,
    [COL_DATA_TYPES]     VARCHAR (4)   NULL,
    [COL_DATE_FORMULAS]  VARCHAR (20)  NULL,
    [COL_FMTS]           VARCHAR (7)   NULL,
    [COL_FORMULAS]       VARCHAR (77)  NULL,
    [COL_HEADINGS]       VARCHAR (60)  NULL,
    [COL_SUM_BUCKETS]    VARCHAR (6)   NULL,
    [COL_SUPPRESS_ULS]   VARCHAR (9)   NULL,
    [NUMERIC_COL_FLAGS]  VARCHAR (7)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([FIN_RPT_FMT_COL_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FIN_RPT_FMT_COL_u2_id_in]
    ON [dbo].[FIN_RPT_FMT_COL]([u2_id] ASC);

