CREATE TABLE [dbo].[FIN_RPT_FMT_ROW_BREAK_LEVEL] (
    [subValueId]         VARCHAR (255) NOT NULL,
    [FIN_RPT_FMT_ROW_ID] VARCHAR (255) NULL,
    [ROW_BREAK_LEVELS]   VARCHAR (19)  NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FIN_RPT_F_FIN_RPT_F_82724]
    ON [dbo].[FIN_RPT_FMT_ROW_BREAK_LEVEL]([FIN_RPT_FMT_ROW_ID] ASC);

