CREATE TABLE [dbo].[FIN_RPT_FMT_LEFT] (
    [FIN_RPT_FMT_LEFT_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [LEFT_HEADING]        VARCHAR (58)  NULL,
    [LEFT_HEADING_FMT]    VARCHAR (6)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([FIN_RPT_FMT_LEFT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FIN_RPT_FMT_LEFT_u2_id_in]
    ON [dbo].[FIN_RPT_FMT_LEFT]([u2_id] ASC);

