CREATE TABLE [dbo].[FIN_RPT_FMT_OVR] (
    [FIN_RPT_FMT_OVR_ID]     VARCHAR (255) NOT NULL,
    [u2_id]                  VARCHAR (255) NULL,
    [OVERRIDE_COLS]          VARCHAR (8)   NULL,
    [OVERRIDE_CONVS]         VARCHAR (8)   NULL,
    [OVERRIDE_DATE_FORMULAS] VARCHAR (20)  NULL,
    [OVERRIDE_FORMULAS]      VARCHAR (29)  NULL,
    [OVERRIDE_ROWS]          VARCHAR (8)   NULL,
    [OVERRIDE_SUM_BUCKETS]   VARCHAR (8)   NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([FIN_RPT_FMT_OVR_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FIN_RPT_FMT_OVR_u2_id_in]
    ON [dbo].[FIN_RPT_FMT_OVR]([u2_id] ASC);

