CREATE TABLE [dbo].[FIN_RPT_FMT_RT] (
    [FIN_RPT_FMT_RT_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [RIGHT_HEADING]     VARCHAR (33)  NULL,
    [RIGHT_HEADING_FMT] VARCHAR (6)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([FIN_RPT_FMT_RT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FIN_RPT_FMT_RT_u2_id_in]
    ON [dbo].[FIN_RPT_FMT_RT]([u2_id] ASC);

