CREATE TABLE [dbo].[FIN_RPT_MAP_SUPP] (
    [FIN_RPT_MAP_SUPP_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [SUPPRESSED_LINES]    VARCHAR (10)  NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([FIN_RPT_MAP_SUPP_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FIN_RPT_MAP_SUPP_u2_id_in]
    ON [dbo].[FIN_RPT_MAP_SUPP]([u2_id] ASC);

