CREATE TABLE [dbo].[FIN_RPT_FMT_CTR_FT] (
    [FIN_RPT_FMT_CTR_FT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [CENTER_FOOTING]        VARCHAR (50)  NULL,
    [CENTER_FOOTING_FMT]    VARCHAR (7)   NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([FIN_RPT_FMT_CTR_FT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FIN_RPT_FMT_CTR_FT_u2_id_in]
    ON [dbo].[FIN_RPT_FMT_CTR_FT]([u2_id] ASC);

