CREATE TABLE [dbo].[FIN_RPT_MAP_SUB] (
    [FIN_RPT_MAP_SUB_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [SUBORDINATE_NODES]  VARCHAR (11)  NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([FIN_RPT_MAP_SUB_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FIN_RPT_MAP_SUB_u2_id_in]
    ON [dbo].[FIN_RPT_MAP_SUB]([u2_id] ASC);

