CREATE TABLE [dbo].[FIN_RPT_FMT_CTR] (
    [FIN_RPT_FMT_CTR_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [CENTER_HEADING]     VARCHAR (43)  NULL,
    [CENTER_HEADING_FMT] VARCHAR (6)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([FIN_RPT_FMT_CTR_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FIN_RPT_FMT_CTR_u2_id_in]
    ON [dbo].[FIN_RPT_FMT_CTR]([u2_id] ASC);

