CREATE TABLE [dbo].[GATH_SYS_SUB_SYS_INDEX] (
    [GATH_SYS_SUB_SYS_INDEX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                     VARCHAR (255) NULL,
    [GATH_SUB_SYS_INDEX]        VARCHAR (8)   NULL,
    [time_stamp]                DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([GATH_SYS_SUB_SYS_INDEX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [GATH_SYS__u2_id_33979]
    ON [dbo].[GATH_SYS_SUB_SYS_INDEX]([u2_id] ASC);

