CREATE TABLE [dbo].[GATH_SYS_ALLOW_DISPS] (
    [GATH_SYS_ALLOW_DISPS_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [ALLOW_DISPS]             VARCHAR (5)   NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([GATH_SYS_ALLOW_DISPS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [GATH_SYS_ALLOW_DISPS_u2_id_in]
    ON [dbo].[GATH_SYS_ALLOW_DISPS]([u2_id] ASC);

