CREATE TABLE [dbo].[GL_BUD_CC_CONS_LEVELS] (
    [GL_BUD_CC_CONS_LEVELS_ID] VARCHAR (255) NOT NULL,
    [u2_id]                    VARCHAR (255) NULL,
    [HIER_LEVEL_CODES]         VARCHAR (25)  NULL,
    [time_stamp]               DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([GL_BUD_CC_CONS_LEVELS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [GL_BUD_CC_CONS_LEVELS_u2_id_in]
    ON [dbo].[GL_BUD_CC_CONS_LEVELS]([u2_id] ASC);

