CREATE TABLE [dbo].[GL_BUD_COST_PHASES] (
    [subValueId]          VARCHAR (255) NOT NULL,
    [GL_BUD_ACCTG_PER_ID] VARCHAR (255) NULL,
    [COST_PHASES]         VARCHAR (5)   NULL,
    [COST_PHASE_AMTS]     VARCHAR (10)  NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [GL_BUD_CO_GL_BUD_AC_50465]
    ON [dbo].[GL_BUD_COST_PHASES]([GL_BUD_ACCTG_PER_ID] ASC);

