CREATE TABLE [dbo].[GL_CC_CONS_ACCTG_PERSPECTIVE] (
    [subValueId]              VARCHAR (255)   NOT NULL,
    [GL_CC_CONS_ACCTG_PER_ID] VARCHAR (255)   NULL,
    [ACCTG_PERSPECTIVES]      VARCHAR (5)     NULL,
    [DEV_RESERVES]            NUMERIC (19, 2) NULL,
    [UNDEV_RESERVES]          NUMERIC (19, 2) NULL,
    [time_stamp]              DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [GL_CC_CON_GL_CC_CON_46452]
    ON [dbo].[GL_CC_CONS_ACCTG_PERSPECTIVE]([GL_CC_CONS_ACCTG_PER_ID] ASC);

