CREATE TABLE [dbo].[GL_DET_ACCTG_PERSPECTIVES] (
    [subValueId]          VARCHAR (255)   NOT NULL,
    [GL_DET_ACCTG_PER_ID] VARCHAR (255)   NULL,
    [ACCTG_PERSPECTIVES]  VARCHAR (5)     NULL,
    [DEV_RESERVES]        NUMERIC (19, 2) NULL,
    [UNDEV_RESERVES]      NUMERIC (19, 2) NULL,
    [time_stamp]          DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [GL_DET_AC_GL_DET_AC_48989]
    ON [dbo].[GL_DET_ACCTG_PERSPECTIVES]([GL_DET_ACCTG_PER_ID] ASC);

