CREATE TABLE [dbo].[GRAVITY_ADJ_CODE_AUDIT] (
    [GRAVITY_ADJ_CODE_AUDIT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                     VARCHAR (255) NULL,
    [SYSTEM_DATE]               DATETIME      NULL,
    [SYSTEM_TIME]               VARCHAR (8)   NULL,
    [SYSTEM_USER_ID]            VARCHAR (8)   NULL,
    [time_stamp]                DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([GRAVITY_ADJ_CODE_AUDIT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [GRAVITY_A_u2_id_82524]
    ON [dbo].[GRAVITY_ADJ_CODE_AUDIT]([u2_id] ASC);

