CREATE TABLE [dbo].[GS_STATUS_WELL_IDX] (
    [GS_STATUS_WELL_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [WELL_PROD_INDEX]       VARCHAR (10)  NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([GS_STATUS_WELL_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [GS_STATUS_WELL_IDX_u2_id_in]
    ON [dbo].[GS_STATUS_WELL_IDX]([u2_id] ASC);

