CREATE TABLE [dbo].[GS_STATUS_PPL] (
    [GS_STATUS_PPL_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [PPL_SALE_INDEX]   VARCHAR (10)  NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([GS_STATUS_PPL_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [GS_STATUS_PPL_u2_id_in]
    ON [dbo].[GS_STATUS_PPL]([u2_id] ASC);

