CREATE TABLE [dbo].[GS_STATUS_NO_SALES_IDX] (
    [GS_STATUS_NO_SALES_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                     VARCHAR (255) NULL,
    [NO_SALES_WELL_PROD_INDEX]  VARCHAR (9)   NULL,
    [time_stamp]                DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([GS_STATUS_NO_SALES_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [GS_STATUS_u2_id_74533]
    ON [dbo].[GS_STATUS_NO_SALES_IDX]([u2_id] ASC);

