CREATE TABLE [dbo].[INS_CERT_AUDIT] (
    [INS_CERT_AUDIT_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [SYSTEM_DATE]       DATETIME      NULL,
    [SYSTEM_TIME]       VARCHAR (8)   NULL,
    [SYSTEM_USER_ID]    VARCHAR (5)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([INS_CERT_AUDIT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INS_CERT_AUDIT_u2_id_in]
    ON [dbo].[INS_CERT_AUDIT]([u2_id] ASC);

