CREATE TABLE [dbo].[INS_CERT_STS] (
    [INS_CERT_STS_ID]  VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [STATUS]           VARCHAR (2)   NULL,
    [STATUS_EFF_DATES] DATETIME      NULL,
    [STATUS_EXP_DATES] DATETIME      NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([INS_CERT_STS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INS_CERT_STS_u2_id_in]
    ON [dbo].[INS_CERT_STS]([u2_id] ASC);

