CREATE TABLE [dbo].[INS_CERT_LINK] (
    [INS_CERT_LINK_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [LINKS]            VARCHAR (20)  NULL,
    [LINK_TYPES]       VARCHAR (6)   NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([INS_CERT_LINK_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INS_CERT_LINK_u2_id_in]
    ON [dbo].[INS_CERT_LINK]([u2_id] ASC);

