CREATE TABLE [dbo].[IR_PGM_ACCTG_PER] (
    [IR_PGM_ACCTG_PER_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [COA_GRP_INDEX]       VARCHAR (8)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([IR_PGM_ACCTG_PER_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IR_PGM_ACCTG_PER_u2_id_in]
    ON [dbo].[IR_PGM_ACCTG_PER]([u2_id] ASC);

