CREATE TABLE [dbo].[IR_PGM_PROP_IDX] (
    [IR_PGM_PROP_IDX_ID]      VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [INVESTOR_PROPERTY_INDEX] VARCHAR (9)   NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([IR_PGM_PROP_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IR_PGM_PROP_IDX_u2_id_in]
    ON [dbo].[IR_PGM_PROP_IDX]([u2_id] ASC);

