CREATE TABLE [dbo].[IR_PGM_PROP] (
    [IR_PGM_PROP_ID] VARCHAR (255) NOT NULL,
    [u2_id]          VARCHAR (255) NULL,
    [PROPERTIES]     VARCHAR (11)  NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([IR_PGM_PROP_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IR_PGM_PROP_u2_id_in]
    ON [dbo].[IR_PGM_PROP]([u2_id] ASC);

