CREATE TABLE [dbo].[IR_TRANS_SUM_TRANS_IDX] (
    [IR_TRANS_SUM_TRANS_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                     VARCHAR (255) NULL,
    [TRANS_INDEX]               VARCHAR (5)   NULL,
    [time_stamp]                DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([IR_TRANS_SUM_TRANS_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IR_TRANS__u2_id_78236]
    ON [dbo].[IR_TRANS_SUM_TRANS_IDX]([u2_id] ASC);

