CREATE TABLE [dbo].[JB_SYS_WELL_CNT] (
    [JB_SYS_WELL_CNT_ID]  VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [WELL_COUNT_STATUSES] VARCHAR (6)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([JB_SYS_WELL_CNT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [JB_SYS_WELL_CNT_u2_id_in]
    ON [dbo].[JB_SYS_WELL_CNT]([u2_id] ASC);

