CREATE TABLE [dbo].[JB_SYS] (
    [u2_id]                      VARCHAR (255) NOT NULL,
    [ALLOC_SUS_ACCT]             VARCHAR (10)  NULL,
    [BALANCING_ACCT]             VARCHAR (10)  NULL,
    [BAL_OWNER]                  VARCHAR (9)   NULL,
    [CUTBACK_APP]                VARCHAR (10)  NULL,
    [CUTBACK_VOU_SRC]            VARCHAR (7)   NULL,
    [JIB_INVOICE_APP]            VARCHAR (10)  NULL,
    [JIB_INVOICE_VOU_SRC]        VARCHAR (7)   NULL,
    [JIB_NET_COST_CENTER]        VARCHAR (10)  NULL,
    [JIB_NET_CPT]                VARCHAR (7)   NULL,
    [JIB_NET_MIN_FLAG]           VARCHAR (4)   NULL,
    [JIB_OWNER_ADJ_APP]          VARCHAR (10)  NULL,
    [JIB_OWNER_ADJ_VOU_SRC]      VARCHAR (10)  NULL,
    [NET_ROLLUP_PROP_FLAG]       VARCHAR (6)   NULL,
    [OH_APP]                     VARCHAR (14)  NULL,
    [OH_VOU_SRC]                 VARCHAR (7)   NULL,
    [OVERRIDE_EFF_DATE_FLAG]     VARCHAR (9)   NULL,
    [OVR_BDECK_EFFDAY]           VARCHAR (6)   NULL,
    [PP_APP]                     VARCHAR (10)  NULL,
    [PP_AR_CONTRA_ACCT]          VARCHAR (10)  NULL,
    [PP_PAYABLE_ACCT]            VARCHAR (10)  NULL,
    [PP_VOU_SRC]                 VARCHAR (7)   NULL,
    [PRINT_FORMAT]               VARCHAR (6)   NULL,
    [PRINT_OCCUR_DATE]           VARCHAR (5)   NULL,
    [RCV_ACCT]                   VARCHAR (10)  NULL,
    [REMIT_TO]                   VARCHAR (9)   NULL,
    [REQUIRE_APPROVED_BDECKS]    VARCHAR (8)   NULL,
    [REQUIRE_MONTHLY_WELL_COUNT] VARCHAR (26)  NULL,
    [SPACE_SAVER_INV]            VARCHAR (3)   NULL,
    [UNALLOC_SUS_ACCT]           VARCHAR (10)  NULL,
    [UNBILL_RCV_ACCT]            VARCHAR (10)  NULL,
    [time_stamp]                 DATETIME      NULL,
    [u2_checksum]                VARCHAR (25)  NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

