CREATE TABLE [dbo].[JBCC_INFO_JBCC] (
    [JBCC_INFO_JBCC_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [JBCC]              VARCHAR (4)   NULL,
    [SUM_OR_DET_FLAGS]  VARCHAR (3)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([JBCC_INFO_JBCC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [JBCC_INFO_JBCC_u2_id_in]
    ON [dbo].[JBCC_INFO_JBCC]([u2_id] ASC);

