CREATE TABLE [dbo].[JBCTL_JBCC] (
    [JBCTL_JBCC_ID] VARCHAR (255) NOT NULL,
    [u2_id]         VARCHAR (255) NULL,
    [OFFSET_ACCTS]  VARCHAR (12)  NULL,
    [TARGET_ACCTS]  VARCHAR (12)  NULL,
    [time_stamp]    DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([JBCTL_JBCC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [JBCTL_JBCC_u2_id_in]
    ON [dbo].[JBCTL_JBCC]([u2_id] ASC);

