CREATE TABLE [dbo].[JBCYCLE_JBCC_IDX] (
    [JBCYCLE_JBCC_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [JBCC_REFS]           VARCHAR (5)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([JBCYCLE_JBCC_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [JBCYCLE_JBCC_IDX_u2_id_in]
    ON [dbo].[JBCYCLE_JBCC_IDX]([u2_id] ASC);

