CREATE TABLE [dbo].[JE_TRANS] (
    [JE_TRANS_ID] VARCHAR (255) NOT NULL,
    [u2_id]       VARCHAR (255) NULL,
    [TRANS_INDEX] VARCHAR (9)   NULL,
    [TRANS_TYPES] VARCHAR (5)   NULL,
    [time_stamp]  DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([JE_TRANS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [JE_TRANS_u2_id_in]
    ON [dbo].[JE_TRANS]([u2_id] ASC);

