CREATE TABLE [dbo].[JUR_TAX_TABLE_WHT] (
    [JUR_TAX_TABLE_WHT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [WHT_ACCTS]            VARCHAR (12)  NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([JUR_TAX_TABLE_WHT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [JUR_TAX_TABLE_WHT_u2_id_in]
    ON [dbo].[JUR_TAX_TABLE_WHT]([u2_id] ASC);

