CREATE TABLE [dbo].[LD_CTL_RECOMMEND] (
    [LD_CTL_RECOMMEND_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [RECOMMEND_CODES]     VARCHAR (9)   NULL,
    [RECOMMEND_DESCS]     VARCHAR (25)  NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LD_CTL_RECOMMEND_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LD_CTL_RECOMMEND_u2_id_in]
    ON [dbo].[LD_CTL_RECOMMEND]([u2_id] ASC);

