CREATE TABLE [dbo].[LD_QUERY_TEMPLATE] (
    [u2_id]       VARCHAR (255) NOT NULL,
    [DESCRIPTION] VARCHAR (30)  NULL,
    [DESTINATION] VARCHAR (11)  NULL,
    [QUERY_TYPE]  VARCHAR (5)   NULL,
    [time_stamp]  DATETIME      NULL,
    [u2_checksum] VARCHAR (25)  NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

