CREATE TABLE [dbo].[LD_SYS_PMT] (
    [LD_SYS_PMT_ID] VARCHAR (255) NOT NULL,
    [u2_id]         VARCHAR (255) NULL,
    [PMT_TYPES]     VARCHAR (9)   NULL,
    [time_stamp]    DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LD_SYS_PMT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LD_SYS_PMT_u2_id_in]
    ON [dbo].[LD_SYS_PMT]([u2_id] ASC);

