CREATE TABLE [dbo].[LDECK_ASSIGN] (
    [LDECK_ASSIGN_ID] VARCHAR (255) NOT NULL,
    [u2_id]           VARCHAR (255) NULL,
    [ASSIGN_INDEX]    VARCHAR (10)  NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LDECK_ASSIGN_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LDECK_ASSIGN_u2_id_in]
    ON [dbo].[LDECK_ASSIGN]([u2_id] ASC);

