CREATE TABLE [dbo].[LDECK_WI_ASSOC_INDEX] (
    [subValueId]     VARCHAR (255) NOT NULL,
    [LDECK_WI_ID]    VARCHAR (255) NULL,
    [WI_ASSOC_INDEX] VARCHAR (6)   NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LDECK_WI__LDECK_WI__82086]
    ON [dbo].[LDECK_WI_ASSOC_INDEX]([LDECK_WI_ID] ASC);

