CREATE TABLE [dbo].[LDECK_ASSIGN_ATTRS] (
    [subValueId]      VARCHAR (255)   NOT NULL,
    [LDECK_ASSIGN_ID] VARCHAR (255)   NULL,
    [ASSIGN_ATTRS]    VARCHAR (20)    NULL,
    [ASSIGN_INTEREST] NUMERIC (19, 8) NULL,
    [ASSIGN_OWNERS]   VARCHAR (8)     NULL,
    [time_stamp]      DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LDECK_ASS_LDECK_ASS_8802]
    ON [dbo].[LDECK_ASSIGN_ATTRS]([LDECK_ASSIGN_ID] ASC);

