CREATE TABLE [dbo].[LDECK_SESS] (
    [LDECK_SESS_ID]      VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [CHANGE_DATES]       DATETIME      NULL,
    [CONTROL_FLAG]       VARCHAR (4)   NULL,
    [CPY_FLG]            VARCHAR (4)   NULL,
    [EFF_DATES]          DATETIME      NULL,
    [EXPLANATIONS]       VARCHAR (246) NULL,
    [OWN_CHANGE_IDS]     VARCHAR (13)  NULL,
    [SESSIONS]           VARCHAR (4)   NULL,
    [SESSION_APPRS]      VARCHAR (3)   NULL,
    [SESSION_APPR_DATES] DATETIME      NULL,
    [SESSION_USER_ID]    VARCHAR (15)  NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LDECK_SESS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LDECK_SESS_u2_id_in]
    ON [dbo].[LDECK_SESS]([u2_id] ASC);

