CREATE TABLE [dbo].[LEASE_ERR] (
    [LEASE_ERR_ID] VARCHAR (255) NOT NULL,
    [u2_id]        VARCHAR (255) NULL,
    [ERRORS]       VARCHAR (76)  NULL,
    [time_stamp]   DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LEASE_ERR_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEASE_ERR_u2_id_in]
    ON [dbo].[LEASE_ERR]([u2_id] ASC);

