CREATE TABLE [dbo].[LEASE_PMT_TRCT_IDX] (
    [LEASE_PMT_TRCT_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [LEASE_PMT_TRACT_INDEX] VARCHAR (8)   NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LEASE_PMT_TRCT_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEASE_PMT_TRCT_IDX_u2_id_in]
    ON [dbo].[LEASE_PMT_TRCT_IDX]([u2_id] ASC);

