CREATE TABLE [dbo].[LEASE_PMT_ADJS] (
    [LEASE_PMT_ADJS_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LEASE_PMT_ADJS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEASE_PMT_ADJS_u2_id_in]
    ON [dbo].[LEASE_PMT_ADJS]([u2_id] ASC);

