CREATE TABLE [dbo].[LEASE] (
    [u2_id]                VARCHAR (255)   NOT NULL,
    [ABANDONMENT_CLAUSE]   VARCHAR (30)    NULL,
    [ACQUIRED_DATE]        DATETIME        NULL,
    [AID_NO]               VARCHAR (16)    NULL,
    [CC_TYPE]              VARCHAR (5)     NULL,
    [CHARGE_ACRES]         NUMERIC (19, 4) NULL,
    [CNV_ID]               VARCHAR (63)    NULL,
    [COMPANY]              VARCHAR (10)    NULL,
    [COMPLETE_FLAG]        VARCHAR (8)     NULL,
    [EFF_DATE]             DATETIME        NULL,
    [EXP_DATE]             DATETIME        NULL,
    [EXP_DATE_D4]          DATETIME        NULL,
    [GROSS_ACRES]          NUMERIC (19, 4) NULL,
    [IDEAS_COST_CENTER]    VARCHAR (12)    NULL,
    [LEASE_DATE]           DATETIME        NULL,
    [LEASE_TERM]           VARCHAR (5)     NULL,
    [LEASE_XREF]           VARCHAR (41)    NULL,
    [LEGAL_DESC]           TEXT            NULL,
    [LEGAL_HOLD]           VARCHAR (5)     NULL,
    [LESSEE]               VARCHAR (116)   NULL,
    [NAME]                 VARCHAR (482)   NULL,
    [OFFICE]               VARCHAR (6)     NULL,
    [ORIGINAL_GROSS_ACRES] NUMERIC (19, 4) NULL,
    [RECORD_TYPE]          VARCHAR (6)     NULL,
    [RENTAL_RESP]          VARCHAR (6)     NULL,
    [RIGHTS_TYPE]          VARCHAR (6)     NULL,
    [ROW_GROSS_FT]         NUMERIC (19, 2) NULL,
    [ROW_WIDTH]            VARCHAR (10)    NULL,
    [SERIAL_NO]            VARCHAR (34)    NULL,
    [SHADOW_KEY]           VARCHAR (17)    NULL,
    [TERMINATION_DATE]     DATETIME        NULL,
    [TERMINATION_REMARKS]  VARCHAR (241)   NULL,
    [TERMINATION_TYPE]     VARCHAR (4)     NULL,
    [TRACT_CTR]            VARCHAR (5)     NULL,
    [TYPE]                 VARCHAR (4)     NULL,
    [time_stamp]           DATETIME        NULL,
    [u2_checksum]          VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

