CREATE TABLE [dbo].[LEASE_BNS] (
    [LEASE_BNS_ID]   VARCHAR (255)   NOT NULL,
    [u2_id]          VARCHAR (255)   NULL,
    [AMT_TYPES]      VARCHAR (10)    NULL,
    [BONUS_PER_ACRE] NUMERIC (19, 2) NULL,
    [CO_BONUS_AMT]   NUMERIC (19, 2) NULL,
    [TOTAL_BONUS]    NUMERIC (19, 2) NULL,
    [time_stamp]     DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([LEASE_BNS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEASE_BNS_u2_id_in]
    ON [dbo].[LEASE_BNS]([u2_id] ASC);

