CREATE TABLE [dbo].[LEASE_LSR] (
    [LEASE_LSR_ID] VARCHAR (255) NOT NULL,
    [u2_id]        VARCHAR (255) NULL,
    [LESSOR]       VARCHAR (482) NULL,
    [time_stamp]   DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LEASE_LSR_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEASE_LSR_u2_id_in]
    ON [dbo].[LEASE_LSR]([u2_id] ASC);

