CREATE TABLE [dbo].[LEASE_CONTRACT] (
    [LEASE_CONTRACT_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [CONTRACTS]         VARCHAR (10)  NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LEASE_CONTRACT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEASE_CONTRACT_u2_id_in]
    ON [dbo].[LEASE_CONTRACT]([u2_id] ASC);

