CREATE TABLE [dbo].[LEASE_PMT_ADJ_TRACT_IDX] (
    [subValueId]  VARCHAR (255) NOT NULL,
    [TRANS_INDEX] VARCHAR (9)   NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEASE_PMT_subValueId_12679]
    ON [dbo].[LEASE_PMT_ADJ_TRACT_IDX]([subValueId] ASC);

