CREATE TABLE [dbo].[LEASE_PAY_IDX] (
    [LEASE_PAY_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [PAY_INDEX]        VARCHAR (10)  NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LEASE_PAY_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEASE_PAY_IDX_u2_id_in]
    ON [dbo].[LEASE_PAY_IDX]([u2_id] ASC);

