CREATE TABLE [dbo].[LEASE_PAY_PMT] (
    [LEASE_PAY_PMT_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [PMT_MOS]          VARCHAR (3)   NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LEASE_PAY_PMT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEASE_PAY_PMT_u2_id_in]
    ON [dbo].[LEASE_PAY_PMT]([u2_id] ASC);

