CREATE TABLE [dbo].[LEASE_PAYEE_IDX] (
    [LEASE_PAYEE_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [PAYEE_INDEX]        VARCHAR (9)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LEASE_PAYEE_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEASE_PAYEE_IDX_u2_id_in]
    ON [dbo].[LEASE_PAYEE_IDX]([u2_id] ASC);

