CREATE TABLE [dbo].[LEGAL_DESC_OFFSHORE] (
    [LEGAL_DESC_OFFSHORE_ID] VARCHAR (255)   NOT NULL,
    [u2_id]                  VARCHAR (255)   NULL,
    [OFFSHORE_AREAS]         VARCHAR (8)     NULL,
    [OFFSHORE_BLOCKS]        VARCHAR (5)     NULL,
    [OFFSHORE_GROSS_ACRES]   NUMERIC (19, 4) NULL,
    [time_stamp]             DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([LEGAL_DESC_OFFSHORE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEGAL_DESC_OFFSHORE_u2_id_in]
    ON [dbo].[LEGAL_DESC_OFFSHORE]([u2_id] ASC);

