CREATE TABLE [dbo].[LEGAL_DESC_ADDL_CTYS] (
    [LEGAL_DESC_ADDL_CTYS_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [ADDL_CTYS]               VARCHAR (6)   NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LEGAL_DESC_ADDL_CTYS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEGAL_DESC_ADDL_CTYS_u2_id_in]
    ON [dbo].[LEGAL_DESC_ADDL_CTYS]([u2_id] ASC);

