CREATE TABLE [dbo].[LEGAL_DESC_OFFSHORE_DESCS] (
    [subValueId]             VARCHAR (255) NOT NULL,
    [LEGAL_DESC_OFFSHORE_ID] VARCHAR (255) NULL,
    [OFFSHORE_DESCS]         VARCHAR (30)  NULL,
    [time_stamp]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEGAL_DES_LEGAL_DES_73501]
    ON [dbo].[LEGAL_DESC_OFFSHORE_DESCS]([LEGAL_DESC_OFFSHORE_ID] ASC);

