CREATE TABLE [dbo].[LEGAL_DESC_APPALACHIAN] (
    [LEGAL_DESC_APPALACHIAN_ID] VARCHAR (255) NOT NULL,
    [u2_id]                     VARCHAR (255) NULL,
    [AP_TOWNSHIP]               VARCHAR (8)   NULL,
    [AP_TOWNSHIP_DESCS]         VARCHAR (30)  NULL,
    [AP_TOWNSHIP_GROSS_ACRES]   VARCHAR (10)  NULL,
    [AP_TOWNSHIP_TAX_MAP]       VARCHAR (10)  NULL,
    [time_stamp]                DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LEGAL_DESC_APPALACHIAN_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEGAL_DES_u2_id_26438]
    ON [dbo].[LEGAL_DESC_APPALACHIAN]([u2_id] ASC);

