CREATE TABLE [dbo].[LEGAL_DESC_WELL_INFO_IDX] (
    [LEGAL_DESC_WELL_INFO_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                       VARCHAR (255) NULL,
    [WELL_INFO_INDEX]             VARCHAR (10)  NULL,
    [time_stamp]                  DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LEGAL_DESC_WELL_INFO_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEGAL_DES_u2_id_50271]
    ON [dbo].[LEGAL_DESC_WELL_INFO_IDX]([u2_id] ASC);

