CREATE TABLE [dbo].[LEGAL_DESC_ADDL_PROSPECTS] (
    [LEGAL_DESC_ADDL_PROSPECTS_ID] VARCHAR (255) NOT NULL,
    [u2_id]                        VARCHAR (255) NULL,
    [ADDL_PROSPECTS]               VARCHAR (9)   NULL,
    [time_stamp]                   DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LEGAL_DESC_ADDL_PROSPECTS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEGAL_DES_u2_id_26695]
    ON [dbo].[LEGAL_DESC_ADDL_PROSPECTS]([u2_id] ASC);

