CREATE TABLE [dbo].[LEGAL_DESC_TRACT_IDX] (
    [LEGAL_DESC_TRACT_IDX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [TRACT_INDEX]             VARCHAR (17)  NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LEGAL_DESC_TRACT_IDX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEGAL_DESC_TRACT_IDX_u2_id_in]
    ON [dbo].[LEGAL_DESC_TRACT_IDX]([u2_id] ASC);

