CREATE TABLE [dbo].[LEGAL_DESC_SURVEY_SEC_DESCS] (
    [subValueId]           VARCHAR (255)  NOT NULL,
    [LEGAL_DESC_SURVEY_ID] VARCHAR (255)  NULL,
    [SURVEY_SEC_DESCS]     VARCHAR (3079) NULL,
    [time_stamp]           DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LEGAL_DES_LEGAL_DES_80620]
    ON [dbo].[LEGAL_DESC_SURVEY_SEC_DESCS]([LEGAL_DESC_SURVEY_ID] ASC);

