CREATE TABLE [dbo].[LOE_ADJ_OGS] (
    [LOE_ADJ_OGS_ID] VARCHAR (255) NOT NULL,
    [u2_id]          VARCHAR (255) NULL,
    [OG_SALES]       VARCHAR (9)   NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LOE_ADJ_OGS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LOE_ADJ_OGS_u2_id_in]
    ON [dbo].[LOE_ADJ_OGS]([u2_id] ASC);

