CREATE TABLE [dbo].[LOE_ADJ_CTRC] (
    [LOE_ADJ_CTRC_ID] VARCHAR (255) NOT NULL,
    [u2_id]           VARCHAR (255) NULL,
    [CONTRACTS]       VARCHAR (15)  NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LOE_ADJ_CTRC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LOE_ADJ_CTRC_u2_id_in]
    ON [dbo].[LOE_ADJ_CTRC]([u2_id] ASC);

