CREATE TABLE [dbo].[LSE_CTRC_REMARKS] (
    [LSE_CTRC_REMARKS_ID]   VARCHAR (255)  NOT NULL,
    [u2_id]                 VARCHAR (255)  NULL,
    [CONTRACT_REMARKS]      VARCHAR (1952) NULL,
    [CONTRACT_REMARK_CODES] VARCHAR (9)    NULL,
    [CONTRACT_REMARK_DATES] DATETIME       NULL,
    [time_stamp]            DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([LSE_CTRC_REMARKS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LSE_CTRC_REMARKS_u2_id_in]
    ON [dbo].[LSE_CTRC_REMARKS]([u2_id] ASC);

