CREATE TABLE [dbo].[LSE_STATUS_PMT] (
    [LSE_STATUS_PMT_ID] VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [PMT_TYPES]         VARCHAR (9)   NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LSE_STATUS_PMT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LSE_STATUS_PMT_u2_id_in]
    ON [dbo].[LSE_STATUS_PMT]([u2_id] ASC);

