CREATE TABLE [dbo].[LSE_CTRC_TRACT_PARTICIPANT] (
    [LSE_CTRC_TRACT_PARTICIPANT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                         VARCHAR (255) NULL,
    [PARTICIPANT_ACTIVE_FLAGS]      VARCHAR (3)   NULL,
    [PARTICIPANT_CODES]             VARCHAR (11)  NULL,
    [PARTICIPANT_DESCS]             VARCHAR (33)  NULL,
    [PARTICIPANT_EFF_DATES]         DATETIME      NULL,
    [PARTICIPANT_EXP_DATES]         DATETIME      NULL,
    [time_stamp]                    DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LSE_CTRC_TRACT_PARTICIPANT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LSE_CTRC__u2_id_1221]
    ON [dbo].[LSE_CTRC_TRACT_PARTICIPANT]([u2_id] ASC);

