CREATE TABLE [dbo].[LSE_CTRC_TRACT_PART_INT] (
    [subValueId]                    VARCHAR (255)   NOT NULL,
    [LSE_CTRC_TRACT_PARTICIPANT_ID] VARCHAR (255)   NULL,
    [PARTICIPANTS]                  VARCHAR (12)    NULL,
    [PARTICIPANT_INTERESTS]         NUMERIC (19, 8) NULL,
    [time_stamp]                    DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LSE_CTRC__LSE_CTRC__2008]
    ON [dbo].[LSE_CTRC_TRACT_PART_INT]([LSE_CTRC_TRACT_PARTICIPANT_ID] ASC);

