CREATE TABLE [dbo].[LSE_CTRC_LINK] (
    [LSE_CTRC_LINK_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [IMAGE_REF]        VARCHAR (83)  NULL,
    [LINKS]            VARCHAR (83)  NULL,
    [LINK_TYPES]       VARCHAR (12)  NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LSE_CTRC_LINK_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LSE_CTRC_LINK_u2_id_in]
    ON [dbo].[LSE_CTRC_LINK]([u2_id] ASC);

