CREATE TABLE [dbo].[LSE_CTRC_ACQ] (
    [LSE_CTRC_ACQ_ID] VARCHAR (255) NOT NULL,
    [u2_id]           VARCHAR (255) NULL,
    [ACQUISITIONS]    VARCHAR (10)  NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LSE_CTRC_ACQ_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LSE_CTRC_ACQ_u2_id_in]
    ON [dbo].[LSE_CTRC_ACQ]([u2_id] ASC);

