CREATE TABLE [dbo].[LSE_CTRC_PROVS] (
    [LSE_CTRC_PROVS_ID]   VARCHAR (255)  NOT NULL,
    [u2_id]               VARCHAR (255)  NULL,
    [CONTRACT_PROV_DATES] DATETIME       NULL,
    [CONTRACT_PROV_DESCS] VARCHAR (2123) NULL,
    [CONTRACT_PROV_TYPES] VARCHAR (10)   NULL,
    [time_stamp]          DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([LSE_CTRC_PROVS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LSE_CTRC_PROVS_u2_id_in]
    ON [dbo].[LSE_CTRC_PROVS]([u2_id] ASC);

