CREATE TABLE [dbo].[LSE_CTRC_TRACT_SVY] (
    [LSE_CTRC_TRACT_SVY_ID] VARCHAR (255) NOT NULL,
    [u2_id]                 VARCHAR (255) NULL,
    [SURVEY_METHOD]         VARCHAR (6)   NULL,
    [time_stamp]            DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LSE_CTRC_TRACT_SVY_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LSE_CTRC_TRACT_SVY_u2_id_in]
    ON [dbo].[LSE_CTRC_TRACT_SVY]([u2_id] ASC);

