CREATE TABLE [dbo].[LSE_CTRC_WELL] (
    [LSE_CTRC_WELL_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [WELL_NAMES]       VARCHAR (33)  NULL,
    [WELL_NOS]         VARCHAR (15)  NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LSE_CTRC_WELL_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LSE_CTRC_WELL_u2_id_in]
    ON [dbo].[LSE_CTRC_WELL]([u2_id] ASC);

