CREATE TABLE [dbo].[LSE_CTRC_OBLS] (
    [LSE_CTRC_OBLS_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [OBL_DATES]        DATETIME      NULL,
    [OBL_END_DATES]    DATETIME      NULL,
    [OBL_PERIODS]      VARCHAR (6)   NULL,
    [OBL_REMARKS]      VARCHAR (303) NULL,
    [OBL_TYPES]        VARCHAR (8)   NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LSE_CTRC_OBLS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LSE_CTRC_OBLS_u2_id_in]
    ON [dbo].[LSE_CTRC_OBLS]([u2_id] ASC);

