CREATE TABLE [dbo].[LSE_CTRC_PARTIES] (
    [LSE_CTRC_PARTIES_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [PARTIES]             VARCHAR (56)  NULL,
    [PARTY_CODES]         VARCHAR (10)  NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([LSE_CTRC_PARTIES_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [LSE_CTRC_PARTIES_u2_id_in]
    ON [dbo].[LSE_CTRC_PARTIES]([u2_id] ASC);

