CREATE TABLE [dbo].[MDECK_WI_ASSOC_INDEX] (
    [subValueId]     VARCHAR (255) NOT NULL,
    [MDECK_WI_ID]    VARCHAR (255) NULL,
    [WI_ASSOC_INDEX] VARCHAR (5)   NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MDECK_WI__MDECK_WI__6001]
    ON [dbo].[MDECK_WI_ASSOC_INDEX]([MDECK_WI_ID] ASC);

