CREATE TABLE [dbo].[MDECK_WI_ENTERED_PRODUCTS] (
    [subValueId]        VARCHAR (255)   NOT NULL,
    [MDECK_WI_ID]       VARCHAR (255)   NULL,
    [WI_MANUAL_FLAG]    VARCHAR (3)     NULL,
    [WI_NRIS]           NUMERIC (19, 8) NULL,
    [WORKING_INTERESTS] NUMERIC (19, 8) NULL,
    [time_stamp]        DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MDECK_WI__MDECK_WI__13213]
    ON [dbo].[MDECK_WI_ENTERED_PRODUCTS]([MDECK_WI_ID] ASC);

