CREATE TABLE [dbo].[MDECK_CPT_INTERESTS] (
    [subValueId]         VARCHAR (255) NOT NULL,
    [MDECK_CPT_ID]       VARCHAR (255) NULL,
    [CPT_EFF_DATES]      DATETIME      NULL,
    [CPT_EFF_SESSIONS]   VARCHAR (7)   NULL,
    [CPT_EXEMPT_TYPES]   VARCHAR (6)   NULL,
    [CPT_EXP_DATES]      DATETIME      NULL,
    [CPT_EXP_SESSIONS]   VARCHAR (7)   NULL,
    [CPT_INTEREST_TYPES] VARCHAR (4)   NULL,
    [CPT_OWNERS]         VARCHAR (10)  NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MDECK_CPT_MDECK_CPT_26031]
    ON [dbo].[MDECK_CPT_INTERESTS]([MDECK_CPT_ID] ASC);

