CREATE TABLE [dbo].[MDECK_BUR_ASSOCS] (
    [MDECK_BUR_ASSOCS_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [ASSOC_DESC]          VARCHAR (30)  NULL,
    [ASSOC_NET_FLAGS]     VARCHAR (4)   NULL,
    [BUR_ASSOCS]          VARCHAR (6)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([MDECK_BUR_ASSOCS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MDECK_BUR_ASSOCS_u2_id_in]
    ON [dbo].[MDECK_BUR_ASSOCS]([u2_id] ASC);

