CREATE TABLE [dbo].[MDECK_NRI_ENTERED_PRODUCTS] (
    [subValueId]            VARCHAR (255)   NOT NULL,
    [MDECK_NRI_ID]          VARCHAR (255)   NULL,
    [NET_REVENUE_INTERESTS] NUMERIC (19, 8) NULL,
    [time_stamp]            DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MDECK_NRI_MDECK_NRI_8842]
    ON [dbo].[MDECK_NRI_ENTERED_PRODUCTS]([MDECK_NRI_ID] ASC);

