CREATE TABLE [dbo].[MDECK_CPT_INT_ENTERED_PRODUCTS] (
    [subValueId]        VARCHAR (255)   NOT NULL,
    [MDECK_CPT_ID]      VARCHAR (255)   NULL,
    [CPT_INTERESTS]     NUMERIC (19, 8) NULL,
    [TOTAL_CPT_ENTERED] NUMERIC (19, 8) NULL,
    [time_stamp]        DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MDECK_CPT_MDECK_CPT_77855]
    ON [dbo].[MDECK_CPT_INT_ENTERED_PRODUCTS]([MDECK_CPT_ID] ASC);

