CREATE TABLE [dbo].[MDECK_TOTAL_NRI_ENTERED] (
    [MDECK_TOTAL_NRI_ENTERED_ID] VARCHAR (255)   NOT NULL,
    [u2_id]                      VARCHAR (255)   NULL,
    [TOTAL_NRI_ENTERED]          NUMERIC (19, 8) NULL,
    [time_stamp]                 DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([MDECK_TOTAL_NRI_ENTERED_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MDECK_TOT_u2_id_14126]
    ON [dbo].[MDECK_TOTAL_NRI_ENTERED]([u2_id] ASC);

