CREATE TABLE [dbo].[MDECK] (
    [u2_id]               VARCHAR (255)   NOT NULL,
    [APPROVED_FLAG]       VARCHAR (4)     NULL,
    [BUR_COMPLETE_FLAG]   VARCHAR (7)     NULL,
    [CNV_ID]              VARCHAR (6)     NULL,
    [CNV_NAME]            VARCHAR (12)    NULL,
    [COMPANY]             VARCHAR (4)     NULL,
    [COST_CENTER]         VARCHAR (8)     NULL,
    [CPT_COMPLETE_FLAG]   VARCHAR (4)     NULL,
    [CREATE_TRACT]        VARCHAR (6)     NULL,
    [DESCRIPTION]         VARCHAR (240)   NULL,
    [DIV_ASSEM_ID]        VARCHAR (9)     NULL,
    [INACTIVE_DATE]       DATETIME        NULL,
    [INACTIVE_REASON]     VARCHAR (51)    NULL,
    [NRI_COMPLETE_FLAG]   VARCHAR (7)     NULL,
    [PARENT_DOI]          VARCHAR (6)     NULL,
    [PROPERTY]            VARCHAR (12)    NULL,
    [PROP_CHANGE_ID]      VARCHAR (10)    NULL,
    [RI_COMPLETE_FLAG]    VARCHAR (7)     NULL,
    [RPTG_DECK]           VARCHAR (4)     NULL,
    [TEMP_INTEREST]       NUMERIC (19, 8) NULL,
    [TEMP_PRODUCT]        VARCHAR (4)     NULL,
    [TEMP_WI_ASSOC_INDEX] VARCHAR (5)     NULL,
    [TRACT_NO]            VARCHAR (7)     NULL,
    [TRACT_PARTICIPATION] NUMERIC (19, 8) NULL,
    [TYPE]                VARCHAR (4)     NULL,
    [UNIT_RPTG_DECK]      VARCHAR (8)     NULL,
    [WI_COMPLETE_FLAG]    VARCHAR (7)     NULL,
    [time_stamp]          DATETIME        NULL,
    [u2_checksum]         VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

