CREATE TABLE [dbo].[MDECK_CPT] (
    [MDECK_CPT_ID]       VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [COMPONENTS]         VARCHAR (6)   NULL,
    [CPT_ALLOC_INT_CATS] VARCHAR (10)  NULL,
    [CPT_ALLOC_TYPES]    VARCHAR (5)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([MDECK_CPT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MDECK_CPT_u2_id_in]
    ON [dbo].[MDECK_CPT]([u2_id] ASC);

