CREATE TABLE [dbo].[MDECK_ASSIGN_INTERESTS] (
    [subValueId]       VARCHAR (255)   NOT NULL,
    [MDECK_ASSIGN_ID]  VARCHAR (255)   NULL,
    [ASSIGN_INTERESTS] NUMERIC (38, 8) NULL,
    [time_stamp]       DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MDECK_ASS_MDECK_ASS_3062]
    ON [dbo].[MDECK_ASSIGN_INTERESTS]([MDECK_ASSIGN_ID] ASC);

