CREATE TABLE [dbo].[MDECK_ASSIGN_OWNERS] (
    [subValueId]      VARCHAR (255) NOT NULL,
    [MDECK_ASSIGN_ID] VARCHAR (255) NULL,
    [ASSIGN_OWNERS]   VARCHAR (10)  NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MDECK_ASS_MDECK_ASS_83625]
    ON [dbo].[MDECK_ASSIGN_OWNERS]([MDECK_ASSIGN_ID] ASC);

