CREATE TABLE [dbo].[MDECK_ASSIGN] (
    [MDECK_ASSIGN_ID] VARCHAR (255) NOT NULL,
    [u2_id]           VARCHAR (255) NULL,
    [ASSIGN_INDEX]    VARCHAR (10)  NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([MDECK_ASSIGN_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MDECK_ASSIGN_u2_id_in]
    ON [dbo].[MDECK_ASSIGN]([u2_id] ASC);

