CREATE TABLE [dbo].[MEAS_PT_ALLOC] (
    [MEAS_PT_ALLOC_ID]    VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [ALLOC_ENT_EFF_DATES] DATETIME      NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([MEAS_PT_ALLOC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MEAS_PT_ALLOC_u2_id_in]
    ON [dbo].[MEAS_PT_ALLOC]([u2_id] ASC);

