CREATE TABLE [dbo].[MEAS_PT_CHILD_MEAS_PT] (
    [subValueId]          VARCHAR (255) NOT NULL,
    [MEAS_PT_CHILDREN_ID] VARCHAR (255) NULL,
    [CHILD_MEAS_PTS]      VARCHAR (12)  NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MEAS_PT_C_MEAS_PT_C_49423]
    ON [dbo].[MEAS_PT_CHILD_MEAS_PT]([MEAS_PT_CHILDREN_ID] ASC);

