CREATE TABLE [dbo].[MEAS_PT_STATUS_CTRC] (
    [MEAS_PT_STATUS_CTRC_ID] VARCHAR (255)   NOT NULL,
    [u2_id]                  VARCHAR (255)   NULL,
    [CONTRACTS]              VARCHAR (8)     NULL,
    [CONTRACT_VALUES]        NUMERIC (19, 2) NULL,
    [CONTRACT_VOLUMES]       NUMERIC (19, 2) NULL,
    [time_stamp]             DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([MEAS_PT_STATUS_CTRC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MEAS_PT_STATUS_CTRC_u2_id_in]
    ON [dbo].[MEAS_PT_STATUS_CTRC]([u2_id] ASC);

