CREATE TABLE [dbo].[METER_FORM_ARG] (
    [METER_FORM_ARG_ID]  VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [ARGUMENTS]          VARCHAR (14)  NULL,
    [ARGUMENT_OPERATORS] VARCHAR (8)   NULL,
    [ARGUMENT_PRODUCTS]  VARCHAR (3)   NULL,
    [ARGUMENT_TYPES]     VARCHAR (4)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([METER_FORM_ARG_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [METER_FORM_ARG_u2_id_in]
    ON [dbo].[METER_FORM_ARG]([u2_id] ASC);

