CREATE TABLE [dbo].[METER_PRD_IDX] (
    [subValueId]         VARCHAR (255) NOT NULL,
    [METER_FACILITY_ID]  VARCHAR (255) NULL,
    [PROD_FAC_PRD_INDEX] VARCHAR (15)  NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [METER_PRD_METER_FAC_63039]
    ON [dbo].[METER_PRD_IDX]([METER_FACILITY_ID] ASC);

