CREATE TABLE [dbo].[MMR_BSUSP_DET_IDX] (
    [subValueId]       VARCHAR (255) NOT NULL,
    [MMR_BSUSP_MMS_ID] VARCHAR (255) NULL,
    [DET_INDEX]        VARCHAR (10)  NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MMR_BSUSP_MMR_BSUSP_81016]
    ON [dbo].[MMR_BSUSP_DET_IDX]([MMR_BSUSP_MMS_ID] ASC);

