CREATE TABLE [dbo].[MMS_SYS_RIK] (
    [MMS_SYS_RIK_ID] VARCHAR (255) NOT NULL,
    [u2_id]          VARCHAR (255) NULL,
    [RIK_SA_CODES]   VARCHAR (5)   NULL,
    [RIK_SA_FLAGS]   VARCHAR (3)   NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([MMS_SYS_RIK_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MMS_SYS_RIK_u2_id_in]
    ON [dbo].[MMS_SYS_RIK]([u2_id] ASC);

