CREATE TABLE [dbo].[MMS_SYS] (
    [u2_id]                    VARCHAR (255)   NOT NULL,
    [AP_OPTION]                VARCHAR (3)     NULL,
    [BAL_AID_NO]               VARCHAR (13)    NULL,
    [BANK_ACCT]                VARCHAR (10)    NULL,
    [BKUP_PATH]                VARCHAR (11)    NULL,
    [CLRG_ACCT]                VARCHAR (10)    NULL,
    [CLRG_CC]                  VARCHAR (10)    NULL,
    [CONTACT_EMAIL]            VARCHAR (20)    NULL,
    [CONTACT_FAX]              VARCHAR (12)    NULL,
    [CONTACT_NAME]             VARCHAR (30)    NULL,
    [CONTACT_PHONE]            VARCHAR (12)    NULL,
    [CREATE_X12]               VARCHAR (6)     NULL,
    [DFLT_PRESSURE_BASE]       NUMERIC (19, 3) NULL,
    [ECA_PASSWORD]             VARCHAR (10)    NULL,
    [FILE_NAME]                VARCHAR (8)     NULL,
    [GAS_DEPR_ACCT]            VARCHAR (10)    NULL,
    [GRPCNTRLNUM]              VARCHAR (9)     NULL,
    [INDIAN_GAS_WRITEOFF_ACCT] VARCHAR (10)    NULL,
    [INDIAN_OIL_WRITEOFF_ACCT] VARCHAR (10)    NULL,
    [INTCHG_ID_QUAL]           VARCHAR (2)     NULL,
    [INTCHG_SENDER_QUAL]       VARCHAR (15)    NULL,
    [INT_CLRG_ACCT]            VARCHAR (10)    NULL,
    [INT_PAID_ACCT]            VARCHAR (10)    NULL,
    [INT_RECD_ACCT]            VARCHAR (10)    NULL,
    [JE_TYPE]                  VARCHAR (6)     NULL,
    [MAXWO_AMT]                NUMERIC (19, 2) NULL,
    [OIL_DEPR_ACCT]            VARCHAR (10)    NULL,
    [PAYOR_NO]                 VARCHAR (10)    NULL,
    [PAY_OFFSET_ACCT]          VARCHAR (10)    NULL,
    [PROCESS_LAG_MO]           NUMERIC (9)     NULL,
    [ROY_VOU_SRC]              VARCHAR (7)     NULL,
    [RPT_AUTH]                 VARCHAR (30)    NULL,
    [RPT_AUTO_DEL]             VARCHAR (4)     NULL,
    [RPT_COMPANY_NAME]         VARCHAR (30)    NULL,
    [RPT_DET_LEV]              VARCHAR (3)     NULL,
    [RPT_DSP_OPT]              VARCHAR (4)     NULL,
    [RPT_INT_CALC]             VARCHAR (3)     NULL,
    [RPT_PBASE]                NUMERIC (19, 3) NULL,
    [RPT_PBASE_TYPE]           VARCHAR (3)     NULL,
    [RPT_POST_AUDIT]           VARCHAR (3)     NULL,
    [RPT_PROC_FLAG]            VARCHAR (4)     NULL,
    [RPT_RVS_ADJ]              VARCHAR (4)     NULL,
    [RPT_SUM_ERR]              VARCHAR (3)     NULL,
    [SENDER_CODE]              VARCHAR (15)    NULL,
    [STCNTRLNUM]               VARCHAR (11)    NULL,
    [VOL_DIFF_CUTOFF]          VARCHAR (7)     NULL,
    [WRITEOFF_ACCT]            VARCHAR (10)    NULL,
    [time_stamp]               DATETIME        NULL,
    [u2_checksum]              VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

