CREATE TABLE [dbo].[MT_SYS_ACCT] (
    [MT_SYS_ACCT_ID]  VARCHAR (255) NOT NULL,
    [u2_id]           VARCHAR (255) NULL,
    [GAIN_LOSS_ACCTS] VARCHAR (10)  NULL,
    [SOURCE_ACCTS]    VARCHAR (10)  NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([MT_SYS_ACCT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MT_SYS_ACCT_u2_id_in]
    ON [dbo].[MT_SYS_ACCT]([u2_id] ASC);

