CREATE TABLE [dbo].[MT_SYS_AFE] (
    [MT_SYS_AFE_ID]  VARCHAR (255) NOT NULL,
    [u2_id]          VARCHAR (255) NULL,
    [AFE_ACCTS]      VARCHAR (9)   NULL,
    [POST_AFE_ACCTS] VARCHAR (9)   NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([MT_SYS_AFE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MT_SYS_AFE_u2_id_in]
    ON [dbo].[MT_SYS_AFE]([u2_id] ASC);

