CREATE TABLE [dbo].[NAME_VALID_COMPANIES] (
    [NAME_VALID_COMPANIES_ID] VARCHAR (255) NOT NULL,
    [u2_id]                   VARCHAR (255) NULL,
    [VALID_COMPANIES]         VARCHAR (5)   NULL,
    [time_stamp]              DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([NAME_VALID_COMPANIES_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NAME_VALID_COMPANIES_u2_id_in]
    ON [dbo].[NAME_VALID_COMPANIES]([u2_id] ASC);

