CREATE TABLE [dbo].[NAME] (
    [u2_id]             VARCHAR (255) NOT NULL,
    [ADDRESS1]          VARCHAR (34)  NULL,
    [ADDRESS2]          VARCHAR (30)  NULL,
    [ADDRESS3]          VARCHAR (30)  NULL,
    [ALT_LOOKUP]        VARCHAR (111) NULL,
    [APPR]              VARCHAR (4)   NULL,
    [APPR_DATE]         DATETIME      NULL,
    [BASE_ID]           VARCHAR (6)   NULL,
    [CITY]              VARCHAR (33)  NULL,
    [COUNTRY]           VARCHAR (6)   NULL,
    [DELIVERY_CODE]     VARCHAR (2)   NULL,
    [ENTITY_TYPE]       VARCHAR (6)   NULL,
    [LAND_TEN99_EXEMPT] VARCHAR (6)   NULL,
    [NAME1]             VARCHAR (35)  NULL,
    [NAME2]             VARCHAR (35)  NULL,
    [NAME3]             VARCHAR (33)  NULL,
    [NAME_CONTROL_1099] VARCHAR (7)   NULL,
    [RESIDENCE_STATE]   VARCHAR (3)   NULL,
    [SITE]              VARCHAR (3)   NULL,
    [SORT_KEY]          VARCHAR (87)  NULL,
    [STATE]             VARCHAR (3)   NULL,
    [TAX_ENTITY_TYPE]   VARCHAR (6)   NULL,
    [TAX_ID]            VARCHAR (11)  NULL,
    [TEN99_ADDRESS]     VARCHAR (40)  NULL,
    [TEN99_CITY]        VARCHAR (27)  NULL,
    [TEN99_STATE]       VARCHAR (5)   NULL,
    [TEN99_TIN_TYPE]    VARCHAR (4)   NULL,
    [TEN99_ZIP]         VARCHAR (10)  NULL,
    [TIN_2ND_NOTICE]    VARCHAR (6)   NULL,
    [W8]                VARCHAR (2)   NULL,
    [W8_EFF_DATE]       DATETIME      NULL,
    [W9]                VARCHAR (2)   NULL,
    [W9_EFF_DATE]       DATETIME      NULL,
    [ZIP]               VARCHAR (12)  NULL,
    [time_stamp]        DATETIME      NULL,
    [u2_checksum]       VARCHAR (25)  NULL
);

