CREATE TABLE [dbo].[OBD_CC_ALLOC_HDR] (
    [u2_id]         VARCHAR (255) NOT NULL,
    [ALLOC_BASIS]   VARCHAR (5)   NULL,
    [COMPANY]       VARCHAR (3)   NULL,
    [CONTRA_ACCT]   VARCHAR (12)  NULL,
    [COST_CENTER]   VARCHAR (6)   NULL,
    [DESCRIPTION]   VARCHAR (30)  NULL,
    [INACTIVE_DATE] DATETIME      NULL,
    [MAJOR_ACCT]    VARCHAR (6)   NULL,
    [SUB_ACCT]      VARCHAR (6)   NULL,
    [time_stamp]    DATETIME      NULL,
    [u2_checksum]   VARCHAR (25)  NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

