CREATE TABLE [dbo].[OBD_BDECK_ASSN_OWN] (
    [subValueId]        VARCHAR (255)   NOT NULL,
    [OBD_BDECK_ASSN_ID] VARCHAR (255)   NULL,
    [ASSIGN_ATTRS]      VARCHAR (15)    NULL,
    [ASSIGN_INTEREST]   NUMERIC (19, 8) NULL,
    [ASSIGN_OWNERS]     VARCHAR (7)     NULL,
    [time_stamp]        DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OBD_BDECK_OBD_BDECK_71118]
    ON [dbo].[OBD_BDECK_ASSN_OWN]([OBD_BDECK_ASSN_ID] ASC);

