CREATE TABLE [dbo].[OBDCTL_ACCT] (
    [OBDCTL_ACCT_ID] VARCHAR (255) NOT NULL,
    [u2_id]          VARCHAR (255) NULL,
    [OFFSET_ACCTS]   VARCHAR (12)  NULL,
    [TARGET_ACCTS]   VARCHAR (12)  NULL,
    [time_stamp]     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OBDCTL_ACCT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OBDCTL_ACCT_u2_id_in]
    ON [dbo].[OBDCTL_ACCT]([u2_id] ASC);

