CREATE TABLE [dbo].[OBDCC_INFO_OH] (
    [OBDCC_INFO_OH_ID] VARCHAR (255) NOT NULL,
    [u2_id]            VARCHAR (255) NULL,
    [OH_TYPES]         VARCHAR (10)  NULL,
    [time_stamp]       DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OBDCC_INFO_OH_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OBDCC_INFO_OH_u2_id_in]
    ON [dbo].[OBDCC_INFO_OH]([u2_id] ASC);

