CREATE TABLE [dbo].[OBDCC_INFO_EFF_DT] (
    [OBDCC_INFO_EFF_DT_ID] VARCHAR (255) NOT NULL,
    [u2_id]                VARCHAR (255) NULL,
    [WELL_COUNT_EFF_DATES] DATETIME      NULL,
    [time_stamp]           DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OBDCC_INFO_EFF_DT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OBDCC_INFO_EFF_DT_u2_id_in]
    ON [dbo].[OBDCC_INFO_EFF_DT]([u2_id] ASC);

