CREATE TABLE [dbo].[OFP_DRIVER_TRANS_ADJ] (
    [OFP_DRIVER_TRANS_ADJ_ID] VARCHAR (255)   NOT NULL,
    [u2_id]                   VARCHAR (255)   NULL,
    [ADJ_BROKER_AMTS]         NUMERIC (19, 2) NULL,
    [ADJ_DRIVER_AMTS]         NUMERIC (19, 2) NULL,
    [ADJ_TYPES]               VARCHAR (4)     NULL,
    [time_stamp]              DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([OFP_DRIVER_TRANS_ADJ_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OFP_DRIVER_TRANS_ADJ_u2_id_in]
    ON [dbo].[OFP_DRIVER_TRANS_ADJ]([u2_id] ASC);

