CREATE TABLE [dbo].[OFP_PROP_DISB] (
    [subValueId]         VARCHAR (255) NOT NULL,
    [OFP_PROP_CPARTY_ID] VARCHAR (255) NULL,
    [DISBURSE_CODES]     VARCHAR (5)   NULL,
    [DISBURSE_EFF_DATES] DATETIME      NULL,
    [DISBURSE_EXP_DATES] DATETIME      NULL,
    [DISBURSE_REMARKS]   VARCHAR (20)  NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OFP_PROP__OFP_PROP__24749]
    ON [dbo].[OFP_PROP_DISB]([OFP_PROP_CPARTY_ID] ASC);

