CREATE TABLE [dbo].[OFP_PROP_CTRC] (
    [subValueId]           VARCHAR (255)   NOT NULL,
    [OFP_PROP_PRC_IDX_ID]  VARCHAR (255)   NULL,
    [PRICE_CTRC_EFF_DATES] DATETIME        NULL,
    [PRICE_CTRC_EXP_DATES] DATETIME        NULL,
    [PRICE_CTRC_INTERESTS] NUMERIC (19, 8) NULL,
    [STMT_RPT_LEVEL]       VARCHAR (5)     NULL,
    [time_stamp]           DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([subValueId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OFP_PROP__OFP_PROP__39356]
    ON [dbo].[OFP_PROP_CTRC]([OFP_PROP_PRC_IDX_ID] ASC);

