CREATE TABLE [dbo].[OFP_PROP_OP] (
    [OFP_PROP_OP_ID]    VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [TEMP_OPERATORS]    VARCHAR (8)   NULL,
    [TEMP_OP_EFF_DATES] DATETIME      NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OFP_PROP_OP_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OFP_PROP_OP_u2_id_in]
    ON [dbo].[OFP_PROP_OP]([u2_id] ASC);

