CREATE TABLE [dbo].[OFP_PROP_PUR] (
    [OFP_PROP_PUR_ID]    VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [TEMP_PURCHASERS]    VARCHAR (9)   NULL,
    [TEMP_PUR_EFF_DATES] DATETIME      NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OFP_PROP_PUR_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OFP_PROP_PUR_u2_id_in]
    ON [dbo].[OFP_PROP_PUR]([u2_id] ASC);

