CREATE TABLE [dbo].[OG_CTRC_CPTS] (
    [OG_CTRC_CPTS_ID]    VARCHAR (255)   NOT NULL,
    [u2_id]              VARCHAR (255)   NULL,
    [COMPONENTS]         VARCHAR (6)     NULL,
    [CPT_ALLOC_INT_CATS] VARCHAR (5)     NULL,
    [CPT_ALLOC_TYPES]    VARCHAR (5)     NULL,
    [TOTAL_CPT_ENTERED]  NUMERIC (19, 8) NULL,
    [time_stamp]         DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([OG_CTRC_CPTS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OG_CTRC_CPTS_u2_id_in]
    ON [dbo].[OG_CTRC_CPTS]([u2_id] ASC);

