CREATE TABLE [dbo].[OG_CTRC_DESC] (
    [OG_CTRC_DESC_ID] VARCHAR (255) NOT NULL,
    [u2_id]           VARCHAR (255) NULL,
    [DESCRIPTION]     VARCHAR (30)  NULL,
    [time_stamp]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OG_CTRC_DESC_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OG_CTRC_DESC_u2_id_in]
    ON [dbo].[OG_CTRC_DESC]([u2_id] ASC);

