CREATE TABLE [dbo].[OG_CTRC_REMIT] (
    [OG_CTRC_REMIT_ID]  VARCHAR (255) NOT NULL,
    [u2_id]             VARCHAR (255) NULL,
    [REMITTER]          VARCHAR (9)   NULL,
    [REMITTER_PROPERTY] VARCHAR (12)  NULL,
    [time_stamp]        DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OG_CTRC_REMIT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OG_CTRC_REMIT_u2_id_in]
    ON [dbo].[OG_CTRC_REMIT]([u2_id] ASC);

