CREATE TABLE [dbo].[OG_MMR_DET_AUDIT] (
    [OG_MMR_DET_AUDIT_ID] VARCHAR (255) NOT NULL,
    [u2_id]               VARCHAR (255) NULL,
    [SYSTEM_DATE]         DATETIME      NULL,
    [SYSTEM_TIME]         VARCHAR (10)  NULL,
    [SYSTEM_USER_ID]      VARCHAR (4)   NULL,
    [time_stamp]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OG_MMR_DET_AUDIT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OG_MMR_DET_AUDIT_u2_id_in]
    ON [dbo].[OG_MMR_DET_AUDIT]([u2_id] ASC);

