CREATE TABLE [dbo].[OG_MMR_RPT_RVSL] (
    [OG_MMR_RPT_RVSL_ID] VARCHAR (255) NOT NULL,
    [u2_id]              VARCHAR (255) NULL,
    [RVSL_INDEX]         VARCHAR (8)   NULL,
    [time_stamp]         DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OG_MMR_RPT_RVSL_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OG_MMR_RPT_RVSL_u2_id_in]
    ON [dbo].[OG_MMR_RPT_RVSL]([u2_id] ASC);

