CREATE TABLE [dbo].[OG_MMR_RPT] (
    [u2_id]             VARCHAR (255)   NOT NULL,
    [ACCTG_PERIOD]      DATETIME        NULL,
    [ADJ_CD]            VARCHAR (2)     NULL,
    [AGREEMENT_NO]      VARCHAR (11)    NULL,
    [AID_NO]            VARCHAR (11)    NULL,
    [BAL_FWD_RVSL_FLAG] VARCHAR (4)     NULL,
    [BREAK_FLAG]        VARCHAR (1)     NULL,
    [BTU_FACTOR]        VARCHAR (4)     NULL,
    [CALC_METH]         VARCHAR (4)     NULL,
    [COMPANY]           VARCHAR (3)     NULL,
    [DOC_NO]            VARCHAR (6)     NULL,
    [ERR_ADJ_CD]        VARCHAR (6)     NULL,
    [GROSS_VAL]         NUMERIC (19, 2) NULL,
    [GROSS_VOL]         NUMERIC (19, 2) NULL,
    [LSE_TYPE]          VARCHAR (3)     NULL,
    [MMBTU]             NUMERIC (19, 2) NULL,
    [MMS_PAD_NO]        VARCHAR (8)     NULL,
    [MMS_PRD_CD]        VARCHAR (3)     NULL,
    [MMS_RECEIPT_DATE]  DATETIME        NULL,
    [MMS_REVERSAL_FLAG] VARCHAR (4)     NULL,
    [OMIT_2014]         VARCHAR (4)     NULL,
    [PAYOR]             VARCHAR (7)     NULL,
    [PERIOD_END]        DATETIME        NULL,
    [PMT_DATE]          DATETIME        NULL,
    [PMT_METH]          VARCHAR (4)     NULL,
    [PRC_AMT]           NUMERIC (19, 2) NULL,
    [REFERENCE_NO]      VARCHAR (9)     NULL,
    [REG_PRICE]         VARCHAR (3)     NULL,
    [REVRBK_CD]         VARCHAR (5)     NULL,
    [ROY_VAL]           NUMERIC (19, 2) NULL,
    [ROY_VOL]           NUMERIC (19, 2) NULL,
    [SALE_MMYY]         VARCHAR (4)     NULL,
    [SA_CODE]           VARCHAR (4)     NULL,
    [SYSTEM_DATE]       DATETIME        NULL,
    [SYSTEM_TIME]       VARCHAR (8)     NULL,
    [SYSTEM_USER_ID]    VARCHAR (7)     NULL,
    [TRANS_AMT]         NUMERIC (19, 2) NULL,
    [TRANS_CD]          VARCHAR (3)     NULL,
    [VOUCHER_NO]        VARCHAR (13)    NULL,
    [time_stamp]        DATETIME        NULL,
    [u2_checksum]       VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

