CREATE TABLE [dbo].[OG_MMR_DET] (
    [u2_id]             VARCHAR (255)   NOT NULL,
    [ACCTG_PERIOD]      DATETIME        NULL,
    [ADJ_CD]            VARCHAR (3)     NULL,
    [ADJ_REAS_CD]       VARCHAR (3)     NULL,
    [AGREEMENT_NO]      VARCHAR (11)    NULL,
    [AID_NO]            VARCHAR (11)    NULL,
    [AID_TYPE]          VARCHAR (1)     NULL,
    [APP]               VARCHAR (8)     NULL,
    [BREAK_FLAG]        VARCHAR (3)     NULL,
    [BTU_FACTOR]        NUMERIC (9)     NULL,
    [CALC_METH]         VARCHAR (2)     NULL,
    [COMPANY]           VARCHAR (3)     NULL,
    [COST_CENTER]       VARCHAR (6)     NULL,
    [CPT]               VARCHAR (6)     NULL,
    [CTRC_NO]           VARCHAR (8)     NULL,
    [GROSS_VAL]         NUMERIC (19, 2) NULL,
    [GROSS_VOL]         NUMERIC (19, 2) NULL,
    [INDEX_PRICE]       NUMERIC (19, 5) NULL,
    [LSE_TYPE]          VARCHAR (1)     NULL,
    [MMS_PAYABLES_ACCT] VARCHAR (10)    NULL,
    [MMS_PRD]           VARCHAR (3)     NULL,
    [OG_MMR_RPT_ID]     VARCHAR (8)     NULL,
    [OMIT_2014]         VARCHAR (3)     NULL,
    [OWNER_SALE_INDEX]  VARCHAR (10)    NULL,
    [PART_DEC]          NUMERIC (19, 8) NULL,
    [PAYEE_NO]          VARCHAR (9)     NULL,
    [PERIOD_END]        DATETIME        NULL,
    [PMT_CD]            VARCHAR (3)     NULL,
    [PRC_AMT]           NUMERIC (19, 2) NULL,
    [PRESSURE_BASE]     NUMERIC (19, 3) NULL,
    [PROPERTY]          VARCHAR (15)    NULL,
    [QUAL_MEAS]         NUMERIC (9)     NULL,
    [REFERENCE_NO]      VARCHAR (9)     NULL,
    [REVENUE_PRICE]     NUMERIC (19, 5) NULL,
    [REVERSAL_FLAG]     VARCHAR (1)     NULL,
    [RIK_FLAG]          VARCHAR (3)     NULL,
    [ROY_DEC]           NUMERIC (19, 8) NULL,
    [ROY_VAL]           NUMERIC (19, 2) NULL,
    [ROY_VOL]           NUMERIC (19, 2) NULL,
    [RV_ROY_VAL]        NUMERIC (19, 2) NULL,
    [SALE_DATE]         DATETIME        NULL,
    [SA_CODE]           VARCHAR (4)     NULL,
    [STATUS]            VARCHAR (3)     NULL,
    [TRANS_AMT]         NUMERIC (19, 2) NULL,
    [TRANS_CD]          VARCHAR (3)     NULL,
    [TRANS_OVERCD]      VARCHAR (3)     NULL,
    [WELL_AMT]          NUMERIC (19, 2) NULL,
    [WELL_NO]           VARCHAR (10)    NULL,
    [time_stamp]        DATETIME        NULL,
    [u2_checksum]       VARCHAR (25)    NULL,
    PRIMARY KEY CLUSTERED ([u2_id] ASC)
);

