CREATE TABLE [dbo].[OG_SALE_ALLOC_OG_SALE_INDEX] (
    [OG_SALE_ALLOC_OG_SALE_INDEX_ID] VARCHAR (255) NOT NULL,
    [u2_id]                          VARCHAR (255) NULL,
    [ALLOC_OG_SALE_INDEX]            VARCHAR (10)  NULL,
    [time_stamp]                     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([OG_SALE_ALLOC_OG_SALE_INDEX_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [OG_SALE_A_u2_id_45752]
    ON [dbo].[OG_SALE_ALLOC_OG_SALE_INDEX]([u2_id] ASC);

