

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[usp_InsertToCombinedFromStg] 
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	INSERT INTO Combined
	(
	[Source]
      ,[TabName]
      ,[Job Title]
      ,[Job Code]
      ,[Inc]
      ,[Cos]
      ,[Effective Date]
      ,[Base 25th Percentile]
      ,[Base 50th Percentile]
      ,[Base 75th Percentile]
      ,[Base 90th Percentile]
      ,[Actual TC 25th Percentile]
      ,[Actual TC 50th Percentile]
      ,[Actual TC 75th Percentile]
      ,[Actual TC 90th Percentile]
      ,[Target TC 25th Percentile]
      ,[Target TC 50th Percentile]
      ,[Target TC 75th Percentile]
      ,[Target TC 90th Percentile]
      ,[LTI 25th Percentile]
      ,[LTI 50th Percentile]
      ,[LTI 75th Percentile]
      ,[LTI 90th Percentile]
      ,[Total Direct Actual 25th Percentile]
      ,[Total Direct Actual 50th Percentile]
      ,[Total Direct Actual 75th Percentile]
      ,[Total Direct Actual 90th Percentile]
      ,[Target TDC 25th Percentile]
      ,[Target TDC 50th Percentile]
      ,[Target TDC 75th Percentile]
      ,[Target TDC 90th Percentile]
      ,[Industry]
      ,[Corporate-Noncorporate]
      ,[Rev Responsibility-Location-Other]
      ,[Family]
      ,[Sub-Family]
      ,[Specialization]
      ,[Job Description]
      ,[Mercer Job Type]
      ,[AonHewitt Scope From]
      ,[AonHewitt Scope To]
      ,[AonHewitt Scope Desc]
      ,[AI Percentage 25th Percentile]
      ,[AI Percentage 50th Percentile]
      ,[AI Percentage 75th Percentile]
      ,[AI Percentage 90th Percentile]
      ,[LTI Percent of Base 25th Percentile]
      ,[LTI Percent of Base 50th Percentile]
      ,[LTI Percent of Base 75th Percentile]
      ,[LTI Percent of Base 90th Percentile]
      ,[Calc AI % 25th Percentile]
      ,[Calc AI % 50th Percentile]
      ,[Calc AI % 75th Percentile]
      ,[Calc AI % 90th Percentile]
      ,[Calc LTI % 25th Percentile]
      ,[Calc LTI % 50th Percentile]
      ,[Calc LTI % 75th Percentile]
      ,[Calc LTI % 90th Percentile]
      ,[CreatedDate]
	)
	SELECT 
      [Source]
      ,[TabName]
      ,[Job Title]
      ,[Job Code]
      ,[Inc]
      ,[Cos]
      ,[Effective Date]
      ,[Base 25th Percentile]
      ,[Base 50th Percentile]
      ,[Base 75th Percentile]
      ,[Base 90th Percentile]
      ,[Actual TC 25th Percentile]
      ,[Actual TC 50th Percentile]
      ,[Actual TC 75th Percentile]
      ,[Actual TC 90th Percentile]
      ,[Target TC 25th Percentile]
      ,[Target TC 50th Percentile]
      ,[Target TC 75th Percentile]
      ,[Target TC 90th Percentile]
      ,[LTI 25th Percentile]
      ,[LTI 50th Percentile]
      ,[LTI 75th Percentile]
      ,[LTI 90th Percentile]
      ,[Total Direct Actual 25th Percentile]
      ,[Total Direct Actual 50th Percentile]
      ,[Total Direct Actual 75th Percentile]
      ,[Total Direct Actual 90th Percentile]
      ,[Target TDC 25th Percentile]
      ,[Target TDC 50th Percentile]
      ,[Target TDC 75th Percentile]
      ,[Target TDC 90th Percentile]
      ,[Industry]
      ,[Corporate-Noncorporate]
      ,[Rev Responsibility-Location-Other]
      ,[Family]
      ,[Sub-Family]
      ,[Specialization]
      ,[Job Description]
      ,[Mercer Job Type]
      ,[AonHewitt Scope From]
      ,[AonHewitt Scope To]
      ,[AonHewitt Scope Desc]
      ,[AI Percentage 25th Percentile]
      ,[AI Percentage 50th Percentile]
      ,[AI Percentage 75th Percentile]
      ,[AI Percentage 90th Percentile]
      ,[LTI Percent of Base 25th Percentile]
      ,[LTI Percent of Base 50th Percentile]
      ,[LTI Percent of Base 75th Percentile]
      ,[LTI Percent of Base 90th Percentile]
      ,[Calc AI % 25th Percentile]
      ,[Calc AI % 50th Percentile]
      ,[Calc AI % 75th Percentile]
      ,[Calc AI % 90th Percentile]
      ,[Calc LTI % 25th Percentile]
      ,[Calc LTI % 50th Percentile]
      ,[Calc LTI % 75th Percentile]
      ,[Calc LTI % 90th Percentile]
      ,[CreatedDate]
  FROM [dbo].[Combined_STG]
  where [Job Code] is not null;

END
GO
GRANT EXECUTE
    ON OBJECT::[dbo].[usp_InsertToCombinedFromStg] TO [RunCompModel]
    AS [dbo];

