








-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[usp_UpdateCombinedIndexed] 
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	truncate table Combined_Indexed;
	INSERT INTO Combined_Indexed
	(
	[Source]
      ,[TabName]
      ,[Job Title]
      ,[Job Code]
      ,[Inc]
      ,[Cos]
      ,[Effective Date]
      ,[Base 25th Percentile]
      ,[Base 50th Percentile]
      ,[Base 75th Percentile]
      ,[Base 90th Percentile]
      ,[Actual TC 25th Percentile]
      ,[Actual TC 50th Percentile]
      ,[Actual TC 75th Percentile]
      ,[Actual TC 90th Percentile]
      ,[Target TC 25th Percentile]
      ,[Target TC 50th Percentile]
      ,[Target TC 75th Percentile]
      ,[Target TC 90th Percentile]
      ,[LTI 25th Percentile]
      ,[LTI 50th Percentile]
      ,[LTI 75th Percentile]
      ,[LTI 90th Percentile]
      ,[Total Direct Actual 25th Percentile]
      ,[Total Direct Actual 50th Percentile]
      ,[Total Direct Actual 75th Percentile]
      ,[Total Direct Actual 90th Percentile]
      ,[Target TDC 25th Percentile]
      ,[Target TDC 50th Percentile]
      ,[Target TDC 75th Percentile]
      ,[Target TDC 90th Percentile]
      ,[Industry]
      ,[Corporate-Noncorporate]
      ,[Rev Responsibility-Location-Other]
      ,[Family]
      ,[Sub-Family]
      ,[Specialization]
      ,[Job Description]
      ,[Mercer Job Type]
      ,[AonHewitt Scope From]
      ,[AonHewitt Scope To]
      ,[AonHewitt Scope Desc]
      ,[AI Percentage 25th Percentile]
      ,[AI Percentage 50th Percentile]
      ,[AI Percentage 75th Percentile]
      ,[AI Percentage 90th Percentile]
      ,[LTI Percent of Base 25th Percentile]
      ,[LTI Percent of Base 50th Percentile]
      ,[LTI Percent of Base 75th Percentile]
      ,[LTI Percent of Base 90th Percentile]
      ,[Calc AI % 25th Percentile]
      ,[Calc AI % 50th Percentile]
      ,[Calc AI % 75th Percentile]
      ,[Calc AI % 90th Percentile]
      ,[Calc LTI % 25th Percentile]
      ,[Calc LTI % 50th Percentile]
      ,[Calc LTI % 75th Percentile]
      ,[Calc LTI % 90th Percentile]
      ,[CreatedDate]
	  ,[UID]
	  ,[OrgCode]
	  ,[YearCode]
	  ,[PublisherCode]
	  ,[TypeCode]
	  ,[WeightCode]
	  ,[CorpCode]
	  ,[IndustryCode]
	  ,[RegionCode]
	  ,[DeptCode]
	  ,[DetailCode]
	  ,[SubRegionCode]
	  ,[StateCode]
	  ,[CityCode]
	  ,[ScopeCode]
	)
	SELECT 
      [Source]
      ,[TabName]
      ,[Job Title]
      ,[Job Code]
      ,[Inc]
      ,[Cos]
      ,[Effective Date]
      ,[Base 25th Percentile]
      ,[Base 50th Percentile]
      ,[Base 75th Percentile]
      ,[Base 90th Percentile]
      ,[Actual TC 25th Percentile]
      ,[Actual TC 50th Percentile]
      ,[Actual TC 75th Percentile]
      ,[Actual TC 90th Percentile]
      ,[Target TC 25th Percentile]
      ,[Target TC 50th Percentile]
      ,[Target TC 75th Percentile]
      ,[Target TC 90th Percentile]
      ,[LTI 25th Percentile]
      ,[LTI 50th Percentile]
      ,[LTI 75th Percentile]
      ,[LTI 90th Percentile]
      ,[Total Direct Actual 25th Percentile]
      ,[Total Direct Actual 50th Percentile]
      ,[Total Direct Actual 75th Percentile]
      ,[Total Direct Actual 90th Percentile]
      ,[Target TDC 25th Percentile]
      ,[Target TDC 50th Percentile]
      ,[Target TDC 75th Percentile]
      ,[Target TDC 90th Percentile]
      ,[Industry]
      ,[Corporate-Noncorporate]
      ,[Rev Responsibility-Location-Other]
      ,[Family]
      ,[Sub-Family]
      ,[Specialization]
      ,[Job Description]
      ,[Mercer Job Type]
      ,[AonHewitt Scope From]
      ,[AonHewitt Scope To]
      ,[AonHewitt Scope Desc]
      ,[AI Percentage 25th Percentile]
      ,[AI Percentage 50th Percentile]
      ,[AI Percentage 75th Percentile]
      ,[AI Percentage 90th Percentile]
      ,[LTI Percent of Base 25th Percentile]
      ,[LTI Percent of Base 50th Percentile]
      ,[LTI Percent of Base 75th Percentile]
      ,[LTI Percent of Base 90th Percentile]
      ,[Calc AI % 25th Percentile]
      ,[Calc AI % 50th Percentile]
      ,[Calc AI % 75th Percentile]
      ,[Calc AI % 90th Percentile]
      ,[Calc LTI % 25th Percentile]
      ,[Calc LTI % 50th Percentile]
      ,[Calc LTI % 75th Percentile]
      ,[Calc LTI % 90th Percentile]
      ,[CreatedDate]
	  ,[UID]
	  ,[OrgCode]
	  ,[YearCode]
	  ,[PublisherCode]
	  ,[TypeCode]
	  ,[WeightCode]
	  ,[CorpCode]
	  ,[IndustryCode]
	  ,[RegionCode]
	  ,[DeptCode]
	  ,[DetailCode]
	  ,[SubRegionCode]
	  ,[StateCode]
	  ,[CityCode]
	  ,[ScopeCode]
  FROM 
	(
	SELECT
		[Source]
      ,[TabName]
      ,[Job Title]
      ,[Job Code]
      ,[Inc]
      ,[Cos]
      ,[Effective Date]
      ,[Base 25th Percentile]
      ,[Base 50th Percentile]
      ,[Base 75th Percentile]
      ,[Base 90th Percentile]
      ,[Actual TC 25th Percentile]
      ,[Actual TC 50th Percentile]
      ,[Actual TC 75th Percentile]
      ,[Actual TC 90th Percentile]
      ,[Target TC 25th Percentile]
      ,[Target TC 50th Percentile]
      ,[Target TC 75th Percentile]
      ,[Target TC 90th Percentile]
      ,[LTI 25th Percentile]
      ,[LTI 50th Percentile]
      ,[LTI 75th Percentile]
      ,[LTI 90th Percentile]
      ,[Total Direct Actual 25th Percentile]
      ,[Total Direct Actual 50th Percentile]
      ,[Total Direct Actual 75th Percentile]
      ,[Total Direct Actual 90th Percentile]
      ,[Target TDC 25th Percentile]
      ,[Target TDC 50th Percentile]
      ,[Target TDC 75th Percentile]
      ,[Target TDC 90th Percentile]
      ,[Industry]
      ,[Corporate-Noncorporate]
      ,[Rev Responsibility-Location-Other]
      ,[Family]
      ,[Sub-Family]
      ,[Specialization]
      ,[Job Description]
      ,[Mercer Job Type]
      ,[AonHewitt Scope From]
      ,[AonHewitt Scope To]
      ,[AonHewitt Scope Desc]
      ,[AI Percentage 25th Percentile]
      ,[AI Percentage 50th Percentile]
      ,[AI Percentage 75th Percentile]
      ,[AI Percentage 90th Percentile]
      ,[LTI Percent of Base 25th Percentile]
      ,[LTI Percent of Base 50th Percentile]
      ,[LTI Percent of Base 75th Percentile]
      ,[LTI Percent of Base 90th Percentile]
      ,[Calc AI % 25th Percentile]
      ,[Calc AI % 50th Percentile]
      ,[Calc AI % 75th Percentile]
      ,[Calc AI % 90th Percentile]
      ,[Calc LTI % 25th Percentile]
      ,[Calc LTI % 50th Percentile]
      ,[Calc LTI % 75th Percentile]
      ,[Calc LTI % 90th Percentile]
      ,[CreatedDate]
	  ,[UID]
	  ,[OrgCode]
	  ,[YearCode]
	  ,[PublisherCode]
	  ,[TypeCode]
	  ,[WeightCode]
	  ,[CorpCode]
	  ,[IndustryCode]
	  ,[RegionCode]
	  ,[DeptCode]
	  ,[DetailCode]
	  ,[SubRegionCode]
	  ,[StateCode]
	  ,[CityCode]
	  ,[ScopeCode]
	  ,ROW_NUMBER() OVER (PARTITION BY [UID] ORDER BY [CreatedDate] DESC) AS RowOrder
	FROM V_Combined_Indexed
	where [Base 50th Percentile] is not null
	) A
WHERE RowOrder = 1

END