CREATE TABLE [RPT].[Dates] (
    [Calendar_Date]          DATE         NOT NULL,
    [Calendar_Date_String]   VARCHAR (10) NOT NULL,
    [Calendar_Month]         TINYINT      NOT NULL,
    [Calendar_Day]           TINYINT      NOT NULL,
    [Calendar_Year]          SMALLINT     NOT NULL,
    [Calendar_Quarter]       TINYINT      NOT NULL,
    [Day_Name]               VARCHAR (9)  NOT NULL,
    [Day_of_Week]            TINYINT      NOT NULL,
    [Day_of_Week_in_Month]   TINYINT      NOT NULL,
    [Day_of_Week_in_Year]    TINYINT      NOT NULL,
    [Day_of_Week_in_Quarter] TINYINT      NOT NULL,
    [Day_of_Quarter]         TINYINT      NOT NULL,
    [Day_of_Year]            SMALLINT     NOT NULL,
    [Week_of_Month]          TINYINT      NOT NULL,
    [Week_of_Quarter]        TINYINT      NOT NULL,
    [Week_of_Year]           TINYINT      NOT NULL,
    [Month_Name]             VARCHAR (9)  NOT NULL,
    [First_Date_of_Week]     DATE         NOT NULL,
    [Last_Date_of_Week]      DATE         NOT NULL,
    [First_Date_of_Month]    DATE         NOT NULL,
    [Last_Date_of_Month]     DATE         NOT NULL,
    [First_Date_of_Quarter]  DATE         NOT NULL,
    [Last_Date_of_Quarter]   DATE         NOT NULL,
    [First_Date_of_Year]     DATE         NOT NULL,
    [Last_Date_of_Year]      DATE         NOT NULL,
    [Is_Holiday]             BIT          NOT NULL,
    [Is_Holiday_Season]      BIT          NOT NULL,
    [Holiday_Name]           VARCHAR (50) NULL,
    [Holiday_Season_Name]    VARCHAR (50) NULL,
    [Is_Weekday]             BIT          NOT NULL,
    [Is_Business_Day]        BIT          NOT NULL,
    [Previous_Business_Day]  DATE         NULL,
    [Next_Business_Day]      DATE         NULL,
    [Is_Leap_Year]           BIT          NOT NULL,
    [Days_in_Month]          TINYINT      NOT NULL,
    CONSTRAINT [PK_Dates] PRIMARY KEY CLUSTERED ([Calendar_Date] ASC)
);

