CREATE TABLE [dbo].[AFEItems] (
    [afeitems_id]        INT             IDENTITY (1, 1) NOT NULL,
    [well_id]            BIGINT          NULL,
    [line_number]        BIGINT          NOT NULL,
    [job_number]         BIGINT          NOT NULL,
    [WorkoverCost]       DECIMAL (19, 9) NULL,
    [WorkoverCode]       NVARCHAR (MAX)  NULL,
    [ProductionCost]     DECIMAL (19, 9) NULL,
    [ProductionCode]     NVARCHAR (MAX)  NULL,
    [NonAFECost]         DECIMAL (19, 9) NULL,
    [NonAFECode]         NVARCHAR (MAX)  NULL,
    [LOECost]            DECIMAL (19, 9) NULL,
    [LOECode]            NVARCHAR (MAX)  NULL,
    [FacilitiesCost]     DECIMAL (19, 9) NULL,
    [FacilitiesCode]     NVARCHAR (MAX)  NULL,
    [ExpenseDescription] NVARCHAR (MAX)  NOT NULL,
    [DrillingCost]       DECIMAL (19, 9) NULL,
    [DrillingCode]       NVARCHAR (MAX)  NULL,
    [CustomCost5Code]    NVARCHAR (MAX)  NULL,
    [CustomCost5]        DECIMAL (19, 9) NULL,
    [CustomCost4Code]    NVARCHAR (MAX)  NULL,
    [CustomCost4]        DECIMAL (19, 9) NULL,
    [CustomCost3Code]    NVARCHAR (MAX)  NULL,
    [CustomCost3]        DECIMAL (19, 9) NULL,
    [CustomCost2Code]    NVARCHAR (MAX)  NULL,
    [CustomCost2]        DECIMAL (19, 9) NULL,
    [CustomCostCode]     NVARCHAR (MAX)  NULL,
    [CustomCost]         DECIMAL (19, 9) NULL,
    [CompletionCost]     DECIMAL (19, 9) NULL,
    [CompletionCode]     NVARCHAR (MAX)  NULL,
    [location_id]        INT             NULL,
    CONSTRAINT [PK_AFEItems] PRIMARY KEY CLUSTERED ([afeitems_id] ASC)
);

