CREATE TABLE [dbo].[BHAItem] (
    [bhaitem_id]          INT             IDENTITY (1, 1) NOT NULL,
    [well_id]             BIGINT          NULL,
    [report_Date]         DATETIME        NOT NULL,
    [line_number]         BIGINT          NOT NULL,
    [job_number]          BIGINT          NOT NULL,
    [UserDefined_9]       NVARCHAR (MAX)  NULL,
    [UserDefined_8]       NVARCHAR (MAX)  NULL,
    [UserDefined_7]       NVARCHAR (MAX)  NULL,
    [UserDefined_6]       NVARCHAR (MAX)  NULL,
    [UserDefined_5]       NVARCHAR (MAX)  NULL,
    [UserDefined_4]       NVARCHAR (MAX)  NULL,
    [UserDefined_3]       NVARCHAR (MAX)  NULL,
    [UserDefined_20]      NVARCHAR (MAX)  NULL,
    [UserDefined_2]       NVARCHAR (MAX)  NULL,
    [UserDefined_19]      NVARCHAR (MAX)  NULL,
    [UserDefined_18]      NVARCHAR (MAX)  NULL,
    [UserDefined_17]      NVARCHAR (MAX)  NULL,
    [UserDefined_16]      NVARCHAR (MAX)  NULL,
    [UserDefined_15]      NVARCHAR (MAX)  NULL,
    [UserDefined_14]      NVARCHAR (MAX)  NULL,
    [UserDefined_13]      NVARCHAR (MAX)  NULL,
    [UserDefined_12]      NVARCHAR (MAX)  NULL,
    [UserDefined_11]      NVARCHAR (MAX)  NULL,
    [UserDefined_10]      NVARCHAR (MAX)  NULL,
    [UserDefined_1]       NVARCHAR (MAX)  NULL,
    [reportTypeId]        BIGINT          NOT NULL,
    [ItemWeight]          DECIMAL (19, 9) NULL,
    [ItemTop]             DECIMAL (19, 9) NULL,
    [ItemSN]              NVARCHAR (MAX)  NULL,
    [ItemOD]              DECIMAL (19, 9) NULL,
    [ItemNoJoint]         BIGINT          NULL,
    [ItemNo]              BIGINT          NULL,
    [ItemModel]           NVARCHAR (MAX)  NULL,
    [ItemMaterial]        NVARCHAR (MAX)  NULL,
    [ItemMake]            NVARCHAR (MAX)  NULL,
    [ItemLength]          DECIMAL (19, 9) NULL,
    [ItemID]              DECIMAL (19, 9) NULL,
    [ItemHrs]             DECIMAL (19, 9) NULL,
    [ItemGrade]           NVARCHAR (MAX)  NULL,
    [ItemDescription]     NVARCHAR (MAX)  NULL,
    [ItemConnectionType]  NVARCHAR (MAX)  NULL,
    [ItemConnectionSize]  NVARCHAR (MAX)  NULL,
    [ItemComponentLookup] NVARCHAR (MAX)  NULL,
    [ItemBottom]          DECIMAL (19, 9) NULL,
    CONSTRAINT [PK_BHAItem] PRIMARY KEY CLUSTERED ([bhaitem_id] ASC)
);

