CREATE TABLE [dbo].[CasingItem] (
    [casingitem_id]      INT             IDENTITY (1, 1) NOT NULL,
    [well_id]            BIGINT          NULL,
    [report_Date]        DATETIME        NOT NULL,
    [line_number]        BIGINT          NOT NULL,
    [job_number]         BIGINT          NOT NULL,
    [Weight]             NVARCHAR (MAX)  NULL,
    [UserDefined_9]      NVARCHAR (MAX)  NULL,
    [UserDefined_8]      NVARCHAR (MAX)  NULL,
    [UserDefined_7]      NVARCHAR (MAX)  NULL,
    [UserDefined_6]      NVARCHAR (MAX)  NULL,
    [UserDefined_5]      NVARCHAR (MAX)  NULL,
    [UserDefined_4]      NVARCHAR (MAX)  NULL,
    [UserDefined_3]      NVARCHAR (MAX)  NULL,
    [UserDefined_20]     NVARCHAR (MAX)  NULL,
    [UserDefined_2]      NVARCHAR (MAX)  NULL,
    [UserDefined_19]     NVARCHAR (MAX)  NULL,
    [UserDefined_18]     NVARCHAR (MAX)  NULL,
    [UserDefined_17]     NVARCHAR (MAX)  NULL,
    [UserDefined_16]     NVARCHAR (MAX)  NULL,
    [UserDefined_15]     NVARCHAR (MAX)  NULL,
    [UserDefined_14]     NVARCHAR (MAX)  NULL,
    [UserDefined_13]     NVARCHAR (MAX)  NULL,
    [UserDefined_12]     NVARCHAR (MAX)  NULL,
    [UserDefined_11]     NVARCHAR (MAX)  NULL,
    [UserDefined_10]     NVARCHAR (MAX)  NULL,
    [UserDefined_1]      NVARCHAR (MAX)  NULL,
    [Torque_Min]         DECIMAL (19, 9) NULL,
    [Torque_Max]         DECIMAL (19, 9) NULL,
    [Top_TVD]            DECIMAL (19, 9) NULL,
    [Top_TMD]            DECIMAL (19, 9) NULL,
    [TOC]                DECIMAL (19, 9) NULL,
    [Shoe_Type]          NVARCHAR (MAX)  NULL,
    [Shoe_Mnf]           NVARCHAR (MAX)  NULL,
    [Shoe_Bottom]        DECIMAL (19, 9) NULL,
    [Run_Time]           NVARCHAR (MAX)  NULL,
    [reportTypeId]       BIGINT          NOT NULL,
    [Remark]             NVARCHAR (MAX)  NULL,
    [Pull_Time]          NVARCHAR (MAX)  NULL,
    [OD]                 NVARCHAR (MAX)  NULL,
    [NoJoints]           BIGINT          NULL,
    [Mud]                DECIMAL (19, 9) NULL,
    [Length]             DECIMAL (19, 9) NULL,
    [ID]                 DECIMAL (19, 9) NULL,
    [Hang]               DECIMAL (19, 9) NULL,
    [Grade]              NVARCHAR (MAX)  NULL,
    [Description]        NVARCHAR (MAX)  NULL,
    [Connection]         NVARCHAR (MAX)  NULL,
    [Collapse]           DECIMAL (19, 9) NULL,
    [Centralizers_Space] DECIMAL (19, 9) NULL,
    [Centralizers]       BIGINT          NULL,
    [Burst]              DECIMAL (19, 9) NULL,
    [Bottom_TVD]         DECIMAL (19, 9) NULL,
    [Bottom_TMD]         DECIMAL (19, 9) NULL,
    [Air]                DECIMAL (19, 9) NULL,
    CONSTRAINT [PK_CasingItem] PRIMARY KEY CLUSTERED ([casingitem_id] ASC)
);

