CREATE TABLE [dbo].[CementingItem] (
    [cementingitem_id] INT             IDENTITY (1, 1) NOT NULL,
    [well_id]          BIGINT          NOT NULL,
    [report_Date]      DATETIME        NOT NULL,
    [line_number]      BIGINT          NOT NULL,
    [job_number]       BIGINT          NOT NULL,
    [UserDefined_9]    NVARCHAR (MAX)  NULL,
    [UserDefined_8]    NVARCHAR (MAX)  NULL,
    [UserDefined_7]    NVARCHAR (MAX)  NULL,
    [UserDefined_6]    NVARCHAR (MAX)  NULL,
    [UserDefined_5]    NVARCHAR (MAX)  NULL,
    [UserDefined_4]    NVARCHAR (MAX)  NULL,
    [UserDefined_3]    NVARCHAR (MAX)  NULL,
    [UserDefined_20]   NVARCHAR (MAX)  NULL,
    [UserDefined_2]    NVARCHAR (MAX)  NULL,
    [UserDefined_19]   NVARCHAR (MAX)  NULL,
    [UserDefined_18]   NVARCHAR (MAX)  NULL,
    [UserDefined_17]   NVARCHAR (MAX)  NULL,
    [UserDefined_16]   NVARCHAR (MAX)  NULL,
    [UserDefined_15]   NVARCHAR (MAX)  NULL,
    [UserDefined_14]   NVARCHAR (MAX)  NULL,
    [UserDefined_13]   NVARCHAR (MAX)  NULL,
    [UserDefined_12]   NVARCHAR (MAX)  NULL,
    [UserDefined_11]   NVARCHAR (MAX)  NULL,
    [UserDefined_10]   NVARCHAR (MAX)  NULL,
    [UserDefined_1]    NVARCHAR (MAX)  NULL,
    [reportTypeId]     BIGINT          NOT NULL,
    [CYield]           DECIMAL (19, 9) NULL,
    [CWeight]          DECIMAL (19, 9) NULL,
    [CWater]           DECIMAL (19, 9) NULL,
    [CVolume]          DECIMAL (19, 9) NULL,
    [CType]            NVARCHAR (MAX)  NULL,
    [CSacks]           DECIMAL (19, 9) NULL,
    [AYield]           DECIMAL (19, 9) NULL,
    [AWeight]          DECIMAL (19, 9) NULL,
    [AWater]           DECIMAL (19, 9) NULL,
    [AVolume]          DECIMAL (19, 9) NULL,
    [AType]            NVARCHAR (MAX)  NULL,
    [ASacks]           DECIMAL (19, 9) NULL,
    [ADescription]     NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_CementingItem] PRIMARY KEY CLUSTERED ([cementingitem_id] ASC)
);

