CREATE TABLE [dbo].[DailyOps] (
    [dailyops_id]           INT             IDENTITY (1, 1) NOT NULL,
    [well_id]               BIGINT          NULL,
    [report_Date]           DATETIME        NOT NULL,
    [job_number]            BIGINT          NOT NULL,
    [WellStatus]            NVARCHAR (MAX)  NULL,
    [UserDefined_9]         NVARCHAR (MAX)  NULL,
    [UserDefined_8]         NVARCHAR (MAX)  NULL,
    [UserDefined_7]         NVARCHAR (MAX)  NULL,
    [UserDefined_6]         NVARCHAR (MAX)  NULL,
    [UserDefined_5]         NVARCHAR (MAX)  NULL,
    [UserDefined_40]        NVARCHAR (MAX)  NULL,
    [UserDefined_4]         NVARCHAR (MAX)  NULL,
    [UserDefined_39]        NVARCHAR (MAX)  NULL,
    [UserDefined_38]        NVARCHAR (MAX)  NULL,
    [UserDefined_37]        NVARCHAR (MAX)  NULL,
    [UserDefined_36]        NVARCHAR (MAX)  NULL,
    [UserDefined_35]        NVARCHAR (MAX)  NULL,
    [UserDefined_34]        NVARCHAR (MAX)  NULL,
    [UserDefined_33]        NVARCHAR (MAX)  NULL,
    [UserDefined_32]        NVARCHAR (MAX)  NULL,
    [UserDefined_31]        NVARCHAR (MAX)  NULL,
    [UserDefined_30]        NVARCHAR (MAX)  NULL,
    [UserDefined_3]         NVARCHAR (MAX)  NULL,
    [UserDefined_29]        NVARCHAR (MAX)  NULL,
    [UserDefined_28]        NVARCHAR (MAX)  NULL,
    [UserDefined_27]        NVARCHAR (MAX)  NULL,
    [UserDefined_26]        NVARCHAR (MAX)  NULL,
    [UserDefined_25]        NVARCHAR (MAX)  NULL,
    [UserDefined_24]        NVARCHAR (MAX)  NULL,
    [UserDefined_23]        NVARCHAR (MAX)  NULL,
    [UserDefined_22]        NVARCHAR (MAX)  NULL,
    [UserDefined_21]        NVARCHAR (MAX)  NULL,
    [UserDefined_20]        NVARCHAR (MAX)  NULL,
    [UserDefined_2]         NVARCHAR (MAX)  NULL,
    [UserDefined_19]        NVARCHAR (MAX)  NULL,
    [UserDefined_18]        NVARCHAR (MAX)  NULL,
    [UserDefined_17]        NVARCHAR (MAX)  NULL,
    [UserDefined_16]        NVARCHAR (MAX)  NULL,
    [UserDefined_15]        NVARCHAR (MAX)  NULL,
    [UserDefined_14]        NVARCHAR (MAX)  NULL,
    [UserDefined_13]        NVARCHAR (MAX)  NULL,
    [UserDefined_12]        NVARCHAR (MAX)  NULL,
    [UserDefined_11]        NVARCHAR (MAX)  NULL,
    [UserDefined_10]        NVARCHAR (MAX)  NULL,
    [UserDefined_1]         NVARCHAR (MAX)  NULL,
    [TripGas]               DECIMAL (19, 9) NULL,
    [TVD]                   DECIMAL (19, 9) NULL,
    [TMD]                   DECIMAL (19, 9) NULL,
    [Supervisor4]           NVARCHAR (MAX)  NULL,
    [Supervisor3]           NVARCHAR (MAX)  NULL,
    [Supervisor2]           NVARCHAR (MAX)  NULL,
    [Supervisor1]           NVARCHAR (MAX)  NULL,
    [Summary]               NVARCHAR (MAX)  NULL,
    [ShoeTest]              DECIMAL (19, 9) NULL,
    [SafetyTopic]           NVARCHAR (MAX)  NULL,
    [SafetyMeet_Date_Next]  DATETIME        NULL,
    [SafetyMeet_Date_Last]  DATETIME        NULL,
    [SafetyDrill]           DATETIME        NULL,
    [reportTypeId]          BIGINT          NOT NULL,
    [ReportNo]              BIGINT          NULL,
    [ReportNo_Prefix]       NVARCHAR (MAX)  NULL,
    [PorePress]             DECIMAL (19, 9) NULL,
    [Planned]               NVARCHAR (MAX)  NULL,
    [Phone3]                NVARCHAR (MAX)  NULL,
    [Phone2]                NVARCHAR (MAX)  NULL,
    [Phone1]                NVARCHAR (MAX)  NULL,
    [PBTVD]                 DECIMAL (19, 9) NULL,
    [PBTD]                  DECIMAL (19, 9) NULL,
    [MaxGas]                DECIMAL (19, 9) NULL,
    [Lithology]             NVARCHAR (MAX)  NULL,
    [LOT]                   DECIMAL (19, 9) NULL,
    [KOP]                   DECIMAL (19, 9) NULL,
    [Incident]              NVARCHAR (MAX)  NULL,
    [HoleSz]                DECIMAL (19, 9) NULL,
    [Forman4]               NVARCHAR (MAX)  NULL,
    [Forman3]               NVARCHAR (MAX)  NULL,
    [Forman2]               NVARCHAR (MAX)  NULL,
    [Forman1]               NVARCHAR (MAX)  NULL,
    [FluidLossDay]          DECIMAL (19, 9) NULL,
    [Fax]                   NVARCHAR (MAX)  NULL,
    [Email]                 NVARCHAR (MAX)  NULL,
    [EOC]                   DECIMAL (19, 9) NULL,
    [DockLoc]               NVARCHAR (MAX)  NULL,
    [Day_PorePress_Dpth]    DECIMAL (19, 9) NULL,
    [Day_FracGrad_Dpth]     DECIMAL (19, 9) NULL,
    [Day_FracGrad]          DECIMAL (19, 9) NULL,
    [DailySummary]          NVARCHAR (MAX)  NULL,
    [DP]                    BIGINT          NULL,
    [DOUserDefined_5]       NVARCHAR (MAX)  NULL,
    [DOUserDefined_4]       NVARCHAR (MAX)  NULL,
    [DOUserDefined_3]       NVARCHAR (MAX)  NULL,
    [DOUserDefined_2]       NVARCHAR (MAX)  NULL,
    [DOUserDefined_1]       NVARCHAR (MAX)  NULL,
    [CrewShort]             BIGINT          NULL,
    [ConGas]                DECIMAL (19, 9) NULL,
    [CompInt]               NVARCHAR (MAX)  NULL,
    [Comments]              NVARCHAR (MAX)  NULL,
    [Clerk2]                NVARCHAR (MAX)  NULL,
    [Clerk1]                NVARCHAR (MAX)  NULL,
    [Chlorides]             DECIMAL (19, 9) NULL,
    [BackGrndGas]           DECIMAL (19, 9) NULL,
    [BHA_MD]                DECIMAL (19, 9) NULL,
    [BOPType]               NVARCHAR (MAX)  NULL,
    [BOPRate]               DECIMAL (19, 9) NULL,
    [BOPDrill]              DATETIME        NULL,
    [BOPTest_Date_Last]     DATETIME        NULL,
    [BOPTest_Date_Next]     DATETIME        NULL,
    [UomPickList_1]         INT             NULL,
    [UomPickList_2]         INT             NULL,
    [UomPickList_3]         INT             NULL,
    [UomPickList_4]         INT             NULL,
    [UomPickList_5]         INT             NULL,
    [UomPickList_6]         INT             NULL,
    [UomPickList_7]         INT             NULL,
    [UomPickList_8]         INT             NULL,
    [UomPickList_9]         INT             NULL,
    [UomPickList_10]        INT             NULL,
    [CheckBox_1]            BIT             NULL,
    [CheckBox_2]            BIT             NULL,
    [CheckBox_3]            BIT             NULL,
    [CheckBox_4]            BIT             NULL,
    [CheckBox_5]            BIT             NULL,
    [CheckBox_6]            BIT             NULL,
    [CheckBox_7]            BIT             NULL,
    [CheckBox_8]            BIT             NULL,
    [CheckBox_9]            BIT             NULL,
    [CheckBox_10]           BIT             NULL,
    [location_id]           INT             NULL,
    [RowID]                 BIGINT          NOT NULL,
    [S1UserDefined_1]       NVARCHAR (MAX)  NULL,
    [S1UserDefined_2]       NVARCHAR (MAX)  NULL,
    [S1UserDefined_3]       NVARCHAR (MAX)  NULL,
    [S1UserDefined_4]       NVARCHAR (MAX)  NULL,
    [S1UserDefined_5]       NVARCHAR (MAX)  NULL,
    [S1UserDefined_6]       NVARCHAR (MAX)  NULL,
    [S1UserDefined_7]       NVARCHAR (MAX)  NULL,
    [S1UserDefined_8]       NVARCHAR (MAX)  NULL,
    [S1UserDefined_9]       NVARCHAR (MAX)  NULL,
    [S1UserDefined_10]      NVARCHAR (MAX)  NULL,
    [S1UomUserDefined_1]    INT             NULL,
    [S1UomUserDefined_2]    INT             NULL,
    [S1UomUserDefined_3]    INT             NULL,
    [S1UomUserDefined_4]    INT             NULL,
    [S1UomUserDefined_5]    INT             NULL,
    [S1UomUserDefined_6]    INT             NULL,
    [S1UomUserDefined_7]    INT             NULL,
    [S1UomUserDefined_8]    INT             NULL,
    [S1UomUserDefined_9]    INT             NULL,
    [S1UomUserDefined_10]   INT             NULL,
    [S1PickList_1]          NVARCHAR (MAX)  NULL,
    [S1PickList_2]          NVARCHAR (MAX)  NULL,
    [S1PickList_3]          NVARCHAR (MAX)  NULL,
    [S1PickList_4]          NVARCHAR (MAX)  NULL,
    [S1PickList_5]          NVARCHAR (MAX)  NULL,
    [S1UomPickList_1]       INT             NULL,
    [S1UomPickList_2]       INT             NULL,
    [S1UomPickList_3]       INT             NULL,
    [S1UomPickList_4]       INT             NULL,
    [S1UomPickList_5]       INT             NULL,
    [DSUserDefined_1]       NVARCHAR (MAX)  NULL,
    [DSUserDefined_2]       NVARCHAR (MAX)  NULL,
    [S3UserDefined_1]       NVARCHAR (MAX)  NULL,
    [S3UserDefined_2]       NVARCHAR (MAX)  NULL,
    [S3UserDefined_3]       NVARCHAR (MAX)  NULL,
    [S3UserDefined_4]       NVARCHAR (MAX)  NULL,
    [S3UserDefined_5]       NVARCHAR (MAX)  NULL,
    [S3UserDefined_6]       NVARCHAR (MAX)  NULL,
    [S3UserDefined_7]       NVARCHAR (MAX)  NULL,
    [S3UserDefined_8]       NVARCHAR (MAX)  NULL,
    [S3UserDefined_9]       NVARCHAR (MAX)  NULL,
    [S3UserDefined_10]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_11]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_12]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_13]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_14]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_15]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_16]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_17]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_18]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_19]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_20]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_21]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_22]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_23]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_24]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_25]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_26]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_27]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_28]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_29]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_30]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_31]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_32]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_33]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_34]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_35]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_36]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_37]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_38]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_39]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_40]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_41]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_42]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_43]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_44]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_45]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_46]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_47]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_48]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_49]      NVARCHAR (MAX)  NULL,
    [S3UserDefined_50]      NVARCHAR (MAX)  NULL,
    [S3UomUserDefined_1]    INT             NULL,
    [S3UomUserDefined_2]    INT             NULL,
    [S3UomUserDefined_3]    INT             NULL,
    [S3UomUserDefined_4]    INT             NULL,
    [S3UomUserDefined_5]    INT             NULL,
    [S3UomUserDefined_6]    INT             NULL,
    [S3UomUserDefined_7]    INT             NULL,
    [S3UomUserDefined_8]    INT             NULL,
    [S3UomUserDefined_9]    INT             NULL,
    [S3UomUserDefined_10]   INT             NULL,
    [S3UomUserDefined_11]   INT             NULL,
    [S3UomUserDefined_12]   INT             NULL,
    [S3UomUserDefined_13]   INT             NULL,
    [S3UomUserDefined_14]   INT             NULL,
    [S3UomUserDefined_15]   INT             NULL,
    [S3UomUserDefined_16]   INT             NULL,
    [S3UomUserDefined_17]   INT             NULL,
    [S3UomUserDefined_18]   INT             NULL,
    [S3UomUserDefined_19]   INT             NULL,
    [S3UomUserDefined_20]   INT             NULL,
    [S3UomUserDefined_21]   INT             NULL,
    [S3UomUserDefined_22]   INT             NULL,
    [S3UomUserDefined_23]   INT             NULL,
    [S3UomUserDefined_24]   INT             NULL,
    [S3UomUserDefined_25]   INT             NULL,
    [S3UomUserDefined_26]   INT             NULL,
    [S3UomUserDefined_27]   INT             NULL,
    [S3UomUserDefined_28]   INT             NULL,
    [S3UomUserDefined_29]   INT             NULL,
    [S3UomUserDefined_30]   INT             NULL,
    [S3UomUserDefined_31]   INT             NULL,
    [S3UomUserDefined_32]   INT             NULL,
    [S3UomUserDefined_33]   INT             NULL,
    [S3UomUserDefined_34]   INT             NULL,
    [S3UomUserDefined_35]   INT             NULL,
    [S3UomUserDefined_36]   INT             NULL,
    [S3UomUserDefined_37]   INT             NULL,
    [S3UomUserDefined_38]   INT             NULL,
    [S3UomUserDefined_39]   INT             NULL,
    [S3UomUserDefined_40]   INT             NULL,
    [S3UomUserDefined_41]   INT             NULL,
    [S3UomUserDefined_42]   INT             NULL,
    [S3UomUserDefined_43]   INT             NULL,
    [S3UomUserDefined_44]   INT             NULL,
    [S3UomUserDefined_45]   INT             NULL,
    [S3UomUserDefined_46]   INT             NULL,
    [S3UomUserDefined_47]   INT             NULL,
    [S3UomUserDefined_48]   INT             NULL,
    [S3UomUserDefined_49]   INT             NULL,
    [S3UomUserDefined_50]   INT             NULL,
    [S3PickList_1]          NVARCHAR (MAX)  NULL,
    [S3PickList_2]          NVARCHAR (MAX)  NULL,
    [S3PickList_3]          NVARCHAR (MAX)  NULL,
    [S3PickList_4]          NVARCHAR (MAX)  NULL,
    [S3PickList_5]          NVARCHAR (MAX)  NULL,
    [S3PickList_6]          NVARCHAR (MAX)  NULL,
    [S3PickList_7]          NVARCHAR (MAX)  NULL,
    [S3PickList_8]          NVARCHAR (MAX)  NULL,
    [S3PickList_9]          NVARCHAR (MAX)  NULL,
    [S3PickList_10]         NVARCHAR (MAX)  NULL,
    [S3PickList_11]         NVARCHAR (MAX)  NULL,
    [S3PickList_12]         NVARCHAR (MAX)  NULL,
    [S3PickList_13]         NVARCHAR (MAX)  NULL,
    [S3PickList_14]         NVARCHAR (MAX)  NULL,
    [S3PickList_15]         NVARCHAR (MAX)  NULL,
    [S3PickList_16]         NVARCHAR (MAX)  NULL,
    [S3PickList_17]         NVARCHAR (MAX)  NULL,
    [S3PickList_18]         NVARCHAR (MAX)  NULL,
    [S3PickList_19]         NVARCHAR (MAX)  NULL,
    [S3PickList_20]         NVARCHAR (MAX)  NULL,
    [S3UomPickList_1]       INT             NULL,
    [S3UomPickList_2]       INT             NULL,
    [S3UomPickList_3]       INT             NULL,
    [S3UomPickList_4]       INT             NULL,
    [S3UomPickList_5]       INT             NULL,
    [S3UomPickList_6]       INT             NULL,
    [S3UomPickList_7]       INT             NULL,
    [S3UomPickList_8]       INT             NULL,
    [S3UomPickList_9]       INT             NULL,
    [S3UomPickList_10]      INT             NULL,
    [S3UomPickList_11]      INT             NULL,
    [S3UomPickList_12]      INT             NULL,
    [S3UomPickList_13]      INT             NULL,
    [S3UomPickList_14]      INT             NULL,
    [S3UomPickList_15]      INT             NULL,
    [S3UomPickList_16]      INT             NULL,
    [S3UomPickList_17]      INT             NULL,
    [S3UomPickList_18]      INT             NULL,
    [S3UomPickList_19]      INT             NULL,
    [S3UomPickList_20]      INT             NULL,
    [UomTMD]                INT             NULL,
    [UomTVD]                INT             NULL,
    [UomPBTD]               INT             NULL,
    [UomPBTVD]              INT             NULL,
    [UomDay_PorePress_Dpth] INT             NULL,
    [UomDay_FracGrad_Dpth]  INT             NULL,
    [UomBHA_MD]             INT             NULL,
    [UomKOP]                INT             NULL,
    [UomEOC]                INT             NULL,
    [UomBOPRate]            INT             NULL,
    [UomLOT]                INT             NULL,
    [UomShoeTest]           INT             NULL,
    [UomFluidLoss]          INT             NULL,
    [UomHoleSz]             INT             NULL,
    [UomDOUserDefined_1]    INT             NULL,
    [UomDOUserDefined_2]    INT             NULL,
    [UomDOUserDefined_3]    INT             NULL,
    [UomDOUserDefined_4]    INT             NULL,
    [UomDOUserDefined_5]    INT             NULL,
    CONSTRAINT [PK_DailyOps] PRIMARY KEY CLUSTERED ([dailyops_id] ASC)
);

