CREATE TABLE [dbo].[JobCustomItem_3] (
    [jobcustomitem_3_id] INT            IDENTITY (1, 1) NOT NULL,
    [well_id]            BIGINT         NULL,
    [line_number]        BIGINT         NOT NULL,
    [job_number]         BIGINT         NOT NULL,
    [UserDefined_9]      NVARCHAR (MAX) NULL,
    [UserDefined_8]      NVARCHAR (MAX) NULL,
    [UserDefined_7]      NVARCHAR (MAX) NULL,
    [UserDefined_6]      NVARCHAR (MAX) NULL,
    [UserDefined_5]      NVARCHAR (MAX) NULL,
    [UserDefined_4]      NVARCHAR (MAX) NULL,
    [UserDefined_3]      NVARCHAR (MAX) NULL,
    [UserDefined_25]     NVARCHAR (MAX) NULL,
    [UserDefined_24]     NVARCHAR (MAX) NULL,
    [UserDefined_23]     NVARCHAR (MAX) NULL,
    [UserDefined_22]     NVARCHAR (MAX) NULL,
    [UserDefined_21]     NVARCHAR (MAX) NULL,
    [UserDefined_20]     NVARCHAR (MAX) NULL,
    [UserDefined_2]      NVARCHAR (MAX) NULL,
    [UserDefined_19]     NVARCHAR (MAX) NULL,
    [UserDefined_18]     NVARCHAR (MAX) NULL,
    [UserDefined_17]     NVARCHAR (MAX) NULL,
    [UserDefined_16]     NVARCHAR (MAX) NULL,
    [UserDefined_15]     NVARCHAR (MAX) NULL,
    [UserDefined_14]     NVARCHAR (MAX) NULL,
    [UserDefined_13]     NVARCHAR (MAX) NULL,
    [UserDefined_12]     NVARCHAR (MAX) NULL,
    [UserDefined_11]     NVARCHAR (MAX) NULL,
    [UserDefined_10]     NVARCHAR (MAX) NULL,
    [UserDefined_1]      NVARCHAR (MAX) NULL,
    [reportTypeId]       BIGINT         NOT NULL,
    [PickList_5]         NVARCHAR (MAX) NULL,
    [PickList_4]         NVARCHAR (MAX) NULL,
    [PickList_3]         NVARCHAR (MAX) NULL,
    [PickList_2]         NVARCHAR (MAX) NULL,
    [PickList_1]         NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_JobCustomItem_3] PRIMARY KEY CLUSTERED ([jobcustomitem_3_id] ASC)
);

