CREATE TABLE [dbo].[JobDetails] (
    [jobdetails_id]               INT             IDENTITY (1, 1) NOT NULL,
    [well_id]                     BIGINT          NULL,
    [job_status]                  BIGINT          NOT NULL,
    [job_number]                  BIGINT          NOT NULL,
    [jobDescription]              NVARCHAR (MAX)  NULL,
    [WorkingInterest]             REAL            NULL,
    [WellType]                    NVARCHAR (MAX)  NULL,
    [WellEngineer]                NVARCHAR (MAX)  NULL,
    [WellBore]                    NVARCHAR (MAX)  NULL,
    [UserDefined_9]               NVARCHAR (MAX)  NULL,
    [UserDefined_8]               NVARCHAR (MAX)  NULL,
    [UserDefined_7]               NVARCHAR (MAX)  NULL,
    [UserDefined_6]               NVARCHAR (MAX)  NULL,
    [UserDefined_5]               NVARCHAR (MAX)  NULL,
    [UserDefined_40]              NVARCHAR (MAX)  NULL,
    [UserDefined_4]               NVARCHAR (MAX)  NULL,
    [UserDefined_39]              NVARCHAR (MAX)  NULL,
    [UserDefined_38]              NVARCHAR (MAX)  NULL,
    [UserDefined_37]              NVARCHAR (MAX)  NULL,
    [UserDefined_36]              NVARCHAR (MAX)  NULL,
    [UserDefined_35]              NVARCHAR (MAX)  NULL,
    [UserDefined_34]              NVARCHAR (MAX)  NULL,
    [UserDefined_33]              NVARCHAR (MAX)  NULL,
    [UserDefined_32]              NVARCHAR (MAX)  NULL,
    [UserDefined_31]              NVARCHAR (MAX)  NULL,
    [UserDefined_30]              NVARCHAR (MAX)  NULL,
    [UserDefined_3]               NVARCHAR (MAX)  NULL,
    [UserDefined_29]              NVARCHAR (MAX)  NULL,
    [UserDefined_28]              NVARCHAR (MAX)  NULL,
    [UserDefined_27]              NVARCHAR (MAX)  NULL,
    [UserDefined_26]              NVARCHAR (MAX)  NULL,
    [UserDefined_25]              NVARCHAR (MAX)  NULL,
    [UserDefined_24]              NVARCHAR (MAX)  NULL,
    [UserDefined_23]              NVARCHAR (MAX)  NULL,
    [UserDefined_22]              NVARCHAR (MAX)  NULL,
    [UserDefined_21]              NVARCHAR (MAX)  NULL,
    [UserDefined_20]              NVARCHAR (MAX)  NULL,
    [UserDefined_2]               NVARCHAR (MAX)  NULL,
    [UserDefined_19]              NVARCHAR (MAX)  NULL,
    [UserDefined_18]              NVARCHAR (MAX)  NULL,
    [UserDefined_17]              NVARCHAR (MAX)  NULL,
    [UserDefined_16]              NVARCHAR (MAX)  NULL,
    [UserDefined_15]              NVARCHAR (MAX)  NULL,
    [UserDefined_14]              NVARCHAR (MAX)  NULL,
    [UserDefined_13]              NVARCHAR (MAX)  NULL,
    [UserDefined_12]              NVARCHAR (MAX)  NULL,
    [UserDefined_11]              NVARCHAR (MAX)  NULL,
    [UserDefined_10]              NVARCHAR (MAX)  NULL,
    [UserDefined_1]               NVARCHAR (MAX)  NULL,
    [UomUserDefined_9]            INT             NULL,
    [UomUserDefined_8]            INT             NULL,
    [UomUserDefined_7]            INT             NULL,
    [UomUserDefined_6]            INT             NULL,
    [UomUserDefined_5]            INT             NULL,
    [UomUserDefined_4]            INT             NULL,
    [UomUserDefined_39]           INT             NULL,
    [UomUserDefined_38]           INT             NULL,
    [UomUserDefined_37]           INT             NULL,
    [UomUserDefined_36]           INT             NULL,
    [UomUserDefined_35]           INT             NULL,
    [UomUserDefined_34]           INT             NULL,
    [UomUserDefined_33]           INT             NULL,
    [UomUserDefined_32]           INT             NULL,
    [UomUserDefined_31]           INT             NULL,
    [UomUserDefined_30]           INT             NULL,
    [UomUserDefined_3]            INT             NULL,
    [UomUserDefined_29]           INT             NULL,
    [UomUserDefined_28]           INT             NULL,
    [UomUserDefined_27]           INT             NULL,
    [UomUserDefined_26]           INT             NULL,
    [UomUserDefined_25]           INT             NULL,
    [UomUserDefined_24]           INT             NULL,
    [UomUserDefined_23]           INT             NULL,
    [UomUserDefined_22]           INT             NULL,
    [UomUserDefined_21]           INT             NULL,
    [UomUserDefined_20]           INT             NULL,
    [UomUserDefined_2]            INT             NULL,
    [UomUserDefined_19]           INT             NULL,
    [UomUserDefined_18]           INT             NULL,
    [UomUserDefined_17]           INT             NULL,
    [UomUserDefined_16]           INT             NULL,
    [UomUserDefined_15]           INT             NULL,
    [UomUserDefined_14]           INT             NULL,
    [UomUserDefined_13]           INT             NULL,
    [UomUserDefined_12]           INT             NULL,
    [UomUserDefined_11]           INT             NULL,
    [UomUserDefined_10]           INT             NULL,
    [UomUserDefined_1]            INT             NULL,
    [TightGroupCode]              NVARCHAR (MAX)  NOT NULL,
    [TightGroup]                  NVARCHAR (MAX)  NOT NULL,
    [ReportNo_Trigger]            INT             NOT NULL,
    [modified_by]                 BIGINT          NULL,
    [modified_on]                 DATETIME        NULL,
    [SurfLocation]                NVARCHAR (MAX)  NULL,
    [SubCode]                     NVARCHAR (MAX)  NOT NULL,
    [StartingDepth]               DECIMAL (19, 9) NULL,
    [StartDate]                   DATETIME        NOT NULL,
    [SpudDate]                    DATETIME        NULL,
    [SortOrder]                   BIGINT          NULL,
    [RigNumber]                   NVARCHAR (MAX)  NULL,
    [RigContractor]               NVARCHAR (MAX)  NULL,
    [PropTVD]                     DECIMAL (19, 9) NULL,
    [PropTMD]                     DECIMAL (19, 9) NULL,
    [PlatformName]                NVARCHAR (MAX)  NULL,
    [PickList_9]                  NVARCHAR (MAX)  NULL,
    [PickList_8]                  NVARCHAR (MAX)  NULL,
    [PickList_7]                  NVARCHAR (MAX)  NULL,
    [PickList_6]                  NVARCHAR (MAX)  NULL,
    [PickList_5]                  NVARCHAR (MAX)  NULL,
    [PickList_4]                  NVARCHAR (MAX)  NULL,
    [PickList_3]                  NVARCHAR (MAX)  NULL,
    [PickList_2]                  NVARCHAR (MAX)  NULL,
    [PickList_10]                 NVARCHAR (MAX)  NULL,
    [PickList_1]                  NVARCHAR (MAX)  NULL,
    [PermitNo]                    NVARCHAR (MAX)  NULL,
    [Operator]                    NVARCHAR (MAX)  NULL,
    [Objective]                   NVARCHAR (MAX)  NULL,
    [NetRevenueInterest]          REAL            NULL,
    [MRI]                         BIGINT          NULL,
    [KOP]                         DECIMAL (19, 9) NULL,
    [Category]                    NVARCHAR (MAX)  NOT NULL,
    [GUID]                        NVARCHAR (MAX)  NOT NULL,
    [Contract]                    NVARCHAR (MAX)  NULL,
    [Comment]                     NVARCHAR (MAX)  NULL,
    [CategoryCode]                NVARCHAR (MAX)  NOT NULL,
    [BHLocation]                  NVARCHAR (MAX)  NULL,
    [AFENumberW]                  NVARCHAR (MAX)  NULL,
    [AFENumberP]                  NVARCHAR (MAX)  NULL,
    [AFENumberNA]                 NVARCHAR (MAX)  NULL,
    [AFENumberL]                  NVARCHAR (MAX)  NULL,
    [AFENumberF]                  NVARCHAR (MAX)  NULL,
    [AFENumberD]                  NVARCHAR (MAX)  NULL,
    [AFENumberCC5]                NVARCHAR (MAX)  NULL,
    [AFENumberCC4]                NVARCHAR (MAX)  NULL,
    [AFENumberCC3]                NVARCHAR (MAX)  NULL,
    [AFENumberCC2]                NVARCHAR (MAX)  NULL,
    [AFENumberCC]                 NVARCHAR (MAX)  NULL,
    [AFENumberC]                  NVARCHAR (MAX)  NULL,
    [AFENumber]                   NVARCHAR (MAX)  NULL,
    [AFEAmountW]                  DECIMAL (19, 9) NULL,
    [AFEAmountP]                  DECIMAL (19, 9) NULL,
    [AFEAmountNA]                 DECIMAL (19, 9) NULL,
    [AFEAmountL]                  DECIMAL (19, 9) NULL,
    [AFEAmountF]                  DECIMAL (19, 9) NULL,
    [AFEAmountD]                  DECIMAL (19, 9) NULL,
    [AFEAmountCC5]                DECIMAL (19, 9) NULL,
    [AFEAmountCC4]                DECIMAL (19, 9) NULL,
    [AFEAmountCC3]                DECIMAL (19, 9) NULL,
    [AFEAmountCC2]                DECIMAL (19, 9) NULL,
    [AFEAmountCC]                 DECIMAL (19, 9) NULL,
    [AFEAmountC]                  DECIMAL (19, 9) NULL,
    [AFEAmount]                   DECIMAL (19, 9) NULL,
    [GL]                          DECIMAL (19, 9) NULL,
    [WD]                          DECIMAL (19, 9) NULL,
    [RKBGL]                       DECIMAL (19, 9) NULL,
    [RKBSL]                       DECIMAL (19, 9) NULL,
    [deleted]                     BIT             NULL,
    [location_id]                 INT             NULL,
    [DrillContgPercentInt]        DECIMAL (19, 9) NULL,
    [DrillContgIsCalculatedInt]   BIT             NULL,
    [DrillContgPercentTan]        DECIMAL (19, 9) NULL,
    [DrillContgIsCalculatedTan]   BIT             NULL,
    [ComplContgPercentInt]        DECIMAL (19, 9) NULL,
    [ComplContgIsCalculatedInt]   BIT             NULL,
    [ComplContgPercentTan]        DECIMAL (19, 9) NULL,
    [ComplContgIsCalculatedTan]   BIT             NULL,
    [WkOvrContgPercentInt]        DECIMAL (19, 9) NULL,
    [WkOvrContgIsCalculatedInt]   BIT             NULL,
    [WkOvrContgPercentTan]        DECIMAL (19, 9) NULL,
    [WkOvrContgIsCalculatedTan]   BIT             NULL,
    [FacilContgPercentInt]        DECIMAL (19, 9) NULL,
    [FacilContgIsCalculatedInt]   BIT             NULL,
    [FacilContgPercentTan]        DECIMAL (19, 9) NULL,
    [FacilContgIsCalculatedTan]   BIT             NULL,
    [ProdContgPercentInt]         DECIMAL (19, 9) NULL,
    [ProdContgIsCalculatedInt]    BIT             NULL,
    [ProdContgPercentTan]         DECIMAL (19, 9) NULL,
    [ProdContgIsCalculatedTan]    BIT             NULL,
    [LOEContgPercentInt]          DECIMAL (19, 9) NULL,
    [LOEContgIsCalculatedInt]     BIT             NULL,
    [LOEContgPercentTan]          DECIMAL (19, 9) NULL,
    [LOEContgIsCalculatedTan]     BIT             NULL,
    [NonAFEContgPercentInt]       DECIMAL (19, 9) NULL,
    [NonAFEContgIsCalculatedInt]  BIT             NULL,
    [NonAFEContgPercentTan]       DECIMAL (19, 9) NULL,
    [NonAFEContgIsCalculatedTan]  BIT             NULL,
    [Custom1ContgPercentInt]      DECIMAL (19, 9) NULL,
    [Custom1ContgIsCalculatedInt] BIT             NULL,
    [Custom1ContgPercentTan]      DECIMAL (19, 9) NULL,
    [Custom1ContgIsCalculatedTan] BIT             NULL,
    [Custom2ContgPercentInt]      DECIMAL (19, 9) NULL,
    [Custom2ContgIsCalculatedInt] BIT             NULL,
    [Custom2ContgPercentTan]      DECIMAL (19, 9) NULL,
    [Custom2ContgIsCalculatedTan] BIT             NULL,
    [Custom3ContgPercentInt]      DECIMAL (19, 9) NULL,
    [Custom3ContgIsCalculatedInt] BIT             NULL,
    [Custom3ContgPercentTan]      DECIMAL (19, 9) NULL,
    [Custom3ContgIsCalculatedTan] BIT             NULL,
    [Custom4ContgPercentInt]      DECIMAL (19, 9) NULL,
    [Custom4ContgIsCalculatedInt] BIT             NULL,
    [Custom4ContgPercentTan]      DECIMAL (19, 9) NULL,
    [Custom4ContgIsCalculatedTan] BIT             NULL,
    [Custom5ContgPercentInt]      DECIMAL (19, 9) NULL,
    [Custom5ContgIsCalculatedInt] BIT             NULL,
    [Custom5ContgPercentTan]      DECIMAL (19, 9) NULL,
    [Custom5ContgIsCalculatedTan] BIT             NULL,
    [job_number_co_source]        BIGINT          NULL,
    [UomPropTVD]                  INT             NULL,
    [UomPropTMD]                  INT             NULL,
    [UomKOP]                      INT             NULL,
    [UomStartingDepth]            INT             NULL,
    CONSTRAINT [PK_JobDetails] PRIMARY KEY CLUSTERED ([jobdetails_id] ASC)
);

