CREATE TABLE [dbo].[MudCheck_4] (
    [mudcheck_4_id]                    INT             IDENTITY (1, 1) NOT NULL,
    [well_id]                          BIGINT          NULL,
    [reportTypeId]                     BIGINT          NOT NULL,
    [section4_YP_Temp]                 DECIMAL (19, 9) NULL,
    [section4_YP]                      DECIMAL (19, 9) NULL,
    [section4_Weight_Out]              DECIMAL (19, 9) NULL,
    [section4_Weight_In_ppg]           DECIMAL (19, 9) NULL,
    [section4_Weight_In]               DECIMAL (19, 9) NULL,
    [section4_Water]                   DECIMAL (19, 9) NULL,
    [section4_WL]                      DECIMAL (19, 9) NULL,
    [section4_Volume_Reverse]          DECIMAL (19, 9) NULL,
    [section4_Volume]                  DECIMAL (19, 9) NULL,
    [section4_Viscosity]               DECIMAL (19, 9) NULL,
    [section4_UomWeight_Out]           INT             NULL,
    [section4_UomWeight_In]            INT             NULL,
    [section4_UomVolume]               INT             NULL,
    [section4_UomStaticUserDefined_9]  INT             NULL,
    [section4_UomStaticUserDefined_8]  INT             NULL,
    [section4_UomStaticUserDefined_7]  INT             NULL,
    [section4_UomStaticUserDefined_6]  INT             NULL,
    [section4_UomStaticUserDefined_5]  INT             NULL,
    [section4_UomStaticUserDefined_4]  INT             NULL,
    [section4_UomStaticUserDefined_3]  INT             NULL,
    [section4_UomStaticUserDefined_2]  INT             NULL,
    [section4_UomStaticUserDefined_10] INT             NULL,
    [section4_UomStaticUserDefined_1]  INT             NULL,
    [section4_UomTrip_Tank]            INT             NULL,
    [section4_UomTemp_FL]              INT             NULL,
    [section4_UomTemp]                 INT             NULL,
    [section4_UomStaticPickList_9]     INT             NULL,
    [section4_UomStaticPickList_8]     INT             NULL,
    [section4_UomStaticPickList_7]     INT             NULL,
    [section4_UomStaticPickList_6]     INT             NULL,
    [section4_UomStaticPickList_5]     INT             NULL,
    [section4_UomStaticPickList_4]     INT             NULL,
    [section4_UomStaticPickList_3]     INT             NULL,
    [section4_UomStaticPickList_2]     INT             NULL,
    [section4_UomStaticPickList_10]    INT             NULL,
    [section4_UomStaticPickList_1]     INT             NULL,
    [section4_UomRes_Pit2]             INT             NULL,
    [section4_UomRes_Pit1]             INT             NULL,
    [section4_UomPV]                   INT             NULL,
    [section4_UomPSI]                  INT             NULL,
    [section4_UomLoss_Surface]         INT             NULL,
    [section4_UomLoss_Hole]            INT             NULL,
    [section4_UomLCM_lb_bbl]           INT             NULL,
    [section4_UomHTHPTemp]             INT             NULL,
    [section4_UomDepth_TVD]            INT             NULL,
    [section4_UomDepth]                INT             NULL,
    [section4_UomBrine]                INT             NULL,
    [section4_UomAct_Pit2]             INT             NULL,
    [section4_UomAct_Pit1]             INT             NULL,
    [section4_Type]                    NVARCHAR (MAX)  NULL,
    [section4_Trip_Tank]               DECIMAL (19, 9) NULL,
    [section4_Time]                    DATETIME        NULL,
    [section4_Temp_FL]                 DECIMAL (19, 9) NULL,
    [section4_Temp]                    DECIMAL (19, 9) NULL,
    [section4_TS]                      DECIMAL (19, 9) NULL,
    [section4_StaticPickList_9]        NVARCHAR (MAX)  NULL,
    [section4_StaticPickList_8]        NVARCHAR (MAX)  NULL,
    [section4_StaticPickList_7]        NVARCHAR (MAX)  NULL,
    [section4_StaticPickList_6]        NVARCHAR (MAX)  NULL,
    [section4_StaticPickList_5]        NVARCHAR (MAX)  NULL,
    [section4_StaticPickList_4]        NVARCHAR (MAX)  NULL,
    [section4_StaticPickList_3]        NVARCHAR (MAX)  NULL,
    [section4_StaticPickList_2]        NVARCHAR (MAX)  NULL,
    [section4_StaticPickList_10]       NVARCHAR (MAX)  NULL,
    [section4_StaticPickList_1]        NVARCHAR (MAX)  NULL,
    [section4_Sand]                    DECIMAL (19, 9) NULL,
    [section4_Retort_Density]          DECIMAL (19, 9) NULL,
    [section4_Res_Pit2]                DECIMAL (19, 9) NULL,
    [section4_Res_Pit1]                DECIMAL (19, 9) NULL,
    [section4_Potassium]               DECIMAL (19, 9) NULL,
    [section4_Pot_Ash]                 DECIMAL (19, 9) NULL,
    [section4_Pm]                      DECIMAL (19, 9) NULL,
    [section4_PV_Temp]                 DECIMAL (19, 9) NULL,
    [section4_PV]                      DECIMAL (19, 9) NULL,
    [section4_PSI]                     DECIMAL (19, 9) NULL,
    [section4_PH]                      DECIMAL (19, 9) NULL,
    [section4_PF]                      DECIMAL (19, 9) NULL,
    [section4_Oil_Brine_Ratio]         DECIMAL (19, 9) NULL,
    [section4_Oil]                     DECIMAL (19, 9) NULL,
    [section4_OW]                      NVARCHAR (MAX)  NULL,
    [section4_StaticUserDefined_9]     NVARCHAR (MAX)  NULL,
    [section4_StaticUserDefined_8]     NVARCHAR (MAX)  NULL,
    [section4_StaticUserDefined_7]     NVARCHAR (MAX)  NULL,
    [section4_StaticUserDefined_6]     NVARCHAR (MAX)  NULL,
    [section4_StaticUserDefined_5]     NVARCHAR (MAX)  NULL,
    [section4_StaticUserDefined_4]     NVARCHAR (MAX)  NULL,
    [section4_StaticUserDefined_3]     NVARCHAR (MAX)  NULL,
    [section4_StaticUserDefined_2]     NVARCHAR (MAX)  NULL,
    [section4_StaticUserDefined_10]    NVARCHAR (MAX)  NULL,
    [section4_StaticUserDefined_1]     NVARCHAR (MAX)  NULL,
    [section4_Mg]                      DECIMAL (19, 9) NULL,
    [section4_MF]                      DECIMAL (19, 9) NULL,
    [section4_MBT]                     DECIMAL (19, 9) NULL,
    [section4_Loss_Surface]            DECIMAL (19, 9) NULL,
    [section4_Loss_Hole]               DECIMAL (19, 9) NULL,
    [section4_Lime]                    DECIMAL (19, 9) NULL,
    [section4_LGS]                     DECIMAL (19, 9) NULL,
    [section4_LCM_lb_bbl]              DECIMAL (19, 9) NULL,
    [section4_LCM]                     DECIMAL (19, 9) NULL,
    [section4_HTHP_Temp]               DECIMAL (19, 9) NULL,
    [section4_HTHP]                    DECIMAL (19, 9) NULL,
    [section4_HGS]                     DECIMAL (19, 9) NULL,
    [section4_H2S]                     DECIMAL (19, 9) NULL,
    [section4_Gel30m]                  DECIMAL (19, 9) NULL,
    [section4_Gel10s]                  DECIMAL (19, 9) NULL,
    [section4_Gel10m]                  DECIMAL (19, 9) NULL,
    [section4_Filtrate]                DECIMAL (19, 9) NULL,
    [section4_FV]                      DECIMAL (19, 9) NULL,
    [section4_Engineer]                NVARCHAR (MAX)  NULL,
    [section4_ES]                      DECIMAL (19, 9) NULL,
    [section4_ECD]                     DECIMAL (19, 9) NULL,
    [section4_Depth_TVD]               DECIMAL (19, 9) NULL,
    [section4_Depth]                   DECIMAL (19, 9) NULL,
    [section4_Density]                 DECIMAL (19, 9) NULL,
    [section4_Critical_Velocity]       DECIMAL (19, 9) NULL,
    [section4_Critical_Flow_Rate]      DECIMAL (19, 9) NULL,
    [section4_Company]                 NVARCHAR (MAX)  NULL,
    [section4_Chloride]                DECIMAL (19, 9) NULL,
    [section4_Carbonate]               DECIMAL (19, 9) NULL,
    [section4_Calcium]                 DECIMAL (19, 9) NULL,
    [section4_Cake]                    NVARCHAR (MAX)  NULL,
    [section4_CaCl]                    DECIMAL (19, 9) NULL,
    [section4_CCI]                     DECIMAL (19, 9) NULL,
    [section4_Brine]                   DECIMAL (19, 9) NULL,
    [section4_BottomsUpTime]           DATETIME        NULL,
    [section4_Barite]                  DECIMAL (19, 9) NULL,
    [section4_Annular_Viscosity]       DECIMAL (19, 9) NULL,
    [section4_Alkalinity]              DECIMAL (19, 9) NULL,
    [section4_Act_Pit2]                DECIMAL (19, 9) NULL,
    [section4_Act_Pit1]                DECIMAL (19, 9) NULL,
    [section3_YP_Temp]                 DECIMAL (19, 9) NULL,
    [section3_YP]                      DECIMAL (19, 9) NULL,
    [section3_Weight_Out]              DECIMAL (19, 9) NULL,
    [section3_Weight_In_ppg]           DECIMAL (19, 9) NULL,
    [section3_Weight_In]               DECIMAL (19, 9) NULL,
    [section3_Water]                   DECIMAL (19, 9) NULL,
    [section3_WL]                      DECIMAL (19, 9) NULL,
    [section3_Volume_Reverse]          DECIMAL (19, 9) NULL,
    [section3_Volume]                  DECIMAL (19, 9) NULL,
    [section3_Viscosity]               DECIMAL (19, 9) NULL,
    [section3_UomWeight_Out]           INT             NULL,
    [section3_UomWeight_In]            INT             NULL,
    [section3_UomVolume]               INT             NULL,
    [section3_UomStaticUserDefined_9]  INT             NULL,
    [section3_UomStaticUserDefined_8]  INT             NULL,
    [section3_UomStaticUserDefined_7]  INT             NULL,
    [section3_UomStaticUserDefined_6]  INT             NULL,
    [section3_UomStaticUserDefined_5]  INT             NULL,
    [section3_UomStaticUserDefined_4]  INT             NULL,
    [section3_UomStaticUserDefined_3]  INT             NULL,
    [section3_UomStaticUserDefined_2]  INT             NULL,
    [section3_UomStaticUserDefined_10] INT             NULL,
    [section3_UomStaticUserDefined_1]  INT             NULL,
    [section3_UomTrip_Tank]            INT             NULL,
    [section3_UomTemp_FL]              INT             NULL,
    [section3_UomTemp]                 INT             NULL,
    [section3_UomStaticPickList_9]     INT             NULL,
    [section3_UomStaticPickList_8]     INT             NULL,
    [section3_UomStaticPickList_7]     INT             NULL,
    [section3_UomStaticPickList_6]     INT             NULL,
    [section3_UomStaticPickList_5]     INT             NULL,
    [section3_UomStaticPickList_4]     INT             NULL,
    [section3_UomStaticPickList_3]     INT             NULL,
    [section3_UomStaticPickList_2]     INT             NULL,
    [section3_UomStaticPickList_10]    INT             NULL,
    [section3_UomStaticPickList_1]     INT             NULL,
    [section3_UomRes_Pit2]             INT             NULL,
    [section3_UomRes_Pit1]             INT             NULL,
    [section3_UomPV]                   INT             NULL,
    [section3_UomPSI]                  INT             NULL,
    [section3_UomLoss_Surface]         INT             NULL,
    [section3_UomLoss_Hole]            INT             NULL,
    [section3_UomLCM_lb_bbl]           INT             NULL,
    [section3_UomHTHPTemp]             INT             NULL,
    [section3_UomDepth_TVD]            INT             NULL,
    [section3_UomDepth]                INT             NULL,
    [section3_UomBrine]                INT             NULL,
    [section3_UomAct_Pit2]             INT             NULL,
    [section3_UomAct_Pit1]             INT             NULL,
    [section3_Type]                    NVARCHAR (MAX)  NULL,
    [section3_Trip_Tank]               DECIMAL (19, 9) NULL,
    [section3_Time]                    DATETIME        NULL,
    [section3_Temp_FL]                 DECIMAL (19, 9) NULL,
    [section3_Temp]                    DECIMAL (19, 9) NULL,
    [section3_TS]                      DECIMAL (19, 9) NULL,
    [section3_StaticPickList_9]        NVARCHAR (MAX)  NULL,
    [section3_StaticPickList_8]        NVARCHAR (MAX)  NULL,
    [section3_StaticPickList_7]        NVARCHAR (MAX)  NULL,
    [section3_StaticPickList_6]        NVARCHAR (MAX)  NULL,
    [section3_StaticPickList_5]        NVARCHAR (MAX)  NULL,
    [section3_StaticPickList_4]        NVARCHAR (MAX)  NULL,
    [section3_StaticPickList_3]        NVARCHAR (MAX)  NULL,
    [section3_StaticPickList_2]        NVARCHAR (MAX)  NULL,
    [section3_StaticPickList_10]       NVARCHAR (MAX)  NULL,
    [section3_StaticPickList_1]        NVARCHAR (MAX)  NULL,
    [section3_Sand]                    DECIMAL (19, 9) NULL,
    [section3_Retort_Density]          DECIMAL (19, 9) NULL,
    [section3_Res_Pit2]                DECIMAL (19, 9) NULL,
    [section3_Res_Pit1]                DECIMAL (19, 9) NULL,
    [section3_Potassium]               DECIMAL (19, 9) NULL,
    [section3_Pot_Ash]                 DECIMAL (19, 9) NULL,
    [section3_Pm]                      DECIMAL (19, 9) NULL,
    [section3_PV_Temp]                 DECIMAL (19, 9) NULL,
    [section3_PV]                      DECIMAL (19, 9) NULL,
    [section3_PSI]                     DECIMAL (19, 9) NULL,
    [section3_PH]                      DECIMAL (19, 9) NULL,
    [section3_PF]                      DECIMAL (19, 9) NULL,
    [section3_Oil_Brine_Ratio]         DECIMAL (19, 9) NULL,
    [section3_Oil]                     DECIMAL (19, 9) NULL,
    [section3_OW]                      NVARCHAR (MAX)  NULL,
    [section3_StaticUserDefined_9]     NVARCHAR (MAX)  NULL,
    [section3_StaticUserDefined_8]     NVARCHAR (MAX)  NULL,
    [section3_StaticUserDefined_7]     NVARCHAR (MAX)  NULL,
    [section3_StaticUserDefined_6]     NVARCHAR (MAX)  NULL,
    [section3_StaticUserDefined_5]     NVARCHAR (MAX)  NULL,
    [section3_StaticUserDefined_4]     NVARCHAR (MAX)  NULL,
    [section3_StaticUserDefined_3]     NVARCHAR (MAX)  NULL,
    [section3_StaticUserDefined_2]     NVARCHAR (MAX)  NULL,
    [section3_StaticUserDefined_10]    NVARCHAR (MAX)  NULL,
    [section3_StaticUserDefined_1]     NVARCHAR (MAX)  NULL,
    [section3_Mg]                      DECIMAL (19, 9) NULL,
    [section3_MF]                      DECIMAL (19, 9) NULL,
    [section3_MBT]                     DECIMAL (19, 9) NULL,
    [section3_Loss_Surface]            DECIMAL (19, 9) NULL,
    [section3_Loss_Hole]               DECIMAL (19, 9) NULL,
    [section3_Lime]                    DECIMAL (19, 9) NULL,
    [section3_LGS]                     DECIMAL (19, 9) NULL,
    [section3_LCM_lb_bbl]              DECIMAL (19, 9) NULL,
    [section3_LCM]                     DECIMAL (19, 9) NULL,
    [section3_HTHP_Temp]               DECIMAL (19, 9) NULL,
    [section3_HTHP]                    DECIMAL (19, 9) NULL,
    [section3_HGS]                     DECIMAL (19, 9) NULL,
    [section3_H2S]                     DECIMAL (19, 9) NULL,
    [section3_Gel30m]                  DECIMAL (19, 9) NULL,
    [section3_Gel10s]                  DECIMAL (19, 9) NULL,
    [section3_Gel10m]                  DECIMAL (19, 9) NULL,
    [section3_Filtrate]                DECIMAL (19, 9) NULL,
    [section3_FV]                      DECIMAL (19, 9) NULL,
    [section3_Engineer]                NVARCHAR (MAX)  NULL,
    [section3_ES]                      DECIMAL (19, 9) NULL,
    [section3_ECD]                     DECIMAL (19, 9) NULL,
    [section3_Depth_TVD]               DECIMAL (19, 9) NULL,
    [section3_Depth]                   DECIMAL (19, 9) NULL,
    [section3_Density]                 DECIMAL (19, 9) NULL,
    [section3_Critical_Velocity]       DECIMAL (19, 9) NULL,
    [section3_Critical_Flow_Rate]      DECIMAL (19, 9) NULL,
    [section3_Company]                 NVARCHAR (MAX)  NULL,
    [section3_Chloride]                DECIMAL (19, 9) NULL,
    [section3_Carbonate]               DECIMAL (19, 9) NULL,
    [section3_Calcium]                 DECIMAL (19, 9) NULL,
    [section3_Cake]                    NVARCHAR (MAX)  NULL,
    [section3_CaCl]                    DECIMAL (19, 9) NULL,
    [section3_CCI]                     DECIMAL (19, 9) NULL,
    [section3_Brine]                   DECIMAL (19, 9) NULL,
    [section3_BottomsUpTime]           DATETIME        NULL,
    [section3_Barite]                  DECIMAL (19, 9) NULL,
    [section3_Annular_Viscosity]       DECIMAL (19, 9) NULL,
    [section3_Alkalinity]              DECIMAL (19, 9) NULL,
    [section3_Act_Pit2]                DECIMAL (19, 9) NULL,
    [section3_Act_Pit1]                DECIMAL (19, 9) NULL,
    [section2_YP_Temp]                 DECIMAL (19, 9) NULL,
    [section2_YP]                      DECIMAL (19, 9) NULL,
    [section2_Weight_Out]              DECIMAL (19, 9) NULL,
    [section2_Weight_In_ppg]           DECIMAL (19, 9) NULL,
    [section2_Weight_In]               DECIMAL (19, 9) NULL,
    [section2_Water]                   DECIMAL (19, 9) NULL,
    [section2_WL]                      DECIMAL (19, 9) NULL,
    [section2_Volume_Reverse]          DECIMAL (19, 9) NULL,
    [section2_Volume]                  DECIMAL (19, 9) NULL,
    [section2_Viscosity]               DECIMAL (19, 9) NULL,
    [section2_UomWeight_Out]           INT             NULL,
    [section2_UomWeight_In]            INT             NULL,
    [section2_UomVolume]               INT             NULL,
    [section2_UomStaticUserDefined_9]  INT             NULL,
    [section2_UomStaticUserDefined_8]  INT             NULL,
    [section2_UomStaticUserDefined_7]  INT             NULL,
    [section2_UomStaticUserDefined_6]  INT             NULL,
    [section2_UomStaticUserDefined_5]  INT             NULL,
    [section2_UomStaticUserDefined_4]  INT             NULL,
    [section2_UomStaticUserDefined_3]  INT             NULL,
    [section2_UomStaticUserDefined_2]  INT             NULL,
    [section2_UomStaticUserDefined_10] INT             NULL,
    [section2_UomStaticUserDefined_1]  INT             NULL,
    [section2_UomTrip_Tank]            INT             NULL,
    [section2_UomTemp_FL]              INT             NULL,
    [section2_UomTemp]                 INT             NULL,
    [section2_UomStaticPickList_9]     INT             NULL,
    [section2_UomStaticPickList_8]     INT             NULL,
    [section2_UomStaticPickList_7]     INT             NULL,
    [section2_UomStaticPickList_6]     INT             NULL,
    [section2_UomStaticPickList_5]     INT             NULL,
    [section2_UomStaticPickList_4]     INT             NULL,
    [section2_UomStaticPickList_3]     INT             NULL,
    [section2_UomStaticPickList_2]     INT             NULL,
    [section2_UomStaticPickList_10]    INT             NULL,
    [section2_UomStaticPickList_1]     INT             NULL,
    [section2_UomRes_Pit2]             INT             NULL,
    [section2_UomRes_Pit1]             INT             NULL,
    [section2_UomPV]                   INT             NULL,
    [section2_UomPSI]                  INT             NULL,
    [section2_UomLoss_Surface]         INT             NULL,
    [section2_UomLoss_Hole]            INT             NULL,
    [section2_UomLCM_lb_bbl]           INT             NULL,
    [section2_UomHTHPTemp]             INT             NULL,
    [section2_UomDepth_TVD]            INT             NULL,
    [section2_UomDepth]                INT             NULL,
    [section2_UomBrine]                INT             NULL,
    [section2_UomAct_Pit2]             INT             NULL,
    [section2_UomAct_Pit1]             INT             NULL,
    [section2_Type]                    NVARCHAR (MAX)  NULL,
    [section2_Trip_Tank]               DECIMAL (19, 9) NULL,
    [section2_Time]                    DATETIME        NULL,
    [section2_Temp_FL]                 DECIMAL (19, 9) NULL,
    [section2_Temp]                    DECIMAL (19, 9) NULL,
    [section2_TS]                      DECIMAL (19, 9) NULL,
    [section2_StaticPickList_9]        NVARCHAR (MAX)  NULL,
    [section2_StaticPickList_7]        NVARCHAR (MAX)  NULL,
    [section2_StaticPickList_5]        NVARCHAR (MAX)  NULL,
    [section2_StaticPickList_3]        NVARCHAR (MAX)  NULL,
    [section2_StaticPickList_10]       NVARCHAR (MAX)  NULL,
    [section2_StaticPickList_1]        NVARCHAR (MAX)  NULL,
    [section2_Sand]                    DECIMAL (19, 9) NULL,
    [section2_Retort_Density]          DECIMAL (19, 9) NULL,
    [section2_Res_Pit2]                DECIMAL (19, 9) NULL,
    [section2_Res_Pit1]                DECIMAL (19, 9) NULL,
    [section2_Potassium]               DECIMAL (19, 9) NULL,
    [section2_Pot_Ash]                 DECIMAL (19, 9) NULL,
    [section2_Pm]                      DECIMAL (19, 9) NULL,
    [section2_PV_Temp]                 DECIMAL (19, 9) NULL,
    [section2_PV]                      DECIMAL (19, 9) NULL,
    [section2_PSI]                     DECIMAL (19, 9) NULL,
    [section2_PH]                      DECIMAL (19, 9) NULL,
    [section2_PF]                      DECIMAL (19, 9) NULL,
    [section2_Oil_Brine_Ratio]         DECIMAL (19, 9) NULL,
    [section2_Oil]                     DECIMAL (19, 9) NULL,
    [section2_OW]                      NVARCHAR (MAX)  NULL,
    [section2_StaticUserDefined_9]     NVARCHAR (MAX)  NULL,
    [section2_StaticUserDefined_8]     NVARCHAR (MAX)  NULL,
    [section2_StaticUserDefined_7]     NVARCHAR (MAX)  NULL,
    [section2_StaticUserDefined_6]     NVARCHAR (MAX)  NULL,
    [section2_StaticUserDefined_5]     NVARCHAR (MAX)  NULL,
    [section2_StaticUserDefined_4]     NVARCHAR (MAX)  NULL,
    [section2_StaticUserDefined_3]     NVARCHAR (MAX)  NULL,
    [section2_StaticUserDefined_2]     NVARCHAR (MAX)  NULL,
    [section2_StaticUserDefined_10]    NVARCHAR (MAX)  NULL,
    [section2_StaticUserDefined_1]     NVARCHAR (MAX)  NULL,
    [section2_Mg]                      DECIMAL (19, 9) NULL,
    [section2_MF]                      DECIMAL (19, 9) NULL,
    [section2_MBT]                     DECIMAL (19, 9) NULL,
    [section2_Loss_Surface]            DECIMAL (19, 9) NULL,
    [section2_Loss_Hole]               DECIMAL (19, 9) NULL,
    [section2_Lime]                    DECIMAL (19, 9) NULL,
    [section2_LGS]                     DECIMAL (19, 9) NULL,
    [section2_LCM_lb_bbl]              DECIMAL (19, 9) NULL,
    [section2_LCM]                     DECIMAL (19, 9) NULL,
    [section2_HTHP_Temp]               DECIMAL (19, 9) NULL,
    [section2_HTHP]                    DECIMAL (19, 9) NULL,
    [section2_HGS]                     DECIMAL (19, 9) NULL,
    [section2_H2S]                     DECIMAL (19, 9) NULL,
    [section2_Gel30m]                  DECIMAL (19, 9) NULL,
    [section2_Gel10s]                  DECIMAL (19, 9) NULL,
    [section2_Gel10m]                  DECIMAL (19, 9) NULL,
    [section2_Filtrate]                DECIMAL (19, 9) NULL,
    [section2_FV]                      DECIMAL (19, 9) NULL,
    [section2_Engineer]                NVARCHAR (MAX)  NULL,
    [section2_ES]                      DECIMAL (19, 9) NULL,
    [section2_ECD]                     DECIMAL (19, 9) NULL,
    [section2_Depth_TVD]               DECIMAL (19, 9) NULL,
    [section2_Depth]                   DECIMAL (19, 9) NULL,
    [section2_Density]                 DECIMAL (19, 9) NULL,
    [section2_Critical_Velocity]       DECIMAL (19, 9) NULL,
    [section2_Critical_Flow_Rate]      DECIMAL (19, 9) NULL,
    [section2_Company]                 NVARCHAR (MAX)  NULL,
    [section2_Chloride]                DECIMAL (19, 9) NULL,
    [section2_Carbonate]               DECIMAL (19, 9) NULL,
    [section2_Calcium]                 DECIMAL (19, 9) NULL,
    [section2_Cake]                    NVARCHAR (MAX)  NULL,
    [section2_CaCl]                    DECIMAL (19, 9) NULL,
    [section2_CCI]                     DECIMAL (19, 9) NULL,
    [section2_Brine]                   DECIMAL (19, 9) NULL,
    [section2_BottomsUpTime]           DATETIME        NULL,
    [section2_Barite]                  DECIMAL (19, 9) NULL,
    [section2_Annular_Viscosity]       DECIMAL (19, 9) NULL,
    [section2_Alkalinity]              DECIMAL (19, 9) NULL,
    [section2_Act_Pit2]                DECIMAL (19, 9) NULL,
    [section2_Act_Pit1]                DECIMAL (19, 9) NULL,
    [section1_YP_Temp]                 DECIMAL (19, 9) NULL,
    [section1_YP]                      DECIMAL (19, 9) NULL,
    [section1_Weight_Out]              DECIMAL (19, 9) NULL,
    [section1_Weight_In_ppg]           DECIMAL (19, 9) NULL,
    [section1_Weight_In]               DECIMAL (19, 9) NULL,
    [section1_Water]                   DECIMAL (19, 9) NULL,
    [section1_WL]                      DECIMAL (19, 9) NULL,
    [section1_Volume_Reverse]          DECIMAL (19, 9) NULL,
    [section1_Volume]                  DECIMAL (19, 9) NULL,
    [section1_Viscosity]               DECIMAL (19, 9) NULL,
    [section1_UomWeight_Out]           INT             NULL,
    [section1_UomWeight_In]            INT             NULL,
    [section1_UomVolume]               INT             NULL,
    [section1_UomStaticUserDefined_9]  INT             NULL,
    [section1_UomStaticUserDefined_8]  INT             NULL,
    [section1_UomStaticUserDefined_7]  INT             NULL,
    [section1_UomStaticUserDefined_6]  INT             NULL,
    [section1_UomStaticUserDefined_5]  INT             NULL,
    [section1_UomStaticUserDefined_4]  INT             NULL,
    [section1_UomStaticUserDefined_3]  INT             NULL,
    [section1_UomStaticUserDefined_2]  INT             NULL,
    [section1_UomStaticUserDefined_10] INT             NULL,
    [section1_UomStaticUserDefined_1]  INT             NULL,
    [section1_UomTrip_Tank]            INT             NULL,
    [section1_UomTemp_FL]              INT             NULL,
    [section1_UomTemp]                 INT             NULL,
    [section1_UomStaticPickList_9]     INT             NULL,
    [section1_UomStaticPickList_8]     INT             NULL,
    [section1_UomStaticPickList_7]     INT             NULL,
    [section1_UomStaticPickList_6]     INT             NULL,
    [section1_UomStaticPickList_5]     INT             NULL,
    [section1_UomStaticPickList_4]     INT             NULL,
    [section1_UomStaticPickList_3]     INT             NULL,
    [section1_UomStaticPickList_2]     INT             NULL,
    [section1_UomStaticPickList_10]    INT             NULL,
    [section1_UomStaticPickList_1]     INT             NULL,
    [section1_UomRes_Pit2]             INT             NULL,
    [section1_UomRes_Pit1]             INT             NULL,
    [section1_UomPV]                   INT             NULL,
    [section1_UomPSI]                  INT             NULL,
    [section1_UomLoss_Surface]         INT             NULL,
    [section1_UomLoss_Hole]            INT             NULL,
    [section1_UomLCM_lb_bbl]           INT             NULL,
    [section1_UomHTHPTemp]             INT             NULL,
    [section1_UomDepth_TVD]            INT             NULL,
    [section1_UomDepth]                INT             NULL,
    [section1_UomBrine]                INT             NULL,
    [section1_UomAct_Pit2]             INT             NULL,
    [section1_UomAct_Pit1]             INT             NULL,
    [section1_Type]                    NVARCHAR (MAX)  NULL,
    [section1_Trip_Tank]               DECIMAL (19, 9) NULL,
    [section1_Time]                    DATETIME        NULL,
    [section1_Temp_FL]                 DECIMAL (19, 9) NULL,
    [section1_Temp]                    DECIMAL (19, 9) NULL,
    [section1_TS]                      DECIMAL (19, 9) NULL,
    [section1_StaticPickList_9]        NVARCHAR (MAX)  NULL,
    [section1_StaticPickList_8]        NVARCHAR (MAX)  NULL,
    [section1_StaticPickList_7]        NVARCHAR (MAX)  NULL,
    [section1_StaticPickList_6]        NVARCHAR (MAX)  NULL,
    [section1_StaticPickList_5]        NVARCHAR (MAX)  NULL,
    [section1_StaticPickList_4]        NVARCHAR (MAX)  NULL,
    [section1_StaticPickList_3]        NVARCHAR (MAX)  NULL,
    [section1_StaticPickList_2]        NVARCHAR (MAX)  NULL,
    [section1_StaticPickList_10]       NVARCHAR (MAX)  NULL,
    [section1_StaticPickList_1]        NVARCHAR (MAX)  NULL,
    [section1_Sand]                    DECIMAL (19, 9) NULL,
    [section1_Retort_Density]          DECIMAL (19, 9) NULL,
    [section1_Res_Pit2]                DECIMAL (19, 9) NULL,
    [section1_Res_Pit1]                DECIMAL (19, 9) NULL,
    [section1_Potassium]               DECIMAL (19, 9) NULL,
    [section1_Pot_Ash]                 DECIMAL (19, 9) NULL,
    [section1_Pm]                      DECIMAL (19, 9) NULL,
    [section1_PV_Temp]                 DECIMAL (19, 9) NULL,
    [section1_PV]                      DECIMAL (19, 9) NULL,
    [section1_PSI]                     DECIMAL (19, 9) NULL,
    [section1_PH]                      DECIMAL (19, 9) NULL,
    [section1_PF]                      DECIMAL (19, 9) NULL,
    [section1_Oil_Brine_Ratio]         DECIMAL (19, 9) NULL,
    [section1_Oil]                     DECIMAL (19, 9) NULL,
    [section1_OW]                      NVARCHAR (MAX)  NULL,
    [section1_StaticUserDefined_9]     NVARCHAR (MAX)  NULL,
    [section1_StaticUserDefined_8]     NVARCHAR (MAX)  NULL,
    [section1_StaticUserDefined_7]     NVARCHAR (MAX)  NULL,
    [section1_StaticUserDefined_6]     NVARCHAR (MAX)  NULL,
    [section1_StaticUserDefined_5]     NVARCHAR (MAX)  NULL,
    [section1_StaticUserDefined_4]     NVARCHAR (MAX)  NULL,
    [section1_StaticUserDefined_3]     NVARCHAR (MAX)  NULL,
    [section1_StaticUserDefined_2]     NVARCHAR (MAX)  NULL,
    [section1_StaticUserDefined_10]    NVARCHAR (MAX)  NULL,
    [section1_StaticUserDefined_1]     NVARCHAR (MAX)  NULL,
    [section1_Mg]                      DECIMAL (19, 9) NULL,
    [section1_MF]                      DECIMAL (19, 9) NULL,
    [section1_MBT]                     DECIMAL (19, 9) NULL,
    [section1_Loss_Surface]            DECIMAL (19, 9) NULL,
    [section1_Loss_Hole]               DECIMAL (19, 9) NULL,
    [section1_Lime]                    DECIMAL (19, 9) NULL,
    [section1_LGS]                     DECIMAL (19, 9) NULL,
    [section1_LCM_lb_bbl]              DECIMAL (19, 9) NULL,
    [section1_LCM]                     DECIMAL (19, 9) NULL,
    [section1_HTHP_Temp]               DECIMAL (19, 9) NULL,
    [section1_HTHP]                    DECIMAL (19, 9) NULL,
    [section1_HGS]                     DECIMAL (19, 9) NULL,
    [section1_H2S]                     DECIMAL (19, 9) NULL,
    [section1_Gel30m]                  DECIMAL (19, 9) NULL,
    [section1_Gel10s]                  DECIMAL (19, 9) NULL,
    [section1_Gel10m]                  DECIMAL (19, 9) NULL,
    [section1_Filtrate]                DECIMAL (19, 9) NULL,
    [section1_FV]                      DECIMAL (19, 9) NULL,
    [section1_Engineer]                NVARCHAR (MAX)  NULL,
    [section1_ES]                      DECIMAL (19, 9) NULL,
    [section1_ECD]                     DECIMAL (19, 9) NULL,
    [section1_Depth_TVD]               DECIMAL (19, 9) NULL,
    [section1_Depth]                   DECIMAL (19, 9) NULL,
    [section1_Density]                 DECIMAL (19, 9) NULL,
    [section1_Critical_Velocity]       DECIMAL (19, 9) NULL,
    [section1_Critical_Flow_Rate]      DECIMAL (19, 9) NULL,
    [section1_Company]                 NVARCHAR (MAX)  NULL,
    [section1_Chloride]                DECIMAL (19, 9) NULL,
    [section1_Carbonate]               DECIMAL (19, 9) NULL,
    [section1_Calcium]                 DECIMAL (19, 9) NULL,
    [section1_Cake]                    NVARCHAR (MAX)  NULL,
    [section1_CaCl]                    DECIMAL (19, 9) NULL,
    [section1_CCI]                     DECIMAL (19, 9) NULL,
    [section1_Brine]                   DECIMAL (19, 9) NULL,
    [section1_BottomsUpTime]           DATETIME        NULL,
    [section1_Barite]                  DECIMAL (19, 9) NULL,
    [section1_Annular_Viscosity]       DECIMAL (19, 9) NULL,
    [section1_Alkalinity]              DECIMAL (19, 9) NULL,
    [section1_Act_Pit2]                DECIMAL (19, 9) NULL,
    [section1_Act_Pit1]                DECIMAL (19, 9) NULL,
    [report_Date]                      DATETIME        NOT NULL,
    [job_number]                       BIGINT          NOT NULL,
    [Comments]                         NVARCHAR (MAX)  NULL,
    [location_id]                      INT             NULL,
    [section1_UomYP]                   INT             NULL,
    [section2_UomYP]                   INT             NULL,
    [section2_StaticPickList_2]        NVARCHAR (MAX)  NULL,
    [section2_StaticPickList_4]        NVARCHAR (MAX)  NULL,
    [section2_StaticPickList_6]        NVARCHAR (MAX)  NULL,
    [section2_StaticPickList_8]        NVARCHAR (MAX)  NULL,
    [section3_UomYP]                   INT             NULL,
    [section4_UomYP]                   INT             NULL,
    [UserDefined_9]                    NVARCHAR (MAX)  NULL,
    [UserDefined_8]                    NVARCHAR (MAX)  NULL,
    [UserDefined_7]                    NVARCHAR (MAX)  NULL,
    [UserDefined_6]                    NVARCHAR (MAX)  NULL,
    [UserDefined_5]                    NVARCHAR (MAX)  NULL,
    [UserDefined_40]                   NVARCHAR (MAX)  NULL,
    [UserDefined_4]                    NVARCHAR (MAX)  NULL,
    [UserDefined_39]                   NVARCHAR (MAX)  NULL,
    [UserDefined_38]                   NVARCHAR (MAX)  NULL,
    [UserDefined_37]                   NVARCHAR (MAX)  NULL,
    [UserDefined_36]                   NVARCHAR (MAX)  NULL,
    [UserDefined_35]                   NVARCHAR (MAX)  NULL,
    [UserDefined_34]                   NVARCHAR (MAX)  NULL,
    [UserDefined_33]                   NVARCHAR (MAX)  NULL,
    [UserDefined_32]                   NVARCHAR (MAX)  NULL,
    [UserDefined_31]                   NVARCHAR (MAX)  NULL,
    [UserDefined_30]                   NVARCHAR (MAX)  NULL,
    [UserDefined_3]                    NVARCHAR (MAX)  NULL,
    [UserDefined_29]                   NVARCHAR (MAX)  NULL,
    [UserDefined_28]                   NVARCHAR (MAX)  NULL,
    [UserDefined_27]                   NVARCHAR (MAX)  NULL,
    [UserDefined_26]                   NVARCHAR (MAX)  NULL,
    [UserDefined_25]                   NVARCHAR (MAX)  NULL,
    [UserDefined_24]                   NVARCHAR (MAX)  NULL,
    [UserDefined_23]                   NVARCHAR (MAX)  NULL,
    [UserDefined_22]                   NVARCHAR (MAX)  NULL,
    [UserDefined_21]                   NVARCHAR (MAX)  NULL,
    [UserDefined_20]                   NVARCHAR (MAX)  NULL,
    [UserDefined_2]                    NVARCHAR (MAX)  NULL,
    [UserDefined_19]                   NVARCHAR (MAX)  NULL,
    [UserDefined_18]                   NVARCHAR (MAX)  NULL,
    [UserDefined_17]                   NVARCHAR (MAX)  NULL,
    [UserDefined_16]                   NVARCHAR (MAX)  NULL,
    [UserDefined_15]                   NVARCHAR (MAX)  NULL,
    [UserDefined_14]                   NVARCHAR (MAX)  NULL,
    [UserDefined_13]                   NVARCHAR (MAX)  NULL,
    [UserDefined_12]                   NVARCHAR (MAX)  NULL,
    [UserDefined_11]                   NVARCHAR (MAX)  NULL,
    [UserDefined_10]                   NVARCHAR (MAX)  NULL,
    [UserDefined_1]                    NVARCHAR (MAX)  NULL,
    [UomUserDefined_9]                 INT             NULL,
    [UomUserDefined_8]                 INT             NULL,
    [UomUserDefined_7]                 INT             NULL,
    [UomUserDefined_6]                 INT             NULL,
    [UomUserDefined_5]                 INT             NULL,
    [UomUserDefined_4]                 INT             NULL,
    [UomUserDefined_39]                INT             NULL,
    [UomUserDefined_38]                INT             NULL,
    [UomUserDefined_37]                INT             NULL,
    [UomUserDefined_36]                INT             NULL,
    [UomUserDefined_35]                INT             NULL,
    [UomUserDefined_34]                INT             NULL,
    [UomUserDefined_33]                INT             NULL,
    [UomUserDefined_32]                INT             NULL,
    [UomUserDefined_31]                INT             NULL,
    [UomUserDefined_30]                INT             NULL,
    [UomUserDefined_3]                 INT             NULL,
    [UomUserDefined_29]                INT             NULL,
    [UomUserDefined_28]                INT             NULL,
    [UomUserDefined_27]                INT             NULL,
    [UomUserDefined_26]                INT             NULL,
    [UomUserDefined_25]                INT             NULL,
    [UomUserDefined_24]                INT             NULL,
    [UomUserDefined_23]                INT             NULL,
    [UomUserDefined_22]                INT             NULL,
    [UomUserDefined_21]                INT             NULL,
    [UomUserDefined_20]                INT             NULL,
    [UomUserDefined_2]                 INT             NULL,
    [UomUserDefined_19]                INT             NULL,
    [UomUserDefined_18]                INT             NULL,
    [UomUserDefined_17]                INT             NULL,
    [UomUserDefined_16]                INT             NULL,
    [UomUserDefined_15]                INT             NULL,
    [UomUserDefined_14]                INT             NULL,
    [UomUserDefined_13]                INT             NULL,
    [UomUserDefined_12]                INT             NULL,
    [UomUserDefined_11]                INT             NULL,
    [UomUserDefined_10]                INT             NULL,
    [UomUserDefined_1]                 INT             NULL,
    [PickList_9]                       NVARCHAR (MAX)  NULL,
    [PickList_8]                       NVARCHAR (MAX)  NULL,
    [PickList_7]                       NVARCHAR (MAX)  NULL,
    [PickList_6]                       NVARCHAR (MAX)  NULL,
    [PickList_5]                       NVARCHAR (MAX)  NULL,
    [PickList_4]                       NVARCHAR (MAX)  NULL,
    [PickList_3]                       NVARCHAR (MAX)  NULL,
    [PickList_2]                       NVARCHAR (MAX)  NULL,
    [PickList_10]                      NVARCHAR (MAX)  NULL,
    [PickList_1]                       NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_MudCheck_4] PRIMARY KEY CLUSTERED ([mudcheck_4_id] ASC)
);

