CREATE TABLE [dbo].[PackerItem] (
    [packeritem_id]        INT             IDENTITY (1, 1) NOT NULL,
    [well_id]              BIGINT          NOT NULL,
    [report_Date]          DATETIME        NOT NULL,
    [line_number]          BIGINT          NOT NULL,
    [job_number]           BIGINT          NOT NULL,
    [UserDefined_9]        NVARCHAR (MAX)  NULL,
    [UserDefined_8]        NVARCHAR (MAX)  NULL,
    [UserDefined_7]        NVARCHAR (MAX)  NULL,
    [UserDefined_6]        NVARCHAR (MAX)  NULL,
    [UserDefined_5]        NVARCHAR (MAX)  NULL,
    [UserDefined_4]        NVARCHAR (MAX)  NULL,
    [UserDefined_3]        NVARCHAR (MAX)  NULL,
    [UserDefined_20]       NVARCHAR (MAX)  NULL,
    [UserDefined_2]        NVARCHAR (MAX)  NULL,
    [UserDefined_19]       NVARCHAR (MAX)  NULL,
    [UserDefined_18]       NVARCHAR (MAX)  NULL,
    [UserDefined_17]       NVARCHAR (MAX)  NULL,
    [UserDefined_16]       NVARCHAR (MAX)  NULL,
    [UserDefined_15]       NVARCHAR (MAX)  NULL,
    [UserDefined_14]       NVARCHAR (MAX)  NULL,
    [UserDefined_13]       NVARCHAR (MAX)  NULL,
    [UserDefined_12]       NVARCHAR (MAX)  NULL,
    [UserDefined_11]       NVARCHAR (MAX)  NULL,
    [UserDefined_10]       NVARCHAR (MAX)  NULL,
    [UserDefined_1]        NVARCHAR (MAX)  NULL,
    [reportTypeId]         BIGINT          NOT NULL,
    [PackerType]           NVARCHAR (MAX)  NULL,
    [PackerTVD]            DECIMAL (19, 9) NULL,
    [PackerTMD]            DECIMAL (19, 9) NULL,
    [PackerStatus]         NVARCHAR (MAX)  NULL,
    [PackerSize]           DECIMAL (19, 9) NULL,
    [PackerSN]             NVARCHAR (MAX)  NULL,
    [PackerOD]             DECIMAL (19, 9) NULL,
    [PackerModel]          NVARCHAR (MAX)  NULL,
    [PackerMake]           NVARCHAR (MAX)  NULL,
    [PackerID]             DECIMAL (19, 9) NULL,
    [PackerConnectionType] NVARCHAR (MAX)  NULL,
    [PackerConnectionSize] DECIMAL (19, 9) NULL,
    CONSTRAINT [PK_PackerItem] PRIMARY KEY CLUSTERED ([packeritem_id] ASC)
);

