CREATE TABLE [dbo].[SurveyItem] (
    [surveyitem_id]  INT             IDENTITY (1, 1) NOT NULL,
    [well_id]        BIGINT          NULL,
    [report_Date]    DATETIME        NOT NULL,
    [line_number]    BIGINT          NOT NULL,
    [job_number]     BIGINT          NOT NULL,
    [UserDefined_9]  NVARCHAR (MAX)  NULL,
    [UserDefined_8]  NVARCHAR (MAX)  NULL,
    [UserDefined_7]  NVARCHAR (MAX)  NULL,
    [UserDefined_6]  NVARCHAR (MAX)  NULL,
    [UserDefined_5]  NVARCHAR (MAX)  NULL,
    [UserDefined_4]  NVARCHAR (MAX)  NULL,
    [UserDefined_3]  NVARCHAR (MAX)  NULL,
    [UserDefined_20] NVARCHAR (MAX)  NULL,
    [UserDefined_2]  NVARCHAR (MAX)  NULL,
    [UserDefined_19] NVARCHAR (MAX)  NULL,
    [UserDefined_18] NVARCHAR (MAX)  NULL,
    [UserDefined_17] NVARCHAR (MAX)  NULL,
    [UserDefined_16] NVARCHAR (MAX)  NULL,
    [UserDefined_15] NVARCHAR (MAX)  NULL,
    [UserDefined_14] NVARCHAR (MAX)  NULL,
    [UserDefined_13] NVARCHAR (MAX)  NULL,
    [UserDefined_12] NVARCHAR (MAX)  NULL,
    [UserDefined_11] NVARCHAR (MAX)  NULL,
    [UserDefined_10] NVARCHAR (MAX)  NULL,
    [UserDefined_1]  NVARCHAR (MAX)  NULL,
    [TVD]            DECIMAL (19, 9) NULL,
    [Section]        NVARCHAR (MAX)  NULL,
    [reportTypeId]   BIGINT          NOT NULL,
    [NS]             NVARCHAR (MAX)  NULL,
    [MD]             DECIMAL (19, 9) NULL,
    [Inclination]    DECIMAL (19, 9) NULL,
    [EW]             NVARCHAR (MAX)  NULL,
    [DLS]            DECIMAL (19, 9) NULL,
    [Closure]        DECIMAL (19, 9) NULL,
    [Build]          NVARCHAR (MAX)  NULL,
    [Azimuth]        DECIMAL (19, 9) NULL,
    CONSTRAINT [PK_SurveyItem] PRIMARY KEY CLUSTERED ([surveyitem_id] ASC)
);

