CREATE TABLE [dbo].[TimeLogActivityItem] (
    [timelogactivityitem_id] INT             IDENTITY (1, 1) NOT NULL,
    [well_id]                BIGINT          NULL,
    [report_Date]            DATETIME        NOT NULL,
    [line_number]            BIGINT          NOT NULL,
    [job_number]             BIGINT          NOT NULL,
    [UserDefined_5]          NVARCHAR (MAX)  NULL,
    [UserDefined_4]          NVARCHAR (MAX)  NULL,
    [UserDefined_3]          NVARCHAR (MAX)  NULL,
    [UserDefined_2]          NVARCHAR (MAX)  NULL,
    [UserDefined_1]          NVARCHAR (MAX)  NULL,
    [UomUserDefined_5]       INT             NULL,
    [UomUserDefined_4]       INT             NULL,
    [UomUserDefined_3]       INT             NULL,
    [UomUserDefined_2]       INT             NULL,
    [UomUserDefined_1]       INT             NULL,
    [UomPickList_2]          INT             NULL,
    [UomPickList_1]          INT             NULL,
    [SubPhaseID]             NVARCHAR (MAX)  NULL,
    [StartTime]              NVARCHAR (MAX)  NULL,
    [reportTypeId]           BIGINT          NOT NULL,
    [PickList_2]             NVARCHAR (MAX)  NULL,
    [PickList_1]             NVARCHAR (MAX)  NULL,
    [PhaseID]                NVARCHAR (MAX)  NULL,
    [PT_NPT]                 NVARCHAR (MAX)  NULL,
    [LossCost]               DECIMAL (19, 9) NULL,
    [LossComments]           NVARCHAR (MAX)  NULL,
    [LossCode]               NVARCHAR (MAX)  NULL,
    [EndTime]                NVARCHAR (MAX)  NULL,
    [Duration]               DECIMAL (19, 9) NULL,
    [Description]            NVARCHAR (MAX)  NULL,
    [ActivityType]           NVARCHAR (MAX)  NULL,
    [NPTCodeID]              NVARCHAR (MAX)  NULL,
    [RowID]                  BIGINT          NOT NULL,
    [location_id]            INT             NULL,
    CONSTRAINT [PK_TimeLogActivityItem] PRIMARY KEY CLUSTERED ([timelogactivityitem_id] ASC)
);

