CREATE TABLE [dbo].[TubingItem] (
    [tubingitem_id]  INT             IDENTITY (1, 1) NOT NULL,
    [well_id]        BIGINT          NULL,
    [report_Date]    DATETIME        NOT NULL,
    [line_number]    BIGINT          NOT NULL,
    [job_number]     BIGINT          NOT NULL,
    [Weight]         NVARCHAR (MAX)  NULL,
    [UserDefined_9]  NVARCHAR (MAX)  NULL,
    [UserDefined_8]  NVARCHAR (MAX)  NULL,
    [UserDefined_70] NVARCHAR (MAX)  NULL,
    [UserDefined_7]  NVARCHAR (MAX)  NULL,
    [UserDefined_69] NVARCHAR (MAX)  NULL,
    [UserDefined_68] NVARCHAR (MAX)  NULL,
    [UserDefined_67] NVARCHAR (MAX)  NULL,
    [UserDefined_66] NVARCHAR (MAX)  NULL,
    [UserDefined_65] NVARCHAR (MAX)  NULL,
    [UserDefined_64] NVARCHAR (MAX)  NULL,
    [UserDefined_63] NVARCHAR (MAX)  NULL,
    [UserDefined_62] NVARCHAR (MAX)  NULL,
    [UserDefined_61] NVARCHAR (MAX)  NULL,
    [UserDefined_60] NVARCHAR (MAX)  NULL,
    [UserDefined_6]  NVARCHAR (MAX)  NULL,
    [UserDefined_59] NVARCHAR (MAX)  NULL,
    [UserDefined_58] NVARCHAR (MAX)  NULL,
    [UserDefined_57] NVARCHAR (MAX)  NULL,
    [UserDefined_56] NVARCHAR (MAX)  NULL,
    [UserDefined_55] NVARCHAR (MAX)  NULL,
    [UserDefined_54] NVARCHAR (MAX)  NULL,
    [UserDefined_53] NVARCHAR (MAX)  NULL,
    [UserDefined_52] NVARCHAR (MAX)  NULL,
    [UserDefined_51] NVARCHAR (MAX)  NULL,
    [UserDefined_50] NVARCHAR (MAX)  NULL,
    [UserDefined_5]  NVARCHAR (MAX)  NULL,
    [UserDefined_49] NVARCHAR (MAX)  NULL,
    [UserDefined_48] NVARCHAR (MAX)  NULL,
    [UserDefined_47] NVARCHAR (MAX)  NULL,
    [UserDefined_46] NVARCHAR (MAX)  NULL,
    [UserDefined_45] NVARCHAR (MAX)  NULL,
    [UserDefined_44] NVARCHAR (MAX)  NULL,
    [UserDefined_43] NVARCHAR (MAX)  NULL,
    [UserDefined_42] NVARCHAR (MAX)  NULL,
    [UserDefined_41] NVARCHAR (MAX)  NULL,
    [UserDefined_40] NVARCHAR (MAX)  NULL,
    [UserDefined_4]  NVARCHAR (MAX)  NULL,
    [UserDefined_39] NVARCHAR (MAX)  NULL,
    [UserDefined_38] NVARCHAR (MAX)  NULL,
    [UserDefined_37] NVARCHAR (MAX)  NULL,
    [UserDefined_36] NVARCHAR (MAX)  NULL,
    [UserDefined_35] NVARCHAR (MAX)  NULL,
    [UserDefined_34] NVARCHAR (MAX)  NULL,
    [UserDefined_33] NVARCHAR (MAX)  NULL,
    [UserDefined_32] NVARCHAR (MAX)  NULL,
    [UserDefined_31] NVARCHAR (MAX)  NULL,
    [UserDefined_30] NVARCHAR (MAX)  NULL,
    [UserDefined_3]  NVARCHAR (MAX)  NULL,
    [UserDefined_29] NVARCHAR (MAX)  NULL,
    [UserDefined_28] NVARCHAR (MAX)  NULL,
    [UserDefined_27] NVARCHAR (MAX)  NULL,
    [UserDefined_26] NVARCHAR (MAX)  NULL,
    [UserDefined_25] NVARCHAR (MAX)  NULL,
    [UserDefined_24] NVARCHAR (MAX)  NULL,
    [UserDefined_23] NVARCHAR (MAX)  NULL,
    [UserDefined_22] NVARCHAR (MAX)  NULL,
    [UserDefined_21] NVARCHAR (MAX)  NULL,
    [UserDefined_20] NVARCHAR (MAX)  NULL,
    [UserDefined_2]  NVARCHAR (MAX)  NULL,
    [UserDefined_19] NVARCHAR (MAX)  NULL,
    [UserDefined_18] NVARCHAR (MAX)  NULL,
    [UserDefined_17] NVARCHAR (MAX)  NULL,
    [UserDefined_16] NVARCHAR (MAX)  NULL,
    [UserDefined_15] NVARCHAR (MAX)  NULL,
    [UserDefined_14] NVARCHAR (MAX)  NULL,
    [UserDefined_13] NVARCHAR (MAX)  NULL,
    [UserDefined_12] NVARCHAR (MAX)  NULL,
    [UserDefined_11] NVARCHAR (MAX)  NULL,
    [UserDefined_10] NVARCHAR (MAX)  NULL,
    [UserDefined_1]  NVARCHAR (MAX)  NULL,
    [TorqueMin]      DECIMAL (19, 9) NULL,
    [TorqueMax]      DECIMAL (19, 9) NULL,
    [Top_TVD]        DECIMAL (19, 9) NULL,
    [Top_TMD]        DECIMAL (19, 9) NULL,
    [RunTime]        NVARCHAR (MAX)  NULL,
    [reportTypeId]   BIGINT          NOT NULL,
    [Remark]         NVARCHAR (MAX)  NULL,
    [PullTime]       NVARCHAR (MAX)  NULL,
    [PickList_9]     NVARCHAR (MAX)  NULL,
    [PickList_8]     NVARCHAR (MAX)  NULL,
    [PickList_7]     NVARCHAR (MAX)  NULL,
    [PickList_6]     NVARCHAR (MAX)  NULL,
    [PickList_5]     NVARCHAR (MAX)  NULL,
    [PickList_4]     NVARCHAR (MAX)  NULL,
    [PickList_3]     NVARCHAR (MAX)  NULL,
    [PickList_20]    NVARCHAR (MAX)  NULL,
    [PickList_2]     NVARCHAR (MAX)  NULL,
    [PickList_19]    NVARCHAR (MAX)  NULL,
    [PickList_18]    NVARCHAR (MAX)  NULL,
    [PickList_17]    NVARCHAR (MAX)  NULL,
    [PickList_16]    NVARCHAR (MAX)  NULL,
    [PickList_15]    NVARCHAR (MAX)  NULL,
    [PickList_14]    NVARCHAR (MAX)  NULL,
    [PickList_13]    NVARCHAR (MAX)  NULL,
    [PickList_12]    NVARCHAR (MAX)  NULL,
    [PickList_11]    NVARCHAR (MAX)  NULL,
    [PickList_10]    NVARCHAR (MAX)  NULL,
    [PickList_1]     NVARCHAR (MAX)  NULL,
    [OD]             NVARCHAR (MAX)  NULL,
    [Length]         DECIMAL (19, 9) NULL,
    [Joints]         BIGINT          NULL,
    [ID]             DECIMAL (19, 9) NULL,
    [Grade]          NVARCHAR (MAX)  NULL,
    [Description]    NVARCHAR (MAX)  NULL,
    [Collapse]       DECIMAL (19, 9) NULL,
    [Burst]          DECIMAL (19, 9) NULL,
    [Bottom_TVD]     DECIMAL (19, 9) NULL,
    [Bottom_TMD]     DECIMAL (19, 9) NULL,
    [Connection]     NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_TubingItem] PRIMARY KEY CLUSTERED ([tubingitem_id] ASC)
);

