CREATE TABLE [dbo].[UserDefinedItem_50] (
    [userdefineditem_50_id] INT            IDENTITY (1, 1) NOT NULL,
    [well_id]               BIGINT         NULL,
    [job_number]            BIGINT         NOT NULL,
    [reportTypeId]          BIGINT         NOT NULL,
    [report_Date]           DATETIME       NOT NULL,
    [line_number]           BIGINT         NOT NULL,
    [PickList_1]            NVARCHAR (MAX) NULL,
    [PickList_2]            NVARCHAR (MAX) NULL,
    [PickList_3]            NVARCHAR (MAX) NULL,
    [PickList_4]            NVARCHAR (MAX) NULL,
    [PickList_5]            NVARCHAR (MAX) NULL,
    [PickList_6]            NVARCHAR (MAX) NULL,
    [PickList_7]            NVARCHAR (MAX) NULL,
    [PickList_8]            NVARCHAR (MAX) NULL,
    [PickList_9]            NVARCHAR (MAX) NULL,
    [PickList_10]           NVARCHAR (MAX) NULL,
    [PickList_11]           NVARCHAR (MAX) NULL,
    [PickList_12]           NVARCHAR (MAX) NULL,
    [PickList_13]           NVARCHAR (MAX) NULL,
    [PickList_14]           NVARCHAR (MAX) NULL,
    [PickList_15]           NVARCHAR (MAX) NULL,
    [PickList_16]           NVARCHAR (MAX) NULL,
    [PickList_17]           NVARCHAR (MAX) NULL,
    [PickList_18]           NVARCHAR (MAX) NULL,
    [PickList_19]           NVARCHAR (MAX) NULL,
    [PickList_20]           NVARCHAR (MAX) NULL,
    [PickList_21]           NVARCHAR (MAX) NULL,
    [PickList_22]           NVARCHAR (MAX) NULL,
    [PickList_23]           NVARCHAR (MAX) NULL,
    [PickList_24]           NVARCHAR (MAX) NULL,
    [PickList_25]           NVARCHAR (MAX) NULL,
    [UserDefined_1]         NVARCHAR (MAX) NULL,
    [UserDefined_2]         NVARCHAR (MAX) NULL,
    [UserDefined_3]         NVARCHAR (MAX) NULL,
    [UserDefined_4]         NVARCHAR (MAX) NULL,
    [UserDefined_5]         NVARCHAR (MAX) NULL,
    [UserDefined_6]         NVARCHAR (MAX) NULL,
    [UserDefined_7]         NVARCHAR (MAX) NULL,
    [UserDefined_8]         NVARCHAR (MAX) NULL,
    [UserDefined_9]         NVARCHAR (MAX) NULL,
    [UserDefined_10]        NVARCHAR (MAX) NULL,
    [UserDefined_11]        NVARCHAR (MAX) NULL,
    [UserDefined_12]        NVARCHAR (MAX) NULL,
    [UserDefined_13]        NVARCHAR (MAX) NULL,
    [UserDefined_14]        NVARCHAR (MAX) NULL,
    [UserDefined_15]        NVARCHAR (MAX) NULL,
    [UserDefined_16]        NVARCHAR (MAX) NULL,
    [UserDefined_17]        NVARCHAR (MAX) NULL,
    [UserDefined_18]        NVARCHAR (MAX) NULL,
    [UserDefined_19]        NVARCHAR (MAX) NULL,
    [UserDefined_20]        NVARCHAR (MAX) NULL,
    [UserDefined_21]        NVARCHAR (MAX) NULL,
    [UserDefined_22]        NVARCHAR (MAX) NULL,
    [UserDefined_23]        NVARCHAR (MAX) NULL,
    [UserDefined_24]        NVARCHAR (MAX) NULL,
    [UserDefined_25]        NVARCHAR (MAX) NULL,
    [UserDefined_26]        NVARCHAR (MAX) NULL,
    [UserDefined_27]        NVARCHAR (MAX) NULL,
    [UserDefined_28]        NVARCHAR (MAX) NULL,
    [UserDefined_29]        NVARCHAR (MAX) NULL,
    [UserDefined_30]        NVARCHAR (MAX) NULL,
    [UserDefined_31]        NVARCHAR (MAX) NULL,
    [UserDefined_32]        NVARCHAR (MAX) NULL,
    [UserDefined_33]        NVARCHAR (MAX) NULL,
    [UserDefined_34]        NVARCHAR (MAX) NULL,
    [UserDefined_35]        NVARCHAR (MAX) NULL,
    [UserDefined_36]        NVARCHAR (MAX) NULL,
    [UserDefined_37]        NVARCHAR (MAX) NULL,
    [UserDefined_38]        NVARCHAR (MAX) NULL,
    [UserDefined_39]        NVARCHAR (MAX) NULL,
    [UserDefined_40]        NVARCHAR (MAX) NULL,
    [UserDefined_41]        NVARCHAR (MAX) NULL,
    [UserDefined_42]        NVARCHAR (MAX) NULL,
    [UserDefined_43]        NVARCHAR (MAX) NULL,
    [UserDefined_44]        NVARCHAR (MAX) NULL,
    [UserDefined_45]        NVARCHAR (MAX) NULL,
    [UserDefined_46]        NVARCHAR (MAX) NULL,
    [UserDefined_47]        NVARCHAR (MAX) NULL,
    [UserDefined_48]        NVARCHAR (MAX) NULL,
    [UserDefined_49]        NVARCHAR (MAX) NULL,
    [UserDefined_50]        NVARCHAR (MAX) NULL,
    [UserDefined_51]        NVARCHAR (MAX) NULL,
    [UserDefined_52]        NVARCHAR (MAX) NULL,
    [UserDefined_53]        NVARCHAR (MAX) NULL,
    [UserDefined_54]        NVARCHAR (MAX) NULL,
    [UserDefined_55]        NVARCHAR (MAX) NULL,
    [UserDefined_56]        NVARCHAR (MAX) NULL,
    [UserDefined_57]        NVARCHAR (MAX) NULL,
    [UserDefined_58]        NVARCHAR (MAX) NULL,
    [UserDefined_59]        NVARCHAR (MAX) NULL,
    [UserDefined_60]        NVARCHAR (MAX) NULL,
    [UserDefined_61]        NVARCHAR (MAX) NULL,
    [UserDefined_62]        NVARCHAR (MAX) NULL,
    [UserDefined_63]        NVARCHAR (MAX) NULL,
    [UserDefined_64]        NVARCHAR (MAX) NULL,
    [UserDefined_65]        NVARCHAR (MAX) NULL,
    [UserDefined_66]        NVARCHAR (MAX) NULL,
    [UserDefined_67]        NVARCHAR (MAX) NULL,
    [UserDefined_68]        NVARCHAR (MAX) NULL,
    [UserDefined_69]        NVARCHAR (MAX) NULL,
    [UserDefined_70]        NVARCHAR (MAX) NULL,
    [UserDefined_71]        NVARCHAR (MAX) NULL,
    [UserDefined_72]        NVARCHAR (MAX) NULL,
    [UserDefined_73]        NVARCHAR (MAX) NULL,
    [UserDefined_74]        NVARCHAR (MAX) NULL,
    [UserDefined_75]        NVARCHAR (MAX) NULL,
    [RowID]                 BIGINT         NOT NULL,
    [location_id]           INT            NULL,
    [CheckBox_1]            BIT            NULL,
    [CheckBox_2]            BIT            NULL,
    [CheckBox_3]            BIT            NULL,
    [CheckBox_4]            BIT            NULL,
    [CheckBox_5]            BIT            NULL,
    [CheckBox_6]            BIT            NULL,
    [CheckBox_7]            BIT            NULL,
    [CheckBox_8]            BIT            NULL,
    [CheckBox_9]            BIT            NULL,
    [CheckBox_10]           BIT            NULL,
    [UomUserDefined_1]      INT            NULL,
    [UomUserDefined_2]      INT            NULL,
    [UomUserDefined_3]      INT            NULL,
    [UomUserDefined_4]      INT            NULL,
    [UomUserDefined_5]      INT            NULL,
    [UomUserDefined_6]      INT            NULL,
    [UomUserDefined_7]      INT            NULL,
    [UomUserDefined_8]      INT            NULL,
    [UomUserDefined_9]      INT            NULL,
    [UomUserDefined_10]     INT            NULL,
    [UomUserDefined_11]     INT            NULL,
    [UomUserDefined_12]     INT            NULL,
    [UomUserDefined_13]     INT            NULL,
    [UomUserDefined_14]     INT            NULL,
    [UomUserDefined_15]     INT            NULL,
    [UomUserDefined_16]     INT            NULL,
    [UomUserDefined_17]     INT            NULL,
    [UomUserDefined_18]     INT            NULL,
    [UomUserDefined_19]     INT            NULL,
    [UomUserDefined_20]     INT            NULL,
    [UomUserDefined_21]     INT            NULL,
    [UomUserDefined_22]     INT            NULL,
    [UomUserDefined_23]     INT            NULL,
    [UomUserDefined_24]     INT            NULL,
    [UomUserDefined_25]     INT            NULL,
    [UomUserDefined_26]     INT            NULL,
    [UomUserDefined_27]     INT            NULL,
    [UomUserDefined_28]     INT            NULL,
    [UomUserDefined_29]     INT            NULL,
    [UomUserDefined_30]     INT            NULL,
    [UomUserDefined_31]     INT            NULL,
    [UomUserDefined_32]     INT            NULL,
    [UomUserDefined_33]     INT            NULL,
    [UomUserDefined_34]     INT            NULL,
    [UomUserDefined_35]     INT            NULL,
    [UomUserDefined_36]     INT            NULL,
    [UomUserDefined_37]     INT            NULL,
    [UomUserDefined_38]     INT            NULL,
    [UomUserDefined_39]     INT            NULL,
    [UomUserDefined_40]     INT            NULL,
    [UomUserDefined_41]     INT            NULL,
    [UomUserDefined_42]     INT            NULL,
    [UomUserDefined_43]     INT            NULL,
    [UomUserDefined_44]     INT            NULL,
    [UomUserDefined_45]     INT            NULL,
    [UomUserDefined_46]     INT            NULL,
    [UomUserDefined_47]     INT            NULL,
    [UomUserDefined_48]     INT            NULL,
    [UomUserDefined_49]     INT            NULL,
    [UomUserDefined_50]     INT            NULL,
    [UomUserDefined_51]     INT            NULL,
    [UomUserDefined_52]     INT            NULL,
    [UomUserDefined_53]     INT            NULL,
    [UomUserDefined_54]     INT            NULL,
    [UomUserDefined_55]     INT            NULL,
    [UomUserDefined_56]     INT            NULL,
    [UomUserDefined_57]     INT            NULL,
    [UomUserDefined_58]     INT            NULL,
    [UomUserDefined_59]     INT            NULL,
    [UomUserDefined_60]     INT            NULL,
    [UomUserDefined_61]     INT            NULL,
    [UomUserDefined_62]     INT            NULL,
    [UomUserDefined_63]     INT            NULL,
    [UomUserDefined_64]     INT            NULL,
    [UomUserDefined_65]     INT            NULL,
    [UomUserDefined_66]     INT            NULL,
    [UomUserDefined_67]     INT            NULL,
    [UomUserDefined_68]     INT            NULL,
    [UomUserDefined_69]     INT            NULL,
    [UomUserDefined_70]     INT            NULL,
    [UomUserDefined_71]     INT            NULL,
    [UomUserDefined_72]     INT            NULL,
    [UomUserDefined_73]     INT            NULL,
    [UomUserDefined_74]     INT            NULL,
    [UomUserDefined_75]     INT            NULL,
    [UomPickList_1]         INT            NULL,
    [UomPickList_2]         INT            NULL,
    [UomPickList_3]         INT            NULL,
    [UomPickList_4]         INT            NULL,
    [UomPickList_5]         INT            NULL,
    [UomPickList_6]         INT            NULL,
    [UomPickList_7]         INT            NULL,
    [UomPickList_8]         INT            NULL,
    [UomPickList_9]         INT            NULL,
    [UomPickList_10]        INT            NULL,
    [UomPickList_11]        INT            NULL,
    [UomPickList_12]        INT            NULL,
    [UomPickList_13]        INT            NULL,
    [UomPickList_14]        INT            NULL,
    [UomPickList_15]        INT            NULL,
    [UomPickList_16]        INT            NULL,
    [UomPickList_17]        INT            NULL,
    [UomPickList_18]        INT            NULL,
    [UomPickList_19]        INT            NULL,
    [UomPickList_20]        INT            NULL,
    [UomPickList_21]        INT            NULL,
    [UomPickList_22]        INT            NULL,
    [UomPickList_23]        INT            NULL,
    [UomPickList_24]        INT            NULL,
    [UomPickList_25]        INT            NULL,
    CONSTRAINT [PK_UserDefinedItem_50] PRIMARY KEY CLUSTERED ([userdefineditem_50_id] ASC)
);

