CREATE TABLE [dbo].[WellInfo] (
    [wellinfo_id]         INT            IDENTITY (1, 1) NOT NULL,
    [well_id]             BIGINT         NOT NULL,
    [rig_status]          BIGINT         NOT NULL,
    [client_id]           BIGINT         NOT NULL,
    [asset_id]            BIGINT         NOT NULL,
    [WellName]            NVARCHAR (MAX) NOT NULL,
    [UserDefined_9]       NVARCHAR (MAX) NULL,
    [UserDefined_8]       NVARCHAR (MAX) NULL,
    [UserDefined_7]       NVARCHAR (MAX) NULL,
    [UserDefined_6]       NVARCHAR (MAX) NULL,
    [UserDefined_5]       NVARCHAR (MAX) NULL,
    [UserDefined_40]      NVARCHAR (MAX) NULL,
    [UserDefined_4]       NVARCHAR (MAX) NULL,
    [UserDefined_39]      NVARCHAR (MAX) NULL,
    [UserDefined_38]      NVARCHAR (MAX) NULL,
    [UserDefined_37]      NVARCHAR (MAX) NULL,
    [UserDefined_36]      NVARCHAR (MAX) NULL,
    [UserDefined_35]      NVARCHAR (MAX) NULL,
    [UserDefined_34]      NVARCHAR (MAX) NULL,
    [UserDefined_33]      NVARCHAR (MAX) NULL,
    [UserDefined_32]      NVARCHAR (MAX) NULL,
    [UserDefined_31]      NVARCHAR (MAX) NULL,
    [UserDefined_30]      NVARCHAR (MAX) NULL,
    [UserDefined_3]       NVARCHAR (MAX) NULL,
    [UserDefined_29]      NVARCHAR (MAX) NULL,
    [UserDefined_28]      NVARCHAR (MAX) NULL,
    [UserDefined_27]      NVARCHAR (MAX) NULL,
    [UserDefined_26]      NVARCHAR (MAX) NULL,
    [UserDefined_25]      NVARCHAR (MAX) NULL,
    [UserDefined_24]      NVARCHAR (MAX) NULL,
    [UserDefined_23]      NVARCHAR (MAX) NULL,
    [UserDefined_22]      NVARCHAR (MAX) NULL,
    [UserDefined_21]      NVARCHAR (MAX) NULL,
    [UserDefined_20]      NVARCHAR (MAX) NULL,
    [UserDefined_2]       NVARCHAR (MAX) NULL,
    [UserDefined_19]      NVARCHAR (MAX) NULL,
    [UserDefined_18]      NVARCHAR (MAX) NULL,
    [UserDefined_17]      NVARCHAR (MAX) NULL,
    [UserDefined_16]      NVARCHAR (MAX) NULL,
    [UserDefined_15]      NVARCHAR (MAX) NULL,
    [UserDefined_14]      NVARCHAR (MAX) NULL,
    [UserDefined_13]      NVARCHAR (MAX) NULL,
    [UserDefined_12]      NVARCHAR (MAX) NULL,
    [UserDefined_11]      NVARCHAR (MAX) NULL,
    [UserDefined_10]      NVARCHAR (MAX) NULL,
    [UserDefined_1]       NVARCHAR (MAX) NULL,
    [Time_Zone]           NVARCHAR (MAX) NOT NULL,
    [State]               NVARCHAR (MAX) NULL,
    [SortOrder]           BIGINT         NULL,
    [LongitudeLocation]   NVARCHAR (MAX) NULL,
    [LegalSurveyLocation] NVARCHAR (MAX) NULL,
    [Lease]               NVARCHAR (MAX) NULL,
    [LatitudeLocation]    NVARCHAR (MAX) NULL,
    [Well_GUID]           NVARCHAR (MAX) NOT NULL,
    [FieldName]           NVARCHAR (MAX) NULL,
    [District]            NVARCHAR (MAX) NULL,
    [County]              NVARCHAR (MAX) NULL,
    [Country]             NVARCHAR (MAX) NULL,
    [CommonWellName]      NVARCHAR (MAX) NULL,
    [Comment]             NVARCHAR (MAX) NULL,
    [AssetName]           NVARCHAR (MAX) NOT NULL,
    [Area]                NVARCHAR (MAX) NULL,
    [APINo]               NVARCHAR (MAX) NULL,
    [location_id]         INT            NULL,
    [UomUserDefined_1]    INT            NULL,
    [UomUserDefined_2]    INT            NULL,
    [UomUserDefined_3]    INT            NULL,
    [UomUserDefined_4]    INT            NULL,
    [UomUserDefined_5]    INT            NULL,
    [UomUserDefined_6]    INT            NULL,
    [UomUserDefined_7]    INT            NULL,
    [UomUserDefined_8]    INT            NULL,
    [UomUserDefined_9]    INT            NULL,
    [UomUserDefined_10]   INT            NULL,
    [UomUserDefined_11]   INT            NULL,
    [UomUserDefined_12]   INT            NULL,
    [UomUserDefined_13]   INT            NULL,
    [UomUserDefined_14]   INT            NULL,
    [UomUserDefined_15]   INT            NULL,
    [UomUserDefined_16]   INT            NULL,
    [UomUserDefined_17]   INT            NULL,
    [UomUserDefined_18]   INT            NULL,
    [UomUserDefined_19]   INT            NULL,
    [UomUserDefined_20]   INT            NULL,
    [UomUserDefined_21]   INT            NULL,
    [UomUserDefined_22]   INT            NULL,
    [UomUserDefined_23]   INT            NULL,
    [UomUserDefined_24]   INT            NULL,
    [UomUserDefined_25]   INT            NULL,
    [UomUserDefined_26]   INT            NULL,
    [UomUserDefined_27]   INT            NULL,
    [UomUserDefined_28]   INT            NULL,
    [UomUserDefined_29]   INT            NULL,
    [UomUserDefined_30]   INT            NULL,
    [UomUserDefined_31]   INT            NULL,
    [UomUserDefined_32]   INT            NULL,
    [UomUserDefined_33]   INT            NULL,
    [UomUserDefined_34]   INT            NULL,
    [UomUserDefined_35]   INT            NULL,
    [UomUserDefined_36]   INT            NULL,
    [UomUserDefined_37]   INT            NULL,
    [UomUserDefined_38]   INT            NULL,
    [UomUserDefined_39]   INT            NULL,
    [DestLoc_Gas]         INT            NULL,
    [DestLoc_Oil]         INT            NULL,
    [DestLoc_Water]       INT            NULL,
    [DestPipe_Gas]        INT            NULL,
    [DestBatt_Oil]        INT            NULL,
    [DestBatt_Water]      INT            NULL,
    [Unit]                NVARCHAR (MAX) NULL,
    [StatePermitNo]       NVARCHAR (MAX) NULL,
    [Section]             NVARCHAR (MAX) NULL,
    [Township]            NVARCHAR (MAX) NULL,
    [Range]               NVARCHAR (MAX) NULL,
    [NetRevenueInterest]  REAL           NULL,
    CONSTRAINT [PK_WellInfo] PRIMARY KEY CLUSTERED ([wellinfo_id] ASC)
);

