CREATE TABLE [dbo].[WFEBhaRepeatable] (
    [wfebharepeatable_id]         INT             IDENTITY (1, 1) NOT NULL,
    [well_id]                     BIGINT          NOT NULL,
    [job_number]                  BIGINT          NOT NULL,
    [deleted]                     BIT             NOT NULL,
    [UomRepeatableUserDefined_9]  INT             NULL,
    [UomRepeatableUserDefined_8]  INT             NULL,
    [UomRepeatableUserDefined_7]  INT             NULL,
    [UomRepeatableUserDefined_6]  INT             NULL,
    [UomRepeatableUserDefined_5]  INT             NULL,
    [UomRepeatableUserDefined_4]  INT             NULL,
    [UomRepeatableUserDefined_3]  INT             NULL,
    [UomRepeatableUserDefined_20] INT             NULL,
    [UomRepeatableUserDefined_2]  INT             NULL,
    [UomRepeatableUserDefined_19] INT             NULL,
    [UomRepeatableUserDefined_18] INT             NULL,
    [UomRepeatableUserDefined_17] INT             NULL,
    [UomRepeatableUserDefined_16] INT             NULL,
    [UomRepeatableUserDefined_15] INT             NULL,
    [UomRepeatableUserDefined_14] INT             NULL,
    [UomRepeatableUserDefined_13] INT             NULL,
    [UomRepeatableUserDefined_12] INT             NULL,
    [UomRepeatableUserDefined_11] INT             NULL,
    [UomRepeatableUserDefined_10] INT             NULL,
    [UomRepeatableUserDefined_1]  INT             NULL,
    [UomItemWeight]               INT             NULL,
    [UomItemTop]                  INT             NULL,
    [UomItemOD]                   INT             NULL,
    [UomItemLength]               INT             NULL,
    [UomItemID]                   INT             NULL,
    [UomItemConnSize]             INT             NULL,
    [UomItemBot]                  INT             NULL,
    [ShortName]                   NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_9]     NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_8]     NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_7]     NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_6]     NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_5]     NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_4]     NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_3]     NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_20]    NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_2]     NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_19]    NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_18]    NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_17]    NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_16]    NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_15]    NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_14]    NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_13]    NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_12]    NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_11]    NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_10]    NVARCHAR (MAX)  NULL,
    [RepeatableUserDefined_1]     NVARCHAR (MAX)  NULL,
    [RepeatablePickList_9]        INT             NULL,
    [RepeatablePickList_8]        INT             NULL,
    [RepeatablePickList_7]        INT             NULL,
    [RepeatablePickList_6]        INT             NULL,
    [RepeatablePickList_5]        INT             NULL,
    [RepeatablePickList_4]        INT             NULL,
    [RepeatablePickList_3]        INT             NULL,
    [RepeatablePickList_2]        INT             NULL,
    [RepeatablePickList_10]       INT             NULL,
    [RepeatablePickList_1]        INT             NULL,
    [NoJoints]                    BIGINT          NULL,
    [Name]                        NVARCHAR (MAX)  NULL,
    [LineNumber]                  BIGINT          NOT NULL,
    [ItemWeight]                  DECIMAL (19, 9) NULL,
    [ItemTop]                     DECIMAL (19, 9) NULL,
    [ItemSerialNo]                NVARCHAR (MAX)  NULL,
    [ItemOD]                      DECIMAL (19, 9) NULL,
    [ItemNumber]                  INT             NULL,
    [ItemModel]                   NVARCHAR (MAX)  NULL,
    [ItemMaterial]                NVARCHAR (MAX)  NULL,
    [ItemMake]                    NVARCHAR (MAX)  NULL,
    [ItemLength]                  DECIMAL (19, 9) NULL,
    [ItemID]                      DECIMAL (19, 9) NULL,
    [ItemHrsUse]                  FLOAT (53)      NULL,
    [ItemDescription]             NVARCHAR (MAX)  NULL,
    [ItemConnSize]                NVARCHAR (MAX)  NULL,
    [ItemConn]                    NVARCHAR (MAX)  NULL,
    [ItemComponent]               NVARCHAR (MAX)  NULL,
    [ItemBot]                     FLOAT (53)      NULL,
    [RowID]                       BIGINT          NOT NULL,
    [reportTypeId]                BIGINT          NOT NULL,
    [BHAStringRef]                INT             NULL,
    [UomRepeatablePickList_1]     INT             NULL,
    [UomRepeatablePickList_2]     INT             NULL,
    [UomRepeatablePickList_3]     INT             NULL,
    [UomRepeatablePickList_4]     INT             NULL,
    [UomRepeatablePickList_5]     INT             NULL,
    [UomRepeatablePickList_6]     INT             NULL,
    [UomRepeatablePickList_7]     INT             NULL,
    [UomRepeatablePickList_8]     INT             NULL,
    [UomRepeatablePickList_9]     INT             NULL,
    [UomRepeatablePickList_10]    INT             NULL,
    CONSTRAINT [PK_WFEBhaRepeatable] PRIMARY KEY CLUSTERED ([wfebharepeatable_id] ASC)
);

