CREATE TABLE [dbo].[WFEDrillBitItem] (
    [wfedrillbititem_id] INT             IDENTITY (1, 1) NOT NULL,
    [RowID]              BIGINT          NOT NULL,
    [well_id]            BIGINT          NOT NULL,
    [job_number]         BIGINT          NOT NULL,
    [reportTypeId]       BIGINT          NOT NULL,
    [BitNumber]          INT             NOT NULL,
    [reportDate]         DATETIME        NOT NULL,
    [line_number]        BIGINT          NULL,
    [DepthStart]         DECIMAL (19, 9) NULL,
    [UomStartDepth]      INT             NULL,
    [DepthEnd]           DECIMAL (19, 9) NULL,
    [UomEndDepth]        INT             NULL,
    [Progress]           DECIMAL (19, 9) NULL,
    [UomProgress]        INT             NULL,
    [StartTime]          NVARCHAR (MAX)  NULL,
    [EndTime]            NVARCHAR (MAX)  NULL,
    [MotorRPM]           NVARCHAR (MAX)  NULL,
    [ROP]                DECIMAL (19, 9) NULL,
    [UomROP]             INT             NULL,
    [Pressure]           DECIMAL (19, 9) NULL,
    [UomPressure]        INT             NULL,
    [HoursOnBit]         FLOAT (53)      NULL,
    [HoursOnBitCalc]     BIT             NULL,
    [ROPCalc]            BIT             NULL,
    [ProgressCalc]       BIT             NULL,
    [WOB]                DECIMAL (19, 9) NULL,
    [UomWOB]             INT             NULL,
    [WOBHigh]            DECIMAL (19, 9) NULL,
    [UomWOBHigh]         INT             NULL,
    [WOBLow]             DECIMAL (19, 9) NULL,
    [UomWOBLow]          INT             NULL,
    [RotaryRPM]          DECIMAL (19, 9) NULL,
    [UserDefined_1]      NVARCHAR (MAX)  NULL,
    [UserDefined_2]      NVARCHAR (MAX)  NULL,
    [UserDefined_3]      NVARCHAR (MAX)  NULL,
    [UserDefined_4]      NVARCHAR (MAX)  NULL,
    [UserDefined_5]      NVARCHAR (MAX)  NULL,
    [UserDefined_6]      NVARCHAR (MAX)  NULL,
    [UserDefined_7]      NVARCHAR (MAX)  NULL,
    [UserDefined_8]      NVARCHAR (MAX)  NULL,
    [UserDefined_9]      NVARCHAR (MAX)  NULL,
    [UserDefined_10]     NVARCHAR (MAX)  NULL,
    [UserDefined_11]     NVARCHAR (MAX)  NULL,
    [UserDefined_12]     NVARCHAR (MAX)  NULL,
    [UserDefined_13]     NVARCHAR (MAX)  NULL,
    [UserDefined_14]     NVARCHAR (MAX)  NULL,
    [UserDefined_15]     NVARCHAR (MAX)  NULL,
    [UserDefined_16]     NVARCHAR (MAX)  NULL,
    [UserDefined_17]     NVARCHAR (MAX)  NULL,
    [UserDefined_18]     NVARCHAR (MAX)  NULL,
    [UserDefined_19]     NVARCHAR (MAX)  NULL,
    [UserDefined_20]     NVARCHAR (MAX)  NULL,
    [UomUserDefined_1]   INT             NULL,
    [UomUserDefined_2]   INT             NULL,
    [UomUserDefined_3]   INT             NULL,
    [UomUserDefined_4]   INT             NULL,
    [UomUserDefined_5]   INT             NULL,
    [UomUserDefined_6]   INT             NULL,
    [UomUserDefined_7]   INT             NULL,
    [UomUserDefined_8]   INT             NULL,
    [UomUserDefined_9]   INT             NULL,
    [UomUserDefined_10]  INT             NULL,
    [UomUserDefined_11]  INT             NULL,
    [UomUserDefined_12]  INT             NULL,
    [UomUserDefined_13]  INT             NULL,
    [UomUserDefined_14]  INT             NULL,
    [UomUserDefined_15]  INT             NULL,
    [UomUserDefined_16]  INT             NULL,
    [UomUserDefined_17]  INT             NULL,
    [UomUserDefined_18]  INT             NULL,
    [UomUserDefined_19]  INT             NULL,
    [UomUserDefined_20]  INT             NULL,
    [CheckBox_1]         BIT             NULL,
    [CheckBox_2]         BIT             NULL,
    [CheckBox_3]         BIT             NULL,
    [CheckBox_4]         BIT             NULL,
    [CheckBox_5]         BIT             NULL,
    [CheckBox_6]         BIT             NULL,
    [CheckBox_7]         BIT             NULL,
    [CheckBox_8]         BIT             NULL,
    [CheckBox_9]         BIT             NULL,
    [CheckBox_10]        BIT             NULL,
    [PickList_1]         NVARCHAR (MAX)  NULL,
    [PickList_2]         NVARCHAR (MAX)  NULL,
    [PickList_3]         NVARCHAR (MAX)  NULL,
    [PickList_4]         NVARCHAR (MAX)  NULL,
    [PickList_5]         NVARCHAR (MAX)  NULL,
    [PickList_6]         NVARCHAR (MAX)  NULL,
    [PickList_7]         NVARCHAR (MAX)  NULL,
    [PickList_8]         NVARCHAR (MAX)  NULL,
    [PickList_9]         NVARCHAR (MAX)  NULL,
    [PickList_10]        NVARCHAR (MAX)  NULL,
    [UomPickList_1]      INT             NULL,
    [UomPickList_2]      INT             NULL,
    [UomPickList_3]      INT             NULL,
    [UomPickList_4]      INT             NULL,
    [UomPickList_5]      INT             NULL,
    [UomPickList_6]      INT             NULL,
    [UomPickList_7]      INT             NULL,
    [UomPickList_8]      INT             NULL,
    [UomPickList_9]      INT             NULL,
    [UomPickList_10]     INT             NULL,
    CONSTRAINT [PK_WFEDrillBitItem] PRIMARY KEY CLUSTERED ([wfedrillbititem_id] ASC)
);

