CREATE TABLE [dbo].[WFEDrillBit] (
    [wfedrillbit_id]           INT             IDENTITY (1, 1) NOT NULL,
    [RowID]                    BIGINT          NOT NULL,
    [well_id]                  BIGINT          NOT NULL,
    [job_number]               BIGINT          NOT NULL,
    [reportTypeId]             BIGINT          NOT NULL,
    [Comment]                  NVARCHAR (MAX)  NULL,
    [BitNumber]                INT             NOT NULL,
    [ReRun]                    BIT             NULL,
    [Size]                     DECIMAL (19, 9) NULL,
    [UomSize]                  INT             NULL,
    [Type]                     NVARCHAR (MAX)  NULL,
    [SerialNumber]             NVARCHAR (MAX)  NULL,
    [ConnectionSize]           DECIMAL (19, 9) NULL,
    [UomConnectionSize]        INT             NULL,
    [BHANumber]                INT             NULL,
    [Jets]                     NVARCHAR (MAX)  NULL,
    [JetSize1]                 DECIMAL (19, 9) NULL,
    [JetSize2]                 DECIMAL (19, 9) NULL,
    [JetSize3]                 DECIMAL (19, 9) NULL,
    [JetSize4]                 DECIMAL (19, 9) NULL,
    [JetSize5]                 DECIMAL (19, 9) NULL,
    [JetSize6]                 DECIMAL (19, 9) NULL,
    [JetSize7]                 DECIMAL (19, 9) NULL,
    [JetSize8]                 DECIMAL (19, 9) NULL,
    [JetSize9]                 DECIMAL (19, 9) NULL,
    [JetSize10]                DECIMAL (19, 9) NULL,
    [WearBearing]              NVARCHAR (MAX)  NULL,
    [WearDull]                 NVARCHAR (MAX)  NULL,
    [WearGauge]                NVARCHAR (MAX)  NULL,
    [WearInner]                NVARCHAR (MAX)  NULL,
    [WearLocation]             NVARCHAR (MAX)  NULL,
    [WearOther]                NVARCHAR (MAX)  NULL,
    [WearOuter]                NVARCHAR (MAX)  NULL,
    [WearPulled]               NVARCHAR (MAX)  NULL,
    [WearSeal]                 NVARCHAR (MAX)  NULL,
    [WearBearingPicklist]      INT             NULL,
    [WearDullPicklist]         INT             NULL,
    [WearGaugePicklist]        INT             NULL,
    [WearInnerPicklist]        INT             NULL,
    [WearLocationPicklist]     INT             NULL,
    [WearOtherPicklist]        INT             NULL,
    [WearOuterPicklist]        INT             NULL,
    [WearPulledPicklist]       INT             NULL,
    [WearSealPicklist]         INT             NULL,
    [Manufacturer]             NVARCHAR (MAX)  NULL,
    [HHP]                      DECIMAL (19, 9) NULL,
    [VelocityDC]               NVARCHAR (MAX)  NULL,
    [VelocityDP]               NVARCHAR (MAX)  NULL,
    [TFA]                      DECIMAL (19, 9) NULL,
    [TFACalc]                  BIT             NULL,
    [BitStartDate]             DATETIME        NULL,
    [BitEndDate]               DATETIME        NULL,
    [BitStartDateCalc]         BIT             NULL,
    [BitEndDateCalc]           BIT             NULL,
    [TotalHoursOnBit]          DECIMAL (19, 9) NULL,
    [TotalHoursOnBitCalc]      BIT             NULL,
    [TotalProgress]            DECIMAL (19, 9) NULL,
    [UomTotalProgress]         INT             NULL,
    [TotalProgressCalc]        BIT             NULL,
    [TotalBitROP]              DECIMAL (19, 9) NULL,
    [UomTotalBitROP]           INT             NULL,
    [TotalBitROPCalc]          BIT             NULL,
    [UserDefined_1]            NVARCHAR (MAX)  NULL,
    [UserDefined_2]            NVARCHAR (MAX)  NULL,
    [UserDefined_3]            NVARCHAR (MAX)  NULL,
    [UserDefined_4]            NVARCHAR (MAX)  NULL,
    [UserDefined_5]            NVARCHAR (MAX)  NULL,
    [UserDefined_6]            NVARCHAR (MAX)  NULL,
    [UserDefined_7]            NVARCHAR (MAX)  NULL,
    [UserDefined_8]            NVARCHAR (MAX)  NULL,
    [UserDefined_9]            NVARCHAR (MAX)  NULL,
    [UserDefined_10]           NVARCHAR (MAX)  NULL,
    [UserDefined_11]           NVARCHAR (MAX)  NULL,
    [UserDefined_12]           NVARCHAR (MAX)  NULL,
    [UserDefined_13]           NVARCHAR (MAX)  NULL,
    [UserDefined_14]           NVARCHAR (MAX)  NULL,
    [UserDefined_15]           NVARCHAR (MAX)  NULL,
    [UserDefined_16]           NVARCHAR (MAX)  NULL,
    [UserDefined_17]           NVARCHAR (MAX)  NULL,
    [UserDefined_18]           NVARCHAR (MAX)  NULL,
    [UserDefined_19]           NVARCHAR (MAX)  NULL,
    [UserDefined_20]           NVARCHAR (MAX)  NULL,
    [UserDefined_21]           NVARCHAR (MAX)  NULL,
    [UserDefined_22]           NVARCHAR (MAX)  NULL,
    [UserDefined_23]           NVARCHAR (MAX)  NULL,
    [UserDefined_24]           NVARCHAR (MAX)  NULL,
    [UserDefined_25]           NVARCHAR (MAX)  NULL,
    [UserDefined_26]           NVARCHAR (MAX)  NULL,
    [UserDefined_27]           NVARCHAR (MAX)  NULL,
    [UserDefined_28]           NVARCHAR (MAX)  NULL,
    [UserDefined_29]           NVARCHAR (MAX)  NULL,
    [UserDefined_30]           NVARCHAR (MAX)  NULL,
    [UserDefined_31]           NVARCHAR (MAX)  NULL,
    [UserDefined_32]           NVARCHAR (MAX)  NULL,
    [UserDefined_33]           NVARCHAR (MAX)  NULL,
    [UserDefined_34]           NVARCHAR (MAX)  NULL,
    [UserDefined_35]           NVARCHAR (MAX)  NULL,
    [UserDefined_36]           NVARCHAR (MAX)  NULL,
    [UserDefined_37]           NVARCHAR (MAX)  NULL,
    [UserDefined_38]           NVARCHAR (MAX)  NULL,
    [UserDefined_39]           NVARCHAR (MAX)  NULL,
    [UserDefined_40]           NVARCHAR (MAX)  NULL,
    [UomUserDefined_1]         INT             NULL,
    [UomUserDefined_2]         INT             NULL,
    [UomUserDefined_3]         INT             NULL,
    [UomUserDefined_4]         INT             NULL,
    [UomUserDefined_5]         INT             NULL,
    [UomUserDefined_6]         INT             NULL,
    [UomUserDefined_7]         INT             NULL,
    [UomUserDefined_8]         INT             NULL,
    [UomUserDefined_9]         INT             NULL,
    [UomUserDefined_10]        INT             NULL,
    [UomUserDefined_11]        INT             NULL,
    [UomUserDefined_12]        INT             NULL,
    [UomUserDefined_13]        INT             NULL,
    [UomUserDefined_14]        INT             NULL,
    [UomUserDefined_15]        INT             NULL,
    [UomUserDefined_16]        INT             NULL,
    [UomUserDefined_17]        INT             NULL,
    [UomUserDefined_18]        INT             NULL,
    [UomUserDefined_19]        INT             NULL,
    [UomUserDefined_20]        INT             NULL,
    [UomUserDefined_21]        INT             NULL,
    [UomUserDefined_22]        INT             NULL,
    [UomUserDefined_23]        INT             NULL,
    [UomUserDefined_24]        INT             NULL,
    [UomUserDefined_25]        INT             NULL,
    [UomUserDefined_26]        INT             NULL,
    [UomUserDefined_27]        INT             NULL,
    [UomUserDefined_28]        INT             NULL,
    [UomUserDefined_29]        INT             NULL,
    [UomUserDefined_30]        INT             NULL,
    [UomUserDefined_31]        INT             NULL,
    [UomUserDefined_32]        INT             NULL,
    [UomUserDefined_33]        INT             NULL,
    [UomUserDefined_34]        INT             NULL,
    [UomUserDefined_35]        INT             NULL,
    [UomUserDefined_36]        INT             NULL,
    [UomUserDefined_37]        INT             NULL,
    [UomUserDefined_38]        INT             NULL,
    [UomUserDefined_39]        INT             NULL,
    [PickList_1]               NVARCHAR (MAX)  NULL,
    [PickList_2]               NVARCHAR (MAX)  NULL,
    [PickList_3]               NVARCHAR (MAX)  NULL,
    [PickList_4]               NVARCHAR (MAX)  NULL,
    [PickList_5]               NVARCHAR (MAX)  NULL,
    [PickList_6]               NVARCHAR (MAX)  NULL,
    [PickList_7]               NVARCHAR (MAX)  NULL,
    [PickList_8]               NVARCHAR (MAX)  NULL,
    [PickList_9]               NVARCHAR (MAX)  NULL,
    [PickList_10]              NVARCHAR (MAX)  NULL,
    [UomPickList_1]            INT             NULL,
    [UomPickList_2]            INT             NULL,
    [UomPickList_3]            INT             NULL,
    [UomPickList_4]            INT             NULL,
    [UomPickList_5]            INT             NULL,
    [UomPickList_6]            INT             NULL,
    [UomPickList_7]            INT             NULL,
    [UomPickList_8]            INT             NULL,
    [UomPickList_9]            INT             NULL,
    [UomPickList_10]           INT             NULL,
    [CheckBox_1]               BIT             NULL,
    [CheckBox_2]               BIT             NULL,
    [CheckBox_3]               BIT             NULL,
    [CheckBox_4]               BIT             NULL,
    [CheckBox_5]               BIT             NULL,
    [CheckBox_6]               BIT             NULL,
    [CheckBox_7]               BIT             NULL,
    [CheckBox_8]               BIT             NULL,
    [CheckBox_9]               BIT             NULL,
    [CheckBox_10]              BIT             NULL,
    [SummaryUserDefined_1]     NVARCHAR (MAX)  NULL,
    [SummaryUserDefined_2]     NVARCHAR (MAX)  NULL,
    [SummaryUserDefined_3]     NVARCHAR (MAX)  NULL,
    [SummaryUserDefined_4]     NVARCHAR (MAX)  NULL,
    [SummaryUserDefined_5]     NVARCHAR (MAX)  NULL,
    [SummaryUserDefined_6]     NVARCHAR (MAX)  NULL,
    [SummaryUserDefined_7]     NVARCHAR (MAX)  NULL,
    [SummaryUserDefined_8]     NVARCHAR (MAX)  NULL,
    [SummaryUserDefined_9]     NVARCHAR (MAX)  NULL,
    [SummaryUserDefined_10]    NVARCHAR (MAX)  NULL,
    [SummaryUomUserDefined_1]  INT             NULL,
    [SummaryUomUserDefined_2]  INT             NULL,
    [SummaryUomUserDefined_3]  INT             NULL,
    [SummaryUomUserDefined_4]  INT             NULL,
    [SummaryUomUserDefined_5]  INT             NULL,
    [SummaryUomUserDefined_6]  INT             NULL,
    [SummaryUomUserDefined_7]  INT             NULL,
    [SummaryUomUserDefined_8]  INT             NULL,
    [SummaryUomUserDefined_9]  INT             NULL,
    [SummaryUomUserDefined_10] INT             NULL,
    [SummaryPickList_1]        INT             NULL,
    [SummaryPickList_2]        INT             NULL,
    [SummaryPickList_3]        INT             NULL,
    [SummaryPickList_4]        INT             NULL,
    [SummaryPickList_5]        INT             NULL,
    [SummaryUomPickList_1]     INT             NULL,
    [SummaryUomPickList_2]     INT             NULL,
    [SummaryUomPickList_3]     INT             NULL,
    [SummaryUomPickList_4]     INT             NULL,
    [SummaryUomPickList_5]     INT             NULL,
    [SummaryCheckBox_1]        INT             NULL,
    [SummaryCheckBox_2]        INT             NULL,
    [SummaryCheckBox_3]        INT             NULL,
    [SummaryCheckBox_4]        INT             NULL,
    [SummaryCheckBox_5]        INT             NULL,
    CONSTRAINT [PK_WFEDrillBit] PRIMARY KEY CLUSTERED ([wfedrillbit_id] ASC)
);

