CREATE TABLE [dbo].[WFEPerforationItem] (
    [wfeperforationitem_id] INT             IDENTITY (1, 1) NOT NULL,
    [well_id]               BIGINT          NOT NULL,
    [reportTypeId]          BIGINT          NOT NULL,
    [line_number]           BIGINT          NULL,
    [Time]                  NVARCHAR (MAX)  NULL,
    [Company]               NVARCHAR (MAX)  NULL,
    [TMD_Bottom]            DECIMAL (19, 9) NULL,
    [TMD_Top]               DECIMAL (19, 9) NULL,
    [Type]                  NVARCHAR (MAX)  NULL,
    [Density]               DECIMAL (19, 9) NULL,
    [Phase]                 NVARCHAR (MAX)  NULL,
    [Gun_Size]              DECIMAL (19, 9) NULL,
    [Hole_Size]             DECIMAL (19, 9) NULL,
    [Charge_Make]           NVARCHAR (MAX)  NULL,
    [Charge_Type]           NVARCHAR (MAX)  NULL,
    [Charge_Size]           DECIMAL (19, 9) NULL,
    [Sand]                  NVARCHAR (MAX)  NULL,
    [Method]                NVARCHAR (MAX)  NULL,
    [Pressure_Initial]      DECIMAL (19, 9) NULL,
    [Pressure_Final]        DECIMAL (19, 9) NULL,
    [Fluid_Type]            NVARCHAR (MAX)  NULL,
    [Remark]                NVARCHAR (MAX)  NULL,
    [UserDefined_1]         NVARCHAR (MAX)  NULL,
    [UserDefined_2]         NVARCHAR (MAX)  NULL,
    [UserDefined_3]         NVARCHAR (MAX)  NULL,
    [UserDefined_4]         NVARCHAR (MAX)  NULL,
    [UserDefined_5]         NVARCHAR (MAX)  NULL,
    [UserDefined_6]         NVARCHAR (MAX)  NULL,
    [UserDefined_7]         NVARCHAR (MAX)  NULL,
    [UserDefined_8]         NVARCHAR (MAX)  NULL,
    [UserDefined_9]         NVARCHAR (MAX)  NULL,
    [UserDefined_10]        NVARCHAR (MAX)  NULL,
    [UserDefined_11]        NVARCHAR (MAX)  NULL,
    [UserDefined_12]        NVARCHAR (MAX)  NULL,
    [UserDefined_13]        NVARCHAR (MAX)  NULL,
    [UserDefined_14]        NVARCHAR (MAX)  NULL,
    [UserDefined_15]        NVARCHAR (MAX)  NULL,
    [UserDefined_16]        NVARCHAR (MAX)  NULL,
    [UserDefined_17]        NVARCHAR (MAX)  NULL,
    [UserDefined_18]        NVARCHAR (MAX)  NULL,
    [UserDefined_19]        NVARCHAR (MAX)  NULL,
    [UserDefined_20]        NVARCHAR (MAX)  NULL,
    [PickList_1]            NVARCHAR (MAX)  NULL,
    [PickList_2]            NVARCHAR (MAX)  NULL,
    [PickList_3]            NVARCHAR (MAX)  NULL,
    [PickList_4]            NVARCHAR (MAX)  NULL,
    [PickList_5]            NVARCHAR (MAX)  NULL,
    [PickList_6]            NVARCHAR (MAX)  NULL,
    [PickList_7]            NVARCHAR (MAX)  NULL,
    [PickList_8]            NVARCHAR (MAX)  NULL,
    [PickList_9]            NVARCHAR (MAX)  NULL,
    [PickList_10]           NVARCHAR (MAX)  NULL,
    [UserDefined_21]        NVARCHAR (MAX)  NULL,
    [UserDefined_22]        NVARCHAR (MAX)  NULL,
    [UserDefined_23]        NVARCHAR (MAX)  NULL,
    [UserDefined_24]        NVARCHAR (MAX)  NULL,
    [UserDefined_25]        NVARCHAR (MAX)  NULL,
    [UserDefined_26]        NVARCHAR (MAX)  NULL,
    [UserDefined_27]        NVARCHAR (MAX)  NULL,
    [UserDefined_28]        NVARCHAR (MAX)  NULL,
    [UserDefined_29]        NVARCHAR (MAX)  NULL,
    [UserDefined_30]        NVARCHAR (MAX)  NULL,
    [UserDefined_31]        NVARCHAR (MAX)  NULL,
    [UserDefined_32]        NVARCHAR (MAX)  NULL,
    [UserDefined_33]        NVARCHAR (MAX)  NULL,
    [UserDefined_34]        NVARCHAR (MAX)  NULL,
    [UserDefined_35]        NVARCHAR (MAX)  NULL,
    [UserDefined_36]        NVARCHAR (MAX)  NULL,
    [UserDefined_37]        NVARCHAR (MAX)  NULL,
    [UserDefined_38]        NVARCHAR (MAX)  NULL,
    [UserDefined_39]        NVARCHAR (MAX)  NULL,
    [UserDefined_40]        NVARCHAR (MAX)  NULL,
    [RowID]                 BIGINT          NOT NULL,
    [PerfDate]              DATETIME        NOT NULL,
    [Stage]                 INT             NULL,
    [UomTMD_Bottom]         INT             NULL,
    [UomTMD_Top]            INT             NULL,
    [PlugDepth]             DECIMAL (19, 9) NULL,
    [UomPlugDepth]          INT             NULL,
    [PlugType]              NVARCHAR (MAX)  NULL,
    [UomHole_Size]          INT             NULL,
    [Cluster_1]             NVARCHAR (MAX)  NULL,
    [Cluster_2]             NVARCHAR (MAX)  NULL,
    [Cluster_3]             NVARCHAR (MAX)  NULL,
    [Cluster_4]             NVARCHAR (MAX)  NULL,
    [Cluster_5]             NVARCHAR (MAX)  NULL,
    [Cluster_6]             NVARCHAR (MAX)  NULL,
    [Cluster_7]             NVARCHAR (MAX)  NULL,
    [Cluster_8]             NVARCHAR (MAX)  NULL,
    [Cluster_9]             NVARCHAR (MAX)  NULL,
    [Cluster_10]            NVARCHAR (MAX)  NULL,
    [Cluster_1_Top]         DECIMAL (19, 9) NULL,
    [UomCluster_1_Top]      INT             NULL,
    [Cluster_1_Bottom]      DECIMAL (19, 9) NULL,
    [UomCluster_1_Bottom]   INT             NULL,
    [Cluster_2_Top]         DECIMAL (19, 9) NULL,
    [UomCluster_2_Top]      INT             NULL,
    [Cluster_2_Bottom]      DECIMAL (19, 9) NULL,
    [UomCluster_2_Bottom]   INT             NULL,
    [Cluster_3_Top]         DECIMAL (19, 9) NULL,
    [UomCluster_3_Top]      INT             NULL,
    [Cluster_3_Bottom]      DECIMAL (19, 9) NULL,
    [UomCluster_3_Bottom]   INT             NULL,
    [Cluster_4_Top]         DECIMAL (19, 9) NULL,
    [UomCluster_4_Top]      INT             NULL,
    [Cluster_4_Bottom]      DECIMAL (19, 9) NULL,
    [UomCluster_4_Bottom]   INT             NULL,
    [Cluster_5_Top]         DECIMAL (19, 9) NULL,
    [UomCluster_5_Top]      INT             NULL,
    [Cluster_5_Bottom]      DECIMAL (19, 9) NULL,
    [UomCluster_5_Bottom]   INT             NULL,
    [Cluster_6_Top]         DECIMAL (19, 9) NULL,
    [UomCluster_6_Top]      INT             NULL,
    [Cluster_6_Bottom]      DECIMAL (19, 9) NULL,
    [UomCluster_6_Bottom]   INT             NULL,
    [Cluster_7_Top]         DECIMAL (19, 9) NULL,
    [UomCluster_7_Top]      INT             NULL,
    [Cluster_7_Bottom]      DECIMAL (19, 9) NULL,
    [UomCluster_7_Bottom]   INT             NULL,
    [Cluster_8_Top]         DECIMAL (19, 9) NULL,
    [UomCluster_8_Top]      INT             NULL,
    [Cluster_8_Bottom]      DECIMAL (19, 9) NULL,
    [UomCluster_8_Bottom]   INT             NULL,
    [Cluster_9_Top]         DECIMAL (19, 9) NULL,
    [UomCluster_9_Top]      INT             NULL,
    [Cluster_9_Bottom]      DECIMAL (19, 9) NULL,
    [UomCluster_9_Bottom]   INT             NULL,
    [Cluster_10_Top]        DECIMAL (19, 9) NULL,
    [UomCluster_10_Top]     INT             NULL,
    [Cluster_10_Bottom]     DECIMAL (19, 9) NULL,
    [UomCluster_10_Bottom]  INT             NULL,
    [UomPressure_Final]     INT             NULL,
    [UomPressure_Initial]   INT             NULL,
    [CheckBox_1]            BIT             NULL,
    [CheckBox_2]            BIT             NULL,
    [CheckBox_3]            BIT             NULL,
    [CheckBox_4]            BIT             NULL,
    [CheckBox_5]            BIT             NULL,
    [CheckBox_6]            BIT             NULL,
    [CheckBox_7]            BIT             NULL,
    [CheckBox_8]            BIT             NULL,
    [CheckBox_9]            BIT             NULL,
    [CheckBox_10]           BIT             NULL,
    [UomUserDefined_1]      INT             NULL,
    [UomUserDefined_2]      INT             NULL,
    [UomUserDefined_3]      INT             NULL,
    [UomUserDefined_4]      INT             NULL,
    [UomUserDefined_5]      INT             NULL,
    [UomUserDefined_6]      INT             NULL,
    [UomUserDefined_7]      INT             NULL,
    [UomUserDefined_8]      INT             NULL,
    [UomUserDefined_9]      INT             NULL,
    [UomUserDefined_10]     INT             NULL,
    [UomUserDefined_11]     INT             NULL,
    [UomUserDefined_12]     INT             NULL,
    [UomUserDefined_13]     INT             NULL,
    [UomUserDefined_14]     INT             NULL,
    [UomUserDefined_15]     INT             NULL,
    [UomUserDefined_16]     INT             NULL,
    [UomUserDefined_17]     INT             NULL,
    [UomUserDefined_18]     INT             NULL,
    [UomUserDefined_19]     INT             NULL,
    [UomUserDefined_20]     INT             NULL,
    [UomUserDefined_21]     INT             NULL,
    [UomUserDefined_22]     INT             NULL,
    [UomUserDefined_23]     INT             NULL,
    [UomUserDefined_24]     INT             NULL,
    [UomUserDefined_25]     INT             NULL,
    [UomUserDefined_26]     INT             NULL,
    [UomUserDefined_27]     INT             NULL,
    [UomUserDefined_28]     INT             NULL,
    [UomUserDefined_29]     INT             NULL,
    [UomUserDefined_30]     INT             NULL,
    [UomUserDefined_31]     INT             NULL,
    [UomUserDefined_32]     INT             NULL,
    [UomUserDefined_33]     INT             NULL,
    [UomUserDefined_34]     INT             NULL,
    [UomUserDefined_35]     INT             NULL,
    [UomUserDefined_36]     INT             NULL,
    [UomUserDefined_37]     INT             NULL,
    [UomUserDefined_38]     INT             NULL,
    [UomUserDefined_39]     INT             NULL,
    [UomUserDefined_40]     INT             NULL,
    [UomPickList_1]         INT             NULL,
    [UomPickList_2]         INT             NULL,
    [UomPickList_3]         INT             NULL,
    [UomPickList_4]         INT             NULL,
    [UomPickList_5]         INT             NULL,
    [UomPickList_6]         INT             NULL,
    [UomPickList_7]         INT             NULL,
    [UomPickList_8]         INT             NULL,
    [UomPickList_9]         INT             NULL,
    [UomPickList_10]        INT             NULL,
    [UomGun_Size]           INT             NULL,
    [UomCharge_Size]        INT             NULL,
    [UomDensity]            INT             NULL,
    CONSTRAINT [PK_WFEPerforationItem] PRIMARY KEY CLUSTERED ([wfeperforationitem_id] ASC)
);

