CREATE TABLE [dbo].[WFEWellPlanItem] (
    [wfewellplanitem_id]     INT             IDENTITY (1, 1) NOT NULL,
    [well_id]                BIGINT          NOT NULL,
    [line_number]            BIGINT          NOT NULL,
    [job_number]             BIGINT          NOT NULL,
    [Plan_User_Defined5]     NVARCHAR (MAX)  NULL,
    [Plan_User_Defined4]     NVARCHAR (MAX)  NULL,
    [Plan_User_Defined3]     NVARCHAR (MAX)  NULL,
    [Plan_User_Defined2]     NVARCHAR (MAX)  NULL,
    [Plan_User_Defined1]     NVARCHAR (MAX)  NULL,
    [Plan_TVD]               DECIMAL (19, 9) NULL,
    [Plan_TMD]               DECIMAL (19, 9) NULL,
    [Plan_PorePress]         DECIMAL (19, 9) NULL,
    [Plan_MW]                DECIMAL (19, 9) NULL,
    [Plan_FracGrad]          DECIMAL (19, 9) NULL,
    [Plan_Day]               DECIMAL (19, 9) NULL,
    [Plan_Csg_ShoeTst]       DECIMAL (19, 9) NULL,
    [Plan_Csg_OD_PickList]   NVARCHAR (MAX)  NULL,
    [Plan_Csg_Len]           DECIMAL (19, 9) NULL,
    [Plan_Csg_Desc_PickList] NVARCHAR (MAX)  NULL,
    [Plan_Cost]              DECIMAL (19, 9) NULL,
    [Plan_Comments]          NVARCHAR (MAX)  NULL,
    [RowID]                  BIGINT          NOT NULL,
    [UomTVD]                 INT             NULL,
    [UomTMD]                 INT             NULL,
    [UomMW]                  INT             NULL,
    [UomFracGrad]            INT             NULL,
    [UomCsgOD]               INT             NULL,
    [UomCsgLen]              INT             NULL,
    [UomPlan_User_Defined1]  INT             NULL,
    [UomPlan_User_Defined2]  INT             NULL,
    [UomPlan_User_Defined3]  INT             NULL,
    [UomPlan_User_Defined4]  INT             NULL,
    [UomPlan_User_Defined5]  INT             NULL,
    CONSTRAINT [PK_WFEWellPlanItem] PRIMARY KEY CLUSTERED ([wfewellplanitem_id] ASC)
);

