CREATE TABLE [dbo].[WFEWellPlan] (
    [wfewellplan_id]   INT            IDENTITY (1, 1) NOT NULL,
    [well_id]          BIGINT         NOT NULL,
    [job_number]       BIGINT         NOT NULL,
    [UserDefined_5]    NVARCHAR (MAX) NULL,
    [UserDefined_4]    NVARCHAR (MAX) NULL,
    [UserDefined_3]    NVARCHAR (MAX) NULL,
    [UserDefined_2]    NVARCHAR (MAX) NULL,
    [UserDefined_1]    NVARCHAR (MAX) NULL,
    [UomUserDefined_5] INT            NULL,
    [UomUserDefined_4] INT            NULL,
    [UomUserDefined_3] INT            NULL,
    [UomUserDefined_2] INT            NULL,
    [UomUserDefined_1] INT            NULL,
    [PickList_1]       NVARCHAR (MAX) NULL,
    [PickList_2]       NVARCHAR (MAX) NULL,
    [PickList_3]       NVARCHAR (MAX) NULL,
    [PickList_4]       NVARCHAR (MAX) NULL,
    [PickList_5]       NVARCHAR (MAX) NULL,
    [UomPickList_1]    INT            NULL,
    [UomPickList_2]    INT            NULL,
    [UomPickList_3]    INT            NULL,
    [UomPickList_4]    INT            NULL,
    [UomPickList_5]    INT            NULL,
    [CheckBox_1]       BIT            NULL,
    [CheckBox_2]       BIT            NULL,
    [CheckBox_3]       BIT            NULL,
    [CheckBox_4]       BIT            NULL,
    [CheckBox_5]       BIT            NULL,
    [Comments]         NVARCHAR (MAX) NULL,
    [RowID]            BIGINT         NOT NULL,
    CONSTRAINT [PK_WFEWellPlan] PRIMARY KEY CLUSTERED ([wfewellplan_id] ASC)
);

