CREATE TABLE [dbo].[RXT_WINDTURBINES] (
    [OBJECTID]          INT              NOT NULL,
    [NAME]              NVARCHAR (100)   NULL,
    [SUB_OPER]          NVARCHAR (150)   NULL,
    [OPERATOR]          NVARCHAR (150)   NULL,
    [OWNER]             NVARCHAR (200)   NULL,
    [TYPE]              NVARCHAR (35)    NULL,
    [STATUS]            NVARCHAR (35)    NULL,
    [DETERM]            NVARCHAR (20)    NULL,
    [SURVACCY]          NVARCHAR (2)     NULL,
    [MLTYPE]            NVARCHAR (40)    NULL,
    [MLTYPE2]           NVARCHAR (50)    NULL,
    [NRAIRPRT]          NVARCHAR (25)    NULL,
    [DIST2AIRPT]        NUMERIC (38, 8)  NULL,
    [DIR2AIRPT]         NUMERIC (38, 8)  NULL,
    [ONAIRPRT]          NVARCHAR (1)     NULL,
    [PROPDES]           NVARCHAR (254)   NULL,
    [LOCDES]            NVARCHAR (254)   NULL,
    [NOTICEOF]          NVARCHAR (15)    NULL,
    [DURATION]          NVARCHAR (10)    NULL,
    [DURDAYS]           INT              NULL,
    [DURMNTHS]          INT              NULL,
    [STARTDATE]         DATETIME2 (7)    NULL,
    [AGLDET]            NUMERIC (38, 8)  NULL,
    [AGLDNE]            NUMERIC (38, 8)  NULL,
    [AGLPROP]           NUMERIC (38, 8)  NULL,
    [ELEV]              NUMERIC (38, 8)  NULL,
    [AMSLDET]           NUMERIC (38, 8)  NULL,
    [AMSLDNE]           NUMERIC (38, 8)  NULL,
    [AMSLPROP]          NUMERIC (38, 8)  NULL,
    [FWSREGION]         NVARCHAR (30)    NULL,
    [STRCITY]           NVARCHAR (30)    NULL,
    [PREV_OWNER]        NVARCHAR (200)   NULL,
    [TRANS_DATE]        DATETIME2 (7)    NULL,
    [TRANS_NOTE]        NVARCHAR (254)   NULL,
    [TRANS_ID]          NVARCHAR (20)    NULL,
    [LOC_ID]            NVARCHAR (20)    NULL,
    [LOC_DOCS]          NVARCHAR (254)   NULL,
    [SUBOPER_ID]        NVARCHAR (20)    NULL,
    [OPER_ID]           NVARCHAR (20)    NULL,
    [OPER_URL]          NVARCHAR (254)   NULL,
    [OPER_DOCS]         NVARCHAR (254)   NULL,
    [OWNER_ID]          NVARCHAR (20)    NULL,
    [OWNER_URL]         NVARCHAR (254)   NULL,
    [OWNER_DOCS]        NVARCHAR (254)   NULL,
    [CATCHALL]          NVARCHAR (500)   NULL,
    [NOTES]             NVARCHAR (150)   NULL,
    [CNTY_NAME]         NVARCHAR (60)    NULL,
    [STATE_NAME]        NVARCHAR (40)    NULL,
    [CNTRY_NAME]        NVARCHAR (40)    NULL,
    [UPDATE_NO]         NVARCHAR (4)     NULL,
    [QUALITY]           NVARCHAR (20)    NULL,
    [Shape]             [sys].[geometry] NULL,
    [GDB_GEOMATTR_DATA] VARBINARY (MAX)  NULL,
    CONSTRAINT [R266_pk] PRIMARY KEY CLUSTERED ([OBJECTID] ASC) WITH (FILLFACTOR = 75),
    CONSTRAINT [g238_ck] CHECK ([Shape].[STSrid]=(3857))
);


GO
CREATE SPATIAL INDEX [S238_idx]
    ON [dbo].[RXT_WINDTURBINES] ([Shape])
    WITH  (
            BOUNDING_BOX = (XMAX = 20037700, XMIN = -20037700, YMAX = 30241100, YMIN = -30241100)
          );

