CREATE TABLE [dbo].[RXT_PORTS] (
    [OBJECTID]          INT              NOT NULL,
    [NAME]              NVARCHAR (100)   NULL,
    [HARBORSIZE]        NVARCHAR (12)    NULL,
    [HARBORTYPE]        NVARCHAR (20)    NULL,
    [SHELTER]           NVARCHAR (11)    NULL,
    [ENTRY_TIDE]        NVARCHAR (2)     NULL,
    [ENTRYSWELL]        NVARCHAR (2)     NULL,
    [ENTRY_ICE]         NVARCHAR (2)     NULL,
    [ENTRYOTHER]        NVARCHAR (2)     NULL,
    [OVERHD_LIM]        NVARCHAR (2)     NULL,
    [CHAN_DEPTH]        NVARCHAR (13)    NULL,
    [ANCH_DEPTH]        NVARCHAR (13)    NULL,
    [CARGODEPTH]        NVARCHAR (13)    NULL,
    [OIL_DEPTH]         NVARCHAR (13)    NULL,
    [TIDE_RANGE]        SMALLINT         NULL,
    [MAX_VESSEL]        NVARCHAR (26)    NULL,
    [HOLDGROUND]        NVARCHAR (2)     NULL,
    [TURN_BASIN]        NVARCHAR (2)     NULL,
    [PORTOFENTR]        NVARCHAR (2)     NULL,
    [US_REP]            NVARCHAR (2)     NULL,
    [ETAMESSAGE]        NVARCHAR (2)     NULL,
    [PILOT_REQD]        NVARCHAR (2)     NULL,
    [PILOTAVAIL]        NVARCHAR (2)     NULL,
    [LOC_ASSIST]        NVARCHAR (2)     NULL,
    [PILOTADVSD]        NVARCHAR (2)     NULL,
    [TUGSALVAGE]        NVARCHAR (2)     NULL,
    [TUG_ASSIST]        NVARCHAR (2)     NULL,
    [PRATIQUE]          NVARCHAR (2)     NULL,
    [SSCC_CERT]         NVARCHAR (2)     NULL,
    [QUAR_OTHER]        NVARCHAR (2)     NULL,
    [COMM_PHONE]        NVARCHAR (2)     NULL,
    [COMM_FAX]          NVARCHAR (2)     NULL,
    [COMM_RADIO]        NVARCHAR (2)     NULL,
    [COMM_VHF]          NVARCHAR (2)     NULL,
    [COMM_AIR]          NVARCHAR (2)     NULL,
    [COMM_RAIL]         NVARCHAR (2)     NULL,
    [CARGOWHARF]        NVARCHAR (2)     NULL,
    [CARGO_ANCH]        NVARCHAR (2)     NULL,
    [CARGMDMOOR]        NVARCHAR (2)     NULL,
    [CARBCHMOOR]        NVARCHAR (2)     NULL,
    [CARICEMOOR]        NVARCHAR (2)     NULL,
    [MED_FACIL]         NVARCHAR (2)     NULL,
    [GARBAGE]           NVARCHAR (2)     NULL,
    [DEGAUSS]           NVARCHAR (2)     NULL,
    [DRTYBALLST]        NVARCHAR (2)     NULL,
    [CRANEFIXED]        NVARCHAR (2)     NULL,
    [CRANEMOBIL]        NVARCHAR (2)     NULL,
    [CRANEFLOAT]        NVARCHAR (2)     NULL,
    [LIFT_100_]         NVARCHAR (2)     NULL,
    [LIFT50_100]        NVARCHAR (2)     NULL,
    [LIFT_25_49]        NVARCHAR (2)     NULL,
    [LIFT_0_24]         NVARCHAR (2)     NULL,
    [LONGSHORE]         NVARCHAR (2)     NULL,
    [ELECTRICAL]        NVARCHAR (2)     NULL,
    [SERV_STEAM]        NVARCHAR (2)     NULL,
    [NAV_EQUIP]         NVARCHAR (2)     NULL,
    [ELECREPAIR]        NVARCHAR (2)     NULL,
    [PROVISIONS]        NVARCHAR (2)     NULL,
    [WATER]             NVARCHAR (2)     NULL,
    [FUEL_OIL]          NVARCHAR (2)     NULL,
    [DIESEL]            NVARCHAR (2)     NULL,
    [DECKSUPPLY]        NVARCHAR (2)     NULL,
    [ENG_SUPPLY]        NVARCHAR (2)     NULL,
    [REPAIRCODE]        NVARCHAR (16)    NULL,
    [DRYDOCK]           NVARCHAR (15)    NULL,
    [RAILWAY]           NVARCHAR (18)    NULL,
    [EXP_CRD]           NVARCHAR (2)     NULL,
    [EXP_OTH]           NVARCHAR (2)     NULL,
    [IMP_CRD]           NVARCHAR (2)     NULL,
    [IMP_OTH]           NVARCHAR (2)     NULL,
    [CNTY_NAME]         NVARCHAR (60)    NULL,
    [STATE_NAME]        NVARCHAR (40)    NULL,
    [CNTRY_NAME]        NVARCHAR (40)    NULL,
    [Shape]             [sys].[geometry] NULL,
    [GDB_GEOMATTR_DATA] VARBINARY (MAX)  NULL,
    CONSTRAINT [R181_pk] PRIMARY KEY CLUSTERED ([OBJECTID] ASC) WITH (FILLFACTOR = 75),
    CONSTRAINT [g153_ck] CHECK ([SHAPE].[STSrid]=(3857))
);


GO
CREATE SPATIAL INDEX [S153_idx]
    ON [dbo].[RXT_PORTS] ([Shape])
    WITH  (
            BOUNDING_BOX = (XMAX = 19959583.0163, XMIN = -19662734.5047, YMAX = 12797432.1935, YMIN = 1654650.4798)
          );

