CREATE TABLE [dbo].[SDE_GEOMETRY1] (
    [GEOMETRY_ID] INT             NOT NULL,
    [CAD]         VARBINARY (MAX) NULL,
    CONSTRAINT [geom1_idx] PRIMARY KEY CLUSTERED ([GEOMETRY_ID] ASC) WITH (FILLFACTOR = 75)
);


GO
GRANT UPDATE
    ON OBJECT::[dbo].[SDE_GEOMETRY1] TO PUBLIC
    WITH GRANT OPTION
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[SDE_GEOMETRY1] TO PUBLIC
    WITH GRANT OPTION
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[SDE_GEOMETRY1] TO PUBLIC
    WITH GRANT OPTION
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[SDE_GEOMETRY1] TO PUBLIC
    WITH GRANT OPTION
    AS [dbo];

