CREATE TABLE [dbo].[BMP_TEXASWETLANDSNWI] (
    [OBJECTID]          INT              NOT NULL,
    [ATTRIBUTE]         NVARCHAR (15)    NULL,
    [WETLAND_TYPE]      NVARCHAR (50)    NULL,
    [ACRES]             NUMERIC (38, 8)  NULL,
    [GLOBALID]          UNIQUEIDENTIFIER NOT NULL,
    [Shape]             [sys].[geometry] NULL,
    [GDB_GEOMATTR_DATA] VARBINARY (MAX)  NULL,
    CONSTRAINT [R293_pk] PRIMARY KEY CLUSTERED ([OBJECTID] ASC) WITH (FILLFACTOR = 75),
    CONSTRAINT [g274_ck] CHECK ([SHAPE].[STSrid]=(3857))
);


GO
CREATE NONCLUSTERED INDEX [UUID_293]
    ON [dbo].[BMP_TEXASWETLANDSNWI]([GLOBALID] ASC) WITH (FILLFACTOR = 75);


GO
CREATE SPATIAL INDEX [S274_idx]
    ON [dbo].[BMP_TEXASWETLANDSNWI] ([Shape])
    WITH  (
            BOUNDING_BOX = (XMAX = -10408392.0085, XMIN = -11878617.2286, YMAX = 4386972.1589, YMIN = 2978888.9216),
            CELLS_PER_OBJECT = 16
          );

