CREATE TABLE [dbo].[D110] (
    [SDE_STATE_ID]       BIGINT NOT NULL,
    [SDE_DELETES_ROW_ID] INT    NOT NULL,
    [DELETED_AT]         BIGINT NOT NULL,
    CONSTRAINT [d110_pk] PRIMARY KEY CLUSTERED ([SDE_STATE_ID] ASC, [SDE_DELETES_ROW_ID] ASC, [DELETED_AT] ASC) WITH (FILLFACTOR = 75)
);


GO
CREATE NONCLUSTERED INDEX [d110_idx2]
    ON [dbo].[D110]([DELETED_AT] ASC) WITH (FILLFACTOR = 75);

