CREATE TABLE [dbo].[DI_LEGALLEASE] (
    [OBJECTID]            INT              NOT NULL,
    [latitude]            NUMERIC (38, 8)  NULL,
    [longitude]           NUMERIC (38, 8)  NULL,
    [volumePage]          NVARCHAR (33)    NOT NULL,
    [instrumentDate]      DATETIME2 (7)    NULL,
    [grantorName]         NVARCHAR (128)   NULL,
    [granteeName]         NVARCHAR (128)   NULL,
    [termMonths]          SMALLINT         NULL,
    [royalty]             NUMERIC (38, 8)  NULL,
    [APIst]               NVARCHAR (2)     NULL,
    [APIcty]              NVARCHAR (3)     NULL,
    [state]               NVARCHAR (5)     NULL,
    [countyName]          NVARCHAR (63)    NULL,
    [LeaseType]           NVARCHAR (64)    NULL,
    [recordDate]          DATETIME2 (7)    NULL,
    [effectiveDate]       DATETIME2 (7)    NULL,
    [acres]               NUMERIC (38, 8)  NULL,
    [bonus]               NUMERIC (38, 8)  NULL,
    [expirationDate]      DATETIME2 (7)    NULL,
    [isOptions]           SMALLINT         NULL,
    [extensionBonus]      NUMERIC (38, 8)  NULL,
    [extensionTermMonths] SMALLINT         NULL,
    [isBLM]               SMALLINT         NULL,
    [isState]             SMALLINT         NULL,
    [isNominated]         SMALLINT         NULL,
    [abstractNumber]      NVARCHAR (16)    NULL,
    [surveyName]          NVARCHAR (64)    NULL,
    [blockSection]        NVARCHAR (44)    NULL,
    [section]             NUMERIC (38, 8)  NULL,
    [township]            NUMERIC (38, 8)  NULL,
    [townshipDirection]   NVARCHAR (10)    NULL,
    [range]               NUMERIC (38, 8)  NULL,
    [rangeDirection]      NVARCHAR (10)    NULL,
    [granteeAlias]        NVARCHAR (50)    NULL,
    [granteeAliasShort]   NVARCHAR (7)     NULL,
    [created]             DATETIME2 (7)    NOT NULL,
    [updated]             DATETIME2 (7)    NOT NULL,
    [remarks]             NVARCHAR (3999)  NULL,
    [depthMin]            INT              NULL,
    [depthMax]            INT              NULL,
    [grantorAddress]      NVARCHAR (307)   NULL,
    [granteeAddress]      NVARCHAR (307)   NULL,
    [quarterCalls]        NVARCHAR (1000)  NULL,
    [recordNumber]        NVARCHAR (16)    NULL,
    [leaseId]             INT              NOT NULL,
    [countyId]            INT              NOT NULL,
    [stateId]             INT              NOT NULL,
    [AbstractId]          INT              NULL,
    [instrumentMonth]     INT              NULL,
    [instrumentYear]      INT              NULL,
    [expirationMonth]     INT              NULL,
    [expirationYear]      INT              NULL,
    [diLink]              NVARCHAR (1570)  NULL,
    [mappingId]           INT              NOT NULL,
    [Shape]               [sys].[geometry] NULL,
    [GDB_GEOMATTR_DATA]   VARBINARY (MAX)  NULL,
    CONSTRAINT [R490_pk] PRIMARY KEY CLUSTERED ([OBJECTID] ASC) WITH (FILLFACTOR = 75),
    CONSTRAINT [g453_ck] CHECK ([SHAPE].[STSrid]=(3857))
);


GO
CREATE SPATIAL INDEX [S453_idx]
    ON [dbo].[DI_LEGALLEASE] ([Shape])
    WITH  (
            BOUNDING_BOX = (XMAX = -8401139.5767, XMIN = -13802412.3593, YMAX = 6274520.9811, YMIN = 3018195.1371),
            CELLS_PER_OBJECT = 16
          );

