CREATE TABLE [dbo].[DI_PRODUCTION] (
    [OBJECTID]              INT              NOT NULL,
    [mappingId]             INT              NOT NULL,
    [APIst]                 NVARCHAR (2)     NULL,
    [APIcty]                NVARCHAR (3)     NULL,
    [API]                   NVARCHAR (16)    NULL,
    [state]                 NVARCHAR (2)     NOT NULL,
    [countyName]            NVARCHAR (255)   NULL,
    [stateId]               INT              NOT NULL,
    [countyId]              INT              NOT NULL,
    [pending]               NVARCHAR (1)     NOT NULL,
    [operatorName]          NVARCHAR (255)   NULL,
    [operatorAlias]         NVARCHAR (255)   NULL,
    [leaseName]             NVARCHAR (120)   NULL,
    [wellNo]                NVARCHAR (32)    NULL,
    [latitude]              NUMERIC (38, 8)  NULL,
    [longitude]             NUMERIC (38, 8)  NULL,
    [pracIPOil]             NUMERIC (38, 8)  NULL,
    [pracIPGas]             NUMERIC (38, 8)  NULL,
    [firstProd]             DATETIME2 (7)    NULL,
    [avgOil]                NUMERIC (38, 8)  NULL,
    [avgGas]                NUMERIC (38, 8)  NULL,
    [lastProd]              DATETIME2 (7)    NULL,
    [cumProdOil1932]        NUMERIC (38, 8)  NULL,
    [cumProdGas1932]        NUMERIC (38, 8)  NULL,
    [cumProdH2O1932]        NUMERIC (38, 8)  NULL,
    [field]                 NVARCHAR (120)   NULL,
    [reservoir]             NVARCHAR (120)   NULL,
    [previousOperator]      NVARCHAR (255)   NULL,
    [previousOperatorAlias] NVARCHAR (255)   NULL,
    [maxMoAvOil]            INT              NULL,
    [maxMoAvGas]            INT              NULL,
    [avgH20]                NUMERIC (38, 8)  NULL,
    [lastMoOil]             NUMERIC (38, 8)  NULL,
    [lastMoGas]             NUMERIC (38, 8)  NULL,
    [RegNo]                 NVARCHAR (32)    NULL,
    [actWellCnt]            INT              NULL,
    [OGCode]                NVARCHAR (5)     NULL,
    [GGCode]                NVARCHAR (5)     NULL,
    [prodIntTop]            NUMERIC (38, 8)  NULL,
    [prodIntBtm]            NUMERIC (38, 8)  NULL,
    [ProdIntCnt]            INT              NULL,
    [gasGravity]            NUMERIC (38, 8)  NULL,
    [oilGravity]            NUMERIC (38, 8)  NULL,
    [maxMoOil]              INT              NULL,
    [maxMoGas]              INT              NULL,
    [totalDepth]            INT              NULL,
    [tdSource]              NVARCHAR (128)   NULL,
    [priorWellTypeCode]     NVARCHAR (2)     NULL,
    [priorWellType]         NVARCHAR (50)    NULL,
    [currentWellType]       NVARCHAR (255)   NULL,
    [priorWellStatus]       NVARCHAR (100)   NULL,
    [currentWellStatus]     NVARCHAR (255)   NULL,
    [elevation]             INT              NULL,
    [elevRef]               NVARCHAR (8)     NULL,
    [isVertical]            NVARCHAR (1)     NOT NULL,
    [abstract]              NVARCHAR (16)    NULL,
    [survey]                NVARCHAR (64)    NULL,
    [sectionBlk]            NVARCHAR (44)    NULL,
    [DIId]                  INT              NULL,
    [reporter]              NVARCHAR (16)    NULL,
    [CumBOE1932]            NUMERIC (38, 8)  NULL,
    [cumOil6Mo]             NUMERIC (38, 8)  NULL,
    [cumGas6Mo]             NUMERIC (38, 8)  NULL,
    [cumOil12Mo]            NUMERIC (38, 8)  NULL,
    [cumGas12Mo]            NUMERIC (38, 8)  NULL,
    [cumOil24Mo]            NUMERIC (38, 8)  NULL,
    [cumGas24Mo]            NUMERIC (38, 8)  NULL,
    [cumOil60Mo]            NUMERIC (38, 8)  NULL,
    [cumGas60Mo]            NUMERIC (38, 8)  NULL,
    [cumBOE6Mo]             NUMERIC (38, 8)  NULL,
    [cumBOE12Mo]            NUMERIC (38, 8)  NULL,
    [cumBOE24Mo]            NUMERIC (38, 8)  NULL,
    [cumBOE60Mo]            NUMERIC (38, 8)  NULL,
    [MMCFGE6Mo]             NUMERIC (38, 8)  NULL,
    [MMCFGE12Mo]            NUMERIC (38, 8)  NULL,
    [MMCFGE24Mo]            NUMERIC (38, 8)  NULL,
    [MMCFGE60Mo]            NUMERIC (38, 8)  NULL,
    [decOil3Mo]             NUMERIC (38, 8)  NULL,
    [decGas3Mo]             NUMERIC (38, 8)  NULL,
    [decOil12Mo]            NUMERIC (38, 8)  NULL,
    [decGas12Mo]            NUMERIC (38, 8)  NULL,
    [decOil24Mo]            NUMERIC (38, 8)  NULL,
    [decGas24Mo]            NUMERIC (38, 8)  NULL,
    [decOil60Mo]            NUMERIC (38, 8)  NULL,
    [decGas60Mo]            NUMERIC (38, 8)  NULL,
    [pracIpGOR]             NUMERIC (38, 8)  NULL,
    [lastMoGOR]             NUMERIC (38, 8)  NULL,
    [pracIpCFGE]            NUMERIC (38, 8)  NULL,
    [curRatCFGE]            NUMERIC (38, 8)  NULL,
    [cumMMCFGE]             NUMERIC (38, 8)  NULL,
    [cumBCFGE]              NUMERIC (38, 8)  NULL,
    [cumGOR]                NUMERIC (38, 8)  NULL,
    [created]               DATETIME2 (7)    NOT NULL,
    [updated]               DATETIME2 (7)    NOT NULL,
    [wellId]                INT              NOT NULL,
    [maxActWells]           SMALLINT         NULL,
    [abstractId]            INT              NULL,
    [diLink]                NVARCHAR (4000)  NULL,
    [Shape]                 [sys].[geometry] NULL,
    [GDB_GEOMATTR_DATA]     VARBINARY (MAX)  NULL,
    CONSTRAINT [R522_pk] PRIMARY KEY CLUSTERED ([OBJECTID] ASC) WITH (FILLFACTOR = 75),
    CONSTRAINT [g485_ck] CHECK ([SHAPE].[STSrid]=(3857))
);


GO
CREATE SPATIAL INDEX [S485_idx]
    ON [dbo].[DI_PRODUCTION] ([Shape])
    WITH  (
            BOUNDING_BOX = (XMAX = -8395866.8175, XMIN = -18129663.8972, YMAX = 11494662.3318, YMIN = 2818699.5231),
            CELLS_PER_OBJECT = 16
          );

