CREATE TABLE [dbo].[GDB_ITEMRELATIONSHIPS] (
    [ObjectID]   INT              NOT NULL,
    [UUID]       UNIQUEIDENTIFIER NOT NULL,
    [Type]       UNIQUEIDENTIFIER NOT NULL,
    [OriginID]   UNIQUEIDENTIFIER NOT NULL,
    [DestID]     UNIQUEIDENTIFIER NOT NULL,
    [Properties] INT              NULL,
    [Attributes] XML              NULL,
    CONSTRAINT [R6_pk] PRIMARY KEY CLUSTERED ([ObjectID] ASC) WITH (FILLFACTOR = 75)
);


GO
CREATE NONCLUSTERED INDEX [GDB_ItemRel_DestID_idx]
    ON [dbo].[GDB_ITEMRELATIONSHIPS]([DestID] ASC) WITH (FILLFACTOR = 75);


GO
CREATE NONCLUSTERED INDEX [GDB_ItemRel_OriginID_idx]
    ON [dbo].[GDB_ITEMRELATIONSHIPS]([OriginID] ASC) WITH (FILLFACTOR = 75);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GDB_ItemRelationships_UUID_idx]
    ON [dbo].[GDB_ITEMRELATIONSHIPS]([UUID] ASC) WITH (FILLFACTOR = 75);


GO
CREATE NONCLUSTERED INDEX [GDB_ItemRel_Type_idx]
    ON [dbo].[GDB_ITEMRELATIONSHIPS]([Type] ASC) WITH (FILLFACTOR = 75);


GO
CREATE XML INDEX [xmlval_GDB_ITEMRELATIONSHIPS_Attributes]
    ON [dbo].[GDB_ITEMRELATIONSHIPS]([Attributes])
    USING XML INDEX [xmlprim_GDB_ITEMRELATIONSHIPS_Attributes] FOR VALUE
    WITH (PAD_INDEX = OFF);


GO
CREATE XML INDEX [xmlpath_GDB_ITEMRELATIONSHIPS_Attributes]
    ON [dbo].[GDB_ITEMRELATIONSHIPS]([Attributes])
    USING XML INDEX [xmlprim_GDB_ITEMRELATIONSHIPS_Attributes] FOR PATH
    WITH (PAD_INDEX = OFF);


GO
CREATE PRIMARY XML INDEX [xmlprim_GDB_ITEMRELATIONSHIPS_Attributes]
    ON [dbo].[GDB_ITEMRELATIONSHIPS]([Attributes])
    WITH (PAD_INDEX = OFF);


GO
CREATE TRIGGER GDB_ITEMS_REL_TR ON dbo.GDB_ITEMRELATIONSHIPS FOR INSERT, UPDATE, DELETE AS BEGIN 
SET NOCOUNT ON 
IF (SELECT COUNT(*) from inserted WHERE Type NOT IN ('8DB31AF1-DF7C-4632-AA10-3CC44B0C6914', 'CC28387C-441F-4D7C-A802-41A160317FE0','79CC71C8-B7D9-4141-9014-B6373E236ABB', 'D022DE33-45BD-424C-88BF-5B1B6B957BD3')) > 0 OR 
(SELECT COUNT(*) from deleted WHERE Type NOT IN ('8DB31AF1-DF7C-4632-AA10-3CC44B0C6914', 'CC28387C-441F-4D7C-A802-41A160317FE0','79CC71C8-B7D9-4141-9014-B6373E236ABB', 'D022DE33-45BD-424C-88BF-5B1B6B957BD3')) > 0
BEGIN 
UPDATE dbo.GDB_TABLES_LAST_MODIFIED SET last_modified_count = last_modified_count + 1 WHERE table_name = 'GDB_ITEMRELATIONSHIPS' IF @@ROWCOUNT = 0 
BEGIN 
INSERT INTO dbo.GDB_TABLES_LAST_MODIFIED VALUES ('GDB_ITEMRELATIONSHIPS', 1) 
END 
END END
GO
GRANT UPDATE
    ON OBJECT::[dbo].[GDB_ITEMRELATIONSHIPS] TO PUBLIC
    WITH GRANT OPTION
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[GDB_ITEMRELATIONSHIPS] TO PUBLIC
    WITH GRANT OPTION
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[GDB_ITEMRELATIONSHIPS] TO PUBLIC
    WITH GRANT OPTION
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[GDB_ITEMRELATIONSHIPS] TO PUBLIC
    WITH GRANT OPTION
    AS [dbo];

