CREATE TABLE [dbo].[RIGS_DRILLINGINFO_05102018] (
    [OBJECTID]          INT              NOT NULL,
    [rig_id]            INT              NULL,
    [api_10]            NVARCHAR (254)   NULL,
    [ofs_reg]           NVARCHAR (254)   NULL,
    [state]             NVARCHAR (254)   NULL,
    [district]          NVARCHAR (254)   NULL,
    [county]            NVARCHAR (254)   NULL,
    [offshr]            NVARCHAR (254)   NULL,
    [c_name]            NVARCHAR (254)   NULL,
    [rig_name]          NVARCHAR (254)   NULL,
    [draw_wrk]          NVARCHAR (254)   NULL,
    [rate_hp]           INT              NULL,
    [wtr_dpth]          INT              NULL,
    [power]             NVARCHAR (254)   NULL,
    [mobility]          NVARCHAR (254)   NULL,
    [o_name]            NVARCHAR (254)   NULL,
    [lease_nm]          NVARCHAR (254)   NULL,
    [well_no]           NVARCHAR (254)   NULL,
    [spud_dt]           DATETIME2 (7)    NULL,
    [rig_lat]           NUMERIC (38, 8)  NULL,
    [rig_lon]           NUMERIC (38, 8)  NULL,
    [permt_no]          NVARCHAR (254)   NULL,
    [p_apvl_d]          DATETIME2 (7)    NULL,
    [p_pstd_d]          DATETIME2 (7)    NULL,
    [p_depth]           INT              NULL,
    [p_type]            NVARCHAR (254)   NULL,
    [well_typ]          NVARCHAR (254)   NULL,
    [drill_tp]          NVARCHAR (254)   NULL,
    [field]             NVARCHAR (254)   NULL,
    [frmtion]           NVARCHAR (254)   NULL,
    [frmtn_dp]          INT              NULL,
    [section]           NUMERIC (38, 8)  NULL,
    [township]          NVARCHAR (254)   NULL,
    [range]             NVARCHAR (254)   NULL,
    [block]             NVARCHAR (254)   NULL,
    [survey]            NVARCHAR (254)   NULL,
    [abstract]          INT              NULL,
    [h2s_area]          NVARCHAR (254)   NULL,
    [c_cntct]           NVARCHAR (254)   NULL,
    [c_phone]           NVARCHAR (254)   NULL,
    [c_email]           NVARCHAR (254)   NULL,
    [c_adrs]            NVARCHAR (254)   NULL,
    [c_city]            NVARCHAR (254)   NULL,
    [c_state]           NVARCHAR (254)   NULL,
    [c_zip]             NVARCHAR (254)   NULL,
    [c_site]            NVARCHAR (254)   NULL,
    [o_cntct]           NVARCHAR (254)   NULL,
    [o_phone]           NVARCHAR (254)   NULL,
    [o_adrs]            NVARCHAR (254)   NULL,
    [o_city]            NVARCHAR (254)   NULL,
    [o_state]           NVARCHAR (254)   NULL,
    [o_zip]             NVARCHAR (254)   NULL,
    [tmp_loc]           NVARCHAR (254)   NULL,
    [dir_loc]           NVARCHAR (254)   NULL,
    [Shape]             [sys].[geometry] NULL,
    [GDB_GEOMATTR_DATA] VARBINARY (MAX)  NULL,
    CONSTRAINT [R47_pk] PRIMARY KEY CLUSTERED ([OBJECTID] ASC) WITH (FILLFACTOR = 75),
    CONSTRAINT [g37_ck] CHECK ([Shape].[STSrid]=(3857))
);


GO
CREATE SPATIAL INDEX [S37_idx]
    ON [dbo].[RIGS_DRILLINGINFO_05102018] ([Shape])
    WITH  (
            BOUNDING_BOX = (XMAX = 20037700, XMIN = -20037700, YMAX = 30241100, YMIN = -30241100),
            CELLS_PER_OBJECT = 16
          );

