CREATE TABLE [dbo].[RXT_OGWELLS_2018_JOINS_JUL3] (
    [OBJECTID]                  INT              NOT NULL,
    [API_UNQSEQ]                NVARCHAR (25)    NULL,
    [API_NATFMT]                NVARCHAR (25)    NULL,
    [API_HRTSTD]                NVARCHAR (25)    NULL,
    [WELLNAME]                  NVARCHAR (150)   NULL,
    [OPERATOR]                  NVARCHAR (100)   NULL,
    [OWNER]                     NVARCHAR (150)   NULL,
    [PREV_OPER]                 NVARCHAR (100)   NULL,
    [COMMODITY]                 NVARCHAR (15)    NULL,
    [COMM_STATE]                NVARCHAR (25)    NULL,
    [OPER_STAT]                 NVARCHAR (15)    NULL,
    [STAT_STATE]                NVARCHAR (150)   NULL,
    [WELLDIRECT]                NVARCHAR (15)    NULL,
    [BH_Y_NAD83]                NUMERIC (38, 8)  NULL,
    [BH_X_NAD83]                NUMERIC (38, 8)  NULL,
    [COUNTY]                    NVARCHAR (20)    NULL,
    [STATE_NAME]                NVARCHAR (25)    NULL,
    [COUNTRY]                   NVARCHAR (50)    NULL,
    [API_COUNTY]                NVARCHAR (3)     NULL,
    [API_STATE]                 NVARCHAR (2)     NULL,
    [FIPS_STATE]                NVARCHAR (2)     NULL,
    [UPDATE_NO]                 INT              NULL,
    [OBJECTID_1]                INT              NULL,
    [STATE_ABBR]                NVARCHAR (2)     NULL,
    [API_HRTSTD_1]              NVARCHAR (25)    NULL,
    [LEASENUM]                  NVARCHAR (25)    NULL,
    [LEASENAME]                 NVARCHAR (250)   NULL,
    [PERMITNUM]                 NVARCHAR (25)    NULL,
    [PERMITDATE]                DATETIME2 (7)    NULL,
    [SPUDDATE]                  DATETIME2 (7)    NULL,
    [COMPLDATE]                 DATETIME2 (7)    NULL,
    [PROD_DATE]                 DATETIME2 (7)    NULL,
    [PLUGDATE]                  DATETIME2 (7)    NULL,
    [DEPTHPROP]                 INT              NULL,
    [TD_FT]                     INT              NULL,
    [TVD_FT]                    INT              NULL,
    [TMD_FT]                    INT              NULL,
    [PBTD_FT]                   INT              NULL,
    [ELEV_FT]                   INT              NULL,
    [ELEV_REF]                  NVARCHAR (2)     NULL,
    [FORMATIONS]                NVARCHAR (250)   NULL,
    [FIELDS]                    NVARCHAR (250)   NULL,
    [SECTIONNUM]                NVARCHAR (10)    NULL,
    [TOWNSHIP]                  NVARCHAR (10)    NULL,
    [WELLRANGE]                 NVARCHAR (10)    NULL,
    [UPDATE_NO_1]               INT              NULL,
    [OBJECTID_12]               INT              NULL,
    [API_HRTSTD_12]             NVARCHAR (25)    NULL,
    [O_2014_BBL]                NUMERIC (38, 8)  NULL,
    [G_2014_MCF]                NUMERIC (38, 8)  NULL,
    [BOE_2014]                  NUMERIC (38, 8)  NULL,
    [PRODMONTHS]                INT              NULL,
    [UPDATE_NO_12]              INT              NULL,
    [OBJECTID_12_13]            INT              NULL,
    [API_HRTSTD_12_13]          NVARCHAR (25)    NULL,
    [O_2015_BBL]                NUMERIC (38, 8)  NULL,
    [G_2015_MCF]                NUMERIC (38, 8)  NULL,
    [BOE_2015]                  NUMERIC (38, 8)  NULL,
    [PRODMONTHS_1]              INT              NULL,
    [UPDATE_NO_12_13]           INT              NULL,
    [OBJECTID_12_13_14]         INT              NULL,
    [API_HRTSTD_12_13_14]       NVARCHAR (25)    NULL,
    [O_2016_BBL]                NUMERIC (38, 8)  NULL,
    [G_2016_MCF]                NUMERIC (38, 8)  NULL,
    [BOE_2016]                  NUMERIC (38, 8)  NULL,
    [PRODMONTHS_12]             INT              NULL,
    [UPDATE_NO_12_13_14]        INT              NULL,
    [OBJECTID_12_13_14_15]      INT              NULL,
    [API_HRTSTD_12_13_14_15]    NVARCHAR (25)    NULL,
    [O_2017_BBL]                NUMERIC (38, 8)  NULL,
    [G_2017_MCF]                NUMERIC (38, 8)  NULL,
    [BOE_2017]                  NUMERIC (38, 8)  NULL,
    [PRODMONTHS_12_13]          INT              NULL,
    [UPDATE_NO_12_13_14_15]     INT              NULL,
    [OBJECTID_12_13_14_15_16]   INT              NULL,
    [API_HRTSTD_12_13_14_15_16] NVARCHAR (25)    NULL,
    [O_2018_BBL]                NUMERIC (38, 8)  NULL,
    [G_2018_MCF]                NUMERIC (38, 8)  NULL,
    [BOE_2018]                  NUMERIC (38, 8)  NULL,
    [PRODMONTHS_12_13_14]       INT              NULL,
    [UPDATE_NO_12_13_14_15_16]  INT              NULL,
    [Shape]                     [sys].[geometry] NULL,
    [GDB_GEOMATTR_DATA]         VARBINARY (MAX)  NULL,
    CONSTRAINT [R109_pk] PRIMARY KEY CLUSTERED ([OBJECTID] ASC) WITH (FILLFACTOR = 75),
    CONSTRAINT [g99_ck] CHECK ([SHAPE].[STSrid]=(3857))
);


GO
CREATE SPATIAL INDEX [S99_idx]
    ON [dbo].[RXT_OGWELLS_2018_JOINS_JUL3] ([Shape])
    WITH  (
            BOUNDING_BOX = (XMAX = 11233541.1391, XMIN = -19847421.3603, YMAX = 11700762.0577, YMIN = 394155.2137),
            CELLS_PER_OBJECT = 16
          );

