CREATE TABLE [dbo].[RXT_CONTACTS] (
    [OBJECTID]    INT             NOT NULL,
    [ENTITY_ID]   NVARCHAR (7)    NULL,
    [LOC_ID]      NVARCHAR (7)    NULL,
    [ENTITY]      NVARCHAR (200)  NULL,
    [G_CONTACT]   NVARCHAR (200)  NULL,
    [G_TITLE]     NVARCHAR (200)  NULL,
    [G_ADDRESS]   NVARCHAR (200)  NULL,
    [G_PHONE]     NVARCHAR (200)  NULL,
    [G_FAX]       NVARCHAR (50)   NULL,
    [G_EMAIL]     NVARCHAR (200)  NULL,
    [E_CONTACT]   NVARCHAR (200)  NULL,
    [E_TITLE]     NVARCHAR (200)  NULL,
    [E_PHONE]     NVARCHAR (16)   NULL,
    [E_EMAIL]     NVARCHAR (200)  NULL,
    [E_ADDRESS]   NVARCHAR (200)  NULL,
    [OPERID_NPM]  NUMERIC (38, 8) NULL,
    [CONT_TITLE]  NVARCHAR (84)   NULL,
    [EM_PH_EML1]  NVARCHAR (72)   NULL,
    [GEN_CONTAC]  NVARCHAR (68)   NULL,
    [GEN_PHN_EM]  NVARCHAR (99)   NULL,
    [OPER_NM]     NVARCHAR (72)   NULL,
    [REX_JOIN]    SMALLINT        NULL,
    [OPER_ID]     INT             NULL,
    [CONT_ID]     INT             NULL,
    [SOURCE]      NVARCHAR (100)  NULL,
    [URL]         NVARCHAR (300)  NULL,
    [DONE]        NVARCHAR (1)    NULL,
    [ENTITY_TYP]  NVARCHAR (8)    NULL,
    [NOTES]       NVARCHAR (200)  NULL,
    [EIT_ID_LONG] INT             NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [R342_SDE_ROWID_UK]
    ON [dbo].[RXT_CONTACTS]([OBJECTID] ASC) WITH (FILLFACTOR = 75);

