CREATE TABLE [dbo].[RXT_NG_METER_POINTS] (
    [OBJECTID]          INT              NOT NULL,
    [PNTRID]            NVARCHAR (40)    NULL,
    [PNTDRN]            NVARCHAR (100)   NULL,
    [PNTPROPLOC]        NVARCHAR (100)   NULL,
    [PNTFERC]           NVARCHAR (5)     NULL,
    [PNTPLNAME]         NVARCHAR (80)    NULL,
    [PNTLOCNAME]        NVARCHAR (200)   NULL,
    [PNTSTDTYPE]        NVARCHAR (2)     NULL,
    [DESIGNCAP]         NUMERIC (38, 8)  NULL,
    [AVG2008OLD]        NUMERIC (38, 8)  NULL,
    [AVG2008NET]        NUMERIC (38, 8)  NULL,
    [AVG2008ABS]        NUMERIC (38, 8)  NULL,
    [AVG2009NET]        NUMERIC (38, 8)  NULL,
    [AVG2009ABS]        NUMERIC (38, 8)  NULL,
    [AVG2010NET]        NUMERIC (38, 8)  NULL,
    [AVG2010ABS]        NUMERIC (38, 8)  NULL,
    [AVG2011NET]        NUMERIC (38, 8)  NULL,
    [AVG2011ABS]        NUMERIC (38, 8)  NULL,
    [AVG2012NET]        NUMERIC (38, 8)  NULL,
    [AVG2012ABS]        NUMERIC (38, 8)  NULL,
    [AVG2013NET]        NUMERIC (38, 8)  NULL,
    [AVG2013ABS]        NUMERIC (38, 8)  NULL,
    [AVG2014NET]        NUMERIC (38, 8)  NULL,
    [AVG2014ABS]        NUMERIC (38, 8)  NULL,
    [AVG2015NET]        NUMERIC (38, 8)  NULL,
    [AVG2015ABS]        NUMERIC (38, 8)  NULL,
    [AVG2016NET]        NUMERIC (38, 8)  NULL,
    [AVG2016ABS]        NUMERIC (38, 8)  NULL,
    [AVG2017NET]        NUMERIC (38, 8)  NULL,
    [AVG2017ABS]        NUMERIC (38, 8)  NULL,
    [STATE]             NVARCHAR (35)    NULL,
    [COUNTRY]           NVARCHAR (254)   NULL,
    [UPDATE_NO]         NVARCHAR (254)   NULL,
    [RQCHECK]           NUMERIC (38, 8)  NULL,
    [Shape]             [sys].[geometry] NULL,
    [GDB_GEOMATTR_DATA] VARBINARY (MAX)  NULL,
    CONSTRAINT [R160_pk] PRIMARY KEY CLUSTERED ([OBJECTID] ASC) WITH (FILLFACTOR = 75),
    CONSTRAINT [g141_ck] CHECK ([SHAPE].[STSrid]=(3857))
);


GO
CREATE NONCLUSTERED INDEX [I551PNTLOCNAME]
    ON [dbo].[RXT_NG_METER_POINTS]([PNTLOCNAME] ASC) WITH (FILLFACTOR = 75);


GO
CREATE NONCLUSTERED INDEX [I551PNTPLNAME]
    ON [dbo].[RXT_NG_METER_POINTS]([PNTPLNAME] ASC) WITH (FILLFACTOR = 75);


GO
CREATE SPATIAL INDEX [S141_idx]
    ON [dbo].[RXT_NG_METER_POINTS] ([Shape])
    WITH  (
            BOUNDING_BOX = (XMAX = 0, XMIN = -13820423.8751, YMAX = 6275273.7242, YMIN = 0),
            CELLS_PER_OBJECT = 16
          );

