CREATE TABLE [dbo].[BusinessEntityTb] (
    [MerrickID]                   INT          NOT NULL,
    [CompanyID]                   VARCHAR (20) NULL,
    [CompanyName]                 VARCHAR (60) NULL,
    [CompanyNameShort]            VARCHAR (16) NULL,
    [Description]                 VARCHAR (60) NULL,
    [ActiveFlag]                  INT          NULL,
    [StartActiveDate]             DATETIME     NULL,
    [EndActiveDate]               DATETIME     NULL,
    [GathererFlag]                INT          NULL,
    [EquipmentCompanyFlag]        INT          NULL,
    [OperatorFlag]                INT          NULL,
    [RegulatoryAgencyFlag]        INT          NULL,
    [HaulerFlag]                  INT          NULL,
    [TransporterFlag]             INT          NULL,
    [IntegratorFlag]              INT          NULL,
    [PurchaserFlag]               INT          NULL,
    [OwnerFlag]                   INT          NULL,
    [PartnerFlag]                 INT          NULL,
    [AccountNumber1]              VARCHAR (14) NULL,
    [AccountNumber2]              VARCHAR (14) NULL,
    [AssociateID]                 VARCHAR (14) NULL,
    [RoleID]                      VARCHAR (14) NULL,
    [AccountingID]                VARCHAR (30) NULL,
    [ProductionID]                VARCHAR (30) NULL,
    [EngineeringID]               VARCHAR (30) NULL,
    [AccountingTeamID]            INT          NULL,
    [DrillingTeamID]              INT          NULL,
    [ProductionTeamID]            INT          NULL,
    [GroupID]                     INT          NULL,
    [DivisionID]                  INT          NULL,
    [FieldGroupID]                INT          NULL,
    [AreaID]                      INT          NULL,
    [SendProductionReportFlag]    INT          NULL,
    [UtahStateCode]               VARCHAR (10) NULL,
    [MichiganStateCode]           VARCHAR (10) NULL,
    [AlaskaStateCode]             VARCHAR (10) NULL,
    [FederalID]                   VARCHAR (16) NULL,
    [TexasP5Number]               INT          NULL,
    [LouisianaCompanyID]          VARCHAR (50) NULL,
    [NewMexicoOGRID]              VARCHAR (10) NULL,
    [WyomingStateCode]            INT          NULL,
    [CaliforniaStateCode]         VARCHAR (10) NULL,
    [ColoradoStateCode]           VARCHAR (10) NULL,
    [SouthDakotaStateCode]        VARCHAR (10) NULL,
    [MississippiStateCode]        VARCHAR (10) NULL,
    [ArkansasStateCode]           VARCHAR (20) NULL,
    [NorthDakotaStateCode]        VARCHAR (10) NULL,
    [MontanaStateCode]            VARCHAR (20) NULL,
    [AlabamaStateCode]            VARCHAR (10) NULL,
    [MerrickRegulatoryAgencyFlag] INT          NULL,
    [PrintFlag]                   INT          NULL,
    [DeleteFlag]                  INT          NULL,
    [DateTimeStamp]               DATETIME     NULL,
    [BLogicDateStamp]             DATETIME     NULL,
    [BLogicTimeStamp]             CHAR (8)     NULL,
    [UserDateStamp]               DATETIME     NULL,
    [UserTimeStamp]               CHAR (8)     NULL,
    [UserID]                      INT          NULL,
    [AccountingShortName]         VARCHAR (30) NULL,
    [DataSourceCode]              INT          NULL,
    CONSTRAINT [PK_BusinessEntityTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC)
);

