CREATE TABLE [dbo].[CompletionDailyDispTb] (
    [MerrickID]              INT          NOT NULL,
    [RecordDate]             DATETIME     NOT NULL,
    [SourceID]               INT          NOT NULL,
    [SourceType]             INT          NOT NULL,
    [RunTicketNumber]        VARCHAR (22) NOT NULL,
    [RunTicketDate]          DATETIME     NULL,
    [RunTicketFlag]          INT          NULL,
    [SequenceNumber]         INT          NULL,
    [ProductCode]            INT          NULL,
    [ProductType]            INT          NULL,
    [DispositionCode]        INT          NULL,
    [OverwriteFlag]          INT          NULL,
    [GatheringSystemID]      FLOAT (53)   NULL,
    [AllocEstBTUFactor]      FLOAT (53)   NULL,
    [AllocEstTemperature]    FLOAT (53)   NULL,
    [AllocEstPressureBase]   FLOAT (53)   NULL,
    [AllocEstGravity]        FLOAT (53)   NULL,
    [AllocEstWetDryFlag]     INT          NULL,
    [AllocEstOilVol]         FLOAT (53)   NULL,
    [AllocEstWaterVol]       FLOAT (53)   NULL,
    [AllocEstGasVolMCF]      FLOAT (53)   NULL,
    [AllocEstGasVolMMBTU]    FLOAT (53)   NULL,
    [AllocEstCO2Vol]         FLOAT (53)   NULL,
    [AllocEstOtherVol]       FLOAT (53)   NULL,
    [AllocEstPlantGasMCF]    FLOAT (53)   NULL,
    [AllocEstPlantGasMMBTU]  FLOAT (53)   NULL,
    [AllocEstInjOilVol]      FLOAT (53)   NULL,
    [AllocEstInjWaterVol]    FLOAT (53)   NULL,
    [AllocEstInjGasVolMCF]   FLOAT (53)   NULL,
    [AllocEstInjGasVolMMBTU] FLOAT (53)   NULL,
    [AllocEstInjCO2Vol]      FLOAT (53)   NULL,
    [AllocEstInjOtherVol]    FLOAT (53)   NULL,
    [AllocEstNGLVol]         FLOAT (53)   NULL,
    [AllocEstSulfurMass]     FLOAT (53)   NULL,
    [DateTimeStamp]          DATETIME     NULL,
    [AllocationDateStamp]    DATETIME     NULL,
    [AllocationTimeStamp]    CHAR (8)     NULL,
    [UserDateStamp]          DATETIME     NULL,
    [UserTimeStamp]          CHAR (8)     NULL,
    [UserID]                 INT          NULL,
    [AllocEstMass]           FLOAT (53)   NOT NULL,
    [ProcessedFlag]          CHAR (1)     NULL,
    CONSTRAINT [PK_CompletionDailyDispTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC, [RecordDate] ASC, [SourceID] ASC, [SourceType] ASC, [RunTicketNumber] ASC)
);

