CREATE TABLE [dbo].[CompletionMonthlyTb] (
    [MerrickID]                  INT              NOT NULL,
    [RecordDate]                 DATETIME         NOT NULL,
    [StartDate]                  DATETIME         NULL,
    [EndDate]                    DATETIME         NULL,
    [OperatorEntityID]           INT              NULL,
    [OperatorEntityLoc]          INT              NULL,
    [OutsideOperatedFlag]        INT              NULL,
    [OperatorEffectiveDate]      DATETIME         NULL,
    [ProducingStatus]            INT              NULL,
    [ProducingMethod]            INT              NULL,
    [ProductCodeGas]             INT              NULL,
    [ProductCodeOil]             INT              NULL,
    [ProductCodeWater]           INT              NULL,
    [ProductType]                INT              NULL,
    [DataSourceCode]             INT              NULL,
    [DataPopulationFlag]         INT              NULL,
    [LoadFluidRecoveryFlag]      INT              NULL,
    [TotalDownTime]              FLOAT (53)       NULL,
    [DaysOn]                     FLOAT (53)       NULL,
    [TotalHoursFlowed]           FLOAT (53)       NULL,
    [DaysInjected]               FLOAT (53)       NULL,
    [TotalHoursInjected]         FLOAT (53)       NULL,
    [DaysIdle]                   FLOAT (53)       NULL,
    [TotalHoursIdle]             FLOAT (53)       NULL,
    [TotalHoursRecovery]         FLOAT (53)       NULL,
    [AllocActBTUFactor]          FLOAT (53)       NULL,
    [AllocActTemperature]        FLOAT (53)       NULL,
    [AllocActPressureBase]       FLOAT (53)       NULL,
    [AllocActGravity]            FLOAT (53)       NULL,
    [AllocActWetDryFlag]         INT              NULL,
    [AllocActOilVol]             FLOAT (53)       NULL,
    [AllocActWaterVol]           FLOAT (53)       NULL,
    [AllocActGasVolMCF]          FLOAT (53)       NULL,
    [AllocActGasVolMMBTU]        FLOAT (53)       NULL,
    [AllocActCO2Vol]             FLOAT (53)       NULL,
    [AllocActCO2Mass]            FLOAT (53)       NULL,
    [AllocActOtherVol]           FLOAT (53)       NULL,
    [AllocActPlantGasMCF]        FLOAT (53)       NULL,
    [AllocActPlantGasMMBTU]      FLOAT (53)       NULL,
    [AllocActInjOilVol]          FLOAT (53)       NULL,
    [AllocActInjWaterVol]        FLOAT (53)       NULL,
    [AllocActInjGasVolMCF]       FLOAT (53)       NULL,
    [AllocActInjGasVolMMBTU]     FLOAT (53)       NULL,
    [AllocActInjCO2Vol]          FLOAT (53)       NULL,
    [AllocActInjOtherVol]        FLOAT (53)       NULL,
    [AllocActNGLVol]             FLOAT (53)       NULL,
    [AllocActSulfurMass]         FLOAT (53)       NULL,
    [BeginningOil]               FLOAT (53)       NULL,
    [EndingOil]                  FLOAT (53)       NULL,
    [OilProduction]              FLOAT (53)       NULL,
    [TankCompDispOil]            FLOAT (53)       NULL,
    [BeginningWater]             FLOAT (53)       NULL,
    [EndingWater]                FLOAT (53)       NULL,
    [WaterProduction]            FLOAT (53)       NULL,
    [TankCompDispWater]          FLOAT (53)       NULL,
    [GasOilRatio]                FLOAT (53)       NULL,
    [AllocActSalesGasVolMCF]     FLOAT (53)       NULL,
    [AllocActRecoveryOilVol]     FLOAT (53)       NULL,
    [AllocActRecoveryWaterVol]   FLOAT (53)       NULL,
    [AllocActRecoveryGasVol]     FLOAT (53)       NULL,
    [AllocActNetOilVol]          FLOAT (53)       NULL,
    [AllocActNetWaterVol]        FLOAT (53)       NULL,
    [AllocActNetGasVol]          FLOAT (53)       NULL,
    [GasBeginningInjInv]         FLOAT (53)       NULL,
    [GasEndingInjInv]            FLOAT (53)       NULL,
    [OilBeginningInjInv]         FLOAT (53)       NULL,
    [OilEndingInjInv]            FLOAT (53)       NULL,
    [WaterBeginningInjInv]       FLOAT (53)       NULL,
    [WaterEndingInjInv]          FLOAT (53)       NULL,
    [OtherBeginningInjInv]       FLOAT (53)       NULL,
    [OtherEndingInjInv]          FLOAT (53)       NULL,
    [OtherInjectionType]         INT              NULL,
    [CumulativeGas]              FLOAT (53)       NULL,
    [CumulativeOil]              FLOAT (53)       NULL,
    [CumulativeWater]            FLOAT (53)       NULL,
    [CumulativeInjGas]           FLOAT (53)       NULL,
    [CumulativeInjOil]           FLOAT (53)       NULL,
    [CumulativeInjWater]         FLOAT (53)       NULL,
    [ReservesGas]                FLOAT (53)       NULL,
    [ReservesOil]                FLOAT (53)       NULL,
    [ReservesWater]              FLOAT (53)       NULL,
    [EstBTUFactor]               FLOAT (53)       NULL,
    [EstTemperature]             FLOAT (53)       NULL,
    [EstPressureBase]            FLOAT (53)       NULL,
    [EstGravity]                 FLOAT (53)       NULL,
    [EstWetDryFlag]              INT              NULL,
    [EstOilVol]                  FLOAT (53)       NULL,
    [EstWaterVol]                FLOAT (53)       NULL,
    [EstGasVolMCF]               FLOAT (53)       NULL,
    [EstGasVolMMBTU]             FLOAT (53)       NULL,
    [EstCO2Vol]                  FLOAT (53)       NULL,
    [EstCO2Mass]                 FLOAT (53)       NULL,
    [EstPlantGasMCF]             FLOAT (53)       NULL,
    [EstPlantGasMMBTU]           FLOAT (53)       NULL,
    [EstInjOilVol]               FLOAT (53)       NULL,
    [EstInjWaterVol]             FLOAT (53)       NULL,
    [EstInjGasVolMCF]            FLOAT (53)       NULL,
    [EstInjGasVolMMBTU]          FLOAT (53)       NULL,
    [EstInjCO2Vol]               FLOAT (53)       NULL,
    [EstInjOtherVol]             FLOAT (53)       NULL,
    [EstOtherVol]                FLOAT (53)       NULL,
    [EstNGLVol]                  FLOAT (53)       NULL,
    [EstSulfurMass]              FLOAT (53)       NULL,
    [EstBeginningOil]            FLOAT (53)       NULL,
    [EstEndingOil]               FLOAT (53)       NULL,
    [EstOilProduction]           FLOAT (53)       NULL,
    [EstBeginningWater]          FLOAT (53)       NULL,
    [EstEndingWater]             FLOAT (53)       NULL,
    [EstWaterProduction]         FLOAT (53)       NULL,
    [EnteredBTUFactor]           FLOAT (53)       NULL,
    [EnteredTemperature]         FLOAT (53)       NULL,
    [EnteredPressureBase]        FLOAT (53)       NULL,
    [EnteredGravity]             FLOAT (53)       NULL,
    [EnteredWetDryFlag]          INT              NULL,
    [EnteredOilVol]              FLOAT (53)       NULL,
    [EnteredWaterVol]            FLOAT (53)       NULL,
    [EnteredGasVolMCF]           FLOAT (53)       NULL,
    [EnteredGasVolMMBTU]         FLOAT (53)       NULL,
    [EnteredGasSalesVolMCF]      FLOAT (53)       NULL,
    [EnteredGasSalesVolMMBTU]    FLOAT (53)       NULL,
    [EnteredCO2Vol]              FLOAT (53)       NULL,
    [EnteredCO2Mass]             FLOAT (53)       NULL,
    [EnteredOtherVol]            FLOAT (53)       NULL,
    [EnteredOilProduction]       FLOAT (53)       NULL,
    [EnteredWaterProduction]     FLOAT (53)       NULL,
    [EnteredBeginningOil]        FLOAT (53)       NULL,
    [EnteredEndingOil]           FLOAT (53)       NULL,
    [EnteredBeginningWater]      FLOAT (53)       NULL,
    [EnteredEndingWater]         FLOAT (53)       NULL,
    [EnteredPlantGasMCF]         FLOAT (53)       NULL,
    [EnteredPlantGasMMBTU]       FLOAT (53)       NULL,
    [EnteredInjOilVol]           FLOAT (53)       NULL,
    [EnteredInjWaterVol]         FLOAT (53)       NULL,
    [EnteredInjGasVolMCF]        FLOAT (53)       NULL,
    [EnteredInjGasVolMMBTU]      FLOAT (53)       NULL,
    [EnteredInjCO2Vol]           FLOAT (53)       NULL,
    [EnteredInjOtherVol]         FLOAT (53)       NULL,
    [EnteredNGLVol]              FLOAT (53)       NULL,
    [EnteredGasFlareMcf]         FLOAT (53)       NULL,
    [EnteredGasFlashMcf]         FLOAT (53)       NULL,
    [EnteredGasVolMcfLeaseUse]   FLOAT (53)       NULL,
    [EnteredGasVentedMcf]        FLOAT (53)       NULL,
    [EnteredRetrogradeVol]       FLOAT (53)       NULL,
    [EntConvBTUFactor]           FLOAT (53)       NULL,
    [EntConvTemperature]         FLOAT (53)       NULL,
    [EntConvPressureBase]        FLOAT (53)       NULL,
    [EntConvGravity]             FLOAT (53)       NULL,
    [EntConvWetDryFlag]          INT              NULL,
    [EntConvOilVol]              FLOAT (53)       NULL,
    [EntConvWaterVol]            FLOAT (53)       NULL,
    [EntConvGasVolMCF]           FLOAT (53)       NULL,
    [EntConvGasVolMMBTU]         FLOAT (53)       NULL,
    [EntConvGasSalesVolMCF]      FLOAT (53)       NULL,
    [EntConvGasSalesVolMMBTU]    FLOAT (53)       NULL,
    [EntConvCO2Vol]              FLOAT (53)       NULL,
    [EntConvOtherVol]            FLOAT (53)       NULL,
    [EntConvPlantGasMCF]         FLOAT (53)       NULL,
    [EntConvPlantGasMMBTU]       FLOAT (53)       NULL,
    [EntConvInjOilVol]           FLOAT (53)       NULL,
    [EntConvInjWaterVol]         FLOAT (53)       NULL,
    [EntConvInjGasVolMCF]        FLOAT (53)       NULL,
    [EntConvInjGasVolMMBTU]      FLOAT (53)       NULL,
    [EntConvInjCO2Vol]           FLOAT (53)       NULL,
    [EntConvInjOtherVol]         FLOAT (53)       NULL,
    [FactorComputationFlag]      INT              NULL,
    [EnteredAsAllocatedFlag]     INT              NULL,
    [AllocationActiveFlag]       INT              NULL,
    [FixedVolumeFlagOil]         INT              NULL,
    [FixedVolumeFlagGas]         INT              NULL,
    [FixedVolumeFlagWater]       INT              NULL,
    [AllocationFactor]           FLOAT (53)       NULL,
    [AllocationFactorType]       INT              NULL,
    [AllocationFactor2]          FLOAT (53)       NULL,
    [AllocationFactorType2]      INT              NULL,
    [AllocationFactor3]          FLOAT (53)       NULL,
    [AllocationFactorType3]      INT              NULL,
    [AllocationFactor4]          FLOAT (53)       NULL,
    [AllocationFactorType4]      INT              NULL,
    [AllocationFactor5]          FLOAT (53)       NULL,
    [AllocationFactorType5]      INT              NULL,
    [AllocationFactor6]          FLOAT (53)       NULL,
    [AllocationFactorType6]      INT              NULL,
    [AllocationFactor7]          FLOAT (53)       NULL,
    [AllocationFactorType7]      INT              NULL,
    [AllocationFactor8]          FLOAT (53)       NULL,
    [AllocationFactorType8]      INT              NULL,
    [EquipAllocFactor]           FLOAT (53)       NULL,
    [EquipAllocFactorType]       INT              NULL,
    [EquipAllocFactor2]          FLOAT (53)       NULL,
    [EquipAllocFactorType2]      INT              NULL,
    [EquipAllocFactor3]          FLOAT (53)       NULL,
    [EquipAllocFactorType3]      INT              NULL,
    [EquipAllocFactor4]          FLOAT (53)       NULL,
    [EquipAllocFactorType4]      INT              NULL,
    [LastEnteredDataChanged]     DATETIME         NULL,
    [LeaseUseCompressor]         FLOAT (53)       NULL,
    [LeaseUseMarket]             FLOAT (53)       NULL,
    [LeaseUseProduction]         FLOAT (53)       NULL,
    [LeaseUse]                   FLOAT (53)       NULL,
    [GasTargetProd]              FLOAT (53)       NULL,
    [OilTargetProd]              FLOAT (53)       NULL,
    [TheoreticalProdGas]         FLOAT (53)       NULL,
    [TheoreticalProdGasLiquids]  FLOAT (53)       NULL,
    [TheoreticalProdGasLift]     FLOAT (53)       NULL,
    [TheoreticalProdGasHighPres] FLOAT (53)       NULL,
    [TheoreticalProdGasLowPres]  FLOAT (53)       NULL,
    [TheoreticalProdOil]         FLOAT (53)       NULL,
    [TheoreticalProdWater]       FLOAT (53)       NULL,
    [TheoreticalProdCO2]         FLOAT (53)       NULL,
    [TheoreticalInjGasMCF]       FLOAT (53)       NULL,
    [TheoreticalInjOil]          FLOAT (53)       NULL,
    [TheoreticalInjWater]        FLOAT (53)       NULL,
    [TheoreticalInjCO2]          FLOAT (53)       NULL,
    [TheoreticalGasLiquidsGPM]   FLOAT (53)       NULL,
    [TheoreticalShrinkage]       FLOAT (53)       NULL,
    [TheoreticalOilWaterRatio]   FLOAT (53)       NULL,
    [TheoreticalWaterGPM]        FLOAT (53)       NULL,
    [TheoreticalOilGPM]          FLOAT (53)       NULL,
    [SustainedDeliverabilityGas] FLOAT (53)       NULL,
    [SustainedDeliverabilityOil] FLOAT (53)       NULL,
    [PressureClassification]     INT              NULL,
    [DeliverabilityComment]      VARCHAR (50)     NULL,
    [DeliverabilityCalcFlag]     INT              NULL,
    [OilGasAllocationRatio]      FLOAT (53)       NULL,
    [WaterGasAllocationRatio]    FLOAT (53)       NULL,
    [OilRunTickets]              INT              NULL,
    [WaterRunTickets]            INT              NULL,
    [PropertyNumber]             VARCHAR (20)     NULL,
    [WellNumber]                 VARCHAR (20)     NULL,
    [CompletionNumber]           VARCHAR (20)     NULL,
    [WellName]                   VARCHAR (60)     NULL,
    [CompletionName]             VARCHAR (60)     NULL,
    [CompletionType]             INT              NULL,
    [FormationID]                INT              NULL,
    [ProjectNumber]              VARCHAR (20)     NULL,
    [OperatorWellID]             VARCHAR (20)     NULL,
    [GatheringSystemID]          INT              NULL,
    [AccountingTeamID]           INT              NULL,
    [DrillingTeamID]             INT              NULL,
    [ProductionTeamID]           INT              NULL,
    [GroupID]                    INT              NULL,
    [DivisionID]                 INT              NULL,
    [FieldGroupID]               INT              NULL,
    [AreaID]                     INT              NULL,
    [PlatformID]                 INT              NULL,
    [BatteryID]                  INT              NULL,
    [LeaseID]                    INT              NULL,
    [DDAID]                      INT              NULL,
    [ReserveCatagory]            INT              NULL,
    [AccountingID]               VARCHAR (30)     NULL,
    [ProductionID]               VARCHAR (30)     NULL,
    [EngineeringID]              VARCHAR (30)     NULL,
    [SustainedDeliverability]    FLOAT (53)       NULL,
    [ProductCode]                INT              NULL,
    [DispositionCode]            INT              NULL,
    [EnteredGasLiftMCF]          FLOAT (53)       NULL,
    [EnteredGasLiftMMBTU]        FLOAT (53)       NULL,
    [EntConvGasLiftMCF]          FLOAT (53)       NULL,
    [EntConvGasLiftMMBTU]        FLOAT (53)       NULL,
    [AllocActGasLiftMCF]         FLOAT (53)       NULL,
    [OilReserve]                 FLOAT (53)       NULL,
    [GasReserve]                 FLOAT (53)       NULL,
    [WaterReserve]               FLOAT (53)       NULL,
    [SummationFlag]              INT              NULL,
    [BackgroundTaskFlag]         INT              NULL,
    [LastTransmission]           INT              NULL,
    [LastLoadDate]               DATETIME         NULL,
    [LastLoadTime]               CHAR (8)         NULL,
    [TransmitFlag]               INT              NULL,
    [DateTimeStamp]              DATETIME         NULL,
    [BLogicDateStamp]            DATETIME         NULL,
    [BLogicTimeStamp]            CHAR (8)         NULL,
    [AllocationDateStamp]        DATETIME         NULL,
    [AllocationTimeStamp]        CHAR (8)         NULL,
    [UserDateStamp]              DATETIME         NULL,
    [UserTimeStamp]              CHAR (8)         NULL,
    [UserID]                     INT              NULL,
    [CalculationStatusFlag]      INT              NOT NULL,
    [EnteredBeginningNGL]        FLOAT (53)       NULL,
    [EnteredEndingNGL]           FLOAT (53)       NULL,
    [EnteredNGLProduction]       FLOAT (53)       NULL,
    [RowUID]                     UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_CompletionMonthlyTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC, [RecordDate] ASC)
);

