CREATE TABLE [dbo].[DispositionCodeTb] (
    [MerrickID]                  INT              NOT NULL,
    [ProductTypeID]              INT              NULL,
    [DispositionCodeDescription] VARCHAR (50)     NULL,
    [DispositionCodeShort]       VARCHAR (16)     NULL,
    [ActiveFlag]                 INT              NULL,
    [FuelUseTypeFlag]            INT              NULL,
    [DispositionGrouping]        INT              NULL,
    [ProductionVolumeFlag]       INT              NULL,
    [PurchaserID]                VARCHAR (10)     NULL,
    [ProductionID]               VARCHAR (30)     NULL,
    [AccountingID]               VARCHAR (30)     NULL,
    [EngineeringID]              VARCHAR (30)     NULL,
    [BillingID]                  VARCHAR (10)     NULL,
    [SealRequiredFlag]           INT              NULL,
    [SealType]                   INT              NULL,
    [SealDistribution]           INT              NULL,
    [AccountingUploadFlag]       INT              NULL,
    [EngineeringUploadFlag]      INT              NULL,
    [MmsMroCode]                 VARCHAR (10)     NULL,
    [MmsOgorCode]                VARCHAR (10)     NULL,
    [TexasStateCode]             VARCHAR (10)     NULL,
    [LouisianaStateCode]         VARCHAR (10)     NULL,
    [NewMexicoStateCode]         VARCHAR (10)     NULL,
    [CaliforniaStateCode]        VARCHAR (10)     NULL,
    [OklahomaStateCode]          VARCHAR (10)     NULL,
    [UtahStateCode]              VARCHAR (10)     NULL,
    [ColoradoStateCode]          VARCHAR (10)     NULL,
    [NorthDakotaStateCode]       VARCHAR (10)     NULL,
    [SouthDakotaStateCode]       VARCHAR (10)     NULL,
    [MississippiStateCode]       VARCHAR (10)     NULL,
    [ArkansasStateCode]          VARCHAR (10)     NULL,
    [WyomingStateCode]           VARCHAR (10)     NULL,
    [MontanaStateCode]           VARCHAR (20)     NULL,
    [AlabamaStateCode]           VARCHAR (10)     NULL,
    [MichiganStateCode]          VARCHAR (10)     NULL,
    [AlaskaStateCode]            VARCHAR (10)     NULL,
    [InternalID]                 VARCHAR (10)     NULL,
    [StateRegulatoryID]          VARCHAR (10)     NULL,
    [FederalRegulatoryID]        VARCHAR (10)     NULL,
    [DateTimeStamp]              DATETIME         NULL,
    [UserDateStamp]              DATETIME         NULL,
    [UserTimeStamp]              CHAR (8)         NULL,
    [UserID]                     INT              NULL,
    [RowUID]                     UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_DispositionCodeTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC)
);

