CREATE TABLE [dbo].[DowntimeReasonTb] (
    [ObjectMerrickID]     INT              NOT NULL,
    [ObjectType]          INT              NOT NULL,
    [OriginalDateEntered] DATETIME         NOT NULL,
    [OriginalTimeEntered] CHAR (8)         NOT NULL,
    [UpDownFlag]          INT              NULL,
    [DateEntryFlag]       INT              NULL,
    [DowntimeCode]        INT              NULL,
    [DowntimeHours]       FLOAT (53)       NULL,
    [RepairCosts]         FLOAT (53)       NULL,
    [LostProduction]      FLOAT (53)       NULL,
    [CalcDowntimeFlag]    INT              NOT NULL,
    [StartDate]           DATETIME         NULL,
    [EndDate]             DATETIME         NULL,
    [StartTime]           CHAR (8)         NULL,
    [EndTime]             CHAR (8)         NULL,
    [StartProductionDate] DATETIME         NULL,
    [EndProductionDate]   DATETIME         NULL,
    [Comments]            VARCHAR (80)     NULL,
    [Reason]              VARCHAR (80)     NULL,
    [MessageSendFlag]     INT              NULL,
    [DestinationPerson]   INT              NULL,
    [RioDowntimeID]       VARCHAR (40)     NULL,
    [LastDayHoursDown]    FLOAT (53)       NULL,
    [DeleteFlag]          INT              NULL,
    [LastTransmission]    INT              NULL,
    [LastLoadDate]        DATETIME         NULL,
    [LastLoadTime]        CHAR (8)         NULL,
    [TransmitFlag]        INT              NULL,
    [DateTimeStamp]       DATETIME         NULL,
    [BLogicDateStamp]     DATETIME         NULL,
    [BLogicTimeStamp]     CHAR (8)         NULL,
    [UserDateStamp]       DATETIME         NULL,
    [UserTimeStamp]       CHAR (8)         NULL,
    [UserID]              INT              NULL,
    [RowUID]              UNIQUEIDENTIFIER NOT NULL,
    [CommentServiceID]    INT              NULL,
    [AllocationDateStamp] DATETIME         NOT NULL,
    CONSTRAINT [PK_DowntimeReasonTb] PRIMARY KEY CLUSTERED ([ObjectMerrickID] ASC, [ObjectType] ASC, [OriginalDateEntered] ASC, [OriginalTimeEntered] ASC)
);

