CREATE TABLE [dbo].[EquipmentDailyTb] (
    [MerrickID]               INT              NOT NULL,
    [RecordDate]              DATETIME         NOT NULL,
    [ProductCode]             INT              NULL,
    [ProductType]             INT              NULL,
    [DispositionCode]         INT              NULL,
    [DataSourceCode]          INT              NULL,
    [AllocationMethod]        INT              NULL,
    [AllocationOrder]         INT              NULL,
    [AllocationByComponent]   INT              NULL,
    [ErrorNumber]             INT              NULL,
    [ProductionDate]          DATETIME         NULL,
    [ActBTUFactor]            FLOAT (53)       NULL,
    [ActTemperature]          FLOAT (53)       NULL,
    [ActPressureBase]         FLOAT (53)       NULL,
    [ActGravity]              FLOAT (53)       NULL,
    [ActWetDryFlag]           INT              NULL,
    [ActOilVol]               FLOAT (53)       NULL,
    [ActWaterVol]             FLOAT (53)       NULL,
    [ActGasVolMCF]            FLOAT (53)       NULL,
    [ActGasVolMMBTU]          FLOAT (53)       NULL,
    [ActOtherVol]             FLOAT (53)       NULL,
    [ActHeatFactor]           FLOAT (53)       NULL,
    [ConvBTUFactor]           FLOAT (53)       NULL,
    [ConvTemperature]         FLOAT (53)       NULL,
    [ConvPressureBase]        FLOAT (53)       NULL,
    [ConvGravity]             FLOAT (53)       NULL,
    [ConvWetDryFlag]          INT              NULL,
    [ConvOilVol]              FLOAT (53)       NULL,
    [ConvWaterVol]            FLOAT (53)       NULL,
    [ConvGasVolMCF]           FLOAT (53)       NULL,
    [ConvGasVolMMBTU]         FLOAT (53)       NULL,
    [ConvOtherVol]            FLOAT (53)       NULL,
    [ConvHeatFactor]          FLOAT (53)       NULL,
    [LeaseUseCoefficient]     FLOAT (53)       NULL,
    [LeaseUseCoefficientType] INT              NULL,
    [Taxable]                 INT              NULL,
    [DownTimeHours]           FLOAT (53)       NULL,
    [HoursOn]                 FLOAT (53)       NULL,
    [HoursOpen]               FLOAT (53)       NULL,
    [HoursClose]              FLOAT (53)       NULL,
    [VolumeAutoPopulateFlag]  INT              NULL,
    [HoursOnAutopopulateFlag] INT              NULL,
    [StrokesPerMinute]        FLOAT (53)       NULL,
    [EngineRPM]               FLOAT (53)       NULL,
    [SuctionPressure]         FLOAT (53)       NULL,
    [DischargePressure]       FLOAT (53)       NULL,
    [PumpingPressure]         FLOAT (53)       NULL,
    [Stage1Pressure]          FLOAT (53)       NULL,
    [Stage2Pressure]          FLOAT (53)       NULL,
    [Stage3Pressure]          FLOAT (53)       NULL,
    [Stage4Pressure]          FLOAT (53)       NULL,
    [SuctionOrBoost1]         FLOAT (53)       NULL,
    [SuctionOrBoost2]         FLOAT (53)       NULL,
    [IntakePressure]          FLOAT (53)       NULL,
    [SuctionTemp]             FLOAT (53)       NULL,
    [DischargeTemp]           FLOAT (53)       NULL,
    [Stage1Temp]              FLOAT (53)       NULL,
    [Stage2Temp]              FLOAT (53)       NULL,
    [Stage3Temp]              FLOAT (53)       NULL,
    [Stage4Temp]              FLOAT (53)       NULL,
    [Exhaust1Temp]            FLOAT (53)       NULL,
    [Exhaust2Temp]            FLOAT (53)       NULL,
    [InletOilTemp]            FLOAT (53)       NULL,
    [OutletOilTemp]           FLOAT (53)       NULL,
    [ExchangeTemp]            FLOAT (53)       NULL,
    [EngineWaterTemp]         FLOAT (53)       NULL,
    [EngineOilTemp]           FLOAT (53)       NULL,
    [EngineOilPressure]       FLOAT (53)       NULL,
    [CompressorWaterTemp]     FLOAT (53)       NULL,
    [CompressorOilTemp]       FLOAT (53)       NULL,
    [CompressorOilPressure]   FLOAT (53)       NULL,
    [LubricationOilUsed]      FLOAT (53)       NULL,
    [LastEnteredDate]         DATETIME         NULL,
    [LastEnteredDateDays]     INT              NULL,
    [RateComputationFlag]     INT              NULL,
    [RateOil]                 FLOAT (53)       NULL,
    [RateWater]               FLOAT (53)       NULL,
    [RateGas]                 FLOAT (53)       NULL,
    [UserNumber1]             FLOAT (53)       NULL,
    [UserNumber2]             FLOAT (53)       NULL,
    [UserNumber3]             FLOAT (53)       NULL,
    [UserNumber4]             FLOAT (53)       NULL,
    [UserNumber5]             FLOAT (53)       NULL,
    [UserNumber6]             FLOAT (53)       NULL,
    [UserStringA]             VARCHAR (50)     NULL,
    [UserStringB]             VARCHAR (50)     NULL,
    [EngineTemperature]       INT              NULL,
    [OilPressure]             INT              NULL,
    [DownTimeCode]            INT              NULL,
    [CommentID]               INT              NULL,
    [BackgroundTaskFlag]      INT              NULL,
    [LastTransmission]        INT              NULL,
    [LastLoadDate]            DATETIME         NULL,
    [LastLoadTime]            CHAR (8)         NULL,
    [TransmitFlag]            INT              NULL,
    [DateTimeStamp]           DATETIME         NULL,
    [BLogicDateStamp]         DATETIME         NULL,
    [BLogicTimeStamp]         CHAR (8)         NULL,
    [AllocationDateStamp]     DATETIME         NULL,
    [AllocationTimeStamp]     CHAR (8)         NULL,
    [UserDateStamp]           DATETIME         NULL,
    [UserTimeStamp]           CHAR (8)         NULL,
    [UserID]                  INT              NULL,
    [CalculationStatusFlag]   INT              NOT NULL,
    [StillDownFlag]           INT              NULL,
    [RowUID]                  UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_EquipmentDailyTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC, [RecordDate] ASC)
);

