CREATE TABLE [dbo].[EquipmentMonthlyTb] (
    [MerrickID]               INT              NOT NULL,
    [RecordDate]              DATETIME         NOT NULL,
    [ProductCode]             INT              NULL,
    [ProductType]             INT              NULL,
    [DispositionCode]         INT              NULL,
    [DataSourceCode]          INT              NULL,
    [AllocationMethod]        INT              NULL,
    [AllocationOrder]         INT              NULL,
    [AllocationByComponent]   INT              NULL,
    [StartDate]               DATETIME         NULL,
    [EndDate]                 DATETIME         NULL,
    [ActBTUFactor]            FLOAT (53)       NULL,
    [ActTemperature]          FLOAT (53)       NULL,
    [ActPressureBase]         FLOAT (53)       NULL,
    [ActGravity]              FLOAT (53)       NULL,
    [ActWetDryFlag]           INT              NULL,
    [ActOilVol]               FLOAT (53)       NULL,
    [ActWaterVol]             FLOAT (53)       NULL,
    [ActGasVolMCF]            FLOAT (53)       NULL,
    [ActGasVolMMBTU]          FLOAT (53)       NULL,
    [ActOtherVol]             FLOAT (53)       NULL,
    [ActHeatFactor]           FLOAT (53)       NULL,
    [ConvBTUFactor]           FLOAT (53)       NULL,
    [ConvTemperature]         FLOAT (53)       NULL,
    [ConvPressureBase]        FLOAT (53)       NULL,
    [ConvGravity]             FLOAT (53)       NULL,
    [ConvWetDryFlag]          INT              NULL,
    [ConvOilVol]              FLOAT (53)       NULL,
    [ConvWaterVol]            FLOAT (53)       NULL,
    [ConvGasVolMCF]           FLOAT (53)       NULL,
    [ConvGasVolMMBTU]         FLOAT (53)       NULL,
    [ConvOtherVol]            FLOAT (53)       NULL,
    [ConvHeatFactor]          FLOAT (53)       NULL,
    [EstBTUFactor]            FLOAT (53)       NULL,
    [EstTemperature]          FLOAT (53)       NULL,
    [EstPressureBase]         FLOAT (53)       NULL,
    [EstGravity]              FLOAT (53)       NULL,
    [EstWetDryFlag]           INT              NULL,
    [EstOilVol]               FLOAT (53)       NULL,
    [EstWaterVol]             FLOAT (53)       NULL,
    [EstGasVolMCF]            FLOAT (53)       NULL,
    [EstGasVolMMBTU]          FLOAT (53)       NULL,
    [EstOtherVol]             FLOAT (53)       NULL,
    [EstHeatFactor]           FLOAT (53)       NULL,
    [DownTimeHours]           FLOAT (53)       NULL,
    [HoursOn]                 FLOAT (53)       NULL,
    [CummHoursOn]             FLOAT (53)       NULL,
    [DaysOn]                  FLOAT (53)       NULL,
    [LeaseUseCoefficient]     FLOAT (53)       NULL,
    [LeaseUseCoefficientType] INT              NULL,
    [Taxable]                 INT              NULL,
    [HoursOnOverwriteFlag]    INT              NULL,
    [MonthlyAutopopulateFlag] INT              NULL,
    [EquipmentNumber]         VARCHAR (20)     NULL,
    [EquipmentType]           INT              NULL,
    [GatheringSystemID]       INT              NULL,
    [EquipmentName]           VARCHAR (30)     NULL,
    [EquipmentDescription]    VARCHAR (50)     NULL,
    [EquipmentOwnerID]        INT              NULL,
    [EquipmentOwnerLoc]       INT              NULL,
    [MeasurementPointRole]    INT              NULL,
    [AccountingID]            VARCHAR (30)     NULL,
    [ProductionID]            VARCHAR (30)     NULL,
    [EngineeringID]           VARCHAR (30)     NULL,
    [AccountingTeamID]        INT              NULL,
    [DrillingTeamID]          INT              NULL,
    [ProductionTeamID]        INT              NULL,
    [GroupID]                 INT              NULL,
    [DivisionID]              INT              NULL,
    [FieldGroupID]            INT              NULL,
    [AreaID]                  INT              NULL,
    [PlatformID]              INT              NULL,
    [BatteryID]               INT              NULL,
    [SuperPersonID]           INT              NULL,
    [ForemanPersonID]         INT              NULL,
    [PumperPersonID]          INT              NULL,
    [EngineerPersonID]        INT              NULL,
    [AccountantPersonID]      INT              NULL,
    [CompletionMethod]        INT              NULL,
    [InternalUnitNumber]      VARCHAR (20)     NULL,
    [LeaseUseMarket]          FLOAT (53)       NULL,
    [LeaseUseProduction]      FLOAT (53)       NULL,
    [DownTimeCode]            INT              NULL,
    [ActiveFlag]              INT              NULL,
    [BackgroundTaskFlag]      INT              NULL,
    [DateTimeStamp]           DATETIME         NULL,
    [BLogicDateStamp]         DATETIME         NULL,
    [BLogicTimeStamp]         CHAR (8)         NULL,
    [AllocationDateStamp]     DATETIME         NULL,
    [AllocationTimeStamp]     CHAR (8)         NULL,
    [UserDateStamp]           DATETIME         NULL,
    [UserTimeStamp]           CHAR (8)         NULL,
    [UserID]                  INT              NULL,
    [CalculationStatusFlag]   INT              NOT NULL,
    [RowUID]                  UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_EquipmentMonthlyTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC, [RecordDate] ASC)
);

