CREATE TABLE [dbo].[MeterDailyDispTb] (
    [MerrickID]              INT          NOT NULL,
    [RecordDate]             DATETIME     NOT NULL,
    [SourceID]               INT          NOT NULL,
    [SourceType]             INT          NOT NULL,
    [RunTicketNumber]        VARCHAR (22) NOT NULL,
    [RunTicketDate]          DATETIME     NULL,
    [RunTicketFlag]          INT          NULL,
    [ProductCode]            INT          NULL,
    [ProductType]            INT          NULL,
    [DispositionCode]        INT          NULL,
    [OverwriteFlag]          INT          NULL,
    [GatheringSystemID]      INT          NULL,
    [SourceAllocationMethod] INT          NULL,
    [AllocActBTUFactor]      FLOAT (53)   NULL,
    [AllocActTemperature]    FLOAT (53)   NULL,
    [AllocActPressureBase]   FLOAT (53)   NULL,
    [AllocActGravity]        FLOAT (53)   NULL,
    [AllocActWetDryFlag]     INT          NULL,
    [AllocActOilVol]         FLOAT (53)   NULL,
    [AllocActWaterVol]       FLOAT (53)   NULL,
    [AllocActGasVolMCF]      FLOAT (53)   NULL,
    [AllocActGasVolMMBTU]    FLOAT (53)   NULL,
    [AllocActPlantGasMCF]    FLOAT (53)   NULL,
    [AllocActPlantGasMMBTU]  FLOAT (53)   NULL,
    [AllocActCO2Vol]         FLOAT (53)   NULL,
    [AllocActOtherVol]       FLOAT (53)   NULL,
    [AllocActOilProd]        FLOAT (53)   NULL,
    [AllocActWaterProd]      FLOAT (53)   NULL,
    [AllocBeginningOil]      FLOAT (53)   NULL,
    [AllocBeginningWater]    FLOAT (53)   NULL,
    [AllocEndOil]            FLOAT (53)   NULL,
    [AllocEndWater]          FLOAT (53)   NULL,
    [AllocBasisGasVolMCF]    FLOAT (53)   NULL,
    [AllocBasisGasVolMMBTU]  FLOAT (53)   NULL,
    [AllocBasisOilVol]       FLOAT (53)   NULL,
    [AllocBasisWaterVol]     FLOAT (53)   NULL,
    [AllocBasisOilProd]      FLOAT (53)   NULL,
    [AllocBasisWaterProd]    FLOAT (53)   NULL,
    [DateTimeStamp]          DATETIME     NULL,
    [AllocationDateStamp]    DATETIME     NULL,
    [AllocationTimeStamp]    CHAR (8)     NULL,
    [UserDateStamp]          DATETIME     NULL,
    [UserTimeStamp]          CHAR (8)     NULL,
    [UserID]                 INT          NULL,
    [AllocActMass]           FLOAT (53)   NOT NULL,
    CONSTRAINT [PK_MeterDailyDispTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC, [RecordDate] ASC, [SourceID] ASC, [SourceType] ASC, [RunTicketNumber] ASC)
);

