CREATE TABLE [dbo].[MeterDailyTb] (
    [MerrickID]                  INT              NOT NULL,
    [RecordDate]                 DATETIME         NOT NULL,
    [GatheringSystemID]          INT              NULL,
    [ProductCode]                INT              NULL,
    [ProductType]                INT              NULL,
    [DispositionCode]            INT              NULL,
    [DataSourceCode]             INT              NULL,
    [MeterType]                  INT              NULL,
    [SetupDataChangeFlag]        INT              NULL,
    [AllocBTUFactor]             FLOAT (53)       NULL,
    [AllocTemperature]           FLOAT (53)       NULL,
    [AllocPressureBase]          FLOAT (53)       NULL,
    [AllocGravity]               FLOAT (53)       NULL,
    [AllocWetDryFlag]            INT              NULL,
    [AllocOilVol]                FLOAT (53)       NULL,
    [AllocWaterVol]              FLOAT (53)       NULL,
    [AllocGasVolMCF]             FLOAT (53)       NULL,
    [AllocGasVolMMBTU]           FLOAT (53)       NULL,
    [AllocPlantGasMCF]           FLOAT (53)       NULL,
    [AllocPlantGasMMBTU]         FLOAT (53)       NULL,
    [AllocCO2Vol]                FLOAT (53)       NULL,
    [AllocCO2Mass]               FLOAT (53)       NULL,
    [AllocOtherVol]              FLOAT (53)       NULL,
    [EstBTUFactor]               FLOAT (53)       NULL,
    [EstTemperature]             FLOAT (53)       NULL,
    [EstPressureBase]            FLOAT (53)       NULL,
    [EstGravity]                 FLOAT (53)       NULL,
    [EstWetDryFlag]              INT              NULL,
    [EstOilVol]                  FLOAT (53)       NULL,
    [EstWaterVol]                FLOAT (53)       NULL,
    [EstGasVolMCF]               FLOAT (53)       NULL,
    [EstGasVolMMBTU]             FLOAT (53)       NULL,
    [EstSulfurMass]              FLOAT (53)       NULL,
    [EstNGLVol]                  FLOAT (53)       NULL,
    [EstCO2Vol]                  FLOAT (53)       NULL,
    [EstCO2Mass]                 FLOAT (53)       NULL,
    [EstOtherVol]                FLOAT (53)       NULL,
    [ConvEstBTUFactor]           FLOAT (53)       NULL,
    [ConvEstTemperature]         FLOAT (53)       NULL,
    [ConvEstPressureBase]        FLOAT (53)       NULL,
    [ConvEstGravity]             FLOAT (53)       NULL,
    [ConvEstWetDryFlag]          INT              NULL,
    [ConvEstOilVol]              FLOAT (53)       NULL,
    [ConvEstWaterVol]            FLOAT (53)       NULL,
    [ConvEstGasVolMCF]           FLOAT (53)       NULL,
    [ConvEstGasVolMMBTU]         FLOAT (53)       NULL,
    [ConvEstCO2Vol]              FLOAT (53)       NULL,
    [ConvEstOtherVol]            FLOAT (53)       NULL,
    [FuelUseGasVolMCF]           FLOAT (53)       NULL,
    [FuelUseGasVolMMBTU]         FLOAT (53)       NULL,
    [FuelUseOilVol]              FLOAT (53)       NULL,
    [FuelUseOtherVol]            FLOAT (53)       NULL,
    [LastEnteredDate]            DATETIME         NULL,
    [LastEnteredDateDays]        INT              NULL,
    [RateComputationFlag]        INT              NULL,
    [RateOil]                    FLOAT (53)       NULL,
    [RateWater]                  FLOAT (53)       NULL,
    [RateGas]                    FLOAT (53)       NULL,
    [RateCO2]                    FLOAT (53)       NULL,
    [AllocationMethod]           INT              NULL,
    [AllocationMethodUpstream]   INT              NULL,
    [AllocatedVolumeSource]      INT              NULL,
    [AllocationOrder]            INT              NULL,
    [AllocationByComponent]      INT              NULL,
    [ProrateUsingFuelUseFlag]    INT              NULL,
    [VolumeBasisFlag]            INT              NULL,
    [VolumeAutoPopFlag]          INT              NULL,
    [InjectionMeasPointFlag]     INT              NULL,
    [PhysicalMeterFlag]          INT              NULL,
    [PressureClassification]     INT              NULL,
    [FixedVolumeFlagOil]         INT              NULL,
    [FixedVolumeFlagGas]         INT              NULL,
    [FixedVolumeFlagWater]       INT              NULL,
    [FactorComputationFlag]      INT              NULL,
    [AllocationFactor]           FLOAT (53)       NULL,
    [AllocationFactorType]       INT              NULL,
    [AllocationFactorComment]    VARCHAR (20)     NULL,
    [AllocationFactor2]          FLOAT (53)       NULL,
    [AllocationFactorType2]      INT              NULL,
    [AllocationFactorComment2]   VARCHAR (20)     NULL,
    [AllocationFactor3]          FLOAT (53)       NULL,
    [AllocationFactorType3]      INT              NULL,
    [AllocationFactorComment3]   VARCHAR (20)     NULL,
    [AllocationFactor4]          FLOAT (53)       NULL,
    [AllocationFactorType4]      INT              NULL,
    [AllocationFactorComment4]   VARCHAR (20)     NULL,
    [AllocationFactor5]          FLOAT (53)       NULL,
    [AllocationFactorType5]      INT              NULL,
    [AllocationFactor6]          FLOAT (53)       NULL,
    [AllocationFactorType6]      INT              NULL,
    [AllocationFactor7]          FLOAT (53)       NULL,
    [AllocationFactorType7]      INT              NULL,
    [AllocationFactor8]          FLOAT (53)       NULL,
    [AllocationFactorType8]      INT              NULL,
    [EquipAllocFactor]           FLOAT (53)       NULL,
    [EquipAllocFactorType]       INT              NULL,
    [EquipAllocFactorComment]    VARCHAR (20)     NULL,
    [EquipAllocFactor2]          FLOAT (53)       NULL,
    [EquipAllocFactorType2]      INT              NULL,
    [EquipAllocFactorComment2]   VARCHAR (20)     NULL,
    [EquipAllocFactor3]          FLOAT (53)       NULL,
    [EquipAllocFactorType3]      INT              NULL,
    [EquipAllocFactor4]          FLOAT (53)       NULL,
    [EquipAllocFactorType4]      INT              NULL,
    [GasNominationMCF]           FLOAT (53)       NULL,
    [GasNominationBTUFactor]     FLOAT (53)       NULL,
    [GasNominationMMBTU]         FLOAT (53)       NULL,
    [BatteryProdCalcFlag]        INT              NULL,
    [BatteryProdGas]             FLOAT (53)       NULL,
    [BatteryProdOil]             FLOAT (53)       NULL,
    [BatteryProdWater]           FLOAT (53)       NULL,
    [BatteryProdNGL]             FLOAT (53)       NULL,
    [ProrationFactorGas]         FLOAT (53)       NULL,
    [ProrationFactorOil]         FLOAT (53)       NULL,
    [ProrationFactorWater]       FLOAT (53)       NULL,
    [ProrationFactorNGL]         FLOAT (53)       NULL,
    [HoursFlowed]                FLOAT (53)       NULL,
    [DownTimeHours]              FLOAT (53)       NULL,
    [ReadingTime]                CHAR (8)         NULL,
    [ReadingHours]               FLOAT (53)       NULL,
    [ProductionDate]             DATETIME         NULL,
    [StaticPressurePsig]         FLOAT (53)       NULL,
    [StaticPressurePsia]         FLOAT (53)       NULL,
    [OutputPressurePsia]         FLOAT (53)       NULL,
    [DifferentialPressure]       FLOAT (53)       NULL,
    [StaticRootReading]          FLOAT (53)       NULL,
    [DifferentialRootReading]    FLOAT (53)       NULL,
    [StaticPercentReading]       FLOAT (53)       NULL,
    [DifferentialPercentReading] FLOAT (53)       NULL,
    [EnteredVolume]              FLOAT (53)       NULL,
    [EnteredVolumeFlag]          INT              NULL,
    [OpenOdometer]               FLOAT (53)       NULL,
    [CloseOdometer]              FLOAT (53)       NULL,
    [LactOpenDate]               DATETIME         NULL,
    [LactOpenTime]               CHAR (8)         NULL,
    [LactCloseDate]              DATETIME         NULL,
    [LactCloseTime]              CHAR (8)         NULL,
    [BSAndW]                     FLOAT (53)       NULL,
    [OpenTemperature]            FLOAT (53)       NULL,
    [CloseTemperature]           FLOAT (53)       NULL,
    [ObservedTemperature]        FLOAT (53)       NULL,
    [ActualGravity]              FLOAT (53)       NULL,
    [ConvertedGravity]           FLOAT (53)       NULL,
    [GrossBarrels]               FLOAT (53)       NULL,
    [NetBarrels]                 FLOAT (53)       NULL,
    [LactMeterFactor]            FLOAT (53)       NULL,
    [LactCompressibilityFactor]  FLOAT (53)       NULL,
    [LactDensityCorrection]      FLOAT (53)       NULL,
    [OdometerResetFlag]          INT              NULL,
    [UnitsFlag]                  INT              NULL,
    [ShrinkageFactor]            FLOAT (53)       NULL,
    [GasEquivalentFactor]        FLOAT (53)       NULL,
    [MeterAdjustmentFactor]      FLOAT (53)       NULL,
    [GasTemperature]             FLOAT (53)       NULL,
    [LinearCoefficient]          FLOAT (53)       NULL,
    [SquareRootCoefficient]      FLOAT (53)       NULL,
    [ChartType]                  INT              NULL,
    [ChartCycle]                 INT              NULL,
    [OrificeHolderType]          INT              NULL,
    [PSIFlag]                    INT              NULL,
    [ComputeCoefficientFlag]     INT              NULL,
    [MeterCalculationFlag]       INT              NULL,
    [StaticRange]                FLOAT (53)       NULL,
    [DifferentialRange]          FLOAT (53)       NULL,
    [SpecificGravity]            FLOAT (53)       NULL,
    [PipeTubeDiameter]           FLOAT (53)       NULL,
    [OrificePlateDiameter]       FLOAT (53)       NULL,
    [ChokeLength]                FLOAT (53)       NULL,
    [MFactor]                    FLOAT (53)       NULL,
    [TemperatureRangeHigh]       FLOAT (53)       NULL,
    [TemperatureRangeLow]        FLOAT (53)       NULL,
    [FlangePipeFlag]             INT              NULL,
    [SteamQualityPercent]        FLOAT (53)       NULL,
    [OutputPressurePsig]         FLOAT (53)       NULL,
    [AbsolutePressure]           FLOAT (53)       NULL,
    [LinePressure]               FLOAT (53)       NOT NULL,
    [DowntimeFlag]               INT              NULL,
    [CommentID]                  INT              NULL,
    [SpringSize]                 CHAR (8)         NULL,
    [AllocOilProd]               FLOAT (53)       NULL,
    [AllocWaterProd]             FLOAT (53)       NULL,
    [BackgroundTaskFlag]         INT              NULL,
    [LastTransmission]           INT              NULL,
    [LastLoadDate]               DATETIME         NULL,
    [LastLoadTime]               CHAR (8)         NULL,
    [TransmitFlag]               INT              NULL,
    [DateTimeStamp]              DATETIME         NULL,
    [BLogicDateStamp]            DATETIME         NULL,
    [BLogicTimeStamp]            CHAR (8)         NULL,
    [AllocationDateStamp]        DATETIME         NULL,
    [AllocationTimeStamp]        CHAR (8)         NULL,
    [UserDateStamp]              DATETIME         NULL,
    [UserTimeStamp]              CHAR (8)         NULL,
    [UserID]                     INT              NULL,
    [EstMass]                    FLOAT (53)       NOT NULL,
    [CalculationStatusFlag]      INT              NOT NULL,
    [LoadTransferFlag]           INT              NULL,
    [OilMeterGaugePressure]      FLOAT (53)       NULL,
    [RowUID]                     UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_MeterDailyTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC, [RecordDate] ASC)
);

