CREATE TABLE [dbo].[MeterTb] (
    [MerrickID]                  INT              NOT NULL,
    [MeterNumber]                VARCHAR (30)     NULL,
    [MeterName]                  VARCHAR (40)     NULL,
    [MeterDescription]           VARCHAR (50)     NULL,
    [LegalDescription]           VARCHAR (40)     NULL,
    [MeterType]                  INT              NULL,
    [MeasurementPointRole]       INT              NULL,
    [AllocationTypeFlag]         INT              NULL,
    [AllocationTypeStartDate]    DATETIME         NULL,
    [AllocationOrder]            INT              NULL,
    [AllocationByComponent]      INT              NULL,
    [AllocAutoFlag]              INT              NULL,
    [AllocAutoStartDate]         DATETIME         NULL,
    [CopyConvertVolumeFlag]      INT              NULL,
    [CopyRunTicketVolumeFlag]    INT              NULL,
    [ComputeFactorFlag]          INT              NULL,
    [FuelFactorFlag]             INT              NULL,
    [MeterTestFrequency]         INT              NOT NULL,
    [AbsolutePressure]           FLOAT (53)       NULL,
    [OdometerMaximum]            FLOAT (53)       NULL,
    [ProrationCalcFlag]          INT              NULL,
    [UnitsTypeFlag]              INT              NULL,
    [UnitsConfigurableFlag]      INT              NULL,
    [DataEditStartDate]          DATETIME         NULL,
    [ProductCode]                INT              NULL,
    [ProductType]                INT              NULL,
    [DispositionCode]            INT              NULL,
    [CheckMeterMerrickId]        INT              NULL,
    [HoursOnTotal24Flag]         INT              NULL,
    [MeterCalculationFlag]       INT              NULL,
    [IgnoreBSWVolumeFlag]        INT              NULL,
    [OutsideOperatedFlag]        INT              NULL,
    [StandardReadingTime]        CHAR (8)         NULL,
    [CarryForwardFlag]           INT              NULL,
    [ValidationDaysBack]         INT              NULL,
    [ParameterTemplateID]        INT              NULL,
    [GasAnalysisSourceID]        INT              NULL,
    [GasAnalysisSourceType]      INT              NULL,
    [GatheringSystemID]          INT              NULL,
    [RouteID]                    INT              NULL,
    [MonthlyDataSourceFlag]      INT              NULL,
    [ProductionID]               VARCHAR (20)     NULL,
    [EngineeringID]              VARCHAR (20)     NULL,
    [AccountingID]               VARCHAR (30)     NULL,
    [StandardMeterID]            VARCHAR (30)     NULL,
    [PurchaserMeterID]           VARCHAR (30)     NULL,
    [IntegratorMeterID]          VARCHAR (30)     NULL,
    [OperatorMeterID]            VARCHAR (30)     NULL,
    [TransporterID]              VARCHAR (30)     NULL,
    [GathererID]                 VARCHAR (30)     NULL,
    [ScadaID]                    VARCHAR (30)     NULL,
    [LocationID]                 VARCHAR (30)     NULL,
    [AccountingTeamID]           INT              NULL,
    [DrillingTeamID]             INT              NULL,
    [ProductionTeamID]           INT              NULL,
    [GroupID]                    INT              NULL,
    [DivisionID]                 INT              NULL,
    [FieldGroupID]               INT              NULL,
    [AreaID]                     INT              NULL,
    [PlatformID]                 INT              NULL,
    [BatteryID]                  INT              NULL,
    [LeaseID]                    INT              NULL,
    [PlantID]                    INT              NULL,
    [StateID]                    INT              NULL,
    [CountyID]                   INT              NULL,
    [AllocationGroupID]          INT              NULL,
    [AccountingUploadFlag]       INT              NULL,
    [EngineeringUploadFlag]      INT              NULL,
    [SuperPersonID]              INT              NULL,
    [ForemanPersonID]            INT              NULL,
    [PumperPersonID]             INT              NULL,
    [EngineerPersonID]           INT              NULL,
    [AccountantPersonID]         INT              NULL,
    [MeterOperatorBEID]          INT              NULL,
    [MeterOperatorBELoc]         INT              NULL,
    [IntegratorBEID]             INT              NULL,
    [IntegratorBELoc]            INT              NULL,
    [PurchaserBEID]              INT              NULL,
    [PurchaserBELoc]             INT              NULL,
    [TransporterBEID]            INT              NULL,
    [TransporterBELoc]           INT              NULL,
    [GathererBEID]               INT              NULL,
    [GathererBELoc]              INT              NULL,
    [ManufacturerBEID]           INT              NULL,
    [SerialNumber]               VARCHAR (20)     NULL,
    [SKUNumber]                  VARCHAR (20)     NULL,
    [ModelNumber]                VARCHAR (20)     NULL,
    [Make]                       VARCHAR (20)     NULL,
    [Section]                    VARCHAR (12)     NULL,
    [Range]                      VARCHAR (12)     NULL,
    [Survey]                     VARCHAR (12)     NULL,
    [Block]                      VARCHAR (12)     NULL,
    [Latitude]                   VARCHAR (12)     NULL,
    [Longitude]                  VARCHAR (12)     NULL,
    [Township]                   VARCHAR (40)     NULL,
    [RegionArea]                 VARCHAR (12)     NULL,
    [SealRequiredFlag]           INT              NULL,
    [ActiveFlag]                 INT              NULL,
    [StartActiveDate]            DATETIME         NULL,
    [EndActiveDate]              DATETIME         NULL,
    [DeleteFlag]                 INT              NULL,
    [TemplateRecordFlag]         INT              NULL,
    [TemplateRecordUsed]         INT              NULL,
    [AllocationRunTwiceDaily]    INT              NULL,
    [AllocationRunTwiceMonthly]  INT              NULL,
    [AllocateUsingFixedVolFlag]  INT              NULL,
    [AllocationReportComment]    VARCHAR (200)    NULL,
    [AllocationDailyComment]     VARCHAR (500)    NULL,
    [AllocationMonthlyComment]   VARCHAR (500)    NULL,
    [SetupComments]              VARCHAR (500)    NULL,
    [PumperInstructions]         VARCHAR (500)    NULL,
    [MeterChildCount]            INT              NULL,
    [UserNumber1]                FLOAT (53)       NULL,
    [UserNumber1Label]           VARCHAR (30)     NULL,
    [UserNumber2]                FLOAT (53)       NULL,
    [UserNumber2Label]           VARCHAR (30)     NULL,
    [UserNumber3]                FLOAT (53)       NULL,
    [UserNumber3Label]           VARCHAR (30)     NULL,
    [UserNumber4]                FLOAT (53)       NULL,
    [UserNumber4Label]           VARCHAR (30)     NULL,
    [UserNumber5]                FLOAT (53)       NULL,
    [UserNumber5Label]           VARCHAR (30)     NULL,
    [UserNumber6]                FLOAT (53)       NULL,
    [UserNumber6Label]           VARCHAR (30)     NULL,
    [UserStringA]                VARCHAR (100)    NULL,
    [UserStringALabel]           VARCHAR (30)     NULL,
    [UserStringB]                VARCHAR (100)    NULL,
    [UserStringBLabel]           VARCHAR (30)     NULL,
    [UserStringC]                VARCHAR (100)    NULL,
    [UserStringCLabel]           VARCHAR (30)     NULL,
    [UserStringD]                VARCHAR (100)    NULL,
    [UserStringDLabel]           VARCHAR (30)     NULL,
    [UserStringE]                VARCHAR (100)    NULL,
    [UserStringELabel]           VARCHAR (30)     NULL,
    [UserStringF]                VARCHAR (100)    NULL,
    [UserStringFLabel]           VARCHAR (30)     NULL,
    [MmsFmpNumber]               VARCHAR (20)     NULL,
    [MmsGasPlantNumber]          VARCHAR (20)     NULL,
    [StatePlantNumber]           VARCHAR (20)     NULL,
    [StatePointOfDisposition]    VARCHAR (20)     NULL,
    [StateFilingFlag]            INT              NULL,
    [RegulatoryFieldID]          INT              NULL,
    [RegulatoryFacilityID]       VARCHAR (20)     NULL,
    [RegulatoryFacilityType]     VARCHAR (20)     NULL,
    [RegulatoryFacilityLongID]   VARCHAR (20)     NULL,
    [HoursOnDefaultFlag]         INT              NULL,
    [StartDate]                  DATETIME         NULL,
    [EndDate]                    DATETIME         NULL,
    [InternalReferenceNumber]    VARCHAR (20)     NULL,
    [PrintFlag]                  INT              NULL,
    [DateTimeStamp]              DATETIME         NULL,
    [SystemMessage]              VARCHAR (80)     NULL,
    [CleanupDateStamp]           DATETIME         NULL,
    [CleanupTimeStamp]           CHAR (8)         NULL,
    [LastTransmission]           INT              NULL,
    [LastLoadDate]               DATETIME         NULL,
    [LastLoadTime]               CHAR (8)         NULL,
    [TransmitFlag]               INT              NULL,
    [RecordCreationDate]         DATETIME         NULL,
    [BLogicDateStamp]            DATETIME         NULL,
    [BLogicTimeStamp]            CHAR (8)         NULL,
    [UserDateStamp]              DATETIME         NULL,
    [UserTimeStamp]              CHAR (8)         NULL,
    [UserID]                     INT              NULL,
    [CalculationStatusFlag]      INT              NOT NULL,
    [LocationMerrickID]          INT              NULL,
    [LocationOrder]              INT              NULL,
    [FacilityID]                 INT              NULL,
    [TerminalID]                 INT              NULL,
    [PipelineID]                 INT              NULL,
    [BTUCopyFlag]                INT              NOT NULL,
    [AccountingTransportMeterID] VARCHAR (30)     NULL,
    [RowUID]                     UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_MeterTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC)
);

