CREATE TABLE [dbo].[MeterAllocationTypeTb] (
    [AllocationType]              INT              NOT NULL,
    [AllocationName]              VARCHAR (50)     NULL,
    [Description]                 VARCHAR (500)    NULL,
    [ActiveFlag]                  INT              NULL,
    [s_MeterType]                 INT              NULL,
    [s_MeasurementPointRole]      INT              NULL,
    [s_ProductCode]               INT              NULL,
    [s_ProductType]               INT              NULL,
    [s_DispositionCode]           INT              NULL,
    [s_HoursOnTotal24Flag]        INT              NULL,
    [s_MeterCalculationFlag]      INT              NULL,
    [s_IgnoreBSWVolumeFlag]       INT              NULL,
    [s_MonthlyDataSourceFlag]     INT              NULL,
    [s_UnitsTypeFlag]             INT              NULL,
    [s_ProrationCalcFlag]         INT              NULL,
    [s_AllocateUsingFixedVolFlag] INT              NULL,
    [s_CarryForwardFlag]          INT              NULL,
    [d_AllocationMethod]          INT              NULL,
    [d_AllocationMethodUpstream]  INT              NULL,
    [d_AllocatedVolumeSource]     INT              NULL,
    [d_ProrateUsingFuelUseFlag]   INT              NULL,
    [d_VolumeBasisFlag]           INT              NULL,
    [d_VolumeAutoPopFlag]         INT              NULL,
    [d_InjectionMeasPointFlag]    INT              NULL,
    [d_PhysicalMeterFlag]         INT              NULL,
    [d_PressureClassification]    INT              NULL,
    [d_AllocationFactor]          FLOAT (53)       NULL,
    [d_AllocationFactorType]      INT              NULL,
    [d_AllocationFactor2]         FLOAT (53)       NULL,
    [d_AllocationFactorType2]     INT              NULL,
    [d_AllocationFactor3]         FLOAT (53)       NULL,
    [d_AllocationFactorType3]     INT              NULL,
    [d_AllocationFactor4]         FLOAT (53)       NULL,
    [d_AllocationFactorType4]     INT              NULL,
    [d_AllocationFactor5]         FLOAT (53)       NULL,
    [d_AllocationFactorType5]     INT              NULL,
    [d_AllocationFactor6]         FLOAT (53)       NULL,
    [d_AllocationFactorType6]     INT              NULL,
    [d_AllocationFactor7]         FLOAT (53)       NULL,
    [d_AllocationFactorType7]     INT              NULL,
    [d_AllocationFactor8]         FLOAT (53)       NULL,
    [d_AllocationFactorType8]     INT              NULL,
    [d_EquipAllocFactor]          FLOAT (53)       NULL,
    [d_EquipAllocFactorType]      INT              NULL,
    [d_EquipAllocFactor2]         FLOAT (53)       NULL,
    [d_EquipAllocFactorType2]     INT              NULL,
    [d_EquipAllocFactor3]         FLOAT (53)       NULL,
    [d_EquipAllocFactorType3]     INT              NULL,
    [d_EquipAllocFactor4]         FLOAT (53)       NULL,
    [d_EquipAllocFactorType4]     INT              NULL,
    [m_AllocationMethod]          INT              NULL,
    [m_AllocationMethodUpstream]  INT              NULL,
    [m_AllocatedVolumeSource]     INT              NULL,
    [m_ProrateUsingFuelUseFlag]   INT              NULL,
    [m_VolumeBasisFlag]           INT              NULL,
    [m_InjectionMeasPointFlag]    INT              NULL,
    [m_PhysicalMeterFlag]         INT              NULL,
    [m_PressureClassification]    INT              NULL,
    [m_ActualVolumeAutoPopFlag]   INT              NULL,
    [m_AllocationFactor]          FLOAT (53)       NULL,
    [m_AllocationFactorType]      INT              NULL,
    [m_AllocationFactor2]         FLOAT (53)       NULL,
    [m_AllocationFactorType2]     INT              NULL,
    [m_AllocationFactor3]         FLOAT (53)       NULL,
    [m_AllocationFactorType3]     INT              NULL,
    [m_AllocationFactor4]         FLOAT (53)       NULL,
    [m_AllocationFactorType4]     INT              NULL,
    [m_AllocationFactor5]         FLOAT (53)       NULL,
    [m_AllocationFactorType5]     INT              NULL,
    [m_AllocationFactor6]         FLOAT (53)       NULL,
    [m_AllocationFactorType6]     INT              NULL,
    [m_AllocationFactor7]         FLOAT (53)       NULL,
    [m_AllocationFactorType7]     INT              NULL,
    [m_AllocationFactor8]         FLOAT (53)       NULL,
    [m_AllocationFactorType8]     INT              NULL,
    [m_EquipAllocFactor]          FLOAT (53)       NULL,
    [m_EquipAllocFactorType]      INT              NULL,
    [m_EquipAllocFactor2]         FLOAT (53)       NULL,
    [m_EquipAllocFactorType2]     INT              NULL,
    [m_EquipAllocFactor3]         FLOAT (53)       NULL,
    [m_EquipAllocFactorType3]     INT              NULL,
    [m_EquipAllocFactor4]         FLOAT (53)       NULL,
    [m_EquipAllocFactorType4]     INT              NULL,
    [s_HoursOnDefaultFlag]        INT              NULL,
    [UserDateStamp]               DATETIME         NULL,
    [UserTimeStamp]               CHAR (8)         NULL,
    [UserID]                      INT              NULL,
    [RowUID]                      UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_MeterAllocationTypeTb] PRIMARY KEY CLUSTERED ([AllocationType] ASC)
);

