CREATE TABLE [dbo].[MeterMonthlyTb] (
    [MerrickID]                  INT              NOT NULL,
    [RecordDate]                 DATETIME         NOT NULL,
    [StartDate]                  DATETIME         NULL,
    [EndDate]                    DATETIME         NULL,
    [ProductCode]                INT              NULL,
    [ProductType]                INT              NULL,
    [DispositionCode]            INT              NULL,
    [DataSourceCode]             INT              NULL,
    [DaysOn]                     FLOAT (53)       NULL,
    [TotalHoursFlowed]           FLOAT (53)       NULL,
    [TotalDownTimeHours]         FLOAT (53)       NULL,
    [ActBTUFactor]               FLOAT (53)       NULL,
    [ActTemperature]             FLOAT (53)       NULL,
    [ActPressureBase]            FLOAT (53)       NULL,
    [ActGravity]                 FLOAT (53)       NULL,
    [ActWetDryFlag]              INT              NULL,
    [ActOilVol]                  FLOAT (53)       NULL,
    [ActWaterVol]                FLOAT (53)       NULL,
    [ActGasVolMCF]               FLOAT (53)       NULL,
    [ActGasVolMMBTU]             FLOAT (53)       NULL,
    [ActSulfurMass]              FLOAT (53)       NULL,
    [ActNGLVol]                  FLOAT (53)       NULL,
    [ActCO2Vol]                  FLOAT (53)       NULL,
    [ActCO2Mass]                 FLOAT (53)       NULL,
    [ActOtherVol]                FLOAT (53)       NULL,
    [ConvActBTUFactor]           FLOAT (53)       NULL,
    [ConvActTemperature]         FLOAT (53)       NULL,
    [ConvActPressureBase]        FLOAT (53)       NULL,
    [ConvActGravity]             FLOAT (53)       NULL,
    [ConvActWetDryFlag]          INT              NULL,
    [ConvActOilVol]              FLOAT (53)       NULL,
    [ConvActWaterVol]            FLOAT (53)       NULL,
    [ConvActGasVolMCF]           FLOAT (53)       NULL,
    [ConvActGasVolMMBTU]         FLOAT (53)       NULL,
    [ConvActCO2Vol]              FLOAT (53)       NULL,
    [ConvActOtherVol]            FLOAT (53)       NULL,
    [AllocBTUFactor]             FLOAT (53)       NULL,
    [AllocTemperature]           FLOAT (53)       NULL,
    [AllocPressureBase]          FLOAT (53)       NULL,
    [AllocGravity]               FLOAT (53)       NULL,
    [AllocWetDryFlag]            INT              NULL,
    [AllocOilVol]                FLOAT (53)       NULL,
    [AllocWaterVol]              FLOAT (53)       NULL,
    [AllocGasVolMCF]             FLOAT (53)       NULL,
    [AllocGasVolMMBTU]           FLOAT (53)       NULL,
    [AllocPlantGasMCF]           FLOAT (53)       NULL,
    [AllocPlantGasMMBTU]         FLOAT (53)       NULL,
    [AllocCO2Vol]                FLOAT (53)       NULL,
    [AllocCO2Mass]               FLOAT (53)       NULL,
    [AllocOtherVol]              FLOAT (53)       NULL,
    [DailyAllocBTUFactor]        FLOAT (53)       NULL,
    [DailyAllocTemperature]      FLOAT (53)       NULL,
    [DailyAllocPressureBase]     FLOAT (53)       NULL,
    [DailyAllocGravity]          FLOAT (53)       NULL,
    [DailyAllocWetDryFlag]       INT              NULL,
    [DailyAllocOilVol]           FLOAT (53)       NULL,
    [DailyAllocWaterVol]         FLOAT (53)       NULL,
    [DailyAllocGasVolMCF]        FLOAT (53)       NULL,
    [DailyAllocGasVolMMBTU]      FLOAT (53)       NULL,
    [DailyAllocPlantGasMCF]      FLOAT (53)       NULL,
    [DailyAllocPlantGasMMBTU]    FLOAT (53)       NULL,
    [DailyAllocCO2Vol]           FLOAT (53)       NULL,
    [DailyAllocOtherVol]         FLOAT (53)       NULL,
    [EstBTUFactor]               FLOAT (53)       NULL,
    [EstTemperature]             FLOAT (53)       NULL,
    [EstPressureBase]            FLOAT (53)       NULL,
    [EstGravity]                 FLOAT (53)       NULL,
    [EstWetDryFlag]              INT              NULL,
    [EstOilVol]                  FLOAT (53)       NULL,
    [EstWaterVol]                FLOAT (53)       NULL,
    [EstGasVolMCF]               FLOAT (53)       NULL,
    [EstGasVolMMBTU]             FLOAT (53)       NULL,
    [EstCO2Vol]                  FLOAT (53)       NULL,
    [EstCO2Mass]                 FLOAT (53)       NULL,
    [EstOtherVol]                FLOAT (53)       NULL,
    [FuelUseGasVolMCF]           FLOAT (53)       NULL,
    [FuelUseGasVolMMBTU]         FLOAT (53)       NULL,
    [FuelUseOilVol]              FLOAT (53)       NULL,
    [FuelUseOtherVol]            FLOAT (53)       NULL,
    [AllocationComment]          VARCHAR (200)    NULL,
    [AllocationMethod]           INT              NULL,
    [AllocationMethodUpstream]   INT              NULL,
    [AllocatedVolumeSource]      INT              NULL,
    [AllocationOrder]            INT              NULL,
    [AllocationByComponent]      INT              NULL,
    [ProrateUsingFuelUseFlag]    INT              NULL,
    [VolumeBasisFlag]            INT              NULL,
    [InjectionMeasPointFlag]     INT              NULL,
    [PhysicalMeterFlag]          INT              NULL,
    [PressureClassification]     INT              NULL,
    [ActualVolumeAutoPopFlag]    INT              NULL,
    [ErrorCorrectionFactor]      FLOAT (53)       NULL,
    [MeterAdjustmentFactor]      FLOAT (53)       NULL,
    [FixedVolumeFlagOil]         INT              NULL,
    [FixedVolumeFlagGas]         INT              NULL,
    [FixedVolumeFlagWater]       INT              NULL,
    [FactorComputationFlag]      INT              NULL,
    [AllocationFactor]           FLOAT (53)       NULL,
    [AllocationFactorType]       INT              NULL,
    [AllocationFactorComment]    VARCHAR (20)     NULL,
    [AllocationFactor2]          FLOAT (53)       NULL,
    [AllocationFactorType2]      INT              NULL,
    [AllocationFactorComment2]   VARCHAR (20)     NULL,
    [AllocationFactor3]          FLOAT (53)       NULL,
    [AllocationFactorType3]      INT              NULL,
    [AllocationFactorComment3]   VARCHAR (20)     NULL,
    [AllocationFactor4]          FLOAT (53)       NULL,
    [AllocationFactorType4]      INT              NULL,
    [AllocationFactorComment4]   VARCHAR (20)     NULL,
    [AllocationFactor5]          FLOAT (53)       NULL,
    [AllocationFactorType5]      INT              NULL,
    [AllocationFactor6]          FLOAT (53)       NULL,
    [AllocationFactorType6]      INT              NULL,
    [AllocationFactor7]          FLOAT (53)       NULL,
    [AllocationFactorType7]      INT              NULL,
    [AllocationFactor8]          FLOAT (53)       NULL,
    [AllocationFactorType8]      INT              NULL,
    [EquipAllocFactor]           FLOAT (53)       NULL,
    [EquipAllocFactorType]       INT              NULL,
    [EquipAllocFactorComment]    VARCHAR (20)     NULL,
    [EquipAllocFactor2]          FLOAT (53)       NULL,
    [EquipAllocFactorType2]      INT              NULL,
    [EquipAllocFactorComment2]   VARCHAR (20)     NULL,
    [EquipAllocFactor3]          FLOAT (53)       NULL,
    [EquipAllocFactorType3]      INT              NULL,
    [EquipAllocFactor4]          FLOAT (53)       NULL,
    [EquipAllocFactorType4]      INT              NULL,
    [OpenOdometer]               FLOAT (53)       NULL,
    [CloseOdometer]              FLOAT (53)       NULL,
    [LactOpenDate]               DATETIME         NULL,
    [LactOpenTime]               CHAR (8)         NULL,
    [LactCloseDate]              DATETIME         NULL,
    [LactCloseTime]              CHAR (8)         NULL,
    [BSAndW]                     FLOAT (53)       NULL,
    [OpenTemperature]            FLOAT (53)       NULL,
    [CloseTemperature]           FLOAT (53)       NULL,
    [ObservedTemperature]        FLOAT (53)       NULL,
    [ActualGravity]              FLOAT (53)       NULL,
    [ConvertedGravity]           FLOAT (53)       NULL,
    [GrossBarrels]               FLOAT (53)       NULL,
    [NetBarrels]                 FLOAT (53)       NULL,
    [LactMeterFactor]            FLOAT (53)       NULL,
    [LactCompressibilityFactor]  FLOAT (53)       NULL,
    [LactDensityCorrection]      FLOAT (53)       NULL,
    [OdometerResetFlag]          INT              NULL,
    [UnitsFlag]                  INT              NULL,
    [ShrinkageFactor]            FLOAT (53)       NULL,
    [GasEquivalentFactor]        FLOAT (53)       NULL,
    [OilPipelineVol]             FLOAT (53)       NULL,
    [MeterType]                  INT              NULL,
    [MeasurementPointRole]       INT              NULL,
    [PurchaserMeterID]           VARCHAR (30)     NULL,
    [IntegratorMeterID]          VARCHAR (30)     NULL,
    [MonthlyDataSourceFlag]      INT              NULL,
    [GatheringSystemID]          INT              NULL,
    [CheckMeterMerrickId]        INT              NULL,
    [TransporterID]              VARCHAR (30)     NULL,
    [GathererID]                 VARCHAR (30)     NULL,
    [MeterOperatorBEID]          INT              NULL,
    [MeterOperatorBELoc]         INT              NULL,
    [IntegratorBEID]             INT              NULL,
    [IntegratorBELoc]            INT              NULL,
    [PurchaserBEID]              INT              NULL,
    [PurchaserBELoc]             INT              NULL,
    [TransporterBEID]            INT              NULL,
    [TransporterBELoc]           INT              NULL,
    [GathererBEID]               INT              NULL,
    [GathererBELoc]              INT              NULL,
    [AccountingTeamID]           INT              NULL,
    [DrillingTeamID]             INT              NULL,
    [ProductionTeamID]           INT              NULL,
    [GroupID]                    INT              NULL,
    [DivisionID]                 INT              NULL,
    [FieldGroupID]               INT              NULL,
    [AreaID]                     INT              NULL,
    [PlatformID]                 INT              NULL,
    [BatteryID]                  INT              NULL,
    [SuperPersonID]              INT              NULL,
    [ForemanPersonID]            INT              NULL,
    [PumperPersonID]             INT              NULL,
    [AccountantPersonID]         INT              NULL,
    [TotalRunsPumperEntered]     INT              NULL,
    [TotalRunsHaulerEntered]     INT              NULL,
    [AllocOilProd]               FLOAT (53)       NULL,
    [AllocWaterProd]             FLOAT (53)       NULL,
    [ErrorCorrectionFactorDaily] FLOAT (53)       NULL,
    [ThirdPartyMeterID]          VARCHAR (30)     NULL,
    [AllocationFactorAutoFlag]   INT              NULL,
    [EquipAllocFactorAutoFlag]   INT              NULL,
    [EquipmentFuelUsageFlag]     INT              NULL,
    [BTUValue]                   FLOAT (53)       NULL,
    [PlateSize]                  FLOAT (53)       NULL,
    [SpringSize]                 CHAR (8)         NULL,
    [LinearCoefficient]          FLOAT (53)       NULL,
    [ProrationFactor]            FLOAT (53)       NULL,
    [Operator]                   INT              NULL,
    [ActiveFlag]                 INT              NULL,
    [SummationFlag]              INT              NULL,
    [BackgroundTaskFlag]         INT              NULL,
    [LastTransmission]           INT              NULL,
    [LastLoadDate]               DATETIME         NULL,
    [LastLoadTime]               CHAR (8)         NULL,
    [TransmitFlag]               INT              NULL,
    [DateTimeStamp]              DATETIME         NULL,
    [BLogicDateStamp]            DATETIME         NULL,
    [BLogicTimeStamp]            CHAR (8)         NULL,
    [AllocationDateStamp]        DATETIME         NULL,
    [AllocationTimeStamp]        CHAR (8)         NULL,
    [UserDateStamp]              DATETIME         NULL,
    [UserTimeStamp]              CHAR (8)         NULL,
    [UserID]                     INT              NULL,
    [ActMass]                    FLOAT (53)       NOT NULL,
    [CalculationStatusFlag]      INT              NOT NULL,
    [LoadTransferFlag]           INT              NULL,
    [RowUID]                     UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_MeterMonthlyTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC, [RecordDate] ASC)
);

