CREATE TABLE [dbo].[ProducingMethodsTb] (
    [ProducingMethodsMerrickID]   INT          NOT NULL,
    [ProducingMethodsDescription] VARCHAR (50) NULL,
    [ProducingMethodsShort]       VARCHAR (6)  NULL,
    [ActiveFlag]                  INT          NULL,
    [HoursOnTotal24Flag]          INT          NULL,
    [AccountingID]                VARCHAR (10) NULL,
    [EngineeringID]               VARCHAR (10) NULL,
    [ProductionID]                VARCHAR (10) NULL,
    [RioMethodCode]               INT          NULL,
    [EntryScreenType]             INT          NOT NULL,
    [CaliforniaStateCode]         VARCHAR (10) NULL,
    [NewMexicoStateCode]          VARCHAR (10) NULL,
    [LouisianaWellTestCode]       VARCHAR (10) NULL,
    [ColoradoStateCode]           VARCHAR (10) NULL,
    [NorthDakotaStateCode]        VARCHAR (10) NULL,
    [SouthDakotaStateCode]        VARCHAR (10) NULL,
    [MississippiStateCode]        VARCHAR (10) NULL,
    [ArkansasStateCode]           VARCHAR (10) NULL,
    [UtahStateCode]               VARCHAR (10) NULL,
    [MichiganStateCode]           VARCHAR (10) NULL,
    [TexasStateCode]              VARCHAR (10) NULL,
    [DateTimeStamp]               DATETIME     NULL,
    [UserDateStamp]               DATETIME     NULL,
    [UserTimeStamp]               CHAR (8)     NULL,
    [UserID]                      INT          NULL,
    CONSTRAINT [PK_ProducingMethodsTb] PRIMARY KEY CLUSTERED ([ProducingMethodsMerrickID] ASC)
);

