CREATE TABLE [dbo].[TankCompletionDailyTb] (
    [TankID]                       INT        NOT NULL,
    [WellID]                       INT        NOT NULL,
    [RecordDate]                   DATETIME   NOT NULL,
    [FirstDayFlag]                 INT        NULL,
    [BeginningNGL]                 FLOAT (53) NULL,
    [EndingNGL]                    FLOAT (53) NULL,
    [ProductionNGL]                FLOAT (53) NULL,
    [DispositionNGL]               FLOAT (53) NULL,
    [BeginningOil]                 FLOAT (53) NULL,
    [BeginningWater]               FLOAT (53) NULL,
    [EndOil]                       FLOAT (53) NULL,
    [EndWater]                     FLOAT (53) NULL,
    [ProductionOil]                FLOAT (53) NULL,
    [ProductionWater]              FLOAT (53) NULL,
    [DispositionOil]               FLOAT (53) NULL,
    [DispositionWater]             FLOAT (53) NULL,
    [ProductionFactorOil]          FLOAT (53) NULL,
    [DispositionFactorOil]         FLOAT (53) NULL,
    [ProductionFactorWater]        FLOAT (53) NULL,
    [DispositionFactorWater]       FLOAT (53) NULL,
    [ProductionAllocationType]     INT        NULL,
    [DispositionAllocationType]    INT        NULL,
    [DispositionAllocationFactor]  FLOAT (53) NULL,
    [ProductionAllocationFactor]   FLOAT (53) NULL,
    [DateTimeStamp]                DATETIME   NULL,
    [AllocationDateStamp]          DATETIME   NULL,
    [AllocationTimeStamp]          CHAR (8)   NULL,
    [UserDateStamp]                DATETIME   NULL,
    [UserTimeStamp]                CHAR (8)   NULL,
    [UserID]                       INT        NULL,
    [LoadTransferFlag]             INT        NOT NULL,
    [EndingInventoryDestinationID] INT        NOT NULL,
    [TankTransferSourceID]         INT        NOT NULL,
    CONSTRAINT [PK_TankCompletionDailyTb] PRIMARY KEY CLUSTERED ([TankID] ASC, [WellID] ASC, [RecordDate] ASC, [TankTransferSourceID] ASC)
);

