CREATE TABLE [dbo].[TankDailyTb] (
    [MerrickID]                INT              NOT NULL,
    [RecordDate]               DATETIME         NOT NULL,
    [FirstDayFlag]             INT              NULL,
    [ProductCode]              INT              NULL,
    [ProductType]              INT              NULL,
    [DataSourceCode]           INT              NULL,
    [AllocationMethod]         INT              NULL,
    [AllocationOrder]          INT              NULL,
    [TankDataEntryFlag]        INT              NULL,
    [ErrorNumber]              INT              NULL,
    [AllocationByComponent]    INT              NULL,
    [GasEquivalentFactor]      FLOAT (53)       NULL,
    [BeginningNGL]             FLOAT (53)       NULL,
    [EndingNGL]                FLOAT (53)       NULL,
    [TotalRunsNGL]             FLOAT (53)       NULL,
    [ProductionNGL]            FLOAT (53)       NULL,
    [GaugePressure]            FLOAT (53)       NULL,
    [TankGaugeTime]            CHAR (8)         NULL,
    [GaugeHours]               FLOAT (53)       NULL,
    [GaugeTemperature]         FLOAT (53)       NULL,
    [ProductionDate]           DATETIME         NULL,
    [ProductionAllocDefault]   INT              NULL,
    [DispositionAllocDefault]  INT              NULL,
    [FactorComputationFlag]    INT              NULL,
    [TopFeet]                  INT              NULL,
    [TopInch]                  INT              NULL,
    [TopQuarter]               FLOAT (53)       NULL,
    [TopTotalInches]           FLOAT (53)       NULL,
    [BottomTotalInches]        FLOAT (53)       NULL,
    [BottomFeet]               INT              NULL,
    [BottomInch]               INT              NULL,
    [BottomQuarter]            FLOAT (53)       NULL,
    [BeginningOil]             FLOAT (53)       NULL,
    [BeginningWater]           FLOAT (53)       NULL,
    [EndingOil]                FLOAT (53)       NULL,
    [EndingWater]              FLOAT (53)       NULL,
    [TotalRunsOil]             FLOAT (53)       NULL,
    [TotalRunsWater]           FLOAT (53)       NULL,
    [ProductionWater]          FLOAT (53)       NULL,
    [ProductionOil]            FLOAT (53)       NULL,
    [TankCompBeginningOil]     FLOAT (53)       NULL,
    [TankCompBeginningWater]   FLOAT (53)       NULL,
    [ObservedTemperature]      FLOAT (53)       NULL,
    [ObservedGravity]          FLOAT (53)       NULL,
    [ConvertedGravity]         FLOAT (53)       NULL,
    [BSAndW]                   FLOAT (53)       NULL,
    [WaterCut]                 FLOAT (53)       NULL,
    [GrossBarrelsOil]          FLOAT (53)       NULL,
    [TemperatureFactor]        FLOAT (53)       NULL,
    [TankVaporFactor]          FLOAT (53)       NULL,
    [TankVaporVolume]          FLOAT (53)       NULL,
    [OilInventoryAdjustment]   FLOAT (53)       NULL,
    [WaterInventoryAdjustment] FLOAT (53)       NULL,
    [AdjustedProductionOil]    FLOAT (53)       NULL,
    [AdjustedProductionWater]  FLOAT (53)       NULL,
    [AdjustedBeginningOil]     FLOAT (53)       NULL,
    [AdjustedBeginningWater]   FLOAT (53)       NULL,
    [AdjustedEndingOil]        FLOAT (53)       NULL,
    [AdjustedEndingWater]      FLOAT (53)       NULL,
    [RateOil]                  FLOAT (53)       NULL,
    [RateWater]                FLOAT (53)       NULL,
    [OtherVolume]              FLOAT (53)       NULL,
    [TankIsolatedFlag]         INT              NULL,
    [DispositionCode]          INT              NULL,
    [CommentID]                INT              NULL,
    [StrappingDate]            DATETIME         NULL,
    [BackgroundTaskFlag]       INT              NULL,
    [LastTransmission]         INT              NULL,
    [LastLoadDate]             DATETIME         NULL,
    [LastLoadTime]             CHAR (8)         NULL,
    [TransmitFlag]             INT              NULL,
    [DateTimeStamp]            DATETIME         NULL,
    [BLogicDateStamp]          DATETIME         NULL,
    [BLogicTimeStamp]          CHAR (8)         NULL,
    [AllocationDateStamp]      DATETIME         NULL,
    [AllocationTimeStamp]      CHAR (8)         NULL,
    [UserDateStamp]            DATETIME         NULL,
    [UserTimeStamp]            CHAR (8)         NULL,
    [UserID]                   INT              NULL,
    [LoadTransferFlag]         INT              NOT NULL,
    [PercentFullNGL]           FLOAT (53)       NOT NULL,
    [GrossNGL]                 FLOAT (53)       NOT NULL,
    [CalculationStatusFlag]    INT              NOT NULL,
    [RowUID]                   UNIQUEIDENTIFIER NOT NULL,
    [GrossTotalRunsOil]        FLOAT (53)       NULL,
    [AmbientTemperature]       FLOAT (53)       NULL,
    CONSTRAINT [PK_TankDailyTb] PRIMARY KEY CLUSTERED ([MerrickID] ASC, [RecordDate] ASC)
);

