CREATE TABLE [Kingdom].[T_Well] (
    [ID]                   INT           NOT NULL,
    [Name]                 VARCHAR (255) NULL,
    [WellNumber]           VARCHAR (255) NULL,
    [SurfaceLocX]          FLOAT (53)    NULL,
    [SurfaceLocY]          FLOAT (53)    NULL,
    [KBElevation]          FLOAT (53)    NULL,
    [SurfaceElevation]     FLOAT (53)    NULL,
    [LoadFormat]           INT           NULL,
    [TotalDepth]           FLOAT (53)    NULL,
    [Latitude]             FLOAT (53)    NULL,
    [Longitude]            FLOAT (53)    NULL,
    [CompletionBoreholeID] INT           NULL,
    [CountyId]             INT           NULL,
    [StateId]              INT           NULL,
    [CountryId]            INT           NULL,
    [DFElevation]          FLOAT (53)    NULL,
    [ReferenceElevation]   FLOAT (53)    NULL,
    [Label]                VARCHAR (255) NULL,
    [CreateDate]           DATETIME2 (7) NULL,
    [CreateBy]             VARCHAR (255) NULL,
    [LastModifyDate]       DATETIME2 (7) NULL,
    [LastModifyBy]         VARCHAR (255) NULL,
    [RealKBElevation]      FLOAT (53)    NULL,
    [CreateByID]           INT           NULL,
    [LastModifyByID]       INT           NULL,
    CONSTRAINT [Well_N] PRIMARY KEY CLUSTERED ([ID] ASC)
);

