CREATE TABLE [RL].[Log] (
    [RequisitionID]                    INT            IDENTITY (1, 1) NOT NULL,
    [ScopeOfWork]                      VARCHAR (1000) NULL,
    [PotentialVendors]                 VARCHAR (200)  NULL,
    [StartDateEst]                     DATETIME       NULL,
    [EndDateEst]                       DATETIME       NULL,
    [DurationEst]                      VARCHAR (200)  NULL,
    [ContractValueEst]                 VARCHAR (200)  NULL,
    [Note]                             VARCHAR (1000) NULL,
    [MajorFabricationConstructionFlag] VARCHAR (1)    NULL,
    [MinorFabricationConstructionFlag] VARCHAR (1)    NULL,
    [HeavyLiftFlag]                    VARCHAR (1)    NULL,
    [HazmatFlag]                       VARCHAR (1)    NULL,
    [MarineFlag]                       VARCHAR (1)    NULL,
    [AviationFlag]                     VARCHAR (1)    NULL,
    [PurchaseFlag]                     VARCHAR (1)    NULL,
    [SpecialConstructionFlag]          VARCHAR (1)    NULL,
    [EngConsultFlag]                   VARCHAR (1)    NULL,
    [ConfidentialityFlag]              VARCHAR (1)    NULL,
    [BudgetedFlag]                     VARCHAR (1)    NULL,
    [NewAgreementFlag]                 VARCHAR (1)    NULL,
    [StatusID]                         INT            NULL,
    [WorkLocationID]                   INT            NULL,
    [ContractOwnerID]                  INT            NULL,
    [SiteProjectID]                    INT            NULL,
    [DisciplineID]                     INT            NULL,
    [AgreementTypeID]                  INT            NULL,
    [CreatedDate]                      DATETIME       NULL,
    [CreatedBy]                        VARCHAR (50)   NULL,
    [ClosedDate]                       DATETIME       NULL,
    [ClosedBy]                         VARCHAR (50)   NULL,
    [ModifiedDate]                     DATETIME       NULL,
    [ModifiedBy]                       VARCHAR (50)   NULL,
    PRIMARY KEY CLUSTERED ([RequisitionID] ASC)
);

