CREATE TABLE [ARIES].[BRIX_SQL_ARGRAPHCURVE_BKP] (
    [GRAPHNAME] VARCHAR (32) NULL,
    [CURVENAME] VARCHAR (32) NULL,
    [USEIF]     VARCHAR (32) NULL,
    [CUM]       SMALLINT     NULL,
    [POSITION]  SMALLINT     NULL,
    [GRIDPOS]   SMALLINT     NULL,
    [OWNER]     VARCHAR (32) NULL
);

