CREATE TABLE [ARIES].[DI_Header_STG] (
    [ENTITYID] INT          NULL,
    [API]      VARCHAR (14) NULL,
    [PROPNUM]  VARCHAR (12) NULL,
    [API10]    VARCHAR (10) NULL,
    [STATE]    VARCHAR (50) NULL
);

