CREATE TABLE [ARIES].[IHS_Header_STG] (
    [ENTITYID] VARCHAR (23) NULL,
    [API]      VARCHAR (14) NULL,
    [PROPNUM]  VARCHAR (12) NULL,
    [API10]    VARCHAR (10) NULL,
    [STATE]    VARCHAR (50) NULL
);

