
/******************************
** Name:  vw_UC_AC_PROP_WithRefPlayNames
** Desc:  View used to populate the upstream table UV_AC_PRODUCT_AT
** Auth:  Aaron Vogt
** Date:  03/03/2020
**************************
** Change History
**************************
** PR   Date         Author    Description 
** --   ----------   -------   ------------------------------------
** 1    03/03/2020   Aaron V   Object creation
*******************************/
CREATE VIEW [Upstream].[vw_UC_AC_PROP_WithRefPlayNames]
	AS 
SELECT 
		prop.[UWI]
      ,prop.[RecordSource]
      ,prop.[LoadDate]
      ,prop.[SOURCE]
      ,prop.[API_NUMBER]
      ,prop.[OPERATOR_NAME]
      ,prop.[REGULATORY_API]
      ,prop.[CURRENT_OPERATOR_NAME]
      ,prop.[LEASE_NAME]
      ,prop.[WELL_NUMBER]
      ,prop.[FIELD_NAME]
      ,prop.[COUNTRY_NAME]
      ,prop.[STATE_NAME]
      ,prop.[COUNTY_NAME]
      ,prop.[HOLE_DIRECTION]
      ,prop.[WELL_STATUS]
      ,prop.[CURRENT_STATUS]
      ,prop.[BASIN]
      ,prop.[PLAY_NAME]
      ,play.New_Play AS [TPC_PLAY_NAME]
      ,prop.[PLAY_TYPE]
      ,prop.[PERMIT_DATE]
      ,prop.[DEPTH_TOTAL_DRILLER]
      ,prop.[DEPTH_TOTAL_LOGGER]
      ,prop.[DEPTH_TRUE_VERTICAL]
      ,prop.[DEPTH_WHIPSTOCK]
      ,prop.[STATUS_FINAL_CODE]
      ,prop.[FORMATION_PROJECTED_NAME]
      ,prop.[DEPTH_TOTAL_PROJECTED]
      ,prop.[FORMATION_AT_TD_NAME]
      ,prop.[PRODFIT_FORMATION_AT_TD_NAME]
      ,prop.[FORMATION_PRODUCING_NAME]
      ,prop.[PRODFIT_TOP_PRODUCING_FORMATION]
      ,prop.[PRODFIT_BASE_PRODUCING_FORMATION]
      ,prop.[PRODFIT_80_DEGREE_HEEL_PT_FORM]
      ,prop.[GROUND_ELEVATION]
      ,prop.[DATE_SPUD]
      ,prop.[DATE_COMPLETION]
      ,prop.[DATE_RIG_RELEASE]
      ,prop.[DATE_ABANDONMENT]
      ,prop.[DATE_LAST_ACTIVITY]
      ,prop.[SURFACE_LATITUDE]
      ,prop.[SURFACE_LONGITUDE]
      ,prop.[BH_LATITUDE]
      ,prop.[BH_LONGITUDE]
      ,prop.[RECORD_CREATION_DATE]
      ,prop.[RECORD_UPDATE_DATE]
      ,prop.[DEPTH_TOP]
      ,prop.[DEPTH_BASE]
      ,prop.[LAT_LEN_HORIZ_DISPLACEMENT_FT]
      ,prop.[LAT_LEN_GROSS_PERF_INTVL]
      ,prop.[NUM_FRAC_STAGES]
      ,prop.[NUM_TREATMENT_RECORDS]
      ,prop.[PROPPANT_SAND_LBS]
      ,prop.[PROPPANT_RESIN_COATED_SAND_LBS]
      ,prop.[PROPPANT_CERAMIC_LBS]
      ,prop.[PROPPANT_RESIN_COATED_CERAMIC_LBS]
      ,prop.[PROPPAND_SAND_CERAMIC_LBS]
      ,prop.[PROPPANT_SAND_RESIN_COATED_CERAMIC_LBS]
      ,prop.[PROPPANT_SAND_CERAMIC_RESIN_COATED_SAND_LBS]
      ,prop.[PROPPANT_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS]
      ,prop.[PROPPANT_SAND_RESIN_COATED_SAND_CERAMIC_RESIN_COATED_CERAMIC_LBS]
      ,prop.[PROPPANT_BAUXITE_LBS]
      ,prop.[PROPPANT_WALNUT_LBS]
      ,prop.[PROPPANT_MARBLE_LBS]
      ,prop.[PROPPANT_GRAVEL_LBS]
      ,prop.[PROPPANT_SAND_BAUXITE_CERAMIC_LBS]
      ,prop.[PROPPANT_OTHER_LBS]
      ,prop.[TOTAL_PROPPANT_LBS]
      ,prop.[FLUID_WATER_GALS]
      ,prop.[FLUID_SLICK_WATER_GALS]
      ,prop.[FLUID_SALT_WATER_GALS]
      ,prop.[FLUID_FOAM_GALS]
      ,prop.[FLUID_OIL_GALS]
      ,prop.[FLUID_POTASSIUM_CHLORIDE_GALS]
      ,prop.[FLUID_SURFACTANT_GALS]
      ,prop.[FLUID_EMULSION_GALS]
      ,prop.[N2_CO2_GAS_GALS]
      ,prop.[ACID_GALS]
      ,prop.[GEL_X_LINK_GALS]
      ,prop.[FLUID_EXPLOSIVE_GALS]
      ,prop.[FLUID_OTHER_GALS]
      ,prop.[TOTAL_FLUID_GALS]
      ,prop.[TOTAL_PROPPANT_LBS_OR_TOTAL_FLUID_GAL]
      ,prop.[SURFACE_TOWNSHIP_DIRECTION]
      ,prop.[SURFACE_TOWNSHIP_NUMBER]
      ,prop.[SURFACE_RANGE_DIRECTION]
      ,prop.[SURFACE_RANGE_NUMBER]
      ,prop.[SURFACE_SECTION_NUMBER]
      ,prop.[SURFACE_SECTION_TYPE]
      ,prop.[SURFACE_SPOT]
      ,prop.[SURFACE_MERIDIAN_NAME]
      ,prop.[SURFACE_REMARK]
      ,prop.[SURFACE_FOOTAGE_NORTH_SOUTH]
      ,prop.[SURFACE_FOOTAGE_NORTH_SOUTH_START_LINE]
      ,prop.[SURFACE_FOOTAGE_EAST_WEST]
      ,prop.[SURFACE_FOOTAGE_EAST_WEST_START_LINE]
      ,prop.[SURFACE_FOOTAGE_REFERENCE_NAME]
      ,prop.[BH_TOWNSHIP_DIRECTION]
      ,prop.[BH_TOWNSHIP_NUMBER]
      ,prop.[BH_RANGE_DIRECTION]
      ,prop.[BH_RANGE_NUMBER]
      ,prop.[BH_SECTION_NUMBER]
      ,prop.[BH_SECTION_TYPE]
      ,prop.[BH_SPOT]
      ,prop.[BH_MERIDIAN_NAME]
      ,prop.[BH_REMARK]
      ,prop.[BH_FOOTAGE_NORTH_SOUTH]
      ,prop.[BH_FOOTAGE_NORTH_SOUTH_START_LINE]
      ,prop.[BH_FOOTAGE_EAST_WEST]
      ,prop.[BH_FOOTAGE_EAST_WEST_START_LINE]
      ,prop.[BH_FOOTAGE_REFERENCE_NAME]
	  ,play.[EIA_PLAY] AS [EIA_PLAY_NAME]
FROM
	[Upstream].[UV_AC_PROP_AT] prop	
INNER JOIN
	[Upstream].[RefWell_PlayByStateCounty] play
ON
	(prop.STATE_NAME = play.State OR 
		(SELECT statelookup.[New_State] FROM 
			[Upstream].[RefWell_State] statelookup 
		WHERE statelookup.State = prop.STATE_NAME) = play.State) AND
	prop.COUNTY_NAME = play.County