CREATE TABLE [StageRystad].[WellHeader] (
    [Id]                                    BIGINT             NOT NULL,
    [API_Number]                            NVARCHAR (4000)    NULL,
    [Well_Name]                             NVARCHAR (4000)    NULL,
    [Texas_District]                        NVARCHAR (4000)    NULL,
    [Lease_Name]                            NVARCHAR (4000)    NULL,
    [Lease_Number]                          INT                NULL,
    [Number_of_Wells_in_Lease]              INT                NULL,
    [Formation]                             NVARCHAR (4000)    NULL,
    [Field]                                 NVARCHAR (4000)    NULL,
    [Well_Direction]                        NVARCHAR (4000)    NULL,
    [Well_Type]                             NVARCHAR (4000)    NULL,
    [Spud_Date]                             DATETIMEOFFSET (7) NULL,
    [Completion_Date]                       DATETIMEOFFSET (7) NULL,
    [Initial_Test_Date]                     DATETIMEOFFSET (7) NULL,
    [Production_Start_Date]                 DATETIMEOFFSET (7) NULL,
    [Peak_Production_Date]                  DATETIMEOFFSET (7) NULL,
    [Permit_Issue_Date]                     DATETIMEOFFSET (7) NULL,
    [Last_Production_Date]                  DATETIMEOFFSET (7) NULL,
    [Refracturing_Date]                     DATETIMEOFFSET (7) NULL,
    [Well_Status]                           NVARCHAR (4000)    NULL,
    [Last_Update_Date]                      DATETIMEOFFSET (7) NULL,
    [Frac_Focus_Version]                    NVARCHAR (4000)    NULL,
    [Pad_ID]                                NVARCHAR (4000)    NULL,
    [Reported_Production_Months]            SMALLINT           NULL,
    [Reported_Well_Type]                    NVARCHAR (4000)    NULL,
    [First_Record_Date]                     DATETIMEOFFSET (7) NULL,
    [Number_of_Casing_Strings_Group]        NVARCHAR (4000)    NULL,
    [Number_of_Casing_Strings_Category]     NVARCHAR (4000)    NULL,
    [Pad_State]                             NVARCHAR (4000)    NULL,
    [Parent_Child_Classification]           NVARCHAR (4000)    NULL,
    [Pad_Sequence_Completion]               SMALLINT           NULL,
    [Pad_Segment_Completion]                SMALLINT           NULL,
    [Pad_Sequence_Spud]                     SMALLINT           NULL,
    [Pad_Segment_Spud]                      SMALLINT           NULL,
    [Land_Type]                             NVARCHAR (4000)    NULL,
    [Choke_Size]                            NVARCHAR (4000)    NULL,
    [Well_Spacing]                          REAL               NULL,
    [Longitude]                             FLOAT (53)         NULL,
    [Latitude]                              FLOAT (53)         NULL,
    [Reported_24_h_Test_Water_Production]   REAL               NULL,
    [Reported_24_h_Test_Production]         REAL               NULL,
    [Maximum_Treatment_Pressure]            REAL               NULL,
    [Maximum_Treatment_Rate]                REAL               NULL,
    [Proppant__Thousand_pounds_]            FLOAT (53)         NULL,
    [Ground_Level]                          REAL               NULL,
    [Total_Measured_Depth]                  REAL               NULL,
    [True_Vertical_Depth]                   REAL               NULL,
    [Lateral_Length]                        REAL               NULL,
    [Drilling_Days]                         REAL               NULL,
    [Frac_Stages__Count_]                   REAL               NULL,
    [BottomHole_Longitude]                  FLOAT (53)         NULL,
    [BottomHole_Latitude]                   FLOAT (53)         NULL,
    [Surface_Lateral_Projection]            FLOAT (53)         NULL,
    [Upper_Perforation]                     REAL               NULL,
    [Lower_Perforation]                     REAL               NULL,
    [Perforated_Length]                     REAL               NULL,
    [Distance_Closest_Well_2D__Feet_]       FLOAT (53)         NULL,
    [Distance_Closest_Well_3D__Feet_]       FLOAT (53)         NULL,
    [FK_NASGeography]                       BIGINT             NULL,
    [FK_NASOperator]                        BIGINT             NULL,
    [RE_ID]                                 NVARCHAR (4000)    NULL,
    [Asset]                                 NVARCHAR (4000)    NULL,
    [FK_NASDataQuality]                     BIGINT             NULL,
    [Light_Oil_Content_Group]               NVARCHAR (4000)    NULL,
    [Light_Oil_Content_Category]            NVARCHAR (4000)    NULL,
    [Light_Oil_Content_Detail]              NVARCHAR (4000)    NULL,
    [Initial_Production_Group]              NVARCHAR (4000)    NULL,
    [Initial_Production_Category]           NVARCHAR (4000)    NULL,
    [Initial_Production_Detail]             NVARCHAR (4000)    NULL,
    [FK_NASREAnalysis]                      BIGINT             NULL,
    [Spud_Date_Reporting_Group]             NVARCHAR (4000)    NULL,
    [Completion_Date_Reporting_Group]       NVARCHAR (4000)    NULL,
    [Production_Start_Date_Reporting_Group] NVARCHAR (4000)    NULL,
    [TVD_Group]                             NVARCHAR (4000)    NULL,
    [TVD_Category]                          NVARCHAR (4000)    NULL,
    [TVD_Detail]                            NVARCHAR (4000)    NULL,
    [Well_Origin]                           NVARCHAR (4000)    NULL,
    [TMD_Group]                             NVARCHAR (4000)    NULL,
    [TMD_Category]                          NVARCHAR (4000)    NULL,
    [TMD_Detail]                            NVARCHAR (4000)    NULL,
    [Lateral_Length_Group]                  NVARCHAR (4000)    NULL,
    [Lateral_Length_Category]               NVARCHAR (4000)    NULL,
    [Lateral_Length_Detail]                 NVARCHAR (4000)    NULL,
    [Service_Provider]                      NVARCHAR (4000)    NULL,
    [Service_Provider_Confidence]           NVARCHAR (4000)    NULL,
    [Initial_Light_Oil_Content_Group]       NVARCHAR (4000)    NULL,
    [Initial_Light_Oil_Content_Category]    NVARCHAR (4000)    NULL,
    [Initial_Light_Oil_Content_Detail]      NVARCHAR (4000)    NULL,
    [FK_NASBreakevenOilPrice]               BIGINT             NULL,
    [FK_NASBreakevenGasPrice]               BIGINT             NULL,
    [API_Group]                             NVARCHAR (4000)    NULL,
    [API_Category]                          NVARCHAR (4000)    NULL,
    [API_Detail]                            NVARCHAR (4000)    NULL,
    [Gas_Gatherer]                          NVARCHAR (4000)    NULL,
    [Liquids_Gatherer]                      NVARCHAR (4000)    NULL,
    [Proppant_Type_Group]                   NVARCHAR (4000)    NULL,
    [Proppant_Type_Category]                NVARCHAR (4000)    NULL,
    [Proppant_Type_Detail]                  NVARCHAR (4000)    NULL,
    [Life_Cycle_Group]                      NVARCHAR (4000)    NULL,
    [Life_Cycle_Category]                   NVARCHAR (4000)    NULL,
    [Life_Cycle_Detail]                     NVARCHAR (4000)    NULL,
    [Acreage_Grade_Group]                   NVARCHAR (4000)    NULL,
    [Acreage_Grade_Category]                NVARCHAR (4000)    NULL,
    [Acreage_Grade_Detail]                  NVARCHAR (4000)    NULL,
    [Frac_Job_Type_Group]                   NVARCHAR (4000)    NULL,
    [Frac_Job_Type_Category]                NVARCHAR (4000)    NULL,
    [Frac_Job_Type_Detail]                  NVARCHAR (4000)    NULL,
    [Proppant_Intensity_Group]              NVARCHAR (4000)    NULL,
    [Proppant_Intensity_Category]           NVARCHAR (4000)    NULL,
    [Proppant_Intensity_Detail]             NVARCHAR (4000)    NULL,
    [Fluid_Intensity_Group]                 NVARCHAR (4000)    NULL,
    [Fluid_Intensity_Category]              NVARCHAR (4000)    NULL,
    [Fluid_Intensity_Detail]                NVARCHAR (4000)    NULL,
    [FK_NASLocation]                        BIGINT             NULL,
    [Distance_3D_Group]                     NVARCHAR (4000)    NULL,
    [Distance_3D_Category]                  NVARCHAR (4000)    NULL,
    [Distance_3D_Detail]                    NVARCHAR (4000)    NULL,
    [TellurianUpdatedDate]                  DATETIME           DEFAULT (getdate()) NULL,
    [TellurianCreatedDate]                  DATETIME           DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_WellHeader] PRIMARY KEY CLUSTERED ([Id] ASC)
);

