CREATE TABLE [dbo].[WEL_TELLROYALTYONLYWELLS] (
    [OBJECTID_1]        INT              NOT NULL,
    [OBJECTID]          INT              NULL,
    [UWI]               NVARCHAR (20)    NULL,
    [SOURCE]            NVARCHAR (12)    NULL,
    [ACTIVITY_C]        NVARCHAR (12)    NULL,
    [API_NUMBER]        NVARCHAR (20)    NULL,
    [BASIN]             NVARCHAR (60)    NULL,
    [BH_LATITUD]        NUMERIC (38, 8)  NULL,
    [BH_LL_SOUR]        NVARCHAR (12)    NULL,
    [BH_LONGITU]        NUMERIC (38, 8)  NULL,
    [CLASS_FINA]        NVARCHAR (12)    NULL,
    [CLASS_FI_1]        NVARCHAR (60)    NULL,
    [CLASS_INIT]        NVARCHAR (12)    NULL,
    [CLASS_IN_1]        NVARCHAR (60)    NULL,
    [COUNTRY_NA]        NVARCHAR (60)    NULL,
    [COUNTY_NAM]        NVARCHAR (12)    NULL,
    [CURRENT_OP]        NVARCHAR (120)   NULL,
    [CURRENT__1]        NVARCHAR (60)    NULL,
    [CURRENT_ST]        NVARCHAR (12)    NULL,
    [DATE_ABAND]        DATETIME2 (7)    NULL,
    [DATE_COMPL]        DATETIME2 (7)    NULL,
    [DATE_FIRST]        DATETIME2 (7)    NULL,
    [DATE_FIR_1]        DATETIME2 (7)    NULL,
    [DATE_LAST_]        DATETIME2 (7)    NULL,
    [DATE_RIG_R]        DATETIME2 (7)    NULL,
    [DATE_SPUD]         DATETIME2 (7)    NULL,
    [DEPTH_TOTA]        NUMERIC (38, 8)  NULL,
    [DEPTH_TO_1]        NUMERIC (38, 8)  NULL,
    [DEPTH_TO_2]        NUMERIC (38, 8)  NULL,
    [DEPTH_TRUE]        NUMERIC (38, 8)  NULL,
    [DEPTH_WATE]        NVARCHAR (12)    NULL,
    [DEPTH_WA_1]        NUMERIC (38, 8)  NULL,
    [DEPTH_WHIP]        NUMERIC (38, 8)  NULL,
    [ELEVATION_]        NVARCHAR (12)    NULL,
    [ELEVATION1]        NUMERIC (38, 8)  NULL,
    [FIELD_NAME]        NVARCHAR (30)    NULL,
    [FORMATION_]        NVARCHAR (60)    NULL,
    [FORMATION1]        NVARCHAR (60)    NULL,
    [FORMATIO_1]        NVARCHAR (60)    NULL,
    [GROUND_ELE]        NUMERIC (38, 8)  NULL,
    [HOLE_DIREC]        NVARCHAR (12)    NULL,
    [IC_NUMBER]         NVARCHAR (20)    NULL,
    [LEASE_NAME]        NVARCHAR (60)    NULL,
    [MAP_SYMBOL]        NVARCHAR (60)    NULL,
    [OPERATOR_C]        NVARCHAR (120)   NULL,
    [OPERATOR_N]        NVARCHAR (60)    NULL,
    [OS_INDICAT]        NVARCHAR (12)    NULL,
    [PERMIT_DAT]        DATETIME2 (7)    NULL,
    [PERMIT_FIL]        NVARCHAR (240)   NULL,
    [PERMIT_NUM]        NVARCHAR (9)     NULL,
    [PERMIT_PHO]        NVARCHAR (30)    NULL,
    [PLAY_NAME]         NVARCHAR (60)    NULL,
    [PLAY_TYPE]         NVARCHAR (30)    NULL,
    [PRODFIT_80]        NVARCHAR (60)    NULL,
    [PRODFIT_FO]        NVARCHAR (60)    NULL,
    [PRODFIT_TO]        NVARCHAR (60)    NULL,
    [PROPOSED_B]        NUMERIC (38, 8)  NULL,
    [PROPOSED_1]        NVARCHAR (12)    NULL,
    [PROPOSED_2]        NUMERIC (38, 8)  NULL,
    [REGULATORY]        NVARCHAR (20)    NULL,
    [REGULATO_1]        NVARCHAR (20)    NULL,
    [REGULATO_2]        DATETIME2 (7)    NULL,
    [STATE_NAME]        NVARCHAR (60)    NULL,
    [STATUS_FIN]        NVARCHAR (12)    NULL,
    [SURFACE_LA]        NUMERIC (38, 8)  NULL,
    [SURFACE_LL]        NVARCHAR (12)    NULL,
    [SURFACE_LO]        NUMERIC (38, 8)  NULL,
    [WELL_NUMBE]        NVARCHAR (20)    NULL,
    [WELL_STATU]        NVARCHAR (12)    NULL,
    [ShapeLine_]        NUMERIC (38, 8)  NULL,
    [Shape]             [sys].[geometry] NULL,
    [GDB_GEOMATTR_DATA] VARBINARY (MAX)  NULL,
    CONSTRAINT [R408_pk] PRIMARY KEY CLUSTERED ([OBJECTID_1] ASC) WITH (FILLFACTOR = 75),
    CONSTRAINT [g371_ck] CHECK ([SHAPE].[STSrid]=(3857))
);


GO
CREATE SPATIAL INDEX [S371_idx]
    ON [dbo].[WEL_TELLROYALTYONLYWELLS] ([Shape])
    WITH  (
            BOUNDING_BOX = (XMAX = -10384681.5021305, XMIN = -10422317.9589988, YMAX = 3788425.40991919, YMIN = 3737404.55040635),
            CELLS_PER_OBJECT = 16
          );

