CREATE TABLE [dbo].[WEL_SONRIS_OGWELLS] (
    [OBJECTID]          INT              NOT NULL,
    [WELL_SERIA]        INT              NULL,
    [ORGANIZATI]        NVARCHAR (6)     NULL,
    [ORGOP_LINE]        INT              NULL,
    [WELL_CLASS]        NVARCHAR (5)     NULL,
    [WELL_NAME]         NVARCHAR (60)    NULL,
    [WELL_NUM]          NVARCHAR (7)     NULL,
    [TOWNSHIP]          NVARCHAR (3)     NULL,
    [EFFECTIVE_]        DATETIME2 (7)    NULL,
    [API_NUM]           NVARCHAR (14)    NULL,
    [OPERATION_]        NVARCHAR (5)     NULL,
    [PERMIT_DAT]        DATETIME2 (7)    NULL,
    [SPUD_DATE]         DATETIME2 (7)    NULL,
    [WELL_STATU]        NVARCHAR (5)     NULL,
    [WELL_STA_1]        DATETIME2 (7)    NULL,
    [ORIGINAL_C]        DATETIME2 (7)    NULL,
    [LAST_RECOM]        DATETIME2 (7)    NULL,
    [LAST_TEST_]        DATETIME2 (7)    NULL,
    [ORPHANED_F]        NVARCHAR (1)     NULL,
    [PRODUCT_TY]        NVARCHAR (5)     NULL,
    [CLASSIFICA]        NVARCHAR (3)     NULL,
    [UNIT_WELL_]        NVARCHAR (1)     NULL,
    [EXEMPT_29E]        NVARCHAR (1)     NULL,
    [FIELD_ID]          NVARCHAR (4)     NULL,
    [LEASE_NUM]         NVARCHAR (7)     NULL,
    [MUD_DENSIT]        NUMERIC (16, 5)  NULL,
    [USDW_VALUE]        INT              NULL,
    [AREA_USDW_]        INT              NULL,
    [SOURCE_ARE]        NVARCHAR (240)   NULL,
    [MAX_SIP]           INT              NULL,
    [SIP_ASSIGN]        DATETIME2 (7)    NULL,
    [SOURCE_OF_]        NVARCHAR (60)    NULL,
    [INJECTION_]        NUMERIC (6, 1)   NULL,
    [COMMENTS]          NVARCHAR (254)   NULL,
    [LOCATION]          NVARCHAR (240)   NULL,
    [SECTN]             NVARCHAR (3)     NULL,
    [MERIDIAN]          NVARCHAR (1)     NULL,
    [WELL_RANGE]        NVARCHAR (3)     NULL,
    [PARISH_COD]        NVARCHAR (5)     NULL,
    [SURFACE_LA]        NUMERIC (22, 9)  NULL,
    [SURFACE_LO]        NUMERIC (22, 9)  NULL,
    [MEASURED_D]        INT              NULL,
    [LEGEND]            NVARCHAR (12)    NULL,
    [DISTRICT_C]        NVARCHAR (5)     NULL,
    [INSPECTION]        DATETIME2 (7)    NULL,
    [INSPECTI_1]        NUMERIC (23, 5)  NULL,
    [SECTION]           NVARCHAR (3)     NULL,
    [INJECTION1]        INT              NULL,
    [LOG_REVIEW]        NVARCHAR (1)     NULL,
    [ORPHAN_STA]        NVARCHAR (5)     NULL,
    [ORPHAN_S_1]        DATETIME2 (7)    NULL,
    [FIELD_NAME]        NVARCHAR (60)    NULL,
    [ORG_OPER_N]        NVARCHAR (40)    NULL,
    [PARISH_NAM]        NVARCHAR (20)    NULL,
    [SCOUT_WELL]        NVARCHAR (5)     NULL,
    [SCOUT_REPO]        DATETIME2 (7)    NULL,
    [SCOUT_MEAS]        NUMERIC (28, 10) NULL,
    [SCOUT_TRUE]        NUMERIC (28, 10) NULL,
    [LUW_CODE]          NVARCHAR (6)     NULL,
    [LUW_TYPE_C]        NVARCHAR (5)     NULL,
    [LUW_NAME]          NVARCHAR (60)    NULL,
    [LW_REC_STA]        NVARCHAR (1)     NULL,
    [SURFACE__1]        NUMERIC (28, 10) NULL,
    [SURFACE__2]        NUMERIC (28, 10) NULL,
    [SURFACE_CO]        NVARCHAR (5)     NULL,
    [SURFACE_ZO]        NVARCHAR (1)     NULL,
    [SURFACE_UT]        NUMERIC (28, 10) NULL,
    [SURFACE__3]        NUMERIC (28, 10) NULL,
    [UPPER_PERF]        NVARCHAR (254)   NULL,
    [LOWER_PERF]        NVARCHAR (254)   NULL,
    [SANDS]             NVARCHAR (254)   NULL,
    [RESERVOIRS]        NVARCHAR (254)   NULL,
    [FORMATIONS]        NVARCHAR (254)   NULL,
    [HYPERLINK]         NVARCHAR (200)   NULL,
    [LEGEND_DES]        NVARCHAR (100)   NULL,
    [DIRWELL]           NVARCHAR (12)    NULL,
    [SCOUT_DETA]        NVARCHAR (254)   NULL,
    [MINERAL_IN]        NVARCHAR (1)     NULL,
    [STATE_INTE]        NVARCHAR (1)     NULL,
    [DOC_ACCESS]        NVARCHAR (254)   NULL,
    [STATE_ZONE]        NVARCHAR (10)    NULL,
    [Shape]             [sys].[geometry] NULL,
    [GDB_GEOMATTR_DATA] VARBINARY (MAX)  NULL,
    CONSTRAINT [R566_pk] PRIMARY KEY CLUSTERED ([OBJECTID] ASC) WITH (FILLFACTOR = 75),
    CONSTRAINT [g529_ck] CHECK ([SHAPE].[STSrid]=(3857))
);


GO
CREATE SPATIAL INDEX [S529_idx]
    ON [dbo].[WEL_SONRIS_OGWELLS] ([Shape])
    WITH  (
            BOUNDING_BOX = (XMAX = -9881076.0809, XMIN = -10866993.8627, YMAX = 3905715.6585, YMIN = 3247084.7393),
            CELLS_PER_OBJECT = 16
          );

